(function(w,doc){'use strict';
var M=w.COMMAND_MODEL,D=w.COMMAND_CONTENT,V=w.COMMAND_VISUALS,PACK=w.APP360_MARKET_OBJECTS,S,profile='',key='',memory={},bad={},storageOK=true,corrupt=false,view='library',selected=-1,running=false,busy=false,timer=null,runToken=0,player=new Audio(),audioPath='',audioState='idle',audioToken=0,audioTimer=null,reader,designer=null,paint='wall',previewDraft=null,output='',downloadURL='',pending='',offlineReady=false;
function $(id){return doc.getElementById(id);}function t(ar,en){return S.language==='en'?en:ar;}function label(p){return p[S.language];}function esc(s){return V.escape(s==null?'':s);}function b(cmd,text,value,cls,disabled){return '<button type="button" data-do="'+cmd+'"'+(value!==undefined?' data-value="'+esc(value)+'"':'')+' class="'+(cls||'')+'"'+(disabled?' disabled':'')+'>'+text+'</button>';}
function api(){try{if(w.parent!==w&&w.parent.APP360_FAMILY_SYNC)return w.parent.APP360_FAMILY_SYNC;}catch(e){}return w.APP360_FAMILY_SYNC||null;}
function identity(){var a=api(),p='';try{p=a&&a.getProfileKey?a.getProfileKey():'';}catch(e){}return p&&p!=='name:'?String(p):'local-guest';}
function coachAllowed(){var a=api(),s;try{s=a&&a.getSession?a.getSession():null;}catch(e){}return !(s&&s.room&&s.role==='guest'&&s.adminRole!=='assistant');}
function notify(text){$('notice').textContent=text;$('notice').style.display='block';clearTimeout(notify.timer);notify.timer=setTimeout(function(){$('notice').style.display='none';},4500);}
function storageLabel(){$('storageStatus').textContent=corrupt?t('الحفظ الأصلي لم يتغير؛ يمكنك تصديره من أدوات المربي.','Original data is unchanged; export it from coach tools.'):storageOK?'':t('حفظ مؤقت: صدّر طريقك قبل الإغلاق.','Temporary save: export your route before closing.');$('status').hidden=storageOK&&!corrupt&&view!=='coach';}
function save(){if(!S)return;S.view=view;S.designer=designer;memory[profile]=M.copy(S);if(!corrupt)try{localStorage.setItem(key,JSON.stringify(S));storageOK=true;}catch(e){storageOK=false;}storageLabel();}
function stopAudio(){audioToken++;clearTimeout(audioTimer);player.onended=player.onerror=player.onloadedmetadata=null;try{player.pause();}catch(e){}audioState='idle';audioPath='';if(reader)reader.stop();$('stopAudioBtn').hidden=true;}
function pause(quiet){running=false;busy=false;runToken++;clearTimeout(timer);stopAudio();if(S&&S.draft&&view==='play')save();if(!quiet)render();}
function load(p){pause(true);profile=p;key='app360:a4-command-path:schema-1:'+encodeURIComponent(p);S=M.blank();designer=null;corrupt=!!bad[p];storageOK=!corrupt;var raw='';if(memory[p]){raw=memory[p];}else try{raw=localStorage.getItem(key)||'';}catch(e){storageOK=false;}if(raw)try{S=M.restore(raw,p);designer=raw.designer?M.map(raw.designer):typeof raw==='string'&&JSON.parse(raw).designer?M.map(JSON.parse(raw).designer):null;}catch(e){corrupt=true;bad[p]=true;storageOK=false;designer=null;}view=S.view;selected=-1;previewDraft=null;output='';pending='';render();}
function syncFocus(){var a=api(),enabled=S&&S.reading_focus!==false,f;try{f=a&&a.getReadingFocusState?a.getReadingFocusState():null;if(f)enabled=f.enabled;}catch(e){}if(reader)reader.setEnabled(enabled);var box=$('coachReadingFocus');if(box){box.checked=enabled;box.disabled=!coachAllowed()||!!(f&&!f.canManage);}}
function say(k,done){stopAudio();if(!S.sound){if(done)done();return;}var text=D.phrases[k];if(!text){if(done)done();return;}var path='audio/'+S.language+'-'+k+'.mp3',token=audioToken,finished=false;
function finish(failed){if(finished||token!==audioToken)return;finished=true;clearTimeout(audioTimer);player.onended=player.onerror=player.onloadedmetadata=null;audioState=failed?'error':'idle';if(reader)reader.stop();$('stopAudioBtn').hidden=true;if(failed)notify(t('الصوت غير متاح الآن؛ الأوامر والصور تعمل.','Sound is unavailable now; commands and pictures still work.'));if(done)done();}
audioPath=path;audioState='loading';player.src=path;player.onended=function(){finish(false);};player.onerror=function(){finish(true);};player.onloadedmetadata=function(){clearTimeout(audioTimer);audioTimer=setTimeout(function(){finish(true);},Math.max(5000,(player.duration||4)*1000+5000));};audioTimer=setTimeout(function(){finish(true);},9000);try{var promise=player.play();if(promise&&promise.then)promise.then(function(){if(token!==audioToken)return;audioState='playing';reader.follow(path);$('stopAudioBtn').hidden=false;}).catch(function(){finish(true);});else{audioState='playing';reader.follow(path);$('stopAudioBtn').hidden=false;}}catch(e){finish(true);}}
function instruction(k){var path='audio/'+S.language+'-'+k+'.mp3';return '<div class="instruction"><p>'+w.APP360_READ_ALONG.markup(label(D.phrases[k]),path)+'</p>'+b('read',t('أسمع','Listen'),k)+'</div>';}
function asset(id){return PACK.items.filter(function(p){return p.id===id;})[0];}
function allMaps(){return D.maps.concat(S.maps);}function find(id){return allMaps().filter(function(m){return m.id===id;})[0];}
function board(m,pos,pred,trace,interactive,mini){return V.board(m,pos,pred||[],trace||[],{interactive:interactive,mini:mini,lang:S.language,label:label(m.title)});}
function commandLabel(op){return {n:t('أعلى','Up'),e:t('يمين','Right'),s:t('أسفل','Down'),w:t('يسار','Left'),f:t('تقدم','Forward'),l:t('در يساراً','Turn left'),r:t('در يميناً','Turn right'),repeat:t('تكرار','Repeat'),if:t('انظر أمامك','Look ahead')}[op];}
function commandButton(cmd,c,i,cls,disabled){var text='<span class="symbol" aria-hidden="true">'+V.symbol(c.op)+'</span><small>'+esc(commandLabel(c.op))+'</small>';if(c.op==='repeat')text+='<strong>'+c.count+'×</strong><span class="repeat-body" dir="ltr">'+c.body.map(function(q){return V.symbol(q.op);}).join(' ')+'</span>';return b(cmd,text,i,'command '+(c.op==='repeat'?'repeat-item ':'')+(cls||''),disabled);}
function tape(d,readOnly){var last=d.result&&d.cursor>0?d.result.trace[d.cursor-1]:null,s='<div class="tape" aria-label="'+t('أوامري بالترتيب','My commands in order')+'">';if(!d.commands.length)s+='<span class="empty">'+t('ابدأ بأمر من الأزرار.','Start with a command button.')+'</span>';d.commands.forEach(function(c,i){s+=commandButton(readOnly?'read-command':'select',c,i,(selected===i&&!readOnly?'selected ':'')+(last&&last.index===i?'executing':''),busy&&!readOnly);});return s+'</div>';}
function library(){var s='<section class="panel intro"><div><h1>'+t('إلى أين يذهب الروبوت؟','Where will the robot go?')+'</h1><p>'+t('اختر خريطة، رتب الطريق، وجرب خطوة خطوة.','Choose a map, arrange a route, then try each step.')+'</p></div><img src="icon.svg" alt=""></section>'+instruction('library')+'<div class="levels">';D.levels.forEach(function(l){s+=b('level','<strong>'+esc(label(l.title))+'</strong><small>'+l.age+t(' سنوات تقريباً',' suggested ages')+'</small><small>'+D.maps.filter(function(m){return m.level===l.id;}).length+t(' خريطة',' maps')+'</small>',l.id,S.level===l.id?'selected':'');});s+='</div>';if(S.draft)s+='<section class="panel resume row spread"><strong>'+esc(label(S.draft.map.title))+'</strong>'+b('resume',t('أكمل طريقي','Continue my route'),undefined,'primary')+'</section>';s+='<div class="maps">';allMaps().filter(function(m){return m.level===S.level;}).forEach(function(m){s+=b('open',board(m,m.start,[],[],false,true)+'<strong>'+esc(label(m.title))+'</strong>',m.id,'map-card');});return s+'</div>'+b('demo',t('أشاهد مثالاً منفصلاً','Watch a separate example'))+' '+b('designer',t('أصنع خريطة لصديقي','Make a map for a friend'));}
function archiveAttempt(d){if(d.result&&d.cursor){var h={commands:M.copy(d.commands),result:M.copy(d.result),prediction:M.copy(d.prediction),assistance:d.assistance};if(!d.history.length||JSON.stringify(d.history[d.history.length-1])!==JSON.stringify(h)){d.history.push(h);d.history=d.history.slice(-12);}}}
function open(id){var m=find(id);if(!m)return false;pause(true);if(S.draft){S.recent.push(M.artifact(S.draft));S.recent=S.recent.slice(-12);}S.draft=M.start(m,profile);S.draft.assistance=S.support;S.level=m.level;selected=-1;handle.replacing=false;go('play');var opened=S.draft;say('goal-'+m.goal_asset,function(){if(S.draft===opened&&view==='play')say('predict');});return true;}
function go(v){pause(true);handle.replacing=false;handle.replacing=false;view=v;pending='';output='';if(v!=='demo')previewDraft=null;if(v==='designer'&&!designer)designer=newMap();save();render();w.scrollTo(0,0);if(v!=='library')try{if(!history.state||!history.state.commandPath)history.pushState({commandPath:true},'',location.href);}catch(e){}}
function current(){return view==='demo'?previewDraft:S.draft;}
function position(d){return d.result&&d.cursor>0?d.result.trace[d.cursor-1].to:d.map.start;}
function playScreen(d,demo){var m=d.map,result=d.result&&d.cursor>=d.result.trace.length&&d.cursor>0,heading=label(m.title),s='<section class="panel '+(demo?'preview-mode':'')+'"><div class="row spread"><h1>'+esc(demo?t('مثال منفصل','Separate example'):heading)+'</h1>'+b(demo?'return-demo':'library',t('خرائط أخرى','Other maps'))+'</div>';
if(demo)s+='<p>'+t('هذا المثال لا يغيّر محاولتك المحفوظة.','This example keeps your own attempt unchanged.')+'</p>';
s+=instruction(d.phase==='predict'?'predict':'plan')+'<div class="work"><div class="map-side">'+board(m,position(d),d.prediction,d.result?d.result.trace.slice(0,d.cursor):[],!demo,false)+'<div class="controls">'+b('read',t('أسمع المقصد','Hear the destination'),'goal-'+m.goal_asset)+'</div><div class="legend"><span>'+t('توقعي','My prediction')+'</span><span>'+t('ما حدث','What happened')+'</span></div><div class="phase-line"><span class="badge">'+t('البداية','Start')+' ⚑</span><span class="badge">'+(m.mode==='absolute'?t('الأسهم تتبع الخريطة','Arrows follow the map'):t('السهم على رأس الروبوت يوضح اتجاهه','The robot arrow shows its direction'))+'</span></div></div><div class="plan-side">';
if(d.phase==='predict'){s+='<h2>'+t('أتوقع الطريق','Predict the route')+'</h2><p class="tap-hint">'+t('المس مربعاً بجانب البداية ثم المربع الذي يليه.','Touch a square beside the start, then the next square.')+'</p><div class="controls">'+b('prediction-undo',t('أرجع مربعاً','Undo a square'),undefined,'',!d.prediction.length)+b('prediction-clear',t('أمسح توقعي','Clear prediction'))+'</div>'+b('plan',t('أرتب أوامري','Arrange commands'),undefined,'primary')+' '+b('skip-predict',t('أكتشف بالمشاهدة','Discover by watching'));
}else{s+='<h2>'+t('أوامري','My commands')+'</h2><div class="palette">';(m.mode==='absolute'?['n','e','s','w']:['f','l','r']).forEach(function(op){s+=commandButton('add',{op:op},op,'',busy||demo);});if(m.level===3)s+=commandButton('add',{op:'if'},'if','',busy||demo);s+='</div>';if(m.level===3)s+='<p class="tools-note">'+esc(label(D.phrases['if']))+'</p>';s+=tape(d,false);
if(selected>=0&&!demo)s+='<div class="controls">'+b('move-command',t('أقدّم البطاقة','Move earlier'),'-1','',busy||selected===0)+b('move-command',t('أؤخر البطاقة','Move later'),'1','',busy||selected>=d.commands.length-1)+b('delete-command',t('أزيل هذه البطاقة','Remove this card'),undefined,'danger',busy)+b('replace-help',t('أبدلها: المس أمراً','Replace: choose a command'),undefined,'',busy)+'</div>';
if(m.level===3&&!demo)s+='<div class="controls">'+b('group',t('أكرر آخر بطاقتين','Repeat the last two cards'),undefined,'',busy||d.commands.length<2)+b('repeat-count',t('أغير عدد التكرار','Change repeat count'),undefined,'',busy||selected<0||d.commands[selected].op!=='repeat')+b('ungroup',t('أفك مجموعة التكرار','Expand repeat group'),undefined,'',busy||selected<0||d.commands[selected].op!=='repeat')+'</div>';
s+='<div class="controls">'+b('step',t('خطوة واحدة','One step'),undefined,'primary',busy||!d.commands.length)+b(running||busy?'pause':'run',running||busy?t('إيقاف مؤقت','Pause'):t('شغّل الطريق','Run route'),undefined,'primary',!d.commands.length)+b('restart',t('من البداية','From start'),undefined,'',busy)+b('clear-tape',t('أبدأ أوامر جديدة','Clear commands'),undefined,'',busy||demo)+'</div><div class="phase-line"><span class="badge">'+t('خطوات شاهدتها: ','Steps watched: ')+d.cursor+'</span>'+b('predict-again',t('أراجع توقعي','Review prediction'),undefined,'',busy||demo)+'</div>';
if(result){s+='<div class="result '+(d.result.status==='blocked'?'blocked':'')+'"><h3>'+esc(label(D.phrases[d.result.status]||D.phrases.away))+'</h3>';if(d.prediction.length){var movement=d.result.trace.filter(function(q){return !M.equal(q.from,q.to);}).map(function(q){return{x:q.to.x,y:q.to.y};}),same=JSON.stringify(movement)===JSON.stringify(d.prediction);s+='<p>'+t(same?'طابقت الخطوات المرسومة توقعي.':'الطريق الذي شاهدته مختلف عن توقعي. نحتفظ بكليهما.',same?'The observed moves matched my prediction.':'The observed route differed from my prediction. We keep both.')+'</p>';}s+='</div><div class="controls">'+b('hint',t('أفحص أول اختلاف','Look at the first difference'),undefined,'',demo)+b('save-route',d.saved?t('طريقي محفوظ ✓','My route is saved ✓'):t('أحفظ طريقي','Save my route'),undefined,'primary',d.saved||demo)+b('print',t('أطبع الطريق والبطاقات','Print route and cards'))+'</div>';if(!demo)s+='<div class="reflection row">'+b('reflect',t('غيرت أمراً','I changed a command'),'changed',d.reflection==='changed'?'selected':'')+b('reflect',t('أجرب طريقاً آخر','I will try another route'),'another',d.reflection==='another'?'selected':'')+b('reflect',t('أطلب مساعدة','I ask for help'),'help',d.reflection==='help'?'selected':'')+'</div>';}
}
s+='</div></div>';if(d.phase!=='predict')s+='<details><summary>'+t('أثر التنفيذ ومحاولاتي','Execution trace and attempts')+'</summary><ol class="trace-list">'+(d.result?d.result.trace.slice(0,d.cursor):[]).map(function(q){return '<li>'+esc(commandLabel(q.op))+(q.op==='if'?' → '+esc(commandLabel(q.effective)):'')+' · ('+q.from.x+','+q.from.y+') → ('+q.to.x+','+q.to.y+')'+(q.blocked?' · '+t('توقف','stopped'):'')+'</li>';}).join('')+'</ol><p>'+t('محاولات قبل التعديل: ','Attempts before editing: ')+d.history.length+'</p></details>';
if(!demo)s+='<details><summary>'+t('أدوات المربي لهذه الخريطة','Coach tools for this map')+'</summary>'+b('demo',t('مثال منفصل','Separate example'))+' '+b('export-current',t('أصدر نسخة','Export a copy'))+' '+b('print',t('بطاقات للواقع','Cards for real play'))+'<p class="muted">'+t('استخدم البطاقات على طاولة أو ضمن مساحة آمنة مع المرافق.','Use the cards on a table or in a safe space with a coach.')+'</p></details>';return s+'</section>';}
function edit(){var d=current();pause(true);archiveAttempt(d);d.result=null;d.cursor=0;d.phase='plan';d.saved=false;save();}
function startExecution(){var d=current();if(!d||!d.commands.length)return false;if(!d.result){d.result=M.execute(d.map,d.commands);d.cursor=0;}if(d.cursor>=d.result.trace.length){archiveAttempt(d);d.cursor=0;}d.phase='run';return true;}
function advance(auto){var d=current();if(!d||!d.result||d.cursor>=d.result.trace.length)return;busy=true;running=auto;var token=++runToken,step=d.result.trace[d.cursor];render();say(step.effective,function(){if(token!==runToken||d!==current())return;busy=false;d.cursor++;if(d.cursor>=d.result.trace.length){running=false;d.phase='review';archiveAttempt(d);save();render();say(d.result.status);return;}save();render();if(auto){running=true;timer=setTimeout(function(){if(token===runToken)advance(true);},550);}});}
function hint(){var d=S.draft,index=d.result?d.result.debug_index:null,n=0;if(index===null&&d.result)d.result.trace.some(function(q){if(M.equal(q.from,q.to))return false;var p=d.prediction[n++];if(p&&!M.equal(p,q.to)){index=q.index;return true;}return false;});selected=index===null?0:index;render();say('hint');}
function newMap(){return {id:'custom-'+Date.now(),size:4,start:{x:0,y:3,dir:0},goal:{x:3,y:0},walls:[],title:{ar:'خريطتي الجديدة',en:'My new map'},mode:'relative',level:2,goal_asset:'book',starter:[]};}
function designerScreen(){var m=designer,s='<section class="panel fields"><h1>'+t('خريطة لصديقي','A map for a friend')+'</h1>'+instruction('designer')+'<div class="work"><div class="map-side"><div class="designer-tools">';['start','goal','wall','erase'].forEach(function(k){s+=b('paint',t({start:'بداية ⚑',goal:'مقصد',wall:'حاجز',erase:'إزالة'}[k],{start:'Start ⚑',goal:'Goal',wall:'Barrier',erase:'Erase'}[k]),k,paint===k?'selected':'');});s+='</div>'+board(m,m.start,[],[],true,false)+'<div class="controls">'+b('rotate-start',t('أدير الروبوت','Rotate robot'))+' '+b('size',t('أغير حجم الخريطة','Change map size'))+'</div></div><div class="plan-side"><label for="mapAr">'+t('اسم عربي اختياري','Optional Arabic title')+'</label><input id="mapAr" maxlength="100" value="'+esc(m.title.ar)+'"><label for="mapEn">'+t('اسم إنجليزي اختياري','Optional English title')+'</label><input id="mapEn" maxlength="100" value="'+esc(m.title.en)+'"><label for="mapMode">'+t('نوع الأوامر','Command type')+'</label><select id="mapMode"><option value="absolute"'+(m.mode==='absolute'?' selected':'')+'>'+t('أسهم الخريطة','Map arrows')+'</option><option value="relative"'+(m.mode==='relative'?' selected':'')+'>'+t('تقدم ودوران','Forward and turn')+'</option></select><label>'+t('صورة المقصد','Destination picture')+'</label><div class="targets">';['book','ball','apple','bear','cat','car'].forEach(function(id){var p=asset(id);s+=b('target','<img src="../../../'+p.image+'" alt="'+esc(p[S.language])+'">'+esc(p[S.language]),id,m.goal_asset===id?'selected':'');});s+='</div><div class="controls">'+b('test-map',t('أختبر خريطتي','Test my map'),undefined,'primary')+b('store-map',t('أحفظ لغزاً لصديقي','Save a puzzle'),undefined,'primary')+b('new-map',t('خريطة جديدة','New map'))+'</div><p class="muted">'+t('نفحص وجود طريق للمقصد قبل حفظ اللغز. لا نعرض حله للطفل.','We check that a route exists before saving. The solution is not shown to the child.')+'</p></div></div></section>';return s;}
function gallery(){var s='<section class="panel row spread"><h1>'+t('طرقي المحفوظة','My saved routes')+'</h1>'+b('export-all',t('أصدر طرقي وخرائطي','Export routes and maps'))+'</section><div class="maps">';if(!S.saved.length)s+='<section class="panel"><p>'+t('احفظ طريقاً بعد تجربته لتراه هنا.','Save a route after trying it to see it here.')+'</p>'+b('library',t('أختار خريطة','Choose a map'))+'</section>';S.saved.forEach(function(d){s+='<article class="panel saved-card">'+board(d.map,d.map.start,[],[],false,true)+'<h2>'+esc(label(d.map.title))+'</h2><p>'+t('أوامر: ','Commands: ')+d.commands.length+' · '+esc(label(D.phrases[d.result&&d.result.status]||D.phrases.away))+'</p><div class="row">'+b('open-saved',t('أجرب نسخة','Try a copy'),d.id)+b('print-saved',t('أطبع','Print'),d.id)+b('delete-saved',pending===d.id?t('أؤكد الحذف','Confirm delete'):t('أحذف','Delete'),d.id,'danger')+'</div></article>';});s+='</div><section class="panel"><h2>'+t('ألغازي','My puzzles')+'</h2>';S.maps.forEach(function(m){s+='<div class="row"><strong>'+esc(label(m.title))+'</strong>'+b('open',t('أجرب','Try'),m.id)+b('edit-map',t('أعدل نسخة','Edit a copy'),m.id)+b('delete-map',pending===m.id?t('تأكيد الحذف','Confirm delete'):t('أحذف','Delete'),m.id,'danger')+'</div>';});return s+'</section><details class="panel"><summary>'+t('استيراد نسخة خاصة بي','Import my own copy')+'</summary><input id="importFile" type="file" accept=".json,application/json"></details>';}
function coach(){if(!coachAllowed())return '<section class="panel"><p>'+t('إعداد المربي متاح للمسؤول والمساعد.','Coach settings are for the owner and assistant.')+'</p>'+b('library',t('أكمل اللعب','Continue playing'))+'</section>';var s='<section class="panel fields"><h1>'+t('مكتب المربي','Coach desk')+'</h1><p>'+t('اسأل: ماذا توقعت؟ أين اختلف الطريق؟ ما الأمر الواحد الذي نغيره؟','Ask: What did you predict? Where did the route differ? Which single command could we change?')+'</p><label><input id="coachReadingFocus" type="checkbox">'+t('تظليل الكلمات مع النطق','Highlight spoken words')+'</label><p class="muted">'+t('إيقاف التظليل يبقي الصوت ويشارك اختيار الجلسة عند توفرها.','Disabling highlighting keeps sound and follows family session controls when available.')+'</p><label for="support">'+t('المساندة','Support')+'</label><select id="support"><option value="together"'+(S.support==='together'?' selected':'')+'>'+t('نفعل معاً','Together')+'</option><option value="independent"'+(S.support==='independent'?' selected':'')+'>'+t('الطفل يختار والمربي حاضر','Child chooses; coach present')+'</option></select><label for="privateNote">'+t('ملاحظة خاصة لا تدخل التصدير','Private note excluded from exports')+'</label><textarea id="privateNote" maxlength="1000">'+esc(S.note)+'</textarea><div class="controls">'+b('family',t('جلسة العائلة','Family session'))+' '+b('demo',t('مثال تعليمي منفصل','Separate demonstration'))+' '+b('print-guide',t('ورقة وبطاقات للواقع','Real-play sheet and cards'))+'</div><p class="tools-note">'+t('بديل الواقع: مساحة آمنة محددة أو لوحة على طاولة. دون سرعة إلزامية أو مقارنة بين الأطفال. المستويات اقتراحات استعداد وجميعها متاحة.','Real-play alternative: a bounded safe space or a table board. No required speed or comparison between children. Levels are readiness suggestions and all are open.')+'</p></section><details class="panel"><summary>'+t('المحاولات الأخيرة','Recent attempts')+'</summary>';S.recent.forEach(function(d,i){s+='<div class="row">'+esc(label(d.map.title))+' '+b('recent',t('أفتح نسخة','Open a copy'),i)+'</div>';});s+='</details>';if(corrupt)s+='<section class="panel"><p>'+t('النسخة الأصلية لم تتغير. صدّرها قبل بدء حفظ جديد إن أردت.','The original remains unchanged. Export it before starting a new save if wanted.')+'</p>'+b('raw-backup',t('أصدر الأصل','Export original'))+' '+b('reset-corrupt',pending==='corrupt'?t('أؤكد حفظاً جديداً','Confirm new save'):t('أبدأ حفظاً جديداً','Start new save'),undefined,'danger')+'</section>';return s;}
function render(){if(!S)return;doc.documentElement.lang=S.language;doc.documentElement.dir=S.language==='ar'?'rtl':'ltr';$('brandTitle').textContent=t('مسار الأوامر','Command paths');$('profileLabel').textContent=t('مدرسة العائلة 360 · 4–8','Family School 360 · 4–8');$('languageBtn').textContent=S.language==='ar'?'English':'عربي';$('voiceBtn').textContent=t('الصوت','Sound');$('voiceBtn').setAttribute('aria-pressed',String(S.sound));$('voiceBtn').className=S.sound?'selected':'';$('app360HomeBtn').textContent=t('الرئيسية','Home');$('footerText').textContent=t('أخطط، أجرب، وأغير فكرتي.','Plan, try, and change my idea.');var nav={navPlay:['library','خرائطي','Maps'],navGallery:['gallery','طرقي','Routes'],navDesign:['designer','أصنع خريطة','Make a map'],navCoach:['coach','للمربي','Coach']};Object.keys(nav).forEach(function(id){$(id).textContent=t(nav[id][1],nav[id][2]);$(id).className=view===nav[id][0]?'active':'';});var html=view==='play'?playScreen(S.draft,false):view==='demo'?playScreen(previewDraft,true):view==='gallery'?gallery():view==='designer'?designerScreen():view==='coach'?coach():library();if(output)html+='<section class="panel output"><h2>'+t('نسختك للتصدير','Your export copy')+'</h2><p>'+t('يمكنك تنزيل الملف أو نسخ النص.','Download the file or copy the text.')+'</p><a href="'+esc(downloadURL)+'" download="command-paths.json">'+t('تنزيل JSON','Download JSON')+'</a><textarea readonly aria-label="JSON">'+esc(output)+'</textarea>'+b('close-output',t('أغلق','Close'))+'</section>';$('app').innerHTML=html;storageLabel();syncFocus();if(reader)reader.refresh();}
function exportValue(value){pause(true);output=typeof value==='string'?value:JSON.stringify(value,null,2);try{if(downloadURL)w.URL.revokeObjectURL(downloadURL);downloadURL=w.URL.createObjectURL(new Blob([output],{type:'application/json'}));}catch(e){downloadURL='data:application/json;charset=utf-8,'+encodeURIComponent(output);}render();}
function importFile(file){if(!file)return;if(file.size>1000000){notify(t('الملف أكبر من حزمة الطرق المدعومة.','This file exceeds the supported route bundle.'));return;}var owner=profile,r=new FileReader();r.onload=function(){if(owner!==profile)return;try{var n=M.importData(JSON.parse(r.result),profile);if(S.saved.length+n.saved.length>50||S.maps.length+n.maps.length>30)throw Error('capacity');S.saved=S.saved.concat(n.saved);n.maps.forEach(function(m){m.id='custom-'+Date.now()+'-'+Math.random().toString(36).slice(2,7);S.maps.push(m);});if(n.draft)S.recent.push(n.draft);S.recent=S.recent.slice(-12);save();render();notify(t('استوردنا نسخاً مستقلة.','Imported independent copies.'));}catch(e){notify(t('لم يتغير حفظك؛ الملف غير صالح أو تجاوز الحد.','Your save is unchanged; this file is invalid or exceeds limits.'));}};r.onerror=function(){notify(t('تعذر قراءة الملف.','Could not read the file.'));};r.readAsText(file);}
function print(d){pause(true);var m=d.map;$('printCard').innerHTML='<h1>'+esc(label(m.title))+'</h1><p>'+t('البداية ⚑ · اتبع الأوامر خطوة خطوة في مساحة آمنة مع المربي.','Start ⚑ · Follow commands step by step in a safe space with a coach.')+'</p>'+board(m,m.start,d.prediction,d.result?d.result.trace.slice(0,d.cursor):[],false,false)+tape(d,true)+'<h2>'+t('بطاقات أوامر للقص','Command cards to cut out')+'</h2><div class="row">'+(m.mode==='absolute'?['n','e','s','w']:['f','l','r']).map(function(op){return commandButton('read-command',{op:op},0,'',false);}).join('')+'</div><p>'+t('توقعت: __________ شاهدت: __________ غيرت: __________','I predicted: __________ I observed: __________ I changed: __________')+'</p>';save();w.print();render();}
function tile(value){var a=value.split(':'),p={x:Number(a[0]),y:Number(a[1])};if(view==='designer'){var m=designer;if(paint==='start'){if(M.equal(p,m.goal)||M.blocked(m,p))return; m.start.x=p.x;m.start.y=p.y;}else if(paint==='goal'){if(M.equal(p,m.start)||M.blocked(m,p))return;m.goal=p;}else if(paint==='wall'){if(M.equal(p,m.start)||M.equal(p,m.goal)||M.blocked(m,p))return;m.walls.push(p);}else m.walls=m.walls.filter(function(q){return !M.equal(p,q);});save();render();return;}var d=S.draft;if(view!=='play'||!d||d.phase!=='predict')return;var last=d.prediction.length?d.prediction[d.prediction.length-1]:d.map.start;if(d.prediction.length>=25||Math.abs(last.x-p.x)+Math.abs(last.y-p.y)!==1){notify(t('اختر مربعاً ملاصقاً لآخر مربع.','Choose a square beside the last square.'));return;}d.prediction.push(p);d.saved=false;save();render();}
function handle(e){var node=e.target;while(node&&node!==doc&&!node.getAttribute('data-do'))node=node.parentNode;if(!node||node===doc)return;var cmd=node.getAttribute('data-do'),v=node.getAttribute('data-value'),d=current(),index;try{
if(cmd==='home'){pause(true);if(w.APP360_AI_SHELL)w.APP360_AI_SHELL.home();else location.href='../../../index.html';return;}
if(cmd==='language'){pause(true);S.language=S.language==='ar'?'en':'ar';save();render();return;}if(cmd==='sound'){pause(true);S.sound=!S.sound;save();render();return;}if(cmd==='stop'||cmd==='pause'){pause();return;}if(cmd==='read'){say(v);return;}
if(['library','gallery','designer','coach'].indexOf(cmd)>=0){go(cmd);return;}if(cmd==='level'){pause(true);S.level=Number(v);save();render();return;}if(cmd==='open'){open(v);return;}if(cmd==='resume'){go('play');return;}
if(cmd==='demo'){pause(true);previewDraft=M.start({id:'demo',size:3,start:{x:0,y:1,dir:1},goal:{x:2,y:1},walls:[],title:{ar:'مثال مستقل',en:'Separate example'},mode:'absolute',level:1,goal_asset:'book'},profile);previewDraft.commands=[{op:'e'},{op:'e'}];previewDraft.phase='plan';view='demo';render();say('demo');return;}if(cmd==='return-demo'){previewDraft=null;go(S.draft?'play':'library');return;}
if(cmd==='tile'){tile(v);return;}if(cmd==='prediction-undo'){d.prediction.pop();save();render();return;}if(cmd==='prediction-clear'){d.prediction=[];save();render();return;}if(cmd==='plan'||cmd==='skip-predict'){d.prediction_skipped=cmd==='skip-predict';d.phase='plan';save();render();say('plan');return;}
if(cmd==='predict-again'){pause(true);d.phase='predict';save();render();say('predict');return;}
if(cmd==='select'){selected=Number(v);render();say(d.commands[selected].op);return;}if(cmd==='read-command'){if(d&&d.commands[Number(v)])say(d.commands[Number(v)].op);return;}
if(cmd==='add'){if(busy||view==='demo')return;var c={op:v},next=M.copy(d.commands);if(handle.replacing&&selected>=0)next[selected]=c;else{if(next.length>=32){notify(t('جرّب الطريق أو استخدم التكرار قبل إضافة أوامر.','Try the route or use repeats before adding more commands.'));return;}next.push(c);}M.program(next,d.map.mode,d.map.level);edit();d.commands=next;handle.replacing=false;selected=-1;save();render();say(v);return;}
if(cmd==='replace-help'){handle.replacing=true;notify(t('المس الأمر الجديد ليحل محل البطاقة المحددة.','Choose a new command to replace the selected card.'));return;}
if(cmd==='move-command'){if(busy||selected<0)return;index=selected+Number(v);if(index<0||index>=d.commands.length)return;edit();var moving=d.commands.splice(selected,1)[0];d.commands.splice(index,0,moving);selected=index;save();render();return;}
if(cmd==='delete-command'){if(busy||selected<0)return;edit();d.commands.splice(selected,1);selected=-1;save();render();return;}if(cmd==='clear-tape'){edit();d.commands=[];selected=-1;save();render();return;}
if(cmd==='group'){if(busy||d.commands.length<2)return;var body=d.commands.slice(-2);if(body.some(function(c){return c.op==='repeat';})){notify(t('اختر بطاقات بسيطة للتجميع.','Choose simple cards for a group.'));return;}var next=d.commands.slice(0,-2).concat([{op:'repeat',count:2,body:body}]);M.program(next,d.map.mode,d.map.level);edit();d.commands=next;selected=next.length-1;save();render();say('repeat');return;}
if(cmd==='repeat-count'){if(busy||selected<0||d.commands[selected].op!=='repeat')return;var old=d.commands[selected].count,nextCount=old===4?2:old+1,next=M.copy(d.commands);next[selected].count=nextCount;M.program(next,d.map.mode,d.map.level);edit();d.commands=next;save();render();say('repeat');return;}
if(cmd==='ungroup'){if(busy||selected<0||d.commands[selected].op!=='repeat')return;var group=d.commands[selected],expanded=[];for(var x=0;x<group.count;x++)expanded=expanded.concat(M.copy(group.body));var next=d.commands.slice(0,selected).concat(expanded,d.commands.slice(selected+1));M.program(next,d.map.mode,d.map.level);edit();d.commands=next;selected=-1;save();render();return;}
if(cmd==='step'||cmd==='run'){if(busy)return;if(startExecution()){save();advance(cmd==='run');}return;}if(cmd==='restart'){pause(true);archiveAttempt(d);d.cursor=0;d.phase='plan';save();render();return;}if(cmd==='hint'){hint();return;}
if(cmd==='save-route'){if(d.saved)return;if(!d.result||d.cursor!==d.result.trace.length||!d.cursor||view==='demo')return;if(S.saved.length>=50){notify(t('الدفتر ممتلئ؛ صدّر أو احذف نسخة قبل الحفظ.','The notebook is full; export or remove a copy before saving.'));return;}d.saved=true;S.saved.push(M.artifact(d));save();render();say('saved');try{doc.dispatchEvent(new CustomEvent('app360:command:saved',{detail:{map:d.map.id}}));}catch(e){var ev=doc.createEvent('Event');ev.initEvent('app360:command:saved',true,false);doc.dispatchEvent(ev);}return;}
if(cmd==='reflect'){d.reflection=v;save();render();return;}if(cmd==='open-saved'||cmd==='recent'){pause(true);var source=cmd==='recent'?S.recent[Number(v)]:S.saved.filter(function(q){return q.id===v;})[0];if(!source)return;S.draft=M.artifact(source);S.draft.id='copy-'+Date.now();S.draft.profile_ref=profile;S.draft.saved=false;go('play');return;}
if(cmd==='delete-saved'||cmd==='delete-map'){if(pending!==v){pending=v;render();return;}if(cmd==='delete-saved')S.saved=S.saved.filter(function(q){return q.id!==v;});else S.maps=S.maps.filter(function(q){return q.id!==v;});pending='';save();render();return;}
if(cmd==='new-map'){designer=newMap();paint='wall';save();render();return;}if(cmd==='paint'){paint=v;render();say(v);return;}if(cmd==='rotate-start'){designer.start.dir=(designer.start.dir+1)%4;save();render();say('rotation');return;}if(cmd==='size'){var n=designer.size===5?3:designer.size+1;designer.size=n;designer.start={x:0,y:n-1,dir:0};designer.goal={x:n-1,y:0};designer.walls=[];save();render();return;}if(cmd==='target'){designer.goal_asset=v;save();render();return;}
if(cmd==='test-map'||cmd==='store-map'){designer.title.ar=designer.title.ar||'خريطتي';designer.title.en=designer.title.en||'My map';var m=M.map(designer);if(!M.solve(m)){notify(t('لا يوجد طريق للمقصد. أزل حاجزاً ثم اختبر.','No route reaches the goal. Remove a barrier, then test.'));return;}if(cmd==='test-map'){pause(true);S.draft=M.start(m,profile);go('play');say('predict');}else{if(S.maps.length>=30){notify(t('صدّر أو احذف لغزاً قبل حفظ المزيد.','Export or remove a puzzle before saving more.'));return;}m.id='custom-'+Date.now()+'-'+Math.random().toString(36).slice(2,6);S.maps.push(m);designer=M.copy(m);save();render();notify(t('لغزك محفوظ وله طريق قابل للاختبار.','Your puzzle is saved with a testable route.'));}return;}
if(cmd==='edit-map'){designer=M.copy(find(v));designer.id='custom-'+Date.now();go('designer');return;}
if(cmd==='export-all'){exportValue(M.exported(S));return;}if(cmd==='export-current'){var tmp=M.blank();tmp.draft=M.artifact(d);tmp.language=S.language;exportValue(M.exported(tmp));return;}if(cmd==='close-output'){output='';render();return;}if(cmd==='print'){print(d);return;}if(cmd==='print-saved'){print(S.saved.filter(function(q){return q.id===v;})[0]);return;}if(cmd==='print-guide'){print(S.draft||M.start(D.maps[0],profile));return;}
if(cmd==='family'&&coachAllowed()){var a=api();if(a&&a.open)a.open();else{var btn=$('app360FamilyBtn');if(btn)btn.click();}return;}
if(cmd==='raw-backup'&&coachAllowed()){try{exportValue(localStorage.getItem(key)||'');}catch(e){notify(t('تعذر الوصول إلى الأصل.','The original data is unavailable.'));}return;}if(cmd==='reset-corrupt'&&coachAllowed()){if(pending!=='corrupt'){pending='corrupt';render();return;}bad[profile]=false;corrupt=false;save();render();return;}
}catch(err){notify(t('لم نغير حفظك. راجع الأوامر أو حدود الخريطة.','Your save is unchanged. Check the commands or map limits.'));}}
doc.addEventListener('click',handle,false);
doc.addEventListener('input',function(e){var n=e.target;if(n.id==='privateNote'&&coachAllowed()){S.note=n.value.slice(0,1000);save();}if(n.id==='mapAr'&&designer){designer.title.ar=n.value.slice(0,100);save();}if(n.id==='mapEn'&&designer){designer.title.en=n.value.slice(0,100);save();}},false);
doc.addEventListener('change',function(e){var n=e.target;if(n.id==='importFile')importFile(n.files[0]);if(n.id==='mapMode'&&designer){designer.mode=n.value==='absolute'?'absolute':'relative';designer.level=designer.mode==='absolute'?1:3;save();render();}if(n.id==='support'&&coachAllowed()){S.support=n.value==='independent'?'independent':'together';if(S.draft)S.draft.assistance=S.support;save();}if(n.id==='coachReadingFocus'&&coachAllowed()){var a=api();if(a&&a.setReadingFocus)a.setReadingFocus(!!n.checked);else S.reading_focus=!!n.checked;save();syncFocus();}},false);
function familyChanged(){if(identity()!==profile){save();load(identity());}else{if(view==='coach'&&!coachAllowed()){go('library');return;}syncFocus();}}
function checkOffline(){if(!w.caches)return;w.caches.keys().then(function(keys){return Promise.all(keys.filter(function(k){return k.indexOf('a4-command-path-')===0;}).map(function(k){return w.caches.open(k).then(function(c){return c.match(new URL('offline-ready.json',location.href).href).then(function(r){return !!r;});});}));}).then(function(values){offlineReady=values.some(function(v){return v;});$('offlineStatus').textContent=offlineReady?t('الصور والصوت جاهزة دون اتصال.','Pictures and sound are ready offline.'):t('يجري تجهيز حزمة العمل دون اتصال.','Preparing the offline bundle.');}).catch(function(){});}
reader=w.APP360_READ_ALONG.create({resolve:function(path){return path.indexOf('audio/')===0?'data/read-along.json':null;},clock:function(){return{path:audioPath,state:audioState,time:player.currentTime||0};},fallback:$('spokenText'),fallbackBox:$('spokenPanel'),onFamilyChange:familyChanged});
w.APP360_COMMAND={version:'preview-1',open:open,snapshot:function(){return M.copy(S);},audio:function(){return{path:audioPath,state:audioState,time:player.currentTime||0,paused:player.paused,readyState:player.readyState,focus:reader.isEnabled()};},debug:function(){return{profile:profile,view:view,offlineReady:offlineReady,storageOK:storageOK,corrupt:corrupt,running:running,busy:busy};}};
w.APP360_PWA_BEFORE_RELOAD=function(done){pause(true);save();done();};
w.addEventListener('popstate',function(){if(view!=='library'){pause(true);view='library';previewDraft=null;save();render();}},false);w.addEventListener('pagehide',function(){pause(true);save();},false);w.addEventListener('beforeunload',save,false);w.addEventListener('resize',save,false);doc.addEventListener('visibilitychange',function(){if(doc.hidden)pause();},false);['app360:namechange','app360:family-session','app360:reading-focus'].forEach(function(name){doc.addEventListener(name,familyChanged,false);});
load(identity());setTimeout(familyChanged,900);setTimeout(familyChanged,2500);setTimeout(checkOffline,2200);setInterval(checkOffline,20000);
})(window,document);
