const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');const root=path.resolve(__dirname,'..'),ctx={};ctx.window=ctx;for(const file of ['../../../resources/early-child-market-objects/manifest.js','data/content.js','src/model.js','src/exercises.js'])vm.runInNewContext(fs.readFileSync(path.resolve(root,file),'utf8'),ctx);const M=ctx.MARKET_MODEL,E=ctx.MARKET_EXERCISES,P=ctx.APP360_MARKET_OBJECTS;
function finish(d){const t=d.task;if(['count','measure'].includes(t.kind)){for(const r of t.requests){while(M.count(d,0,r.product)<r.quantity)M.take(d,r.product,0);while(M.count(d,0,r.product)>r.quantity)M.move(d,d.tokens.find(x=>x.zone===0&&x.product===r.product).id,-1)}}else if(t.kind==='pattern')while(d.sequence.length<t.length)M.append(d,t.rule[d.sequence.length%t.rule.length]);else if(t.kind==='compare')M.choose(d,t.left===t.right?'equal':t.left>t.right?'a':'b');else if(t.kind==='combine')d.tokens.slice().forEach(x=>M.move(d,x.id,2));else d.tokens.slice().forEach((x,i)=>M.move(d,x.id,i%t.groups));return d}
let seed=717;const rng=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
test('all ten ready activities solve from real cards in seven worlds, four levels and both languages',()=>{let checked=0;for(const m of P.markets)for(const type of E.types)for(let level=1;level<=4;level++)for(const lang of ['ar','en']){const out=E.generate(type.id,m.id,level,lang,[],null,rng);assert.ok(m.products.includes(out.task.product));const d=finish(M.start(out.task));assert.equal(M.evaluate(d).matches,true,[m.id,type.id,level,lang].join(':'));assert.equal(M.evaluate(M.artifact(d)).matches,true);checked++}assert.equal(checked,560)});
test('successive ready activities change picture and quantity and avoid recent exact repetitions',()=>{for(const type of E.types){let history=[],prev;for(let i=0;i<18;i++){const out=E.generate(type.id,'fruits',2,'ar',history,null,rng);if(prev){assert.notEqual(out.record.product,prev.product,type.id);if(type.id!=='pattern')assert.notEqual(out.record.quantity,prev.quantity,type.id);assert.notEqual(out.record.signature,prev.signature,type.id)}assert.ok(!history.slice(-12).some(h=>h.signature===out.record.signature),type.id);history.push(out.record);prev=out.record}}});
test('ascending recipes progress within valid quantities, change pictures and wrap at the range end',()=>{const r=E.recipe({type:'share',market:'animals',products:['rabbit','cat'],min:4,max:8,groups:2,strategy:'ascending',level:2}),history=[];for(const n of [4,6,8,4]){const out=E.generate(r.type,r.market,2,'ar',history,r,rng);assert.equal(out.record.quantity,n);history.push(out.record)}});
test('recipe bounds reject impossible sharing, missing pattern pictures and unsuitable measure/comparison ranges',()=>{const r={type:'count',market:'fruits',min:1,max:5};for(const bad of [{...r,type:'share',min:5,max:5,groups:2},{...r,type:'pattern',products:['apple']},{...r,type:'pattern',products:['apple','banana'],pattern:'three'},{...r,type:'compare',max:11},{...r,type:'measure',max:9},{...r,products:['car']},{...r,products:['apple','apple']}])assert.throws(()=>E.recipe(bad));assert.throws(()=>E.importRecipes('{"schema_version":2,"app_id":"a4-family-market-recipes","recipes":[]}'))});
test('old saves load, new rotation and coach patterns survive restore, and import makes independent copies',()=>{const s=M.blank(),out=E.generate('mixed','school',3,'ar',[],null,rng);s.draft=finish(M.start(out.task));s.recent=[out.record];s.recipes=[out.recipe];s.market='school';const restored=M.restore(JSON.stringify(s));assert.equal(restored.market,'school');assert.equal(restored.recent[0].signature,out.record.signature);assert.equal(M.evaluate(restored.draft).matches,true);assert.equal(restored.draft.task.recipe_spec.type,'mixed');const imported=E.importRecipes(JSON.stringify(E.exportRecipes(s.recipes)));assert.equal(imported.length,1);assert.notEqual(imported[0].id,s.recipes[0].id);const old={schema_version:1,saved:[],templates:[]};assert.equal(M.restore(JSON.stringify(old)).recipes.length,0)});

test('recorded numeral coverage includes excess cards in the largest single and mixed orders',()=>{const audio=require('../data/audio-manifest.json').items;for(const lang of ['ar','en'])for(const type of ['count','mixed']){const r=E.recipe({type,market:'fruits',min:20,max:20,level:4}),d=M.start(E.generate(type,r.market,4,lang,[],r,rng).task);assert.ok(d.tokens.length<=26);for(const request of d.task.requests)while(M.take(d,request.product,0)){}assert.equal(M.count(d,0),d.tokens.length);assert.equal(M.evaluate(d).matches,false);finish(d);assert.equal(M.evaluate(d).matches,true);for(let n=0;n<=d.tokens.length;n++){const file=P.numbers[lang][String(n)]?.path;if(file)assert.ok(fs.existsSync(path.resolve(root,'../../..',file)));else assert.ok(audio.some(a=>a.path==='audio/'+(lang==='ar'?'ar-':'')+'number-'+n+'.mp3'&&a.language===lang))}}});
