const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),ctx={};vm.runInNewContext(fs.readFileSync(path.join(root,'src/model.js'),'utf8'),ctx);const M=ctx.MARKET_MODEL,C=require('../data/content.json');const task=id=>C.missions.find(m=>m.id==='ar-'+id);
function finish(d){const t=d.task;if(t.kind==='count'||t.kind==='measure'){for(const r of t.requests){while(M.count(d,0,r.product)<r.quantity)M.take(d,r.product,0);while(M.count(d,0,r.product)>r.quantity){const x=d.tokens.find(x=>x.zone===0&&x.product===r.product);M.move(d,x.id,-1)}}}else if(t.kind==='compare')M.choose(d,t.left===t.right?'equal':t.left>t.right?'a':'b');else if(t.kind==='pattern')while(d.sequence.length<t.length)M.append(d,t.rule[d.sequence.length%t.rule.length]);else if(t.kind==='combine')for(const x of d.tokens)M.move(d,x.id,2);else for(let i=0;i<d.tokens.length;i++)M.move(d,d.tokens[i].id,i%t.groups);return d}
test('all 32 missions cover four levels and independent language texts; every loop solves from actual tokens',()=>{for(let n=1;n<=4;n++)for(const l of ['ar','en'])assert.equal(C.missions.filter(m=>m.level===n&&m.language===l).length,4);for(const m of C.missions){const d=finish(M.start(m));assert.equal(M.evaluate(d).matches,true,m.id);assert.equal(M.evaluate(M.artifact(d)).matches,true,m.id)}});
test('mixed order needs the correct kinds as well as the total; undo/redo retains tokens',()=>{const d=M.start(task('mixed-order'));for(let i=0;i<5;i++)M.take(d,'tomato',0);assert.equal(M.count(d,0),5);assert.equal(M.evaluate(d).matches,false);for(let i=0;i<2;i++)M.move(d,d.tokens.find(x=>x.zone===0).id,-1);for(let i=0;i<2;i++)M.take(d,'carrot',0);assert.equal(M.evaluate(d).matches,true);M.undo(d);assert.equal(M.evaluate(d).matches,false);M.undo(d,true);assert.equal(M.evaluate(d).matches,true)});
test('sharing conserves all tokens, rejects leftovers and tests equality; partition permits different splits',()=>{const d=M.start(task('two-friends'));for(const x of d.tokens.slice(0,4))M.move(d,x.id,0);assert.equal(M.evaluate(d).matches,false);finish(d);assert.equal(M.evaluate(d).matches,true);assert.equal(d.tokens.length,6);const p=finish(M.start(task('two-ways')));M.move(p,p.tokens.find(x=>x.zone===0).id,1);assert.equal(M.evaluate(p).matches,true);assert.equal(M.evaluate(p).counts.reduce((a,b)=>a+b),8);assert.throws(()=>M.task({...task('two-friends'),total:5}))});
test('comparison is invariant to visual spacing; tampered quantities cannot be imported',()=>{const d=M.start(task('more-or-longer'));M.choose(d,'b');assert.equal(M.evaluate(d).matches,false);d.tokens.forEach((x,i)=>x.screenPosition=100*i);M.choose(d,'a');assert.equal(M.evaluate(d).matches,true);d.tokens[0].zone=1;assert.throws(()=>M.artifact(d))});
test('pattern order matters and prefixes cannot be overwritten; rollback keeps the original rule',()=>{const d=M.start(task('double-pattern'));M.append(d,'orange');assert.equal(M.evaluate(d).matches,false);M.undo(d);finish(d);assert.equal(M.evaluate(d).matches,true);d.sequence[0]='orange';assert.throws(()=>M.artifact(d))});
test('saved attempts remain independent; export removes identity/private notes; schema rejection precedes mutation',()=>{const s=M.blank();s.draft=finish(M.start(task('little-order')));s.notes.observation='SECRET';s.profile_ref='PRIVATE';M.checkpoint(s.draft,'before-help');M.saved(s);const original=JSON.stringify(s.saved[0]);M.move(s.draft,s.draft.tokens.find(x=>x.zone===0).id,-1);assert.equal(JSON.stringify(s.saved[0]),original);const exported=JSON.stringify(M.exportData(s.saved));assert.ok(!/SECRET|PRIVATE/.test(exported));assert.equal(M.importData(exported).length,1);assert.throws(()=>M.restore('{bad'));assert.throws(()=>M.importData('{"schema_version":2,"app_id":"a4-family-market","projects":[]}'));assert.equal(M.restore(JSON.stringify(s)).saved.length,1)});
test('input limits reject altered stock, unknown products, duplicate token IDs and noninteger quantities',()=>{const t=task('little-order');assert.throws(()=>M.task({...t,requests:[{product:'apple',quantity:21}]}));assert.throws(()=>M.task({...t,requests:[{product:'apple',quantity:2.5}]}));const d=M.start(t);d.tokens[1].id=d.tokens[0].id;assert.throws(()=>M.artifact(d));const e=M.start(t);e.tokens[0].product='banana';assert.throws(()=>M.artifact(e));const f=M.start(t);f.tokens.push({...f.tokens[0],id:'extra'});assert.throws(()=>M.artifact(f))});
test('all generated audio uses its real segment boundaries, every numeral segment uses English',()=>{const manifest=require('../data/audio-manifest.json'),R=require('../data/read-along.json').items;assert.equal(manifest.items.length,173);for(const a of manifest.items){assert.ok(fs.statSync(path.join(root,a.path)).size>1000);const r=R[a.path];assert.equal(r.text,a.text);let prior=-1;for(const [i,start,end] of r.cues){assert.ok(i>prior&&start>=0&&end>=start&&end<=r.duration,a.path);prior=i}assert.equal(r.cues.length,a.text.split(/\s+/).length,a.path);a.text.split(/\s+/).forEach((v,i)=>{if(/^\d+/.test(v))assert.equal(r.segments.find(s=>s.token_indices.includes(i)).language,'en',a.path)})}});
test('promoted images and recorded names match the live source bytes, with no app runtime dependency',()=>{const repo=path.resolve(root,'../../..'),resource=path.join(repo,'resources/early-child-market-objects'),p=require(path.join(resource,'manifest.json'));assert.equal(p.items.length,12);for(const item of p.items)for(const key of ['image','audio_ar','audio_en']){const promoted=fs.readFileSync(path.join(resource,item[key])),source=fs.readFileSync(path.join(repo,'apps/1-4/say-and-name',item.source_paths[key]));assert.ok(promoted.equals(source));assert.equal(crypto.createHash('sha256').update(promoted).digest('hex'),item.sha256[key])}assert.ok(!/\.\.\/.*apps\/1-4|say-and-name/.test(fs.readFileSync(path.join(root,'index.html'),'utf8')))});
