const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),crypto=require('crypto'),M=require('../src/model.js'),C=require('../src/challenges.js');const root=path.resolve(__dirname,'..');
test('all 96 bounded recipes solve and every preset varies its recent layout',()=>{for(const c of C.cards)for(let level=1;level<=4;level++){const seen=new Set();for(let v=0;v<3;v++){const {task}=C.generate(c.id,level,{[c.id]:v});if(c.id!=='free'){assert.ok(M.evaluate({task,pieces:task.solution}).ok,task.id);seen.add(task.target.join('|'));task.solution.forEach(M.validPiece)}assert.ok(task.library.length<=16)}if(!['free','boat','bridge','rocket','robot'].includes(c.id))assert.ok(seen.size>=2)}});
test('coverage rejects overlap even if the union matches; rejects gaps and outside atoms',()=>{const task=C.generate('house',1,{}).task,p=M.copy(task.solution);assert.ok(M.evaluate({task,pieces:p}).ok);assert.ok(M.evaluate({task,pieces:p.concat([p[0]])}).overlap>0);assert.equal(M.evaluate({task,pieces:p.concat([p[0]])}).ok,false);p.pop();assert.ok(M.evaluate({task,pieces:p}).missing>0);p[0].x=0;assert.ok(M.evaluate({task,pieces:p}).outside>0)});
test('equal-looking wings in wrong positions are not mirror symmetry',()=>{const task=C.generate('wings',1,{}).task,p=M.copy(task.solution);assert.ok(M.evaluate({task,pieces:p}).symmetric);p[1].x=4;assert.equal(M.evaluate({task,pieces:p}).symmetric,false);assert.equal(M.evaluate({task,pieces:p}).ok,false)});
test('house accepts a different decomposition, not just a rearrangement of identical identities',()=>{const task=C.generate('house',3,{}).task,d=M.start(task);d.pieces.slice(0,4).forEach((p,i)=>Object.assign(p,task.solution[i]));assert.ok(M.evaluate(d).ok);const first=M.signature(d.pieces);d.pieces[2].placed=d.pieces[3].placed=false;[[1,3],[3,3],[1,4],[3,4]].forEach((pos,i)=>Object.assign(d.pieces[i+4],{x:pos[0],y:pos[1],rot:0,flip:false,placed:true}));assert.ok(M.evaluate(d).ok);assert.notEqual(M.signature(d.pieces),first);let swapped=M.copy(task.solution);[swapped[2],swapped[3]]=[swapped[3],swapped[2]];assert.equal(M.signature(swapped),M.signature(task.solution))});
test('bridge count is checked separately from covered area',()=>{const task=C.generate('bridge',1,{}).task;assert.ok(M.evaluate({task,pieces:task.solution}).ok);const alt=task.solution.slice(1);alt.push(M.piece('bar',1,1,0,false,3),M.piece('bar',3,1,0,false,4));const e=M.evaluate({task,pieces:alt});assert.equal(e.missing,0);assert.equal(e.overlap,0);assert.equal(e.count,4);assert.equal(e.ok,false)});
test('draft transforms, mirror, solutions, explanations and undo survive edits and independent exports',()=>{const task=C.generate('wings',2,{}).task,d=M.start(task);M.edit(d,()=>{d.pieces=M.copy(task.solution)},'build');assert.ok(M.evaluate(d).ok);assert.ok(M.undo(d,false));assert.ok(d.pieces.every(p=>!p.placed));assert.ok(M.undo(d,true));const sig=M.signature(d.pieces);d.explanation='بنيت جناحين';d.coach_note='private';d.solutions.push({signature:sig,pieces:M.copy(d.pieces)});const s=M.blank();s.draft=d;s.saved=[M.artifact(d,true)];const r=M.restore(JSON.stringify(s));assert.equal(M.signature(r.draft.pieces),sig);const exported=M.exportData(s.saved);assert.ok(!JSON.stringify(exported).includes('private'));const imported=M.importData(JSON.stringify(exported));assert.notEqual(imported[0].id,d.id);imported[0].pieces[0].x=0;assert.notEqual(imported[0].pieces[0].x,d.pieces[0].x)});
test('custom puzzles can be solved from their own contract; false mirror constraints cannot be authored',()=>{let d=M.start(C.generate('free',1,{}).task);Object.assign(d.pieces[0],{placed:true,x:1,y:1});const t=C.fromDesign(d,{ar:'فكرتي',en:'My idea',exact_count:true});assert.ok(M.evaluate({task:t,pieces:t.solution}).ok);assert.throws(()=>C.fromDesign(d,{symmetric:true}));const exported={schema_version:1,app_id:'a4-shape-design',patterns:[t]},p=C.importPatterns(JSON.stringify(exported));assert.notEqual(p[0].id,t.id)});
test('malformed imported placements, target atoms and empty puzzles do not enter local state',()=>{const task=C.generate('house',1,{}).task,d=M.start(task);d.pieces[0].x=99;assert.throws(()=>M.importData(JSON.stringify(M.exportData([d]))));task.target.push('9,9,9');assert.throws(()=>M.validTask(task));const q=C.generate('house',1,{}).task;q.solution[0].x=0;assert.throws(()=>M.validTask(q));assert.throws(()=>M.restore('{'))});
test('authored Arabic clips contain Arabic text, numeric instructions are spoken as words, cues are real and ordered',()=>{const manifest=require('../data/audio-manifest.json'),timing=require('../data/read-along.json');assert.equal(manifest.items.length,88);for(const item of manifest.items){assert.ok(fs.statSync(path.join(root,item.path)).size>1000);const cue=timing.items[item.path];assert.equal(cue.text,item.text);assert.equal(cue.language,item.language);assert.equal(cue.cues.length,item.text.split(/\s+/).length);let last=-1;for(const [i,a,b] of cue.cues){assert.ok(i>last&&b>a&&a>=0&&b<=cue.duration);last=i}if(item.language==='ar'){assert.ok(!/[A-Za-z0-9]/.test(item.text));assert.equal(manifest.voices.ar,'ar-SA-ZariyahNeural')}}});
test('boat assets reference the original bytes without new image or word-audio copies',()=>{const pack=require('../../../../resources/early-child-market-objects/manifest.json'),boat=pack.items.find(p=>p.id==='boat'),repo=path.resolve(root,'../../..');for(const key of ['image','audio_ar','audio_en'])assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(repo,boat[key]))).digest('hex'),boat.sha256[key]);assert.ok(!fs.existsSync(path.join(root,'assets/boat.jpg')))});

test('shared Arabic and English numerals zero to sixteen reuse canonical source bytes',()=>{const p=require('../../../../resources/shape-numeral-audio/manifest.json'),repo=path.resolve(root,'../../..');for(const lang of ['ar','en']){assert.equal(Object.keys(p.numbers[lang]).length,17);for(const n of Object.values(p.numbers[lang])){assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(repo,n.path))).digest('hex'),n.sha256);assert.ok(n.source_word)}}});
