(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.COMMAND_CELEBRATION=factory();}(this,function(){'use strict';
var BASE='../../../resources/early-child-name-audio/',REGISTRY=BASE+'audio/registry.json';
function norm(s){return String(s||'').toLowerCase().replace(/[\u064B-\u065F\u0670ـ]/g,'').replace(/[أإآ]/g,'ا').replace(/\s+/g,' ').replace(/^\s+|\s+$/g,'');}
function match(reg,name){var users=reg&&reg.users||{},keys=Object.keys(users),n=norm(name),i,j,u;if(!n)return null;for(i=0;i<keys.length;i++){u=users[keys[i]];if(norm(keys[i])===n)return{key:keys[i],user:u};for(j=0;j<(u.aliases||[]).length;j++)if(norm(u.aliases[j])===n)return{key:keys[i],user:u};}return null;}
function clip(entry){var clips=entry&&entry.user.clips||[],i;for(i=0;i<clips.length;i++)if(clips[i].kind==='cheer'&&clips[i].id==='cheer-01')return clips[i];for(i=0;i<clips.length;i++)if(clips[i].kind==='cheer')return clips[i];return null;}
function paths(c){var out=[],f=c&&c.files||{};[f.mp3||c&&c.file,f.wav,f.ogg].forEach(function(p){if(typeof p==='string'&&/^audio\/(?:names\/[a-z0-9-]+|[a-z0-9-]+|نور)\/[a-z0-9-]+\.(?:mp3|wav|ogg)$/.test(p)&&out.indexOf(BASE+p)<0)out.push(BASE+p);});return out;}
function google(text,lang){return 'https://translate.googleapis.com/translate_tts?ie=UTF-8&client=gtx&tl='+lang+'&q='+encodeURIComponent(text);}
function create(o){var w=o.window||window,doc=w.document,registry=null,loading=false,callbacks=[],token=0,audio=new w.Audio(),timer=null,hideTimer=null,box=null,source='',state='idle';
function name(){var s='';try{s=o.getName()||'';}catch(e){}return String(s).replace(/[^a-zA-Z\u0600-\u06ff\s'-]/g,'').replace(/\s+/g,' ').replace(/^\s+|\s+$/g,'').slice(0,60);}
function load(done){if(registry){if(done)done(registry);return;}if(done)callbacks.push(done);if(loading)return;loading=true;var x=new w.XMLHttpRequest();x.open('GET',REGISTRY,true);x.timeout=7000;function finish(r){if(!loading)return;loading=false;registry=r;var c=callbacks;callbacks=[];c.forEach(function(fn){fn(r);});}x.onload=function(){try{finish(x.status>=200&&x.status<300?JSON.parse(x.responseText):null);}catch(e){finish(null);}};x.onerror=x.ontimeout=function(){finish(null);};x.send(null);}
function stopAudio(){token++;w.clearTimeout(timer);audio.onended=audio.onerror=audio.onloadedmetadata=null;try{audio.pause();}catch(e){}try{if(w.speechSynthesis)w.speechSynthesis.cancel();}catch(e){}source='';state='idle';if(o.onAudioEnd)o.onAudioEnd();}
function hide(){w.clearTimeout(hideTimer);if(box){box.hidden=true;box.innerHTML='';}}
function show(){hide();var n=name(),lang=o.getLanguage(),text=lang==='en'?'You reached the goal'+(n?', '+n:'')+'!':'وصلت إلى المقصد'+(n?' يا '+n:'')+'!';if(!box){box=doc.createElement('div');box.id='commandCelebration';box.className='celebration';box.setAttribute('role','status');box.setAttribute('aria-live','polite');doc.body.appendChild(box);}box.hidden=false;var badge=doc.createElement('p');badge.className='celebration-badge';badge.textContent=text;box.appendChild(badge);var reduced=w.matchMedia&&w.matchMedia('(prefers-reduced-motion: reduce)').matches,count=reduced?0:32;for(var i=0;i<count;i++){var piece=doc.createElement('i');piece.className='confetti-piece';piece.setAttribute('aria-hidden','true');piece.style.left=(i*31%100)+'%';piece.style.backgroundColor=['#287f91','#edb83d','#de7972','#8974b1'][i%4];piece.style.animationDelay=(i%7*.07)+'s';piece.style.webkitAnimationDelay=(i%7*.07)+'s';box.appendChild(piece);}hideTimer=w.setTimeout(hide,4500);return text;}
function play(done){stopAudio();if(!o.getSound()){if(done)done();return;}var own=token,n=name(),lang=o.getLanguage(),text=lang==='en'?'Well done'+(n?', '+n:'')+'. You reached the goal.':'أَحْسَنْتَ'+(n?' يا '+n:'')+'. وَصَلْتَ إِلَى الْمَقْصِدِ.';
function completed(){if(own!==token)return;stopAudio();if(done)done();}
function native(){if(own!==token)return;try{if(!w.speechSynthesis||!w.SpeechSynthesisUtterance)throw Error('no voice');var u=new w.SpeechSynthesisUtterance(text);u.lang=lang==='en'?'en-US':'ar-SA';u.rate=.9;u.onend=function(){if(own===token)completed();};u.onerror=function(){if(own===token)offline();};state='device';source='device-tts';w.speechSynthesis.speak(u);timer=w.setTimeout(function(){if(own===token)offline();},12000);}catch(e){offline();}}
function offline(){if(own!==token)return;w.clearTimeout(timer);try{if(w.speechSynthesis)w.speechSynthesis.cancel();}catch(e){}state='fallback';attempt(['audio/'+lang+'-arrived.mp3'],function(){state='unavailable';if(o.onAudioEnd)o.onAudioEnd();if(done)done();},false);}
function attempt(urls,failed,isGoogle){var idx=0,attemptId=0;function next(){if(own!==token)return;w.clearTimeout(timer);var id=++attemptId;if(idx>=urls.length){failed();return;}var url=urls[idx++],settled=false;source=isGoogle?'google':url;state='loading';function bad(){if(settled||own!==token||id!==attemptId)return;settled=true;next();}audio.onerror=bad;audio.onended=function(){if(own===token&&id===attemptId){settled=true;completed();}};audio.onloadedmetadata=function(){if(own!==token||id!==attemptId)return;w.clearTimeout(timer);timer=w.setTimeout(bad,Math.max(7000,(audio.duration||4)*1000+4000));};audio.src=url;timer=w.setTimeout(bad,8000);try{var p=audio.play();function started(){if(own!==token||id!==attemptId)return;state='playing';if(o.onAudioStart)o.onAudioStart();}if(p&&p.then)p.then(started).catch(bad);else started();}catch(e){bad();}}next();}
function online(){if(own!==token)return;attempt([google(text,lang)],native,true);}
load(function(r){if(own!==token)return;var e=match(r,n),c=clip(e),ps=lang==='ar'?paths(c):[];if(lang==='en'&&e){var aliases=e.user.aliases||[],enName=n;for(var i=0;i<aliases.length;i++)if(/^[a-zA-Z ]+$/.test(aliases[i])){enName=aliases[i];break;}text='Well done'+(enName?', '+enName:'')+'. You reached the goal.';}if(ps.length)attempt(ps,online,false);else online();});}
load();return{show:show,play:play,stopAudio:stopAudio,hide:hide,warm:load,debug:function(){return{source:source,state:state,name:name(),visible:!!(box&&!box.hidden)};}};}
return{normalize:norm,match:match,clip:clip,paths:paths,google:google,create:create};}));
