(function(w){'use strict';
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function robot(dir){return '<svg class="robot" style="-webkit-transform:rotate('+(dir*90)+'deg);transform:rotate('+(dir*90)+'deg)" viewBox="0 0 64 64" aria-hidden="true"><path d="M32 3L20 18h24z" fill="#efaa32"/><rect x="12" y="20" width="40" height="34" rx="12" fill="#2b7898"/><rect x="18" y="26" width="28" height="17" rx="6" fill="#e8f8ff"/><circle cx="25" cy="34" r="3" fill="#163f50"/><circle cx="39" cy="34" r="3" fill="#163f50"/><path d="M25 47h14" stroke="#d9eff5" stroke-width="3" stroke-linecap="round"/><path d="M8 32v14M56 32v14" stroke="#2b7898" stroke-width="6" stroke-linecap="round"/></svg>';}
function symbol(op){var names={n:'↑',e:'→',s:'↓',w:'←',f:'⇧',l:'↶',r:'↷',repeat:'↻',if:'◇'};return names[op]||'?';}
function board(m,pos,pred,trace,options){options=options||{};var n=m.size,i,j,html='<div class="board '+(options.mini?'mini':'')+'" dir="ltr" role="group" aria-label="'+esc(options.label||'Map')+'">',asset=(w.APP360_MARKET_OBJECTS&&w.APP360_MARKET_OBJECTS.items||[]).filter(function(p){return p.id===m.goal_asset;})[0];
for(j=0;j<n;j++){html+='<div class="board-row">';for(i=0;i<n;i++){var wall=m.walls.some(function(p){return p.x===i&&p.y===j;}),goal=m.goal.x===i&&m.goal.y===j,start=m.start.x===i&&m.start.y===j,here=pos&&pos.x===i&&pos.y===j,guess=pred.some(function(p){return p.x===i&&p.y===j;}),visited=trace.some(function(p){return p.to.x===i&&p.to.y===j&&!p.blocked;}),classes='cell '+(wall?'wall ':'')+(goal?'goal ':'')+(guess?'guess ':'')+(visited?'visited ':'')+(start?'start ':'');html+='<'+(options.interactive?'button type="button" data-do="tile" data-value="'+i+':'+j+'"':'span')+' class="'+classes+'" style="width:'+(100/n)+'%" aria-label="'+esc((options.lang==='ar'?'صف ':'Row ')+(j+1)+(options.lang==='ar'?' عمود ':' column ')+(i+1)+(wall?(options.lang==='ar'?' حاجز':' barrier'):'')+(goal?(options.lang==='ar'?' مقصد':' destination'):'')+(here?(options.lang==='ar'?' روبوت':' robot'):''))+'">';if(wall)html+='<svg class="barrier" viewBox="0 0 64 64" aria-hidden="true"><rect x="8" y="14" width="48" height="36" rx="8" fill="#d1a87b"/><path d="M14 22h36M14 42h36M27 22v20M43 22v20" stroke="#976c48" stroke-width="3"/></svg>';if(goal&&asset)html+='<img class="goal-photo" src="../../../'+esc(asset.image)+'" alt="'+esc(asset[options.lang||'ar'])+'">';if(start&&!here)html+='<span class="start-dot" aria-hidden="true">⚑</span>';if(guess)html+='<span class="guess-dot" aria-hidden="true"></span>';if(here)html+=robot(pos.dir);html+='</'+(options.interactive?'button':'span')+'>'; }html+='</div>';}
return html+'</div>';}
w.COMMAND_VISUALS={board:board,robot:robot,symbol:symbol,escape:esc};
})(window);
