var CACHE='app360-portal-v75-family-school-v103';
var CORE=[
 './assets/covers/a4-story-language-v2-640.webp','./assets/covers/a4-story-language-v2-640.jpg','./assets/js/lab360-v24.js?v=102&brand=98','./assets/js/home-showcase-v31.js?v=102&brand=98',
  './assets/js/family-reels-v1.js?v=102','./assets/js/family-reels-launcher-v1.js?v=102','./assets/css/family-reels-v1.css?v=99','./reels/index.html','./assets/covers/family-reels-learner-art-640.webp','./assets/covers/family-reels-learner-art-640.jpg','./assets/covers/family-reels-coach-art-640.webp','./assets/covers/family-reels-coach-art-640.jpg','./assets/brand/family-reels-360-logo-160.png',
  './assets/js/app360-app-audience-v1.js?v=98',
  './','./index.html',
  './assets/css/lab360.css','./assets/css/legacy-compat.css','./assets/css/home-showcase-v31.css',
  './assets/js/lab360-v24.js','./assets/js/home-showcase-v31.js','./assets/js/home-cover-open-v32.js','./assets/js/home-cover-open-v32.js?v=103','./assets/js/app360-family-shell-viewport-fix-v1.js?v=103','./assets/js/pwa-install-v24.js?v=103&brand=98','./assets/js/retired-apps-v36.js','./assets/js/swal-modern-loader-v24.js','./assets/js/pwa-install-v24.js','./assets/js/app360-ai-shell.js',
  './assets/js/app360-family-hybrid-transport-v1.js','./assets/js/app360-peer-media-bootstrap-v1.js','./assets/js/app360-family-stability-v1.js','./assets/js/app360-family-fast-start-v1.js','./assets/js/app360-family-sync-v1.js','./assets/js/app360-family-core-v2.js','./assets/js/app360-family-catalog-v1.js','./assets/js/app360-family-ui-v2.js','./assets/js/app360-family-mutation-guard-v1.js','./assets/js/app360-family-shell-v1.js','./assets/js/app360-family-shell-viewport-fix-v1.js','./assets/js/app360-family-navigation-safety-v1.js','./assets/js/app360-family-preview-v2.js','./assets/js/app360-family-media-v1.js','./assets/js/app360-family-media-core-v3.js','./assets/js/app360-family-audio-guard-v1.js',
  './assets/js/app360-family-hybrid-transport-v1.js?v=3','./assets/js/app360-peer-media-bootstrap-v1.js?v=1','./assets/js/app360-family-stability-v1.js?v=2','./assets/js/app360-family-fast-start-v1.js?v=1','./assets/js/app360-family-sync-v1.js?v=103','./assets/js/app360-family-core-v2.js?v=103&brand=98','./assets/js/app360-family-catalog-v1.js?v=103&brand=98','./assets/js/app360-family-shell-v1.js?v=103&brand=98','./assets/js/app360-family-media-v1.js?v=7','./assets/js/app360-family-media-core-v3.js?v=3&brand=98','./assets/js/app360-family-audio-guard-v1.js?v=3',
  './manifest.webmanifest?v=98','./assets/brand/family-school-360-logo-640.webp','./assets/brand/family-school-360-logo-640.png','./assets/brand/family-school-360-icon-192.png?v=98','./assets/brand/family-school-360-share.jpg?v=98',
  './assets/covers/app-coming-soon-v30.svg',
  './assets/covers/a1-drawing-writing.jpg','./assets/covers/a1-first-words.jpg','./assets/covers/a1-imitate.jpg','./assets/covers/a1-screen-move.jpg','./assets/covers/a1-calm.jpg','./assets/covers/a1-sensory.jpg','./assets/covers/a1-routine.jpg','./assets/covers/a1-plan-runner.jpg','./assets/covers/a1-shape-builder.jpg','./assets/covers/a1-picture-puzzles.jpg',
  './data/catalog.json','./data/goals.json','./data/live-overrides.json',
  './ages/1-4/index.html','./ages/4-8/index.html','./ages/8-12/index.html','./ages/12-16/index.html',
  './ages/16-24/index.html','./ages/24-45/index.html','./ages/45-60/index.html','./ages/60-80/index.html'
];
function cacheCore(c,i){i=i||0;if(i>=CORE.length)return Promise.resolve();return Promise.all(CORE.slice(i,i+4).map(function(u){return c.add(u).catch(function(){return null})})).then(function(){return new Promise(function(resolve){setTimeout(resolve,25)})}).then(function(){return cacheCore(c,i+4)})}
self.addEventListener('install',function(e){e.waitUntil(caches.open(CACHE).then(function(c){return cacheCore(c)}).then(function(){if(self.skipWaiting)return self.skipWaiting()}))});
self.addEventListener('activate',function(e){e.waitUntil(caches.keys().then(function(keys){return Promise.all(keys.map(function(k){if(k.indexOf('app360-portal-')===0&&k!==CACHE)return caches.delete(k)}))}).then(function(){return self.clients&&self.clients.claim?self.clients.claim():null}))});
self.addEventListener('message',function(e){if(e.data&&e.data.type==='SKIP_WAITING'&&self.skipWaiting)self.skipWaiting()});
function sameOrigin(req){try{return new URL(req.url).origin===self.location.origin}catch(e){return false}}
function networkFirst(req,fallback){return fetch(req,{cache:'no-store'}).then(function(resp){if(resp&&resp.ok&&sameOrigin(req)){var copy=resp.clone();caches.open(CACHE).then(function(c){c.put(req,copy)});}return resp}).catch(function(){return caches.match(req).then(function(hit){return hit||caches.match(fallback||'./index.html')})})}
function staleWhileRevalidate(req){return caches.match(req).then(function(hit){var update=fetch(req).then(function(resp){if(resp&&resp.ok&&sameOrigin(req)){var copy=resp.clone();caches.open(CACHE).then(function(c){c.put(req,copy)});}return resp}).catch(function(){return null});return hit||update})}
function canonicalFamilyUrl(url){var base=self.location.href,name='';if(url.indexOf('/assets/js/app360-peer-bootstrap-v1.js')>=0||url.indexOf('/assets/js/app360-peer-bootstrap-single-v2.js')>=0||url.indexOf('/assets/js/app360-peer-media-bootstrap-v1.js')>=0)name='assets/js/app360-peer-media-bootstrap-v1.js?v=1';else if(url.indexOf('/assets/js/app360-family-hybrid-transport-v1.js')>=0)name='assets/js/app360-family-hybrid-transport-v1.js?v=3';else if(url.indexOf('/assets/js/app360-family-stability-v1.js')>=0)name='assets/js/app360-family-stability-v1.js?v=2';else if(url.indexOf('/assets/js/app360-family-fast-start-v1.js')>=0)name='assets/js/app360-family-fast-start-v1.js?v=1';else if(url.indexOf('/assets/js/app360-family-sync-v1.js')>=0)name='assets/js/app360-family-sync-v1.js?v=103';else if(url.indexOf('/assets/js/app360-family-core-v2.js')>=0)name='assets/js/app360-family-core-v2.js?v=103&brand=98';else if(url.indexOf('/assets/js/app360-family-catalog-v1.js')>=0)name='assets/js/app360-family-catalog-v1.js?v=103&brand=98';else if(url.indexOf('/assets/js/app360-family-shell-v1.js')>=0)name='assets/js/app360-family-shell-v1.js?v=103&brand=98';else if(url.indexOf('/assets/js/app360-family-audio-guard-v1.js')>=0)name='assets/js/app360-family-audio-guard-v1.js?v=3';else if(url.indexOf('/assets/js/app360-family-media-v1.js')>=0)name='assets/js/app360-family-media-v1.js?v=7';else if(url.indexOf('/assets/js/app360-family-media-core-v3.js')>=0)name='assets/js/app360-family-media-core-v3.js?v=3&brand=98';if(!name)return'';return new URL(name,base).href}
function canonicalFamilyResponse(url){var u=canonicalFamilyUrl(url);if(!u)return null;return staleWhileRevalidate(new Request(u,{credentials:'same-origin'}))}
self.addEventListener('fetch',function(e){var req=e.request;if(!req||req.method!=='GET'||!sameOrigin(req))return;var url=req.url||'',canon=canonicalFamilyResponse(url);var isData=url.indexOf('/data/catalog.json')>=0||url.indexOf('/data/goals.json')>=0||url.indexOf('/data/live-overrides.json')>=0;var isPortalLogic=url.indexOf('/assets/js/lab360')>=0||url.indexOf('/assets/js/home-showcase')>=0||url.indexOf('/assets/js/home-cover-open')>=0||url.indexOf('/assets/js/retired-apps')>=0||url.indexOf('/assets/js/swal-modern-loader')>=0||url.indexOf('/assets/js/pwa-install')>=0||url.indexOf('/assets/js/app360-ai-shell')>=0||url.indexOf('/assets/js/app360-family-')>=0||url.indexOf('/assets/js/app360-peer-')>=0;var isBrand=url.indexOf('/assets/brand/')>=0||url.indexOf('/assets/covers/')>=0||url.indexOf('/manifest.webmanifest')>=0;var isPortalStyle=url.indexOf('/assets/css/home-showcase')>=0||url.indexOf('/assets/css/lab360')>=0;if(req.mode==='navigate'){e.respondWith(networkFirst(req,'./index.html'));return}if(canon){e.respondWith(canon);return}if(isData||isPortalLogic||isBrand||isPortalStyle){e.respondWith(networkFirst(req));return}e.respondWith(staleWhileRevalidate(req))});