(function(){
'use strict';
var BUILD='22',registry=null,mode='auto',loading=false,currentAudio=null,currentSource=null,ctx=null,unlocked=false;
var BASE=(typeof window!=='undefined'&&window.Audio360Base)||'';
function resolveAsset(f){if(!f)return'';if(/^(?:https?:|data:|blob:|\/)/i.test(f))return f;return BASE+f}
function $(id){return document.getElementById(id)}
function trim(s){return(''+(s||'')).replace(/^\s+|\s+$/g,'')}
function norm(s){return trim(s).toLowerCase().replace(/[ًٌٍَُِّْـ،,.!؟?؛;:\-–—]/g,'').replace(/\s+/g,' ')}
function storeGet(k,d){try{var v=localStorage.getItem(k);return v===null?d:v}catch(e){return d}}
function storeSet(k,v){try{localStorage.setItem(k,v)}catch(e){}}
function username(){try{if(window.PenKidsCore&&PenKidsCore.getUserName)return trim(PenKidsCore.getUserName())||'نور'}catch(e){}return'نور'}
function setStatus(s){try{if(window.PenKidsCore&&PenKidsCore.setStatus)PenKidsCore.setStatus(s);else if($('statusText'))$('statusText').innerHTML=s}catch(e){}}
function setInfo(s){var e=$('bundledAudioInfo');if(e)e.innerHTML=s}
function ua(){return navigator.userAgent||''}
function androidVersion(){var m=ua().match(/Android\s+([0-9.]+)/i);return m?parseFloat(m[1])||0:0}
function chromeVersion(){var m=ua().match(/(?:Chrome|CriOS)\/([0-9]+)/i);return m?parseInt(m[1],10)||0:0}
function isLegacy(){var av=androidVersion(),cv=chromeVersion(),u=ua();return !!((av&&av<5)||(cv&&cv<50)||/Android 4\.|Version\/4\.|BigTAB|DMTAB/i.test(u))}
function isMobile(){return /Android|iPhone|iPad|iPod|Mobile/i.test(ua())}
function xhrJson(url,ok,fail){try{var x=new XMLHttpRequest();x.open('GET',url+(url.indexOf('?')>=0?'&':'?')+'_='+(+new Date()),true);try{x.setRequestHeader('Cache-Control','no-cache')}catch(e){}x.onreadystatechange=function(){if(x.readyState===4){if((x.status>=200&&x.status<300)||x.status===0){try{ok(JSON.parse(x.responseText))}catch(e){if(fail)fail(e)}}else if(fail)fail(new Error('HTTP '+x.status))}};x.send(null)}catch(e){if(fail)fail(e)}}
function loadRegistry(cb){if(registry){if(cb)cb(true);return}if(loading){setTimeout(function(){loadRegistry(cb)},100);return}loading=true;xhrJson(fileUrl('audio/registry.json'),function(j){registry=j||{};loading=false;refreshInfo();if(cb)cb(true)},function(){registry=null;loading=false;refreshInfo();if(cb)cb(false)})}
function userEntry(){if(!registry||!registry.users)return null;var n=norm(username()),k,u,a,i;if(n==='noor'||n==='nour'||n==='nur'||n==='noour'||n==='نور')return registry.users['نور']||registry.users.noor||null;if(registry.users[username()])return registry.users[username()];for(k in registry.users){if(registry.users.hasOwnProperty(k)){u=registry.users[k];a=u.aliases||[];if(norm(k)===n)return u;for(i=0;i<a.length;i++)if(norm(a[i])===n)return u}}return null}
function matchClip(list,text){var n=norm(text),i,j,c,a;for(i=0;i<(list||[]).length;i++){c=list[i];if(norm(c.text)===n)return c;if(c.name&&norm(c.name)===n)return c;a=c.aliases||[];for(j=0;j<a.length;j++)if(norm(a[j])===n)return c}return null}
function colorClip(text){var arr=registry&&registry.colors||[],c=matchClip(arr,text),n,i;if(c)return c;n=norm(text).replace(/^اللون\s+/,'').replace(/^لون\s+/,'');for(i=0;i<arr.length;i++)if(norm(arr[i].name)===n)return arr[i];return null}
function clipFor(text){var c=colorClip(text),u,clips,n,i,cheers=[];if(c)return c;u=userEntry();clips=u&&u.clips||[];c=matchClip(clips,text);if(c)return c;n=norm(text);if(n.indexOf('اختبار')>=0||n.indexOf('مرحبا')>=0){for(i=0;i<clips.length;i++)if(clips[i].id==='test')return clips[i]}for(i=0;i<clips.length;i++)if(clips[i].kind==='cheer')cheers.push(clips[i]);return cheers.length?cheers[Math.floor(Math.random()*cheers.length)]:null}
function fileUrl(f){if(!f)return'';f=resolveAsset(f);return f+(f.indexOf('?')>=0?'&':'?')+'v='+BUILD}
function candidates(c,legacyOrder){var f=c&&c.files||{},r=[];function add(x,t){if(x)r.push({src:x,type:t})}if(legacyOrder){add(f.wav,'wav');add(f.mp3,'mp3');add(f.ogg,'ogg')}else{add(f.mp3,'mp3');add(f.ogg,'ogg');add(f.wav,'wav')}if(!r.length&&c&&c.file)add(c.file,/\.wav$/i.test(c.file)?'wav':/\.ogg$/i.test(c.file)?'ogg':'mp3');return r}
function ensureCtx(){if(ctx)return ctx;try{var C=window.AudioContext||window.webkitAudioContext;if(C)ctx=new C()}catch(e){}return ctx}
function unlockCtx(){var c=ensureCtx();if(!c)return false;try{if(c.state==='suspended'&&c.resume)c.resume()}catch(e){}try{var o=c.createOscillator(),g=c.createGain?c.createGain():null;if(g){g.gain.value=0;o.connect(g);g.connect(c.destination)}else{o.connect(c.destination)}if(o.start)o.start(0);else if(o.noteOn)o.noteOn(0);if(o.stop)o.stop(c.currentTime+.01);else if(o.noteOff)o.noteOff(c.currentTime+.01)}catch(e){}return true}
function stopRecorded(){try{if(currentAudio){try{currentAudio.pause()}catch(e){}try{currentAudio.currentTime=0}catch(e){}}}catch(e){}currentAudio=null;try{if(currentSource){if(currentSource.stop)currentSource.stop(0);else if(currentSource.noteOff)currentSource.noteOff(0)}}catch(e){}currentSource=null}
function playWebAudio(c,onDone){var ac=ensureCtx(),list=candidates(c,true),idx=0,finished=false;if(!ac||!list.length)return false;try{if(ac.state==='suspended'&&ac.resume)ac.resume()}catch(e){}function fail(){if(finished)return;if(idx>=list.length){finished=true;if(onDone)onDone(false,'webaudio-failed');return}var it=list[idx++],x;try{x=new XMLHttpRequest();x.open('GET',fileUrl(it.src),true);x.responseType='arraybuffer';x.onreadystatechange=function(){if(x.readyState!==4)return;if(!((x.status>=200&&x.status<300)||x.status===0)||!x.response){fail();return}var ok=function(buf){if(finished||!buf){fail();return}try{var s=ac.createBufferSource();currentSource=s;s.buffer=buf;s.connect(ac.destination);s.onended=function(){if(finished)return;finished=true;currentSource=null;if(onDone)onDone(true,'webaudio-'+it.type)};if(s.start)s.start(0);else if(s.noteOn)s.noteOn(0);setStatus(c.kind==='color'?'🔊 نطق اللون من التسجيل':'🔊 الصوت المسجل يعمل')}catch(e){fail()}};var bad=function(){fail()};try{var p=ac.decodeAudioData(x.response,ok,bad);if(p&&p.then)p.then(ok).catch(bad)}catch(e){bad()}};x.onerror=fail;x.send(null)}catch(e){fail()}}fail();return true}
function ensureAudio(){var a=$('legacyAudioPlayer');if(!a){a=document.createElement('audio');a.id='legacyAudioPlayer';a.setAttribute('preload','auto');a.style.position='absolute';a.style.left='-9999px';a.style.width='1px';a.style.height='1px';document.body.appendChild(a)}return a}
function playHtmlAudio(c,onDone){var list=candidates(c,false),idx=0,a=ensureAudio(),done=false;if(!list.length)return false;stopRecorded();currentAudio=a;function next(){if(done)return;if(idx>=list.length){done=true;currentAudio=null;if(onDone)onDone(false,'htmlaudio-failed');return}var it=list[idx++];try{a.onended=function(){if(done)return;done=true;currentAudio=null;if(onDone)onDone(true,'htmlaudio-'+it.type)};a.onerror=function(){next()};a.src=fileUrl(it.src);a.preload='auto';a.volume=1;try{a.load()}catch(e){}var p=a.play();if(p&&typeof p.then==='function')p.then(function(){setStatus(c.kind==='color'?'🔊 نطق اللون من التسجيل':'🔊 الصوت المسجل يعمل')},function(){next()});else setStatus(c.kind==='color'?'🔊 نطق اللون من التسجيل':'🔊 الصوت المسجل يعمل')}catch(e){next()}}next();return true}
var pcmLoads={};
function pcmPack(c){var packs=window.Audio360PCMPacks||{},p=c&&c.pcmPack;if(p&&packs[p])return packs[p];return window.Audio360PCM||null}
function loadPcmPack(c,cb){var url=c&&c.pcmScript;if(!url){cb(false);return false}var packs=window.Audio360PCMPacks||{};if(c.pcmPack&&packs[c.pcmPack]){cb(true);return true}if(pcmLoads[url]){pcmLoads[url].push(cb);return true}pcmLoads[url]=[cb];try{var s=document.createElement('script');s.type='text/javascript';s.src=fileUrl(url);s.onload=function(){var a=pcmLoads[url]||[];delete pcmLoads[url];for(var i=0;i<a.length;i++)a[i](true)};s.onerror=function(){var a=pcmLoads[url]||[];delete pcmLoads[url];for(var i=0;i<a.length;i++)a[i](false)};(document.getElementsByTagName('head')[0]||document.body).appendChild(s);return true}catch(e){var a=pcmLoads[url]||[];delete pcmLoads[url];for(var i=0;i<a.length;i++)a[i](false);return false}}
function playEmbedded(c,onDone){var ac=ensureCtx(),pack=pcmPack(c),key=(c&&c.pcmKey)||(c&&c.id),b64=pack&&pack.clips&&pack.clips[key],raw,buf,data,src,i,rate;if(!b64&&c&&c.pcmScript){loadPcmPack(c,function(ok){if(ok)playEmbedded(c,onDone);else if(onDone)onDone(false,'pcm-pack-load-failed')});return true}if(!ac||!b64||!window.atob)return false;try{unlockCtx();raw=atob(b64);rate=parseInt(pack.rate,10)||16000;buf=ac.createBuffer(1,raw.length,rate);data=buf.getChannelData(0);for(i=0;i<raw.length;i++)data[i]=(raw.charCodeAt(i)-128)/128;src=ac.createBufferSource();currentSource=src;src.buffer=buf;src.connect(ac.destination);src.onended=function(){if(currentSource===src)currentSource=null;if(onDone)onDone(true,'embedded-pcm')};if(src.start)src.start(0);else if(src.noteOn)src.noteOn(0);setStatus(c.kind==='color'?'🔊 نطق اللون من التسجيل الداخلي':'🔊 الصوت المسجل الداخلي يعمل');return true}catch(e){if(onDone)onDone(false,'embedded-error');return false}}
function playClip(c,onDone){if(!c)return false;stopRecorded();if(isLegacy()){if(playEmbedded(c,function(ok,why){if(ok){if(onDone)onDone(true,why)}else if(playWebAudio(c,function(ok2,why2){if(ok2){if(onDone)onDone(true,why2)}else playHtmlAudio(c,onDone)})){}else playHtmlAudio(c,onDone)}))return true;if(playWebAudio(c,function(ok,why){if(ok){if(onDone)onDone(true,why)}else playHtmlAudio(c,onDone)}))return true;return playHtmlAudio(c,onDone)}if(playHtmlAudio(c,function(ok,why){if(ok){if(onDone)onDone(true,why)}else if(playWebAudio(c,function(ok2,why2){if(ok2){if(onDone)onDone(true,why2)}else playEmbedded(c,onDone)})){}else playEmbedded(c,onDone)}))return true;if(playWebAudio(c,function(ok,why){if(ok){if(onDone)onDone(true,why)}else playEmbedded(c,onDone)}))return true;return playEmbedded(c,onDone)}
function playFile(text,onDone){return playClip(clipFor(text),onDone)}
function customFallback(){try{var b=$('testCustomBtn');if(b){b.click();return true}}catch(e){}return false}
function voiceKey(v){return(v.voiceURI||v.name||'')+'|'+(v.lang||'')}
function isArabic(v){var l=((v&&v.lang)||'').toLowerCase(),n=((v&&v.name)||'').toLowerCase();return l.indexOf('ar')===0||n.indexOf('arab')>=0||n.indexOf('عرب')>=0}
function selectedVoice(){var vs=[],i,s=$('voiceSelect'),key=s?s.value:'auto';try{vs=speechSynthesis.getVoices()||[]}catch(e){}if(key&&key!=='auto')for(i=0;i<vs.length;i++)if(voiceKey(vs[i])===key)return vs[i];for(i=0;i<vs.length;i++)if(isArabic(vs[i]))return vs[i];return null}
function nativeSpeak(text,done){if(!(window.speechSynthesis&&window.SpeechSynthesisUtterance)){done(false,'no-api');return}var synth=window.speechSynthesis,v=selectedVoice();if(!isMobile()&&!v){done(false,'no-arabic-desktop-voice');return}var u,started=false,finished=false,timer;try{try{synth.cancel()}catch(e){}u=new SpeechSynthesisUtterance(text);u.lang=v?(v.lang||'ar-SA'):'ar-SA';if(v)u.voice=v;var r=$('rateSelect');u.rate=r?(parseFloat(r.value)||.86):.86;u.pitch=1;u.volume=1;u.onstart=function(){started=true;setStatus('🔊 الصوت الآلي يعمل')};u.onend=function(){if(finished)return;finished=true;if(timer)clearTimeout(timer);done(true,'ended')};u.onerror=function(){if(finished)return;finished=true;if(timer)clearTimeout(timer);done(false,'error')};synth.speak(u);timer=setTimeout(function(){if(started||finished)return;finished=true;try{synth.cancel()}catch(e){}done(false,'timeout')},1400)}catch(e){done(false,'exception')}}
function speak(text,allowFallback){var c=clipFor(text);if(mode==='files'){if(c&&playClip(c,function(ok){if(!ok)customFallback()}))return true;return customFallback()}if(mode==='tts'){nativeSpeak(text,function(ok){if(!ok)setStatus('تعذر تشغيل الصوت الآلي. اختر الملفات المسجلة أو الوضع التلقائي.')});return true}if(isLegacy()&&c){if(playClip(c,function(ok){if(!ok)nativeSpeak(text,function(ok2){if(!ok2&&allowFallback!==false)customFallback()})}))return true}nativeSpeak(text,function(ok){if(!ok&&allowFallback!==false){if(c)playClip(c,function(ok2){if(!ok2)customFallback()});else customFallback()}});return true}
function unlock(){if(unlocked)return;unlocked=true;unlockCtx();ensureAudio();loadRegistry()}
function refreshInfo(){var u=userEntry(),colors=registry&&registry.colors||[];if(!u){setInfo('لا توجد حزمة صوت مطابقة للاسم «'+username()+'». توجد '+colors.length+' ملفات ألوان عامة.');return}setInfo('✅ الصوت المسجل جاهز للاسم «'+username()+'». 🎨 الألوان: '+colors.length+'. '+(isLegacy()?'تم اكتشاف جهاز قديم؛ سيستخدم التطبيق التسجيل الداخلي PCM عبر WebAudio أولاً بدون الاعتماد على ترميز MP3 أو WAV في المتصفح.':'يمكنك التبديل يدوياً بين الصوت الآلي والملفات المسجلة حتى لو كان الجهاز يدعم الاثنين.'))}
function injectUI(){var box=$('voiceSelect');if(!box||$('audioModeSelect'))return;var p=box.parentNode&&box.parentNode.parentNode;if(!p)return;var wrap=document.createElement('div');wrap.style.margin='8px 0';wrap.innerHTML='<label style="display:block;margin:6px">طريقة الصوت <select id="audioModeSelect" style="min-width:260px"><option value="auto">تلقائي ذكي: الأنسب للجهاز</option><option value="files">الملفات المسجلة فقط</option><option value="tts">الصوت الآلي فقط</option></select></label><button id="testBundledAudioBtn" type="button">🎧 اختبار تشغيل الصوت المسجل</button><button id="testColorAudioBtn" type="button">🎨 اختبار صوت الألوان</button><div id="bundledAudioInfo" style="font-size:11px;line-height:1.8;margin:7px;padding:8px;border-radius:6px;background:#eef8ff"></div>';p.appendChild(wrap);var s=$('audioModeSelect');mode=storeGet('pk_audio_mode','auto');s.value=mode;if(s.selectedIndex<0){mode='auto';s.value='auto'}s.onchange=function(){mode=this.value;storeSet('pk_audio_mode',mode);refreshInfo();setStatus(mode==='files'?'تم اختيار الملفات المسجلة':mode==='tts'?'تم اختيار الصوت الآلي':'تم اختيار الوضع التلقائي')};$('testBundledAudioBtn').onclick=function(){unlockCtx();loadRegistry(function(){var c=clipFor('مرحبا يا '+username()+'، هذا اختبار للصوت المسجل');if(!c){setStatus('لا توجد ملفات صوت مسجلة لهذا الاسم');return}playClip(c,function(ok,why){setStatus(ok?'✅ الصوت المسجل يعمل'+(why?' - '+why:''):'تعذر تشغيل التسجيل حتى عبر WebAudio')})})};$('testColorAudioBtn').onclick=function(){unlockCtx();loadRegistry(function(){var c=clipFor('اللون أزرق');if(!c){setStatus('لا توجد حزمة ألوان مسجلة');return}playClip(c,function(ok){if(!ok)setStatus('تعذر تشغيل ملف اللون')})})};refreshInfo()}
function watchName(){var b=$('saveUserBtn');if(b)b.addEventListener('click',function(){setTimeout(function(){refreshInfo();loadRegistry()},80)},false)}
function init(){mode=storeGet('pk_audio_mode','auto');injectUI();watchName();loadRegistry();document.addEventListener('mousedown',unlock,false);document.addEventListener('touchstart',unlock,false);document.addEventListener('keydown',unlock,false);setTimeout(injectUI,400);setTimeout(refreshInfo,800);setTimeout(function(){var db=$('desktopAudioTest');if(db)db.onclick=function(){unlockCtx();loadRegistry(function(){speak('مرحبا يا '+username()+'، هذا اختبار للصوت المسجل',true)})}},650)}
window.Audio360={speak:function(text,allowFallback){loadRegistry();return speak(text,allowFallback)},playRecorded:function(text){loadRegistry(function(){var c=clipFor(text);if(c)playClip(c)});return true},stop:function(){stopRecorded();try{speechSynthesis.cancel()}catch(e){}},reload:function(){registry=null;loadRegistry()},mode:function(){return mode},unlock:function(){return unlockCtx()}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,false);else init();
})();
;(function(w,d){
'use strict';
if(w.APP360_AI_SHELL||d.getElementById('app360AiShellScript'))return;
function load(){if(w.APP360_AI_SHELL||d.getElementById('app360AiShellScript'))return;var s=d.createElement('script');s.id='app360AiShellScript';s.src='../../../assets/js/app360-ai-shell.js?v=2';s.async=true;(d.head||d.getElementsByTagName('head')[0]||d.body).appendChild(s)}
if(d.readyState==='loading'){if(d.addEventListener)d.addEventListener('DOMContentLoaded',load,false);else if(w.attachEvent)w.attachEvent('onload',load)}else load();
})(window,document);
