(function(w,doc){
'use strict';
var D=w.MARKET_CONTENT,M=w.MARKET_MODEL,PACK=w.APP360_MARKET_OBJECTS,E=w.MARKET_EXERCISES,ROOT='../../../',demo=null,builderRecipe=null,builderSelected=[],builderMarket='fruits',builderType='count',builderPreview=null,S,profile='',storageKey='',memory={},corruptProfiles={},storageOK=true,corrupt=false,view='library',savedId='',builderProduct='apple',builderSource='',pendingDelete='',noticeTimer,offlineReady=false,audio=new Audio(),audioPath='',audioState='idle',queue=[],serial=0,countNodes=[],speech=null;
function $(id){return doc.getElementById(id)}
function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function t(ar,en){return S&&S.language==='en'?en:ar}
function b(cmd,label,val,cls,disabled){if(label==='♪')label=t('أسمع','Listen');return '<button type="button" data-do="'+cmd+'"'+(val!==undefined?' data-value="'+esc(val)+'"':'')+' class="'+(cls||'')+'"'+(disabled?' disabled':'')+'>'+label+'</button>'}
function api(){try{if(w.parent!==w&&w.parent.APP360_FAMILY_SYNC)return w.parent.APP360_FAMILY_SYNC}catch(e){}return w.APP360_FAMILY_SYNC||null}
function identity(){var a=api(),p='';try{if(a&&a.getProfileKey)p=a.getProfileKey()}catch(e){}return p&&p!=='name:'?String(p):'local-guest'}
function coachAllowed(){var a=api(),s;try{s=a&&a.getSession?a.getSession():null}catch(e){}return !(s&&s.room&&s.role==='guest'&&s.adminRole!=='assistant')}
function focus(){var a=api();try{if(a&&a.getReadingFocusState)return a.getReadingFocusState()}catch(e){}return {enabled:true,scope:'local',canManage:false}}
function focusStrip(){var f=focus();return '<div class="focus"><label><input type="checkbox" data-focus-toggle'+(f.enabled?' checked':'')+(!f.canManage||!coachAllowed()?' disabled':'')+'>'+t('تتبع الكلمات أثناء القراءة','Follow words during reading')+'</label><small data-focus-note></small></div>'}
function syncFocus(){var f=focus();if(reader)reader.setEnabled(f.enabled);var inputs=doc.querySelectorAll('[data-focus-toggle]'),notes=doc.querySelectorAll('[data-focus-note]'),i;for(i=0;i<inputs.length;i++){inputs[i].checked=f.enabled;inputs[i].disabled=!f.canManage||!coachAllowed()}for(i=0;i<notes.length;i++)notes[i].textContent=f.scope==='individual'?t('اختيار خاص لهذا المتعلم.','An individual learner setting.'):f.scope==='session'?t('يتبع اختيار مسؤول الجلسة.','Follows the session coach.'):t('اختيار المرافق المحفوظ بين التطبيقات.','The coach setting is saved across supported apps.');if(!f.enabled)clearDynamic()}
function object(id){for(var i=0;i<PACK.items.length;i++)if(PACK.items[i].id===id)return PACK.items[i];return PACK.items[0]}
function name(id,lang){var p=object(id);return p[lang||S.language]}
function image(id){return ROOT+object(id).image}
function nameAudio(id,lang){return ROOT+object(id)['audio_'+(lang||S.language)]}
function markup(text,path){return w.APP360_READ_ALONG.markup(text,path||'dynamic:text')}
function numeral(n,lang){var value=String(n);return (lang||S.language)==='ar'?value.replace(/[0-9]/g,function(c){return '٠١٢٣٤٥٦٧٨٩'.charAt(Number(c))}):value}
function numberAudio(n,lang){lang=lang||S.language;var source=PACK.numbers[lang][String(n)];return source?ROOT+source.path:'audio/'+(lang==='ar'?'ar-':'')+'number-'+n+'.mp3'}
function term(text,path){return '<span class="ra-text" data-ra-path="'+esc(path)+'"><span class="ra-token" data-ra-index="0">'+esc(text)+'</span></span>'}
function exerciseOf(m){return m.exercise||(m.kind==='count'?(m.requests.length>1?'mixed':m.initial>m.requests[0].quantity?'return':m.initial?'fill':'count'):m.kind==='partition'?'split':m.kind)}
function playGuide(m){return guide(exerciseOf(m))}
function marketButtons(command,selected){return '<div class="market-list">'+PACK.markets.map(function(m){return b(command,'<img src="'+image(m.cover)+'" alt=""><span>'+esc(m[S.language])+'</span>',m.id,'market-chip'+(m.id===selected?' selected':''))}).join('')+'</div>'}
function recipeById(id){for(var i=0;i<S.recipes.length;i++)if(S.recipes[i].id===id)return S.recipes[i];return null}
function generated(kind,recipe){if(demo)closeDemo();var out;try{out=E.generate(kind,recipe?recipe.market:S.market,S.level,S.language,S.recent,recipe)}catch(e){notify(t('هذا النمط يحتاج صورًا أو مجال أعداد مناسبًا.','This activity needs a suitable picture pool and number range.'));return false}if(!archive())return false;S.recent.push(out.record);S.recent=S.recent.slice(-80);S.draft=M.start(out.task,S.support);S.level=out.task.level;S.market=out.task.market;savedId='';go('play');if(S.voice)listenOrder();return true}
function listenOrder(){var d=current();if(!d)return;var m=d.task,parts=[playGuide(m).path];if(m.requests){parts.push(guide('order').path);m.requests.forEach(function(r){parts.push(numberAudio(r.quantity,m.language),nameAudio(r.product,m.language))})}else if(m.total){parts.push(guide('total').path,numberAudio(m.total,m.language),nameAudio(m.product,m.language));if(m.kind==='share')parts.push(guide('baskets').path,numberAudio(m.groups,m.language))}listen(parts)}

function guide(k){return D.guides[S.language][k]}
function instruction(text,path){return '<div class="instruction"><p>'+markup(text,path)+'</p>'+b('read','♪',path,'read-btn')+'</div>'}
function notify(s){$('notice').textContent=s;$('notice').style.display='block';clearTimeout(noticeTimer);noticeTimer=setTimeout(function(){$('notice').style.display='none'},4500)}
function storageLabel(){$('storageStatus').textContent=corrupt?t('الحفظ يحتاج استعادة؛ النسخة الأصلية محفوظة.','Save data needs recovery; the original is preserved.'):storageOK?t('حفظ محلي خاص · معاينة','Private local save · preview'):t('حفظ مؤقت؛ صدّر قبل الإغلاق.','Temporary memory; export before closing.')}
function save(){if(!S)return;memory[profile]=M.copy(S);if(!corrupt)try{localStorage.setItem(storageKey,JSON.stringify(S));storageOK=true}catch(e){storageOK=false}storageLabel()}
function load(p){profile=p;storageKey='app360:a4-family-market:schema-1:'+encodeURIComponent(p);S=M.blank();corrupt=!!corruptProfiles[p];storageOK=!corrupt;if(memory[p])S=M.copy(memory[p]);else try{S=M.restore(localStorage.getItem(storageKey))}catch(e){corrupt=e.name!=='SecurityError';corruptProfiles[p]=corrupt;storageOK=false}view=S.view;if(view==='builder')view='library';if((view==='play'||view==='review')&&!S.draft)view='library';savedId='';pendingDelete='';render()}
function taskById(id){var all=D.missions.concat(S.templates);for(var i=0;i<all.length;i++)if(all[i].id===id)return all[i];return null}
function signature(d){return JSON.stringify({task:d.task,tokens:d.tokens,sequence:d.sequence,choice:d.choice,explanation:d.explanation,reflection:d.reflection,support:d.support,help_used:d.help_used,attempts:d.attempt_history.filter(function(a){return a.reason!=='saved'&&a.reason!=='review'&&a.reason!=='pause'}).map(function(a){return {reason:a.reason,support:a.support,board:a.board}})})}
function saveWork(auto){if(!S.draft)return false;var sig=signature(S.draft);for(var i=0;i<S.saved.length;i++)if(signature(S.saved[i])===sig){savedId=S.saved[i].id;return true}if(S.saved.length>=50){notify(t('المعرض ممتلئ؛ تابع اللعب أو صدّر طلبات واحذف نسخة لحفظ طلب جديد.','The gallery is full; keep playing, or export and remove a copy to save a new order.'));return false}var a=M.saved(S);savedId=a.id;save();try{var ev=doc.createEvent('CustomEvent');ev.initCustomEvent('app360:market:saved',false,false,{id:a.id});doc.dispatchEvent(ev)}catch(e){}if(!auto)notify(t('حفظنا طلبك ومحاولتك.','Your order and attempt are saved.'));return true}
function archive(){var d=S.draft;if(!d)return true;if(d.history.length||d.future.length||d.attempt_history.length||d.explanation||d.checked){M.checkpoint(d,'transition');var sig=signature(d),last=S.practice[S.practice.length-1];if(!last||signature(last)!==sig){var a=M.artifact(d);a.history=[];a.future=[];S.practice.push(a);S.practice=S.practice.slice(-20)}save()}return true}
function open(id){var m=taskById(id);if(!m)return false;if(m.seller){builderSource=id;builderProduct=m.product;builderType='count';builderMarket=object(m.product).market;builderSelected=E.market(builderMarket).products.slice();builderRecipe=null;go('builder');return true}if(S.draft&&S.draft.task.id===id){S.language=m.language;S.level=m.level;go(S.draft.stage==='review'?'review':'play');return true}if(!archive())return false;S.draft=M.start(m,S.support);S.language=m.language;S.level=m.level;go('play');if(S.voice)listen([m.audio.prompt]);return true}
function go(next,push){if(demo)closeDemo();save();stopAudio();view=next;S.view=next;pendingDelete='';save();if(push!==false)try{history.pushState({market:true,view:next},'','')}catch(e){}render();w.scrollTo(0,0)}
function levelButtons(){return '<div class="levels">'+D.levels.map(function(l){return b('level',esc(l[S.language])+'<small>'+numeral(l.age)+'</small>',l.level,'level'+(S.level===l.level?' selected':''))}).join('')+'</div>'}
function library(){var g=guide('library'),out='<section class="hero simple-hero"><div><h1>'+t('اختر تجربة وابدأ','Choose an activity and play')+'</h1><p>'+t('صور جديدة وطلب مختلف في كل مرة.','New pictures and a different order each time.')+'</p></div><img src="assets/market.svg" alt=""></section><h2 class="market-heading">'+t('اختر عالم الصور','Choose a picture world')+'</h2>'+marketButtons('market',S.market);
if(S.draft)out+='<div class="resume-card"><span>'+t('طلبك ينتظرك','Your order is waiting')+'</span>'+b('resume',t('أكمل اللعب','Continue playing'),undefined,'primary')+'</div>';
out+='<div class="row between experience-heading"><h2>'+t('تجارب جاهزة للعب','Ready-to-play activities')+'</h2><details class="level-picker"><summary>'+t('المستوى','Level')+'</summary>'+levelButtons()+'</details></div><div class="experience-grid">';var ps=E.market(S.market).products;E.types.forEach(function(x,i){var art='<div class="experience-pictures">';var sequence=x.id==='pattern'?[ps[0],ps[1],ps[0]]:x.id==='mixed'?[ps[1],ps[2]]:[ps[i%ps.length],ps[i%ps.length]];sequence.forEach(function(p){art+='<img src="'+image(p)+'" alt="">'});art+='</div>';out+=b('experience',art+'<strong>'+esc(x[S.language])+'</strong><span>'+esc(x['description_'+S.language])+'</span>'+(x.id==='count'?'<small class="start-here">'+t('ابدأ هنا','Start here')+'</small>':''),x.id,'experience-card')});out+='</div>';
if(S.recipes.length||S.templates.length){out+='<h2 class="section-gap">'+t('تجارب صنعها المربي','Coach-made activities')+'</h2><div class="experience-grid">';S.recipes.forEach(function(r){out+=b('recipe-play','<img class="recipe-cover" src="'+image(r.products[0])+'" alt=""><strong>'+esc(r.title||E.type(r.type)[S.language])+'</strong><span>'+esc(E.market(r.market)[S.language])+' · '+t('طلب جديد كل مرة','A new order each time')+'</span>',r.id,'experience-card')});S.templates.forEach(function(m){out+=b('open',esc(m.title),m.id,'experience-card')});out+='</div>'}return out+'<p class="muted">'+t('يمكن للمربي اختيار الصعوبة وبناء تجارب خاصة.','The coach can choose the difficulty and make activities.')+'</p>'}
function kindName(k){var names={count:['أجهز طلبًا','Prepare an order'],share:['أوزع بالتساوي','Share equally'],partition:['أقسم العدد','Split a number'],compare:['أقارن','Compare'],pattern:['أكتشف نمطًا','Find a pattern'],combine:['أجمع','Combine'],measure:['أقيس','Measure']};return t(names[k][0],names[k][1])}
function tokenHTML(x,d,interactive,index){var act=d.task.kind==='compare'?null:'move',zone=d.task.kind==='combine'&&x.zone!==2?2:-1,n=name(x.product,d.task.language);return interactive&&act?'<button class="token" data-do="'+act+'" data-value="'+x.id+'" data-destination="'+zone+'" draggable="true" data-token="'+x.id+'" data-count-token="'+x.id+'" aria-label="'+esc(n+' · '+t(zone===2?'أنقل إلى الطلب':'أعيد إلى الرف',zone===2?'Move to the order':'Return to the shelf'))+'"><img src="'+image(x.product)+'" alt="">'+(d.representation==='frame'?'<span class="token-count">'+numeral(index+1)+'</span>':'')+'</button>':'<span class="token" data-count-token="'+x.id+'"><img src="'+image(x.product)+'" alt="'+esc(n)+'"></span>'}
function request(d){var m=d.task,out='<div class="request-card"><strong>'+markup(guide(m.requests?'order':'total').text,guide(m.requests?'order':'total').path)+'</strong>';if(m.requests)m.requests.forEach(function(r){out+='<div class="request-line"><img src="'+image(r.product)+'" alt=""><span>'+term(name(r.product,m.language),nameAudio(r.product,m.language))+'</span><span class="quantity">'+term(numeral(r.quantity,m.language),numberAudio(r.quantity,m.language))+'</span></div>'});else if(m.total)out+='<div class="request-line"><img src="'+image(m.product)+'" alt=""><span>'+term(name(m.product,m.language),nameAudio(m.product,m.language))+'</span><span class="quantity">'+term(numeral(m.total,m.language),numberAudio(m.total,m.language))+'</span></div>';
if(m.kind==='share')out+='<div class="basket-goal">'+markup(guide('baskets').text,guide('baskets').path)+' <strong>'+term(numeral(m.groups,m.language),numberAudio(m.groups,m.language))+'</strong></div>';if(m.kind==='compare'||m.kind==='pattern')out+='<span>'+esc(E.type(exerciseOf(m))[m.language])+'</span>';return out+'</div>'}
function zoneHTML(d,z,interactive){var tsk=d.task,items=d.tokens.filter(function(x){return x.zone===z}),title=tsk.kind==='combine'?(z===2?t('سلة الطلب','Order basket'):t('مجموعة ','Group ')+numeral(z+1)):tsk.kind==='measure'?t('طول الرف','Shelf length'):tsk.groups>1?t('سلة ','Basket ')+numeral(z+1):t('سلتي','My basket'),out='<section class="basket'+(interactive&&d.destination===z?' active':'')+'" data-zone="'+z+'"><div class="basket-label">'+(interactive&&tsk.kind!=='combine'&&tsk.groups>1?b('destination',title,z,d.destination===z?'selected':''): '<strong>'+title+'</strong>')+(interactive?b('count',t('أعدّ ','Count ')+term(numeral(items.length),numberAudio(items.length,d.task.language)),z,'small count-btn'):'<span class="quantity">'+numeral(items.length)+'</span>')+'</div>';
var frame=d.representation==='frame'||tsk.kind==='measure';if(frame){var slots=tsk.kind==='measure'?tsk.requests[0].quantity:Math.max(10,Math.ceil(items.length/10)*10);out+='<div class="frame'+(tsk.kind==='measure'?' measure':'')+'">';for(var i=0;i<slots;i++)out+=items[i]?tokenHTML(items[i],d,interactive,i):'<span class="slot'+(tsk.kind==='measure'?' measure':'')+'" aria-hidden="true"></span>';out+='</div>';if(items.length>slots)out+='<div class="token-list overflow-cards">'+items.slice(slots).map(function(x,i){return tokenHTML(x,d,interactive,slots+i)}).join('')+'</div>'}else out+='<div class="token-list">'+items.map(function(x,i){return tokenHTML(x,d,interactive,i)}).join('')+'</div>';if(!items.length&&!frame)out+='<div class="empty">'+t('مكان بطاقاتك هنا','Your cards go here')+'</div>';return out+'</section>'}
function board(d,interactive){var m=d.task,out='';if(m.kind==='pattern'){out='<div class="pattern-shelf" aria-label="'+t('ترتيب الصور','Picture sequence')+'">';for(var i=0;i<m.length;i++)out+=d.sequence[i]?'<span class="token'+(i<m.prefix?' locked':'')+'"><img src="'+image(d.sequence[i])+'" alt="'+esc(name(d.sequence[i],m.language))+'"></span>':'<span class="slot'+(i===d.sequence.length?' next-slot':'')+'" aria-hidden="true">'+(i===d.sequence.length?t('؟','?'):'')+'</span>';return out+'</div>'}if(m.kind==='compare'){out='<section class="panel compare-board'+(d.representation==='frame'?' comparison-paired':'')+'">';for(var z=0;z<2;z++)out+='<div class="compare-group"><strong class="row-label row-'+z+'">'+t(z===0?'الصف الأول':'الصف الثاني',z===0?'First row':'Second row')+'</strong><div class="comparison-row'+(z===1&&d.representation!=='frame'?' spread':'')+'">'+d.tokens.filter(function(x){return x.zone===z}).map(function(x,i){return tokenHTML(x,d,false,i)}).join('')+'</div></div>';out+='</section>';if(interactive)out+='<div class="compare-choices">'+b('choice',t('الصف الأول أكثر','First row has more'),'a','row-0'+(d.choice==='a'?' selected':''))+b('choice',t('العددان متساويان','Both have the same number'),'equal',d.choice==='equal'?'selected':'')+b('choice',t('الصف الثاني أكثر','Second row has more'),'b','row-1'+(d.choice==='b'?' selected':''))+'</div>';return out}
out='<div class="zones '+(m.kind==='combine'?'combine-zones':'')+'">';for(var j=0;j<(m.groups||1);j++)out+=zoneHTML(d,j,interactive);return out+'</div>'}
function stock(d){var tsk=d.task;if(tsk.kind==='compare'||tsk.kind==='combine'||exerciseOf(tsk)==='return')return '';var ps=tsk.kind==='pattern'?tsk.rule.filter(function(x,i,a){return a.indexOf(x)===i}):tsk.requests?tsk.requests.map(function(r){return r.product}):[tsk.product];return '<div class="stock">'+ps.map(function(p){var n=name(p,tsk.language),path=nameAudio(p,tsk.language),left=M.count(d,-1,p),disabled=tsk.kind==='pattern'?d.sequence.length>=tsk.length:left===0;return '<div class="stock-product">'+b(tsk.kind==='pattern'?'append':'take','<img src="'+image(p)+'" alt=""><span>'+term(n,path)+'<small>'+t('أضيف بطاقة','Add a card')+'</small></span>',p,'take',disabled)+b('read','♪',path,'small')+'</div>'}).join('')+'</div>'}
function current(){return savedId?S.saved.filter(function(x){return x.id===savedId})[0]||S.draft:S.draft}
function feedback(d){var r=M.evaluate(d),g=guide(r.matches?'match':'retry');return '<div class="feedback'+(!r.matches?' check-again':'')+'"><p>'+markup(g.text,g.path)+'</p>'+b('read','♪',g.path,'small')+'</div>'}
function playScreen(){var d=S.draft,m=d.task,g=playGuide(m),out='<div class="row between task-heading"><h1>'+esc(E.type(exerciseOf(m))[S.language])+'</h1>'+b('library',t('التجارب','Activities'),undefined,'small')+'</div><div class="play-help">'+b('listen-order',t('أسمع المطلوب','Hear the order'),undefined,'read-btn')+b('demo-open',t('أرني كيف ألعب','Show me how'),undefined,'secondary')+'</div><p class="play-instruction">'+markup(g.text,g.path)+'</p>'+request(d)+'<div class="play-layout"><div class="work">';
if(m.kind!=='combine')out+=stock(d);out+=board(d,true);if(d.checked)out+=feedback(d);out+='<div class="row board-tools">'+b('undo',t('تراجع','Undo'),undefined,'small',!d.history.length)+b('redo',t('إعادة','Redo'),undefined,'small',!d.future.length)+b('representation',d.representation==='frame'?t('أرى الصور','Show pictures'):t('أطابق وأعدّ','Match & count'),undefined,'small')+b('hint',t('ساعدني','Help me'),undefined,'small')+(m.kind==='pattern'?b('pattern-remove',t('أعيد آخر صورة','Return the last picture'),undefined,'small',d.sequence.length<=m.prefix):'')+'</div><div class="next-actions">'+b('check',t('هل جهزت الطلب؟','Is my order ready?'),undefined,'primary')+(d.checked&&M.evaluate(d).matches?b('new-try',t('تجربة جديدة','A new activity'),undefined,'secondary'):'')+'</div>';
if(d.checked&&M.evaluate(d).matches)out+='<div class="row">'+b('save-work',t('أحفظ طلبي','Save my order'),undefined,'')+b('review',t('أحكي طريقتي','Tell my way'),undefined,'')+'</div>';
out+='<details class="coach-details"><summary>'+t('للمرافق: الحكي والتوجيه','For the grown-up: telling and guidance')+'</summary><div class="panel"><label class="label" for="explanation">'+t('ما يحكيه الطفل · اختياري','The child’s own words · optional')+'</label><textarea id="explanation" maxlength="600" data-field="explanation">'+esc(d.explanation)+'</textarea>'+b('read',t('أسمع كلامي','Hear my words'),'dynamic:explanation','small')+focusStrip()+b('review',t('المراجعة والطباعة','Review and print'),undefined,'small')+b('pause',t('أستريح وأعود','Pause and return'),undefined,'small')+'</div></details></div></div>';return out}
function equation(d){var tsk=d.task,c=M.evaluate(d).counts;if(!d.checked||!M.evaluate(d).matches)return '';if(tsk.kind==='partition')return c[0]+' + '+c[1]+' = '+tsk.total;if(tsk.kind==='combine')return tsk.left+' + '+(tsk.total-tsk.left)+' = '+tsk.total;if(tsk.kind==='share')return tsk.total+' ÷ '+tsk.groups+' = '+c[0];if(tsk.requests&&tsk.initial>tsk.requests[0].quantity)return tsk.initial+' − '+(tsk.initial-tsk.requests[0].quantity)+' = '+tsk.requests[0].quantity;return ''}
function review(){var d=current();if(!d)return gallery();var m=d.task,g=guide('review'),out='<div class="row between"><h1>'+t('طلبي وطريقتي','My order and my way')+'</h1>'+b(savedId?'saved':'play',t('أعود','Back'),undefined,'small')+'</div>'+instruction(g.text,g.path)+'<div class="review-layout"><section class="panel"><h2>'+esc(m.title)+'</h2>'+request(d)+board(d,false)+feedback(d);var eq=equation(d);if(eq)out+='<details><summary>'+t('أرى الرمز بعد البطاقات','See the symbol after the cards')+'</summary><p class="equation">'+esc(numeral(eq,m.language))+'</p></details>';if(d.explanation)out+='<p class="tip">'+esc(d.explanation)+'</p>';if(!savedId)out+='<label class="label" for="reflection">'+t('ما الذي جرّبته أو سأغيّره؟ · اختياري','What did I try, or what will I change? · optional')+'</label><textarea id="reflection" data-field="reflection" maxlength="500">'+esc(d.reflection)+'</textarea>';else if(d.reflection)out+='<p>'+esc(d.reflection)+'</p>';out+='<div class="row">'+(!savedId?b('save-work',t('أحفظ طلبي','Save my order'),undefined,'primary'):b('edit-work',t('أجرب نسخة جديدة','Try a new copy'),d.id,'primary'))+b('print',t('أطبع','Print'),undefined,'')+b('export-one',t('أصدّر','Export'),undefined,'')+'</div></section><aside class="side"><section class="panel"><h2>'+t('من الشاشة إلى الطاولة','From screen to table')+'</h2><p>'+markup(m.real,m.audio.real||'dynamic:real')+'</p>'+b('read','♪',m.audio.real||'dynamic:real','small')+'<p class="muted">'+markup(guide('safety').text,guide('safety').path)+'</p><div class="transfer"><h3>'+t('أنا البائع الآن','I am the seller now')+'</h3><p>'+t('أصمم طلبًا وأترك المرافق يجربه.','I make an order and let my grown-up try it.')+'</p>'+b('swap-role',t('نبدّل الدور','Swap roles'),undefined,'secondary')+'</div></section>';
if(d.attempt_history.length)out+='<section class="panel"><h3>'+t('محاولاتي الأصلية','My original attempts')+'</h3>'+d.attempt_history.map(function(a,i){return b('restore-attempt',t('محاولة ','Attempt ')+numeral(i+1),i,'attempt')}).join('')+'</section>';return out+'</aside></div>'}
function gallery(){var out='<div class="row between"><h1>'+t('طلباتي المحفوظة','My saved orders')+'</h1>'+b('library',t('أعود للسوق','Back to market'),undefined,'primary')+'</div>';if(!S.saved.length)out+='<section class="panel"><p>'+t('لم تحفظ طلبًا بعد. ابدأ بطلب صغير.','No saved orders yet. Start with a little order.')+'</p></section>';out+='<div class="cards">';S.saved.slice().reverse().forEach(function(d){var r=M.evaluate(d);out+='<article class="card gallery-card"><img src="'+image(d.task.product)+'" alt=""><h2>'+esc(d.task.title)+'</h2><p>'+t('البطاقات في محاولتي: ','Cards in my attempt: ')+r.counts.map(function(n){return numeral(n,d.task.language)}).join(' · ')+'</p><div class="row">'+b('open-work',t('أرى طلبي','View'),d.id,'primary')+b('delete',pendingDelete===d.id?t('تأكيد الحذف','Confirm delete'):t('حذف','Delete'),d.id,'small danger')+'</div></article>'});out+='</div><div class="panel"><div class="row">'+b('export-all',t('تصدير الطلبات','Export orders'),undefined,'',!S.saved.length)+'<label class="small">'+t('استيراد نسخة','Import a copy')+'<input type="file" id="importFile" accept="application/json,.json"></label></div><p class="muted">'+t('ملف التصدير يتضمن الطلبات والتفسير المكتوب. يستبعد الحساب وملاحظات المرافق الخاصة.','Export includes orders and written explanations. Account identity and private coach notes are excluded.')+'</p></div>';return out}
function builderInit(){if(!builderRecipe){builderMarket=builderMarket||S.market;builderRecipe=E.defaultRecipe(builderType,builderMarket,S.level);builderRecipe.id=M.id();builderSelected=builderRecipe.products.slice()}return builderRecipe}
function builder(){var r=builderInit(),out='<div class="row between"><h1>'+t('مصنع التجارب','Activity workshop')+'</h1>'+b('coach',t('أعود للمربي','Back to coach'),undefined,'small')+'</div><p class="tip">'+markup(guide('coach').text,guide('coach').path)+'</p>'+b('read',t('أسمع الطريقة','Hear how'),guide('coach').path,'small')+'<section class="panel"><h2>'+t('ما الذي نتعلمه؟','What shall we practise?')+'</h2><div class="recipe-types">';E.types.forEach(function(x){out+=b('builder-type',esc(x[S.language]),x.id,r.type===x.id?'selected':'')});out+='</div><h2 class="section-gap">'+t('عالم الصور','Picture world')+'</h2>'+marketButtons('builder-market',r.market)+'<p>'+t('اختر الصور التي تتغير بينها الطلبات.','Choose pictures that orders can rotate between.')+'</p><div class="builder-products">';E.market(r.market).products.forEach(function(p){out+=b('builder-toggle','<img src="'+image(p)+'" alt=""><span>'+esc(name(p))+'</span>',p,r.products.indexOf(p)>=0?'selected':'')});out+='</div><div class="builder-fields"><div><label class="label" for="builderTitle">'+t('اسم النمط · اختياري','Pattern name · optional')+'</label><input id="builderTitle" type="text" maxlength="100" value="'+esc(r.title)+'"></div>';
if(r.type!=='pattern'){out+='<div><label class="label" for="builderMin">'+t('الكمية من','Quantity from')+'</label>'+rangeSelect('builderMin',r.min,r.type==='compare'?10:r.type==='measure'?8:r.type==='return'?19:20)+'</div><div><label class="label" for="builderMax">'+t('إلى','To')+'</label>'+rangeSelect('builderMax',r.max,r.type==='compare'?10:r.type==='measure'?8:r.type==='return'?19:20)+'</div>'}
if(r.type==='share')out+='<div><label class="label" for="builderGroups">'+t('عدد السلال','Number of baskets')+'</label>'+rangeSelect('builderGroups',r.groups,4,2)+'</div>';
if(r.type==='pattern')out+='<div><label class="label" for="builderRule">'+t('ترتيب التكرار','Repeating order')+'</label><select id="builderRule"><option value="alternate"'+(r.pattern==='alternate'?' selected':'')+'>'+t('صورتان بالتبادل','Two alternating pictures')+'</option><option value="double"'+(r.pattern==='double'?' selected':'')+'>'+t('صورتان من الأولى ثم الثانية','Two of the first, then the second')+'</option><option value="three"'+(r.pattern==='three'?' selected':'')+'>'+t('ثلاث صور بالتتابع','Three pictures in sequence')+'</option></select></div>';
if(r.type!=='pattern')out+='<div><label class="label" for="builderStrategy">'+t('كيف تتغير الطلبات؟','How do orders change?')+'</label><select id="builderStrategy"><option value="varied"'+(r.strategy==='varied'?' selected':'')+'>'+t('أغيّر الصورة والكمية','Vary picture and quantity')+'</option><option value="ascending"'+(r.strategy==='ascending'?' selected':'')+'>'+t('أزيد الكمية تدريجيًا ثم أبدأ من جديد','Build quantity gradually, then begin again')+'</option></select></div>';
out+='</div><div id="builderError" role="status"></div><div id="builderPreview" class="builder-preview"></div><div class="row">'+b('create-task',t('أجرب الآن','Try it now'),undefined,'primary')+(coachAllowed()?b('save-template',t('أحفظ كنمط جاهز','Save as a ready activity'),undefined,'secondary'):'')+'</div></section>';return out}
function rangeSelect(id,value,max,min){var out='<select id="'+id+'">';for(var n=min||1;n<=max;n++)out+='<option value="'+n+'"'+(n===value?' selected':'')+'>'+numeral(n)+'</option>';return out+'</select>'}
function readBuilder(){var r=builderInit();['Min','Max','Groups'].forEach(function(k){var el=$('builder'+k);if(el)r[k.toLowerCase()]=Number(el.value)});if($('builderTitle'))r.title=$('builderTitle').value;if($('builderRule'))r.pattern=$('builderRule').value;if($('builderStrategy'))r.strategy=$('builderStrategy').value;return r}
function builderControls(){var r=readBuilder(),box=$('builderPreview');if(!box)return;try{var clean=E.recipe(r),sample=E.generate(r.type,r.market,r.level,S.language,[],clean,function(){return .37});builderPreview=sample.task;box.innerHTML='<h3>'+t('معاينة الطلب','Order preview')+'</h3>'+request(M.start(sample.task,S.support))+'<p class="muted">'+t('المعاينة مثال. التجربة التالية تتغير داخل الخيارات التي اخترتها.','This is an example. Future activities vary within your choices.')+'</p>';$('builderError').textContent=''}catch(e){builderPreview=null;box.innerHTML='';$('builderError').textContent=t('اختر صورًا كافية ومدى صحيحًا. التوزيع يحتاج كمية تقبل القسمة على السلال؛ القياس حتى ثماني وحدات، والمقارنة حتى عشر بطاقات.','Choose enough pictures and a valid range. Sharing needs a divisible total; measurement holds up to eight units and comparison up to ten cards.')}}
function storeRecipe(){if(!coachAllowed())return;try{var r=E.recipe(readBuilder()),old=recipeById(r.id);if(!old){if(S.recipes.length>=20)throw Error('recipe-limit');S.recipes.push(M.copy(r))}else for(var i=0;i<S.recipes.length;i++)if(S.recipes[i].id===r.id)S.recipes[i]=M.copy(r);save();notify(t('حفظنا نمطًا يولّد طلبات جديدة في صفحة اللعب.','A pattern that makes new orders is saved on the play page.'))}catch(e){builderControls()}}
function importRecipes(f){if(!f||!coachAllowed())return;if(f.size>1024*1024){notify(t('ملف الأنماط كبير جدًا.','The pattern file is too large.'));return}var owner=profile,fr=new FileReader();fr.onload=function(){if(owner!==profile||!coachAllowed())return;try{var recipes=E.importRecipes(String(fr.result));if(S.recipes.length+recipes.length>20)throw Error('recipe-limit');S.recipes=S.recipes.concat(recipes);save();render();notify(t('استوردنا الأنماط كنسخ مستقلة.','The patterns imported as independent copies.'))}catch(e){notify(t('ملف الأنماط غير صالح؛ لم نغيّر تجاربك.','The pattern file is invalid; your activities are unchanged.'))}};fr.readAsText(f)}
function openDemo(){if(!S.draft)return;stopAudio();var focusNode=doc.activeElement;demo={draft:M.start(S.draft.task,S.support),step:0,focusNode:focusNode,overflow:doc.body.style.overflow};doc.body.style.overflow='hidden';$('app').setAttribute('aria-hidden','true');renderDemo();if(S.voice)listen([guide('demo').path,playGuide(demo.draft.task).path])}
function renderDemo(){if(!demo)return;var d=demo.draft,g=playGuide(d.task),ps=d.task.rule||d.task.requests&&d.task.requests.map(function(r){return r.product})||[d.task.product];$('demoLayer').hidden=false;$('demoLayer').innerHTML='<div class="demo-dialog" role="dialog" aria-modal="true" aria-labelledby="demoTitle"><div class="row between"><h2 id="demoTitle">'+t('أرني كيف ألعب','Show me how')+'</h2>'+b('demo-close',t('أجرب بنفسي','I will try'),undefined,'primary')+'</div><p class="tip">'+markup(guide('demo').text,guide('demo').path)+'</p><p>'+markup(g.text,g.path)+'</p>'+request(d)+'<div class="demo-source">'+ps.filter(function(p,i,a){return a.indexOf(p)===i}).map(function(p){return '<img src="'+image(p)+'" alt="'+esc(name(p))+'">'}).join('')+'</div>'+board(d,false)+'<div class="row between demo-controls"><span>'+t('خطوة ','Step ')+numeral(demo.step)+'</span>'+b('demo-next',demo.step? t('الخطوة التالية','Next step'):t('أرى أول نقرة','Show the first tap'),undefined,'secondary',demo.step>=2)+'</div></div>';reader.refresh();$('demoLayer').querySelector('[data-do="demo-close"]').focus()}
function advanceDemo(){if(!demo||demo.step>=2)return;stopAudio();var d=demo.draft,m=d.task,step=demo.step,i;if(m.kind==='pattern')M.append(d,m.rule[d.sequence.length%m.rule.length]);else if(m.kind==='compare')d.representation='frame';else if(m.kind==='combine'){var token=d.tokens.filter(function(x){return x.zone===step})[0];if(token)M.move(d,token.id,2)}else if(exerciseOf(m)==='return'){var extra=d.tokens.filter(function(x){return x.zone===0})[0];if(extra)M.move(d,extra.id,-1)}else {var product=m.requests?m.requests[Math.min(step,m.requests.length-1)].product:m.product;M.take(d,product,m.kind==='share'||m.kind==='partition'?step%m.groups:0)}demo.step++;renderDemo();if(S.voice)listen([playGuide(m).path])}
function closeDemo(){if(!demo)return;var old=demo;demo=null;stopAudio();$('demoLayer').hidden=true;$('demoLayer').innerHTML='';$('app').removeAttribute('aria-hidden');doc.body.style.overflow=old.overflow;if(old.focusNode&&doc.documentElement.contains(old.focusNode))old.focusNode.focus()}

function coach(){if(!coachAllowed())return '<section class="panel"><h1>'+t('للمرافق','For the coach')+'</h1><p>'+t('يدير الأب أو المربي أو المسؤول المساعد إعدادات هذه الجلسة.','The parent, teacher or authorised assistant manages session settings.')+'</p>'+b('library',t('أعود للسوق','Back to market'),undefined,'primary')+'</section>';var out='<h1>'+t('مكتب المرافق','The coach desk')+'</h1>'+focusStrip()+'<p class="tip">'+t('اختر استعدادًا مريحًا. دع الطفل يحرك البطاقات ويحكي طريقته. المزامنة تدير تتبع الكلمات للجميع أو لمتعلم محدد.','Choose a comfortable level. Let the child move the cards and explain. Family sync controls word focus for everyone or an individual learner.')+'</p><div class="coach-cols"><section class="panel"><h2>'+t('الاستعداد والمساعدة','Readiness & support')+'</h2>'+levelButtons()+'<label class="label" for="support">'+t('مقدار المساعدة','Amount of support')+'</label><select id="support">'+['together','hint','independent'].map(function(v){return '<option value="'+v+'"'+(S.support===v?' selected':'')+'>'+supportName(v)+'</option>'}).join('')+'</select><p>'+t('لاحظ: هل يفهم الطلب؟ هل يعد كل بطاقة مرة؟ هل يقارن الكمية أم طول الصف؟ جرب تمثيلًا آخر وسجل ما تغيّر.','Observe: does the child understand the order and count each card once? Do they compare quantity or row length? Try another representation and note what changes.')+'</p>'+b('builder',t('أصمم طلبًا جديدًا','Design an order'),undefined,'secondary')+'</section><section class="panel"><h2>'+t('ملاحظة خاصة','Private observation')+'</h2><label class="label" for="coachNote">'+t('ما لاحظته قبل المساعدة وبعدها؟','What did you notice before and after helping?')+'</label><textarea id="coachNote" maxlength="1200">'+esc(S.notes.observation||'')+'</textarea><p class="muted">'+t('محلية لهذا الملف، ولا تدخل التصدير الافتراضي. ليست تشخيصًا أو درجة للطفل.','Local to this profile and excluded from default export. This is not a diagnosis or a score.')+'</p>'+b('clear-note',t('أحذف الملاحظة','Delete note'),undefined,'small danger')+'</section></div>';
out+='<section class="panel"><h2>'+t('أنماط جاهزة يصنعها المربي','Ready activities made by the coach')+'</h2><p>'+t('اختر الصور وحدود الكمية وطريقة التنويع، ثم تظهر التجربة للطفل بنقرة واحدة.','Choose pictures, quantity bounds and the variation strategy. The child can then open it with one tap.')+'</p>'+b('builder',t('أبني تجربة جديدة','Build an activity'),undefined,'primary');if(S.recipes.length)out+='<div class="coach-recipes">'+S.recipes.map(function(r){return '<article><strong>'+esc(r.title||E.type(r.type)[S.language])+'</strong><p>'+esc(E.market(r.market)[S.language])+' · '+numeral(r.min)+'–'+numeral(r.max)+'</p><div class="row">'+b('recipe-play',t('أجرب','Try'),r.id,'small')+b('edit-recipe',t('أعدّل نسخة','Edit a copy'),r.id,'small')+b('delete-recipe',pendingDelete==='recipe:'+r.id?t('تأكيد الحذف','Confirm delete'):t('حذف','Delete'),r.id,'small danger')+'</div></article>'}).join('')+'</div>';out+='<div class="row section-gap">'+b('export-recipes',t('أصدّر الأنماط','Export patterns'),undefined,'small',!S.recipes.length)+'<label class="small">'+t('أستورد أنماطًا','Import patterns')+'<input type="file" id="importRecipes" accept="application/json,.json"></label></div></section>';if(S.practice.length)out+='<details class="coach-details"><summary>'+t('آخر المحاولات التلقائية','Recent automatic attempts')+'</summary><section class="panel"><p>'+t('نحتفظ بآخر عشرين محاولة تلقائية. الطلبات المحفوظة يدويًا تبقى حتى حذفها.','We keep the last twenty automatic attempts. Manually saved orders stay until you delete them.')+'</p>'+S.practice.map(function(d,i){return b('practice-copy',esc(d.task.title)+' · '+t('أفتح نسخة','Open a copy'),i,'small')}).reverse().join('')+'</section></details>';if(S.templates.length)out+='<section class="panel"><h2>'+t('قوالبي المحلية','My local templates')+'</h2>'+S.templates.map(function(m){return '<div class="row">'+b('open',esc(m.title),m.id,'')+b('remove-template',t('حذف القالب','Delete template'),m.id,'small danger')+'</div>'}).join('')+'</section>';if(corrupt)out+='<section class="panel"><p>'+t('ملف الحفظ لم يُستبدل. نزّل نسخة خام قبل إنشاء حفظ جديد.','The save file has not been replaced. Download a raw backup before creating a new save.')+'</p>'+b('raw-backup',t('نسخة خام','Raw backup'),undefined,'')+b('reset-corrupt',t('أبدأ حفظًا جديدًا','Start a new save'),undefined,'danger')+'</section>';return out}
function supportName(v){return v==='independent'?t('محاولة مستقلة','Independent'):v==='hint'?t('تلميح عند الحاجة','Hint when needed'):t('نجرب معًا','Try together')}
function render(){doc.documentElement.lang=S.language;doc.documentElement.dir=S.language==='ar'?'rtl':'ltr';doc.body.setAttribute('dir',S.language==='ar'?'rtl':'ltr');$('brandTitle').textContent=t('سوق العائلة','Family Market');var a=api(),n='';try{n=a&&a.getName?a.getName():''}catch(e){}$('profileLabel').textContent=n||t('مدرسة العائلة 360 · 4–8','Family School 360 · 4–8');$('langAr').className=S.language==='ar'?'selected':'';$('langEn').className=S.language==='en'?'selected':'';$('voiceBtn').className=S.voice?'audio-toggle-on':'';$('voiceBtn').setAttribute('aria-pressed',String(S.voice));$('voiceBtn').textContent=t('الصوت','Sound');$('voiceBtn').setAttribute('aria-label',S.voice?t('إيقاف الصوت','Turn sound off'):t('تشغيل الصوت','Turn sound on'));$('langAr').hidden=S.language==='ar';$('langEn').hidden=S.language==='en';$('stopAudioBtn').textContent=t('إيقاف','Stop');$('app360HomeBtn').textContent=t('الرئيسية','Home');$('navLibrary').textContent=t('العب','Play');$('navSaved').textContent=t('طلباتي','My orders');$('navCoach').textContent=t('للمربي','For the coach');$('familyBtn').hidden=view!=='coach';$('appStatus').hidden=view!=='coach'&&storageOK&&!corrupt;$('familyBtn').textContent=t('المزامنة','Family sync');$('footerText').textContent=t('نعدّ ونجرّب ونتعلّم معًا.','Count, try and learn together.');$('installAppBtn').textContent=t('تثبيت','Install');$('updateAppBtn').textContent=t('تحديث','Update');$('app').innerHTML=view==='play'?playScreen():view==='review'?review():view==='saved'?gallery():view==='builder'?builder():view==='coach'?coach():library();if(view==='builder')builderControls();syncFocus();storageLabel();offlineLabel();reader.refresh()}
function clearCount(){for(var i=0;i<countNodes.length;i++)countNodes[i].className=countNodes[i].className.replace(/\s*count-active\b/g,'');countNodes=[]}
function clearDynamic(){var nodes=doc.querySelectorAll('.ra-active');for(var i=0;i<nodes.length;i++){nodes[i].className=nodes[i].className.replace(/\s*ra-active\b/g,'');nodes[i].removeAttribute('aria-current')}}
function stopAudio(){serial++;queue=[];audio.pause();audio.onended=null;audio.onplaying=null;audio.onerror=null;audioState='idle';audioPath='';if(reader)reader.stop();try{if(w.speechSynthesis)w.speechSynthesis.cancel()}catch(e){}speech=null;clearCount();clearDynamic();$('stopAudioBtn').hidden=true;$('audioState').textContent='';$('spokenPanel').hidden=true}
function resolveCue(path){if(path.indexOf('audio/')===0)return 'data/read-along.json?v=2';var word='',lang='';PACK.items.forEach(function(p){['ar','en'].forEach(function(l){if(path===ROOT+p['audio_'+l]){word=p[l];lang=l}})});['ar','en'].forEach(function(l){Object.keys(PACK.numbers[l]).forEach(function(n){if(path===ROOT+PACK.numbers[l][n].path){word=numeral(n,l);lang=l}})});if(word)return {text:word,language:lang,duration:Math.round((audio.duration||1)*1000),cues:[[0,0,Math.round((audio.duration||1)*1000)]]};return ''}
var reader=w.APP360_READ_ALONG.create({resolve:resolveCue,clock:function(){return{path:audioPath,state:audioState,time:audio.currentTime||0}},fallback:$('spokenText'),fallbackBox:$('spokenPanel'),onFamilyChange:syncFocus});
function listen(paths){stopAudio();queue=paths.filter(function(x){return !!x}).map(function(x){return typeof x==='string'?{path:x}:x});nextAudio()}
function nextAudio(){clearCount();if(!queue.length){stopAudio();return}var entry=queue.shift(),path=entry.path;if(path.indexOf('dynamic:')===0){readDynamic(path);return}var g=serial;audioPath=path;audioState='waiting';$('stopAudioBtn').hidden=false;$('audioState').textContent=t('أستمع…','Listening…');audio.src=path;audio.onplaying=function(){if(g!==serial)return;audioState='playing';reader.follow(path);if(entry.token){var node=doc.querySelector('[data-count-token="'+entry.token+'"]');if(node){node.className+=' count-active';countNodes.push(node)}}};audio.onended=function(){if(g!==serial)return;reader.stop();audioState='idle';nextAudio()};audio.onerror=function(){if(g!==serial)return;stopAudio();notify(t('الصوت غير متاح الآن؛ الصور والنص والممارسة مستمرة.','Audio is unavailable now; pictures, text and practice still work.'))};try{var p=audio.play();if(p&&p.catch)p.catch(function(){if(g===serial){stopAudio();notify(t('اضغط للاستماع مجددًا، أو تابع بالصور والنص.','Tap to listen again, or continue with pictures and text.'))}})}catch(e){stopAudio()}}
function dynamicText(path){if(path==='dynamic:prompt')return S.draft&&S.draft.task.prompt||'';if(path==='dynamic:real')return current()&&current().task.real||'';if(path==='dynamic:explanation')return current()&&current().explanation||'';if(path.indexOf('dynamic:task:')===0){var m=taskById(path.slice(13));return m&&m.title||''}return ''}
function readDynamic(path){var text=dynamicText(path),voices=[],lang=current()?current().task.language:S.language;try{voices=w.speechSynthesis?w.speechSynthesis.getVoices():[]}catch(e){}var sourceWords=String(text).match(/\S+/g)||[],words=[],local={};for(var wi=0;wi<sourceWords.length;wi++){var plain=sourceWords[wi].replace(/[*#]/g,'').replace(/^[\s.,!?،؛؟:;"'“”‘’()\[\]{}<>…+×=–—-]+|[\s.,!?،؛؟:;"'“”‘’()\[\]{}<>…+×=–—-]+$/g,'');if(/[A-Za-z0-9\u0621-\u063a\u0641-\u064a\u0660-\u0669\u0671-\u06d3\u06f0-\u06f9]/.test(plain))words.push({text:plain,index:wi})}voices.forEach(function(v){if(v.localService===true&&/^ar|^en/i.test(v.lang))local[v.lang.slice(0,2).toLowerCase()]=v});
var ok=!!w.SpeechSynthesisUtterance&&words.length>0;for(var i=0;i<words.length;i++){var l=/^[A-Za-z]/.test(words[i].text)?'en':lang;if(!local[l])ok=false}if(!ok){if(path==='dynamic:prompt'&&S.draft){var tsk=S.draft.task,parts=[guide(tsk.kind==='partition'?'share':tsk.kind==='measure'?'count':tsk.kind).path];if(tsk.requests)tsk.requests.forEach(function(r){parts.push(numberAudio(r.quantity,tsk.language),nameAudio(r.product,tsk.language))});else if(tsk.total)parts.push(numberAudio(tsk.total,tsk.language),nameAudio(tsk.product,tsk.language));queue=parts.map(function(p){return {path:p}});nextAudio();return}stopAudio();notify(t('لا يوجد صوت محلي لهذا النص الجديد. يمكنك حكايته للمرافق.','A local voice for this new text is unavailable. Tell it to your grown-up.'));return}
var s=serial,index=0,wordMode=focus().enabled,segments=[];for(var j=0;j<words.length;j++){var cleaned=words[j].text.replace(/[٠-٩۰-۹]/g,function(c){var n=c.charCodeAt(0);return String(n>=1776?n-1776:n-1632)}),language=/^[A-Za-z]/.test(cleaned)?'en':lang,last=segments[segments.length-1];if(cleaned==='عمر')cleaned='عُمَر';if(/^[0-9]+$/.test(cleaned)&&D.number_words[language]&&D.number_words[language][Number(cleaned)])cleaned=D.number_words[language][Number(cleaned)];if(!wordMode&&last&&last.lang===language){last.offsets.push(last.text.length+1);last.indices.push(words[j].index);last.text+=' '+cleaned}else segments.push({text:cleaned,lang:language,index:words[j].index,offsets:[0],indices:[words[j].index]})}
$('spokenText').innerHTML=markup(text,path);$('spokenText').setAttribute('dir',lang==='ar'?'rtl':'ltr');$('spokenPanel').hidden=false;$('stopAudioBtn').hidden=false;
function mark(index){clearDynamic();if(!focus().enabled)return;var roots=doc.querySelectorAll('[data-ra-path]');for(var i=0;i<roots.length;i++)if(roots[i].getAttribute('data-ra-path')===path){var n=roots[i].querySelector('[data-ra-index="'+index+'"]');if(n){n.className+=' ra-active';n.setAttribute('aria-current','true')}}}
function say(){if(s!==serial)return;if(index>=segments.length){stopAudio();return}var seg=segments[index],txt=seg.text.replace(/(^|\s)عمر(?=\s|[،.!؟?]|$)/g,'$1عُمَر');var u=new w.SpeechSynthesisUtterance(txt);u.lang=seg.lang==='ar'?'ar-SA':'en-US';u.voice=local[seg.lang];u.rate=.84;speech=u;u.onstart=function(){if(s===serial){audioState='playing';if(wordMode)mark(seg.index)}};u.onboundary=function(e){if(s===serial&&!wordMode){var at=0;while(at+1<seg.offsets.length&&seg.offsets[at+1]<=(e.charIndex||0))at++;mark(seg.indices[at])}};u.onend=function(){if(s===serial){index++;say()}};u.onerror=function(){if(s===serial){stopAudio();notify(t('تعذر نطق النص الجديد؛ الحكي متاح.','The new text could not be read; telling it remains available.'))}};try{w.speechSynthesis.speak(u)}catch(e){stopAudio()}}say()}
function countZone(z){var d=S.draft;if(!d)return;var items=d.tokens.filter(function(x){return x.zone===z});listen(items.length?items.map(function(x,i){return{path:numberAudio(i+1,d.task.language),token:x.id}}):[numberAudio(0,d.task.language)])}

function afterMove(p){save();render();if(S.voice){var d=S.draft;if(d.task.kind==='pattern'&&p)listen([nameAudio(p,d.task.language)]);else if(d.task.kind!=='compare')listen([numberAudio(M.count(d,d.task.kind==='combine'?2:d.destination),d.task.language)])}}
function action(cmd,value,node){if(cmd==='builder-type'){readBuilder();var previous=builderRecipe;builderRecipe=E.defaultRecipe(value,previous.market,S.level);builderRecipe.id=M.id();builderRecipe.title=previous.title;render();return}if(cmd==='builder-market'){readBuilder();var prior=builderRecipe;builderRecipe=E.defaultRecipe(prior.type,value,S.level);builderRecipe.id=M.id();builderRecipe.title=prior.title;render();return}if(cmd==='builder-toggle'){var br=readBuilder(),at=br.products.indexOf(value);if(at<0&&E.market(br.market).products.indexOf(value)>=0)br.products.push(value);else if(at>=0)br.products.splice(at,1);render();return}if(cmd==='create-task'){try{var generatedRecipe=E.recipe(readBuilder());generated(generatedRecipe.type,generatedRecipe)}catch(e){builderControls()}return}if(cmd==='save-template'){storeRecipe();return}if(cmd==='export-recipes'&&coachAllowed()){download(JSON.stringify(E.exportRecipes(S.recipes),null,2),'family-market-patterns.json','application/json');return}if(cmd==='edit-recipe'&&coachAllowed()){var editRecipe=recipeById(value);if(editRecipe){builderRecipe=M.copy(editRecipe);builderRecipe.id=M.id();go('builder')}return}if(cmd==='delete-recipe'&&coachAllowed()){if(pendingDelete!=='recipe:'+value){pendingDelete='recipe:'+value;render();return}S.recipes=S.recipes.filter(function(r){return r.id!==value});pendingDelete='';save();render();return}if(cmd==='practice-copy'&&coachAllowed()){var priorAttempt=S.practice[Number(value)];if(!priorAttempt)return;if(!archive())return;S.draft=M.artifact(priorAttempt);S.draft.id=M.id();S.draft.stage='play';savedId='';S.language=S.draft.task.language;S.level=S.draft.task.level;go('play');return}if(cmd==='experience'){generated(value);return}if(cmd==='recipe-play'){var rr=recipeById(value);if(rr)generated(rr.type,rr);return}if(cmd==='market'){E.market(value);S.market=value;save();render();return}if(cmd==='new-try'){var dm=current();if(dm){var rp=recipeById(dm.task.recipe_ref)||dm.task.recipe_spec;generated(exerciseOf(dm.task),rp)}return}if(cmd==='listen-order'){listenOrder();return}if(cmd==='demo-open'){openDemo();return}if(cmd==='demo-next'){advanceDemo();return}if(cmd==='demo-close'){closeDemo();return}if(cmd==='stop'){stopAudio();return}if(cmd==='read'){listen([value]);return}if(cmd==='family'){save();var a=api();if(a&&a.open)a.open();else notify(t('جارٍ تجهيز المزامنة.','Family sync is getting ready.'));return}if(cmd==='home'){save();stopAudio();try{if(w.parent!==w&&w.parent.APP360_FAMILY_SHELL){w.parent.APP360_FAMILY_SHELL.closeApp();return}}catch(e){}location.href='../../../index.html';return}
if(cmd==='voice'){S.voice=!S.voice;stopAudio();save();render();return}if(cmd==='level'){S.level=Number(value)||1;save();render();return}if(cmd==='language'){if(value!=='ar'&&value!=='en')return;S.language=value;go('library');return}if(cmd==='library'||cmd==='saved'||cmd==='coach'){savedId='';go(cmd);return}if(cmd==='open'){open(value);return}if(cmd==='resume'||cmd==='play'){savedId='';if(S.draft){S.language=S.draft.task.language;S.level=S.draft.task.level;S.draft.stage='play';S.draft.state='in_progress';go('play')}return}
if(cmd==='builder'||cmd==='swap-role'){builderProduct=current()?current().task.product:'apple';builderSource='';savedId='';builderRecipe=null;builderMarket=S.market;builderSelected=E.market(builderMarket).products.slice();builderType=current()?exerciseOf(current().task):'count';go('builder');return}if(cmd==='builder-product'){if(M.products.indexOf(value)<0)return;builderProduct=value;var nodes=doc.querySelectorAll('[data-do="builder-product"]');for(var i=0;i<nodes.length;i++)nodes[i].className=nodes[i].getAttribute('data-value')===value?'selected':'';if(S.voice)listen([nameAudio(value)]);return}
if(cmd==='remove-template'&&coachAllowed()){S.templates=S.templates.filter(function(m){return m.id!==value});save();render();return}if(cmd==='clear-note'&&coachAllowed()){S.notes={};save();render();return}if(cmd==='raw-backup'){try{download(localStorage.getItem(storageKey)||'','market-raw-backup.json','application/json')}catch(e){}return}if(cmd==='reset-corrupt'&&coachAllowed()){corrupt=false;delete corruptProfiles[profile];save();render();return}
if(cmd==='open-work'){savedId=value;var work=current();if(work){S.language=work.task.language;S.level=work.task.level}go('review');return}if(cmd==='delete'){if(pendingDelete!==value){pendingDelete=value;render();return}S.saved=S.saved.filter(function(x){return x.id!==value});pendingDelete='';save();render();return}if(cmd==='export-all'){download(JSON.stringify(M.exportData(S.saved),null,2),'family-market-orders.json','application/json');return}if(cmd==='export-one'){var ex=current();if(ex)download(JSON.stringify(M.exportData([ex]),null,2),'family-market-order.json','application/json');return}if(cmd==='print'){printWork(current());return}if(cmd==='edit-work'){var original=current();if(!original||!archive())return;S.draft=M.artifact(original);S.draft.id=M.id();S.draft.stage='play';S.draft.state='in_progress';savedId='';S.language=S.draft.task.language;S.level=S.draft.task.level;go('play');return}if(cmd==='restore-attempt'){var work=current(),a=work&&work.attempt_history[Number(value)];if(!a||!archive())return;S.draft=M.artifact(work);S.draft.id=M.id();M.setBoard(S.draft,a.board);S.draft.stage='play';savedId='';S.language=S.draft.task.language;go('play');return}
var d=S.draft;if(!d)return;if(cmd==='destination'){d.destination=Number(value);save();render();return}if(cmd==='take'){if(M.take(d,value,d.destination))afterMove(value);return}if(cmd==='append'){if(M.append(d,value))afterMove(value);return}if(cmd==='pattern-remove'){if(M.removePattern(d))afterMove();return}if(cmd==='move'){var token=d.tokens.filter(function(x){return x.id===value})[0];if(token&&M.move(d,value,Number(node.getAttribute('data-destination'))))afterMove(token.product);return}if(cmd==='choice'){M.choose(d,value);afterMove();return}if(cmd==='undo'||cmd==='redo'){stopAudio();if(M.undo(d,cmd==='redo'))afterMove();return}if(cmd==='representation'){d.representation=d.representation==='frame'?'objects':'frame';save();render();return}if(cmd==='hint'){M.checkpoint(d,'before-hint');d.help_used++;d.state='needs_help';d.representation='frame';save();render();listen([d.task.audio.hint||'dynamic:prompt']);return}if(cmd==='count'){countZone(Number(value));return}if(cmd==='check'){M.checkpoint(d,'check');d.checked=true;d.state='review';save();render();if(S.voice)listen([guide(M.evaluate(d).matches?'match':'retry').path]);return}if(cmd==='review'){M.checkpoint(d,'review');d.stage='review';d.state='review';savedId='';go('review');return}if(cmd==='save-work'){if(saveWork(false)){go('review')}return}if(cmd==='pause'){M.checkpoint(d,'pause');d.state='paused';go('library');if(S.voice)listen([guide('pause').path]);return}}
function input(node){if(view==='builder'&&node.id&&node.id.indexOf('builder')===0)readBuilder();if(node.getAttribute&&node.getAttribute('data-field')&&S.draft){S.draft[node.getAttribute('data-field')]=node.value;save()}if(node.id==='coachNote'&&coachAllowed()){S.notes.observation=node.value;save()}}
function download(text,name,type){try{var blob=new Blob([text],{type:type}),url=URL.createObjectURL(blob),a=doc.createElement('a');a.href=url;a.download=name;doc.body.appendChild(a);a.click();doc.body.removeChild(a);setTimeout(function(){URL.revokeObjectURL(url)},1000)}catch(e){notify(t('تعذر التصدير في هذا المتصفح.','Export is unavailable in this browser.'))}}
function importFile(f){if(!f)return;if(f.size>3*1024*1024){notify(t('الملف أكبر من الحد المسموح.','The file is too large.'));return}var owner=profile,fr=new FileReader();fr.onload=function(){if(owner!==profile)return;try{var items=M.importData(String(fr.result));if(S.saved.length+items.length>50)throw Error('limit');S.saved=S.saved.concat(items);save();render();notify(t('استوردنا نسخًا مستقلة للطلبات.','Independent copies of the orders imported.'))}catch(e){notify(t('لم نغيّر طلباتك. ملف الاستيراد غير صالح أو المعرض ممتلئ.','Your orders are unchanged. The file is invalid or the gallery is full.'))}};fr.onerror=function(){notify(t('تعذر قراءة الملف.','The file could not be read.'))};fr.readAsText(f)}
function printWork(d){if(!d)return;save();stopAudio();var lang=S.language;S.language=d.task.language;$('printMarket').innerHTML='<article class="print-artifact" dir="'+(d.task.language==='ar'?'rtl':'ltr')+'"><h1>'+esc(d.task.title)+'</h1><p>'+esc(d.task.prompt)+'</p>'+request(d)+board(d,false)+'<p>'+esc(d.explanation)+'</p><p>'+esc(d.reflection)+'</p><div class="print-note"><h3>'+t('جرّب الطلب على الطاولة','Try the order on a table')+'</h3><p>'+esc(d.task.real)+'</p><p>'+esc(guide('safety').text)+'</p><p>'+t('المساعدة: ','Support: ')+supportName(d.support)+'</p></div><p class="muted">'+t('سوق العائلة · مدرسة العائلة 360','Family Market · Family School 360')+'</p></article>';S.language=lang;setTimeout(function(){w.print()},100)}
function offlineLabel(){$('offlineStatus').textContent=!navigator.serviceWorker?t('الحفظ متاح؛ التثبيت دون اتصال غير متاح هنا.','Local saves available; offline installation unavailable here.'):offlineReady?t('الصور والصوت والطلبات جاهزة دون اتصال.','Pictures, audio and orders ready offline.'):navigator.onLine===false?t('دون اتصال · تابع المحتوى المتاح.','Offline · use available content.'):t('تجهيز حزمة السوق…','Preparing the market pack…')}
function checkOffline(){if(offlineReady||!w.caches)return;try{caches.open('a4-family-market-preview-2').then(function(c){return c.match('./offline-ready.json')}).then(function(r){offlineReady=!!r;offlineLabel()}).catch(function(){})}catch(e){}}
w.APP360_PWA_BEFORE_RELOAD=function(done){save();stopAudio();done()};w.APP360_PWA_APPLY_PENDING=function(){return false};
load(identity());
doc.addEventListener('click',function(e){var node=e.target;while(node&&node!==doc){if(node.getAttribute&&node.getAttribute('data-do')){if(!node.disabled)action(node.getAttribute('data-do'),node.getAttribute('data-value'),node);return}node=node.parentNode}},false);
doc.addEventListener('keydown',function(e){if(!demo)return;if(e.key==='Escape'||e.keyCode===27){e.preventDefault();closeDemo();return}if(e.key==='Tab'||e.keyCode===9){var nodes=$('demoLayer').querySelectorAll('button:not([disabled])'),first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&doc.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&doc.activeElement===last){e.preventDefault();first.focus()}}},false);
doc.addEventListener('input',function(e){input(e.target)},false);
doc.addEventListener('change',function(e){var n=e.target;input(n);if(n.getAttribute&&n.getAttribute('data-focus-toggle')!==null){var a=api();if(!coachAllowed()||!a||!a.setReadingFocus||!a.setReadingFocus(!!n.checked))notify(t('يدير المرافق هذا الاختيار.','The coach manages this setting.'));syncFocus()}if(n.id&&n.id.indexOf('builder')===0)builderControls();if(n.id==='support'&&coachAllowed()){if(S.draft)M.checkpoint(S.draft,'support-change');S.support=n.value;if(S.draft)S.draft.support=n.value;save()}if(n.id==='importFile')importFile(n.files[0]);if(n.id==='importRecipes')importRecipes(n.files[0])},false);
doc.addEventListener('dragstart',function(e){var n=e.target;while(n&&n!==doc){if(n.getAttribute&&n.getAttribute('data-token')){save();e.dataTransfer.setData('text/plain',n.getAttribute('data-token'));return}n=n.parentNode}},false);
doc.addEventListener('dragover',function(e){var n=e.target;while(n&&n!==doc){if(n.getAttribute&&n.getAttribute('data-zone')!==null){e.preventDefault();return}n=n.parentNode}},false);
doc.addEventListener('drop',function(e){var n=e.target;if(!S.draft)return;while(n&&n!==doc){if(n.getAttribute&&n.getAttribute('data-zone')!==null){e.preventDefault();var id=e.dataTransfer.getData('text/plain'),token=S.draft.tokens.filter(function(x){return x.id===id})[0];if(token&&M.move(S.draft,id,Number(n.getAttribute('data-zone'))))afterMove(token.product);return}n=n.parentNode}},false);
w.addEventListener('beforeunload',function(){save();stopAudio()},false);w.addEventListener('pagehide',function(){save();stopAudio()},false);doc.addEventListener('visibilitychange',function(){if(doc.hidden){if(demo)closeDemo();save();stopAudio()}},false);w.addEventListener('resize',save,false);
w.addEventListener('popstate',function(){if(demo){closeDemo();return}save();stopAudio();if(view==='review'&&!savedId&&S.draft){S.draft.stage='play';go('play',false)}else{savedId='';go('library',false)}},false);
setInterval(function(){var p=identity();if(p!==profile){if(demo)closeDemo();save();stopAudio();load(p)}else if(view==='coach'&&!coachAllowed())render();syncFocus();checkOffline()},1300);
w.APP360_MARKET={version:'preview-2',open:open,openExperience:function(k,m){try{E.type(k);if(m)E.market(m)}catch(e){return false}if(m)S.market=m;return generated(k)},snapshot:function(){return M.copy(S)},profile:function(){return profile},reading:function(){return reader.debug()},evaluate:function(){return S.draft?M.evaluate(S.draft):null},audio:function(){return{path:audioPath,state:audioState}},debug:function(){return {storageOK:storageOK,corrupt:corrupt,view:view}},exportData:function(){return M.exportData(S.saved)},isOfflineReady:function(){return offlineReady},stop:stopAudio};
})(window,document);
