(function(w,d){'use strict';var KEY='app360:sensory:v1',STATE='app360:sensory:state:v1',current={place:'',materials:[],move:'',prop:'',mission:null,variant:'original',outcome:''},saved=[],deferred=null;
var places=[['floor','🧩','على الأرض'],['table','🪑','على طاولة منخفضة'],['yard','🌿','مساحة خارجية آمنة']];
var mats=[['ball','⚽','كرات كبيرة'],['cup','🥤','أكواب/أوعية كبيرة'],['block','🧱','مكعبات كبيرة'],['shoe','👟','أحذية'],['book','📘','كتب'],['cloth','🧣','قطع قماش كبيرة']];
var moves=[['transfer','↔️','نقل'],['sort','🧺','فرز'],['match','🖼️','مطابقة'],['stack','🏗️','تكديس'],['touch','✋','لمس'],['path','👣','مسار حركي']];
var props=[['color','🎨','اللون'],['shape','🔷','الشكل'],['size','↕️','الحجم'],['texture','🖐️','الملمس'],['place','📍','المكان']];
var templates={transfer:{title:'من هنا إلى هناك',inst:'انقل الأشياء الكبيرة واحدًا واحدًا إلى الوعاء الآخر.',easy:'قرّب الوعاءين وانقل غرضًا واحدًا فقط.',hard:'انقل الأشياء ثم أعدها إلى مكان البداية.'},sort:{title:'سلال الفرز',inst:'ضع الأشياء المتشابهة معًا في مكان واحد.',easy:'استخدم مجموعتين واضحتين وغرضين فقط.',hard:'استخدم مجموعتين أو ثلاثًا واطلب من الطفل اختيار المكان.'},match:{title:'ابحث عن الشبيه',inst:'ضع كل غرض كبير بجانب الغرض أو الصورة التي تشبهه.',easy:'اعرض خيارين فقط والنموذج أمام الطفل.',hard:'زد خيارًا ثالثًا واترك الطفل يبحث عن المطابقة.'},stack:{title:'نبني معًا',inst:'ضع القطع الكبيرة فوق بعضها لبناء برج منخفض.',easy:'ابنِ قطعتين فقط مع نموذج من المرافق.',hard:'ابنِ صفًا ثم برجًا منخفضًا.'},touch:{title:'المس واكتشف',inst:'المس الخامات الآمنة واحدة واحدة ولاحظ الفرق بينها.',easy:'استخدم خامتين واضحتين فقط.',hard:'طابق خامتين متشابهتين دون استعجال.'},path:{title:'اتبع الطريق',inst:'تحرك على العلامات الأرضية الكبيرة واحدة بعد الأخرى.',easy:'استخدم علامتين متقاربتين وخطوة واحدة.',hard:'اصنع مسارًا قصيرًا من ثلاث علامات واتبع الترتيب.'}};
function E(id){return d.getElementById(id)}function each(a,f){for(var i=0;i<a.length;i++)f(a[i],i)}function txt(s){return String(s==null?'':s)}function esc(s){return txt(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;')}
function store(){try{w.localStorage.setItem(KEY,JSON.stringify(saved));w.localStorage.setItem(STATE,JSON.stringify(current));return true}catch(e){notice('تعذر الحفظ المحلي؛ يمكنك متابعة النشاط والتصدير لاحقًا.');return false}}
function load(){try{saved=JSON.parse(w.localStorage.getItem(KEY)||'[]')||[];var s=JSON.parse(w.localStorage.getItem(STATE)||'null');if(s&&typeof s==='object')current=s}catch(e){saved=[]}}
function notice(s){var n=E('notice');n.innerHTML=esc(s);n.style.display='block';setTimeout(function(){n.style.display='none'},2600)}
function renderChoices(id,data,key,multi){var box=E(id),h='';each(data,function(x){var on=multi?current[key].indexOf(x[0])>=0:current[key]===x[0];h+='<button type="button" data-key="'+x[0]+'" class="'+(on?'on':'')+'"><span class="emoji">'+x[1]+'</span>'+x[2]+'</button>'});box.innerHTML=h;box.onclick=function(e){var t=e.target||e.srcElement;while(t&&t!==box&&!t.getAttribute('data-key'))t=t.parentNode;if(!t||t===box)return;var k=t.getAttribute('data-key');if(multi){var ix=current[key].indexOf(k);if(ix>=0)current[key].splice(ix,1);else current[key].push(k)}else current[key]=k;renderChoices(id,data,key,multi);store()}}
function go(id){each(d.querySelectorAll('.view'),function(v){v.hidden=v.id!==id});each(d.querySelectorAll('.steps button'),function(b){b.className=b.getAttribute('data-step')===id?'on':''});try{w.scrollTo(0,0)}catch(e){}store();if(id==='saved')renderSaved();if(id==='mission')renderMission();if(id==='run')renderRun()}
function label(data,id){for(var i=0;i<data.length;i++)if(data[i][0]===id)return data[i][2];return id}
function build(){if(!current.place||!current.materials.length||!current.move){notice('اختر المكان ومادة واحدة ونوع اللعب أولًا.');go('setup');return}var checks=d.querySelectorAll('[data-safe]'),ok=true;each(checks,function(c){if(!c.checked)ok=false});if(!ok){notice('أكمل فحص السلامة قبل بناء المهمة.');return}var t=templates[current.move]||templates.transfer;current.mission={id:'m'+new Date().getTime(),title:t.title,instruction:t.inst,easy:t.easy,hard:t.hard,safety:'مراقبة قريبة، مواد كبيرة آمنة، والتوقف عند التعب أو الرفض.',created:new Date().toISOString()};store();go('mission')}
function renderMission(){if(!current.mission)return;var m=current.mission,ms=[];each(current.materials,function(x){ms.push(label(mats,x))});E('missionTitle').innerHTML=esc(m.title);E('missionCard').innerHTML='<div class="instruction">👋 '+esc(m.instruction)+'</div><div class="mission-grid"><div><b>🧺 المواد</b><br>'+esc(ms.join('، '))+'</div><div><b>📍 المكان</b><br>'+esc(label(places,current.place))+'</div><div><b>🌱 أبسط</b><br>'+esc(m.easy)+'</div><div><b>⭐ تحدٍ إضافي</b><br>'+esc(m.hard)+'</div><div><b>🛡 السلامة</b><br>'+esc(m.safety)+'</div></div>';E('customTitle').value=m.title;E('customInstruction').value=m.instruction;E('customEasy').value=m.easy;E('customHard').value=m.hard;E('customSafety').value=m.safety}
function renderRun(){if(!current.mission)return;E('runInstruction').innerHTML=esc(current.mission.instruction);variant('original')}
function variant(v){if(!current.mission)return;current.variant=v;var text=v==='easy'?current.mission.easy:v==='hard'?current.mission.hard:current.mission.instruction;E('variantText').innerHTML=esc(text);each(d.querySelectorAll('.variant button'),function(b){b.className=b.id===(v==='easy'?'easyBtn':v==='hard'?'hardBtn':'originalBtn')?'on':''});store()}
function saveMission(){if(!current.mission||!current.materials.length||!current.mission.instruction||!current.mission.safety){notice('لا يمكن الحفظ دون مادة وتعليمة وسلامة.');return}var copy=JSON.parse(JSON.stringify(current));copy.saved_at=new Date().toISOString();saved.unshift(copy);store();notice('تم حفظ المهمة محليًا.')}
function finish(){current.outcome=current.outcome||'adapted';var r={what_worked:E('worked').value,what_changed:E('changed').value,next_adjustment:E('next').value};if(current.mission){current.reflection=r;saveMission()}notice('حُفظت الملاحظة.');setTimeout(function(){go('saved')},400)}
function renderSaved(){var box=E('savedList'),h='';if(!saved.length){box.innerHTML='<p>لا توجد مهمات محفوظة بعد.</p>';return}each(saved,function(s,i){var m=s.mission||{};h+='<article class="saved-card"><h3>'+esc(m.title||'مهمة')+'</h3><p>'+esc(m.instruction||'')+'</p><small>'+esc(s.outcome==='done'?'تم النشاط':s.outcome==='stopped'?'توقفنا':'تم التعديل')+'</small><div class="saved-actions"><button data-open="'+i+'">فتح</button><button data-del="'+i+'">حذف</button></div></article>'});box.innerHTML=h;box.onclick=function(e){var t=e.target||e.srcElement;if(t.getAttribute('data-open')!=null){current=JSON.parse(JSON.stringify(saved[+t.getAttribute('data-open')]));go('mission')}if(t.getAttribute('data-del')!=null){saved.splice(+t.getAttribute('data-del'),1);store();renderSaved()}}}
function exportData(){var data=JSON.stringify({schema:1,app:'a1-sensory',items:saved},null,2);try{var b=new Blob([data],{type:'application/json'}),u=URL.createObjectURL(b),a=d.createElement('a');a.href=u;a.download='sensory-missions.json';a.click();setTimeout(function(){URL.revokeObjectURL(u)},500)}catch(e){w.prompt('انسخ البيانات:',data)}}
function speak(){var m=current.mission;if(!m)return;if(w.speechSynthesis&&w.SpeechSynthesisUtterance){try{var u=new SpeechSynthesisUtterance(m.instruction);u.lang='ar';w.speechSynthesis.cancel();w.speechSynthesis.speak(u);return}catch(e){}}notice('الصوت غير متاح على هذا الجهاز؛ التعليمة مكتوبة أمامك.')}
function bind(){renderChoices('places',places,'place',false);renderChoices('materials',mats,'materials',true);renderChoices('moves',moves,'move',false);renderChoices('props',props,'prop',false);each(d.querySelectorAll('[data-go]'),function(b){b.onclick=function(){go(this.getAttribute('data-go'))}});E('toSafety').onclick=function(){if(!current.place||!current.materials.length||!current.move){notice('اختر المكان ومادة ونوع اللعب.');return}go('safe')};E('buildMission').onclick=build;E('saveBtn').onclick=saveMission;E('printBtn').onclick=function(){w.print()};E('speakBtn').onclick=speak;E('easyBtn').onclick=function(){variant('easy')};E('originalBtn').onclick=function(){variant('original')};E('hardBtn').onclick=function(){variant('hard')};E('outcomes').onclick=function(e){var t=e.target||e.srcElement;if(t.getAttribute('data-outcome')){current.outcome=t.getAttribute('data-outcome');each(E('outcomes').getElementsByTagName('button'),function(b){b.className=b===t?'on':''});store()}};E('finishBtn').onclick=finish;E('newBtn').onclick=function(){current={place:'',materials:[],move:'',prop:'',mission:null,variant:'original',outcome:''};store();go('setup');renderChoices('places',places,'place',false);renderChoices('materials',mats,'materials',true);renderChoices('moves',moves,'move',false);renderChoices('props',props,'prop',false)};E('applyCustom').onclick=function(){if(!current.mission)return;var vals=[E('customTitle').value,E('customInstruction').value,E('customEasy').value,E('customHard').value,E('customSafety').value];if(!vals[1]||!vals[4]){notice('التعليمة وملاحظة السلامة مطلوبتان.');return}current.mission.title=vals[0]||current.mission.title;current.mission.instruction=vals[1];current.mission.easy=vals[2]||current.mission.easy;current.mission.hard=vals[3]||current.mission.hard;current.mission.safety=vals[4];store();renderMission();notice('تم تحديث البطاقة')};E('exportBtn').onclick=exportData;each(d.querySelectorAll('.steps button'),function(b){b.onclick=function(){var s=this.getAttribute('data-step');if((s==='mission'||s==='run'||s==='reflect')&&!current.mission){notice('ابنِ مهمة أولًا.');return}go(s)}});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(function(){});w.addEventListener('beforeinstallprompt',function(e){e.preventDefault();deferred=e});E('installBtn').onclick=function(){if(deferred){deferred.prompt();deferred=null}else notice('استخدم خيار إضافة إلى الشاشة الرئيسية من المتصفح إذا لم يظهر التثبيت.')}}load();bind();go(current.mission?'mission':'setup')})(window,document);