(function(w,d){'use strict';var MAP=w.APP360_WORD_IMAGE_MAP||{},BASE='../say-and-name/assets/word-images/',cats=[['الألعاب',['كرة','دمية','سيارة','بالون','أحجية','طبلة','مكعب','طائرة ورقية']],['الفواكه',['تفاح','موز','برتقال','عنب','فراولة','بطيخ','مانجو','تمر']],['الحيوانات',['قطة','كلب','طائر','سمكة','أرنب','حصان','أسد','فيل']],['المنزل',['كوب','كتاب','كرسي','ملعقة','حذاء','فرشاة','منشفة','مفتاح']],['النقل',['سيارة','حافلة','شاحنة','دراجة','قطار','طائرة','سفينة','قارب']],['الطبيعة',['شمس','قمر','شجرة','زهرة','حجر','بحر','سحابة','مطر']]],ci=0,mode='basket',stars=0,selected=null,sound=true,touch=null,basketItems=[],takeTimer=null;
function E(x){return d.getElementById(x)}function img(n){return BASE+(MAP[n]||'w0037.jpg')}function toast(s){var x=E('toast');x.innerHTML=s;x.style.display='block';setTimeout(function(){x.style.display='none'},1300)}
function say(s){if(!sound)return;try{if(w.speechSynthesis&&w.SpeechSynthesisUtterance){var u=new SpeechSynthesisUtterance(s);u.lang='ar';u.rate=.82;u.pitch=1.08;w.speechSynthesis.cancel();w.speechSynthesis.speak(u)}}catch(e){}}
function phrase(action,word){if(action==='in')return 'دخلت '+word+' إلى السلة';if(action==='out')return 'خرجت '+word+' من السلة';return word}
function tray(){E('catName').innerHTML=cats[ci][0];var h='',a=cats[ci][1];for(var i=0;i<a.length;i++)h+='<button class="trayItem" data-word="'+a[i]+'"><img src="'+img(a[i])+'" alt=""><span>'+a[i]+'</span></button>';E('tray').innerHTML=h;E('tray').onclick=function(e){var t=e.target||e.srcElement;while(t&&t!==this&&!t.getAttribute('data-word'))t=t.parentNode;if(t&&t!==this)add(t.getAttribute('data-word'))}}
function add(word,x,y){var box=E('playground'),p=d.createElement('div'),n=E('pieces').children.length;p.className='piece';p.setAttribute('data-word',word);p.style.left=(typeof x==='number'?x:15+(n*100)%Math.max(190,box.clientWidth-110))+'px';p.style.top=(typeof y==='number'?y:75+(n%2)*90)+'px';p.innerHTML='<img src="'+img(word)+'" alt="'+word+'">';E('pieces').appendChild(p);bindPiece(p);say(word)}
function bindPiece(p){p.onclick=function(){if(touch&&new Date().getTime()-touch.time<450)return;selectPiece(this)};p.ontouchstart=function(e){var q=e.touches[0],r=this.getBoundingClientRect();touch={el:this,sx:q.clientX,sy:q.clientY,ox:q.clientX-r.left,oy:q.clientY-r.top,moved:false,time:new Date().getTime()};this.className='piece selected';E('basketZone').className='basketZone ready'};p.ontouchmove=function(e){if(!touch||touch.el!==this)return;var q=e.touches[0],pg=E('playground').getBoundingClientRect();if(Math.abs(q.clientX-touch.sx)>6||Math.abs(q.clientY-touch.sy)>6)touch.moved=true;e.preventDefault();this.style.left=Math.max(0,Math.min(pg.width-this.offsetWidth,q.clientX-pg.left-touch.ox))+'px';this.style.top=Math.max(0,Math.min(pg.height-this.offsetHeight,q.clientY-pg.top-touch.oy))+'px'};p.ontouchend=function(){if(!touch||touch.el!==this)return;var moved=touch.moved;touch.time=new Date().getTime();E('basketZone').className='basketZone';if(moved)drop(this);else selectPiece(this);setTimeout(function(){touch=null},500)};p.onmousedown=function(e){var el=this,pg=E('playground').getBoundingClientRect(),r=el.getBoundingClientRect(),ox=e.clientX-r.left,oy=e.clientY-r.top,m=false;E('basketZone').className='basketZone ready';function mv(q){m=true;el.style.left=Math.max(0,Math.min(pg.width-el.offsetWidth,q.clientX-pg.left-ox))+'px';el.style.top=Math.max(0,Math.min(pg.height-el.offsetHeight,q.clientY-pg.top-oy))+'px'}function up(){d.removeEventListener('mousemove',mv);d.removeEventListener('mouseup',up);E('basketZone').className='basketZone';if(m)drop(el)}d.addEventListener('mousemove',mv);d.addEventListener('mouseup',up)}}
function selectPiece(p){if(selected===p){p.className='piece';selected=null;return}if(selected)selected.className='piece';selected=p;p.className='piece selected';say(p.getAttribute('data-word'));toast('الآن المس السلة لإدخال '+p.getAttribute('data-word'))}
function drop(p){p.className='piece';selected=null;if(mode==='basket'&&hitBasket(p)){putInBasket(p);return}if(mode==='free')return;var ts=E('targets').children,pr=p.getBoundingClientRect();for(var i=0;i<ts.length;i++){var r=ts[i].getBoundingClientRect(),cx=pr.left+pr.width/2,cy=pr.top+pr.height/2;if(cx>=r.left&&cx<=r.right&&cy>=r.top&&cy<=r.bottom){judge(p,ts[i]);return}}}
function hitBasket(p){var r=E('basket').getBoundingClientRect(),q=p.getBoundingClientRect(),cx=q.left+q.width/2,cy=q.top+q.height/2;return cx>r.left-20&&cx<r.right+20&&cy>r.top-20&&cy<r.bottom+25}
function putInBasket(p){var word=p.getAttribute('data-word');basketItems.push(word);updateBasket();E('basketZone').className='basketZone bump';p.className='piece enter';say(phrase('in',word));toast('🧺 '+word+' داخل السلة');setTimeout(function(){if(p.parentNode)p.parentNode.removeChild(p);E('basketZone').className='basketZone'},390);stars++;E('starCount').innerHTML='⭐ '+stars;celebrate()}
function updateBasket(){E('basketCount').innerHTML=basketItems.length;E('insideCount').innerHTML='('+basketItems.length+')';try{w.localStorage.setItem('a1-sensory-basket',JSON.stringify(basketItems))}catch(e){}}
function openBasket(){renderInside();E('basketModal').className='modal open';E('basketModal').setAttribute('aria-hidden','false');say(basketItems.length?'لنر ما في السلة':'السلة فارغة')}
function closeBasket(){E('basketModal').className='modal';E('basketModal').setAttribute('aria-hidden','true');if(takeTimer){clearTimeout(takeTimer);takeTimer=null}}
function renderInside(){var h='';for(var i=0;i<basketItems.length;i++)h+='<button class="insideItem" data-index="'+i+'" data-word="'+basketItems[i]+'"><img src="'+img(basketItems[i])+'" alt=""><span>'+basketItems[i]+'</span></button>';E('insideBasket').innerHTML=h;E('insideBasket').style.display=basketItems.length?'flex':'none';E('emptyBasket').style.display=basketItems.length?'none':'block';E('takeAll').style.display=basketItems.length?'block':'none';E('insideCount').innerHTML='('+basketItems.length+')';E('insideBasket').onclick=function(e){var t=e.target||e.srcElement;while(t&&t!==this&&!t.getAttribute('data-index'))t=t.parentNode;if(t&&t!==this)takeOut(parseInt(t.getAttribute('data-index'),10),t)}}
function takeOut(i,el){if(i<0||i>=basketItems.length)return;var word=basketItems[i];if(el)el.className='insideItem lift';basketItems.splice(i,1);updateBasket();say(phrase('out',word));toast('👋 خرجت '+word+' من السلة');setTimeout(function(){renderInside();closeBasket();var pg=E('playground'),x=Math.max(8,Math.min(pg.clientWidth-105,pg.clientWidth/2-48)),y=70+Math.floor(Math.random()*80);add(word,x,y);celebrate()},360)}
function takeAll(){if(!basketItems.length)return;var word=basketItems[0];say(phrase('out',word));toast('👋 خرجت '+word);basketItems.splice(0,1);updateBasket();renderInside();closeBasket();add(word,20+Math.floor(Math.random()*Math.max(30,E('playground').clientWidth-140)),80);celebrate();if(basketItems.length)takeTimer=setTimeout(function(){openBasket()},800)}
function judge(p,t){var word=p.getAttribute('data-word'),ok=false;if(mode==='match')ok=t.getAttribute('data-word')===word;else if(mode==='sort')ok=t.getAttribute('data-group')===group(word);if(ok){stars++;E('starCount').innerHTML='⭐ '+stars;p.className='piece good';say('أحسنت، '+word);setTimeout(function(){if(p.parentNode)p.parentNode.removeChild(p)},300);celebrate()}else{toast('جرّب مكانًا آخر 🌱');say('جرّب مرة أخرى')}}
function group(wd){if(cats[1][1].indexOf(wd)>=0)return'fruit';if(cats[2][1].indexOf(wd)>=0)return'animal';return'thing'}
function celebrate(){var c=E('celebrate');c.innerHTML=['✨','⭐','🎉','🌟'][stars%4];c.className='celebrate show';setTimeout(function(){c.className='celebrate'},480)}
function clearPieces(){E('pieces').innerHTML='';E('targets').innerHTML='';selected=null}
function newRound(){clearPieces();E('basketZone').style.display=mode==='basket'?'block':'none';var h='',a=cats[ci][1];if(mode==='basket'){E('missionText').innerHTML='ضع الأشياء في السلة ثم افتحها وأخرجها';E('hint').innerHTML=basketItems.length?'في السلة '+basketItems.length+' — يمكنك فتحها':'اسحب شيئًا إلى السلة 👇'}else if(mode==='free'){E('missionText').innerHTML='حرّك الصور والعب بها بحرية';E('hint').innerHTML='اختر صورة من الأسفل';}else if(mode==='match'){var x=a[Math.floor(Math.random()*a.length)],y=a[(a.indexOf(x)+1)%a.length];h='<div class="target" data-word="'+x+'"><img src="'+img(x)+'"><br>'+x+'</div><div class="target" data-word="'+y+'"><img src="'+img(y)+'"><br>'+y+'</div>';E('missionText').innerHTML='ضع كل صورة فوق شبيهها';E('hint').innerHTML='طابق الصورة';E('targets').innerHTML=h;add(x);add(y)}else if(mode==='sort'){h='<div class="target" data-group="fruit">🍎<br>فواكه</div><div class="target" data-group="animal">🐾<br>حيوانات</div><div class="target" data-group="thing">🧸<br>أشياء</div>';E('missionText').innerHTML='ضع كل شيء مع مجموعته';E('hint').innerHTML='فرز بسيط';E('targets').innerHTML=h}}
function setMode(m,b){mode=m;var bs=d.querySelectorAll('.modes button');for(var i=0;i<bs.length;i++)bs[i].className=bs[i]===b?'on':'';closeBasket();if(m==='real'){E('gameView').hidden=true;E('realView').hidden=false}else{E('gameView').hidden=false;E('realView').hidden=true;newRound()}}
function reset(){clearPieces();basketItems=[];stars=0;updateBasket();E('starCount').innerHTML='⭐ 0';try{w.localStorage.removeItem('a1-sensory-basket')}catch(e){}newRound();say('السلة فارغة')}
E('basket').onclick=function(){if(selected&&mode==='basket'){var p=selected;selected=null;putInBasket(p)}else openBasket()};E('openBasket').onclick=openBasket;E('closeBasket').onclick=closeBasket;E('modalShade').onclick=closeBasket;E('takeAll').onclick=takeAll;E('prevCat').onclick=function(){ci=(ci+cats.length-1)%cats.length;tray();newRound()};E('nextCat').onclick=function(){ci=(ci+1)%cats.length;tray();newRound()};E('resetBtn').onclick=reset;E('soundBtn').onclick=function(){sound=!sound;this.innerHTML=sound?'🔊':'🔇';if(sound)say('الصوت يعمل')};var mb=d.querySelectorAll('.modes button');for(var i=0;i<mb.length;i++)mb[i].onclick=function(){setMode(this.getAttribute('data-mode'),this)};try{var saved=JSON.parse(w.localStorage.getItem('a1-sensory-basket')||'[]');if(saved&&saved.length)basketItems=saved}catch(e){}updateBasket();tray();newRound();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(function(){})})(window,document);