(function(w,d){'use strict';var MAP=w.APP360_WORD_IMAGE_MAP||{},BASE='../say-and-name/assets/word-images/',cats=[['الألعاب',['كرة','دمية','سيارة','بالون','أحجية','طبلة','مكعب']],['الفواكه',['تفاح','موز','برتقال','عنب','فراولة','بطيخ','مانجو','تمر']],['الحيوانات',['قطة','كلب','طائر','سمكة','أرنب','حصان','أسد','فيل']],['المنزل',['كوب','كتاب','كرسي','ملعقة','حذاء','فرشاة','منشفة','مفتاح']],['النقل',['سيارة','حافلة','شاحنة','دراجة','قطار','طائرة','سفينة','قارب']],['الطبيعة',['شمس','قمر','شجرة','زهرة','حجر','بحر','سحابة','مطر']]],ci=0,mode='free',stars=0,round=[],selected=null,sound=true,touch=null;
function E(x){return d.getElementById(x)}function img(n){return BASE+(MAP[n]||'w0037.jpg')}function toast(s){var x=E('toast');x.innerHTML=s;x.style.display='block';setTimeout(function(){x.style.display='none'},1200)}function say(s){if(!sound)return;try{if(w.speechSynthesis&&w.SpeechSynthesisUtterance){var u=new SpeechSynthesisUtterance(s);u.lang='ar';w.speechSynthesis.cancel();w.speechSynthesis.speak(u)}}catch(e){}}
function tray(){E('catName').innerHTML=cats[ci][0];var h='',a=cats[ci][1];for(var i=0;i<a.length;i++)h+='<button class="trayItem" data-word="'+a[i]+'"><img src="'+img(a[i])+'" alt=""><span>'+a[i]+'</span></button>';E('tray').innerHTML=h;E('tray').onclick=function(e){var t=e.target||e.srcElement;while(t&&t!==this&&!t.getAttribute('data-word'))t=t.parentNode;if(t&&t!==this)add(t.getAttribute('data-word'))}}
function add(word){var box=E('playground'),p=d.createElement('div'),n=E('pieces').children.length;p.className='piece';p.setAttribute('data-word',word);p.style.left=(20+(n*105)%(Math.max(220,box.clientWidth-120)))+'px';p.style.top=(80+(n%2)*105)+'px';p.innerHTML='<img src="'+img(word)+'" alt="'+word+'">';E('pieces').appendChild(p);bindPiece(p);say(word);if(mode==='basket'||mode==='match'||mode==='sort')checkRoundAdd(word)}
function bindPiece(p){p.onclick=function(e){if(touch&&new Date().getTime()-touch.time<450)return;selectOrPlace(this)};p.ontouchstart=function(e){var q=e.touches[0],r=this.getBoundingClientRect();touch={el:this,sx:q.clientX,sy:q.clientY,ox:q.clientX-r.left,oy:q.clientY-r.top,moved:false,time:new Date().getTime()};this.className='piece selected'};p.ontouchmove=function(e){if(!touch||touch.el!==this)return;var q=e.touches[0],pg=E('playground').getBoundingClientRect();if(Math.abs(q.clientX-touch.sx)>6||Math.abs(q.clientY-touch.sy)>6)touch.moved=true;e.preventDefault();this.style.left=Math.max(0,Math.min(pg.width-this.offsetWidth,q.clientX-pg.left-touch.ox))+'px';this.style.top=Math.max(0,Math.min(pg.height-this.offsetHeight,q.clientY-pg.top-touch.oy))+'px'};p.ontouchend=function(e){if(!touch||touch.el!==this)return;var moved=touch.moved;touch.time=new Date().getTime();if(moved)drop(this);else selectOrPlace(this);setTimeout(function(){touch=null},500)};p.onmousedown=function(e){var el=this,pg=E('playground').getBoundingClientRect(),r=el.getBoundingClientRect(),ox=e.clientX-r.left,oy=e.clientY-r.top,m=false;function mv(q){m=true;el.style.left=Math.max(0,Math.min(pg.width-el.offsetWidth,q.clientX-pg.left-ox))+'px';el.style.top=Math.max(0,Math.min(pg.height-el.offsetHeight,q.clientY-pg.top-oy))+'px'}function up(){d.removeEventListener('mousemove',mv);d.removeEventListener('mouseup',up);if(m)drop(el)}d.addEventListener('mousemove',mv);d.addEventListener('mouseup',up)}}
function selectOrPlace(p){if(selected===p){p.className='piece';selected=null;return}if(selected)selected.className='piece';selected=p;p.className='piece selected';say(p.getAttribute('data-word'));if(mode==='free')toast('حرّك '+p.getAttribute('data-word')+' أينما تريد')}
function drop(p){p.className='piece';selected=null;if(mode==='free')return;var ts=E('targets').children,pr=p.getBoundingClientRect();for(var i=0;i<ts.length;i++){var r=ts[i].getBoundingClientRect(),cx=pr.left+pr.width/2,cy=pr.top+pr.height/2;if(cx>=r.left&&cx<=r.right&&cy>=r.top&&cy<=r.bottom){judge(p,ts[i]);return}}}
function judge(p,t){var word=p.getAttribute('data-word'),ok=false;if(mode==='basket')ok=true;else if(mode==='match')ok=t.getAttribute('data-word')===word;else if(mode==='sort')ok=t.getAttribute('data-group')===group(word);if(ok){stars++;E('starCount').innerHTML='⭐ '+stars;p.className='piece good';say('أحسنت');setTimeout(function(){if(p.parentNode)p.parentNode.removeChild(p)},300);celebrate();}else{toast('جرّب مكانًا آخر 🌱');say('جرّب مرة أخرى')}}
function group(wd){var fruit=cats[1][1],animal=cats[2][1];if(fruit.indexOf(wd)>=0)return'fruit';if(animal.indexOf(wd)>=0)return'animal';return'thing'}
function celebrate(){var c=E('celebrate');c.innerHTML=['✨','⭐','🎉','🌟'][stars%4];c.className='celebrate show';setTimeout(function(){c.className='celebrate'},550)}
function clear(){E('pieces').innerHTML='';E('targets').innerHTML='';selected=null}
function newRound(){clear();var h='',a=cats[ci][1];if(mode==='free'){E('missionText').innerHTML='اختر أي صورة واسحبها والعب بها';E('hint').innerHTML='اختر من صور أشيائي 👇';return}if(mode==='basket'){h='<div class="target basket">🧺<br>السلة</div>';E('missionText').innerHTML='ضع الصور داخل السلة';E('hint').innerHTML='اسحب إلى السلة';}else if(mode==='match'){var x=a[Math.floor(Math.random()*a.length)],y=a[(a.indexOf(x)+1)%a.length];h='<div class="target" data-word="'+x+'"><img src="'+img(x)+'"><br>'+x+'</div><div class="target" data-word="'+y+'"><img src="'+img(y)+'"><br>'+y+'</div>';E('missionText').innerHTML='ضع كل صورة فوق شبيهها';add(x);add(y)}else if(mode==='sort'){h='<div class="target" data-group="fruit">🍎<br>فواكه</div><div class="target" data-group="animal">🐾<br>حيوانات</div><div class="target" data-group="thing">🧸<br>أشياء</div>';E('missionText').innerHTML='فرز الصور في المكان المناسب'}E('targets').innerHTML=h}
function checkRoundAdd(){}
function setMode(m,b){mode=m;var bs=d.querySelectorAll('.modes button');for(var i=0;i<bs.length;i++)bs[i].className=bs[i]===b?'on':'';if(m==='real'){E('gameView').hidden=true;E('realView').hidden=false}else{E('gameView').hidden=false;E('realView').hidden=true;newRound()}}
E('prevCat').onclick=function(){ci=(ci+cats.length-1)%cats.length;tray();newRound()};E('nextCat').onclick=function(){ci=(ci+1)%cats.length;tray();newRound()};E('newRound').onclick=newRound;E('soundBtn').onclick=function(){sound=!sound;this.innerHTML=sound?'🔊':'🔇'};var mb=d.querySelectorAll('.modes button');for(var i=0;i<mb.length;i++)mb[i].onclick=function(){setMode(this.getAttribute('data-mode'),this)};tray();newRound();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(function(){})})(window,document);