(function(w,d){
'use strict';
var C=w.APP360_CALM_CONTENT||{};
var APP_ID='a1-calm';
var SCHEMA='1.0';
var STORAGE_KEY='app360:'+APP_ID+':schema-'+SCHEMA+':state';
var MAX_IMAGE_BYTES=650000;
var MAX_AUDIO_BYTES=750000;
var storageOk=true;
var state=null;
var pendingHelpImage='';
var pendingHelpAudio='';
var pendingTransitionImage='';
var lastTouchAt=0;
var deferredInstall=null;
var $=function(id){return d.getElementById(id)};
function text(v){return String(v==null?'':v)}
function trim(v){return text(v).replace(/^\s+|\s+$/g,'')}
function nowIso(){return new Date().toISOString()}
function uid(prefix){return (prefix||'id')+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8)}
function clone(obj){try{return JSON.parse(JSON.stringify(obj))}catch(e){return obj}}
function hasClass(el,name){return (' '+(el.className||'')+' ').indexOf(' '+name+' ')>=0}
function addClass(el,name){if(el&&!hasClass(el,name))el.className=(el.className?el.className+' ':'')+name}
function removeClass(el,name){if(el)el.className=(' '+(el.className||'')+' ').replace(' '+name+' ',' ').replace(/^\s+|\s+$/g,'')}
function setHidden(el,hidden){if(!el)return;el.hidden=!!hidden;el.style.display=hidden?'none':''}
function esc(s){return text(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function testStorage(){try{var k='__app360_calm_test__';w.localStorage.setItem(k,'1');w.localStorage.removeItem(k);return true}catch(e){return false}}
function defaultState(){return {schema_version:SCHEMA,app_id:APP_ID,library:clone(C.helps||[]),custom_transitions:[],plans:[],reviews:[],settings:{speech:true},current:{session_id:uid('session'),signal_or_feeling:null,selected_help:null,now:null,then:null,assistance_level:'adult-offered-two'}}}
function normalize(raw){var s=raw&&typeof raw==='object'?raw:defaultState();if(!s.library||!s.library.length)s.library=clone(C.helps||[]);if(!s.custom_transitions)s.custom_transitions=[];if(!s.plans)s.plans=[];if(!s.reviews)s.reviews=[];if(!s.settings)s.settings={speech:true};if(!s.current)s.current=defaultState().current;return s}
function load(){storageOk=testStorage();var parsed=null;if(storageOk){try{parsed=JSON.parse(w.localStorage.getItem(STORAGE_KEY)||'null')}catch(e){parsed=null}}state=normalize(parsed);updateStorageBanner()}
function persist(){if(!storageOk){updateStorageBanner();return false}try{w.localStorage.setItem(STORAGE_KEY,JSON.stringify(state));updateStorageBanner();return true}catch(e){storageOk=false;updateStorageBanner();return false}}
function updateStorageBanner(){var b=$('storageBanner');if(!b)return;setHidden(b,storageOk);if(!storageOk)b.innerHTML='<b>الحفظ المحلي غير متاح.</b> يمكنك متابعة النشاط، لكن لن نعدك بحفظه بعد إغلاق الصفحة. استخدم التصدير لحفظ نسخة بيانات.'}
function toast(msg){var n=$('toast');if(!n)return;n.textContent=msg;n.className='toast show';clearTimeout(toast.t);toast.t=setTimeout(function(){n.className='toast'},2600)}
function status(msg){var n=$('audioStatus');if(n)n.textContent=msg}
function contentValid(){var groups=['signals','feelings','helps','transitions'],i,j,seen={},a,x;for(i=0;i<groups.length;i++){a=C[groups[i]];if(!a||!a.length)return false;for(j=0;j<a.length;j++){x=a[j];if(!x.id||!x.label_ar||seen[groups[i]+'|'+x.id])return false;seen[groups[i]+'|'+x.id]=1}}return true}
function itemById(list,id){var i;for(i=0;i<(list||[]).length;i++)if(list[i].id===id)return list[i];return null}
function imageHtml(item,extra){var label=esc(item&&item.label_ar||'');if(item&&item.image)return '<img '+(extra||'')+' src="'+esc(item.image)+'" alt="'+label+'" onerror="this.style.display=\'none\';this.nextSibling.style.display=\'inline-block\'"><span class="symbol image-fallback" style="display:none">'+esc(item.symbol||'◯')+'</span>';return '<span class="symbol" '+(extra||'')+'>'+esc(item&&item.symbol||'◯')+'</span>'}
function closestButton(node,root){while(node&&node!==root&&node!==d){if(node.tagName&&node.tagName.toLowerCase()==='button')return node;node=node.parentNode}if(node&&node.tagName&&node.tagName.toLowerCase()==='button')return node;return null}
function bindActivation(root,fn){if(!root)return;function run(e){e=e||w.event;var b=closestButton(e.target||e.srcElement,root);if(!b||b.disabled)return;var t=Date.now();if(e.type==='touchend'){lastTouchAt=t;if(e.preventDefault)e.preventDefault()}else if(t-lastTouchAt<650)return;fn(b,e)}if(root.addEventListener){root.addEventListener('touchend',run,false);root.addEventListener('click',run,false)}else root.onclick=run}
function speakItem(item){if(!item)return;var phrase=item.speech_ar||item.label_ar||'';if(item.audio){try{var a=new Audio(item.audio);a.play();status('تشغيل الصوت المسجل المحلي.');return}catch(e){}}
  if(state.settings.speech===false){status('الصوت متوقف. كل الخطوات ما زالت متاحة بصريًا.');return}
  try{if('speechSynthesis'in w&&w.SpeechSynthesisUtterance){w.speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(phrase);u.lang='ar';u.rate=.86;w.speechSynthesis.speak(u);status('الصوت اختياري؛ يمكنك متابعة التطبيق بصريًا بالكامل.');return}}catch(e){}
  status('الصوت غير متاح على هذا الجهاز. استخدم النص والصورة أو اقرأ العبارة بصوتك.')
}
function switchView(name){var names=['child','transition','plans','caregiver'],i,p,b;for(i=0;i<names.length;i++){p=$(names[i]+'View');setHidden(p,names[i]!==name);b=$('nav-'+names[i]);if(b)b.className=names[i]===name?'nav-btn active':'nav-btn'}w.scrollTo(0,0);if(name==='plans')renderPlans();if(name==='caregiver'){renderLibrary();renderReviewForm()}if(name==='transition')renderTransition()}
function selectionKey(kind,id){return kind+':'+id}
function renderChoiceCards(rootId,items,kind,selected){var root=$(rootId),h='',i,it,key;if(!root)return;for(i=0;i<items.length;i++){it=items[i];key=selectionKey(kind,it.id);h+='<button type="button" class="choice-card'+(selected===key?' selected':'')+'" data-kind="'+kind+'" data-id="'+esc(it.id)+'" aria-pressed="'+(selected===key?'true':'false')+'">'+imageHtml(it)+'<strong>'+esc(it.label_ar)+'</strong><span class="listen-mark" aria-hidden="true">🔊</span></button>'}root.innerHTML=h}
function activeHelps(){var out=[],i;for(i=0;i<state.library.length;i++)if(state.library[i].enabled!==false)out.push(state.library[i]);return out}
function renderHelps(){var root=$('helpCards'),h='',list=activeHelps(),i,it,selected=state.current.selected_help&&state.current.selected_help.id;if(!root)return;for(i=0;i<list.length;i++){it=list[i];h+='<button type="button" class="choice-card help-card'+(selected===it.id?' selected':'')+'" data-help="'+esc(it.id)+'" aria-pressed="'+(selected===it.id?'true':'false')+'">'+imageHtml(it)+'<strong>'+esc(it.label_ar)+'</strong><span class="listen-mark">🔊</span></button>'}root.innerHTML=h||'<p class="empty">لا توجد مساعدات مفعلة. يمكن للمرافق تفعيلها من الإعدادات.</p>'}
function describeCurrent(){var s=state.current.signal_or_feeling,h=state.current.selected_help;var a=$('currentSignalText'),b=$('currentHelpText');if(a)a.textContent=s?s.label_ar:'لم نشترط تسمية';if(b)b.textContent=h?h.label_ar:'لا توجد مساعدة مختارة بعد'}
function renderChild(){var selected=state.current.signal_or_feeling?selectionKey(state.current.signal_or_feeling.type,state.current.signal_or_feeling.id):'';renderChoiceCards('signalCards',C.signals||[],'signal',selected);renderChoiceCards('feelingCards',C.feelings||[],'feeling',selected);renderHelps();describeCurrent()}
function chooseSignal(kind,id){var list=kind==='feeling'?C.feelings:C.signals,it=itemById(list,id);if(!it)return;state.current.signal_or_feeling={type:kind,id:it.id,label_ar:it.label_ar};persist();renderChild();speakItem(it);toast('تم تسجيل الإشارة كخيار وصفي فقط.');scrollToEl('helpSection')}
function skipSignal(){state.current.signal_or_feeling={type:'skipped',id:'skipped',label_ar:'تم تجاوز التسمية'};persist();renderChild();toast('يمكن المتابعة دون تسمية الشعور.');scrollToEl('helpSection')}
function chooseHelp(id){var it=itemById(state.library,id);if(!it)return;state.current.selected_help={id:it.id,label_ar:it.label_ar,image:it.image||'',symbol:it.symbol||'',audio:it.audio||'',category:it.category||'custom'};persist();renderHelps();describeCurrent();speakItem(it);toast('هذه مساعدة معروضة ويمكن رفضها أو تغييرها.')}
function rejectHelp(){state.current.selected_help={id:'declined',label_ar:'لم نختَر مساعدة الآن',symbol:'○',category:'declined'};persist();renderHelps();describeCurrent();toast('لا عقوبة على رفض المساعدة. يمكنك الانتقال للخطوة التالية.')}
function scrollToEl(id){var el=$(id);if(!el)return;setTimeout(function(){try{el.scrollIntoView({behavior:'smooth',block:'start'})}catch(e){try{el.scrollIntoView(true)}catch(x){}}},50)}
function allTransitions(){var a=clone(C.transitions||[]),i;for(i=0;i<state.custom_transitions.length;i++)a.push(state.custom_transitions[i]);return a}
function renderTransitionPicker(rootId,slot){var root=$(rootId),items=allTransitions(),selected=state.current[slot]&&state.current[slot].id,h='',i,it;if(!root)return;for(i=0;i<items.length;i++){it=items[i];h+='<button type="button" class="transition-option'+(selected===it.id?' selected':'')+'" data-slot="'+slot+'" data-step="'+esc(it.id)+'">'+imageHtml(it)+'<span>'+esc(it.label_ar)+'</span></button>'}root.innerHTML=h}
function renderTransition(){renderTransitionPicker('nowPicker','now');renderTransitionPicker('thenPicker','then');renderPlanPreview()}
function chooseTransition(slot,id){var it=itemById(allTransitions(),id);if(!it)return;state.current[slot]=clone(it);persist();renderTransition();speakItem(it)}
function renderPlanPreview(){var now=state.current.now,then=state.current.then,box=$('planPreview');if(!box)return;var h='<div class="plan-step"><b>الآن</b>'+(now?imageHtml(now)+'<strong>'+esc(now.label_ar)+'</strong>':'<span class="placeholder">اختر خطوة الآن</span>')+'</div><div class="plan-arrow">←</div><div class="plan-step"><b>بعد ذلك</b>'+(then?imageHtml(then)+'<strong>'+esc(then.label_ar)+'</strong>':'<span class="placeholder">اختر الخطوة التالية</span>')+'</div>';box.innerHTML=h;var save=$('savePlanBtn');if(save)save.disabled=!(now&&then);var print=$('printCurrentBtn');if(print)print.disabled=!(now&&then)}
function makePlan(){if(!state.current.now||!state.current.then)return null;var title=trim($('planTitle').value)||'خطة الآن وبعد ذلك';return {schema_version:SCHEMA,app_id:APP_ID,support_plan_id:uid('plan'),created_at:nowIso(),title:title,signal_or_feeling:clone(state.current.signal_or_feeling),help_options:activeHelps().map(function(x){return {id:x.id,label_ar:x.label_ar}}),selected_help:clone(state.current.selected_help),transition_plan:{now:clone(state.current.now),then:clone(state.current.then)},reflection:null,assistance_level:state.current.assistance_level||'adult-offered-two'}}
function savePlan(){var p=makePlan();if(!p){toast('اختر «الآن» و«بعد ذلك» أولًا.');return}state.plans.unshift(p);persist();toast(storageOk?'تم حفظ الخطة محليًا.':'الخطة موجودة في هذه الجلسة فقط؛ صدّرها لحفظ نسخة.');renderPlans();preparePrint(p)}
function planById(id){return itemById(state.plans,id)}
function stepHtml(step){if(!step)return '<span class="placeholder">—</span>';return imageHtml(step)+'<strong>'+esc(step.label_ar)+'</strong>'}
function planCardHtml(p){var sig=p.signal_or_feeling&&p.signal_or_feeling.label_ar||'دون تسمية',help=p.selected_help&&p.selected_help.label_ar||'دون مساعدة محددة';return '<article class="saved-plan" data-plan="'+esc(p.support_plan_id)+'"><div class="saved-plan-head"><div><h3>'+esc(p.title)+'</h3><small>'+esc(formatDate(p.created_at))+'</small></div><span class="plan-id">'+esc(p.support_plan_id)+'</span></div><div class="mini-plan"><div><b>الآن</b>'+stepHtml(p.transition_plan&&p.transition_plan.now)+'</div><span>←</span><div><b>بعد ذلك</b>'+stepHtml(p.transition_plan&&p.transition_plan.then)+'</div></div><p><b>الإشارة:</b> '+esc(sig)+' · <b>المساعدة:</b> '+esc(help)+'</p><div class="row-actions"><button type="button" data-plan-action="open" data-id="'+esc(p.support_plan_id)+'">استخدام الخطة</button><button type="button" data-plan-action="print" data-id="'+esc(p.support_plan_id)+'">طباعة</button><button type="button" data-plan-action="export" data-id="'+esc(p.support_plan_id)+'">تصدير</button><button type="button" class="danger" data-plan-action="delete" data-id="'+esc(p.support_plan_id)+'">حذف</button></div></article>'}
function renderPlans(){var root=$('plansList'),h='',i;if(!root)return;for(i=0;i<state.plans.length;i++)h+=planCardHtml(state.plans[i]);root.innerHTML=h||'<div class="empty"><b>لا توجد خطط محفوظة بعد.</b><span>أنشئ «الآن وبعد ذلك» ثم احفظها هنا.</span></div>';$('plansCount').textContent=String(state.plans.length)}
function openPlan(id){var p=planById(id);if(!p)return;state.current.signal_or_feeling=clone(p.signal_or_feeling);state.current.selected_help=clone(p.selected_help);state.current.now=clone(p.transition_plan.now);state.current.then=clone(p.transition_plan.then);$('planTitle').value=p.title;persist();renderChild();renderTransition();switchView('transition');toast('تم فتح الخطة ويمكن تعديلها وحفظ نسخة جديدة.')}
function deletePlan(id){var i;for(i=0;i<state.plans.length;i++)if(state.plans[i].support_plan_id===id){if(!w.confirm('حذف هذه الخطة من هذا الجهاز؟'))return;state.plans.splice(i,1);persist();renderPlans();toast('تم حذف الخطة من التخزين المحلي.');return}}
function preparePrint(p){var area=$('printArea');if(!area||!p)return;var sig=p.signal_or_feeling&&p.signal_or_feeling.label_ar||'دون تسمية',help=p.selected_help&&p.selected_help.label_ar||'دون مساعدة محددة';area.innerHTML='<section class="print-card"><h1>'+esc(p.title)+'</h1><div class="print-sequence"><div><h2>الآن</h2>'+stepHtml(p.transition_plan.now)+'</div><div class="print-arrow">←</div><div><h2>بعد ذلك</h2>'+stepHtml(p.transition_plan.then)+'</div></div><p><b>إشارة أو شعور اختياري:</b> '+esc(sig)+'</p><p><b>مساعدة معروضة:</b> '+esc(help)+'</p><p class="print-note">هذه البطاقة تعرض خيارات انتقال ومساعدة؛ لا تشخص شعور الطفل ولا تشترط إكمال التسلسل.</p></section>'}
function printPlan(id){var p=id?planById(id):makePlan();if(!p){toast('لا توجد خطة جاهزة للطباعة.');return}preparePrint(p);setTimeout(function(){try{w.print()}catch(e){toast('تعذرت الطباعة على هذا الجهاز. استخدم التصدير بدلًا منها.')}},50)}
function jsonPayload(plans){return {schema_version:SCHEMA,app_id:APP_ID,exported_at:nowIso(),plans:plans,reviews:state.reviews,library:state.library}}
function showExportText(obj){var ta=$('transferText');ta.value=JSON.stringify(obj,null,2);setHidden($('transferBox'),false);try{ta.focus();ta.select()}catch(e){}toast('تم تجهيز نسخة البيانات. يمكنك نسخ النص إذا لم يبدأ التنزيل.')}
function downloadJson(obj,name){var raw=JSON.stringify(obj,null,2);showExportText(obj);try{if(w.Blob&&(w.URL||w.webkitURL)){var blob=new Blob([raw],{type:'application/json;charset=utf-8'}),url=(w.URL||w.webkitURL).createObjectURL(blob),a=d.createElement('a');a.href=url;a.download=name;d.body.appendChild(a);a.click();setTimeout(function(){try{(w.URL||w.webkitURL).revokeObjectURL(url)}catch(e){};if(a.parentNode)a.parentNode.removeChild(a)},400);return}}catch(e){}toast('استخدم مربع البيانات للنسخ اليدوي على هذا الجهاز.')}
function exportOne(id){var p=planById(id);if(p)downloadJson(jsonPayload([p]),'calm-with-me-plan.json')}
function exportAll(){downloadJson(jsonPayload(state.plans),'calm-with-me-data.json')}
function copyTransfer(){var ta=$('transferText');if(!ta||!ta.value)return;try{ta.focus();ta.select();if(d.execCommand&&d.execCommand('copy')){toast('تم نسخ البيانات.');return}}catch(e){}toast('حدد النص وانسخه يدويًا.')}
function validateImported(obj){if(!obj||typeof obj!=='object')return false;if(obj.app_id&&obj.app_id!==APP_ID)return false;if(obj.plans&&!Array.isArray(obj.plans))return false;return true}
function importObject(obj){if(!validateImported(obj)){toast('ملف البيانات غير مناسب لهذا التطبيق.');return}var incoming=obj.plans||[],i,p,existing={};for(i=0;i<state.plans.length;i++)existing[state.plans[i].support_plan_id]=1;for(i=0;i<incoming.length;i++){p=incoming[i];if(!p.support_plan_id||!p.transition_plan)continue;if(!existing[p.support_plan_id]){state.plans.push(p);existing[p.support_plan_id]=1}}if(obj.library&&Array.isArray(obj.library)&&obj.library.length)state.library=obj.library;if(obj.reviews&&Array.isArray(obj.reviews))state.reviews=obj.reviews.concat(state.reviews);persist();renderPlans();renderLibrary();toast('تم استيراد البيانات المتوافقة دون حذف خططك الحالية.')}
function importText(){var raw=trim($('transferText').value);if(!raw){toast('الصق بيانات JSON أولًا.');return}try{importObject(JSON.parse(raw))}catch(e){toast('تعذر قراءة JSON. تحقق من النص وحاول مرة أخرى.')}}
function readImportFile(file){if(!file||!w.FileReader){toast('قراءة الملفات غير متاحة هنا؛ استخدم لصق JSON.');return}var r=new FileReader();r.onload=function(){try{importObject(JSON.parse(text(r.result)))}catch(e){toast('ملف JSON غير صالح.')}};r.onerror=function(){toast('تعذر قراءة الملف. استخدم لصق JSON.');};r.readAsText(file,'utf-8')}
function renderLibrary(){var root=$('libraryList'),h='',i,it;if(!root)return;for(i=0;i<state.library.length;i++){it=state.library[i];h+='<div class="library-row" data-lib="'+esc(it.id)+'"><div class="library-visual">'+imageHtml(it)+'</div><div class="library-main"><input type="text" data-lib-label="'+esc(it.id)+'" value="'+esc(it.label_ar)+'" aria-label="اسم المساعدة"><label class="toggle"><input type="checkbox" data-lib-enabled="'+esc(it.id)+'" '+(it.enabled!==false?'checked':'')+'> تظهر للطفل</label></div><div class="library-actions"><button type="button" data-lib-action="up" data-id="'+esc(it.id)+'" aria-label="تحريك لأعلى">↑</button><button type="button" data-lib-action="down" data-id="'+esc(it.id)+'" aria-label="تحريك لأسفل">↓</button><button type="button" data-lib-action="speak" data-id="'+esc(it.id)+'">🔊</button>'+(it.custom?'<button type="button" class="danger" data-lib-action="remove" data-id="'+esc(it.id)+'">حذف</button>':'')+'</div></div>'}root.innerHTML=h}
function moveLibrary(id,dir){var i=-1,j;for(j=0;j<state.library.length;j++)if(state.library[j].id===id){i=j;break}if(i<0)return;j=i+dir;if(j<0||j>=state.library.length)return;var t=state.library[i];state.library[i]=state.library[j];state.library[j]=t;persist();renderLibrary();renderHelps()}
function removeLibrary(id){var i;for(i=0;i<state.library.length;i++)if(state.library[i].id===id&&state.library[i].custom){state.library.splice(i,1);persist();renderLibrary();renderHelps();return}}
function updateLibraryField(id,field,value){var it=itemById(state.library,id);if(!it)return;it[field]=value;persist();renderHelps()}
function readFileData(file,limit,kind,done){if(!file){done('');return}if(file.size&&file.size>limit){toast(kind+' كبير. اختر ملفًا أصغر للحفظ المحلي.');done('');return}if(!w.FileReader){toast('قراءة الملفات غير متاحة على هذا الجهاز. سيبقى الخيار النصي متاحًا.');done('');return}var r=new FileReader();r.onload=function(){done(text(r.result))};r.onerror=function(){toast('تعذر قراءة '+kind+'.');done('')};r.readAsDataURL(file)}
function addCustomHelp(){var label=trim($('customHelpLabel').value);if(!label){toast('اكتب اسم المساعدة أولًا.');return}state.library.push({id:uid('help'),label_ar:label,image:pendingHelpImage,audio:pendingHelpAudio,symbol:'☆',category:'family',speech_ar:label,enabled:true,custom:true});$('customHelpLabel').value='';$('customHelpImage').value='';$('customHelpAudio').value='';pendingHelpImage='';pendingHelpAudio='';persist();renderLibrary();renderHelps();toast('أضيفت المساعدة محليًا إلى هذه الأسرة.')}
function addCustomTransition(){var label=trim($('customTransitionLabel').value);if(!label){toast('اكتب اسم الخطوة أولًا.');return}state.custom_transitions.push({id:uid('step'),label_ar:label,image:pendingTransitionImage,symbol:'☆',speech_ar:label,custom:true});$('customTransitionLabel').value='';$('customTransitionImage').value='';pendingTransitionImage='';persist();renderTransition();toast('أضيفت خطوة انتقال محلية.')}
function reviewPlanOptions(){var sel=$('reviewPlan'),h='<option value="current">الخطة الحالية</option>',i,p;for(i=0;i<state.plans.length;i++){p=state.plans[i];h+='<option value="'+esc(p.support_plan_id)+'">'+esc(p.title)+'</option>'}sel.innerHTML=h}
function renderReviewForm(){reviewPlanOptions();var levels=C.assistance_levels||[],sel=$('reviewAssistance'),h='',i;for(i=0;i<levels.length;i++)h+='<option value="'+esc(levels[i].id)+'">'+esc(levels[i].label_ar)+'</option>';sel.innerHTML=h;var outcomes=C.review_options||[],root=$('reviewOutcomeButtons');h='';for(i=0;i<outcomes.length;i++)h+='<button type="button" data-review-outcome="'+esc(outcomes[i].id)+'">'+esc(outcomes[i].label_ar)+'</button>';root.innerHTML=h;root.setAttribute('data-selected','')}
function selectedReviewOutcome(){return $('reviewOutcomeButtons').getAttribute('data-selected')||''}
function saveReview(){var outcome=selectedReviewOutcome();if(!outcome){toast('اختر وصفًا لما حدث أو استخدم «توقفنا ولم نكمل».');return}var planId=$('reviewPlan').value,plan=planId==='current'?makePlan():planById(planId),review={review_id:uid('review'),session_id:state.current.session_id,created_at:nowIso(),support_plan_id:plan&&plan.support_plan_id||planId,shown_help:state.current.selected_help&&state.current.selected_help.label_ar||'',outcome:outcome,accepted_help:trim($('reviewAccepted').value),what_helped:trim($('reviewHelped').value),what_did_not:trim($('reviewNotHelped').value),next_change:trim($('reviewNext').value),assistance_level:$('reviewAssistance').value};state.reviews.unshift(review);if(plan&&plan.support_plan_id){var p=planById(plan.support_plan_id);if(p)p.reflection=clone(review)}persist();$('reviewAccepted').value='';$('reviewHelped').value='';$('reviewNotHelped').value='';$('reviewNext').value='';$('reviewOutcomeButtons').setAttribute('data-selected','');renderReviewOutcomeSelection();toast(storageOk?'تم حفظ مراجعة وصفية للمرافق.':'المراجعة باقية في الجلسة فقط؛ استخدم التصدير.')}
function renderReviewOutcomeSelection(){var root=$('reviewOutcomeButtons'),chosen=selectedReviewOutcome(),buttons=root.getElementsByTagName('button'),i;for(i=0;i<buttons.length;i++)buttons[i].className=buttons[i].getAttribute('data-review-outcome')===chosen?'selected':''}
function newSession(){state.current={session_id:uid('session'),signal_or_feeling:null,selected_help:null,now:null,then:null,assistance_level:'adult-offered-two'};$('planTitle').value='';persist();renderChild();renderTransition();switchView('child');toast('بدأ موقف جديد دون حذف الخطط السابقة.')}
function resetLibrary(){if(!w.confirm('إعادة مكتبة المساعدات إلى الخيارات الافتراضية؟ لن تُحذف الخطط المحفوظة.'))return;state.library=clone(C.helps||[]);persist();renderLibrary();renderHelps();toast('عادت مكتبة المساعدات الافتراضية.')}
function formatDate(iso){try{return new Date(iso).toLocaleString('ar')}catch(e){return text(iso)}}
function bind(){
  var nav=$('mainNav');bindActivation(nav,function(b){var v=b.getAttribute('data-view');if(v)switchView(v)});
  bindActivation($('signalCards'),function(b){chooseSignal(b.getAttribute('data-kind'),b.getAttribute('data-id'))});
  bindActivation($('feelingCards'),function(b){chooseSignal(b.getAttribute('data-kind'),b.getAttribute('data-id'))});
  bindActivation($('helpCards'),function(b){chooseHelp(b.getAttribute('data-help'))});
  bindActivation($('nowPicker'),function(b){chooseTransition('now',b.getAttribute('data-step'))});
  bindActivation($('thenPicker'),function(b){chooseTransition('then',b.getAttribute('data-step'))});
  bindActivation($('plansList'),function(b){var a=b.getAttribute('data-plan-action'),id=b.getAttribute('data-id');if(a==='open')openPlan(id);else if(a==='print')printPlan(id);else if(a==='export')exportOne(id);else if(a==='delete')deletePlan(id)});
  bindActivation($('libraryList'),function(b){var a=b.getAttribute('data-lib-action'),id=b.getAttribute('data-id');if(a==='up')moveLibrary(id,-1);else if(a==='down')moveLibrary(id,1);else if(a==='remove')removeLibrary(id);else if(a==='speak')speakItem(itemById(state.library,id))});
  bindActivation($('reviewOutcomeButtons'),function(b){$('reviewOutcomeButtons').setAttribute('data-selected',b.getAttribute('data-review-outcome'));renderReviewOutcomeSelection()});
  $('skipSignalBtn').onclick=skipSignal;$('rejectHelpBtn').onclick=rejectHelp;$('goTransitionBtn').onclick=function(){switchView('transition')};$('goCaregiverBtn').onclick=function(){switchView('caregiver')};
  $('savePlanBtn').onclick=savePlan;$('printCurrentBtn').onclick=function(){printPlan('')};$('newSessionBtn').onclick=newSession;
  $('exportAllBtn').onclick=exportAll;$('copyTransferBtn').onclick=copyTransfer;$('importTextBtn').onclick=importText;$('importFile').onchange=function(){readImportFile(this.files&&this.files[0])};
  $('addHelpBtn').onclick=addCustomHelp;$('addTransitionBtn').onclick=addCustomTransition;$('resetLibraryBtn').onclick=resetLibrary;$('saveReviewBtn').onclick=saveReview;
  $('customHelpImage').onchange=function(){readFileData(this.files&&this.files[0],MAX_IMAGE_BYTES,'الصورة',function(v){pendingHelpImage=v;toast(v?'تم تجهيز الصورة محليًا.':'سيستخدم الخيار رمزًا بصريًا بدل الصورة.')})};
  $('customHelpAudio').onchange=function(){readFileData(this.files&&this.files[0],MAX_AUDIO_BYTES,'الصوت',function(v){pendingHelpAudio=v;toast(v?'تم تجهيز الصوت المحلي.':'سيستخدم TTS أو النص بدل الصوت المسجل.')})};
  $('customTransitionImage').onchange=function(){readFileData(this.files&&this.files[0],MAX_IMAGE_BYTES,'الصورة',function(v){pendingTransitionImage=v;toast(v?'تم تجهيز صورة الخطوة محليًا.':'ستبقى الخطوة نصية/رمزية.')})};
  $('libraryList').onchange=function(e){e=e||w.event;var t=e.target||e.srcElement,id;if(!t)return;id=t.getAttribute('data-lib-enabled');if(id)updateLibraryField(id,'enabled',!!t.checked);id=t.getAttribute('data-lib-label');if(id)updateLibraryField(id,'label_ar',trim(t.value)||'مساعدة')};
  $('speechToggle').onchange=function(){state.settings.speech=!!this.checked;persist();status(this.checked?'الصوت الاختياري مفعّل عند توفره.':'الصوت متوقف؛ التجربة البصرية كاملة.')};
  $('installAppBtn').onclick=function(){if(deferredInstall){try{deferredInstall.prompt();deferredInstall=null}catch(e){}}else toast('استخدم «إضافة إلى الشاشة الرئيسية» من قائمة المتصفح إذا لم يظهر زر التثبيت.')};
  $('updateAppBtn').onclick=function(){if('serviceWorker'in navigator&&navigator.serviceWorker.getRegistration){navigator.serviceWorker.getRegistration('./').then(function(r){if(r){r.update();toast('جارٍ التحقق من التحديث.')}else toast('التحديث التلقائي غير متاح الآن.')},function(){toast('تعذر التحقق الآن.')})}else toast('التحديث التلقائي غير متاح في هذا المتصفح.')};
  w.addEventListener&&w.addEventListener('beforeinstallprompt',function(e){try{e.preventDefault();deferredInstall=e;$('installAppBtn').style.display='inline-block'}catch(x){}},false)
}
function registerSw(){if(!('serviceWorker'in navigator)||w.location.protocol.indexOf('http')!==0)return;var reloading=false;navigator.serviceWorker.addEventListener('controllerchange',function(){if(reloading)return;reloading=true;setTimeout(function(){w.location.reload()},180)});navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(function(reg){if(reg.waiting)try{reg.waiting.postMessage({type:'SKIP_WAITING'})}catch(e){};setTimeout(function(){try{reg.update()}catch(x){}},1200)},function(){})}
function init(){if(!contentValid()){$('fatal').style.display='block';$('fatal').innerHTML='<b>تعذر تشغيل المحتوى بأمان.</b> توجد سجلات ناقصة في قاموس المحتوى.';return}load();$('speechToggle').checked=state.settings.speech!==false;bind();renderChild();renderTransition();renderPlans();renderLibrary();renderReviewForm();switchView('child');registerSw();status('الصوت اختياري. التطبيق يعمل بصريًا حتى عند تعذره.')}
if(d.readyState==='loading'){if(d.addEventListener)d.addEventListener('DOMContentLoaded',init,false);else w.attachEvent&&w.attachEvent('onload',init)}else init();
})(window,document);
