(function(w,d){
'use strict';
var APP_ID='a1-calm';
var STATE_KEY='app360:a1-calm:schema-1.0:state';
var EVENT_KEY='app360:interop:v1:events';
var CATALOG_KEY='app360:interop:v1:catalog-cache';
var ROOT=rootHref();
var catalog=[];
var currentItems=[];
var scanTimer=null;
var lastTouchAt=0;
var $=function(id){return d.getElementById(id)};
function text(v){return String(v==null?'':v)}
function trim(v){return text(v).replace(/^\s+|\s+$/g,'')}
function esc(s){return text(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]})}
function nowIso(){return new Date().toISOString()}
function uid(prefix){return (prefix||'id')+'-'+(+new Date()).toString(36)+'-'+Math.floor(Math.random()*99999)}
function clone(x){try{return JSON.parse(JSON.stringify(x))}catch(e){return x}}
function rootHref(){var a=d.createElement('a');a.href='../../../';return a.href}
function safePath(p){p=text(p).replace(/^\/+/, '');if(!p||/^[a-z]+:\/\//i.test(p)||p.indexOf('..')>=0)return'';return p}
function resolve(p){p=safePath(p);if(!p)return'';var a=d.createElement('a');a.href=ROOT+p;return a.href}
function appendParam(href,key,value){var s=href.indexOf('?')>=0?'&':'?';return href+s+encodeURIComponent(key)+'='+encodeURIComponent(text(value))}
function query(){var out={},s=(w.location.search||'').replace(/^\?/,'').split('&'),i,p;for(i=0;i<s.length;i++){if(!s[i])continue;p=s[i].split('=');try{out[decodeURIComponent(p[0])]=decodeURIComponent(p.slice(1).join('=')||'')}catch(e){}}return out}
function readState(){try{var raw=w.localStorage.getItem(STATE_KEY);return raw?JSON.parse(raw):null}catch(e){return null}}
function writeState(s){try{w.localStorage.setItem(STATE_KEY,JSON.stringify(s));return true}catch(e){return false}}
function sessSet(k,v){try{w.sessionStorage.setItem('app360:calm:interop:'+k,text(v));return true}catch(e){return false}}
function sessGet(k){try{return w.sessionStorage.getItem('app360:calm:interop:'+k)||''}catch(e){return''}}
function sessDel(k){try{w.sessionStorage.removeItem('app360:calm:interop:'+k)}catch(e){}}
function setResume(view,runner,msg){sessSet('view',view||'');sessSet('runner',runner||'');if(msg)sessSet('message',msg);var t=$('planTitle');if(t&&t.value)sessSet('planTitle',t.value)}
function events(){try{var a=JSON.parse(w.localStorage.getItem(EVENT_KEY)||'[]');return a&&a.push?a:[]}catch(e){return[]}}
function completedEvent(launchId){var a=events(),i;for(i=a.length-1;i>=0;i--)if(a[i]&&a[i].launch_id===launchId&&a[i].type==='completed')return a[i];return null}
function xhrJson(path,ok,fail){var url=resolve(path),x;if(!url){fail&&fail(new Error('unsafe path'));return}try{x=new XMLHttpRequest();x.open('GET',url+(url.indexOf('?')>=0?'&':'?')+'_='+Date.now(),true);x.onreadystatechange=function(){if(x.readyState!==4)return;if(x.status>=200&&x.status<300){try{ok(JSON.parse(x.responseText))}catch(e){fail&&fail(e)}}else fail&&fail(new Error('HTTP '+x.status))};x.send(null)}catch(e){fail&&fail(e)}}
function cacheCatalog(list){try{w.localStorage.setItem(CATALOG_KEY,JSON.stringify({at:nowIso(),apps:list}))}catch(e){}}
function cachedCatalog(){try{var x=JSON.parse(w.localStorage.getItem(CATALOG_KEY)||'null');return x&&x.apps&&x.apps.length?x.apps:[]}catch(e){return[]}}
function loadCatalog(done){xhrJson('data/app-links-registry.json',function(reg){var refs=reg.apps||[],out=[],left=refs.length;if(!left){done([]);return}function oneDone(){left--;if(left<=0){catalog=out;cacheCatalog(out);done(out)}}for(var i=0;i<refs.length;i++)(function(meta){xhrJson(meta.archive_path,function(man){man.archive_path=meta.archive_path;out.push(man);oneDone()},function(){oneDone()})})(refs[i])},function(){var c=cachedCatalog();catalog=c;done(c)})}
var loadedScripts={};
function loadScript(path,done){if(loadedScripts[path]){done(true);return}var src=resolve(path);if(!src){done(false);return}var s=d.createElement('script');s.src=src+(src.indexOf('?')>=0?'&':'?')+'interop=1';s.async=true;s.onload=function(){loadedScripts[path]=1;done(true)};s.onerror=function(){done(false)};(d.head||d.documentElement).appendChild(s)}
function appById(id){for(var i=0;i<catalog.length;i++)if(catalog[i].app_id===id)return catalog[i];return null}
function routeById(app,id){var a=app&&app.routes||[];for(var i=0;i<a.length;i++)if(a[i].id===id)return a[i];return null}
function routeNeedsItem(route){return !!(route&&route.href_template&&/\{[^}]+\}/.test(route.href_template))}
function loadSayItems(app,route,done){var path=app.base_path+(route.collection_source||'data/levels-inline-v8.js');loadScript(path,function(ok){if(!ok||!w.APP360_LEVELS){done([]);return}var L=w.APP360_LEVELS,out=[],seen={},lv,rows,i,j,words,cat,key,word;if(route.id==='category'){for(lv=1;lv<=4;lv++){rows=L[String(lv)]||[];for(i=0;i<rows.length;i++){cat=text(rows[i][0]);key=lv+'|'+cat;if(seen[key])continue;seen[key]=1;out.push({value:cat,label:cat,option:'المستوى '+lv+' · '+cat,params:{category:cat,level:lv}})}}done(out);return}for(lv=1;lv<=4;lv++){rows=L[String(lv)]||[];for(i=0;i<rows.length;i++){cat=text(rows[i][0]);words=text(rows[i][2]).split('|');for(j=0;j<words.length;j++){word=trim(words[j]);if(!word)continue;key=lv+'|'+word;if(seen[key])continue;seen[key]=1;out.push({value:word,label:word,option:word+' · '+cat+' · المستوى '+lv,params:{word:word,level:lv}})}}}done(out)})}
function loadImitateItems(app,route,done){xhrJson(app.base_path+(route.collection_source||'experiences.json'),function(data){var rows=data.experiences||[],out=[],i,x;for(i=0;i<rows.length;i++){x=rows[i];out.push({value:x.id,label:x.title||x.id,option:x.id+' · '+(x.title||x.id),params:{id:x.id}})}done(out)},function(){done([])})}
function loadScreenItems(app,route,done){var sources=route.collection_sources||['games-data.js','games-data-v12.js'],idx=0;function next(){if(idx>=sources.length){var a=(w.A1ScreenMoveGames||[]).concat(w.A1ScreenMoveGamesV12||[]),out=[],seen={},i,g;for(i=0;i<a.length;i++){g=a[i];if(!g||!g.id||seen[g.id])continue;seen[g.id]=1;out.push({value:g.id,label:g.title||g.id,option:g.id+' · '+(g.title||g.id),params:{id:g.id}})}done(out);return}loadScript(app.base_path+sources[idx++],function(){next()})}next()}
var LABELS={line_h:'خط أفقي',line_v:'خط رأسي',line_d1:'خط مائل يمين',line_d2:'خط مائل يسار',zigzag:'خط متعرج',wave:'موجة',arches:'أقواس',loops:'حلقات',circle:'دائرة',oval:'بيضاوي',square:'مربع',rectangle:'مستطيل',triangle:'مثلث',diamond:'معين',pentagon:'خماسي',hexagon:'سداسي',semicircle:'نصف دائرة',star:'نجمة',house:'بيت',sun:'شمس',tree:'شجرة',flower:'زهرة',fish:'سمكة',balloon:'بالون',boat:'قارب',face:'وجه مبتسم',apple:'تفاحة',cloud:'سحابة'};
function drawingValues(route){var letters=['ا','ب','ت','ث','ج','ح','خ','د','ذ','ر','ز','س','ش','ص','ض','ط','ظ','ع','غ','ف','ق','ك','ل','م','ن','ه','و','ي','ء','أ','إ','آ','ة','ى'],numbers=['٠','١','٢','٣','٤','٥','٦','٧','٨','٩','١٠'],shapes=['circle','oval','square','rectangle','triangle','diamond','pentagon','hexagon','semicircle','star'];if(route.items&&route.items.length)return route.items;if(route.id==='letters'||route.id==='free-letters')return letters;if(route.id==='numbers'||route.id==='free-numbers')return numbers;if(route.id==='colors'||route.id==='free-shapes')return shapes;return[]}
function loadDrawingItems(app,route,done){var vals=drawingValues(route),out=[],i,v,key;for(i=0;i<vals.length;i++){v=vals[i];key=(route.id.indexOf('letters')>=0||route.id.indexOf('numbers')>=0)?'value':'id';var p={};p[key]=v;out.push({value:v,label:LABELS[v]||v,option:(LABELS[v]||v),params:p})}done(out)}
function loadItems(app,route,done){if(!routeNeedsItem(route)){done([]);return}if(app.app_id==='a1-first-words'){loadSayItems(app,route,done);return}if(app.app_id==='a1-imitate'){loadImitateItems(app,route,done);return}if(app.app_id==='a1-screen-move'){loadScreenItems(app,route,done);return}if(app.app_id==='a1-drawing-writing'){loadDrawingItems(app,route,done);return}done([])}
function buildHref(route,params){var href=route.href||route.href_template||'';if(route.href_template)href=route.href_template.replace(/\{([^}]+)\}/g,function(all,key){return encodeURIComponent(params&&params[key]!=null?params[key]:'')});if(/\{[^}]+\}/.test(href))return'';return safePath(href)}
function hash(s){var h=0,i;for(i=0;i<s.length;i++)h=((h<<5)-h+s.charCodeAt(i))|0;return Math.abs(h)}
function injectStyle(){if($('interopStyle'))return;var s=d.createElement('style');s.id='interopStyle';s.innerHTML='.interop-box,.interop-runner{background:#f7fbff;border:2px solid #8bb9d6;border-radius:22px;padding:18px;margin:18px 0}.interop-box h2,.interop-runner h2{margin:2px 0 6px}.interop-note{color:#456873;margin:0 0 12px}.interop-grid{display:flex;gap:10px;flex-wrap:wrap}.interop-field{flex:1 1 220px;display:flex;flex-direction:column;gap:5px;font-weight:bold}.interop-field select,.interop-field input{width:100%;min-height:50px;border:2px solid #bfd3df;border-radius:13px;background:#fff;padding:9px 11px}.interop-status{margin:10px 0;padding:10px 12px;background:#fff;border-radius:12px;color:#365861}.interop-status.ok{border-right:5px solid #0f8f8a}.interop-status.warn{border-right:5px solid #c28b24}.interop-actions{display:flex;gap:10px;flex-wrap:wrap}.interop-actions button,.interop-run-btn{min-height:50px;border:2px solid #0f8f8a;border-radius:13px;padding:9px 14px;background:#0f8f8a;color:#fff;font-weight:bold}.interop-actions button.secondary{background:#fff;color:#0b716d}.interop-run-btn{background:#17343a;border-color:#17343a}.interop-run-grid{display:flex;gap:12px;flex-wrap:wrap}.interop-run-step{flex:1 1 280px;background:#fff;border:1px solid #cedfe7;border-radius:18px;padding:14px}.interop-run-step.done{border-color:#57a989;background:#f4fffa}.interop-run-step.skipped{border-color:#c9b56b;background:#fffdf1}.interop-run-step h3{margin:4px 0}.interop-badge{display:inline-block;background:#e6f2f8;color:#24536b;border-radius:9px;padding:3px 8px;font-size:.82rem}.interop-run-status{margin:10px 0;font-weight:bold}.interop-run-actions{display:flex;gap:8px;flex-wrap:wrap}.interop-run-actions button{min-height:46px;border:2px solid #0f8f8a;border-radius:12px;background:#fff;color:#0b716d;padding:8px 12px;font-weight:bold}.interop-run-actions .launch{background:#0f8f8a;color:#fff}.interop-run-actions button[disabled]{opacity:.45}.interop-toast{position:fixed;z-index:2147483642;right:50%;bottom:20px;transform:translateX(50%);max-width:90%;background:#17343a;color:#fff;padding:11px 16px;border-radius:14px;box-shadow:0 8px 24px rgba(0,0,0,.22)}@media(max-width:720px){.interop-box,.interop-runner{padding:13px}.interop-field{flex-basis:100%}.interop-run-step{flex-basis:100%}}';(d.head||d.documentElement).appendChild(s)}
function showMessage(msg){var n=d.createElement('div');n.className='interop-toast';n.innerHTML=esc(msg);d.body.appendChild(n);setTimeout(function(){if(n.parentNode)n.parentNode.removeChild(n)},3000)}
function setBuilderStatus(msg,kind){var n=$('interopStatus');if(!n)return;n.className='interop-status '+(kind||'');n.innerHTML=esc(msg)}
function builderHtml(){return '<span class="step-kicker">تطبيقات مختبر 360 المرتبطة</span><h2>أضف نشاطًا حقيقيًا إلى الخطة</h2><p class="interop-note">اختر التطبيق ثم البطاقة أو اللعبة أو الخدمة. سيُحفظ المسار النسبي فقط، وعند التنفيذ يفتح التطبيق الأصلي ويسجل الإكمال ثم يعيدك إلى الخطة.</p><div class="interop-grid"><label class="interop-field">التطبيق<select id="interopApp"><option value="">تحميل التطبيقات…</option></select></label><label class="interop-field">الخدمة<select id="interopRoute"><option value="">اختر التطبيق أولًا</option></select></label><label id="interopItemWrap" class="interop-field" style="display:none">البطاقة أو اللعبة<input id="interopFilter" type="text" placeholder="اكتب للبحث"><select id="interopItem"></select></label></div><div id="interopStatus" class="interop-status">جارٍ قراءة أرشيف الخدمات…</div><div class="interop-actions"><button id="interopAddNow" type="button">استخدام النشاط في «الآن»</button><button id="interopAddThen" class="secondary" type="button">استخدام النشاط في «بعد ذلك»</button></div>'}
function injectUi(){if($('interopBuilder'))return;injectStyle();var transition=$('transitionView'),plans=$('plansView');if(!transition||!plans)return;var box=d.createElement('section');box.id='interopBuilder';box.className='interop-box';box.innerHTML=builderHtml();var custom=transition.querySelector?transition.querySelector('.custom-step-box'):null;if(custom)transition.insertBefore(box,custom);else transition.appendChild(box);var currentRunner=d.createElement('section');currentRunner.id='interopCurrentRunner';currentRunner.className='interop-runner';currentRunner.style.display='none';transition.insertBefore(currentRunner,box.nextSibling);var savedRunner=d.createElement('section');savedRunner.id='interopSavedRunner';savedRunner.className='interop-runner';savedRunner.style.display='none';var list=$('plansList');if(list)plans.insertBefore(savedRunner,list);else plans.appendChild(savedRunner);var actions=transition.querySelector?transition.querySelector('.primary-actions'):null;if(actions&&!$('interopRunCurrentBtn')){var rb=d.createElement('button');rb.id='interopRunCurrentBtn';rb.className='quiet huge';rb.type='button';rb.innerHTML='تنفيذ الخطة الحالية فعليًا';actions.appendChild(rb);rb.onclick=function(){var s=readState();if(!s||!s.current||!s.current.now||!s.current.then){showMessage('اختر «الآن» و«بعد ذلك» أولًا.');return}openRunner(currentRef(s),'interopCurrentRunner')}}bindBuilder();bindPlanRuns();loadCatalog(function(list){renderApps(list)});resumeAfterReload();scanPlans();scanTimer=setInterval(scanPlans,1000)}
function renderApps(list){var s=$('interopApp'),h='<option value="">اختر تطبيقًا</option>',i;if(!s)return;if(!list.length){h+='<option value="">تعذر تحميل الأرشيف</option>';s.innerHTML=h;setBuilderStatus('تعذر تحميل أرشيف الخدمات. الخطط العادية ما زالت تعمل دون تغيير.','warn');return}for(i=0;i<list.length;i++)h+='<option value="'+esc(list[i].app_id)+'">'+esc(list[i].title_ar||list[i].app_id)+'</option>';s.innerHTML=h;setBuilderStatus('الأرشيف جاهز. اختر تطبيقًا ثم خدمة.','ok')}
function renderRoutes(app){var s=$('interopRoute'),h='<option value="">اختر خدمة</option>',a=app&&app.routes||[],i;for(i=0;i<a.length;i++)h+='<option value="'+esc(a[i].id)+'">'+esc(a[i].label_ar||a[i].id)+'</option>';s.innerHTML=h;currentItems=[];hideItems()}
function hideItems(){var wra=$('interopItemWrap');if(wra)wra.style.display='none';var f=$('interopFilter');if(f)f.value='';var s=$('interopItem');if(s)s.innerHTML=''}
function renderItemOptions(){var sel=$('interopItem'),filter=trim($('interopFilter').value).toLowerCase(),h='',shown=0,i,it,hay;if(!sel)return;for(i=0;i<currentItems.length&&shown<150;i++){it=currentItems[i];hay=text(it.option||it.label).toLowerCase();if(filter&&hay.indexOf(filter)<0)continue;h+='<option value="'+i+'">'+esc(it.option||it.label||it.value)+'</option>';shown++}sel.innerHTML=h||'<option value="">لا توجد نتائج</option>';setBuilderStatus('وجدنا '+currentItems.length+' عنصرًا. يعرض البحث حتى 150 نتيجة في كل مرة.','ok')}
function loadRouteSelection(){var app=appById($('interopApp').value),route=routeById(app,$('interopRoute').value);currentItems=[];hideItems();if(!app||!route)return;if(!routeNeedsItem(route)){setBuilderStatus('الخدمة جاهزة للإضافة مباشرة إلى الخطة.','ok');return}var wrap=$('interopItemWrap');if(wrap)wrap.style.display='flex';setBuilderStatus('جارٍ تحميل البطاقات أو الألعاب من المصدر الأصلي…','');loadItems(app,route,function(items){currentItems=items||[];renderItemOptions();if(!currentItems.length)setBuilderStatus('لم نتمكن من قراءة عناصر هذه الخدمة الآن. جرّب خدمة أخرى أو تحقق من الاتصال.','warn')})}
function selectedExternal(){var app=appById($('interopApp').value),route=routeById(app,$('interopRoute').value),item=null,idx,href,label,params={};if(!app||!route)return null;if(routeNeedsItem(route)){idx=parseInt($('interopItem').value,10);if(isNaN(idx)||!currentItems[idx])return null;item=currentItems[idx];params=item.params||{};label=item.label||route.label_ar}else label=route.label_ar;href=buildHref(route,params);if(!href)return null;return {label:label,href:href,app_id:app.app_id,app_title:app.title_ar||app.app_id,route_id:route.id,route_label:route.label_ar||route.id,item_id:item?item.value:'',item_label:item?item.label:'',archive_path:app.archive_path||'',added_at:nowIso()}}
function addExternal(slot){var ext=selectedExternal(),s=readState(),id,step,i,found=false;if(!ext){showMessage('اختر التطبيق والخدمة والعنصر المطلوب أولًا.');return}if(!s||!s.current){showMessage('الحفظ المحلي غير متاح؛ تعذر ربط النشاط بالخطة الحالية.');return}id='ext-'+ext.app_id.replace(/[^a-z0-9-]/gi,'')+'-'+ext.route_id.replace(/[^a-z0-9-]/gi,'')+'-'+hash(ext.href);step={id:id,label_ar:ext.label,symbol:'↗',speech_ar:ext.label,custom:true,external_service:ext};s.custom_transitions=s.custom_transitions||[];for(i=0;i<s.custom_transitions.length;i++)if(s.custom_transitions[i].id===id){s.custom_transitions[i]=clone(step);found=true;break}if(!found)s.custom_transitions.push(clone(step));s.current[slot]=clone(step);if(!writeState(s)){showMessage('تعذر حفظ النشاط على هذا الجهاز.');return}setResume('transition','','تمت إضافة نشاط فعلي إلى '+(slot==='now'?'«الآن»':'«بعد ذلك»')+'.');w.location.reload()}
function bindBuilder(){var app=$('interopApp'),route=$('interopRoute'),filter=$('interopFilter');app.onchange=function(){var a=appById(this.value);renderRoutes(a);setBuilderStatus(a?'اختر الخدمة المطلوبة من التطبيق.':'اختر تطبيقًا أولًا.',a?'ok':'')};route.onchange=loadRouteSelection;filter.onkeyup=renderItemOptions;$('interopAddNow').onclick=function(){addExternal('now')};$('interopAddThen').onclick=function(){addExternal('then')}}
function currentRef(s){return 'current:'+(s.current&&s.current.session_id||'session')}
function findPlan(s,ref){var i;if(ref.indexOf('current:')===0)return {support_plan_id:ref,title:'الخطة الحالية',transition_plan:{now:s.current&&s.current.now,then:s.current&&s.current.then}};for(i=0;i<(s.plans||[]).length;i++)if(s.plans[i].support_plan_id===ref)return s.plans[i];return null}
function ensureRun(s,ref){s.interop_runs=s.interop_runs||{};if(!s.interop_runs[ref])s.interop_runs[ref]={run_id:uid('run'),plan_ref:ref,created_at:nowIso(),updated_at:nowIso(),steps:{now:{status:'pending'},then:{status:'pending'}},history:[]};if(!s.interop_runs[ref].steps)s.interop_runs[ref].steps={now:{status:'pending'},then:{status:'pending'}};if(!s.interop_runs[ref].steps.now)s.interop_runs[ref].steps.now={status:'pending'};if(!s.interop_runs[ref].steps.then)s.interop_runs[ref].steps.then={status:'pending'};if(!s.interop_runs[ref].history)s.interop_runs[ref].history=[];return s.interop_runs[ref]}
function stepLabel(step){return step&&step.label_ar||'خطوة غير محددة'}
function statusText(st){var x=st&&st.status||'pending';if(x==='completed')return '✓ تم التنفيذ فعليًا';if(x==='skipped')return 'تم تجاوز هذه الخطوة';if(x==='opened')return 'تم فتح النشاط ولم يصل تأكيد الإكمال بعد';return 'لم تُنفذ بعد'}
function runnerStepHtml(slot,step,st,enabled){var ext=step&&step.external_service,h='<article class="interop-run-step '+((st&&st.status==='completed')?'done':((st&&st.status==='skipped')?'skipped':''))+'"><span class="step-kicker">'+(slot==='now'?'الآن':'بعد ذلك')+'</span><h3>'+esc(stepLabel(step))+'</h3>';if(ext)h+='<span class="interop-badge">'+esc(ext.app_title)+' · '+esc(ext.route_label)+'</span>';else h+='<span class="interop-badge">خطوة داخل الخطة</span>';h+='<div class="interop-run-status">'+esc(statusText(st))+'</div><div class="interop-run-actions">';if(ext)h+='<button type="button" class="launch" data-interop-action="launch" data-slot="'+slot+'" '+(enabled?'':'disabled')+'>'+((st&&st.status==='completed')?'إعادة النشاط':'فتح النشاط وتنفيذه')+'</button>';else h+='<button type="button" class="launch" data-interop-action="manual" data-slot="'+slot+'" '+(enabled?'':'disabled')+'>تمت هذه الخطوة</button>';h+='<button type="button" data-interop-action="skip" data-slot="'+slot+'" '+(enabled?'':'disabled')+'>تجاوز</button></div></article>';return h}
function openRunner(ref,targetId){var s=readState(),p=s&&findPlan(s,ref),run,target=$(targetId||'interopSavedRunner'),nowDone;if(!s||!p||!p.transition_plan||!p.transition_plan.now||!p.transition_plan.then){showMessage('الخطة غير مكتملة.');return}run=s.interop_runs&&s.interop_runs[ref]?s.interop_runs[ref]:{steps:{now:{status:'pending'},then:{status:'pending'}}};if(!run.steps)run.steps={now:{status:'pending'},then:{status:'pending'}};if(!run.steps.now)run.steps.now={status:'pending'};if(!run.steps.then)run.steps.then={status:'pending'};nowDone=run.steps.now.status==='completed'||run.steps.now.status==='skipped';target.style.display='block';target.setAttribute('data-run-ref',ref);target.innerHTML='<span class="step-kicker">تنفيذ مباشر ومسجل</span><h2>'+esc(p.title||'الخطة')+'</h2><p class="interop-note">ابدأ بخطوة «الآن». عند فتح نشاط من تطبيق آخر سيعود بك إلى هنا بعد الإكمال، ويُسجل التنفيذ بواسطة launch_id نفسه.</p><div class="interop-run-grid">'+runnerStepHtml('now',p.transition_plan.now,run.steps.now,true)+runnerStepHtml('then',p.transition_plan.then,run.steps.then,nowDone)+'</div>';target.scrollIntoView?target.scrollIntoView(true):null}
function saveAndReload(s,view,runner,msg){if(!writeState(s)){showMessage('تعذر حفظ سجل التنفيذ.');return}setResume(view,runner,msg);w.location.reload()}
function markRun(ref,slot,status){var s=readState(),p=s&&findPlan(s,ref),run;if(!s||!p)return;run=ensureRun(s,ref);run.steps[slot]={status:status,at:nowIso(),manual:true};run.updated_at=nowIso();run.history.unshift({at:nowIso(),slot:slot,status:status,manual:true});saveAndReload(s,ref.indexOf('current:')===0?'transition':'plans',ref,status==='completed'?'تم تسجيل تنفيذ الخطوة.':'تم تجاوز الخطوة دون عقوبة.')}
function launchRun(ref,slot){var s=readState(),p=s&&findPlan(s,ref),step,ext,run,launchId,ret,href;if(!s||!p)return;step=p.transition_plan&&p.transition_plan[slot];ext=step&&step.external_service;if(!ext||!ext.href){markRun(ref,slot,'completed');return}launchId=uid('launch');run=ensureRun(s,ref);run.steps[slot]={status:'opened',at:nowIso(),launch_id:launchId,target_app:ext.app_id};run.updated_at=nowIso();run.history.unshift({at:nowIso(),slot:slot,status:'opened',launch_id:launchId,target_app:ext.app_id});s.interop_pending=s.interop_pending||{};s.interop_pending[launchId]={plan_ref:ref,slot:slot,target_app:ext.app_id,target_ref:ext.item_id||ext.route_id,started_at:nowIso()};if(!writeState(s)){showMessage('تعذر حفظ نقطة العودة قبل فتح النشاط.');return}ret='apps/1-4/calm-with-me/index.html?interop_return=1&interop_plan='+encodeURIComponent(ref)+'&interop_slot='+encodeURIComponent(slot);href=appendParam(ext.href,'caller',APP_ID);href=appendParam(href,'launch_id',launchId);href=appendParam(href,'return_to',ret);href=resolve(href);if(!href){showMessage('رابط النشاط غير صالح.');return}w.location.href=href}
function handleRunAction(btn){var holder=btn;while(holder&&holder!==d&&!(holder.getAttribute&&holder.getAttribute('data-run-ref')))holder=holder.parentNode;if(!holder||holder===d)return;var ref=holder.getAttribute('data-run-ref'),action=btn.getAttribute('data-interop-action'),slot=btn.getAttribute('data-slot');if(action==='launch')launchRun(ref,slot);else if(action==='manual')markRun(ref,slot,'completed');else if(action==='skip')markRun(ref,slot,'skipped')}
function closestAction(node,root){while(node&&node!==root&&node!==d){if(node.getAttribute&&(node.getAttribute('data-interop-action')||node.getAttribute('data-interop-run')))return node;node=node.parentNode}return null}
function bindPlanRuns(){function run(e){e=e||w.event;var t=Date.now(),b=closestAction(e.target||e.srcElement,d.body);if(!b)return;if(e.type==='touchend'){lastTouchAt=t;if(e.preventDefault)e.preventDefault()}else if(t-lastTouchAt<650)return;var ref=b.getAttribute('data-interop-run');if(ref){switchTo('plans');openRunner(ref,'interopSavedRunner');return}handleRunAction(b)}if(d.addEventListener){d.addEventListener('touchend',run,false);d.addEventListener('click',run,false)}else d.onclick=run}
function scanPlans(){var root=$('plansList'),cards,i,c,id,actions,b;if(!root||!root.querySelectorAll)return;cards=root.querySelectorAll('.saved-plan[data-plan]');for(i=0;i<cards.length;i++){c=cards[i];id=c.getAttribute('data-plan');if(c.querySelector('[data-interop-run]'))continue;actions=c.querySelector('.row-actions');if(!actions)continue;b=d.createElement('button');b.type='button';b.className='interop-run-btn';b.setAttribute('data-interop-run',id);b.innerHTML='▶ تنفيذ الخطة فعليًا';actions.insertBefore(b,actions.firstChild)}}
function switchTo(view){var b=$('nav-'+view);if(!b)return;try{b.click()}catch(e){if(b.onclick)b.onclick()}}
function resumeAfterReload(){var view=sessGet('view'),runner=sessGet('runner'),msg=sessGet('message'),title=sessGet('planTitle');sessDel('view');sessDel('runner');sessDel('message');sessDel('planTitle');setTimeout(function(){if(title&&$('planTitle'))$('planTitle').value=title;if(view)switchTo(view);if(msg)showMessage(msg);if(runner)setTimeout(function(){openRunner(runner,runner.indexOf('current:')===0?'interopCurrentRunner':'interopSavedRunner')},180)},80)}
function processReturn(){var q=query(),launchId,pending,s,ref,slot,run,ev;if(q.app360_result!=='completed'||!q.app360_launch_id)return false;s=readState();if(!s)return false;launchId=q.app360_launch_id;pending=s.interop_pending&&s.interop_pending[launchId];ref=q.interop_plan||(pending&&pending.plan_ref)||'';slot=q.interop_slot||(pending&&pending.slot)||'';if(!ref||!slot)return false;run=ensureRun(s,ref);ev=completedEvent(launchId);run.steps[slot]={status:'completed',at:nowIso(),launch_id:launchId,target_app:q.app360_target||(pending&&pending.target_app)||'',event_verified:!!ev};run.updated_at=nowIso();run.history.unshift({at:nowIso(),slot:slot,status:'completed',launch_id:launchId,target_app:q.app360_target||(pending&&pending.target_app)||'',event_verified:!!ev});if(s.interop_pending)delete s.interop_pending[launchId];writeState(s);setResume(ref.indexOf('current:')===0?'transition':'plans',ref,'✓ تم تسجيل تنفيذ النشاط والعودة إلى الخطة.');var clean=w.location.href.split('?')[0].split('#')[0];if(w.history&&w.history.replaceState){try{w.history.replaceState(null,d.title,clean);setTimeout(function(){w.location.reload()},40);return true}catch(e){}}try{w.location.replace('index.html')}catch(x){w.location.href='index.html'}return true}
function ready(){return !!($('transitionView')&&$('plansView')&&$('plansList')&&$('planTitle'))}
function initWhenReady(){var n=0,t=setInterval(function(){n++;if(ready()){clearInterval(t);injectUi()}else if(n>80)clearInterval(t)},75)}
if(!processReturn()){if(d.readyState==='loading'){if(d.addEventListener)d.addEventListener('DOMContentLoaded',initWhenReady,false);else w.attachEvent&&w.attachEvent('onload',initWhenReady)}else initWhenReady()}
})(window,document);
