'use strict';
function stageWin(){won=true;S('app360:a1-tangram:done:'+level+':'+puzzleIndex,'1');buildDots();showMsg('اكتمل الشكل!','good',0);d.getElementById('winTitle').innerHTML='أحسنت يا '+esc(userName)+'!';d.getElementById('winText').innerHTML='بنيت '+esc(currentPuzzle().name)+' كاملًا';setTimeout(function(){winCard.style.display='block'},330);celebrate();victoryTone();setTimeout(successCheer,340)}
function celebrate(){confetti=[];var i;for(i=0;i<85;i++)confetti.push({x:W*.5+(Math.random()-.5)*W*.25,y:H*.45+(Math.random()-.5)*H*.1,vx:(Math.random()-.5)*7,vy:-3-Math.random()*6,g:.12+Math.random()*.08,r:3+Math.random()*5,a:1,c:palette[i%palette.length],rot:Math.random()*6});if(fxFrame)caf(fxFrame);animateFx()}
function animateFx(){fctx.clearRect(0,0,W,H);var alive=0,i,p;for(i=0;i<confetti.length;i++){p=confetti[i];p.x+=p.vx;p.y+=p.vy;p.vy+=p.g;p.rot+=.09;p.a-=.009;if(p.a>0&&p.y<H+20){alive++;fctx.save();fctx.globalAlpha=p.a;fctx.translate(p.x,p.y);fctx.rotate(p.rot);fctx.fillStyle=p.c;fctx.fillRect(-p.r,-p.r*.55,p.r*2,p.r*1.1);fctx.restore()}}if(alive)fxFrame=raf(animateFx);else{fctx.clearRect(0,0,W,H);fxFrame=0}}

function openProfile(){unlockAudio();d.getElementById('profilePanel').style.display='block';d.getElementById('profilePanel').setAttribute('aria-hidden','false')}
function closeProfile(){d.getElementById('profilePanel').style.display='none';d.getElementById('profilePanel').setAttribute('aria-hidden','true')}
function saveProfile(){var v=d.getElementById('nameInput').value.replace(/^\s+|\s+$/g,'');if(!v)v='نور';userName=v;userGender=d.getElementById('genderSelect').value==='boy'?'boy':'girl';audioMode=d.getElementById('audioMode').value;S('app360:a1-tangram:name',userName);S('app360:a1-tangram:gender',userGender);S('app360:a1-tangram:audio-mode',audioMode);S('pk_user_name',userName);S('pk_user_gender',userGender);closeProfile();showMsg('تم حفظ الاسم يا '+userName,'good',1200)}
function testAudio(){unlockAudio();successCheer();showMsg('نجرب التشجيع يا '+userName,'good',1100)}

function bind(){var bs=d.getElementsByClassName('levelBtn'),i;for(i=0;i<bs.length;i++)bs[i].onclick=function(){setLevel(parseInt(this.getAttribute('data-level'),10)||0)};d.getElementById('resetBtn').onclick=resetPuzzle;d.getElementById('replayBtn').onclick=resetPuzzle;d.getElementById('nextBtn').onclick=nextPuzzle;d.getElementById('nextPuzzleBtn').onclick=nextPuzzle;d.getElementById('hintBtn').onclick=function(){hints=hints===2?1:2;showMsg(hints===2?'أظهرنا أماكن القطع بوضوح':'التلميح أخف الآن','',900);draw()};d.getElementById('soundBtn').onclick=function(){unlockAudio();soundEnabled=!soundEnabled;S('app360:a1-tangram:sound',soundEnabled?'1':'0');updateSoundBtn();if(soundEnabled)tone(660,90,.02)};d.getElementById('profileBtn').onclick=openProfile;d.getElementById('closeProfile').onclick=closeProfile;d.getElementById('saveProfileBtn').onclick=saveProfile;d.getElementById('testAudioBtn').onclick=testAudio;d.getElementById('profilePanel').onclick=function(e){if(e.target===this)closeProfile()};w.addEventListener('resize',function(){raf(size)},false);w.addEventListener('orientationchange',function(){setTimeout(size,300)},false);d.addEventListener('keydown',function(e){if((e.keyCode||e.which)===27)closeProfile()},false)}
function setupPwa(){if('serviceWorker'in navigator&&location.protocol.indexOf('http')===0){try{navigator.serviceWorker.register('sw.js?v=1',{updateViaCache:'none'}).then(function(r){try{r.update()}catch(e){}})}catch(e){}}}
loadPrefs();bind();fetchRegistry();size();refresh(true);setupPwa();
