'use strict';
function stageWin(){won=true;S('app360:a1-tangram:done:'+level+':'+puzzleIndex,'1');updateLevelButtons();buildDots();showMsg('اكتمل الشكل!','good',0);d.getElementById('winTitle').innerHTML='أحسنت يا '+esc(userName)+'!';d.getElementById('winText').innerHTML='بنيت '+esc(currentPuzzle().name)+' كاملًا';setTimeout(function(){winCard.style.display='block'},330);celebrate();victoryTone();setTimeout(successCheer,340)}
function celebrate(){confetti=[];var i;for(i=0;i<85;i++)confetti.push({x:W*.5+(Math.random()-.5)*W*.25,y:H*.45+(Math.random()-.5)*H*.1,vx:(Math.random()-.5)*7,vy:-3-Math.random()*6,g:.12+Math.random()*.08,r:3+Math.random()*5,a:1,c:palette[i%palette.length],rot:Math.random()*6});if(fxFrame)caf(fxFrame);animateFx()}
function animateFx(){fctx.clearRect(0,0,W,H);var alive=0,i,p;for(i=0;i<confetti.length;i++){p=confetti[i];p.x+=p.vx;p.y+=p.vy;p.vy+=p.g;p.rot+=.09;p.a-=.009;if(p.a>0&&p.y<H+20){alive++;fctx.save();fctx.globalAlpha=p.a;fctx.translate(p.x,p.y);fctx.rotate(p.rot);fctx.fillStyle=p.c;fctx.fillRect(-p.r,-p.r*.55,p.r*2,p.r*1.1);fctx.restore()}}if(alive)fxFrame=raf(animateFx);else{fctx.clearRect(0,0,W,H);fxFrame=0}}
function openPanel(id){var el=d.getElementById(id);if(!el)return;el.style.display='block';el.setAttribute('aria-hidden','false')}
function closePanel(id){var el=d.getElementById(id);if(!el)return;el.style.display='none';el.setAttribute('aria-hidden','true')}
function openProfile(){unlockAudio();openPanel('profilePanel')}
function closeProfile(){closePanel('profilePanel')}
function saveProfile(){var v=d.getElementById('nameInput').value.replace(/^\s+|\s+$/g,'');if(!v)v='نور';userName=v;userGender=d.getElementById('genderSelect').value==='boy'?'boy':'girl';audioMode=d.getElementById('audioMode').value;S('app360:a1-tangram:name',userName);S('app360:a1-tangram:gender',userGender);S('app360:a1-tangram:audio-mode',audioMode);S('pk_user_name',userName);S('pk_user_gender',userGender);closeProfile();showMsg('تم حفظ الاسم يا '+userName,'good',1200)}
function testAudio(){unlockAudio();successCheer();showMsg('نجرب التشجيع يا '+userName,'good',1100)}
function openSettings(){d.getElementById('snapRange').value=Math.round(settings.snapFactor*100);d.getElementById('pickupRange').value=Math.round(settings.pickupFactor*100);d.getElementById('snapValue').innerHTML=Math.round(settings.snapFactor*100)+'%';d.getElementById('pickupValue').innerHTML=Math.round(settings.pickupFactor*100)+'%';openPanel('settingsPanel')}
function closeSettings(){closePanel('settingsPanel')}
function saveSettingsFromUI(){settings.snapFactor=(parseInt(d.getElementById('snapRange').value,10)||65)/100;settings.pickupFactor=(parseInt(d.getElementById('pickupRange').value,10)||95)/100;saveSettings();closeSettings();showMsg('تم حفظ الإعدادات','good',900);draw()}
function resetSettingsDefaults(){d.getElementById('snapRange').value='65';d.getElementById('pickupRange').value='95';d.getElementById('snapValue').innerHTML='65%';d.getElementById('pickupValue').innerHTML='95%'}
function openLevelMap(){renderLevelMap();openPanel('levelMapPanel')}
function closeLevelMap(){closePanel('levelMapPanel')}
function bind(){var bs=d.getElementsByClassName('levelBtn'),i;for(i=0;i<bs.length;i++)bs[i].onclick=function(){var lv=parseInt(this.getAttribute('data-level'),10)||0;if(lv!==level){level=lv;puzzleIndex=findFirstIncomplete(lv);savePrefs();refresh(true)}openLevelMap()};d.getElementById('resetBtn').onclick=resetPuzzle;d.getElementById('replayBtn').onclick=resetPuzzle;d.getElementById('nextBtn').onclick=nextPuzzle;d.getElementById('nextPuzzleBtn').onclick=nextPuzzle;d.getElementById('hintBtn').onclick=function(){hints=hints===2?1:2;showMsg(hints===2?'أظهرنا أماكن القطع بوضوح':'التلميح أخف الآن','',900);draw()};d.getElementById('soundBtn').onclick=function(){unlockAudio();soundEnabled=!soundEnabled;S('app360:a1-tangram:sound',soundEnabled?'1':'0');updateSoundBtn();if(soundEnabled)tone(660,90,.02)};d.getElementById('profileBtn').onclick=openProfile;d.getElementById('closeProfile').onclick=closeProfile;d.getElementById('saveProfileBtn').onclick=saveProfile;d.getElementById('testAudioBtn').onclick=testAudio;d.getElementById('settingsBtn').onclick=openSettings;d.getElementById('closeSettings').onclick=closeSettings;d.getElementById('saveSettingsBtn').onclick=saveSettingsFromUI;d.getElementById('resetSettingsBtn').onclick=resetSettingsDefaults;d.getElementById('snapRange').oninput=function(){d.getElementById('snapValue').innerHTML=this.value+'%'};d.getElementById('pickupRange').oninput=function(){d.getElementById('pickupValue').innerHTML=this.value+'%'};d.getElementById('stageMapBtn').onclick=openLevelMap;d.getElementById('closeLevelMap').onclick=closeLevelMap;d.getElementById('levelMapGrid').onclick=function(e){var t=e.target;while(t&&t!==this&&!t.getAttribute('data-stage'))t=t.parentNode;if(t&&t.getAttribute&&t.getAttribute('data-stage')){setPuzzle(parseInt(t.getAttribute('data-stage'),10)||0);closeLevelMap()}};d.getElementById('profilePanel').onclick=function(e){if(e.target===this)closeProfile()};d.getElementById('settingsPanel').onclick=function(e){if(e.target===this)closeSettings()};d.getElementById('levelMapPanel').onclick=function(e){if(e.target===this)closeLevelMap()};w.addEventListener('resize',function(){raf(size)},false);w.addEventListener('orientationchange',function(){setTimeout(size,300)},false);d.addEventListener('keydown',function(e){var k=e.keyCode||e.which;if(k===27){closeProfile();closeSettings();closeLevelMap()}},false)}
function setupPwa(){if('serviceWorker'in navigator&&location.protocol.indexOf('http')===0){try{navigator.serviceWorker.register('sw.js?v=8',{updateViaCache:'none'}).then(function(r){try{r.update()}catch(e){}})}catch(e){}}}
loadPrefs();bind();fetchRegistry();size();refresh(true);setupPwa();
