'use strict';
(function(){
/* v10: compact large figures, overlap protection, bigger tool pieces, and viewport-safe layout. */
var PI=Math.PI;
function rawFactorV10(a){return a&&a.length>4&&a[4]?a[4]:1}
function rawColorV10(a,type,i){return a&&a.length>5&&a[5]?a[5]:(typePalette[type]||palette[i%palette.length])}
function normalizedFactorV10(f){f=f||1;return n(.72+f*.42,.82,1.18)}
computeZones=function(){var pad=Math.max(8,Math.round(Math.min(W,H)*.016)),split;if(W/H>1.12){zones.mode='side';split=Math.round(W*.76);zones.target={x:pad,y:pad,w:split-pad*1.35,h:H-pad*2};zones.tray={x:split+pad*.35,y:pad,w:W-split-pad*1.35,h:H-pad*2}}else{zones.mode='stack';split=Math.round(H*.67);zones.target={x:pad,y:pad,w:W-pad*2,h:split-pad*1.05};zones.tray={x:pad,y:split+pad*.10,w:W-pad*2,h:H-split-pad*1.10}}zones.targetInner={x:zones.target.x+9,y:zones.target.y+36,w:Math.max(90,zones.target.w-18),h:Math.max(90,zones.target.h-46)};zones.trayInner={x:zones.tray.x+9,y:zones.tray.y+36,w:Math.max(80,zones.tray.w-18),h:Math.max(80,zones.tray.h-46)}};
function layoutV10(raw){var i,a,minX=9,maxX=-9,minY=9,maxY=-9,spanX,spanY,availW,availH,scale,w0,h0;for(i=0;i<raw.length;i++){a=raw[i];if(a[1]<minX)minX=a[1];if(a[1]>maxX)maxX=a[1];if(a[2]<minY)minY=a[2];if(a[2]>maxY)maxY=a[2]}spanX=Math.max(.16,maxX-minX);spanY=Math.max(.16,maxY-minY);availW=zones.targetInner.w*(zones.mode==='side'?.88:.90);availH=zones.targetInner.h*(zones.mode==='side'?.84:.86);scale=Math.min(availW/spanX,availH/spanY);w0=spanX*scale;h0=spanY*scale;return{minX:minX,minY:minY,spanX:spanX,spanY:spanY,scale:scale,x:zones.targetInner.x+(zones.targetInner.w-w0)/2,y:zones.targetInner.y+(zones.targetInner.h-h0)/2,w:w0,h:h0}}
function keepInsideV10(p){var r=Math.max(8,p.size*.48);p.tx=n(p.tx,zones.targetInner.x+r,zones.targetInner.x+zones.targetInner.w-r);p.ty=n(p.ty,zones.targetInner.y+r,zones.targetInner.y+zones.targetInner.h-r)}
function repelOverlapsV10(list){var pass,i,j,a,b,dx,dy,d,minD,push,ux,uy;for(pass=0;pass<8;pass++){for(i=0;i<list.length;i++){for(j=i+1;j<list.length;j++){a=list[i];b=list[j];dx=b.tx-a.tx;dy=b.ty-a.ty;d=Math.sqrt(dx*dx+dy*dy);minD=(a.size+b.size)*.42;if(d<minD){if(d<1){ux=((i+j)%2?1:-1);uy=((j%3)-1)*.35;d=1}else{ux=dx/d;uy=dy/d}push=(minD-d)*.53+1;a.tx-=ux*push*.48;a.ty-=uy*push*.48;b.tx+=ux*push*.52;b.ty+=uy*push*.52;keepInsideV10(a);keepInsideV10(b)}}}}}
rebuildPieces=function(){var cp=currentPuzzle&&currentPuzzle(),raw=cp&&cp.pieces?cp.pieces:[],old={},i,a,o,lay=layoutV10(raw),base=n(lay.scale*(level===0?.112:(level===1?.118:.112)),38,W>1200?150:(W>700?125:100)),factor,nf;base*=cp&&cp.pieceScale?cp.pieceScale:1;for(i=0;i<pieces.length;i++)old[pieces[i].id]=pieces[i];pieces=[];for(i=0;i<raw.length;i++){a=raw[i];o=old['p'+i];factor=rawFactorV10(a);nf=normalizedFactorV10(factor);pieces.push({id:'p'+i,type:a[0],tx:lay.x+((a[1]-lay.minX)/lay.spanX)*lay.w,ty:lay.y+((a[2]-lay.minY)/lay.spanY)*lay.h,rot:a[3]||0,size:base*nf,factor:factor,color:rawColorV10(a,a[0],i),placed:o?o.placed:false,state:o?(o.placed?'placed':(o.state==='drag'?'tray':o.state)):'tray',x:o?o.x:0,y:o?o.y:0,magnet:false})}repelOverlapsV10(pieces);for(i=0;i<pieces.length;i++){if(pieces[i].placed){pieces[i].state='placed';pieces[i].x=pieces[i].tx;pieces[i].y=pieces[i].ty}else if(pieces[i].state!=='drag')pieces[i].state='tray'}buildTrayStacks();updateStatus()};
trayPieceScale=function(slotW,slotH){return n(Math.min(slotW,slotH)*.62,34,W>1000?104:88)};
var oldDrawPanelV10=drawPanel;drawPanel=function(rect,title,icon){ctx.save();ctx.shadowColor='rgba(72,39,14,.18)';ctx.shadowBlur=16;ctx.shadowOffsetY=6;ctx.fillStyle='rgba(255,249,236,.97)';roundRect(ctx,rect.x,rect.y,rect.w,rect.h,22);ctx.fill();ctx.shadowColor='transparent';ctx.lineWidth=2;ctx.strokeStyle='rgba(122,74,34,.25)';ctx.stroke();ctx.fillStyle='rgba(255,255,255,.40)';roundRect(ctx,rect.x+4,rect.y+4,rect.w-8,Math.max(18,rect.h*.11),18);ctx.fill();ctx.fillStyle='#74471f';ctx.font='bold '+(W>900?19:16)+'px Tahoma';ctx.textAlign='center';ctx.fillText((icon?icon+' ':'')+title,rect.x+rect.w/2,rect.y+25);ctx.restore()};
drawGuidePiece=function(p,alpha){drawPiece(ctx,p,p.tx,p.ty,'#b9a486',Math.min(.34,alpha),2.2)};
})();
