'use strict';
(function(){
/* v17: keep the successful v15 composition exactly, with only a very small overlap reduction. */
var PI=Math.PI;
function rf17(a){return a&&a.length>4&&a[4]?a[4]:1}
function rc17(a,t,i){return a&&a.length>5&&a[5]?a[5]:(typePalette[t]||palette[i%palette.length])}
function fk17(v){return Math.round((v||1)*100)/100}
function profiles17(raw){var m={},i,a,t,k,j,exists;for(i=0;i<raw.length;i++){a=raw[i];t=a[0];if(!m[t])m[t]=[];exists=false;for(j=0;j<m[t].length;j++)if(fk17(m[t][j])===fk17(rf17(a))){exists=true;break}if(!exists)m[t].push(rf17(a))}for(k in m)if(m.hasOwnProperty(k))m[k].sort(function(x,y){return x-y});return m}
function vf17(t,f,p){var a=p[t]||[f],i,idx=0,k=fk17(f);for(i=0;i<a.length;i++)if(fk17(a[i])===k){idx=i;break}if(a.length===1)return 1;if(a.length===2)return idx===0 ? .80 : 1.22;if(a.length===3)return idx===0 ? .76 : (idx===1 ? 1 : 1.28);if(a.length===4)return [.73,.90,1.08,1.30][idx]||1;return .72+(idx/Math.max(1,a.length-1))*.58}
function focus17(){return (' '+(d.body.className||'')+' ').indexOf(' shapeFocus ')>=0}
computeZones=function(){var pad=Math.max(6,Math.round(Math.min(W,H)*.014)),split,focus=focus17();if(W/H>1.08){zones.mode='side';split=Math.round(W*(focus ? .78 : .75));zones.target={x:pad,y:pad,w:split-pad*1.2,h:H-pad*2};zones.tray={x:split+pad*.2,y:pad,w:W-split-pad*1.2,h:H-pad*2}}else{zones.mode='stack';split=Math.round(H*(focus ? .68 : .65));zones.target={x:pad,y:pad,w:W-pad*2,h:split-pad*.8};zones.tray={x:pad,y:split+pad*.1,w:W-pad*2,h:H-split-pad*1.1}}zones.targetInner={x:zones.target.x+8,y:zones.target.y+34,w:Math.max(90,zones.target.w-16),h:Math.max(86,zones.target.h-42)};zones.trayInner={x:zones.tray.x+8,y:zones.tray.y+34,w:Math.max(80,zones.tray.w-16),h:Math.max(76,zones.tray.h-42)}};
function keep17(p){var r=Math.max(7,p.size*.58);p.tx=n(p.tx,zones.targetInner.x+r,zones.targetInner.x+zones.targetInner.w-r);p.ty=n(p.ty,zones.targetInner.y+r,zones.targetInner.y+zones.targetInner.h-r)}
/* Only slightly stronger than v15 (.28 -> .30). No shape-aware separation, so balance stays like v15. */
function repel17(list){var pass,i,j,a,b,dx,dy,dd,minD,ux,uy,push;for(pass=0;pass<5;pass++){for(i=0;i<list.length;i++){for(j=i+1;j<list.length;j++){a=list[i];b=list[j];dx=b.tx-a.tx;dy=b.ty-a.ty;dd=Math.sqrt(dx*dx+dy*dy);minD=(a.size+b.size)*.30;if(dd<minD){if(dd<1){ux=((i+j)%2?1:-1);uy=((j%3)-1)*.25}else{ux=dx/dd;uy=dy/dd}push=(minD-dd)*.46+.6;a.tx-=ux*push*.48;a.ty-=uy*push*.48;b.tx+=ux*push*.52;b.ty+=uy*push*.52;keep17(a);keep17(b)}}}}}
function bounds17(list){var i,p,r,minX=1e9,maxX=-1e9,minY=1e9,maxY=-1e9;for(i=0;i<list.length;i++){p=list[i];r=p.size*.70;if(p.tx-r<minX)minX=p.tx-r;if(p.tx+r>maxX)maxX=p.tx+r;if(p.ty-r<minY)minY=p.ty-r;if(p.ty+r>maxY)maxY=p.ty+r}return{minX:minX,maxX:maxX,minY:minY,maxY:maxY,w:Math.max(1,maxX-minX),h:Math.max(1,maxY-minY),cx:(minX+maxX)/2,cy:(minY+maxY)/2}}
function enlarge17(list){var b=bounds17(list),inner=zones.targetInner,scale=Math.min(inner.w*.88/b.w,inner.h*.86/b.h),i,p,cx=inner.x+inner.w/2,cy=inner.y+inner.h/2;scale=n(scale,.96,1.34);for(i=0;i<list.length;i++){p=list[i];p.tx=cx+(p.tx-b.cx)*scale;p.ty=cy+(p.ty-b.cy)*scale;p.size*=scale;keep17(p)}}
rebuildPieces=function(){var cp=currentPuzzle&&currentPuzzle(),raw=cp&&cp.pieces?cp.pieces:[],old={},prof=profiles17(raw),i,a,o,vf,inner=zones.targetInner,unit=Math.min(inner.w/.90,inner.h/.80),compact=zones.mode==='side' ? .70 : .64,coef=level===0 ? .178 : (level===1 ? .162 : .148),base=n(unit*coef,level===0 ? 46 : (level===1 ? 42 : 39),W>1200 ? 146 : (W>700 ? 124 : 104)),cx=inner.x+inner.w*.50,cy=inner.y+inner.h*.50;if(!raw.length)return;base*=cp&&cp.pieceScale?cp.pieceScale:1;for(i=0;i<pieces.length;i++)old[pieces[i].id]=pieces[i];pieces=[];for(i=0;i<raw.length;i++){a=raw[i];o=old['p'+i];vf=vf17(a[0],rf17(a),prof);pieces.push({id:'p'+i,type:a[0],tx:cx+(a[1]-.50)*unit*compact,ty:cy+(a[2]-.45)*unit*compact,rot:a[3]||0,size:base*vf,factor:rf17(a),visualFactor:vf,color:rc17(a,a[0],i),placed:o?o.placed:false,state:o&&o.placed?'placed':'tray',x:o&&o.placed?o.x:0,y:o&&o.placed?o.y:0,magnet:false})}repel17(pieces);enlarge17(pieces);repel17(pieces);for(i=0;i<pieces.length;i++){if(pieces[i].placed){pieces[i].state='placed';pieces[i].x=pieces[i].tx;pieces[i].y=pieces[i].ty}else pieces[i].state='tray'}drag=null;buildTrayStacks();updateStatus()};
trayPieceScale=function(sw,sh){return n(Math.min(sw,sh)*.72,40,W>1000 ? 116 : 98)};
})();
