'use strict';
(function(){
/* v14 final visual fit: the whole figure fills its target panel while preserving size differences. */
var PI=Math.PI;
function rf(a){return a&&a.length>4&&a[4]?a[4]:1}
function rc(a,t,i){return a&&a.length>5&&a[5]?a[5]:(typePalette[t]||palette[i%palette.length])}
function fk(v){return Math.round((v||1)*100)/100}
function profiles(raw){var m={},i,a,t,k,j,exists;for(i=0;i<raw.length;i++){a=raw[i];t=a[0];if(!m[t])m[t]=[];exists=false;for(j=0;j<m[t].length;j++)if(fk(m[t][j])===fk(rf(a))){exists=true;break}if(!exists)m[t].push(rf(a))}for(k in m)if(m.hasOwnProperty(k))m[k].sort(function(x,y){return x-y});return m}
function visualFactor(t,f,p){var a=p[t]||[f],i,idx=0,k=fk(f);for(i=0;i<a.length;i++)if(fk(a[i])===k){idx=i;break}if(a.length===1)return 1;if(a.length===2)return idx===0?.80:1.22;if(a.length===3)return idx===0?.76:(idx===1?1:1.28);if(a.length===4)return [.73,.90,1.08,1.30][idx]||1;return .72+(idx/Math.max(1,a.length-1))*.58}
function focusMode(){return (' '+(d.body.className||'')+' ').indexOf(' shapeFocus ')>=0}
computeZones=function(){var pad=Math.max(6,Math.round(Math.min(W,H)*.014)),split,focus=focusMode();if(W/H>1.08){zones.mode='side';split=Math.round(W*(focus?.77:.75));zones.target={x:pad,y:pad,w:split-pad*1.20,h:H-pad*2};zones.tray={x:split+pad*.20,y:pad,w:W-split-pad*1.20,h:H-pad*2}}else{zones.mode='stack';split=Math.round(H*(focus?.67:.65));zones.target={x:pad,y:pad,w:W-pad*2,h:split-pad*.8};zones.tray={x:pad,y:split+pad*.1,w:W-pad*2,h:H-split-pad*1.1}}zones.targetInner={x:zones.target.x+8,y:zones.target.y+34,w:Math.max(90,zones.target.w-16),h:Math.max(90,zones.target.h-42)};zones.trayInner={x:zones.tray.x+8,y:zones.tray.y+34,w:Math.max(80,zones.tray.w-16),h:Math.max(75,zones.tray.h-42)}};
function rawBounds(raw){var i,a,minX=9,maxX=-9,minY=9,maxY=-9;for(i=0;i<raw.length;i++){a=raw[i];if(a[1]<minX)minX=a[1];if(a[1]>maxX)maxX=a[1];if(a[2]<minY)minY=a[2];if(a[2]>maxY)maxY=a[2]}return{minX:minX,maxX:maxX,minY:minY,maxY:maxY,spanX:Math.max(.12,maxX-minX),spanY:Math.max(.12,maxY-minY)}}
function clampInside(p){var r=Math.max(6,p.size*.56);p.tx=n(p.tx,zones.targetInner.x+r,zones.targetInner.x+zones.targetInner.w-r);p.ty=n(p.ty,zones.targetInner.y+r,zones.targetInner.y+zones.targetInner.h-r)}
function measure(list){var i,p,r,minX=1e9,maxX=-1e9,minY=1e9,maxY=-1e9;for(i=0;i<list.length;i++){p=list[i];r=p.size*.72;if(p.tx-r<minX)minX=p.tx-r;if(p.tx+r>maxX)maxX=p.tx+r;if(p.ty-r<minY)minY=p.ty-r;if(p.ty+r>maxY)maxY=p.ty+r}return{minX:minX,maxX:maxX,minY:minY,maxY:maxY,w:Math.max(1,maxX-minX),h:Math.max(1,maxY-minY),cx:(minX+maxX)/2,cy:(minY+maxY)/2}}
function fillTarget(list){var b=measure(list),inner=zones.targetInner,k=Math.min(inner.w*.93/b.w,inner.h*.91/b.h);k=n(k,.88,1.38);var tcx=inner.x+inner.w/2,tcy=inner.y+inner.h/2,i,p;for(i=0;i<list.length;i++){p=list[i];p.tx=tcx+(p.tx-b.cx)*k;p.ty=tcy+(p.ty-b.cy)*k;p.size*=k;clampInside(p)}}
function preventHidden(list){var pass,i,j,a,b,dx,dy,dd,minD,ux,uy,push;for(pass=0;pass<4;pass++){for(i=0;i<list.length;i++){for(j=i+1;j<list.length;j++){a=list[i];b=list[j];dx=b.tx-a.tx;dy=b.ty-a.ty;dd=Math.sqrt(dx*dx+dy*dy);minD=Math.min(a.size,b.size)*.20;if(dd<minD){if(dd<1){ux=((i+j)%2?1:-1);uy=((j%3)-1)*.30}else{ux=dx/dd;uy=dy/dd}push=(minD-dd)*.52+1;a.tx-=ux*push*.48;a.ty-=uy*push*.48;b.tx+=ux*push*.52;b.ty+=uy*push*.52;clampInside(a);clampInside(b)}}}}}
rebuildPieces=function(){var cp=currentPuzzle&&currentPuzzle(),raw=cp&&cp.pieces?cp.pieces:[],old={},prof=profiles(raw),rb=rawBounds(raw),i,a,o,vf,inner=zones.targetInner,usableW=inner.w*.86,usableH=inner.h*.82,mapScale=Math.min(usableW/rb.spanX,usableH/rb.spanY),drawW=rb.spanX*mapScale,drawH=rb.spanY*mapScale,ox=inner.x+(inner.w-drawW)/2,oy=inner.y+(inner.h-drawH)/2,base=n(Math.min(inner.w,inner.h)*(level===0?.135:(level===1?.125:.112)),38,W>1200?122:(W>700?106:92));if(!raw.length)return;for(i=0;i<pieces.length;i++)old[pieces[i].id]=pieces[i];pieces=[];base*=cp&&cp.pieceScale?cp.pieceScale:1;for(i=0;i<raw.length;i++){a=raw[i];o=old['p'+i];vf=visualFactor(a[0],rf(a),prof);pieces.push({id:'p'+i,type:a[0],tx:ox+((a[1]-rb.minX)/rb.spanX)*drawW,ty:oy+((a[2]-rb.minY)/rb.spanY)*drawH,rot:a[3]||0,size:base*vf,factor:rf(a),visualFactor:vf,color:rc(a,a[0],i),placed:o?o.placed:false,state:o?(o.placed?'placed':'tray'):'tray',x:o&&o.placed?o.x:0,y:o&&o.placed?o.y:0,magnet:false})}fillTarget(pieces);preventHidden(pieces);for(i=0;i<pieces.length;i++){if(pieces[i].placed){pieces[i].state='placed';pieces[i].x=pieces[i].tx;pieces[i].y=pieces[i].ty}else{pieces[i].state='tray'}}drag=null;buildTrayStacks();updateStatus()};
trayPieceScale=function(slotW,slotH){return n(Math.min(slotW,slotH)*.66,34,W>1000?104:90)};
})();
