'use strict';
var d=document,w=window;
var canvas=d.getElementById('gameCanvas'),ctx=canvas.getContext('2d'),wrap=d.getElementById('boardWrap');
var fx=d.getElementById('celebrateCanvas'),fctx=fx.getContext('2d');
var message=d.getElementById('message'),winCard=d.getElementById('winCard'),pieceStatus=d.getElementById('pieceStatus');
var levelLabel=d.getElementById('levelLabel'),puzzleTitle=d.getElementById('puzzleTitle'),progressDots=d.getElementById('progressDots');
var raf=w.requestAnimationFrame||w.webkitRequestAnimationFrame||function(fn){return setTimeout(fn,16)};
var caf=w.cancelAnimationFrame||w.webkitCancelAnimationFrame||clearTimeout;
var DPR=1,W=1,H=1,level=0,puzzleIndex=0,pieces=[],trayStacks=[],drag=null,hints=1,won=false,fxFrame=0,confetti=[];
var soundEnabled=true,userName='نور',userGender='girl',audioMode='auto',registry=null,audioCtx=null,lastCheer=-1,audioUnlocked=false;
var SHARED='../../../resources/early-child-name-audio/';
var palette=['#ef4b4d','#f4c845','#41a8e5','#79c94b','#8a4fc5','#f08f35','#e967b2'];
var typePalette={tri:'#ef4b4d',square:'#41a8e5',rect:'#f4c845',para:'#79c94b',semi:'#e967b2',circle:'#f08f35',diamond:'#8a4fc5'};
var zones={mode:'stack',target:null,targetInner:null,tray:null,trayInner:null};
var settings={snapFactor:.65,pickupFactor:.95};
function S(k,v){try{if(w.localStorage)localStorage.setItem(k,String(v))}catch(e){}}
function G(k,v){try{var x=w.localStorage?localStorage.getItem(k):null;return x===null?String(v):x}catch(e){return String(v)}}
function n(v,a,b){return Math.max(a,Math.min(b,v))}
function dist(a,b){var x=a.x-b.x,y=a.y-b.y;return Math.sqrt(x*x+y*y)}
function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function showMsg(t,kind,delay){message.className='message'+(kind?' '+kind:'');message.innerHTML=esc(t);if(delay)setTimeout(function(){if(!won){message.className='message';message.innerHTML='اسحب من الأدوات إلى مكان القطعة'}},delay)}
function unlockAudio(){if(audioUnlocked)return;audioUnlocked=true;try{var AC=w.AudioContext||w.webkitAudioContext;if(AC){audioCtx=audioCtx||new AC();if(audioCtx.state==='suspended'&&audioCtx.resume)audioCtx.resume()}}catch(e){}}
function tri(s){return [[-s*.55,s*.45],[0,-s*.52],[s*.55,s*.45]]}
function square(s){return [[-s*.48,-s*.48],[s*.48,-s*.48],[s*.48,s*.48],[-s*.48,s*.48]]}
function rect(s){return [[-s*.68,-s*.32],[s*.68,-s*.32],[s*.68,s*.32],[-s*.68,s*.32]]}
function para(s){return [[-s*.55,-s*.36],[s*.34,-s*.36],[s*.55,s*.36],[-s*.34,s*.36]]}
function semi(s){var p=[],i,t;for(i=0;i<=12;i++){t=Math.PI*i/12;p.push([Math.cos(t)*s*.55,-Math.sin(t)*s*.55])}p.push([-s*.55,0]);return p}
function circlePoly(s){var p=[],i,t;for(i=0;i<18;i++){t=Math.PI*2*i/18;p.push([Math.cos(t)*s*.48,Math.sin(t)*s*.48])}return p}
function diamond(s){return [[0,-s*.58],[s*.48,0],[0,s*.58],[-s*.48,0]]}
function shape(type,s){if(type==='tri')return tri(s);if(type==='square')return square(s);if(type==='rect')return rect(s);if(type==='para')return para(s);if(type==='semi')return semi(s);if(type==='circle')return circlePoly(s);return diamond(s)}
var puzzles=[[],[],[]];
var levelCfg=[{scale:1.04,snap:.125,targetAlpha:.38},{scale:.90,snap:.112,targetAlpha:.30},{scale:.78,snap:.098,targetAlpha:.24}];
function countDoneForLevel(lv){var i,c=0;for(i=0;i<puzzles[lv].length;i++)if(G('app360:a1-tangram:done:'+lv+':'+i,'0')==='1')c++;return c}
function findFirstIncomplete(lv){var i;for(i=0;i<puzzles[lv].length;i++)if(G('app360:a1-tangram:done:'+lv+':'+i,'0')!=='1')return i;return 0}
function loadPrefs(){level=parseInt(G('app360:a1-tangram:level','0'),10)||0;level=n(level,0,2);puzzleIndex=parseInt(G('app360:a1-tangram:puzzle','0'),10)||0;if(puzzleIndex<0||puzzleIndex>=puzzles[level].length)puzzleIndex=0;soundEnabled=G('app360:a1-tangram:sound','1')!=='0';userName=G('app360:a1-tangram:name',G('pk_user_name','نور'))||'نور';userGender=G('app360:a1-tangram:gender',G('pk_user_gender','girl'))==='boy'?'boy':'girl';audioMode=G('app360:a1-tangram:audio-mode','auto');if(audioMode!=='recorded'&&audioMode!=='tts')audioMode='auto';settings.snapFactor=(parseInt(G('app360:a1-tangram:snapFactor','65'),10)||65)/100;settings.pickupFactor=(parseInt(G('app360:a1-tangram:pickupFactor','95'),10)||95)/100;d.getElementById('nameInput').value=userName;d.getElementById('genderSelect').value=userGender;d.getElementById('audioMode').value=audioMode;d.getElementById('snapRange').value=Math.round(settings.snapFactor*100);d.getElementById('pickupRange').value=Math.round(settings.pickupFactor*100);d.getElementById('snapValue').innerHTML=Math.round(settings.snapFactor*100)+'%';d.getElementById('pickupValue').innerHTML=Math.round(settings.pickupFactor*100)+'%';updateSoundBtn()}
function savePrefs(){S('app360:a1-tangram:level',level);S('app360:a1-tangram:puzzle',puzzleIndex)}
function saveSettings(){S('app360:a1-tangram:snapFactor',Math.round(settings.snapFactor*100));S('app360:a1-tangram:pickupFactor',Math.round(settings.pickupFactor*100))}
function updateSoundBtn(){d.getElementById('soundBtn').innerHTML=soundEnabled?'🔊':'🔇'}
function size(){var r=wrap.getBoundingClientRect();DPR=w.devicePixelRatio||1;if(DPR>2)DPR=2;W=Math.max(1,r.width);H=Math.max(1,r.height);canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);fx.width=Math.round(W*DPR);fx.height=Math.round(H*DPR);canvas.style.width=W+'px';canvas.style.height=H+'px';fx.style.width=W+'px';fx.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0);fctx.setTransform(DPR,0,0,DPR,0,0);computeZones();rebuildPieces();draw()}
function computeZones(){var pad=Math.max(10,Math.round(Math.min(W,H)*.022)),split;if(W/H>1.12){zones.mode='side';split=Math.round(W*.72);zones.target={x:pad,y:pad,w:split-pad*1.5,h:H-pad*2};zones.tray={x:split+pad*.5,y:pad,w:W-split-pad*1.5,h:H-pad*2}}else{zones.mode='stack';split=Math.round(H*.62);zones.target={x:pad,y:pad,w:W-pad*2,h:split-pad*1.2};zones.tray={x:pad,y:split+pad*.2,w:W-pad*2,h:H-split-pad*1.2}}zones.targetInner={x:zones.target.x+14,y:zones.target.y+42,w:zones.target.w-28,h:zones.target.h-56};zones.trayInner={x:zones.tray.x+14,y:zones.tray.y+42,w:zones.tray.w-28,h:zones.tray.h-56}}
function currentPuzzle(){return puzzles[level][puzzleIndex]}
function targetPieceScale(){return n(Math.min(zones.targetInner.w,zones.targetInner.h)*.18,34,96)*levelCfg[level].scale}
function trayPieceScale(slotW,slotH){return n(Math.min(slotW,slotH)*.52,28,78)}
function rebuildPieces(){var raw=currentPuzzle().pieces,old={},i,a,o,s=targetPieceScale();for(i=0;i<pieces.length;i++)old[pieces[i].id]=pieces[i];pieces=[];for(i=0;i<raw.length;i++){a=raw[i];o=old['p'+i];pieces.push({id:'p'+i,type:a[0],tx:zones.targetInner.x+a[1]*zones.targetInner.w,ty:zones.targetInner.y+a[2]*zones.targetInner.h,rot:a[3]||0,size:s,color:typePalette[a[0]]||palette[i%palette.length],placed:o?o.placed:false,state:o?(o.placed?'placed':(o.state==='drag'?'tray':o.state)):'tray',x:o?o.x:0,y:o?o.y:0,magnet:false})}for(i=0;i<pieces.length;i++)if(pieces[i].placed){pieces[i].state='placed';pieces[i].x=pieces[i].tx;pieces[i].y=pieces[i].ty}else if(pieces[i].state!=='drag'){pieces[i].state='tray'}buildTrayStacks();updateStatus()}
function buildTrayStacks(){var map={},order=[],i,p,k,cols,rows,rect=zones.trayInner,slotW,slotH,r,c,idx,group;trayStacks=[];for(i=0;i<pieces.length;i++){p=pieces[i];if(p.state!=='tray')continue;k=p.type;if(!map[k]){map[k]={key:k,type:k,count:0,members:[]};order.push(k)}map[k].count++;map[k].members.push(p.id)}if(!order.length)return;if(zones.mode==='side'){cols=rect.w<175?1:2}else cols=order.length<=4?order.length:(order.length<=8?4:5);if(cols<1)cols=1;rows=Math.ceil(order.length/cols);slotW=rect.w/cols;slotH=rect.h/rows;for(idx=0;idx<order.length;idx++){c=idx%cols;r=Math.floor(idx/cols);group=map[order[idx]];group.x=rect.x+slotW*(c+.5);group.y=rect.y+slotH*(r+.5);group.size=trayPieceScale(slotW,slotH);trayStacks.push(group)}}
function buildDots(){var total=puzzles[level].length,i,h='',doneCount=countDoneForLevel(level),bars=Math.min(total,14),filled=Math.round((doneCount/Math.max(1,total))*bars),current=Math.min(bars-1,Math.floor((puzzleIndex/Math.max(1,total))*bars));for(i=0;i<bars;i++)h+='<i class="dot'+(i===current?' on':'')+(i<filled?' done':'')+'"></i>';progressDots.innerHTML=h}
function updateLevelButtons(){var bs=d.getElementsByClassName('levelBtn'),i,b,done,total;for(i=0;i<bs.length;i++){b=bs[i];done=countDoneForLevel(i);total=puzzles[i].length;b.className='levelBtn'+(parseInt(b.getAttribute('data-level'),10)===level?' on':'');if(b.getElementsByTagName('small')[0])b.getElementsByTagName('small')[0].innerHTML=done+' / '+total}}
function refresh(resetAll){if(resetAll)pieces=[];levelLabel.innerHTML='المستوى '+(level+1)+' • '+(puzzleIndex+1)+' / '+puzzles[level].length;puzzleTitle.innerHTML=currentPuzzle().name;updateLevelButtons();buildDots();rebuildPieces();won=false;winCard.style.display='none';showMsg('اسحب من الأدوات إلى مكان الظل','',0);draw()}
function setLevel(v){if(v<0||v>=puzzles.length)return;level=v;if(puzzleIndex>=puzzles[level].length)puzzleIndex=0;savePrefs();refresh(true)}
function setPuzzle(idx){if(idx<0||idx>=puzzles[level].length)return;puzzleIndex=idx;hints=1;savePrefs();refresh(true)}
function resetPuzzle(){var i;won=false;drag=null;for(i=0;i<pieces.length;i++){pieces[i].placed=false;pieces[i].state='tray';pieces[i].magnet=false}winCard.style.display='none';hints=1;buildTrayStacks();updateStatus();showMsg('جرب مرة أخرى بطريقتك','',1100);draw()}
function nextPuzzle(){puzzleIndex=(puzzleIndex+1)%puzzles[level].length;hints=1;savePrefs();refresh(true)}
function pathPoly(c,p,sizeOverride){var poly=shape(p.type,sizeOverride||p.size),i;c.beginPath();for(i=0;i<poly.length;i++){if(i===0)c.moveTo(poly[i][0],poly[i][1]);else c.lineTo(poly[i][0],poly[i][1])}c.closePath()}
function transform(c,p,x,y){c.translate(x,y);c.rotate(p.rot||0)}
function drawPiece(c,p,x,y,fill,alpha,outline,sizeOverride){c.save();c.globalAlpha=typeof alpha==='number'?alpha:1;transform(c,p,x,y);pathPoly(c,p,sizeOverride);if(fill){c.fillStyle=fill;c.fill()}if(outline){c.lineWidth=outline;c.strokeStyle='rgba(75,43,18,.58)';c.stroke()}c.restore()}
function roundRect(c,x,y,w0,h0,r){var rr=Math.min(r,w0*.5,h0*.5);c.beginPath();c.moveTo(x+rr,y);c.lineTo(x+w0-rr,y);c.quadraticCurveTo(x+w0,y,x+w0,y+rr);c.lineTo(x+w0,y+h0-rr);c.quadraticCurveTo(x+w0,y+h0,x+w0-rr,y+h0);c.lineTo(x+rr,y+h0);c.quadraticCurveTo(x,y+h0,x,y+h0-rr);c.lineTo(x,y+rr);c.quadraticCurveTo(x,y,x+rr,y);c.closePath()}
function drawWood(){var i;ctx.save();ctx.fillStyle='#ecd2a7';ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(255,255,255,.07)';for(i=0;i<10;i++)ctx.fillRect(0,(i+1)*H/11,W,1);ctx.restore()}
function drawPanel(rect,title,icon){ctx.save();ctx.fillStyle='rgba(255,248,233,.88)';roundRect(ctx,rect.x,rect.y,rect.w,rect.h,22);ctx.fill();ctx.lineWidth=2;ctx.strokeStyle='rgba(122,74,34,.24)';ctx.stroke();ctx.fillStyle='#74471f';ctx.font='bold 17px Tahoma';ctx.textAlign='center';ctx.fillText((icon?icon+' ':'')+title,rect.x+rect.w/2,rect.y+26);ctx.restore()}
function drawWorkspace(){drawPanel(zones.target,'الشكل المطلوب','◌');drawPanel(zones.tray,'الأدوات المتاحة','▣');if(zones.mode==='side'){ctx.save();ctx.strokeStyle='rgba(122,74,34,.14)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(zones.tray.x-8,20);ctx.lineTo(zones.tray.x-8,H-20);ctx.stroke();ctx.restore()}else{ctx.save();ctx.strokeStyle='rgba(122,74,34,.14)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(20,zones.tray.y-8);ctx.lineTo(W-20,zones.tray.y-8);ctx.stroke();ctx.restore()}}
function drawGuidePiece(p,alpha){drawPiece(ctx,p,p.tx,p.ty,'#9a805f',alpha,2.1)}
function drawTrayStack(g){var rep={type:g.type,size:g.size,rot:0},i,layers=Math.min(g.count,3);for(i=layers-1;i>=0;i--)drawPiece(ctx,rep,g.x-i*4,g.y-i*4,'#f6efd9',1,1.6,g.size);drawPiece(ctx,rep,g.x,g.y,typePalette[g.type]||palette[0],1,2.2,g.size);if(g.count>1){ctx.save();ctx.fillStyle='#e85a34';ctx.beginPath();ctx.arc(g.x+g.size*.42,g.y-g.size*.42,Math.max(12,g.size*.20),0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold '+Math.round(Math.max(12,g.size*.22))+'px Tahoma';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(g.count),g.x+g.size*.42,g.y-g.size*.42+1);ctx.restore()}}
function draw(){var i,p,cfg=levelCfg[level];ctx.clearRect(0,0,W,H);drawWood();drawWorkspace();for(i=0;i<pieces.length;i++){p=pieces[i];if(p.state!=='placed'){drawGuidePiece(p,hints===2?Math.max(cfg.targetAlpha,.52):cfg.targetAlpha);if(drag&&drag.p===p||p.magnet){ctx.save();ctx.strokeStyle='rgba(255,255,255,.95)';ctx.lineWidth=4;ctx.beginPath();ctx.arc(p.tx,p.ty,p.size*.72,0,Math.PI*2);ctx.stroke();ctx.restore()}}}for(i=0;i<pieces.length;i++){p=pieces[i];if(p.state==='placed')drawPiece(ctx,p,p.x,p.y,p.color,1,2.2)}for(i=0;i<trayStacks.length;i++)drawTrayStack(trayStacks[i]);if(drag&&drag.p){p=drag.p;ctx.save();ctx.shadowColor='rgba(0,0,0,.28)';ctx.shadowBlur=12;ctx.shadowOffsetY=5;drawPiece(ctx,p,p.x,p.y,p.color,.98,2.5);ctx.restore()}}
function screenPos(clientX,clientY){var r=canvas.getBoundingClientRect();return{x:(clientX-r.left)*(W/r.width),y:(clientY-r.top)*(H/r.height)}}
function localPoint(pt,p){return w.APP360_PIECES.localPoint(pt,p)}
function pointInPoly(pt,poly){return w.APP360_PIECES.pointInPoly(pt,poly)}
function hitStack(pt,stack){var q={x:pt.x-stack.x,y:pt.y-stack.y};if(pointInPoly(q,shape(stack.type,stack.size*settings.pickupFactor*1.02)))return true;return Math.abs(q.x)<stack.size*.70*settings.pickupFactor&&Math.abs(q.y)<stack.size*.70*settings.pickupFactor}
function findTrayStack(pt){var i;for(i=trayStacks.length-1;i>=0;i--)if(hitStack(pt,trayStacks[i]))return trayStacks[i];return null}
function findPieceById(id){var i;for(i=0;i<pieces.length;i++)if(pieces[i].id===id)return pieces[i];return null}
function snapRadius(){var diag=Math.sqrt(zones.targetInner.w*zones.targetInner.w+zones.targetInner.h*zones.targetInner.h);return diag*levelCfg[level].snap*settings.snapFactor}
function nearestCompatibleTarget(p){return w.APP360_PIECES.nearestCompatible(p,pieces)}
function swapTargets(a,b){if(!a||!b||a===b)return;var tx=a.tx,ty=a.ty,rot=a.rot;a.tx=b.tx;a.ty=b.ty;a.rot=b.rot;b.tx=tx;b.ty=ty;b.rot=rot}
function beginDrag(pt){var stack,p;if(won)return;unlockAudio();stack=findTrayStack(pt);if(!stack)return;p=findPieceById(stack.members[0]);if(!p)return;p.state='drag';p.placed=false;p.magnet=false;p.x=pt.x;p.y=pt.y;drag={p:p,dx:0,dy:0};buildTrayStacks();if(d.body.className.indexOf('grabCursor')<0)d.body.className+=' grabCursor';draw()}
function placeNow(p,target){if(target&&target!==p)swapTargets(p,target);p.x=p.tx;p.y=p.ty;p.placed=true;p.state='placed';p.magnet=false;drag=null;d.body.className=d.body.className.replace(/\s*grabCursor/g,'');buildTrayStacks();softSuccess();showMsg('ممتاز! ثبتت القطعة','good',750);updateStatus();draw();if(allPlaced())stageWin()}
function moveDrag(pt){if(!drag)return;var p=drag.p,s=snapRadius(),near;p.x=n(pt.x-drag.dx,16,W-16);p.y=n(pt.y-drag.dy,16,H-16);near=nearestCompatibleTarget(p);p.magnet=!!(near&&near.d<=s);if(p.magnet){placeNow(p,near.p);return}draw()}
function endDrag(){if(!drag)return;var p=drag.p,s=snapRadius(),near=nearestCompatibleTarget(p);if(near&&near.d<=s*1.05){placeNow(p,near.p);return}p.state='tray';p.placed=false;p.magnet=false;drag=null;d.body.className=d.body.className.replace(/\s*grabCursor/g,'');buildTrayStacks();softReturn();showMsg('اقترب أكثر من مكان القطعة','soft',800);updateStatus();draw()}
function allPlaced(){var i;if(!pieces.length)return false;for(i=0;i<pieces.length;i++)if(!pieces[i].placed)return false;return true}
function updateStatus(){var i,c=0;for(i=0;i<pieces.length;i++)if(pieces[i].placed)c++;pieceStatus.innerHTML='مكتمل '+c+' / '+pieces.length+' • باقي '+(pieces.length-c)}
function touchById(list,id){var i;for(i=0;i<(list?list.length:0);i++)if(list[i].identifier===id)return list[i];return null}
var touchId=null;
function renderLevelMap(){var grid=d.getElementById('levelMapGrid'),title=d.getElementById('levelMapTitle'),summary=d.getElementById('levelMapSummary'),html='',i,done,total=puzzles[level].length,status,cls;done=countDoneForLevel(level);title.innerHTML='مراحل المستوى '+(level+1);summary.innerHTML='اكتملت '+done+' من أصل '+total+' مرحلة • اختر أي مرحلة للمتابعة';for(i=0;i<total;i++){status=G('app360:a1-tangram:done:'+level+':'+i,'0')==='1'?'مكتملة':(i===puzzleIndex?'جارية':'متبقية');cls=status==='مكتملة'?'done':(i===puzzleIndex?'current':'remaining');html+='<button type="button" class="stageCard '+cls+'" data-stage="'+i+'"><b>المرحلة '+(i+1)+'</b><span>'+esc(puzzles[level][i].name)+'</span><small>'+status+'</small></button>'}grid.innerHTML=html}
