'use strict';
canvas.addEventListener('touchstart',function(e){if(!e.touches||!e.touches.length)return;touchId=e.touches[0].identifier;var t=e.touches[0];beginDrag(screenPos(t.clientX,t.clientY));if(drag)e.preventDefault()},false);
canvas.addEventListener('touchmove',function(e){if(!drag)return;var t=touchById(e.touches,touchId)||e.touches[0];if(t)moveDrag(screenPos(t.clientX,t.clientY));e.preventDefault()},false);
canvas.addEventListener('touchend',function(e){if(!drag)return;endDrag();touchId=null;e.preventDefault()},false);
canvas.addEventListener('touchcancel',function(e){if(drag)endDrag();touchId=null;e.preventDefault()},false);
canvas.addEventListener('mousedown',function(e){beginDrag(screenPos(e.clientX,e.clientY));if(drag)e.preventDefault()},false);
w.addEventListener('mousemove',function(e){if(drag)moveDrag(screenPos(e.clientX,e.clientY))},false);
w.addEventListener('mouseup',function(){if(drag)endDrag()},false);

function tone(freq,dur,vol){if(!soundEnabled)return;try{var AC=w.AudioContext||w.webkitAudioContext;if(!AC)return;audioCtx=audioCtx||new AC();if(audioCtx.state==='suspended'&&audioCtx.resume)audioCtx.resume();var o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=freq;g.gain.value=vol||.025;o.connect(g);g.connect(audioCtx.destination);o.start(0);setTimeout(function(){try{o.stop(0)}catch(e){}},dur||90)}catch(e){}}
function softSuccess(){tone(520,65,.018);setTimeout(function(){tone(680,65,.016)},70)}
function softReturn(){tone(260,65,.011)}
function victoryTone(){tone(523,110,.025);setTimeout(function(){tone(659,110,.025)},125);setTimeout(function(){tone(784,170,.025)},250)}
function speakTts(text){if(!soundEnabled)return false;try{if(!w.speechSynthesis||!w.SpeechSynthesisUtterance)return false;w.speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(text);u.lang='ar-SA';u.rate=.84;u.pitch=1.04;w.speechSynthesis.speak(u);return true}catch(e){return false}}
function normalize(s){return String(s||'').toLowerCase().replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[ًٌٍَُِّْـ\s]/g,'')}
function fetchRegistry(){try{var x=new XMLHttpRequest();x.open('GET',SHARED+'audio/registry.json?v=1',true);x.onreadystatechange=function(){if(x.readyState!==4)return;if(x.status>=200&&x.status<300){try{registry=JSON.parse(x.responseText)}catch(e){registry=null}}};x.send(null)}catch(e){}}
function findUser(){if(!registry||!registry.users)return null;var k,target=normalize(userName),u,als,i;for(k in registry.users)if(registry.users.hasOwnProperty(k)){u=registry.users[k];if(normalize(k)===target)return u;als=u.aliases||[];for(i=0;i<als.length;i++)if(normalize(als[i])===target)return u}return null}
function recordedCheer(done){var u=findUser(),clips=[],i,c;if(!u||!u.clips){done(false);return}for(i=0;i<u.clips.length;i++)if(u.clips[i].kind==='cheer')clips.push(u.clips[i]);if(!clips.length){done(false);return}i=Math.floor(Math.random()*clips.length);if(clips.length>1&&i===lastCheer)i=(i+1)%clips.length;lastCheer=i;c=clips[i];var src=c.files&&c.files.mp3?c.files.mp3:c.file;if(!src){done(false);return}try{var a=new Audio(SHARED+src);a.volume=1;var finished=false;var timer=setTimeout(function(){if(!finished){finished=true;done(false)}},1700);a.onplaying=function(){if(!finished){finished=true;clearTimeout(timer);done(true)}};a.onerror=function(){if(!finished){finished=true;clearTimeout(timer);done(false)}};var pr=a.play();if(pr&&pr.catch)pr.catch(function(){if(!finished){finished=true;clearTimeout(timer);done(false)}})}catch(e){done(false)}}
function isLegacy(){var u=navigator.userAgent||'',m=u.match(/Android\s+([0-9.]+)/i),av=(m?(parseFloat(m[1])||0):0),c=u.match(/(?:Chrome|CriOS)\/([0-9]+)/i),cv=(c?(parseInt(c[1],10)||0):0);return !!((av&&av<5)||(cv&&cv<50)||/Android 4\.|Version\/4\.|BigTAB|DMTAB/i.test(u))}
function pcmPackFor(c){var packs=w.Audio360PCMPacks||{};if(c&&c.pcmPack&&packs[c.pcmPack])return packs[c.pcmPack];return w.Audio360PCM||null}
function playPcmBuffer(pack,key,done){var b64=pack&&pack.clips&&pack.clips[key],raw,buf,data,src,i,rate;if(!b64||!w.atob){done(false);return}try{var AC=w.AudioContext||w.webkitAudioContext;if(!AC){done(false);return}audioCtx=audioCtx||new AC();if(audioCtx.state==='suspended'&&audioCtx.resume)audioCtx.resume();raw=atob(b64);rate=parseInt(pack.rate,10)||16000;buf=audioCtx.createBuffer(1,raw.length,rate);data=buf.getChannelData(0);for(i=0;i<raw.length;i++)data[i]=(raw.charCodeAt(i)-128)/128;src=audioCtx.createBufferSource();src.buffer=buf;src.connect(audioCtx.destination);src.onended=function(){done(true)};if(src.start)src.start(0);else if(src.noteOn)src.noteOn(0)}catch(e){done(false)}}
function embeddedCheer(done){var u=findUser(),clips=[],i,c,pack,key,script;if(!u||!u.clips){done(false);return}for(i=0;i<u.clips.length;i++)if(u.clips[i].kind==='cheer')clips.push(u.clips[i]);if(!clips.length){done(false);return}c=clips[Math.floor(Math.random()*clips.length)];key=c.pcmKey||c.id;pack=pcmPackFor(c);if(pack&&pack.clips&&pack.clips[key]){playPcmBuffer(pack,key,done);return}script=c.pcmScript;if(!script){try{var mono=d.createElement('script');mono.type='text/javascript';mono.src=SHARED+'audio-pcm-v18.js?v=1';mono.onload=function(){pack=pcmPackFor(c);if(pack&&pack.clips&&pack.clips[key])playPcmBuffer(pack,key,done);else done(false)};mono.onerror=function(){done(false)};(d.getElementsByTagName('head')[0]||d.body).appendChild(mono)}catch(e0){done(false)}return}try{var sc=d.createElement('script');sc.type='text/javascript';sc.src=SHARED+script+'?v=1';sc.onload=function(){pack=pcmPackFor(c);if(pack&&pack.clips&&pack.clips[key])playPcmBuffer(pack,key,done);else done(false)};sc.onerror=function(){done(false)};(d.getElementsByTagName('head')[0]||d.body).appendChild(sc)}catch(e){done(false)}}
function successCheer(){if(!soundEnabled)return;var text='أحسنت يا '+userName;if(audioMode==='tts'){if(!speakTts(text))victoryTone();return}if(isLegacy()){embeddedCheer(function(ok){if(ok)return;recordedCheer(function(ok2){if(ok2)return;if(audioMode==='recorded'){victoryTone();return}if(!speakTts(text))victoryTone()})});return}recordedCheer(function(ok){if(ok)return;embeddedCheer(function(ok2){if(ok2)return;if(audioMode==='recorded'){victoryTone();return}if(!speakTts(text))victoryTone()})})}
