/* Own application model. ES5, no DOM/storage dependencies; shared pencil commands only. */
(function(root,factory){if(typeof module==='object'&&module.exports){module.exports=factory();}else{root.MAKER_MODEL=factory();}}(this,function(){
'use strict';
var IDS=['book','house','track','box','bridge','drawing'],STEPS=['plan','design1','test1','design2','test2','review'],KEYS={book:['base','back','lip'],house:['width','height','roof'],track:['slope','rail','target'],box:['divider','space','edge'],bridge:['fold','span','support'],drawing:['window','corner','opening']};
function copy(x){return JSON.parse(JSON.stringify(x));}function text(x,n){return typeof x==='string'?x.slice(0,n||600):'';}function has(a,v){return a.indexOf(v)>=0;}
function defaults(id){var d={},k=KEYS[id];for(var i=0;i<k.length;i++){d[k[i]]=1;}return d;}
function conditionCount(d){return d.readiness_track==='extend'?2:1;}
function create(id,profile,track,mode,now){if(!has(IDS,id))throw Error('project');return {schema_version:1,app_id:'a4-maker-solutions',profile_ref:profile,session_id:'maker-'+(now||Date.now())+'-'+Math.random().toString(36).slice(2,8),problem_id:id,current_task_id:id,readiness_track:track||'entry',mode:mode||'screen',state:'ready',step:'plan',user_need:'',design_constraints:[],materials:[],assistance_level:'together',design:defaults(id),drawing:[],prototype_versions:[],test_protocol:null,test_notes:[],change_reason:'',attempt_history:[],reflection:'',coach_note:'',other_user_note:'',artifact:null,updated:now||Date.now()};}
function changed(a,b){var c=[];for(var k in a){if(a.hasOwnProperty(k)&&a[k]!==b[k])c.push(k);}return c;}
function simulate(id,d,track){var c=[],rules=[];
switch(id){case'book':c=[d.base>=1&&d.back>=1&&d.lip>=1,d.lip<2];rules=['base ≥ 1, back ≥ 1, lip ≥ 1','lip < 2'];break;
case'house':c=[d.width>=1&&d.height>=1,d.roof>=1];rules=['width ≥ 1, height ≥ 1','roof ≥ 1'];break;
case'track':c=[d.target===d.slope,d.rail>=d.slope];rules=['target = slope','rail ≥ slope'];break;
case'box':c=[d.divider>=1&&d.edge>=1,d.space>=1];rules=['divider ≥ 1, edge ≥ 1','space ≥ 1'];break;
case'bridge':c=[d.fold>=1&&d.support>=1,d.span>=1];rules=['fold ≥ 1, support ≥ 1','span ≥ 1'];break;
case'drawing':c=[d.window>=1&&d.corner>=1,d.opening>=1];rules=['window ≥ 1, corner ≥ 1','opening ≥ 1'];break;
default:throw Error('project');}
return {source:'screen-rule-model',conditions:c.slice(0,track==='extend'?2:1),rules:rules.slice(0,track==='extend'?2:1),observation:!c[0]?0:(c[1]?2:1),passed:c[0]&&(track!=='extend'||c[1])};}
function record(d,what){d.updated=Date.now();d.attempt_history.push({event:what,step:d.step,time:d.updated,assistance:d.assistance_level});d.attempt_history=d.attempt_history.slice(-40);}
function start(d,p){if(d.step!=='plan')throw Error('stage');if(!d.user_need.trim()||!d.materials.length)throw Error('plan');d.test_protocol={project_id:d.problem_id,readiness_track:d.readiness_track,instruction:copy(p.protocol),conditions:[copy(p.condition)],mode:d.mode};if(conditionCount(d)===2)d.test_protocol.conditions.push(copy(p.extended));d.design_constraints=copy(d.test_protocol.conditions);d.state='in_progress';d.step='design1';record(d,'start');}
function freeze(d){if(d.step!=='design1'&&d.step!=='design2')throw Error('stage');var second=d.step==='design2';if(second&&changed(d.prototype_versions[0].design,d.design).length!==1)throw Error('one-change');if(second&&!d.change_reason.trim())throw Error('reason');var v={version:second?2:1,design:copy(d.design),drawing:copy(d.drawing),time:Date.now()};d.prototype_versions[second?1:0]=v;d.step=second?'test2':'test1';record(d,'prototype');}
function test(d,observation,note,built){if(d.step!=='test1'&&d.step!=='test2')throw Error('stage');var second=d.step==='test2',v=d.prototype_versions[second?1:0],result;if(d.mode==='real'){if(!built||!has([0,1,2,3],observation))throw Error('real-observation');result={source:'physical-observation',observation:observation,conditions:[],passed:null};}else{result=simulate(d.problem_id,v.design,d.readiness_track);}if(!text(note).trim())throw Error('observation');if(!second&&d.readiness_track==='extend'&&!d.other_user_note.trim())throw Error('other-user');d.test_notes[second?1:0]={prototype_version:second?2:1,result:result,note:text(note),protocol:copy(d.test_protocol),time:Date.now()};if(second){d.step='review';d.state='review';}else{d.step='design2';d.design=copy(v.design);d.drawing=copy(v.drawing);}record(d,'test');return result;}
function finish(d){if(d.step!=='review'||d.prototype_versions.length!==2||d.test_notes.length!==2||changed(d.prototype_versions[0].design,d.prototype_versions[1].design).length!==1||!d.user_need.trim()||!d.reflection.trim()||!d.change_reason.trim())throw Error('incomplete');d.artifact={prototype_versions:copy(d.prototype_versions),comparison:copy(d.test_notes),next_step:d.reflection};d.state='saved';record(d,'save');return copy(d);}
function validate(x,profile){if(!x||x.schema_version!==1||x.app_id!=='a4-maker-solutions'||!has(IDS,x.problem_id)||!has(STEPS,x.step)||!has(['entry','practice','extend'],x.readiness_track)||!has(['screen','real'],x.mode))throw Error('invalid');if(x.profile_ref!==profile)throw Error('profile');var allowed=['schema_version','app_id','profile_ref','session_id','problem_id','current_task_id','readiness_track','mode','state','step','user_need','design_constraints','materials','assistance_level','design','drawing','prototype_versions','test_protocol','test_notes','change_reason','attempt_history','reflection','coach_note','other_user_note','artifact','updated','screen_test_run','pending_test'];for(var field in x)if(x.hasOwnProperty(field)&&allowed.indexOf(field)<0)throw Error('unknown-field');
if(!has(['ready','in_progress','paused','needs_help','review','saved'],x.state)||typeof x.session_id!=='string'||x.session_id.length>100)throw Error('state');
function design(v){var keys=KEYS[x.problem_id];if(!v||Object.keys(v).length!==keys.length)throw Error('design');for(var i=0;i<keys.length;i++)if(!has([0,1,2],v[keys[i]]))throw Error('design');}
function drawing(v){if(!Array.isArray(v)||v.length>300)throw Error('drawing');for(var i=0;i<v.length;i++){var c=v[i];if(c.type==='stamp'){if(!has(['house','star','heart','sun','book','flower'],c.kind)||typeof c.color!=='string'||!/^#[0-9a-f]{6}$/i.test(c.color)||!(c.x>=0&&c.x<=1&&c.y>=0&&c.y<=1&&c.size>0&&c.size<=1))throw Error('stamp');}else if(c.type==='stroke'){if(!Array.isArray(c.points)||c.points.length>1000||typeof c.color!=='string'||!/^#[0-9a-f]{6}$/i.test(c.color)||!(c.width>0&&c.width<30))throw Error('stroke');for(var j=0;j<c.points.length;j++){var p=c.points[j];if(!(p.x>=0&&p.x<=1&&p.y>=0&&p.y<=1))throw Error('point');}}else throw Error('command');}}
design(x.design);drawing(x.drawing);if(!Array.isArray(x.prototype_versions)||x.prototype_versions.length>2||!Array.isArray(x.test_notes)||x.test_notes.length>2||!Array.isArray(x.materials)||x.materials.length>4||!Array.isArray(x.attempt_history)||x.attempt_history.length>40)throw Error('arrays');
function pair(v){if(!v||typeof v.ar!=='string'||typeof v.en!=='string'||v.ar.length>600||v.en.length>600)throw Error('language');}for(var mi=0;mi<x.materials.length;mi++)pair(x.materials[mi]);if(!has(['together','hint','independent'],x.assistance_level))throw Error('assistance');if(x.pending_test&&((x.pending_test.note&&typeof x.pending_test.note!=='string')||(x.pending_test.note&&x.pending_test.note.length>600)||(x.pending_test.observation!=null&&!has([0,1,2,3],x.pending_test.observation))||(x.pending_test.built!=null&&typeof x.pending_test.built!=='boolean')))throw Error('pending-test');for(var i=0;i<x.prototype_versions.length;i++){var v=x.prototype_versions[i];if(v.version!==i+1)throw Error('version');design(v.design);drawing(v.drawing);}
for(i=0;i<x.test_notes.length;i++){var t=x.test_notes[i];if(!t.result||!has(['screen-rule-model','physical-observation'],t.result.source)||!has([0,1,2,3],t.result.observation)||typeof t.note!=='string'||t.note.length>600||!t.note.trim()||JSON.stringify(t.protocol)!==JSON.stringify(x.test_protocol))throw Error('notes');if(x.mode==='real'&&(t.result.source!=='physical-observation'||t.result.passed!==null||!Array.isArray(t.result.conditions)||t.result.conditions.length!==0))throw Error('physical-test');if(x.mode==='screen'&&JSON.stringify(t.result)!==JSON.stringify(simulate(x.problem_id,x.prototype_versions[i].design,x.readiness_track)))throw Error('simulation');}
if(x.step!=='plan'){if(!x.test_protocol||x.test_protocol.project_id!==x.problem_id||x.test_protocol.mode!==x.mode||x.test_protocol.readiness_track!==x.readiness_track||!Array.isArray(x.test_protocol.conditions)||x.test_protocol.conditions.length!==conditionCount(x)||!x.user_need||!x.materials.length)throw Error('protocol');pair(x.test_protocol.instruction);for(var ci=0;ci<x.test_protocol.conditions.length;ci++)pair(x.test_protocol.conditions[ci]);if(JSON.stringify(x.design_constraints)!==JSON.stringify(x.test_protocol.conditions))throw Error('constraints');}
var stage=STEPS.indexOf(x.step);if(x.prototype_versions.length<(stage>=4?2:stage>=2?1:0)||x.test_notes.length<(stage>=5?2:stage>=3?1:0))throw Error('incomplete');
if(x.prototype_versions.length===2&&changed(x.prototype_versions[0].design,x.prototype_versions[1].design).length!==1)throw Error('comparison');
for(var k in {user_need:1,change_reason:1,reflection:1,coach_note:1,other_user_note:1})if(typeof x[k]!=='string'||x[k].length>600)throw Error('text');if(x.readiness_track==='extend'&&stage>=3&&!x.other_user_note.trim())throw Error('other-user');if(x.state==='saved'&&(!x.reflection.trim()||!x.change_reason.trim()||stage!==5))throw Error('saved');if(x.state==='saved'&&JSON.stringify(x.artifact)!==JSON.stringify({prototype_versions:x.prototype_versions,comparison:x.test_notes,next_step:x.reflection}))throw Error('artifact');return copy(x);}
function exported(db){var out=copy(db);for(var i=0;i<out.gallery.length;i++)out.gallery[i].coach_note='';if(out.draft)out.draft.coach_note='';return out;}
return {ids:IDS,keys:KEYS,steps:STEPS,copy:copy,create:create,start:start,freeze:freeze,test:test,finish:finish,changed:changed,simulate:simulate,validate:validate,exported:exported,record:record};
}));
