(function(w){'use strict';
function ui(lang){return {t:function(ar,en){return lang==='ar'?ar:en;},txt:function(v){return v[lang]||'';}};}
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function button(action,label,more,cls){return '<button type="button" data-action="'+action+'" class="'+(cls||'')+'" '+(more||'')+'>'+label+'</button>';}
function image(scene,cls){var col=scene.cell%3,row=Math.floor(scene.cell/3);return '<div class="story-crop '+(cls||'')+'" role="img" aria-label="'+esc(scene.title.ar+' / '+scene.title.en)+'"><img alt="" src="'+scene.atlas+'" draggable="false" style="left:-'+(col*100)+'%;top:-'+(row*100)+'%"></div>';}
function library(o){var u=ui(o.lang),C=w.MAKER_STORIES,html='<section class="story-library"><div class="story-intro"><span class="eyebrow">'+u.t('تجارب المشاهد • نسخة تجريبية','Scene experiments • preview')+'</span><h2>'+u.t('أشاهد… أجرّب… وأفسّر','Watch. Try. Explain.')+'</h2><p>'+u.t('اختر تجربة. شاهد الصور مع الشرح، أو انتقل بينها مع المدرب.','Choose an experiment. Watch the pictures with narration, or explore them with a coach.')+'</p></div><div class="story-levels" role="group" aria-label="'+u.t('مستويات التجارب','Experiment levels')+'">';
for(var i=0;i<C.levels.length;i++){var l=C.levels[i];html+=button('story-level','<b>'+u.t('المستوى ','Level ')+l.id+'</b><span>'+esc(u.txt(l.title))+'</span><small>'+l.age+' '+u.t('سنوات تقريبًا','years, approximately')+'</small>','data-index="'+l.id+'" aria-pressed="'+(o.level===l.id)+'"',o.level===l.id?'chosen':'');}
html+='</div><p class="story-level-goal">'+esc(u.txt(C.levels[o.level-1].goal))+' '+u.t('الاستعداد أهم من العمر؛ يمكن للمدرب اختيار أي مستوى.','Readiness matters more than age; coaches can select any level.')+'</p><div class="story-experiment-grid">';
for(i=0;i<C.projects.length;i++){var p=C.projects[i],route=p.routes[String(o.level)],progress=o.progress(p.id,o.level),seen=progress.seen||[],count=0;for(var j=0;j<route.length;j++)if(seen.indexOf(route[j])>=0)count++;html+='<article class="story-experiment">'+image(p.scenes[route[0]])+'<div><h3>'+esc(u.txt(p.title))+'</h3><p>'+route.length+' '+u.t('مشاهد • قبل التجربة وبعدها','scenes • before and after')+'</p><small>'+u.t('زرت ','Visited ')+count+' / '+route.length+' '+u.t('مشاهد','scenes')+'</small>'+button('story-open',u.t('▶ شغّل التجربة','▶ Play experiment'),'data-id="'+p.id+'"','primary')+'</div></article>';}
html+='</div><div class="story-library-links">'+button('legacy-home',u.t('ورشة التصميم • المشروعات السابقة','Design workshop • previous projects'))+(o.draft?button('resume',u.t('أكمل محاولة التصميم المحفوظة','Continue saved design attempt')):'')+'</div></section>';return html;}
function workspace(o){var u=ui(o.lang),p=o.project,route=p.routes[String(o.level)],html='<section class="story-workspace"><div class="story-heading">'+button('back',u.t('← المكتبة','← Library'))+'<h2>'+esc(u.txt(p.title))+'</h2><span class="tag">'+u.t('المستوى ','Level ')+o.level+' · '+w.MAKER_STORIES.levels[o.level-1].age+'</span></div><div class="story-stage"><div id="storyScene"></div><div class="story-caption"><h3 id="storySceneTitle"></h3><p id="storyText"></p><div id="storyVariable" class="story-variable"></div></div><div class="story-play-controls">'+button('story-prev',u.t('◀ السابق','◀ Previous'),'id="storyPrev"')+button('story-play',u.t('▶ تشغيل','▶ Play'),'id="storyPlay"','primary')+button('story-pause',u.t('إيقاف','Pause'),'id="storyPause"')+button('story-next',u.t('التالي ▶','Next ▶'),'id="storyNext"')+'</div><div class="story-progress-row"><span id="storyProgress" role="status" aria-live="polite"></span>'+button('story-mode',u.t('المدرب: تحكم يدوي','Coach: manual control'),'id="storyMode" aria-pressed="false"')+'</div><div class="story-strip" role="group" aria-label="'+u.t('صور مشاهد التجربة','Experiment scene pictures')+'" dir="ltr">';
for(var i=0;i<route.length;i++){var scene=p.scenes[route[i]];html+=button('story-step',image(scene)+'<small>'+esc(u.txt(scene.title))+'</small>','data-index="'+i+'" aria-pressed="false" aria-label="'+esc(u.txt(scene.title))+'"','story-thumb');}
html+='</div><p class="story-tip">'+u.t('اضغط صورة لعرضها وسماعها. التشغيل ينتقل بعد انتهاء الشرح.','Tap a picture to see and hear it. Playback moves on after the narration.')+'</p></div><div class="story-follow-up"><details><summary>'+u.t('قارن نتيجتين','Compare two outcomes')+'</summary><div class="story-comparison">';
var comparisons=route.length>=4?[route[1],route[3]]:[route[0],route[route.length-1]];
for(i=0;i<comparisons.length;i++){scene=p.scenes[comparisons[i]];html+='<figure>'+image(scene)+'<figcaption>'+esc(u.txt(scene.title))+'</figcaption></figure>';}
html+='</div></details><details><summary>'+u.t('ملاحظتي • مع المدرب','My observation • with a coach')+'</summary><label for="storyNote">'+u.t('ما الذي تغير؟ ماذا لاحظت؟','What changed? What did you notice?')+'</label><textarea id="storyNote" maxlength="400">'+esc(o.progress.note||'')+'</textarea>'+button('story-save',u.t('حفظ الملاحظة لهذا الطفل','Save this child’s observation'),'id="storySave"')+'<p id="storySaved" role="status"></p></details><details><summary>'+u.t('تجربة واقعية مع المدرب','Try it with a coach')+'</summary><p>'+esc(u.txt(p.coach))+'</p><p>'+u.t('شاهد كل حالة، ثم غيّر جزءًا واحدًا في محاولتك الواقعية وسجّل ما يحدث فعلًا.','Explore each case, then change one part in your real attempt and record what actually happens.')+'</p></details><p class="story-disclaimer">'+u.t('صور توضيحية مولّدة لحالات محتملة؛ النتيجة الواقعية تعتمد على المواد وطريقة التجربة.','Generated illustrations of possible cases; real results depend on materials and the experiment.')+'</p>'+button('story-restart',u.t('↻ أعد التجربة من البداية','↻ Restart experiment'))+'</div></section>';return html;}
w.MAKER_STORY_VIEW={library:library,workspace:workspace,image:image};
}(window));
