/* Ready-to-play recipes: bounded variety, no learner scoring or remote generation. */
(function(w){'use strict';
var M=w.MARKET_MODEL,P=w.APP360_MARKET_OBJECTS,C=w.MARKET_CONTENT;
var types=[['count','أعدّ وأضع','Count & fill','أضع بطاقات في السلة.','Put picture cards in a basket.','count'],['fill','أكمل الناقص','Fill the gap','أكمل سلة بدأناها.','Complete a basket we started.','fill'],['return','أعيد الزائد','Return extras','أعيد البطاقات الزائدة.','Return the extra cards.','return'],['share','أوزّع بالتساوي','Share fairly','أوزّع على سلال الأصدقاء.','Share between friends’ baskets.','share'],['split','أقسّم بطريقتي','Split my way','أصنع مجموعتين للعدد نفسه.','Make two groups of the same total.','split'],['combine','أضمّ المجموعتين','Join two groups','أنقل المجموعتين إلى سلة واحدة.','Move two groups into one basket.','combine'],['mixed','طلب من صورتين','A two-picture order','أعدّ كل نوع وأجهز الطلب.','Count each kind to make an order.','mixed'],['compare','أيهما أكثر؟','Which has more?','أقارن العدد، ولو اختلف التباعد.','Compare quantity, even with different spacing.','compare'],['pattern','أكمل النمط','Continue a pattern','أختار الصورة التالية في الصف.','Choose the next picture in the row.','pattern'],['measure','أقيس بالبطاقات','Measure with cards','أملأ خطًا بوحدات متساوية.','Fill a line with equal units.','measure']].map(function(a){return{id:a[0],ar:a[1],en:a[2],description_ar:a[3],description_en:a[4],guide:a[5]}});
function integer(n,a,b){return typeof n==='number'&&isFinite(n)&&Math.floor(n)===n&&n>=a&&n<=b}
function market(id){for(var i=0;i<P.markets.length;i++)if(P.markets[i].id===id)return P.markets[i];throw Error('unknown-market')}
function type(id){for(var i=0;i<types.length;i++)if(types[i].id===id)return types[i];throw Error('unknown-exercise')}
function recipe(x){if(!x||typeof x!=='object')throw Error('invalid-recipe');type(x.type);var m=market(x.market),ps=x.products||m.products;if(!Array.isArray(ps)||!ps.length||ps.length>7)throw Error('invalid-pool');var unique=[];ps.forEach(function(p){if(m.products.indexOf(p)<0||unique.indexOf(p)>=0)throw Error('invalid-pool');unique.push(p)});var lo=Number(x.min),hi=Number(x.max),g=Number(x.groups)||2;if(!integer(lo,1,20)||!integer(hi,lo,20)||!integer(g,2,4)||['alternate','double','three'].indexOf(x.pattern||'alternate')<0||['varied','ascending'].indexOf(x.strategy||'varied')<0)throw Error('invalid-range');if((x.type==='pattern'||x.type==='mixed')&&ps.length<(x.pattern==='three'&&x.type==='pattern'?3:2))throw Error('more-pictures');if(['share','combine','split','fill','return','mixed'].indexOf(x.type)>=0&&hi<2)throw Error('small-range');if(x.type==='compare'&&hi>10||x.type==='measure'&&hi>8||x.type==='return'&&hi>19)throw Error('range-limit');if(x.type==='share'){var found=false;for(var n=lo;n<=hi;n++)if(n>=g&&n%g===0)found=true;if(!found)throw Error('no-fair-total')}
return{id:typeof x.id==='string'?x.id.slice(0,90):M.id(),title:typeof x.title==='string'?x.title.slice(0,100):'',type:x.type,market:x.market,products:unique,min:lo,max:hi,groups:g,pattern:x.pattern||'alternate',strategy:x.strategy||'varied',level:integer(x.level,1,4)?x.level:1}}
function defaultRecipe(kind,m,level){var max=[5,8,12,20][level-1],min=['combine','split','fill','return','mixed'].indexOf(kind)>=0?2:1;return recipe({id:'ready-'+m+'-'+kind,type:kind,market:m,min:min,max:kind==='compare'?Math.min(8,max):kind==='measure'?Math.min(8,max):kind==='return'?max-1:max,groups:level>=4?3:2,pattern:level>=3?'double':'alternate',level:level})}
function shape(q){return JSON.stringify([q.exercise,q.product,q.requests||[],q.initial||0,q.total||0,q.left||0,q.right||0,q.groups||0,q.rule||[],q.length||0])}
function make(r,lang,p,n,rand){var info=type(r.type),g=C.guides[lang][info.guide],title=info[lang],q={id:M.id(),language:lang,level:r.level,kind:r.type==='fill'||r.type==='return'||r.type==='mixed'?'count':r.type==='split'?'partition':r.type,exercise:r.type,market:r.market,recipe_ref:r.id,product:p,title:r.title||title,prompt:g.text,hint:g.text,real:C.guides[lang].safety.text,audio:{prompt:g.path,hint:g.path,real:C.guides[lang].safety.path}};
function other(){var xs=r.products.filter(function(x){return x!==p});return xs[Math.floor(rand()*xs.length)]}
if(q.kind==='count'||q.kind==='measure'){q.requests=[{product:p,quantity:n}];q.initial=r.type==='fill'?Math.max(1,n-1-Math.floor(rand()*Math.max(1,n-1))):r.type==='return'?n+1+Math.floor(rand()*Math.min(3,20-n)):0;if(r.type==='mixed'){var left=1+Math.floor(rand()*(n-1));q.requests=[{product:p,quantity:left},{product:other(),quantity:n-left}];}}
else if(q.kind==='share'||q.kind==='partition'||q.kind==='combine'){q.total=n;q.groups=r.type==='share'?r.groups:q.kind==='combine'?3:2;if(q.kind==='combine')q.left=1+Math.floor(rand()*(n-1));}
else if(q.kind==='compare'){q.left=n;q.right=r.min+Math.floor(rand()*(r.max-r.min+1));}
else {q.rule=r.pattern==='double'?[p,p,other()]:r.pattern==='three'?[p,other(),r.products.filter(function(x){return x!==p})[0]]:[p,other()];if(r.pattern==='three'){q.rule[2]=r.products.filter(function(x){return q.rule.indexOf(x)<0})[0]}q.prefix=q.rule.length*2;q.length=q.prefix+q.rule.length;}
q.recipe_spec=M.copy(r);q=M.task(q);q.variant_signature=shape(q);return q}
function generate(kind,m,level,lang,recent,custom,random){var rand=random||Math.random,r=custom?recipe(custom):defaultRecipe(kind,m,level);if(['ar','en'].indexOf(lang)<0)throw Error('unknown-language');var key=r.id+':'+lang,history=(recent||[]).filter(function(a){return a.key===key}).slice(-12),last=history[history.length-1],values=[];for(var n=r.min;n<=r.max;n++)if((r.type!=='share'||n>=r.groups&&n%r.groups===0)&&(['combine','split','fill','return','mixed'].indexOf(r.type)<0||n>=2))values.push(n);if(!values.length)throw Error('no-quantity');var candidates=[];r.products.forEach(function(p){values.forEach(function(n){var q=make(r,lang,p,n,rand),sig=shape(q);candidates.push({task:q,key:key,product:p,quantity:n,signature:sig})})});var fresh=candidates.filter(function(c){return !history.some(function(h){return h.signature===c.signature})&&(!last||(r.products.length===1||last.product!==c.product)&&(values.length===1||last.quantity!==c.quantity))});if(!fresh.length)fresh=candidates.filter(function(c){return !last||c.signature!==last.signature});if(!fresh.length)fresh=candidates;if(r.strategy==='ascending'&&r.type!=='pattern'){var next=last?values.filter(function(n){return n>last.quantity})[0]:values[0];if(next===undefined)next=values[0];var up=fresh.filter(function(c){return c.quantity===next});if(up.length)fresh=up;else fresh=candidates.filter(function(c){return c.quantity===next})}var picked=fresh[Math.min(fresh.length-1,Math.floor(rand()*fresh.length))];return {task:picked.task,record:{key:key,product:picked.product,quantity:picked.quantity,signature:picked.signature},recipe:r}}
function exportRecipes(xs){return{schema_version:1,app_id:'a4-family-market-recipes',recipes:xs.map(recipe)}}
function importRecipes(raw){var x=JSON.parse(raw);if(!x||x.schema_version!==1||x.app_id!=='a4-family-market-recipes'||!Array.isArray(x.recipes)||x.recipes.length>20)throw Error('invalid-recipes');return x.recipes.map(function(a){var r=recipe(a);r.id=M.id();return r})}
w.MARKET_EXERCISES={types:types,type:type,market:market,recipe:recipe,defaultRecipe:defaultRecipe,generate:generate,signature:shape,exportRecipes:exportRecipes,importRecipes:importRecipes};
})(typeof window!=='undefined'?window:globalThis);
