#!/usr/bin/env python3
"""Verify actual local SILMA clips and activate *only* human-reviewed SHA-matched audio.
Run after: python tooling/build-silma-audio.py --root apps/1-4/calm-with-me
 --manifest audio/silma/manifest.json --cache CACHE --model-cache MODEL --generate-only
No runtime inference or network access; uses ffprobe on generated local MP3.
"""
import argparse
import hashlib
import json
import pathlib
import re
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "audio/silma/manifest.json"
INDEX = ROOT / "calm-silma-index-serial-v1.js"
REVIEW = ROOT / "audio/silma/reviewed.json"

def source_ids(kind, next_kind):
    js = (ROOT / "data/content.js").read_text(encoding="utf-8")
    start = js.index("\n  " + kind + ":[")
    end = js.index("\n  " + next_kind + ":[", start + 1)
    return re.findall(r"\bid:'([^']+)'", js[start:end])

def probe(path):
    cmd = ["ffprobe", "-v", "error", "-select_streams", "a:0",
           "-show_entries", "stream=codec_name,sample_rate,channels:format=duration",
           "-of", "json", str(path)]
    try:
        data = json.loads(subprocess.check_output(cmd, stderr=subprocess.STDOUT, timeout=12))
        audio = data["streams"][0]
        duration = float(data["format"]["duration"])
        if audio["codec_name"] != "mp3" or int(audio["channels"]) != 1 or int(audio["sample_rate"]) != 24000:
            return None, "MP3 must be 24 kHz mono"
        if not (0.45 < duration < 45) or path.stat().st_size < 1500:
            return None, "duration/size outside valid range"
        return round(duration, 3), ""
    except (OSError, ValueError, KeyError, IndexError, subprocess.SubprocessError) as exc:
        return None, "ffprobe rejected: " + str(exc)[:140]

def run(write):
    m = json.loads(MANIFEST.read_text(encoding="utf-8"))
    items = m["items"]
    expected = set(source_ids("signals", "feelings")) | set(source_ids("feelings", "helps"))
    ids = [item["item_id"] for item in items]
    assert len(ids) == len(set(ids)) == len(expected) and set(ids) == expected, "source ID mismatch"
    assert len({x["event_id"] for x in items}) == len(items), "duplicate event"
    assert len({x["path"] for x in items}) == len(items), "duplicate path"
    reviewed = {}
    if REVIEW.exists():
        review = json.loads(REVIEW.read_text(encoding="utf-8"))
        reviewed = {entry["event_id"]: entry["sha256"] for entry in review.get("reviewed", [])}
    output = {}
    summary = {"source_choices": len(expected), "authored_texts": len(items), "files_found": 0,
               "valid_mp3": 0, "listened_and_sha_matched": 0, "activated": 0, "problems": []}
    for item in items:
        rel = pathlib.PurePosixPath(item["path"])
        assert not rel.is_absolute() and ".." not in rel.parts
        assert rel.as_posix() == "audio/silma/" + item["kind"] + "/" + item["item_id"] + ".mp3"
        assert item["event_id"] == "calm-with-me:" + item["kind"] + ":" + item["item_id"]
        assert item["engine"] == "silma" and item["language"] == "ar"
        assert re.search(r"[\u064b-\u0652]", item["text"]), "unvowelled: " + item["event_id"]
        target = ROOT / rel
        good = False
        digest = ""
        if target.exists():
            summary["files_found"] += 1
            duration, problem = probe(target)
            if duration is not None:
                summary["valid_mp3"] += 1
                digest = hashlib.sha256(target.read_bytes()).hexdigest()
                good = reviewed.get(item["event_id"]) == digest
                if good: summary["listened_and_sha_matched"] += 1
                else: problem = "requires listening review and matching SHA256"
            if problem: summary["problems"].append({"event_id":item["event_id"],"reason":problem})
        else:
            summary["problems"].append({"event_id":item["event_id"],"reason":"MP3 file missing"})
        output[item["item_id"]] = {"path":rel.as_posix(), "engine":"silma", "verified":good,
                                   "kind":item["kind"], "event_id":item["event_id"]}
        if good: summary["activated"] += 1
    if write:
        source = "/* SHA-reviewed real MP3 only; generated by tools/verify_silma_serial.py. */\n"
        source += "window.APP360_CALM_SILMA_INDEX = " + json.dumps(output,ensure_ascii=False,indent=2) + ";\n"
        tmp = INDEX.with_suffix(".js.tmp")
        tmp.write_text(source,encoding="utf-8")
        tmp.replace(INDEX)
    print(json.dumps(summary,ensure_ascii=False,indent=2))
    return 0

if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--write-index", action="store_true", help="Activate only reviewed and matching MP3 SHA256 files")
    raise SystemExit(run(p.parse_args().write_index))
