const {test}=require('node:test'),assert=require('node:assert/strict'),M=require('../src/model.js');
function complete(track='entry',plan='turns'){let d=M.fresh('child-a',track);M.next(d);d.heard.needA=true;M.next(d);d.heard.needB=true;M.next(d);d.explored={turns:true,together:true};M.select(d,plan);M.next(d);d.agreed_rule='نتبادل اللعب بعد رحلة.';d.consent=[true,true,track==='extend'];M.next(d);d.trial_done=true;M.next(d);d.reflection='worked';return d;}
test('all three tracks and either plan complete the actual trial and review',()=>{for(const track of ['entry','practice','extend'])for(const plan of ['turns','together']){const d=complete(track,plan);assert.equal(M.finish(d).state,'saved');assert.equal(M.validate(M.finish(d),'child-a').selected_plan,plan);}});
test('a request must be represented before advancing',()=>{const d=M.fresh('child-a','entry');M.next(d);assert.throws(()=>M.next(d),/listen/);d.heard.needA=true;M.next(d);assert.throws(()=>M.next(d),/listen/);});
test('higher tracks explore both alternatives',()=>{const d=complete('practice');M.revise(d);d.explored.together=false;assert.throws(()=>M.next(d),/both/);});
test('no agreement is prescribed as a correct answer',()=>{assert.equal(M.finish(complete('entry','turns')).state,M.finish(complete('entry','together')).state);});
test('all participants must consent and a third participant is supported',()=>{const d=complete('extend');d.step='agree';d.participants=3;d.consent[2]=false;assert.throws(()=>M.next(d),/consent/);d.consent[2]=true;M.next(d);assert.equal(d.step,'trial');});
test('real-world trial confirmation is required for review',()=>{const d=complete();d.step='trial';d.trial_done=false;assert.throws(()=>M.next(d),/trial/);assert.throws(()=>M.go(d,'review'),/trial/);});
test('revising preserves the attempt and clears trial and consent',()=>{const d=complete();M.revise(d);assert.equal(d.revisions,1);assert.equal(d.step,'solutions');assert.equal(d.trial_done,false);assert.deepEqual(d.consent,[false,false,false]);assert.throws(()=>M.go(d,'review'),/stage/);});
test('changing a plan invalidates the old agreement',()=>{const d=complete();d.step='solutions';M.select(d,'together');assert.equal(d.agreed_rule,'');assert.equal(d.reached,3);assert.equal(d.trial_done,false);});
test('pause and assistance never erase the attempt',()=>{const d=complete();d.state='paused';M.record(d,'pause');assert.equal(M.validate(d,'child-a').agreed_rule,d.agreed_rule);d.state='needs_help';assert.equal(M.validate(d,'child-a').state,'needs_help');});
test('profiles cannot read each other’s attempts',()=>{assert.throws(()=>M.validate(complete(),'child-b'),/draft/);});
test('export excludes identity, history and private coach notes',()=>{const d=M.finish(complete());d.coach_note='private';const x=M.exported({gallery:[d]});assert.equal(x.agreements[0].profile_ref,undefined);assert.equal(x.agreements[0].coach_note,undefined);assert.equal(x.agreements[0].attempt_history,undefined);});
test('malformed and oversized saves are rejected',()=>{for(const edit of [d=>d.trial_note='x'.repeat(601),d=>d.participants=4,d=>d.selected_plan='force',d=>d.reached=99,d=>d.consent[0]='yes',d=>d.assistance_level='diagnosis']){const d=complete();edit(d);assert.throws(()=>M.validate(d,'child-a'));}});
test('saved artifacts require a performed trial, a rule and a review',()=>{for(const edit of [d=>d.trial_done=false,d=>d.agreed_rule='',d=>d.reflection='',d=>d.heard.needB=false]){const d=M.finish(complete());edit(d);assert.throws(()=>M.validate(d,'child-a'));}});
