const {JSDOM}=require('jsdom'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..');
const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://example.test/apps/4-8/cooperative-play-lab/index.html',runScripts:'outside-only'}),w=dom.window,d=w.document;let lastAudio='',lastPlayer=null;
w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=function(){};w.confirm=()=>true;w.Audio=function(p){lastPlayer=this;lastAudio=p;this.pause=()=>{};this.play=()=>Promise.resolve();};w.APP360_FAMILY_SYNC={getProfileKey:()=> 'integration',getReadingFocusState:()=>({enabled:false,canManage:true})};w.APP360_READ_ALONG={markup:(text)=>text,create:()=>({stop(){},follow(){},refresh(){},setEnabled(){}})};
for(const file of ['content.js','model.js','app.js'])w.eval(fs.readFileSync(path.join(root,'src',file),'utf8'));
function click(sel){let e=d.querySelector(sel);assert(e,'missing '+sel);e.click();}
function check(sel){let e=d.querySelector(sel);assert(e,'missing '+sel);e.checked=true;e.dispatchEvent(new w.Event('change',{bubbles:true}));}
for(const e of w.COOP_CONTENT.experiments){click('[data-action="track"][data-track="'+e.track+'"]');assert.equal(d.querySelectorAll('[data-action="experiment"]').length,5);click('[data-experiment="'+e.id+'"]');click('[data-action="start"]');assert.equal(w.APP360_COOPERATE.state().draft.situation_id,e.id);assert.equal(lastAudio,'audio/ar/'+e.id+'-intro.mp3');click('[data-action="next"]');assert(d.querySelector('.choice-glow [data-field="heard"]'));lastPlayer.onended();assert.equal(lastAudio,'audio/ar/hint-listen.mp3');click('[data-action="next"]');assert.equal(w.APP360_COOPERATE.state().draft.step,'needA');assert(d.querySelector('.choice-glow [data-field="heard"]'));assert.equal(lastAudio,'audio/ar/hint-listen.mp3');check('[data-field="heard"]');click('[data-action="next"]');let requestPlayer=lastPlayer;check('[data-field="heard"]');requestPlayer.onended();assert(!d.querySelector('.choice-glow'),'completed choice must not light up again');assert.equal(lastAudio,'audio/ar/'+e.id+'-needB.mp3');click('[data-action="next"]');click('[data-action="next"]');assert(d.querySelector('[data-action="choose"].choice-glow'));assert.equal(lastAudio,'audio/ar/hint-plan.mp3');click('[data-action="choose"][data-plan="turns"]');if(e.track!=='entry'){click('[data-action="next"]');assert(d.querySelector('[data-action="preview"][data-plan="together"].choice-glow'));assert.equal(lastAudio,'audio/ar/hint-both.mp3');click('[data-action="preview"][data-plan="together"]');}click('[data-action="next"]');assert.equal(d.querySelector('#rule').value,e.plans.turns.rule_ar);click('[data-action="next"]');assert(d.querySelector('.choice-glow [data-field="consent"]'));assert.equal(lastAudio,'audio/ar/hint-consent.mp3');check('[data-field="consent"][data-index="0"]');check('[data-field="consent"][data-index="1"]');click('[data-action="next"]');assert(d.querySelector('main').textContent.includes(e.trial.ar));click('[data-action="next"]');assert(d.querySelector('.choice-glow [data-field="trial_done"]'));check('[data-field="trial_done"]');click('[data-action="next"]');assert(d.querySelector('main').textContent.includes(e.question.ar));click('[data-action="finish"]');assert(d.querySelector('[data-action="reflect"].choice-glow'));click('[data-action="reflect"][data-value="worked"]');click('[data-action="finish"]');assert(d.querySelector('main h2').textContent.includes(e.title.ar));click('[data-action="home"]');}
assert.equal(w.APP360_COOPERATE.state().gallery.length,15);click('#langBtn');assert(d.querySelector('main').textContent.includes('A plan to finish together'));assert.equal(w.APP360_COOPERATE.state().gallery[14].situation_id,'team-cleanup');dom.window.close();console.log('PASS: all 15 rendered flows, saved identities, bilingual titles and all choice hints');
