(function(w){'use strict';
function copy(x){return JSON.parse(JSON.stringify(x))}
function id(){return 'work-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8)}
function blank(){return{schema_version:1,language:'ar',level:1,view:'library',assistance:'together',voice_guidance:true,draft:null,saved:[],templates:[],notes:{}}}
function page(){return{commands:[],undone:[],caption:'',dictation:'',recording_ref:''}}
function start(m,assistance){var pages=[],i;for(i=0;i<m.pages;i++)pages.push(page());return{id:id(),source_id:m.id,language:m.language,level:m.level,stage:'draw',page:0,title:m.title,recipient:'',purpose:'',reflection:'',pages:pages,original_attempts:[],assistance_level:assistance||'together',created:Date.now(),updated:Date.now()}}
function checkpoint(d,reason){if(!d)return;var pages=copy(d.pages);for(var i=0;i<pages.length;i++)pages[i].undone=[];var sig=JSON.stringify(pages),last=d.original_attempts[d.original_attempts.length-1];if(last&&JSON.stringify(last.pages)===sig)return;d.original_attempts.push({at:Date.now(),reason:reason,assistance:d.assistance_level,pages:pages});if(d.original_attempts.length>8)d.original_attempts.shift();d.updated=Date.now()}
function number(x,min,max){return typeof x==='number'&&isFinite(x)&&x>=min&&x<=max}
function cleanCommand(c){if(!c||typeof c!=='object')throw Error('invalid-command');if(c.type==='stamp'){if(['heart','star','sun','flower','house','book','balloon','leaf','smile','circle'].indexOf(c.kind)<0||!number(c.x,0,1)||!number(c.y,0,1)||!number(c.size,.02,.5))throw Error('invalid-stamp');return{type:'stamp',kind:c.kind,x:c.x,y:c.y,size:c.size,color:color(c.color)}}if(c.type!=='stroke'||!Array.isArray(c.points)||c.points.length<1||c.points.length>1600||!number(c.width,1,100))throw Error('invalid-stroke');return{type:'stroke',points:c.points.map(function(p){if(!p||!number(p.x,0,1)||!number(p.y,0,1))throw Error('invalid-point');return{x:p.x,y:p.y}}),color:color(c.color),width:c.width,erase:!!c.erase}}
function color(x){return /^#[a-fA-F0-9]{6}$/.test(x||'')?x:'#343b52'}
function text(x,n){return typeof x==='string'?x.slice(0,n):''}
function cleanPage(p,strip){if(!p||!Array.isArray(p.commands)||p.commands.length>600)throw Error('invalid-page');var q=page();q.commands=p.commands.map(cleanCommand);q.undone=Array.isArray(p.undone)?p.undone.slice(0,100).map(cleanCommand):[];q.caption=text(p.caption,600);q.dictation=text(p.dictation,600);q.recording_ref=strip?'':text(p.recording_ref,150);return q}
function artifact(d,strip){if(!d||!Array.isArray(d.pages)||d.pages.length<1||d.pages.length>4||['ar','en'].indexOf(d.language)<0||!number(d.level,1,4))throw Error('invalid-artifact');return{id:text(d.id,100)||id(),source_id:text(d.source_id,100),language:d.language,level:d.level,stage:['draw','meaning','review'].indexOf(d.stage)>=0?d.stage:'draw',page:number(d.page,0,d.pages.length-1)?d.page:0,title:text(d.title,120),recipient:text(d.recipient,100),purpose:text(d.purpose,300),reflection:text(d.reflection,500),pages:d.pages.map(function(p){return cleanPage(p,strip)}),original_attempts:Array.isArray(d.original_attempts)?d.original_attempts.slice(-8).map(function(a){if(!a||!Array.isArray(a.pages)||a.pages.length>4)throw Error('invalid-attempt');return{at:Number(a.at)||0,reason:text(a.reason,80),assistance:text(a.assistance,30),pages:a.pages.map(function(p){return cleanPage(p,strip)})}}):[],assistance_level:['together','hint','independent'].indexOf(d.assistance_level)>=0?d.assistance_level:'together',created:Number(d.created)||Date.now(),updated:Number(d.updated)||Date.now()}}
function restore(raw){if(!raw)return blank();var x;try{x=JSON.parse(raw)}catch(e){throw Error('corrupt-storage')}if(!x||x.schema_version!==1)throw Error('unknown-schema');var s=blank();s.language=x.language==='en'?'en':'ar';s.level=number(x.level,1,4)?x.level:1;s.view=['library','studio','saved','coach','review-saved'].indexOf(x.view)>=0?x.view:'library';s.assistance=['together','hint','independent'].indexOf(x.assistance)>=0?x.assistance:'together';s.voice_guidance=x.voice_guidance!==false;s.draft=x.draft?artifact(x.draft,false):null;if(!Array.isArray(x.saved)||x.saved.length>60)throw Error('invalid-collection');s.saved=x.saved.map(function(d){return artifact(d,false)});s.templates=Array.isArray(x.templates)?x.templates.slice(0,30):[];s.notes=x.notes&&typeof x.notes==='object'?x.notes:{};return s}
function saveAttempt(s){if(!s.draft)return null;checkpoint(s.draft,'saved');var d=artifact(s.draft,false);d.id=id();d.saved_at=Date.now();s.saved.push(d);return d}
function exportData(items){return{schema_version:1,app_id:'a4-draw-write',media_policy:'Voice recordings and private coach notes excluded',projects:items.map(function(d){return artifact(d,true)})}}
function importData(raw){var x=JSON.parse(raw);if(x.app_id!=='a4-draw-write'||x.schema_version!==1||!Array.isArray(x.projects)||x.projects.length>60)throw Error('invalid-import');return x.projects.map(function(d){var a=artifact(d,true);a.id=id();return a})}
w.STUDIO_MODEL={blank:blank,start:start,page:page,copy:copy,id:id,checkpoint:checkpoint,artifact:artifact,restore:restore,saveAttempt:saveAttempt,exportData:exportData,importData:importData};
})(typeof window!=='undefined'?window:globalThis);
