(function(w,d){'use strict';
var D=w.ROUTINE_DATA,key='app360-a1-routine-v2',routine=null,run=null,sound=true,view='library',display='one',selectedHabit=0,activeCategory='all',storyTimer=null;
function E(x){return d.getElementById(x)}
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function toast(s){var x=E('toast');if(!x)return;x.innerHTML=s;x.style.display='block';setTimeout(function(){x.style.display='none'},1400)}
function category(id){var i;for(i=0;i<D.categories.length;i++)if(D.categories[i].id===id)return D.categories[i];return D.categories[0]}
function habitById(id){var i;for(i=0;i<D.habits.length;i++)if(D.habits[i].id===id)return D.habits[i];return null}
function artFor(label){var i,j,h;for(i=0;i<D.habits.length;i++){h=D.habits[i];for(j=0;j<h.steps.length;j++)if(h.steps[j]===label)return h.arts[j]||h.icon}return'⭐'}
function speakText(text){if(!sound||!text)return;try{if(w.speechSynthesis&&w.SpeechSynthesisUtterance){var u=new SpeechSynthesisUtterance(text);u.lang='ar-SA';u.rate=.82;w.speechSynthesis.cancel();w.speechSynthesis.speak(u)}}catch(e){}}
function saveLocal(){try{localStorage.setItem(key,JSON.stringify({routine:routine,run:run,display:display,selectedHabit:selectedHabit,reflection:E('reflection')?E('reflection').value:''}));return true}catch(e){toast('يمكن المتابعة، لكن الحفظ غير متاح');return false}}
function load(){try{var x=JSON.parse(localStorage.getItem(key)||'null');if(x){routine=x.routine;run=x.run;display=x.display||'one';selectedHabit=parseInt(x.selectedHabit,10)||0}}catch(e){}}
function show(v){view=v;var vs=d.querySelectorAll('.view'),bs=d.querySelectorAll('#tabs button'),i;for(i=0;i<vs.length;i++)vs[i].className=vs[i].id===v?'view on':'view';for(i=0;i<bs.length;i++)bs[i].className=bs[i].getAttribute('data-view')===v?'on':'';if(v==='builder')renderBuilder();if(v==='child')renderChild();if(v==='review')renderReview();w.scrollTo(0,0)}
function renderCategories(){var h='<button data-cat="all" class="on"><span>✨</span><b>الكل</b><small>50</small></button>',i,c,count,j;for(i=0;i<D.categories.length;i++){c=D.categories[i];count=0;for(j=0;j<D.habits.length;j++)if(D.habits[j].category===c.id)count++;h+='<button data-cat="'+c.id+'"><span>'+c.icon+'</span><b>'+c.title+'</b><small>'+count+'</small></button>'}E('categoryRail').innerHTML=h;bindTap(E('categoryRail'),function(t){while(t&&t!==E('categoryRail')&&!t.getAttribute('data-cat'))t=t.parentNode;if(t&&t!==E('categoryRail'))setCategory(t.getAttribute('data-cat'))})}
function setCategory(id){activeCategory=id||'all';var bs=E('categoryRail').getElementsByTagName('button'),i,first=-1;for(i=0;i<bs.length;i++)bs[i].className=bs[i].getAttribute('data-cat')===activeCategory?'on':'';for(i=0;i<D.habits.length;i++)if(activeCategory==='all'||D.habits[i].category===activeCategory){first=i;break}if(first>=0)selectHabit(first,false);renderHabitCards()}
function renderHabitCards(){var h='',i,a,c;for(i=0;i<D.habits.length;i++){a=D.habits[i];if(activeCategory!=='all'&&a.category!==activeCategory)continue;c=category(a.category);h+='<button class="habitCard '+(i===selectedHabit?'selected':'')+'" data-habit="'+a.id+'" style="border-top-color:'+c.accent+'"><span class="habitNo">'+a.num+'</span><span class="habitIcon">'+a.icon+'</span><span class="habitWords"><b>'+esc(a.title)+'</b><small>'+esc(c.title)+' · 5 لقطات</small></span><i>شاهد ›</i></button>'}E('habitCards').innerHTML=h;bindTap(E('habitCards'),function(t){while(t&&t!==E('habitCards')&&!t.getAttribute('data-habit'))t=t.parentNode;if(t&&t!==E('habitCards')){var a=habitById(t.getAttribute('data-habit')),j;for(j=0;j<D.habits.length;j++)if(D.habits[j]===a){selectHabit(j,true);break}}})}
function selectHabit(i,scroll){if(i<0)i=D.habits.length-1;if(i>=D.habits.length)i=0;selectedHabit=i;var a=D.habits[i],c=category(a.category),board=E('storyBoard');board.className='storyBoard theme-'+a.category;E('storyNum').innerHTML=a.num;E('storyCategory').innerHTML=c.icon+' '+c.title;E('storyTitle').innerHTML=a.title;E('storyTip').innerHTML=a.tip||'خمس لقطات بسيطة ثم ممارسة حقيقية.';renderScenes(a);renderHabitCards();saveLocal();if(scroll){var r=board.getBoundingClientRect();w.scrollTo(0,(w.pageYOffset||d.documentElement.scrollTop||0)+r.top-90)}}
function renderScenes(a){var h='',dots='',i;for(i=0;i<a.steps.length;i++){h+='<div class="sceneCard" data-scene="'+i+'"><span class="sceneNo">'+(i+1)+'</span><div class="sceneArt">'+(a.arts[i]||a.icon)+'</div><b>'+esc(a.steps[i])+'</b><small>'+(a.demo?'نموذج بصري · الصورة النهائية ستستبدل هنا':'لقطة '+(i+1)+' جاهزة لإضافة الصورة')+'</small></div>';dots+='<i'+(i===0?' class="on"':'')+'></i>'}E('sceneStrip').innerHTML=h;E('storyDots').innerHTML=dots}
function stopStory(){if(storyTimer){clearTimeout(storyTimer);storyTimer=null}var cards=E('sceneStrip').getElementsByTagName('div'),i;for(i=0;i<cards.length;i++)if((' '+cards[i].className+' ').indexOf(' sceneCard ')>=0)cards[i].className='sceneCard'}
function playStory(){stopStory();var a=D.habits[selectedHabit],cards=[],nodes=E('sceneStrip').childNodes,i=0;for(var j=0;j<nodes.length;j++)if(nodes[j].nodeType===1)cards.push(nodes[j]);function step(){if(i>0)cards[i-1].className='sceneCard';if(i>=cards.length){storyTimer=null;toast('أحسنت يا بطل ⭐ الآن نجربها في الواقع');speakText('أحسنت يا بطل');return}cards[i].className='sceneCard active';var ds=E('storyDots').getElementsByTagName('i'),k;for(k=0;k<ds.length;k++)ds[k].className=k===i?'on':'';speakText(a.steps[i]);i++;storyTimer=setTimeout(step,1500)}step()}
function chooseHabit(a){routine={id:'r'+new Date().getTime(),sourceHabit:a.id,title:a.title,steps:[],created:new Date().getTime()};for(var i=0;i<a.steps.length;i++)routine.steps.push({id:'s'+i,label:a.steps[i],art:a.arts[i]||a.icon,instruction:a.steps[i],assistance:'حسب الحاجة'});run=null;saveLocal();show('builder')}
function blank(){routine={id:'r'+new Date().getTime(),title:'روتيني الجديد',steps:[{id:'s0',label:'خطوتي الأولى',art:'⭐',instruction:'نفذ الخطوة مع المرافق',assistance:'حسب الحاجة'}]};run=null;show('builder')}
function renderBuilder(){if(!routine){chooseHabit(D.habits[selectedHabit]);return}E('builderTitle').innerHTML=routine.title;var h='',i,s;for(i=0;i<routine.steps.length;i++){s=routine.steps[i];h+='<div class="stepRow" data-i="'+i+'"><div class="stepPic">'+(s.art||artFor(s.label))+'</div><div class="stepText"><b>'+(i+1)+'. '+esc(s.label)+'</b><small>'+esc(s.instruction||s.label)+'</small></div><div class="stepBtns"><button data-a="up" aria-label="أعلى">↑</button><button data-a="down" aria-label="أسفل">↓</button><button data-a="copy" aria-label="نسخ">⧉</button><button data-a="del" aria-label="حذف">×</button></div></div>'}E('stepList').innerHTML=h;renderMini();bindTap(E('stepList'),stepAction)}
function stepAction(t){while(t&&t!==E('stepList')&&!t.getAttribute('data-a'))t=t.parentNode;if(!t||t===E('stepList'))return;var row=t.parentNode.parentNode,i=parseInt(row.getAttribute('data-i'),10),a=t.getAttribute('data-a'),x;if(a==='up'&&i>0){x=routine.steps[i-1];routine.steps[i-1]=routine.steps[i];routine.steps[i]=x}if(a==='down'&&i<routine.steps.length-1){x=routine.steps[i+1];routine.steps[i+1]=routine.steps[i];routine.steps[i]=x}if(a==='copy'&&routine.steps.length<8){x={id:'s'+new Date().getTime(),label:routine.steps[i].label,art:routine.steps[i].art,instruction:routine.steps[i].instruction,assistance:routine.steps[i].assistance};routine.steps.splice(i+1,0,x)}if(a==='del'&&routine.steps.length>1)routine.steps.splice(i,1);saveLocal();renderBuilder()}
function renderMini(){var h='',i;for(i=0;i<routine.steps.length;i++)h+='<span><em>'+(routine.steps[i].art||artFor(routine.steps[i].label))+'</em><small>'+(i+1)+'</small></span>';E('miniStrip').innerHTML=h}
function addStep(){if(routine.steps.length>=8){toast('ثماني خطوات كحد أقصى');return}routine.steps.push({id:'s'+new Date().getTime(),label:'خطوة جديدة',art:'⭐',instruction:'نفذ الخطوة مع المرافق',assistance:'حسب الحاجة'});saveLocal();renderBuilder()}
function start(){if(!routine||!routine.steps.length)return;run={current:0,results:[],status:'running',started:new Date().getTime()};saveLocal();show('child')}
function renderChild(){if(!routine)return show('library');if(!run)run={current:0,results:[],status:'running'};var i=Math.min(run.current,routine.steps.length-1),s=routine.steps[i],art=s.art||artFor(s.label);E('runTitle').innerHTML=routine.title;E('progressText').innerHTML='الخطوة '+(i+1)+' من '+routine.steps.length;E('focusImg').style.display='none';E('focusLabel').innerHTML='<span class="focusEmoji">'+art+'</span>'+esc(s.label);E('focusInstruction').innerHTML=esc(s.instruction||s.label);var h='',j,startAt=Math.max(0,i-1),end=Math.min(routine.steps.length,i+4);for(j=startAt;j<end;j++)h+='<span class="'+(j===i?'active':'')+'"><em>'+(routine.steps[j].art||artFor(routine.steps[j].label))+'</em><small>'+(j+1)+'</small></span>';E('filmStrip').innerHTML=h;var nn='';if(display==='now-next'){nn='<div><b>الآن</b><span>'+art+'</span><small>'+esc(s.label)+'</small></div>';if(i+1<routine.steps.length)nn+='<div><b>بعد ذلك</b><span>'+(routine.steps[i+1].art||artFor(routine.steps[i+1].label))+'</span><small>'+esc(routine.steps[i+1].label)+'</small></div>'}E('nowNext').innerHTML=nn;E('filmStrip').style.display=display==='sequence'?'block':'none';E('nowNext').style.display=display==='now-next'?'block':'none'}
function outcome(o){var i=run.current;run.results.push({step:routine.steps[i].id,outcome:o,at:new Date().getTime()});run.current++;if(run.current>=routine.steps.length){run.status='completed';saveLocal();speakText('أحسنت يا بطل');show('review')}else{saveLocal();renderChild();toast(o==='assisted'?'أكملناها معًا 🤝':o==='skipped'?'انتقلنا بلطف':'أحسنت، إلى الخطوة التالية')}}
function renderReview(){if(!routine)return;var a=0,b=0,c=0,i,r;for(i=0;i<(run?run.results.length:0);i++){r=run.results[i].outcome;if(r==='independent')a++;if(r==='assisted')b++;if(r==='skipped')c++}E('reviewSummary').innerHTML='<div class="summaryBox"><span>✓ تم: '+a+'</span><span>🤝 بمساعدة: '+b+'</span><span>↷ تجاوزنا: '+c+'</span></div><p>هذه ملاحظة للجلسة وليست تقييمًا للطفل. يمكن تقصير الروتين أو تغيير صورة في المرة القادمة.</p>'}
function speakStep(){if(!routine||!run)return;speakText(routine.steps[Math.min(run.current,routine.steps.length-1)].label)}
function bindTap(el,fn){var moved=false,sx=0,sy=0,last=0;el.ontouchstart=function(e){var q=e.touches&&e.touches[0];if(!q)return;sx=q.clientX;sy=q.clientY;moved=false};el.ontouchmove=function(e){var q=e.touches&&e.touches[0];if(q&&(Math.abs(q.clientX-sx)>10||Math.abs(q.clientY-sy)>10))moved=true};el.ontouchend=function(e){last=new Date().getTime();if(!moved){if(e.preventDefault)e.preventDefault();fn(e.target||e.srcElement)}};el.onclick=function(e){if(new Date().getTime()-last<650)return;fn(e.target||e.srcElement)}}
function init(){load();renderCategories();renderHabitCards();selectHabit(Math.min(selectedHabit,D.habits.length-1),false);var tabs=E('tabs');bindTap(tabs,function(t){while(t&&t!==tabs&&!t.getAttribute('data-view'))t=t.parentNode;if(t&&t!==tabs)show(t.getAttribute('data-view'))});E('prevHabit').onclick=function(){selectHabit(selectedHabit-1,true)};E('nextHabit').onclick=function(){selectHabit(selectedHabit+1,true)};E('playStory').onclick=playStory;E('speakStory').onclick=function(){speakText(D.habits[selectedHabit].title)};E('useHabit').onclick=function(){chooseHabit(D.habits[selectedHabit])};E('blank').onclick=blank;E('addStep').onclick=addStep;E('save').onclick=function(){saveLocal();toast('تم الحفظ على هذا الجهاز')};E('startRoutine').onclick=start;E('backBuilder').onclick=function(){show('builder')};E('stopRun').onclick=function(){if(run){run.status='stopped';saveLocal()}show('review')};E('speakStep').onclick=speakStep;var os=d.querySelectorAll('.outcomes button'),i;for(i=0;i<os.length;i++)os[i].onclick=function(){outcome(this.getAttribute('data-outcome'))};var modes=d.querySelectorAll('[data-display]');for(i=0;i<modes.length;i++)modes[i].onclick=function(){display=this.getAttribute('data-display');saveLocal();renderMini();toast('تم تغيير طريقة العرض')};E('print').onclick=function(){w.print()};E('exportBtn').onclick=function(){var text=JSON.stringify({schema:2,routine:routine,run:run},null,2);try{var a=d.createElement('a');a.href='data:application/json;charset=utf-8,'+encodeURIComponent(text);a.download='routine.json';a.click()}catch(e){toast('التصدير غير مدعوم هنا')}};E('again').onclick=function(){start()};E('sound').onclick=function(){sound=!sound;this.innerHTML=sound?'🔊':'🔇'};if(run&&run.status==='running'&&routine)show('child');else show('library');if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(function(){})}
init();
})(window,document);