/* Optional browser QA: requires Playwright, Chromium and Python. No production dependency. */
const fs=require('fs'),cp=require('child_process'),assert=require('assert/strict'),path=require('path'),os=require('os'),{chromium}=require('playwright');
const repo=path.resolve(__dirname,'../../../..'),qaDir=process.env.STORY_TEST_OUTPUT||path.join(os.tmpdir(),'app360-story-qa');
const base='http://127.0.0.1:8766/',app=base+'apps/4-8/story-language-lab/',delay=ms=>new Promise(r=>setTimeout(r,ms)),results=[],metrics={};let browser;
const server=cp.spawn('python',['-m','http.server','8766','--bind','127.0.0.1'],{cwd:repo,stdio:'ignore'});
async function click(p,a,v){if(a==='stage'&&await p.locator('[data-do="stage"][data-value="'+v+'"]:visible').count()===0)await p.locator('[data-do="toggle-steps"]').click();await p.locator('[data-do="'+a+'"]'+(v===undefined?'':'[data-value="'+v+'"]')+':visible').first().click();}
const state=p=>p.evaluate(()=>APP360_STORY.snapshot());
async function ready(p){await p.waitForFunction(()=>window.APP360_STORY);}
async function test(name,fn){await fn();results.push(name);console.log('PASS '+name);}
(async()=>{await delay(600);browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});fs.mkdirSync(qaDir,{recursive:true});const c=await browser.newContext({viewport:{width:412,height:915},permissions:['microphone']});const p=await c.newPage(),errors=[],requested=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>requested.push(r.url()));await p.goto(app);await ready(p);
await test('Three open age levels, light responsive images and child controls',async()=>{assert.equal(await p.locator('.levels .track').count(),3);assert.equal(await p.locator('#voiceBtn svg').count(),1);assert.equal(await p.locator('.age-range[dir="ltr"]').count(),4);assert.match(await p.locator('.levels').innerText(),/4–5/);await p.waitForFunction(()=>document.querySelector('.cover img').naturalWidth>0);assert.match(await p.locator('.cover img').evaluate(i=>i.currentSrc),/\.webp/);assert.ok(!requested.some(u=>/cup-story\.png|cat-story\.png|ball-story\.png|a4-story-language-v1\.png/.test(u)));assert.equal(await p.locator('[data-do="open"] .picture-play').count(),4);});
await test('Entry child loop works entirely by picture taps and spoken help',async()=>{await click(p,'open','ar-cup');await p.waitForFunction(()=>APP360_STORY_AUDIO.debug().plays>0);await click(p,'play-scene','cup-0');await p.waitForFunction(()=>APP360_STORY_AUDIO.debug().path==='audio/ar-cup-0.mp3');await p.waitForTimeout(150);await click(p,'play-scene','cup-0');await p.waitForFunction(()=>APP360_STORY_AUDIO.debug().path==='audio/ar-cup-0.mp3');assert.ok(await p.evaluate(()=>APP360_STORY_AUDIO.debug().lastStartMs)<300);await click(p,'stage','meaning');await click(p,'meaning','0');await click(p,'stage','order');for(const id of ['cup-0','cup-1','cup-2'])await click(p,'order-pick',id);await click(p,'order-check');assert.deepEqual((await state(p)).drafts['ar-cup'].scene_order,['cup-0','cup-1','cup-2']);await click(p,'stage','compose');assert.equal(await p.locator('#ending').isVisible(),false);await click(p,'ending-choice','0');await click(p,'save-story');assert.equal((await state(p)).saved.length,1);assert.match((await state(p)).saved[0].ending,/لَيْلَى/);assert.deepEqual((await state(p)).progress.entry,['ar-cup']);});
await test('Middle level builds a joined word and three-word sentence',async()=>{await click(p,'library');await click(p,'track','practice');await click(p,'open','ar-door');await click(p,'stage','word');await click(p,'word-add','0');await click(p,'word-add','1');await click(p,'word-check');assert.match(await p.locator('#builtWord').innerText(),/بَاب/);await click(p,'stage','sentence');for(const n of [0,1,2])await click(p,'sentence-add',String(n));await click(p,'sentence-check');const before=(await state(p)).drafts['ar-door'].sentence_sequences.practice;await p.setViewportSize({width:640,height:360});await p.reload();await ready(p);assert.deepEqual((await state(p)).drafts['ar-door'].sentence_sequences.practice,before);await click(p,'stage','compose');await click(p,'ending-choice','1');await click(p,'save-story');assert.match((await state(p)).saved.at(-1).sentence_text,/عُمَرُ طَرَقَ/);});
await test('Advanced English transfer word, longer sentence and optional authorship',async()=>{await click(p,'library');await click(p,'language','en');await click(p,'track','extend');await p.locator('[data-do="all-stories"]').click();await click(p,'open','en-cat');await click(p,'stage','word');await click(p,'transfer-build');for(const i of [0,1,2])await click(p,'word-add',String(i));await click(p,'word-check');assert.equal(await p.locator('#builtWord').innerText(),'mat');await click(p,'stage','sentence');await click(p,'sentence-model');assert.equal((await state(p)).drafts['en-cat'].sentence_sequences.extend.length,5);await click(p,'stage','compose');await click(p,'toggle-writing');await p.locator('#storyTitle').fill('My own cat story');await p.locator('#ending').fill('The cat visits a friend.');await p.locator('#caption-0').fill('My first picture');await click(p,'compose-add','ball-2');assert.equal((await state(p)).drafts['en-cat'].compose.length,5);await click(p,'save-story');assert.equal((await state(p)).saved.at(-1).ending,'The cat visits a friend.');assert.equal(await p.locator('html').getAttribute('dir'),'ltr');});
await test('Optional recording, private export, print and restore',async()=>{await click(p,'library');await p.evaluate(()=>APP360_STORY.open('en-cat','compose'));await click(p,'record-start');await p.locator('[data-do="record-stop"]').waitFor();await delay(300);await click(p,'record-stop');await p.locator('#recordStatus').filter({hasText:'A local recording is saved'}).waitFor();await click(p,'save-story');await p.locator('[data-do="play-saved-recording"]').waitFor();const out=await p.evaluate(()=>APP360_STORY.exportData());assert.ok(!JSON.stringify(out).includes('recording_ref_optional'));assert.ok(!JSON.stringify(out).includes('profile_ref'));await p.evaluate(()=>window.print=()=>{});await click(p,'print');await p.emulateMedia({media:'print'});await p.pdf({path:qaDir+'/story-book.pdf',format:'A4',printBackground:true});await p.emulateMedia({media:'screen'});await click(p,'saved');const n=(await state(p)).saved.length;p.once('dialog',d=>d.accept());await p.locator('#importFile').setInputFiles({name:'stories.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(out))});await p.waitForFunction(n=>APP360_STORY.snapshot().saved.length===n*2,n);});
await test('Offline pack completes without reloading the first lesson and keeps all three levels',async()=>{await p.waitForFunction(()=>APP360_STORY.isOfflineReady(),null,{timeout:60000});await c.setOffline(true);await p.reload();await ready(p);await click(p,'library');await click(p,'language','ar');for(const track of ['entry','practice','extend']){await click(p,'track',track);assert.equal((await state(p)).track,track);}await p.evaluate(()=>APP360_STORY.open('ar-door','sentence'));await click(p,'sentence-model');await p.waitForFunction(()=>APP360_STORY_AUDIO.debug().path.indexOf('sentence')>=0);assert.ok(await p.evaluate(async()=>(await(await fetch('audio/ar-door-new-sound-1.mp3')).arrayBuffer()).byteLength)>100);await c.setOffline(false);});
await test('Update waits while authoring and age suggestions remain adjustable',async()=>{await p.evaluate(()=>navigator.serviceWorker.dispatchEvent(new Event('controllerchange')));await delay(350);assert.ok(await p.locator('#builtSentence').isVisible());await click(p,'library');await ready(p);await click(p,'coach');await p.locator('#learnerAge').selectOption('7');assert.equal((await state(p)).track,'extend');await click(p,'track','entry');assert.equal((await state(p)).track,'entry');assert.equal((await state(p)).learner_age,7);});
await test('Viewport matrix retains layout and all touch targets',async()=>{for(const [width,height] of [[360,640],[412,915],[768,1024],[1024,768],[1440,900]]){await p.setViewportSize({width,height});await click(p,'library');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),width+' library');await p.evaluate(()=>APP360_STORY.open('ar-cup','compose'));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),width+' composer');await p.evaluate(()=>APP360_STORY.open('ar-cup','sentence'));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),width+' sentence');assert.ok(await p.evaluate(()=>document.querySelector('.journey-actions').getBoundingClientRect().top>=document.querySelector('#app>.panel').getBoundingClientRect().bottom),width+' action footer cannot cover tiles');}await click(p,'library');await p.screenshot({path:qaDir+'/library-desktop.png',fullPage:true});await p.setViewportSize({width:412,height:915});await p.screenshot({path:qaDir+'/library-phone.png',fullPage:true});await p.evaluate(()=>APP360_STORY.open('ar-cup','sentence'));await p.screenshot({path:qaDir+'/sentence-phone.png',fullPage:true});});assert.deepEqual(errors,[]);await c.close();
const profiles=await browser.newContext({serviceWorkers:'block'});await profiles.addInitScript(()=>{window.testProfile='A';window.APP360_FAMILY_SYNC={getProfileKey:()=>testProfile,getSession:()=>({role:'owner',room:'test'})};});const q=await profiles.newPage();await q.goto(app);await ready(q);
await test('Level progress and authorship isolate by learner',async()=>{await q.evaluate(()=>APP360_STORY.open('ar-cup','compose'));await click(q,'ending-choice','0');await click(q,'save-story');await q.evaluate(()=>testProfile='B');await q.waitForFunction(()=>APP360_STORY.profile()==='B');assert.equal((await state(q)).progress.entry.length,0);assert.equal((await state(q)).saved.length,0);await q.evaluate(()=>testProfile='A');await q.waitForFunction(()=>APP360_STORY.profile()==='A');assert.equal((await state(q)).saved.length,1);});await profiles.close();
const legacy=await browser.newContext({serviceWorkers:'block',viewport:{width:1024,height:768},userAgent:'Mozilla/5.0 (Linux; Android 4.4.2; BigTAB) AppleWebKit/537.36 Chrome/34.0.1847.114 Safari/537.36'});await legacy.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw Error('denied')}});window.AudioContext=window.webkitAudioContext=undefined;window.MediaRecorder=undefined;Object.defineProperty(navigator,'mediaDevices',{value:undefined});});const l=await legacy.newPage();await l.goto(app);await ready(l);
await test('Legacy HTML audio and unavailable storage still support independent play',async()=>{await click(l,'open','ar-cup');await click(l,'play-scene','cup-0');await l.waitForFunction(()=>APP360_STORY_AUDIO.debug().plays>0);assert.equal(await l.evaluate(()=>APP360_STORY_AUDIO.debug().context),'html-audio');await click(l,'stage','compose');await click(l,'ending-choice','1');await click(l,'save-story');assert.equal((await state(l)).saved.length,1);assert.match(await l.locator('#storageStatus').innerText(),/مؤقت/);});await legacy.close();
const denied=await browser.newContext({serviceWorkers:'block'});await denied.addInitScript(()=>navigator.mediaDevices.getUserMedia=()=>Promise.reject(Error('denied')));const d=await denied.newPage();await d.goto(app);await ready(d);
await test('Denied microphone cannot block the picture ending or save',async()=>{await d.evaluate(()=>APP360_STORY.open('ar-cup','compose'));await click(d,'record-start');await d.waitForFunction(()=>document.querySelector('#notice').textContent.indexOf('الميكروفون')>=0);await click(d,'ending-choice','0');await click(d,'save-story');assert.equal((await state(d)).saved.length,1);});await denied.close();
const links=await browser.newContext({serviceWorkers:'block'});const linked=await links.newPage();await linked.goto(base+'apps/4-8/story-language-lab/launch.html?item=en-door&stage=word');await linked.waitForSelector('iframe');const linkedFrame=await(await linked.$('iframe')).contentFrame();await ready(linkedFrame);await linkedFrame.waitForFunction(()=>APP360_STORY.snapshot().active==='en-door');await test('Existing launch links still open the requested English lesson',async()=>{assert.equal((await state(linkedFrame)).active,'en-door');assert.equal((await state(linkedFrame)).language,'en');assert.equal(await linkedFrame.locator('#builtWord').count(),1);});await links.close();
const guest=await browser.newContext({serviceWorkers:'block'});await guest.addInitScript(()=>{window.APP360_FAMILY_SYNC={getProfileKey:()=> 'guest-test',getSession:()=>({role:'guest',room:'test',adminRole:'member'})};});const g=await guest.newPage();await g.goto(app);await ready(g);await test('Guest learner has child play while age and template controls stay with the coach',async()=>{await click(g,'coach');assert.equal(await g.locator('#learnerAge').count(),0);assert.equal(await g.locator('#templateSource').count(),0);await click(g,'library');await click(g,'track','practice');await click(g,'open','ar-door');assert.equal((await state(g)).active,'ar-door');});await guest.close();
const school=await browser.newContext({serviceWorkers:'block'});const h=await school.newPage(),schoolImages=[];h.on('request',r=>{if(r.resourceType()==='image')schoolImages.push(r.url());});await h.goto(base);await h.waitForFunction(()=>window.APP360_FAMILY_SYNC&&APP360_FAMILY_SYNC.openApp);await h.locator('#a360GlobalName').fill('اختبار الأسرة');await h.locator('#a360GlobalAge').selectOption('4-8');await h.locator('[data-prof-save]').click();
await test('Real cover and open button share the shell, swipes are ignored and returning restores scroll',async()=>{
 await h.waitForFunction(()=>APP360_FAMILY_SYNC.apps.some(a=>a.id==='a4-story-language'));
 const cover=h.locator('#showcaseTrack [data-app="a4-story-language"] .showcase-cover-img');
 await delay(500);await cover.click({force:true});
 await h.waitForFunction(()=>APP360_FAMILY_SHELL.getActiveApp()&&APP360_FAMILY_SHELL.getActiveApp().id==='a4-story-language');
 const f=h.frameLocator('#app360FamilyShellFrame');await f.locator('[data-do="open"][data-value="ar-cup"]').first().click();
 assert.ok(h.url().startsWith(base+'?'));assert.equal(await h.evaluate(()=>APP360_FAMILY_SHELL.getActiveApp().id),'a4-story-language');
 await f.locator('#homeBtn').click();await h.locator('#app360FamilyShellFrame').waitFor({state:'hidden'});
 await h.evaluate(()=>{const el=document.querySelector('#showcaseTrack [data-app="a4-story-language"] .showcase-cover-link');function send(type,x,y){const e=new Event(type,{bubbles:true,cancelable:true});e.touches=type==='touchend'?[]:[{clientX:x,clientY:y}];e.changedTouches=[{clientX:x,clientY:y}];el.dispatchEvent(e);}send('touchstart',200,240);send('touchmove',202,340);send('touchend',202,340);el.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true}));});
 assert.equal(await h.evaluate(()=>APP360_FAMILY_SHELL.getActiveApp()),null);await delay(750);
 await h.locator('#showcaseTrack [data-app="a4-story-language"] .open').click({force:true});await f.locator('#homeBtn').click();await h.locator('#app360FamilyShellFrame').waitFor({state:'hidden'});
 await h.locator('#showcaseToolsToggle').click();await h.locator('#modeClassic').click();
 await h.locator('#homeClassicGrid img[src*="a4-story-language-v2-640.webp"]').waitFor();await h.waitForFunction(()=>document.querySelector('.showcase-logo').naturalWidth>0);
 assert.match(await h.locator('.showcase-logo').getAttribute('src'),/640\.webp/);
 assert.ok(!schoolImages.some(u=>/family-reels-(?:learner|coach)-art\.png|family-school-360-logo\.png/.test(u)));
 for(let i=0;i<3;i++){
  await h.locator('#homeClassicGrid .classic-cover[href*="story-language-lab"]').click();await f.locator('#homeBtn').click();await h.locator('#app360FamilyShellFrame').waitFor({state:'hidden'});
  await h.evaluate(()=>scrollTo(0,0));await h.mouse.move(400,600);await h.mouse.wheel(0,650);await h.waitForFunction(()=>scrollY>0);
 }
});await school.close();
const expanded=await browser.newContext({serviceWorkers:'block',viewport:{width:412,height:915}});const x=await expanded.newPage();await x.goto(app);await ready(x);await x.waitForFunction(()=>window.APP360_FAMILY_SYNC&&APP360_FAMILY_SYNC.__ready);await x.locator('#a360GlobalName').fill('المحتوى الجديد');await x.locator('#a360GlobalAge').selectOption('4-8');await x.locator('[data-prof-save]').click();await x.waitForFunction(()=>APP360_STORY.profile()==='name:المحتوى الجديد');
await test('Twelve stories per language play in all levels with new sounds, sentences and picture endings',async()=>{
 for(const language of ['ar','en']){
  await click(x,'language',language);for(const track of ['entry','practice','extend']){await click(x,'track',track);assert.equal(await x.locator('[data-do="open"] .picture-play').count(),4);}
  await click(x,'track','entry');await click(x,'open',language+'-first-next-last');await click(x,'play-scene','first-next-last-1');await x.waitForFunction(lang=>APP360_STORY_AUDIO.debug().path==='audio/'+lang+'-first-next-last-1.mp3',language);await click(x,'stage','meaning');await click(x,'meaning','0');await click(x,'stage','compose');await click(x,'ending-choice','1');await click(x,'save-story');
  await click(x,'library');await click(x,'track','practice');await click(x,'open',language+'-ball-actions');await click(x,'stage','word');await click(x,'word-model');assert.equal((await state(x)).drafts[language+'-ball-actions'].grapheme_sequence.length,language==='ar'?2:3);await click(x,'stage','sentence');await click(x,'sentence-model');assert.equal((await state(x)).drafts[language+'-ball-actions'].sentence_sequences.practice.length,3);await click(x,'stage','compose');await click(x,'ending-choice','0');await click(x,'save-story');
  await click(x,'library');await click(x,'track','extend');await x.evaluate(id=>APP360_STORY.open(id,'word'),language+'-ball-actions');await click(x,'transfer-build');await click(x,'word-model');assert.match(await x.locator('#builtWord').innerText(),language==='ar'?/كُرَات/:/bell/);await click(x,'library');await click(x,'open',language+'-notice-and-explain');await click(x,'stage','sentence');await click(x,'sentence-model');assert.equal((await state(x)).drafts[language+'-notice-and-explain'].sentence_sequences.extend.length,5);await click(x,'stage','compose');await click(x,'ending-choice','1');await click(x,'save-story');
 }
 assert.equal((await state(x)).saved.length,6);
});
await test('Six-times CPU slowdown remains responsive during repeated lesson changes and audio taps',async()=>{
 const cdp=await expanded.newCDPSession(x);await cdp.send('Emulation.setCPUThrottlingRate',{rate:6});
 await x.evaluate(()=>{window.usageTasks=[];window.usageObserver=new PerformanceObserver(l=>l.getEntries().forEach(e=>usageTasks.push(e.duration)));usageObserver.observe({entryTypes:['longtask']});});
 for(const [id,stage] of [['ar-ball-actions','word'],['en-notice-and-explain','sentence'],['ar-first-next-last','meaning'],['en-polite-words','compose']]){await x.evaluate(([id,stage])=>APP360_STORY.open(id,stage),[id,stage]);await click(x,'guide',stage);}
 const lag=await x.evaluate(()=>new Promise(resolve=>{const t=performance.now();setTimeout(()=>resolve(performance.now()-t),50);}));assert.ok(lag<800,'timer delay '+lag);
 const tasks=await x.evaluate(()=>usageTasks);metrics.usage={cpuSlowdown:6,timerDelayMs:Math.round(lag),longTasks:tasks.length,maxLongTaskMs:Math.round(Math.max(0,...tasks))};console.log('USAGE '+JSON.stringify(metrics.usage));await cdp.send('Emulation.setCPUThrottlingRate',{rate:1});
});await expanded.close();
const install=await browser.newContext();const portal=await install.newPage();await portal.goto(base);await portal.waitForFunction(()=>window.APP360_FAMILY_SYNC&&APP360_FAMILY_SYNC.apps.some(a=>a.id==='a4-story-language'));await portal.locator('#a360GlobalName').fill('تثبيت');await portal.locator('#a360GlobalAge').selectOption('4-8');await portal.locator('[data-prof-save]').click();
await test('Portal service-worker installation and update cannot return a running lesson to homepage',async()=>{
 await delay(500);await portal.locator('#showcaseTrack [data-app="a4-story-language"] .showcase-cover-img').click({force:true});const f=portal.frameLocator('#app360FamilyShellFrame');await f.locator('[data-do="open"][data-value="ar-first-next-last"]').first().click();
 await portal.waitForFunction(()=>!!navigator.serviceWorker.controller);await delay(700);assert.equal(await portal.evaluate(()=>APP360_FAMILY_SHELL.getActiveApp().id),'a4-story-language');
 await portal.evaluate(()=>navigator.serviceWorker.dispatchEvent(new Event('controllerchange')));await delay(400);assert.equal(await portal.evaluate(()=>APP360_FAMILY_SHELL.getActiveApp().id),'a4-story-language');assert.ok(await f.locator('[data-do="play-scene"]').first().isVisible());
});await install.close();
fs.writeFileSync(qaDir+'/results.json',JSON.stringify({passed:results.length,checks:results,metrics,pageErrors:errors},null,2));console.log('TOTAL '+results.length);
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();server.kill()});
