'use strict';const test=require('node:test'),A=require('node:assert/strict'),fs=require('fs'),path=require('path'),M=require('../src/model.js'),D=require('../data/stories.json'),root=path.resolve(__dirname,'..');
test('complete draft survives restart with order, word, ending, caption and assistance',()=>{const s=M.blank(),st=D.stories[0],d=M.ensureDraft(s,st);s.active=st.id;s.page='compose';M.move(d.scene_order,0,1);d.grapheme_sequence=[0,1];d.ending='نهاية من عندي';d.captions['cup-1']='تعليق';d.assistance_level='hint';M.note(d,'blend-described','كوب');const r=M.restore(JSON.stringify(s),D);for(const k of ['scene_order','grapheme_sequence','ending','assistance_level','attempt_history'])A.deepEqual(r.drafts[st.id][k],d[k]);A.equal(r.drafts[st.id].captions['cup-1'],'تعليق');A.equal(r.page,'compose')});
test('marked Arabic chunks join correctly; English stays separate',()=>{for(const w of Object.values(D.words)){A.equal(M.letters(M.assembled({grapheme_sequence:w.units.map((x,i)=>i)},w)),M.letters(w.text));A.equal(w.units.length,w.unit_audio.length);if(w.language==='en')A(!/[\u0600-\u06ff]/.test(w.text+w.units.join('')))}});
test('export excludes recording, identity, private logs; import rejects external assets and another app',()=>{const d=M.draft(D.stories[0],'entry');d.recording_ref_optional='private-voice';M.note(d,'opened','private-detail');const a=M.artifact(d,'private-profile',D),out=M.exportData([a],D);for(const v of ['private-voice','private-profile','profile_ref','attempt_history','recording_ref_optional'])A(!JSON.stringify(out).includes(v));A.equal(M.importData(out,D)[0].scenes.length,3);out.stories[0].scenes=['https://example.com/a.png','cup-1'];A.throws(()=>M.importData(out,D));A.throws(()=>M.importData({schema_version:1,app_id:'other',stories:[]},D))});
test('custom template identity is stable across restores and original remains untouched',()=>{const s=M.blank(),source=D.stories[0],before=JSON.stringify(source),c=M.copy(source);c.id='custom-test';c.source_id=source.id;c.title='My template';s.custom.push(c);M.ensureDraft(s,c);const r=M.restore(JSON.stringify(M.restore(JSON.stringify(s),D)),D);A.equal(r.custom[0].id,c.id);A(r.drafts[c.id]);A.equal(JSON.stringify(source),before)});
test('corrupt storage is reported and invalid order/sound indices repaired',()=>{A.throws(()=>M.restore('{broken',D));const s=M.blank(),d=M.ensureDraft(s,D.stories[0]);d.scene_order=['cat-0','cat-1'];d.grapheme_sequence=[0,0,.5,1,99];const r=M.restore(JSON.stringify(s),D).drafts['ar-cup'];A.deepEqual(r.scene_order,D.stories[0].scenes.slice().reverse());A.deepEqual(r.grapheme_sequence,[0,1])});
test('all local narration, guides, words and sentence assets exist in the atomic offline pack',()=>{const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8'),files=new Set();for(const s of Object.values(D.scenes)){files.add(s.sheet);Object.values(s.audio).forEach(x=>files.add(x))}D.stories.forEach(s=>files.add(s.question_audio));for(const w of Object.values(D.words))[w.image,w.audio,w.phrase_audio,w.transfer_audio,...w.unit_audio].forEach(x=>files.add(x));for(const rel of files){A(fs.existsSync(path.resolve(root,rel)),rel);A(sw.includes(JSON.stringify(rel)),rel)}const manifest=JSON.parse(fs.readFileSync(path.join(root,'data/audio-manifest.json'),'utf8'));A.equal(fs.readdirSync(path.join(root,'audio')).length,manifest.items.length);for(const clip of manifest.items){A(fs.existsSync(path.join(root,clip.path)),clip.path);A(sw.includes(JSON.stringify(clip.path)),clip.path)}A(sw.indexOf('return cacheCore(c).then')<sw.indexOf("c.put('./offline-ready.json'"))});
test('button reordering respects boundaries and rejects invalid moves',()=>{const a=['one','two','three'];A(M.move(a,1,-1));A.deepEqual(a,['two','one','three']);for(const [i,d]of [[0,-1],[1.2,1],[99,-1],[0,NaN]])A.equal(M.move(a,i,d),false)});
test('readiness changes task scene complexity and retains personal authorship',()=>{const st=D.stories[0],d=M.draft(st,'extend');A.equal(M.draft(st,'entry').practice_scenes.length,3);A.equal(d.practice_scenes.length,4);d.ending='My ending';const s=M.blank();s.drafts[st.id]=d;const r=M.restore(JSON.stringify(s),D).drafts[st.id];A.deepEqual(r.practice_scenes,d.practice_scenes);A.equal(r.ending,d.ending)});
test('malformed optional histories and templates cannot crash rendering',()=>{const s=M.blank(),d=M.ensureDraft(s,D.stories[0]);s.custom=[null,4];d.attempt_history=[null,{action:42,detail:{x:1},support:'unknown',at:'bad'}];const r=M.restore(JSON.stringify(s),D);A.equal(r.custom.length,0);A.deepEqual(r.drafts['ar-cup'].attempt_history,[{action:'',detail:'',support:'together',at:0}])});

test('three age suggestions stay open and have different learning paths',()=>{A.equal(D.levels.length,3);A.equal(M.levelForAge(4),'entry');A.equal(M.levelForAge(5),'practice');A.equal(M.levelForAge(6),'extend');A.equal(M.levelForAge(8),'extend');A(!M.level(D,'entry').steps.includes('word'));A(M.level(D,'practice').steps.includes('sentence'));A.equal(M.level(D,'extend').compose_max,5)});
test('sentence progress, transfer word and age restore without exposing age in exports',()=>{const s=M.blank(),st=D.stories[2],d=M.ensureDraft(s,st);d.readiness_track='extend';d.sentence_sequences.extend=st.sentences.extend.units.map((x,i)=>i);d.transfer_mode=true;d.transfer_graphemes=[0,1];d.order_picks=d.practice_scenes.slice();s.learner_age=7;s.progress.extend=[st.id];s.voice_guidance=false;const r=M.restore(JSON.stringify(s),D);A.equal(r.learner_age,7);A.equal(r.voice_guidance,false);A.equal(M.wordFor(D,st,r.drafts[st.id]).text,D.words[st.word].transfer);A.deepEqual(r.drafts[st.id].order_picks,d.order_picks);A.equal(M.sentenceText(r.drafts[st.id],st),st.sentences.extend.units.join(' '));const out=M.exportData([M.artifact(d,'profile',D)],D);A(out.stories[0].sentence_text);A(!JSON.stringify(out).includes('learner_age'))});
test('sentence indices are bounded, unique and survive repeated-token content',()=>{const s=M.blank(),st=D.stories[0],d=M.ensureDraft(s,st);d.sentence_sequences.practice=[0,0,-1,2.5,99,1];d.order_picks=['cup-0','cup-0','cat-0'];d.transfer_graphemes=[0,0,99,1];const r=M.restore(JSON.stringify(s),D).drafts[st.id];A.deepEqual(r.sentence_sequences.practice,[0,1]);A.deepEqual(r.order_picks,['cup-0']);A.deepEqual(r.transfer_graphemes,[0,1])});
test('sentence and alternate ending assets match library scenes and language',()=>{for(const st of D.stories){for(const se of Object.values(st.sentences)){A(D.scenes[se.scene]);A.equal(se.units.length,se.unit_audio.length);A.equal(se.text.replace(/\.$/,''),se.units.join(' '));if(st.language==='en')A(!/[\u0600-\u06ff]/.test(se.text))}for(const e of st.endings){A(D.scenes[e.scene]);A(fs.existsSync(path.join(root,e.audio)))}}});
test('library retains earlier stories and adds ten recommended stories per level in each language',()=>{
 for(const lang of ['ar','en'])for(const track of ['entry','practice','extend'])A.equal(D.stories.filter(s=>s.language===lang&&s.track===track).length,14);
 for(const st of D.stories){A(D.words[st.word]);A.equal(D.words[st.word].language,st.language);for(const track of ['entry','practice','extend']){const d=M.draft(st,track);A(d.practice_scenes.every(id=>D.scenes[id]));A.equal(d.compose.length,Math.min(track==='entry'?3:4,d.practice_scenes.length));}}
 A.equal(new Set(Object.values(D.scenes).map(s=>s.sheet)).size,14);
 A.equal(D.stories.find(s=>s.id==='ar-in-and-out').sentences.extend.scene,'in-and-out-2');
 A.equal(D.stories.find(s=>s.id==='en-ball-actions').sentences.extend.scene,'ball-actions-3');
 A.equal(D.stories.find(s=>s.id==='ar-look-for-clues').sentences.practice.scene,'look-for-clues-1');
});

test('thirty new concepts have bilingual journeys, varied picture answers and graded sentences',()=>{
 const added=D.stories.filter(s=>s.collection==='new-worlds-4');A.equal(added.length,60);
 for(const lang of ['ar','en'])for(const track of ['entry','practice','extend']){
  const rows=added.filter(s=>s.language===lang&&s.track===track);A.equal(rows.length,10);A.equal(new Set(rows.map(s=>s.world)).size,10);A.equal(new Set(rows.map(s=>s.title)).size,10);
  A.deepEqual(new Set(rows.map(s=>s.meaning)),new Set([0,1]));
  for(const st of rows){A.equal(st.scenes.length,4);A(st.scenes.includes(st.choices[st.meaning].scene));A.equal(st.sentences.practice.units.length,3);A.equal(st.sentences.extend.units.length,5);A.equal(st.endings.length,2);A.equal(D.words[st.word].language,lang)}
 }
 for(const w of Object.values(D.words)){A.equal(M.letters(w.transfer_units.join('')),M.letters(w.transfer));A.equal(w.transfer_units.length,w.transfer_unit_audio.length);if(w.support_scene)A(D.scenes[w.support_scene])}
});
test('nonuniform illustration panels keep all crop frames within their source sheet',()=>{
 for(const scene of Object.values(D.scenes))if(scene.frame){const [x,y,width,height]=scene.frame;A(x>=0&&y>=0&&width>0&&height>0);A(x+width<=1.000001&&y+height<=1.000001)}
 A(D.scenes['v4-rain-entry-0'].frame[3]<.5);A(D.scenes['v4-picnic-extend-2'].frame[1]<.5);
});
