(function(w){'use strict';
var pool={},queue=[],inFlight=0,ctx=null,currentSource=null,currentAudio=null,serial=0,currentPath='',listener=null,stats={plays:0,lastStartMs:null,path:''};
function now(){return w.performance&&w.performance.now?w.performance.now():Date.now()}
function emit(state,path){if(listener)listener(state,path)}
function item(path){if(!pool[path])pool[path]={path:path,state:'idle',callbacks:[],data:null,buffer:null,url:'',media:null,touched:Date.now(),decoding:false};pool[path].touched=Date.now();return pool[path]}
function prune(){var keys=Object.keys(pool);if(keys.length<=24)return;keys.sort(function(a,b){return pool[a].touched-pool[b].touched});for(var i=0;i<keys.length-24;i++){var p=pool[keys[i]];if(!p||p.path===currentPath||p.state==='loading'||p.decoding)continue;if(p.url)try{URL.revokeObjectURL(p.url)}catch(e){}if(p.media){p.media.pause();p.media.src=''}delete pool[p.path]}}
function decoded(p,done){if(p.buffer){done(true);return}if(!ctx||!p.data||p.decoding){done(false);return}p.decoding=true;try{var bytes=p.data.slice?p.data.slice(0):p.data;ctx.decodeAudioData(bytes,function(b){p.buffer=b;p.decoding=false;done(true);prune()},function(){p.decoding=false;done(false)})}catch(e){p.decoding=false;done(false)}}
function unlock(){try{if(!ctx){var C=w.AudioContext||w.webkitAudioContext;if(C)ctx=new C()}if(ctx&&ctx.resume){var p=ctx.resume();if(p&&p.catch)p.catch(function(){})}}catch(e){ctx=null}}
function pump(){while(inFlight<2&&queue.length){var p=queue.shift();if(p.state!=='queued')continue;inFlight++;p.state='loading';(function(p){var req;function finish(ok){inFlight--;p.state=ok?'ready':'failed';var callbacks=p.callbacks.slice();p.callbacks=[];callbacks.forEach(function(cb){cb(ok)});prune();pump()}try{req=new XMLHttpRequest();req.open('GET',p.path,true);req.responseType='arraybuffer';req.timeout=12000;req.onload=function(){if(req.status>=200&&req.status<300&&req.response&&req.response.byteLength){p.data=req.response;finish(true)}else finish(false)};req.onerror=req.ontimeout=function(){finish(false)};req.send()}catch(e){finish(false)}})(p)}}
function get(p,cb,priority){if(p.state==='ready'){cb(true);return}p.callbacks.push(cb);if(p.state==='idle'||p.state==='failed'){p.state='queued';if(priority)queue.unshift(p);else queue.push(p)}else if(priority&&p.state==='queued'){var index=queue.indexOf(p);if(index>=0)queue.splice(index,1);queue.unshift(p)}pump()}
function warm(paths){var wanted=paths.slice(0,12);queue=queue.filter(function(p){if(wanted.indexOf(p.path)>=0||p.path===currentPath)return true;p.state='idle';p.callbacks=[];return false});wanted.forEach(function(path){if(!path||path.indexOf('blob:')===0)return;var p=item(path);get(p,function(ok){if(ok&&ctx)decoded(p,function(){})})})}
function stop(){serial++;if(currentSource){try{currentSource.onended=null;currentSource.stop(0);currentSource.disconnect()}catch(e){}currentSource=null}if(currentAudio){currentAudio.onended=currentAudio.onplaying=currentAudio.onerror=null;try{currentAudio.pause();currentAudio.currentTime=0}catch(e){}currentAudio=null}currentPath='';emit('idle','')}
function fallback(p,n,began,end,error){var a=p.media;if(!a){a=new Audio();a.preload='auto';p.media=a;if(p.data&&p.data.byteLength&&w.Blob&&w.URL&&URL.createObjectURL)try{p.url=URL.createObjectURL(new Blob([p.data],{type:'audio/mpeg'}))}catch(e){}a.src=p.url||p.path}currentAudio=a;try{a.currentTime=0}catch(e){}a.onplaying=function(){if(n!==serial)return;stats.lastStartMs=Math.round(now()-began);stats.plays++;stats.path=p.path;emit('playing',p.path)};a.onended=function(){if(n!==serial)return;currentAudio=null;currentPath='';emit('idle','');if(end)end()};a.onerror=function(){if(n!==serial)return;emit('error',p.path);if(error)error()};try{var promise=a.play();if(promise&&promise.catch)promise.catch(function(){if(n===serial){emit('error',p.path);if(error)error()}})}catch(e){if(n===serial){emit('error',p.path);if(error)error()}}}
function play(path,end,error){stop();unlock();var n=serial,began=now(),p=path.indexOf('blob:')===0?{path:path}:item(path);currentPath=path;emit('waiting',path);function start(){if(n!==serial)return;decoded(p,function(ok){if(n!==serial)return;if(ok&&ctx){try{var source=ctx.createBufferSource();source.buffer=p.buffer;source.connect(ctx.destination);source.onended=function(){if(n!==serial)return;currentSource=null;currentPath='';emit('idle','');if(end)end()};currentSource=source;if(source.start)source.start(0);else source.noteOn(0);stats.lastStartMs=Math.round(now()-began);stats.plays++;stats.path=path;emit('playing',path);return}catch(e){}}fallback(p,n,began,end,error)})}if(path.indexOf('blob:')===0){fallback(p,n,began,end,error);return}get(p,function(){start()},true)}
w.APP360_STORY_AUDIO={play:play,stop:stop,warm:warm,unlock:unlock,onState:function(fn){listener=fn},debug:function(){return{plays:stats.plays,lastStartMs:stats.lastStartMs,path:stats.path,cached:Object.keys(pool).length,context:ctx?ctx.state||'running':'html-audio',active:currentPath}}};
})(window);
