(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.STORY_MODEL=factory()})(this,function(){'use strict';
function copy(v){return JSON.parse(JSON.stringify(v))}function text(v,max){return typeof v==='string'?v.slice(0,max||500):''}function own(o,k){return Object.prototype.hasOwnProperty.call(o,k)}function history(v){return Array.isArray(v)?v.filter(function(n){return n&&typeof n==='object'}).slice(-40).map(function(n){return{action:text(n.action,50),detail:text(n.detail,100),support:['together','hint','independent'].indexOf(n.support)>=0?n.support:'together',at:typeof n.at==='number'?n.at:0}}):[]}
function blank(){return{schema_version:1,language:'ar',track:'entry',assistance:'together',page:'library',active:'',drafts:{},saved:[],custom:[]}}
function findStory(data,state,id){var all=data.stories.concat(state.custom);for(var i=0;i<all.length;i++)if(all[i].id===id)return all[i];return null}
function taskScenes(story,track){var a=story.scenes.slice(0,3);if(track==='extend'&&a.indexOf(story.optional_scene)<0)a.push(story.optional_scene);return a}
function draft(story,track){var scenes=taskScenes(story,track||story.track);return{story_id:story.id,language:story.language,readiness_track:track||story.track,status:'ready',listen_index:0,practice_scenes:scenes,scene_order:scenes.slice().reverse(),meaning_choice:null,grapheme_sequence:[],decoded_word:'',compose:scenes.slice(),captions:{},title:story.title,ending:'',reflection:'',attempt_history:[],assistance_level:'together',recording_ref_optional:''}}
function ensureDraft(state,story){if(!own(state.drafts,story.id))state.drafts[story.id]=draft(story,state.track);return state.drafts[story.id]}
function move(array,index,delta){index=Number(index);delta=Number(delta);var dest=index+delta;if(!isFinite(index)||!isFinite(delta)||Math.floor(index)!==index||Math.floor(delta)!==delta||index<0||dest<0||index>=array.length||dest>=array.length)return false;var v=array[index];array[index]=array[dest];array[dest]=v;return true}
function note(d,action,detail){d.attempt_history.push({action:action,detail:text(detail,100),support:d.assistance_level,at:Date.now()});if(d.attempt_history.length>40)d.attempt_history.shift()}
function letters(v){return String(v||'').replace(/[\u064b-\u065f\u0670\u0640]/g,'').toLowerCase()}
function assembled(d,w){return d.grapheme_sequence.map(function(n){return w.units[n]||''}).join('')}
function validScenes(list,data,min){return Array.isArray(list)&&list.length>=(min||2)&&list.length<=5&&list.every(function(id){return typeof id==='string'&&own(data.scenes,id)})}
function normalize(a,data){if(!a||!validScenes(a.scenes,data)||(a.language!=='ar'&&a.language!=='en'))throw Error('invalid-story');var caps={};a.scenes.forEach(function(id){caps[id]=text(a.captions&&a.captions[id],500)});return{id:text(a.id,100),story_id:text(a.story_id,100),language:a.language,title:text(a.title,100)||'My story',scenes:a.scenes.slice(),captions:caps,ending:text(a.ending,1000),reflection:text(a.reflection,500),readiness_track:['entry','practice','extend'].indexOf(a.readiness_track)>=0?a.readiness_track:'entry',assistance_level:['together','hint','independent'].indexOf(a.assistance_level)>=0?a.assistance_level:'together',decoded_word:text(a.decoded_word,50),meaning_choice:typeof a.meaning_choice==='number'?a.meaning_choice:null,saved_at:typeof a.saved_at==='number'?a.saved_at:Date.now()}}
function artifact(d,profile,data){var a=normalize({id:'story-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),story_id:d.story_id,language:d.language,title:d.title,scenes:d.compose,captions:d.captions,ending:d.ending,reflection:d.reflection,readiness_track:d.readiness_track,assistance_level:d.assistance_level,decoded_word:d.decoded_word,meaning_choice:d.meaning_choice,saved_at:Date.now()},data);a.profile_ref=profile;a.attempt_history=history(d.attempt_history);a.recording_ref_optional=d.recording_ref_optional||'';return a}
function exportData(saved,data){return{app_id:'a4-story-language',schema_version:1,media_included:false,stories:saved.map(function(a){return normalize(a,data)})}}
function importData(p,data){if(!p||p.app_id!=='a4-story-language'||p.schema_version!==1||!Array.isArray(p.stories)||p.stories.length>50)throw Error('invalid-package');return p.stories.map(function(a){return normalize(a,data)})}
function restore(raw,data){var s=blank(),src,k,i,st,sd,d;if(!raw)return s;try{src=JSON.parse(raw)}catch(e){throw Error('corrupt-storage')}if(!src||src.schema_version!==1)throw Error('unknown-schema');if(src.language==='en')s.language='en';if(['entry','practice','extend'].indexOf(src.track)>=0)s.track=src.track;if(['together','hint','independent'].indexOf(src.assistance)>=0)s.assistance=src.assistance;
if(Array.isArray(src.custom))src.custom.slice(0,20).forEach(function(c){if(!c||typeof c!=='object')return;var source=data.stories.filter(function(x){return x.id===c.source_id})[0];if(!source||source.language!==c.language||text(c.id,80).indexOf('custom-')!==0)return;var a=copy(source);a.id=text(c.id,80).replace(/[^a-z0-9_-]/gi,'');a.source_id=source.id;a.title=text(c.title,100)||source.title;a.coach_tip=text(c.coach_tip,500)||source.coach_tip;s.custom.push(a)});
if(Array.isArray(src.saved))src.saved.slice(0,50).forEach(function(a){try{var n=normalize(a,data);n.recording_ref_optional=text(a.recording_ref_optional,200);n.profile_ref=text(a.profile_ref,200);n.attempt_history=history(a.attempt_history);s.saved.push(n)}catch(e){}});
if(src.drafts&&typeof src.drafts==='object')for(k in src.drafts){if(!own(src.drafts,k))continue;st=findStory(data,s,k);if(!st)continue;sd=src.drafts[k]||{};d=draft(st,sd.readiness_track||s.track);if(validScenes(sd.practice_scenes,data)&&sd.practice_scenes.every(function(id){return st.scenes.indexOf(id)>=0||id===st.optional_scene}))d.practice_scenes=sd.practice_scenes.slice();if(validScenes(sd.scene_order,data)&&sd.scene_order.slice().sort().join('|')===d.practice_scenes.slice().sort().join('|'))d.scene_order=sd.scene_order.slice();if(validScenes(sd.compose,data))d.compose=sd.compose.slice();d.title=text(sd.title,100)||st.title;d.ending=text(sd.ending,1000);d.reflection=text(sd.reflection,500);d.recording_ref_optional=text(sd.recording_ref_optional,200);if(['together','hint','independent'].indexOf(sd.assistance_level)>=0)d.assistance_level=sd.assistance_level;if(['ready','in_progress','paused','needs_help','review','saved'].indexOf(sd.status)>=0)d.status=sd.status;d.listen_index=Math.max(0,Math.min(d.practice_scenes.length-1,Number(sd.listen_index)||0));d.meaning_choice=typeof sd.meaning_choice==='number'&&sd.meaning_choice>=0&&sd.meaning_choice<st.choices.length?sd.meaning_choice:null;d.compose.forEach(function(id){d.captions[id]=text(sd.captions&&sd.captions[id],500)});var wd=data.words[st.word];if(wd&&Array.isArray(sd.grapheme_sequence))d.grapheme_sequence=sd.grapheme_sequence.filter(function(n,j,a){return typeof n==='number'&&Math.floor(n)===n&&n>=0&&n<wd.units.length&&a.indexOf(n)===j});d.decoded_word=text(sd.decoded_word,50);d.attempt_history=history(sd.attempt_history);s.drafts[k]=d}
if(findStory(data,s,src.active)){s.active=src.active;s.page=['listen','order','meaning','word','compose','review'].indexOf(src.page)>=0?src.page:'library'}return s}
return{blank:blank,copy:copy,text:text,findStory:findStory,taskScenes:taskScenes,draft:draft,ensureDraft:ensureDraft,move:move,note:note,letters:letters,assembled:assembled,validScenes:validScenes,artifact:artifact,exportData:exportData,importData:importData,restore:restore};});
