const fs=require('fs'),http=require('http'),path=require('path'),assert=require('node:assert/strict');let chromium;try{chromium=require('playwright').chromium;}catch(e){chromium=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright').chromium;}const root=path.resolve(__dirname,'../../../..'),D=require(root+'/apps/4-8/command-path-lab/data/content.json'),M=require(root+'/apps/4-8/command-path-lab/src/model.js');
(async()=>{const server=http.createServer((q,r)=>{let f=path.join(root,new URL(q.url,'http://localhost').pathname);try{if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');r.setHeader('Content-Type',({'.js':'text/javascript','.html':'text/html','.json':'application/json','.css':'text/css','.mp3':'audio/mpeg','.svg':'image/svg+xml','.jpg':'image/jpeg','.png':'image/png'})[path.extname(f)]||'application/octet-stream');r.end(fs.readFileSync(f));}catch(e){r.writeHead(404);r.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port+'/apps/4-8/command-path-lab/index.html',browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu'],headless:true});try{const p=await browser.newPage({viewport:{width:360,height:640},serviceWorkers:'block'}),errs=[];p.on('pageerror',e=>errs.push(e.message));await p.goto(url);await p.waitForFunction(()=>window.APP360_COMMAND);const click=(k,v)=>p.locator('[data-do="'+k+'"]'+(v!==undefined?'[data-value="'+v+'"]':'')).first().click();await click('sound');
for(const m of D.maps){await p.evaluate(id=>APP360_COMMAND.open(id),m.id);await click('clear-tape');for(const c of M.solve(m)){await click('add',c.op);await p.waitForFunction(()=>!APP360_COMMAND.debug().busy&&!APP360_COMMAND.debug().running);}for(const c of M.solve(m))await click('step');assert.equal(await p.evaluate(()=>APP360_COMMAND.snapshot().draft.result.status),'arrived',m.id);}
console.log('PASS 36 UI routes');await click('save-route');const saved=await p.evaluate(()=>APP360_COMMAND.snapshot().saved);await click('library');await click('demo');await click('step');await click('return-demo');assert.deepEqual(await p.evaluate(()=>APP360_COMMAND.snapshot().saved),saved);console.log('PASS independent demo');
await p.evaluate(()=>APP360_COMMAND.open('entry-book'));await click('add','n');await p.waitForFunction(()=>!APP360_COMMAND.debug().busy&&!APP360_COMMAND.debug().running);await click('select','1');await click('replace-help');await click('add','e');await click('add','e');await click('step');await click('step');assert.equal(await p.evaluate(()=>APP360_COMMAND.snapshot().draft.result.status),'arrived');console.log('PASS edit correction');
await click('designer');await p.locator('#mapAr').fill('');await p.reload();await p.waitForFunction(()=>APP360_COMMAND);assert.equal(await p.evaluate(()=>APP360_COMMAND.debug().corrupt),false);await click('store-map');assert.equal(await p.evaluate(()=>APP360_COMMAND.snapshot().maps.length),1);console.log('PASS custom map, blank title reload');
for(const size of [[360,640],[412,915],[768,1024],[1024,768],[1366,768]]){await p.setViewportSize({width:size[0],height:size[1]});await p.evaluate(()=>APP360_COMMAND.open(COMMAND_CONTENT.maps[30].id));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,size.join('x'));const cells=await p.locator('button.cell').evaluateAll(xs=>xs.map(x=>({w:x.getBoundingClientRect().width,h:x.getBoundingClientRect().height})));assert.ok(cells.every(x=>x.w>=48&&x.h>=48),JSON.stringify({size,cells}));await click('language');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await click('language');}console.log('PASS five sizes AR/EN, 48px tiles, rotation');
await p.setViewportSize({width:768,height:1024});await p.screenshot({path:process.env.COMMAND_SCREENSHOT||'/tmp/command-tablet.png',fullPage:true});assert.deepEqual(errs,[]);
// Motion begins with recorded narration; pausing retains the displayed step.
await p.evaluate(()=>APP360_COMMAND.open('build-0'));await click('clear-tape');await click('add','f');await click('add','r');await click('group');await p.waitForFunction(()=>!APP360_COMMAND.debug().busy&&!APP360_COMMAND.debug().running);assert.equal(await p.evaluate(()=>APP360_COMMAND.snapshot().draft.commands[0].op),'repeat');await click('step');assert.equal(await p.evaluate(()=>APP360_COMMAND.snapshot().draft.cursor),1);await click('step');assert.equal(await p.evaluate(()=>APP360_COMMAND.snapshot().draft.cursor),2);await click('step');await click('step');assert.equal(await p.evaluate(()=>APP360_COMMAND.snapshot().draft.result.trace.length),4);await click('select','0');await click('ungroup');assert.equal(await p.evaluate(()=>APP360_COMMAND.snapshot().draft.commands.length),4);console.log('PASS repeat group UI and expanded cursor');
await p.evaluate(()=>APP360_COMMAND.open('build-0'));await click('clear-tape');for(let i=0;i<5;i++)await click('add','if');for(let i=0;i<5;i++)await click('step');assert.equal(await p.evaluate(()=>APP360_COMMAND.snapshot().draft.result.trace[4].effective),'r');console.log('PASS conditional UI changes at edge');
await p.evaluate(()=>APP360_COMMAND.open('entry-book'));await click('add','e');await click('add','e');await click('sound');await click('replay');await p.waitForFunction(()=>APP360_COMMAND.audio().state==='playing');assert.equal(await p.evaluate(()=>APP360_COMMAND.snapshot().draft.cursor),1);await click('pause');await new Promise(r=>setTimeout(r,3500));assert.equal(await p.evaluate(()=>APP360_COMMAND.snapshot().draft.cursor),1);await click('step');await p.waitForFunction(()=>!APP360_COMMAND.debug().busy,null,{timeout:12000});await p.waitForFunction(()=>APP360_COMMAND.snapshot().draft.phase==='review',null,{timeout:12000});assert.equal(await p.evaluate(()=>APP360_COMMAND.snapshot().draft.result.status),'arrived');console.log('PASS actual narration, pause cancellation, resume step');
await p.evaluate(()=>window.print=function(){});await click('print');assert.equal(await p.locator('#printCard .board').count(),1);await p.locator('details').last().locator('summary').click();await click('export-current');const exported=JSON.parse(await p.locator('.output textarea').inputValue());assert.equal(exported.draft.commands.length,2);assert.equal(exported.draft.profile_ref,undefined);await click('close-output');await click('sound');console.log('PASS print and export model');
const offline=await browser.newContext({viewport:{width:412,height:915}}),op=await offline.newPage();await op.goto(url);await op.waitForFunction(()=>window.APP360_COMMAND);await op.waitForFunction(async()=>{const ks=await caches.keys();for(const k of ks)if(k.startsWith('a4-command-path-')&&await(await caches.open(k)).match(new URL('offline-ready.json',location.href)))return true;return false;},{timeout:60000});await op.waitForFunction(()=>navigator.serviceWorker.controller);await offline.setOffline(true);await op.reload();await op.waitForFunction(()=>APP360_COMMAND);assert.equal(await op.evaluate(()=>COMMAND_CONTENT.maps.length),36);const aud=await op.evaluate(async()=>{const a=new Audio('audio/en-goal-book.mp3');await new Promise((res,rej)=>{a.onloadedmetadata=res;a.onerror=rej;});return a.duration;});assert.ok(aud>0);const images=await op.locator('.goal-photo').evaluateAll(xs=>xs.every(x=>x.complete&&x.naturalWidth>0));assert.ok(images);console.log('PASS offline reload, images and real audio metadata');await offline.close();
const blocked=await browser.newContext({serviceWorkers:'block'});await blocked.addInitScript(()=>{Storage.prototype.setItem=function(){throw Error('denied');};});const bp=await blocked.newPage();await bp.goto(url);await bp.waitForFunction(()=>APP360_COMMAND);await bp.evaluate(()=>APP360_COMMAND.open('entry-book'));assert.equal(await bp.evaluate(()=>APP360_COMMAND.debug().storageOK),false);assert.equal(await bp.evaluate(()=>APP360_COMMAND.snapshot().draft.map.id),'entry-book');console.log('PASS storage refusal');await blocked.close();
const corruptCtx=await browser.newContext({serviceWorkers:'block'});await corruptCtx.addInitScript(()=>localStorage.setItem('app360:a4-command-path:schema-1:local-guest','{broken'));const cp=await corruptCtx.newPage();await cp.goto(url);await cp.waitForFunction(()=>APP360_COMMAND);assert.equal(await cp.evaluate(()=>APP360_COMMAND.debug().corrupt),true);await cp.evaluate(()=>APP360_COMMAND.open('entry-book'));assert.equal(await cp.evaluate(()=>localStorage.getItem('app360:a4-command-path:schema-1:local-guest')),'{broken');await corruptCtx.close();console.log('PASS corrupt original preservation');
const launch=await browser.newPage({serviceWorkers:'block'});await launch.goto(url.replace('index.html','launch.html?action=item&id=turn-3'));await launch.waitForFunction(()=>{const f=document.querySelector('iframe');return f&&f.contentWindow.APP360_COMMAND&&f.contentWindow.APP360_COMMAND.snapshot().draft;});assert.equal(await launch.evaluate(()=>document.querySelector('iframe').contentWindow.APP360_COMMAND.snapshot().draft.map.id),'turn-3');await launch.close();console.log('PASS launch exact map');
await p.evaluate(()=>{window.qaProfile='qa-one';window.APP360_FAMILY_SYNC={getProfileKey:()=>window.qaProfile,getSession:()=>({room:'qa',role:'guest'}),getReadingFocusState:()=>({enabled:false,canManage:false})};document.dispatchEvent(new Event('app360:namechange'));});assert.equal(await p.evaluate(()=>APP360_COMMAND.debug().profile),'qa-one');await p.evaluate(()=>APP360_COMMAND.open('entry-book'));await p.evaluate(()=>{window.qaProfile='qa-two';document.dispatchEvent(new Event('app360:namechange'));});assert.equal(await p.evaluate(()=>APP360_COMMAND.snapshot().draft),null);await p.evaluate(()=>{window.qaProfile='qa-one';document.dispatchEvent(new Event('app360:namechange'));});assert.equal(await p.evaluate(()=>APP360_COMMAND.snapshot().draft.map.id),'entry-book');await click('coach');assert.equal(await p.locator('#privateNote').count(),0);assert.equal(await p.evaluate(()=>APP360_COMMAND.audio().focus),false);console.log('PASS profile isolation, guest coach gate, family reading focus');

}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
