const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');const base=path.resolve(__dirname,'..'),M=require('../src/model.js'),D=require('../data/content.json');
assert.equal(D.maps.length,36);for(const m of D.maps){assert.equal(M.execute(m,M.solve(m)).status,'arrived',m.id);for(const c of m.starter)M.program([c],m.mode,m.level);}
const m={id:'test',size:3,start:{x:0,y:2,dir:0},goal:{x:2,y:0},walls:[],title:{ar:'خريطة',en:'Map'},mode:'relative',level:3,goal_asset:'book'};
let r=M.execute(m,[{op:'r'}]);assert.deepEqual(r.position,{x:0,y:2,dir:1});assert.equal(r.trace[0].from.x,r.trace[0].to.x);
r=M.execute(m,[{op:'repeat',count:2,body:[{op:'f'}]},{op:'r'},{op:'repeat',count:2,body:[{op:'f'}]}]);assert.equal(r.status,'arrived');assert.equal(r.trace.length,5);assert.equal(r.trace[1].index,0);assert.equal(r.trace[1].iteration,1);
r=M.execute({...m,start:{x:0,y:0,dir:0}},[{op:'if'},{op:'if'}]);assert.equal(r.trace[0].effective,'r');assert.equal(r.trace[1].effective,'f');
r=M.execute(m,[{op:'l'},{op:'f'}]);assert.equal(r.status,'blocked');assert.equal(r.debug_index,1);
assert.throws(()=>M.program([{op:'repeat',count:2,body:[{op:'repeat',count:2,body:[{op:'f'}]}]}],'relative',3));assert.throws(()=>M.program([{op:'if'}],'relative',2));
const s=M.blank();s.note='private note';s.draft=M.start(m,'person-name');s.draft.commands=[{op:'f'}];s.saved=[M.artifact(s.draft)];s.draft.commands.push({op:'r'});assert.equal(s.saved[0].commands.length,1);const ex=M.exported(s);assert.equal(JSON.stringify(ex).includes('private note'),false);assert.equal(JSON.stringify(ex).includes('person-name'),false);const im=M.importData(ex,'another');assert.equal(im.saved[0].profile_ref,'another');assert.notEqual(im.saved[0].id,s.saved[0].id);assert.throws(()=>M.restore('{broken','profile'));
const am=require('../data/audio-manifest.json');assert.equal(am.items.length,298);for(const x of am.items)assert.ok(fs.statSync(path.join(base,x.path)).size>500);const cues=require('../data/read-along.json');assert.ok(cues);
const sw=fs.readFileSync(path.join(base,'sw.js'),'utf8');const core=JSON.parse(sw.match(/var CORE=(\[.*?\]);/)[1]);for(const p of core){assert.ok(fs.existsSync(path.resolve(base,p.split('?')[0])),p);}console.log('PASS 36 reachable maps; turns, repeats, conditions, collisions, immutable copies, private export, import ownership, invalid saves; 298 recordings; offline paths');
const C=require('../src/celebration.js'),registry=require('../../../../resources/early-child-name-audio/audio/registry.json');for(const name of ['محمد','مُحَمَّد','Mohammed','Noor','نور']){const e=C.match(registry,name);assert.ok(e,name);assert.ok(C.paths(C.clip(e)).length,name);}assert.equal(C.match(registry,'unknown learner'),null);assert.equal(C.match(registry,''),null);assert.deepEqual(C.paths({file:'https://evil.invalid/name.mp3'}),[]);const past=M.execute(m,[{op:'f'}]).trace,future=M.execute(m,[{op:'f'},{op:'r'}]).trace;assert.equal(M.observedPrefix(past,future),1);assert.equal(M.observedPrefix(past,M.execute(m,[{op:'r'}]).trace),0);assert.ok(C.google('Well done Sam','en').includes('tl=en&q=Well%20done%20Sam'));console.log('PASS recorded name aliases, safe asset paths, Google language, observed-prefix edit semantics');

for(const mode of ['absolute','relative']){const map=Object.assign({},D.maps[0],{mode:mode});assert.equal(M.touchMove(map,map.start,{x:2,y:1}).kind,'jump');assert.equal(M.touchMove(map,map.start,{x:0,y:0}).kind,'turn');assert.deepEqual(M.touchMove(map,map.start,{x:1,y:1}).commands,[{op:'f'}]);assert.deepEqual(M.directionCommands(map.start,0),[{op:'l'},{op:'f'}]);assert.deepEqual(M.execute(map,[{op:'r'},{op:'f'}]).position,{x:0,y:2,dir:2});}
console.log('PASS live touch constraints and turns in both command modes');
