(function(root,factory){var api=factory(typeof module==='object'&&module.exports?require('./model.js'):root.SHAPE_MODEL);if(typeof module==='object'&&module.exports)module.exports=api;else root.SHAPE_CHALLENGES=api})(this,function(M){'use strict';
var cards=[{id:'house',ar:'بيت بطريقتين',en:'A house, two ways',icon:'house'},{id:'wings',ar:'جناحان متناظران',en:'Matching wings',icon:'wings'},{id:'gap',ar:'أكمل الفراغ',en:'Fill the space',icon:'gap'},{id:'boat',ar:'صورة ثم قارب',en:'Build a boat',icon:'boat'},{id:'bridge',ar:'جسر بثلاث قطع',en:'A three-piece bridge',icon:'bridge'},{id:'rocket',ar:'صاروخي',en:'My rocket',icon:'rocket'},{id:'robot',ar:'روبوت الأشكال',en:'Shape robot',icon:'robot'},{id:'free',ar:'لغزي لصديقي',en:'A puzzle for a friend',icon:'free'}];
function get(id){for(var i=0;i<cards.length;i++)if(cards[i].id===id)return cards[i];return null}
function rows(id,v){var y=v%2,x=v===2?0:1;if(id==='house')return[['triangle',1,1+y,2],['triangle',3,1+y,3],['block',1,3+y,0],['block',3,3+y,0]];
if(id==='wings')return v===2?[['triangle',1,2,0],['triangle',3,2,1],['square',2,4,0],['square',3,4,0]]:[['elbow',1,1+y,0],['elbow',3,1+y,0,true],['small',2,3+y,1],['small',3,3+y,0]];
if(id==='gap')return v===2?[['bar',1,1,0],['bar',3,1,0],['elbow',1,2,0],['square',2,3,0],['block',3,2,0]]:[['block',1,1+y,0],['triangle',3,1+y,0],['triangle',3,1+y,2]];
if(id==='boat')return[['triangle',1,1+y,2],['triangle',3,1+y,3],['bar',2,3+y,0],['small',1,3+y,2],['small',4,3+y,3]];
if(id==='bridge')return[['beam',1,1+y,0],['bar',1,2+y,1],['bar',4,2+y,1]];
if(id==='rocket')return[['triangle',2,0+y,0],['triangle',2,0+y,2],['bar',2,2+y,1],['small',1,3+y,1],['small',3,3+y,0]];
if(id==='robot')return[['bar',2,0+y,0],['block',2,1+y,0],['bar',1,2+y,1],['bar',4,2+y,1],['square',2,3+y,0],['square',3,3+y,0]];
return[]}
function generate(id,level,recent){var card=get(id);if(!card)throw Error('unknown');level=Math.max(1,Math.min(4,level||1));var v=((recent&&recent[id])||0)%3,raw=rows(id,v),solution=raw.map(function(a,i){return M.piece(a[0],a[1],a[2],a[3],a[4],i)}),target=M.union(solution),library=solution.map(function(p){return{type:p.type,rot:level===1?p.rot:(p.rot+1+v)%4,flip:level===1?p.flip:false}});if(id==='free'){library=['block','triangle','triangle','bar','elbow','square','slant','small'].map(function(type){return{type:type,rot:0,flip:false}})}
if(id==='house'&&level>=3)for(var j=0;j<4;j++)library.push({type:'bar',rot:j%2,flip:false});
var task={id:id+'-'+v+'-'+level,kind:id,variant:v,level:level,title_ar:card.ar,title_en:card.en,mode:id==='free'?'free':'coverage',target:target,library:library,solution:solution,symmetric:id==='wings'||id==='robot'&&level===4,exact_count:id==='bridge'?3:0,require_second:id==='house'&&level>=3,origin:'authored',help_default:level===1};M.validTask(task);return{task:task,next:v+1}}
function fromDesign(d,options){var e=M.evaluate(d);if(!e.ok||!e.count)throw Error('design');options=options||{};var placed=d.pieces.filter(function(p){return p.placed}),task={id:M.id(),kind:'custom',level:d.task.level||1,title_ar:String(options.ar||'لغزي الجديد').slice(0,100),title_en:String(options.en||'My new puzzle').slice(0,100),mode:'coverage',target:M.union(placed),library:placed.map(function(p){return{type:p.type,rot:0,flip:false}}),solution:placed.map(function(p,i){p=M.copy(p);p.id='p'+i;return p}),symmetric:!!options.symmetric,exact_count:options.exact_count?placed.length:0,require_second:false,origin:'coach-copy',help_default:!!options.help};return M.validTask(task)}
function importPatterns(raw){var o=JSON.parse(raw);if(o.app_id!=='a4-shape-design'||o.schema_version!==1||!Array.isArray(o.patterns)||o.patterns.length>20)throw Error('patterns');return o.patterns.map(function(t){t=M.copy(M.validTask(t));t.id=M.id();return t})}
return{cards:cards,get:get,generate:generate,fromDesign:fromDesign,importPatterns:importPatterns};
});
