(function(root,factory){var api=factory(typeof module==='object'&&module.exports?require('../../../../packages/piece-core/browser.js'):root.APP360_PIECES);if(typeof module==='object'&&module.exports)module.exports=api;else root.SHAPE_MODEL=api})(this,function(G){'use strict';
var shapes={square:[[0,0],[1,0],[1,1],[0,1]],block:[[0,0],[2,0],[2,2],[0,2]],triangle:[[0,0],[2,0],[0,2]],small:[[0,0],[1,0],[0,1]],bar:[[0,0],[2,0],[2,1],[0,1]],beam:[[0,0],[4,0],[4,1],[0,1]],elbow:[[0,0],[2,0],[2,1],[1,1],[1,2],[0,2]],slant:[[0,0],[2,0],[3,1],[1,1]]};
var palette=['#dd7857','#358b94','#e3b74a','#836bb3','#68a276','#db83a5','#4b84c4','#ae7a43'];
function copy(v){return JSON.parse(JSON.stringify(v))}function id(){return 's'+Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function polygon(p){return G.transform(shapes[p.type],p.rot,p.flip)}
/* Exact cells for the supported integer, axis/45-degree polygon lattice.
   Each square is split into four center-to-corner triangles; centroids classify atoms. */
function atoms(p){var poly=polygon(p),b=G.bounds(poly),out=[],sample=[[.5,1/6],[5/6,.5],[.5,5/6],[1/6,.5]],x,y,k;for(y=0;y<b.h;y++)for(x=0;x<b.w;x++)for(k=0;k<4;k++)if(G.pointInPoly({x:x+sample[k][0],y:y+sample[k][1]},poly))out.push((x+p.x)+','+(y+p.y)+','+k);return out}
function map(list){var m={};for(var i=0;i<list.length;i++)m[list[i]]=true;return m}
function union(pieces){var all={};for(var i=0;i<pieces.length;i++)atoms(pieces[i]).forEach(function(k){all[k]=true});return Object.keys(all).sort()}
function mirror(k,width){var a=k.split(',').map(Number),swap=[0,3,2,1];return (width-1-a[0])+','+a[1]+','+swap[a[2]]}
function evaluate(d){var target=map(d.task.target),used={},overlap=0,outside=0,count=0,covered=0,symmetry=true,keys,missing,i,p,aa,j,k;for(i=0;i<d.pieces.length;i++){p=d.pieces[i];if(!p.placed)continue;count++;aa=atoms(p);for(j=0;j<aa.length;j++){k=aa[j];if(used[k])overlap++;used[k]=true;if(!target[k]&&d.task.mode!=='free')outside++}}keys=Object.keys(used);missing=0;Object.keys(target).forEach(function(k){if(!used[k])missing++;else covered++});for(i=0;i<keys.length;i++)if(!used[mirror(keys[i],6)])symmetry=false;var ok=count>0&&overlap===0&&(d.task.mode==='free'?true:missing===0&&outside===0)&&(!d.task.symmetric||symmetry)&&(!d.task.exact_count||count===d.task.exact_count);return{ok:ok,missing:missing,overlap:overlap,outside:outside,count:count,covered:covered,total:Object.keys(target).length,symmetric:symmetry}}
function piece(type,x,y,rot,flip,i){return{id:'p'+i,type:type,x:x,y:y,rot:rot||0,flip:!!flip,color:palette[i%palette.length],placed:true}}
function signature(pieces){return pieces.filter(function(p){return p.placed}).map(function(p){return p.type+':'+atoms(p).sort().join(';')}).sort().join('|')}
function checkpoint(d,reason){d.history.push({reason:reason,pieces:copy(d.pieces),hint_level:d.hint_level,time:Date.now()});d.history=d.history.slice(-32)}
function start(task,support){var d={id:id(),task:copy(task),stage:'in_progress',pieces:task.library.map(function(p,i){return{id:'p'+i,type:p.type,rot:p.rot||0,flip:!!p.flip,x:0,y:0,color:palette[i%palette.length],placed:false}}),hint_level:0,support:support||'together',history:[],solutions:[],explanation:'',reflection:'',undo:[],redo:[],created:Date.now(),updated:Date.now()};return d}
function edit(d,fn,reason){d.undo.push({pieces:copy(d.pieces),library:copy(d.task.library)});d.undo=d.undo.slice(-24);d.redo=[];fn();d.stage='in_progress';d.updated=Date.now();checkpoint(d,reason)}
function undo(d,redo){var from=redo?d.redo:d.undo,to=redo?d.undo:d.redo;if(!from.length)return false;to.push({pieces:copy(d.pieces),library:copy(d.task.library)});var previous=from.pop();d.pieces=previous.pieces;d.task.library=previous.library;d.stage='in_progress';checkpoint(d,redo?'redo':'undo');return true}
/* ES5 runtime predicates, including older browsers without Number.isFinite. */
function integer(v){return typeof v==='number'&&isFinite(v)&&v%1===0}
function validTask(t){if(!t||typeof t.id!=='string'||t.id.length>120||!Array.isArray(t.library)||!t.library.length||t.library.length>16||!Array.isArray(t.target)||t.target.length>144||['coverage','free'].indexOf(t.mode)<0)throw Error('task');t.library.forEach(function(p){if(!shapes[p.type]||!integer(p.rot||0)||(p.rot||0)<0||(p.rot||0)>3)throw Error('piece')});t.target.forEach(function(k){if(!/^[0-5],[0-5],[0-3]$/.test(k))throw Error('target')});if(SetFallback(t.target).length!==t.target.length)throw Error('duplicate target');if(t.mode!=='free'&&!t.target.length)throw Error('empty');if(t.exact_count&&(!integer(t.exact_count)||t.exact_count<1||t.exact_count>16))throw Error('count');if(typeof t.title_ar!=='string'||t.title_ar.length>100||typeof t.title_en!=='string'||t.title_en.length>100)throw Error('title');if(t.mode!=='free'&&(!Array.isArray(t.solution)||!t.solution.length))throw Error('solution');if(t.solution&&t.solution.length){if(!Array.isArray(t.solution)||t.solution.length>16)throw Error('solution');t.solution.forEach(validPiece);var available={};t.library.forEach(function(p){available[p.type]=(available[p.type]||0)+1});t.solution.forEach(function(p){if(!p.placed||!(available[p.type]>0))throw Error('solution library');available[p.type]--});var q={task:t,pieces:t.solution};if(!evaluate(q).ok)throw Error('unsolved template')}return t}
function SetFallback(a){return Object.keys(map(a))}
function validPiece(p){if(!p||!shapes[p.type]||!integer(p.x)||!integer(p.y)||p.x<0||p.y<0||!integer(p.rot)||p.rot<0||p.rot>3||typeof p.flip!=='boolean'||typeof p.placed!=='boolean')throw Error('transform');if(p.color!==undefined&&!/^#[0-9a-f]{6}$/i.test(p.color))throw Error('color');var b=G.bounds(polygon(p));if(p.x+b.w>6||p.y+b.h>6)throw Error('bounds');return p}
function artifact(d,privateNote){var a=copy(d);delete a.undo;delete a.redo;if(!privateNote)delete a.coach_note;return a}
function validateArtifact(a){if(!a||typeof a.id!=='string'||!Array.isArray(a.pieces)||a.pieces.length>16)throw Error('artifact');validTask(a.task);a.pieces.forEach(validPiece);if(a.pieces.length!==a.task.library.length)throw Error('library');var ids={};a.pieces.forEach(function(p,i){if(p.id!=='p'+i||p.type!==a.task.library[i].type||ids[p.id])throw Error('identity');ids[p.id]=true});if(typeof a.explanation!=='string'||a.explanation.length>1200)throw Error('text');if(!Array.isArray(a.solutions)||a.solutions.length>4)throw Error('solutions');a.solutions.forEach(function(s){if(!Array.isArray(s.pieces)||s.pieces.length>16)throw Error('solution');s.pieces.forEach(validPiece);if(s.signature!==signature(s.pieces))throw Error('signature');if(!evaluate({task:a.task,pieces:s.pieces}).ok)throw Error('invalid saved solution')});if(!Array.isArray(a.history)||a.history.length>32)throw Error('history');a.history.forEach(function(h){if(!Array.isArray(h.pieces)||h.pieces.length>16)throw Error('history');h.pieces.forEach(validPiece)});a.undo=[];a.redo=[];return a}
function blank(){return{schema_version:1,app_id:'a4-shape-design',language:'ar',level:1,support:'together',voice:true,view:'library',draft:null,saved:[],practice:[],patterns:[],recent:{},note:''}}
function restore(raw){if(!raw)return blank();var s=JSON.parse(raw);if(s.schema_version!==1||s.app_id!=='a4-shape-design'||['ar','en'].indexOf(s.language)<0||!integer(s.level)||s.level<1||s.level>4||['together','hint','independent'].indexOf(s.support)<0||!Array.isArray(s.saved)||s.saved.length>40||!Array.isArray(s.patterns)||s.patterns.length>20)throw Error('state');if(s.draft)validateArtifact(s.draft);s.saved.forEach(validateArtifact);s.practice=s.practice||[];if(!Array.isArray(s.practice)||s.practice.length>20)throw Error('practice');s.practice.forEach(validateArtifact);s.patterns.forEach(validTask);s.recent=s.recent||{};return s}
function exportData(list){return{schema_version:1,app_id:'a4-shape-design',artifacts:list.map(function(d){return artifact(d,false)})}}
function importData(raw){var data=JSON.parse(raw);if(data.schema_version!==1||data.app_id!=='a4-shape-design'||!Array.isArray(data.artifacts)||data.artifacts.length>40)throw Error('import');return data.artifacts.map(function(a){a=validateArtifact(a);a.id=id();delete a.coach_note;return a})}
return{copy:copy,id:id,shapes:shapes,palette:palette,polygon:polygon,atoms:atoms,union:union,mirror:mirror,evaluate:evaluate,piece:piece,signature:signature,checkpoint:checkpoint,start:start,edit:edit,undo:undo,artifact:artifact,validTask:validTask,validPiece:validPiece,validateArtifact:validateArtifact,blank:blank,restore:restore,exportData:exportData,importData:importData};
});
