'use strict';
(function(){
var d=document,w=window,canvas=d.getElementById('gameCanvas'),ctx=canvas.getContext('2d'),wrap=d.getElementById('boardWrap'),fx=d.getElementById('celebrateCanvas'),fctx=fx.getContext('2d');
var W=1,H=1,DPR=1,level=0,index=0,library=[],img=null,imageReady=false,tiles=[],drag=null,won=false,hint=false,sound=true,focus=false,touchId=null,graceTimer=null,confetti=[],fxFrame=0;
var zones={target:null,targetInner:null,tray:null,trayInner:null},imageRect=null;
var LEVELS=[{cols:2,rows:2,label:'4 قطع'},{cols:3,rows:2,label:'6 قطع'},{cols:3,rows:3,label:'9 قطع'}];
var palette=['#ef4b4d','#f4c845','#41a8e5','#79c94b','#8a4fc5','#f08f35','#e967b2'];
var $=function(id){return d.getElementById(id)};
var raf=w.requestAnimationFrame||w.webkitRequestAnimationFrame||function(fn){return setTimeout(fn,16)};
function n(v,a,b){return Math.max(a,Math.min(b,v))}
function S(k,v){try{if(w.localStorage)localStorage.setItem(k,String(v))}catch(e){}}
function G(k,v){try{var x=w.localStorage?localStorage.getItem(k):null;return x===null?String(v):x}catch(e){return String(v)}}
function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function showMsg(t,kind,delay){var m=$('message');m.className='message'+(kind?' '+kind:'');m.innerHTML=esc(t);if(delay)setTimeout(function(){if(!won){m.className='message';m.innerHTML='اسحب قطعة إلى مكانها في الصورة'}},delay)}
function parseLibrary(){var map=w.APP360_WORD_IMAGE_CONTEXT_MAP||{},seen={},k,file,parts,word,cat,i=0;library=[];for(k in map)if(map.hasOwnProperty(k)){file=map[k];if(!file||seen[file])continue;parts=String(k).split('\u0001');cat=parts[0]||'صور';word=parts[1]||('صورة '+(++i));seen[file]=1;library.push({file:file,word:word,category:cat})}if(!library.length){for(i=1;i<=140;i++)library.push({file:'w'+('0000'+i).slice(-4)+'.jpg',word:'صورة '+i,category:'صور'})}}
function hash(s){var h=2166136261,i;for(i=0;i<s.length;i++){h^=s.charCodeAt(i);h+=(h<<1)+(h<<4)+(h<<7)+(h<<8)+(h<<24)}return h>>>0}
function rng(seed){var x=seed||123456789;return function(){x=(x*1664525+1013904223)>>>0;return x/4294967296}}
function current(){return library[index]||null}
function imagePath(item){return '../say-and-name/assets/word-images/'+item.file}
function loadPrefs(){level=parseInt(G('app360:a1-picture-puzzles:level','0'),10)||0;level=n(level,0,2);index=parseInt(G('app360:a1-picture-puzzles:index','0'),10)||0;sound=G('app360:a1-picture-puzzles:sound','1')!=='0'}
function savePrefs(){S('app360:a1-picture-puzzles:level',level);S('app360:a1-picture-puzzles:index',index);S('app360:a1-picture-puzzles:sound',sound?'1':'0')}
function updateSound(){if($('soundBtn'))$('soundBtn').innerHTML=sound?'🔊':'🔇'}
function computeZones(){var pad=Math.max(6,Math.round(Math.min(W,H)*.014)),split;if(W/H>1.08){split=Math.round(W*.72);zones.target={x:pad,y:pad,w:split-pad*1.2,h:H-pad*2};zones.tray={x:split+pad*.2,y:pad,w:W-split-pad*1.2,h:H-pad*2}}else{split=Math.round(H*.60);zones.target={x:pad,y:pad,w:W-pad*2,h:split-pad*.8};zones.tray={x:pad,y:split+pad*.1,w:W-pad*2,h:H-split-pad*1.1}}zones.targetInner={x:zones.target.x+10,y:zones.target.y+38,w:Math.max(90,zones.target.w-20),h:Math.max(80,zones.target.h-48)};zones.trayInner={x:zones.tray.x+10,y:zones.tray.y+38,w:Math.max(80,zones.tray.w-20),h:Math.max(70,zones.tray.h-48)}}
function size(){var r=wrap.getBoundingClientRect();DPR=w.devicePixelRatio||1;if(DPR>2)DPR=2;W=Math.max(1,r.width);H=Math.max(1,r.height);canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);fx.width=Math.round(W*DPR);fx.height=Math.round(H*DPR);canvas.style.width=W+'px';canvas.style.height=H+'px';fx.style.width=W+'px';fx.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0);fctx.setTransform(DPR,0,0,DPR,0,0);computeZones();if(imageReady)buildPuzzle(true);draw()}
function fitImageRect(){if(!img)return null;var iw=img.naturalWidth||img.width||1,ih=img.naturalHeight||img.height||1,box=zones.targetInner,scale=Math.min(box.w/iw,box.h/ih)*.94,w0=iw*scale,h0=ih*scale;return{x:box.x+(box.w-w0)/2,y:box.y+(box.h-h0)/2,w:w0,h:h0}}
function gridPoints(cols,rows,random){var pts=[],r,c,x,y,jx,jy,ampX=.12/cols,ampY=.12/rows;for(r=0;r<=rows;r++){pts[r]=[];for(c=0;c<=cols;c++){x=c/cols;y=r/rows;if(c>0&&c<cols){jx=(random()-.5)*2*ampX;x+=jx}if(r>0&&r<rows){jy=(random()-.5)*2*ampY;y+=jy}pts[r][c]={x:x,y:y}}}return pts}
function centroid(poly){var x=0,y=0,i;for(i=0;i<poly.length;i++){x+=poly[i].x;y+=poly[i].y}return{x:x/poly.length,y:y/poly.length}}
function bbox(poly){var minX=9,maxX=-9,minY=9,maxY=-9,i;for(i=0;i<poly.length;i++){minX=Math.min(minX,poly[i].x);maxX=Math.max(maxX,poly[i].x);minY=Math.min(minY,poly[i].y);maxY=Math.max(maxY,poly[i].y)}return{w:maxX-minX,h:maxY-minY}}
function buildPuzzle(preservePlaced){var cfg=LEVELS[level],item=current(),random=rng(hash((item?item.file:'x')+'|'+level)),pts=gridPoints(cfg.cols,cfg.rows,random),old={},r,c,p,poly,cen,b,i=0;if(!imageReady)return;imageRect=fitImageRect();if(preservePlaced){for(i=0;i<tiles.length;i++)old[tiles[i].id]=tiles[i]}tiles=[];i=0;for(r=0;r<cfg.rows;r++){for(c=0;c<cfg.cols;c++){poly=[pts[r][c],pts[r][c+1],pts[r+1][c+1],pts[r+1][c]];cen=centroid(poly);b=bbox(poly);p=old['t'+i];tiles.push({id:'t'+i,row:r,col:c,poly:poly,cx:cen.x,cy:cen.y,bw:b.w,bh:b.h,targetX:imageRect.x+cen.x*imageRect.w,targetY:imageRect.y+cen.y*imageRect.h,x:0,y:0,trayX:0,trayY:0,trayScale:1,scale:1,placed:p?p.placed:false,state:p&&p.placed?'placed':'tray'});i++}}layoutTray();for(i=0;i<tiles.length;i++){p=tiles[i];if(p.placed){p.x=p.targetX;p.y=p.targetY;p.scale=1}else{p.x=p.trayX;p.y=p.trayY;p.scale=p.trayScale}}drag=null;updateStatus()}
function layoutTray(){var rect=zones.trayInner,count=tiles.length,cols=W/H>1.08?(rect.w<210?1:2):3,rows=Math.ceil(count/cols),sw=rect.w/cols,sh=rect.h/rows,i,t,c,r,bb,fit,jitter;for(i=0;i<count;i++){t=tiles[i];c=i%cols;r=Math.floor(i/cols);bb={w:t.bw*imageRect.w,h:t.bh*imageRect.h};fit=Math.min(sw*.76/Math.max(20,bb.w),sh*.70/Math.max(20,bb.h),1);fit=n(fit,.45,1);jitter=((i%2)?1:-1)*Math.min(5,sw*.03);t.trayX=rect.x+sw*(c+.5)+jitter;t.trayY=rect.y+sh*(r+.5);t.trayScale=fit}}
function roundRect(c,x,y,w0,h0,r){var rr=Math.min(r,w0*.5,h0*.5);c.beginPath();c.moveTo(x+rr,y);c.lineTo(x+w0-rr,y);c.quadraticCurveTo(x+w0,y,x+w0,y+rr);c.lineTo(x+w0,y+h0-rr);c.quadraticCurveTo(x+w0,y+h0,x+w0-rr,y+h0);c.lineTo(x+rr,y+h0);c.quadraticCurveTo(x,y+h0,x,y+h0-rr);c.lineTo(x,y+rr);c.quadraticCurveTo(x,y,x+rr,y);c.closePath()}
function drawPanel(rect,title){ctx.save();ctx.shadowColor='rgba(70,38,13,.16)';ctx.shadowBlur=12;ctx.shadowOffsetY=4;ctx.fillStyle='rgba(255,249,236,.97)';roundRect(ctx,rect.x,rect.y,rect.w,rect.h,20);ctx.fill();ctx.shadowColor='transparent';ctx.strokeStyle='rgba(123,75,33,.24)';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#70431f';ctx.font='bold '+(W>900?19:16)+'px Tahoma';ctx.textAlign='center';ctx.fillText(title,rect.x+rect.w/2,rect.y+25);ctx.restore()}
function localPoly(t,scale){var out=[],i,p;for(i=0;i<t.poly.length;i++){p=t.poly[i];out.push({x:(p.x-t.cx)*imageRect.w*scale,y:(p.y-t.cy)*imageRect.h*scale})}return out}
function pathPoly(c,poly){var i;c.beginPath();for(i=0;i<poly.length;i++){if(i===0)c.moveTo(poly[i].x,poly[i].y);else c.lineTo(poly[i].x,poly[i].y)}c.closePath()}
function drawTile(t,x,y,scale,alpha,shadow){var poly=localPoly(t,scale);ctx.save();ctx.globalAlpha=alpha==null?1:alpha;ctx.translate(x,y);if(shadow){ctx.shadowColor='rgba(45,24,8,.28)';ctx.shadowBlur=8;ctx.shadowOffsetY=4}pathPoly(ctx,poly);ctx.clip();ctx.drawImage(img,-t.cx*imageRect.w*scale,-t.cy*imageRect.h*scale,imageRect.w*scale,imageRect.h*scale);ctx.restore();ctx.save();ctx.globalAlpha=alpha==null?1:alpha;ctx.translate(x,y);pathPoly(ctx,poly);ctx.lineWidth=Math.max(1.5,2.4*scale);ctx.strokeStyle='rgba(82,49,23,.67)';ctx.stroke();ctx.restore()}
function drawTargetSlots(){var i,t,poly;if(!imageReady)return;ctx.save();ctx.fillStyle='#f5eddf';ctx.fillRect(imageRect.x,imageRect.y,imageRect.w,imageRect.h);ctx.globalAlpha=hint?.28:.09;ctx.drawImage(img,imageRect.x,imageRect.y,imageRect.w,imageRect.h);ctx.globalAlpha=1;ctx.restore();for(i=0;i<tiles.length;i++){t=tiles[i];if(t.placed)continue;poly=localPoly(t,1);ctx.save();ctx.translate(t.targetX,t.targetY);pathPoly(ctx,poly);ctx.fillStyle='rgba(218,203,179,.18)';ctx.fill();ctx.lineWidth=2;ctx.strokeStyle='rgba(119,87,52,.35)';ctx.stroke();ctx.restore()}}
function draw(){var i,t;ctx.clearRect(0,0,W,H);ctx.fillStyle='#ecd2a7';ctx.fillRect(0,0,W,H);drawPanel(zones.target,'الصورة المطلوبة');drawPanel(zones.tray,'القطع المتاحة');if(imageReady){drawTargetSlots();for(i=0;i<tiles.length;i++){t=tiles[i];if(t.placed)drawTile(t,t.targetX,t.targetY,1,1,false)}for(i=0;i<tiles.length;i++){t=tiles[i];if(t.state==='tray')drawTile(t,t.trayX,t.trayY,t.trayScale,1,true)}if(drag&&drag.tile)drawTile(drag.tile,drag.tile.x,drag.tile.y,1,.99,true)}else{ctx.fillStyle='#76502e';ctx.font='bold 18px Tahoma';ctx.textAlign='center';ctx.fillText('جارٍ تحميل الصورة…',W/2,H/2)}}
function pointInPoly(pt,poly){var inside=false,i,j,xi,yi,xj,yj,hit;for(i=0,j=poly.length-1;i<poly.length;j=i++){xi=poly[i].x;yi=poly[i].y;xj=poly[j].x;yj=poly[j].y;hit=((yi>pt.y)!==(yj>pt.y))&&(pt.x<(xj-xi)*(pt.y-yi)/(yj-yi||.0001)+xi);if(hit)inside=!inside}return inside}
function screenPos(clientX,clientY){var r=canvas.getBoundingClientRect();return{x:(clientX-r.left)*(W/r.width),y:(clientY-r.top)*(H/r.height)}}
function hitTile(pt,t){var scale=t.state==='tray'?t.trayScale:1,poly=localPoly(t,scale),q={x:pt.x-(t.state==='tray'?t.trayX:t.x),y:pt.y-(t.state==='tray'?t.trayY:t.y)},r=Math.max(20,Math.min(imageRect.w,imageRect.h)*.04);if(pointInPoly(q,poly))return true;return Math.abs(q.x)<t.bw*imageRect.w*scale*.62+r&&Math.abs(q.y)<t.bh*imageRect.h*scale*.62+r}
function findTile(pt){var i,t;for(i=tiles.length-1;i>=0;i--){t=tiles[i];if(t.state==='tray'&&hitTile(pt,t))return t}return null}
function clearGrace(){if(graceTimer){clearTimeout(graceTimer);graceTimer=null}}
function beginDrag(pt){var t;if(won)return;t=findTile(pt);if(!t)return;clearGrace();t.state='drag';t.x=pt.x;t.y=pt.y;t.scale=1;drag={tile:t};d.body.className+=' grabCursor';draw()}
function nearDragged(pt){if(!drag||!drag.tile)return false;var t=drag.tile,dx=pt.x-t.x,dy=pt.y-t.y,r=Math.max(55,Math.min(imageRect.w,imageRect.h)*.16);return dx*dx+dy*dy<=r*r}
function moveDrag(pt){if(!drag)return;drag.tile.x=n(pt.x,12,W-12);drag.tile.y=n(pt.y,12,H-12);draw()}
function snapRadius(){return Math.max(34,Math.min(imageRect.w,imageRect.h)*(level===0?.16:(level===1?.13:.11)))}
function tryPlace(){if(!drag)return false;var t=drag.tile,dx=t.x-t.targetX,dy=t.y-t.targetY,dd=Math.sqrt(dx*dx+dy*dy);if(dd<=snapRadius()){t.placed=true;t.state='placed';t.x=t.targetX;t.y=t.targetY;drag=null;d.body.className=d.body.className.replace(/\s*grabCursor/g,'');tone(620,70,.018);showMsg('ممتاز! ثبتت القطعة','good',700);updateStatus();draw();if(allPlaced())stageWin();return true}return false}
function safeReturn(){var t;if(!drag)return;t=drag.tile;clearGrace();t.state='tray';t.placed=false;t.x=t.trayX;t.y=t.trayY;t.scale=t.trayScale;drag=null;touchId=null;d.body.className=d.body.className.replace(/\s*grabCursor/g,'');updateStatus();draw()}
function endDrag(grace){if(!drag)return;if(tryPlace())return;clearGrace();graceTimer=setTimeout(function(){graceTimer=null;if(drag){showMsg('حاول الاقتراب من مكان القطعة','soft',700);safeReturn()}},grace||480)}
function allPlaced(){var i;for(i=0;i<tiles.length;i++)if(!tiles[i].placed)return false;return !!tiles.length}
function updateStatus(){var i,c=0;for(i=0;i<tiles.length;i++)if(tiles[i].placed)c++;$('pieceStatus').innerHTML=c+' / '+tiles.length;$('progressText').innerHTML='باقي '+(tiles.length-c)+' قطع'}
function tone(freq,dur,vol){if(!sound)return;try{var AC=w.AudioContext||w.webkitAudioContext;if(!AC)return;var ac=tone.ac||(tone.ac=new AC()),o=ac.createOscillator(),g=ac.createGain();if(ac.state==='suspended'&&ac.resume)ac.resume();o.frequency.value=freq;g.gain.value=vol||.02;o.connect(g);g.connect(ac.destination);o.start(0);setTimeout(function(){try{o.stop(0)}catch(e){}},dur||80)}catch(e){}}
function speak(text){if(!sound)return;try{if(w.speechSynthesis&&w.SpeechSynthesisUtterance){w.speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(text);u.lang='ar-SA';u.rate=.82;w.speechSynthesis.speak(u)}}catch(e){}}
function stageWin(){won=true;showMsg('اكتملت الصورة!','good',0);$('winTitle').innerHTML='أحسنت!';$('winText').innerHTML='أكملت صورة '+esc(current().word);setTimeout(function(){$('winCard').style.display='block'},260);celebrate();tone(740,120,.025);setTimeout(function(){speak(current().word)},250)}
function celebrate(){confetti=[];var i;for(i=0;i<70;i++)confetti.push({x:W*.5,y:H*.45,vx:(Math.random()-.5)*7,vy:-3-Math.random()*6,g:.13+Math.random()*.07,r:3+Math.random()*5,a:1,c:palette[i%palette.length]});animateFx()}
function animateFx(){fctx.clearRect(0,0,W,H);var alive=0,i,p;for(i=0;i<confetti.length;i++){p=confetti[i];p.x+=p.vx;p.y+=p.vy;p.vy+=p.g;p.a-=.012;if(p.a>0&&p.y<H+20){alive++;fctx.save();fctx.globalAlpha=p.a;fctx.fillStyle=p.c;fctx.fillRect(p.x,p.y,p.r*2,p.r);fctx.restore()}}if(alive)fxFrame=raf(animateFx);else fctx.clearRect(0,0,W,H)}
function refreshImage(){var item=current();if(!item)return;imageReady=false;tiles=[];drag=null;won=false;$('winCard').style.display='none';$('imageTitle').innerHTML=esc(item.word);$('imageMeta').innerHTML=esc(item.category)+' · '+(index+1)+' / '+library.length;img=new Image();img.onload=function(){imageReady=true;buildPuzzle(false);draw();showMsg('رتّب قطع صورة '+item.word,'',1000)};img.onerror=function(){index=(index+1)%library.length;savePrefs();setTimeout(refreshImage,20)};img.src=imagePath(item)+'?v=24'}
function setLevel(lv){level=n(lv,0,2);savePrefs();updateLevelButtons();if(imageReady){won=false;$('winCard').style.display='none';buildPuzzle(false);draw()}}
function updateLevelButtons(){var bs=d.getElementsByClassName('levelBtn'),i,lv;for(i=0;i<bs.length;i++){lv=parseInt(bs[i].getAttribute('data-level'),10)||0;bs[i].className='levelBtn'+(lv===level?' on':'')}}
function next(step){if(!library.length)return;index=(index+(step||1)+library.length)%library.length;savePrefs();refreshImage()}
function randomImage(){if(library.length<2)return;var old=index;while(index===old)index=Math.floor(Math.random()*library.length);savePrefs();refreshImage()}
function reset(){won=false;$('winCard').style.display='none';buildPuzzle(false);draw();showMsg('أعدنا خلط القطع','',700)}
function toggleHint(){hint=!hint;showMsg(hint?'ظهرت الصورة كدليل':'أخفينا الدليل','',700);draw()}
function requestFS(){var el=$('app'),fn=el&&(el.requestFullscreen||el.webkitRequestFullscreen||el.webkitRequestFullScreen||el.mozRequestFullScreen||el.msRequestFullscreen);try{if(fn)fn.call(el)}catch(e){}}
function exitFS(){var fn=d.exitFullscreen||d.webkitExitFullscreen||d.webkitCancelFullScreen||d.mozCancelFullScreen||d.msExitFullscreen;try{if(fn&&(d.fullscreenElement||d.webkitFullscreenElement||d.webkitCurrentFullScreenElement||d.mozFullScreenElement||d.msFullscreenElement))fn.call(d)}catch(e){}}
function enterFocus(){if(focus)return;focus=true;d.body.className+=' pictureFocus';requestFS();setTimeout(size,60);setTimeout(size,260)}
function leaveFocus(){if(!focus)return;focus=false;d.body.className=d.body.className.replace(/\s*pictureFocus/g,'');exitFS();setTimeout(size,60);setTimeout(size,260)}
function touchById(list,id){var i;for(i=0;i<(list?list.length:0);i++)if(list[i].identifier===id)return list[i];return list&&list.length?list[0]:null}
function bindTouch(){canvas.addEventListener('touchstart',function(e){if(!e.touches||!e.touches.length)return;var t=e.touches[0],pt=screenPos(t.clientX,t.clientY);touchId=t.identifier;if(drag&&nearDragged(pt)){clearGrace();moveDrag(pt)}else{if(drag)safeReturn();beginDrag(pt)}if(drag)e.preventDefault()},true);canvas.addEventListener('touchmove',function(e){if(!drag)return;var t=touchById(e.touches,touchId);if(t)moveDrag(screenPos(t.clientX,t.clientY));e.preventDefault()},true);canvas.addEventListener('touchend',function(e){if(!drag)return;var t=touchById(e.changedTouches,touchId);if(t)moveDrag(screenPos(t.clientX,t.clientY));endDrag(520);e.preventDefault()},true);canvas.addEventListener('touchcancel',function(e){if(drag)endDrag(720);e.preventDefault()},true);canvas.addEventListener('mousedown',function(e){beginDrag(screenPos(e.clientX,e.clientY));if(drag)e.preventDefault()},false);w.addEventListener('mousemove',function(e){if(drag)moveDrag(screenPos(e.clientX,e.clientY))},false);w.addEventListener('mouseup',function(){if(drag){if(!tryPlace())safeReturn()}},false);w.addEventListener('blur',safeReturn,false);d.addEventListener('visibilitychange',function(){if(d.hidden)safeReturn()},false)}
function bind(){var bs=d.getElementsByClassName('levelBtn'),i;for(i=0;i<bs.length;i++)bs[i].onclick=function(){setLevel(parseInt(this.getAttribute('data-level'),10)||0)};$('hintBtn').onclick=toggleHint;$('randomBtn').onclick=randomImage;$('focusBtn').onclick=enterFocus;$('focusBack').onclick=leaveFocus;$('focusPrev').onclick=function(){next(-1)};$('focusNext').onclick=function(){next(1)};$('prevBtn').onclick=function(){next(-1)};$('nextBtn').onclick=function(){next(1)};$('resetBtn').onclick=reset;$('replayBtn').onclick=reset;$('nextWinBtn').onclick=function(){next(1)};$('soundBtn').onclick=function(){sound=!sound;savePrefs();updateSound();if(sound)tone(660,90,.02)};w.addEventListener('resize',function(){raf(size)},false);w.addEventListener('orientationchange',function(){if(drag)safeReturn();setTimeout(size,260)},false);d.addEventListener('keydown',function(e){if((e.keyCode||e.which)===27&&focus)leaveFocus()},false);bindTouch()}
function setupPwa(){if('serviceWorker'in navigator&&location.protocol.indexOf('http')===0){try{navigator.serviceWorker.register('sw.js?v=1',{updateViaCache:'none'}).then(function(r){try{r.update()}catch(e){}})}catch(e){}}}
parseLibrary();loadPrefs();if(index>=library.length)index=0;bind();updateSound();updateLevelButtons();size();refreshImage();setupPwa();
})();
