'use strict';
(function(){
var d=document,w=window;
var SAY_ROOT='../say-and-name/';
var SHARED='../../../resources/early-child-name-audio/';
var KEY='app360:a1-picture-puzzles:';
var registry=null,currentAudio=null,audioCtx=null,lastCheer=-1,unlocked=false,pendingStart=false,completed=false,seq=0,suppressUntil=0;
var ss=w.speechSynthesis||null,nativeSpeak=null,nativeCancel=null;
var prefs={name:'نور',lang:'ar',announceStart:true,announceFinish:true,cheer:true,audioMode:'auto'};
function $(id){return d.getElementById(id)}
function G(k,v){try{var x=w.localStorage?localStorage.getItem(k):null;return x===null?String(v):x}catch(e){return String(v)}}
function S(k,v){try{if(w.localStorage)localStorage.setItem(k,String(v))}catch(e){}}
function normalize(s){return String(s||'').toLowerCase().replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[ًٌٍَُِّْـ\s]/g,'')}
function soundOn(){var b=$('soundBtn');return !b||String(b.innerHTML).indexOf('🔇')<0}
function title(){return $('imageTitle')?String($('imageTitle').textContent||'').replace(/^\s+|\s+$/g,''):''}
function category(){var s=$('imageMeta')?String($('imageMeta').textContent||''):'';return String(s.split('·')[0]||'').replace(/^\s+|\s+$/g,'')}
function englishWord(){var word=title(),cat=category(),map=w.APP360_EN&&w.APP360_EN.words,k;if(!map)return word;if(map[cat+'\u0001'+word])return map[cat+'\u0001'+word];for(k in map)if(map.hasOwnProperty(k)&&k.slice(k.lastIndexOf('\u0001')+1)===word)return map[k];return word}
function loadPrefs(){prefs.name=G(KEY+'name',G('app360:a1-tangram:name',G('pk_user_name','نور')))||'نور';prefs.lang=G(KEY+'voice-lang','ar');if(prefs.lang!=='en'&&prefs.lang!=='both')prefs.lang='ar';prefs.announceStart=G(KEY+'announce-start','1')!=='0';prefs.announceFinish=G(KEY+'announce-finish','1')!=='0';prefs.cheer=G(KEY+'name-cheer','1')!=='0';prefs.audioMode=G(KEY+'audio-mode','auto');if(prefs.audioMode!=='recorded'&&prefs.audioMode!=='tts')prefs.audioMode='auto'}
function savePrefs(){S(KEY+'name',prefs.name);S(KEY+'voice-lang',prefs.lang);S(KEY+'announce-start',prefs.announceStart?'1':'0');S(KEY+'announce-finish',prefs.announceFinish?'1':'0');S(KEY+'name-cheer',prefs.cheer?'1':'0');S(KEY+'audio-mode',prefs.audioMode)}
function fetchRegistry(){try{var x=new XMLHttpRequest();x.open('GET',SHARED+'audio/registry.json?v=21',true);x.onreadystatechange=function(){if(x.readyState!==4)return;if(x.status>=200&&x.status<300){try{registry=JSON.parse(x.responseText)}catch(e){registry=null}}};x.send(null)}catch(e){}}
function findUser(){if(!registry||!registry.users)return null;var k,target=normalize(prefs.name),u,als,i;for(k in registry.users)if(registry.users.hasOwnProperty(k)){u=registry.users[k];if(normalize(k)===target)return u;als=u.aliases||[];for(i=0;i<als.length;i++)if(normalize(als[i])===target)return u}return null}
function stopCurrent(){try{if(currentAudio){currentAudio.pause();currentAudio.currentTime=0}}catch(e){}currentAudio=null}
function playUrl(src,done){if(!src){done(false);return}try{stopCurrent();var a=new Audio(src);currentAudio=a;var finished=false,timer=setTimeout(function(){if(!finished){finished=true;done(false)}},5000);a.onended=function(){if(!finished){finished=true;clearTimeout(timer);currentAudio=null;done(true)}};a.onerror=function(){if(!finished){finished=true;clearTimeout(timer);currentAudio=null;done(false)}};var p=a.play();if(p&&p.catch)p.catch(function(){if(!finished){finished=true;clearTimeout(timer);currentAudio=null;done(false)}})}catch(e){done(false)}}
function tts(text,lang,done){if(!ss||!w.SpeechSynthesisUtterance){done(false);return}try{if(nativeCancel)nativeCancel();var u=new SpeechSynthesisUtterance(text);u.lang=lang;u.rate=lang.indexOf('ar')===0?.82:.88;u.pitch=1.03;var fin=false,t=setTimeout(function(){if(!fin){fin=true;done(false)}},4500);u.onend=function(){if(!fin){fin=true;clearTimeout(t);done(true)}};u.onerror=function(){if(!fin){fin=true;clearTimeout(t);done(false)}};(nativeSpeak||ss.speak.bind(ss))(u)}catch(e){done(false)}}
function arWord(done){var word=title(),m=w.APP360_AUDIO_MAP||{},src=m[word];if(src){playUrl(SAY_ROOT+src,function(ok){if(ok)done(true);else tts(word,'ar-SA',done)});return}tts(word,'ar-SA',done)}
function enWord(done){var word=englishWord(),m=w.APP360_AUDIO_MAP_EN||{},src=m[word];if(src){playUrl(SAY_ROOT+src,function(ok){if(ok)done(true);else tts(word,'en-US',done)});return}tts(word,'en-US',done)}
function playImageName(done){var my=++seq;if(!soundOn()){done&&done();return}function finish(){if(my===seq&&done)done()}if(prefs.lang==='ar'){arWord(function(){finish()});return}if(prefs.lang==='en'){enWord(function(){finish()});return}arWord(function(){if(my!==seq)return;setTimeout(function(){if(my!==seq)return;enWord(function(){finish()})},90)})}
function isLegacy(){var u=navigator.userAgent||'',m=u.match(/Android\s+([0-9.]+)/i),av=m?(parseFloat(m[1])||0):0,c=u.match(/(?:Chrome|CriOS)\/([0-9]+)/i),cv=c?(parseInt(c[1],10)||0):0;return !!((av&&av<5)||(cv&&cv<50)||/Android 4\.|Version\/4\.|BigTAB|DMTAB/i.test(u))}
function pcmPackFor(c){var packs=w.Audio360PCMPacks||{};if(c&&c.pcmPack&&packs[c.pcmPack])return packs[c.pcmPack];return w.Audio360PCM||null}
function playPcmBuffer(pack,key,done){var b64=pack&&pack.clips&&pack.clips[key],raw,buf,data,src,i,rate;if(!b64||!w.atob){done(false);return}try{var AC=w.AudioContext||w.webkitAudioContext;if(!AC){done(false);return}audioCtx=audioCtx||new AC();if(audioCtx.state==='suspended'&&audioCtx.resume)audioCtx.resume();raw=atob(b64);rate=parseInt(pack.rate,10)||16000;buf=audioCtx.createBuffer(1,raw.length,rate);data=buf.getChannelData(0);for(i=0;i<raw.length;i++)data[i]=(raw.charCodeAt(i)-128)/128;src=audioCtx.createBufferSource();src.buffer=buf;src.connect(audioCtx.destination);src.onended=function(){done(true)};if(src.start)src.start(0);else if(src.noteOn)src.noteOn(0)}catch(e){done(false)}}
function embeddedCheer(done){var u=findUser(),clips=[],i,c,pack,key,script;if(!u||!u.clips){done(false);return}for(i=0;i<u.clips.length;i++)if(u.clips[i].kind==='cheer')clips.push(u.clips[i]);if(!clips.length){done(false);return}i=Math.floor(Math.random()*clips.length);if(clips.length>1&&i===lastCheer)i=(i+1)%clips.length;lastCheer=i;c=clips[i];key=c.pcmKey||c.id;pack=pcmPackFor(c);if(pack&&pack.clips&&pack.clips[key]){playPcmBuffer(pack,key,done);return}script=c.pcmScript;try{var sc=d.createElement('script');sc.type='text/javascript';sc.src=SHARED+(script||'audio-pcm-v18.js')+'?v=21';sc.onload=function(){pack=pcmPackFor(c);if(pack&&pack.clips&&pack.clips[key])playPcmBuffer(pack,key,done);else done(false)};sc.onerror=function(){done(false)};(d.getElementsByTagName('head')[0]||d.body).appendChild(sc)}catch(e){done(false)}}
function recordedCheer(done){var u=findUser(),clips=[],i,c,src;if(!u||!u.clips){done(false);return}for(i=0;i<u.clips.length;i++)if(u.clips[i].kind==='cheer')clips.push(u.clips[i]);if(!clips.length){done(false);return}i=Math.floor(Math.random()*clips.length);if(clips.length>1&&i===lastCheer)i=(i+1)%clips.length;lastCheer=i;c=clips[i];src=c.files&&c.files.mp3?c.files.mp3:c.file;if(!src){done(false);return}playUrl(SHARED+src,done)}
function arCheer(done){var text='أحسنت يا '+prefs.name;if(prefs.audioMode==='tts'){tts(text,'ar-SA',done);return}function fallback(){tts(text,'ar-SA',done)}if(isLegacy()){embeddedCheer(function(ok){if(ok)done(true);else recordedCheer(function(ok2){if(ok2)done(true);else fallback()})})}else{recordedCheer(function(ok){if(ok)done(true);else embeddedCheer(function(ok2){if(ok2)done(true);else fallback()})})}}
function enCheer(done){tts('Well done, '+prefs.name+'!','en-US',done)}
function playCheer(done){if(!prefs.cheer||!soundOn()){done&&done();return}if(prefs.lang==='en'){enCheer(function(){done&&done()});return}if(prefs.lang==='both'){arCheer(function(){setTimeout(function(){enCheer(function(){done&&done()})},80)});return}arCheer(function(){done&&done()})}
function announceStart(){if(!prefs.announceStart||!soundOn())return;if(!unlocked){pendingStart=true;return}pendingStart=false;setTimeout(function(){if(soundOn())playImageName()},260)}
function announceFinish(){if(!soundOn())return;suppressUntil=(new Date()).getTime()+3000;if(prefs.announceFinish){playImageName(function(){playCheer()})}else{seq++;playCheer()}}
function installSpeechGuard(){if(!ss)return;try{nativeSpeak=ss.speak.bind(ss);nativeCancel=ss.cancel?ss.cancel.bind(ss):null;ss.speak=function(u){var now=(new Date()).getTime(),txt=u&&u.text?String(u.text):'';if(now<suppressUntil&&normalize(txt)===normalize(title()))return;return nativeSpeak(u)};if(nativeCancel)ss.cancel=function(){if((new Date()).getTime()<suppressUntil)return;return nativeCancel()}}catch(e){}}
function unlock(){if(unlocked)return;unlocked=true;try{var AC=w.AudioContext||w.webkitAudioContext;if(AC){audioCtx=audioCtx||new AC();if(audioCtx.state==='suspended'&&audioCtx.resume)audioCtx.resume()}}catch(e){}if(pendingStart)announceStart()}
function bindUnlock(){var fn=function(){unlock()};d.addEventListener('touchstart',fn,true);d.addEventListener('mousedown',fn,true);d.addEventListener('keydown',fn,true)}
function parseStatus(){var s=$('pieceStatus')?String($('pieceStatus').textContent||''):'',m=s.match(/(\d+)\s*\/\s*(\d+)/);if(!m)return;var a=parseInt(m[1],10)||0,b=parseInt(m[2],10)||0;if(b&&a>=b){if(!completed){completed=true;announceFinish()}}else completed=false}
function observeGame(){var titleEl=$('imageTitle'),statusEl=$('pieceStatus'),last=title();if(w.MutationObserver&&titleEl){new MutationObserver(function(){var t=title();if(t&&t!==last&&t!=='ألغاز الصور'){last=t;completed=false;seq++;announceStart()}}).observe(titleEl,{childList:true,characterData:true,subtree:true})}if(w.MutationObserver&&statusEl)new MutationObserver(parseStatus).observe(statusEl,{childList:true,characterData:true,subtree:true});setTimeout(function(){if(title()&&title()!=='ألغاز الصور')announceStart();parseStatus()},450)}
function openSettings(){var p=$('audioSettingsPanel');if(!p)return;$('childNameInput').value=prefs.name;$('voiceLangSelect').value=prefs.lang;$('announceStartToggle').checked=prefs.announceStart;$('announceFinishToggle').checked=prefs.announceFinish;$('nameCheerToggle').checked=prefs.cheer;$('audioModeSelect').value=prefs.audioMode;p.setAttribute('aria-hidden','false');p.style.display='flex'}
function closeSettings(){var p=$('audioSettingsPanel');if(!p)return;p.setAttribute('aria-hidden','true');p.style.display='none'}
function saveSettings(){prefs.name=String($('childNameInput').value||'نور').replace(/^\s+|\s+$/g,'')||'نور';prefs.lang=$('voiceLangSelect').value;prefs.announceStart=!!$('announceStartToggle').checked;prefs.announceFinish=!!$('announceFinishToggle').checked;prefs.cheer=!!$('nameCheerToggle').checked;prefs.audioMode=$('audioModeSelect').value;savePrefs();closeSettings();var m=$('message');if(m){m.className='message good';m.innerHTML='تم حفظ إعدادات الصوت';setTimeout(function(){m.className='message';m.innerHTML='اسحب قطعة إلى مكانها في الصورة'},900)}}
function testAudio(){unlock();prefs.name=String($('childNameInput').value||prefs.name||'نور').replace(/^\s+|\s+$/g,'')||'نور';prefs.lang=$('voiceLangSelect').value;prefs.audioMode=$('audioModeSelect').value;playImageName(function(){playCheer()})}
function bindPanel(){if($('settingsBtn'))$('settingsBtn').onclick=openSettings;if($('closeAudioSettings'))$('closeAudioSettings').onclick=closeSettings;if($('saveAudioSettings'))$('saveAudioSettings').onclick=saveSettings;if($('testPictureAudio'))$('testPictureAudio').onclick=testAudio;var p=$('audioSettingsPanel');if(p)p.onclick=function(e){if(e.target===p)closeSettings()}}
function registerV2(){if('serviceWorker'in navigator&&location.protocol.indexOf('http')===0){try{navigator.serviceWorker.register('sw.js?v=2',{updateViaCache:'none'}).then(function(r){try{r.update()}catch(e){}})}catch(e){}}}
loadPrefs();fetchRegistry();installSpeechGuard();bindUnlock();bindPanel();observeGame();registerV2();
})();
