import json,pathlib
R=pathlib.Path(__file__).resolve().parents[4]; A=R/'apps/4-8/maker-solutions-lab';(A/'data').mkdir(exist_ok=True);(A/'assets').mkdir(exist_ok=True);(A/'src').mkdir(exist_ok=True);(A/'test').mkdir(exist_ok=True)
def pair(ar,en):return {'ar':ar,'en':en}
projects=[]
def project(id,title,need,condition,extended,protocol,materials,steps,params,obs):
 projects.append(dict(id=id,title=pair(*title),need=pair(*need),condition=pair(*condition),extended=pair(*extended),protocol=pair(*protocol),materials=[pair(*x) for x in materials],steps=[pair(*x) for x in steps],params=[dict(id=k,label=pair(*label),values=[pair(*v) for v in vals]) for k,label,vals in params],observations=[pair(*x) for x in obs]))
project('book',('حامل كتاب','Book stand'),('أريد رؤية الكتاب مفتوحًا دون إمساكه.','I want to see the open book without holding it.'),('يبقى الكتاب الخفيف على الحامل.','The light book stays on the stand.'),('تظل الصفحة ظاهرة أيضًا.','The page also stays visible.'),('استخدم الكتاب الخفيف نفسه. ضعه مفتوحًا على الحامل ثم ارفع يدك بهدوء وراقب ثباته.','Use the same light book. Place it open on the stand, gently release it and watch whether it stays.'),[('ورق مقوّى كبير','Large card'),('ورق كبير مطوي','Large folded paper')],[('يجهز البالغ الورق والثنيات.','An adult prepares the card and folds.'),('كوّن قاعدة ومسندًا ثم ضع الكتاب الخفيف.','Make a base and back support, then place the light book.')],[('base',('القاعدة','Base'),[('ضيقة','Narrow'),('متوسطة','Medium'),('واسعة','Wide')]),('back',('المسند','Back support'),[('قصير','Short'),('متوسط','Medium'),('عالٍ','Tall')]),('lip',('حافة التثبيت','Holding lip'),[('منخفضة','Low'),('متوسطة','Medium'),('عالية','High')])],[('مال الحامل أو انزلق الكتاب.','The stand tipped or the book slipped.'),('بقي الكتاب ثابتًا.','The book stayed in place.'),('بقي ثابتًا والصفحة واضحة.','It stayed and the page was clear.')])
project('house',('بيت لدمية','Toy house'),('أريد بيتًا تستطيع الدمية الكبيرة دخوله.','I want a house the large toy can enter.'),('تمر الدمية الكبيرة عبر الباب دون دفع.','The large toy passes through the door without pushing.'),('يبقى السقف فوق الدمية بعد دخولها.','The roof stays above the toy after it enters.'),('استخدم الدمية الكبيرة نفسها. أدخلها عبر الباب دون ضغط ثم انظر إلى السقف.','Use the same large toy. Pass it through the door without forcing it, then look at the roof.'),[('علبة كرتون كبيرة','Large cardboard box'),('ورق مقوّى كبير','Large card')],[('يفتح البالغ الباب في الكرتون قبل النشاط.','An adult prepares the doorway before the activity.'),('اختر حجم الباب وثبّت السقف مع البالغ.','Choose the doorway size and attach the roof with an adult.')],[('width',('عرض الباب','Door width'),[('ضيق','Narrow'),('متوسط','Medium'),('واسع','Wide')]),('height',('ارتفاع الباب','Door height'),[('منخفض','Low'),('متوسط','Medium'),('عالٍ','Tall')]),('roof',('ارتفاع السقف','Roof height'),[('منخفض','Low'),('متوسط','Medium'),('عالٍ','Tall')])],[('لم تمر الدمية بسهولة.','The toy did not pass easily.'),('مرت الدمية عبر الباب.','The toy passed through the door.'),('مرت وبقي السقف فوقها.','It passed and the roof stayed above it.')])
project('track',('مسار كرة كبيرة','Large ball track'),('أريد إيصال الكرة إلى مكان محدد.','I want the ball to reach a chosen place.'),('تصل الكرة داخل الدائرة المرئية.','The ball reaches the visible circle.'),('تبقى الكرة بين الحافتين طوال المسار.','The ball stays between the rails along the track.'),('استخدم الكرة الكبيرة نفسها ونقطة البداية نفسها. اتركها دون دفع وراقب موضع وصولها.','Use the same large ball and starting point. Release it without pushing and watch where it arrives.'),[('كرتون كبير مطوي','Large folded card'),('ورق مقوّى كبير','Large card')],[('ضع المسار منخفضًا على الأرض.','Keep the track low on the floor.'),('ثبّت الحافتين وارسم دائرة الوصول.','Attach the side rails and mark the target circle.')],[('slope',('ميل المسار','Track slope'),[('هادئ','Gentle'),('متوسط','Medium'),('شديد','Steep')]),('rail',('الحافتان','Side rails'),[('منخفضتان','Low'),('متوسطتان','Medium'),('عاليتان','High')]),('target',('دائرة الوصول','Target circle'),[('قريبة','Near'),('وسط','Middle'),('بعيدة','Far')])],[('توقفت خارج الدائرة.','It stopped outside the circle.'),('وصلت داخل الدائرة.','It reached the circle.'),('وصلت وبقيت بين الحافتين.','It reached the circle and stayed between the rails.')])
project('box',('علبة ترتيب','Sorting box'),('أريد إيجاد نوعين من ألعابي بسهولة.','I want to find two kinds of toys easily.'),('يبقى كل نوع في قسم منفصل.','Each kind stays in a separate section.'),('تسع الأقسام الألعاب الكبيرة دون ضغط.','The sections fit the large toys without squeezing.'),('ضع الألعاب الكبيرة نفسها في القسمين. حرّك العلبة برفق على الطاولة وراقب الفصل والمساحة.','Place the same large toys in both sections. Gently move the box on the table and watch separation and space.'),[('علبة كرتون كبيرة','Large cardboard box'),('ورق مقوّى مطوي','Folded card')],[('اختر نوعين من أغراض اللعب الكبيرة.','Choose two kinds of large play objects.'),('ضع حاجزًا في العلبة واختبر المساحة.','Place a divider in the box and test the space.')],[('divider',('الحاجز','Divider'),[('منخفض','Low'),('متوسط','Medium'),('عالٍ','High')]),('space',('المساحة','Space'),[('ضيقة','Narrow'),('متوسطة','Medium'),('واسعة','Wide')]),('edge',('حافة العلبة','Box edge'),[('منخفضة','Low'),('متوسطة','Medium'),('عالية','High')])],[('اختلطت الأغراض أو لم تتسع.','The objects mixed or did not fit.'),('بقي النوعان منفصلين.','The two kinds stayed separate.'),('بقي كل نوع منفصلًا وله مساحة.','Each kind stayed separate with enough space.')])
project('bridge',('جسر لعب','Play bridge'),('أريد عبور لعبة خفيفة فوق فجوة صغيرة.','I want a light toy to cross a small gap.'),('يبقى الجسر تحت لعبة خفيفة.','The bridge holds a light toy.'),('يبقى طرفاه على الدعامتين.','Both ends stay on the supports.'),('استخدم اللعبة الخفيفة والفجوة نفسيهما. ضع اللعبة في الوسط دون ضغط. لا تحمل إنسانًا على الجسر.','Use the same light toy and gap. Place the toy in the middle without pressing. Never put a person on the bridge.'),[('ورقة كبيرة','Large paper sheet'),('ورق مقوّى كبير','Large card')],[('يجهز البالغ دعامتين منخفضتين وثنيات الورق.','An adult prepares two low supports and paper folds.'),('ضع الورقة فوق الفجوة ثم اللعبة الخفيفة.','Place the paper over the gap, then the light toy.')],[('fold',('شكل الطي','Fold shape'),[('مسطح','Flat'),('ثنية واحدة','One fold'),('ثنيات متتابعة','Accordion folds')]),('span',('امتداد الجسر','Bridge length'),[('قصير','Short'),('متوسط','Medium'),('طويل','Long')]),('support',('الدعامتان','Supports'),[('ضيقتان','Narrow'),('متوسطتان','Medium'),('واسعتان','Wide')])],[('هبط الجسر أو تحرك طرفه.','The bridge sagged or an end moved.'),('حمل اللعبة الخفيفة.','It held the light toy.'),('حملها وبقي الطرفان ثابتين.','It held it and both ends stayed in place.')])
project('drawing',('حماية رسمة','Protect a drawing'),('أريد حفظ رسمتي مع رؤية جزء منها.','I want to protect my drawing and still see it.'),('تبقى الرسمة داخل الغلاف دون أن تختفي كلها.','The drawing stays in its sleeve without being fully hidden.'),('يسهل إخراج الرسمة وإعادتها برفق.','The drawing can be gently removed and returned.'),('استخدم الرسمة نفسها. حرّك الغلاف برفق ثم أخرج الرسمة وأعدها دون شد.','Use the same drawing. Gently move the sleeve, then remove and replace the drawing without pulling hard.'),[('ورق مقوّى كبير','Large card'),('ورق كبير مطوي','Large folded paper')],[('يجهز البالغ نافذة الغلاف وزواياه.','An adult prepares the sleeve window and corners.'),('ضع الرسمة تحت الزوايا واترك جزءًا ظاهرًا.','Put the drawing under the corners and leave part visible.')],[('window',('النافذة','Window'),[('مغلقة','Closed'),('وسط','Medium'),('واسعة','Wide')]),('corner',('زوايا التثبيت','Holding corners'),[('قصيرة','Short'),('متوسطة','Medium'),('كبيرة','Large')]),('opening',('فتحة الإخراج','Removal opening'),[('ضيقة','Narrow'),('متوسطة','Medium'),('واسعة','Wide')])],[('اختفت الرسمة أو خرجت من الغلاف.','The drawing was hidden or fell out.'),('بقيت الرسمة وجزء منها ظاهر.','It stayed with part visible.'),('بقيت واضحة وسهل إخراجها وإعادتها.','It stayed visible and was easy to remove and replace.')])
ui={
 'intro':pair('نلاحظ مشكلة، نصمم حلًا، ثم نجرب تغييرًا واحدًا.','Notice a problem, design a solution, then try one change.'),
 'plan':pair('لمن نصنع الحل؟ اختر المواد والاستعداد.','Who is the solution for? Choose materials and readiness.'),
 'design1':pair('اصنع نموذجك الأول بالأزرار وارسم فكرتك إن أحببت.','Make your first model with the buttons and sketch your idea if you like.'),
 'test1':pair('احفظ النموذج الأول، ثم اختبره وسجل ما لاحظته.','Keep the first model, then test it and record what you noticed.'),
 'design2':pair('غيّر جزءًا واحدًا من النموذج الأول واشرح السبب.','Change one part of the first model and explain why.'),
 'test2':pair('اختبر النموذج الثاني بالطريقة نفسها قبل المقارنة.','Test the second model in the same way before comparing.'),
 'review':pair('انظر إلى النموذجين. ما الذي تغير؟ وما الخطوة التالية؟','Look at both models. What changed, and what will you try next?'),
 'safety':pair('يجهز البالغ القطع واللاصق. استخدم مواد كبيرة آمنة ولعبًا خفيفًا فقط. لا حرارة أو أسلاك أو أدوات حادة مستقلة، ولا وزن إنسان على النموذج.','An adult prepares cutting and tape. Use large safe materials and light toys only. No heat, wires, independent sharp tools, or human weight on models.'),
 'screen':pair('نموذج الشاشة','Screen model'),'real':pair('بناء في الواقع','Physical build'),
 'screenNote':pair('هذه محاكاة مبسطة لها قواعد ظاهرة، وليست قياسًا لقوة الورق الحقيقي. جرّب بالأزرار ثم راقب النتيجة.','This simplified model uses visible rules. It does not measure real paper strength. Try the controls and observe the result.'),
 'entry':pair('مدخل • قالب ومادة واحدة','Entry • template and one material'),
 'practice':pair('ممارسة • اختيارات واختبار شرط','Practice • choices and one condition'),
 'extend':pair('توسع • شرطان ومستخدم آخر','Extend • two conditions and another user'),
 'help':pair('يمكنك طلب المساعدة أو التوقف. المحاولة ليست مسابقة.','You can ask for help or pause. This is not a competition.'),
 'reason':pair('أريد تغيير هذا الجزء لنجرب تحسين نتيجة الاختبار.','I want to change this part to try to improve the test result.'),
 'nextIdea':pair('سأجرب الحل مع مستخدم آخر وألاحظ احتياجه.','I will try the solution with another user and notice their needs.'),
 'saved':pair('حفظنا مقارنة المحاولتين. ما زال بإمكانك تجربة حل آخر.','Your comparison is saved. You can still try another solution.')}
# every authored narration gets one public recording with real word cues
items=[]
for key,v in ui.items():
 for lang,text in v.items():items.append(dict(language=lang,text=text,path=f'audio/{lang}/ui-{key}.mp3'))
for p in projects:
 for key in ['title','need','condition','extended','protocol']:
  for lang,text in p[key].items():items.append(dict(language=lang,text=text,path=f'audio/{lang}/{p["id"]}-{key}.mp3'))
for p in projects:
 for param in p['params']:
  for i,value in enumerate(param['values']):
   value['spoken']=pair(param['label']['ar']+': '+value['ar']+'.',param['label']['en']+': '+value['en']+'.')
   value['audio']={}
   for language in ['ar','en']:
    path=f'audio/{language}/{p["id"]}-{param["id"]}-{i}.mp3'
    value['audio'][language]=path
    items.append(dict(language=language,text=value['spoken'][language],path=path))
(A/'data/audio-manifest.json').write_text(json.dumps(dict(voices={'ar':'ar-SA-ZariyahNeural','en':'en-US-JennyNeural'},rate='-10%',items=items),ensure_ascii=False,indent=2)+'\n')
(A/'src/content.js').write_text('window.MAKER_CONTENT='+json.dumps(dict(projects=projects,ui=ui),ensure_ascii=False,separators=(',',':'))+';\n')
