(function(){
'use strict';
var BUILD='15',registry=null,mode='auto',currentAudio=null,loading=false,unlocked=false;
function $(id){return document.getElementById(id)}
function trim(s){return(''+(s||'')).replace(/^\s+|\s+$/g,'')}
function norm(s){return trim(s).toLowerCase().replace(/[ًٌٍَُِّْـ،,.!؟?؛;:\-–—]/g,'').replace(/\s+/g,' ')}
function storeGet(k,d){try{var v=localStorage.getItem(k);return v===null?d:v}catch(e){return d}}
function storeSet(k,v){try{localStorage.setItem(k,v)}catch(e){}}
function username(){try{if(window.PenKidsCore&&PenKidsCore.getUserName)return trim(PenKidsCore.getUserName())||'نور'}catch(e){}return'نور'}
function setStatus(s){try{if(window.PenKidsCore&&PenKidsCore.setStatus)PenKidsCore.setStatus(s);else if($('statusText'))$('statusText').innerHTML=s}catch(e){}}
function setInfo(s){var e=$('bundledAudioInfo');if(e)e.innerHTML=s}
function ua(){return navigator.userAgent||''}
function androidVersion(){var m=ua().match(/Android\s+([0-9.]+)/i);return m?parseFloat(m[1])||0:0}
function chromeVersion(){var m=ua().match(/(?:Chrome|CriOS)\/([0-9]+)/i);return m?parseInt(m[1],10)||0:0}
function isLegacy(){var av=androidVersion(),cv=chromeVersion(),u=ua();if(av&&av<5)return true;if(cv&&cv<50)return true;if(/Android 4\.|Version\/4\.|BigTAB|DMTAB/i.test(u))return true;return false}
function isMobile(){return /Android|iPhone|iPad|iPod|Mobile/i.test(ua())}
function xhrJson(url,ok,fail){try{var x=new XMLHttpRequest();x.open('GET',url+(url.indexOf('?')>=0?'&':'?')+'_='+(+new Date()),true);try{x.setRequestHeader('Cache-Control','no-cache')}catch(e){}x.onreadystatechange=function(){if(x.readyState===4){if((x.status>=200&&x.status<300)||x.status===0){try{ok(JSON.parse(x.responseText))}catch(e){if(fail)fail(e)}}else if(fail)fail(new Error('HTTP '+x.status))}};x.send(null)}catch(e){if(fail)fail(e)}}
function loadRegistry(cb){if(registry){if(cb)cb(true);return}if(loading){setTimeout(function(){loadRegistry(cb)},120);return}loading=true;xhrJson('audio/registry.json?v='+BUILD,function(j){registry=j||{};loading=false;refreshInfo();if(cb)cb(true)},function(){registry=null;loading=false;refreshInfo();if(cb)cb(false)})}
function userEntry(){if(!registry||!registry.users)return null;var n=norm(username()),k,u,a,i;if(n==='noor'||n==='nour'||n==='nur'||n==='noour'||n==='نور')return registry.users['نور']||registry.users.noor||null;if(registry.users[username()])return registry.users[username()];for(k in registry.users){if(registry.users.hasOwnProperty(k)){u=registry.users[k];a=u.aliases||[];if(norm(k)===n)return u;for(i=0;i<a.length;i++)if(norm(a[i])===n)return u}}return null}
function matchClip(list,text){var n=norm(text),i,j,c,a;for(i=0;i<(list||[]).length;i++){c=list[i];if(norm(c.text)===n)return c;if(c.name&&norm(c.name)===n)return c;a=c.aliases||[];for(j=0;j<a.length;j++)if(norm(a[j])===n)return c}return null}
function colorClip(text){var arr=registry&&registry.colors||[],c=matchClip(arr,text),n,i;if(c)return c;n=norm(text).replace(/^اللون\s+/,'').replace(/^لون\s+/,'');for(i=0;i<arr.length;i++)if(norm(arr[i].name)===n)return arr[i];return null}
function clipFor(text){var c=colorClip(text),u,clips,n,i,cheers=[];if(c)return c;u=userEntry();clips=u&&u.clips||[];c=matchClip(clips,text);if(c)return c;n=norm(text);if(n.indexOf('اختبار')>=0||n.indexOf('مرحبا')>=0){for(i=0;i<clips.length;i++)if(clips[i].id==='test')return clips[i]}for(i=0;i<clips.length;i++)if(clips[i].kind==='cheer')cheers.push(clips[i]);return cheers.length?cheers[Math.floor(Math.random()*cheers.length)]:null}
function compatFiles(c){var r=[],f=c&&c.files||null;if(f){if(typeof f==='string')r.push({src:f,type:''});else if(f.length){for(var i=0;i<f.length;i++){if(typeof f[i]==='string')r.push({src:f[i],type:''});else if(f[i]&&f[i].src)r.push(f[i])}}else{if(f.mp3)r.push({src:f.mp3,type:'audio/mpeg'});if(f.ogg)r.push({src:f.ogg,type:'audio/ogg'});if(f.wav)r.push({src:f.wav,type:'audio/wav'})}}if(!r.length&&c&&c.file)r.push({src:c.file,type:/\.ogg$/i.test(c.file)?'audio/ogg':/\.wav$/i.test(c.file)?'audio/wav':'audio/mpeg'});return r}
function fileUrl(f){if(!f)return'';return f+(f.indexOf('?')>=0?'&':'?')+'v='+BUILD}
function ensurePlayer(){var a=$('legacyAudioPlayer');if(!a){a=document.createElement('audio');a.id='legacyAudioPlayer';a.setAttribute('preload','auto');a.setAttribute('playsinline','playsinline');a.style.position='absolute';a.style.width='1px';a.style.height='1px';a.style.opacity='0.01';a.style.left='-9999px';a.controls=false;document.body.appendChild(a)}return a}
function stopFile(){try{var a=currentAudio||$('legacyAudioPlayer');if(a){a.pause();try{a.currentTime=0}catch(e){}}}catch(e){}currentAudio=null}
function addSources(a,files){while(a.firstChild)a.removeChild(a.firstChild);var ordered=[],i,f,canMp3='',canOgg='',canWav='';try{canMp3=a.canPlayType('audio/mpeg')||'';canOgg=a.canPlayType('audio/ogg; codecs="vorbis"')||'';canWav=a.canPlayType('audio/wav; codecs="1"')||''}catch(e){}function pushType(t){for(i=0;i<files.length;i++){f=files[i];if(f.type===t)ordered.push(f)}}if(isLegacy()){if(canMp3)pushType('audio/mpeg');if(canOgg)pushType('audio/ogg');if(canWav)pushType('audio/wav');pushType('')}else{if(canMp3)pushType('audio/mpeg');if(canOgg)pushType('audio/ogg');if(canWav)pushType('audio/wav');pushType('')}if(!ordered.length)ordered=files.slice(0);for(i=0;i<ordered.length;i++){f=ordered[i];var s=document.createElement('source');s.src=fileUrl(f.src);if(f.type)s.type=f.type;a.appendChild(s)}if(ordered.length)a.src=fileUrl(ordered[0].src)}
function playClip(c,onDone){if(!c)return false;var files=compatFiles(c);if(!files.length)return false;stopFile();try{var a=ensurePlayer();currentAudio=a;addSources(a,files);a.preload='auto';a.volume=1;a.onended=function(){currentAudio=null;if(onDone)onDone(true)};a.onerror=function(){currentAudio=null;if(onDone)onDone(false)};try{a.load()}catch(e){}var p=a.play();if(p&&typeof p.then==='function'){p.then(function(){setStatus(c.kind==='color'?'🔊 نطق اللون من الملف المسجل':'🔊 الصوت المسجل يعمل')},function(){currentAudio=null;if(onDone)onDone(false)})}else{setStatus(c.kind==='color'?'🔊 نطق اللون من الملف المسجل':'🔊 الصوت المسجل يعمل')}return true}catch(e){if(onDone)onDone(false);return false}}
function playFile(text,onDone){return playClip(clipFor(text),onDone)}
function customFallback(){try{var b=$('testCustomBtn');if(b){b.click();return true}}catch(e){}return false}
function voiceKey(v){return(v.voiceURI||v.name||'')+'|'+(v.lang||'')}
function isArabic(v){var l=((v&&v.lang)||'').toLowerCase(),n=((v&&v.name)||'').toLowerCase();return l.indexOf('ar')===0||n.indexOf('arab')>=0||n.indexOf('عرب')>=0}
function selectedVoice(){var vs=[],i,s=$('voiceSelect'),key=s?s.value:'auto';try{vs=speechSynthesis.getVoices()||[]}catch(e){}if(key&&key!=='auto')for(i=0;i<vs.length;i++)if(voiceKey(vs[i])===key)return vs[i];for(i=0;i<vs.length;i++)if(isArabic(vs[i]))return vs[i];return null}
function nativeSpeak(text,done){if(!(window.speechSynthesis&&window.SpeechSynthesisUtterance)){done(false,'no-api');return}var synth=window.speechSynthesis,v=selectedVoice();if(!isMobile()&&!v){done(false,'no-arabic-desktop-voice');return}var u,started=false,finished=false,timer;try{try{synth.cancel()}catch(e){}try{if(synth.paused&&synth.resume)synth.resume()}catch(e){}u=new SpeechSynthesisUtterance(text);u.lang=v?(v.lang||'ar-SA'):'ar-SA';if(v)u.voice=v;var r=$('rateSelect');u.rate=r?(parseFloat(r.value)||.86):.86;u.pitch=1;u.volume=1;u.onstart=function(){started=true;setStatus('🔊 الصوت التلقائي يعمل')};u.onend=function(){if(finished)return;finished=true;if(timer)clearTimeout(timer);done(true,'ended')};u.onerror=function(){if(finished)return;finished=true;if(timer)clearTimeout(timer);done(false,'error')};synth.speak(u);timer=setTimeout(function(){if(started||finished)return;finished=true;try{synth.cancel()}catch(e){}done(false,'timeout')},1200)}catch(e){done(false,'exception')}}
function fallback(text){if(playFile(text,function(ok){if(!ok)customFallback()}))return true;return customFallback()}
function speak(text,allowFallback){var c=clipFor(text);if(mode==='files'){if(c&&playClip(c,function(ok){if(!ok)customFallback()}))return true;return customFallback()}if(mode==='tts'){nativeSpeak(text,function(ok){if(!ok)setStatus('تعذر تشغيل صوت الجهاز. يمكنك اختيار «الملفات المسجلة» يدوياً.')});return true}if(isLegacy()&&c){if(playClip(c,function(ok){if(!ok)nativeSpeak(text,function(ok2){if(!ok2&&allowFallback!==false)customFallback()})}))return true}nativeSpeak(text,function(ok){if(!ok&&allowFallback!==false)fallback(text)});return true}
function unlock(){if(unlocked)return;unlocked=true;ensurePlayer();loadRegistry(function(){var c=clipFor('مرحبا يا '+username()+' هذا اختبار للصوت المسجل');if(!c)return;var a=ensurePlayer();try{addSources(a,compatFiles(c));a.muted=true;a.volume=0;try{a.load()}catch(e){}var p=a.play();if(p&&typeof p.then==='function')p.then(function(){try{a.pause();a.currentTime=0;a.muted=false;a.volume=1}catch(e){}},function(){try{a.muted=false;a.volume=1}catch(e){}})}catch(e){try{a.muted=false;a.volume=1}catch(x){}}})}
function refreshInfo(){var u=userEntry(),colors=registry&&registry.colors||[],legacy=isLegacy();if(!u){setInfo('لا توجد حزمة مطابقة حرفياً للاسم «'+username()+'». توجد '+colors.length+' ملفات ألوان عامة. إذا كان المقصود نور فاكتب Noor أو Nour أو Nur أو نور. '+(legacy?'تم اكتشاف جهاز/متصفح قديم وسيعطي التطبيق أولوية للملفات المسجلة.':''));return}setInfo('✅ حزمة الصوت للاسم «'+username()+'» جاهزة. 🎨 الألوان: '+colors.length+' ملفات. '+(legacy?'📻 تم اكتشاف جهاز قديم: الوضع التلقائي سيستخدم الملفات المسجلة أولاً وبصيغ MP3/OGG/WAV المتوافقة.':'الوضع التلقائي يجرب صوت الجهاز ثم الملفات المسجلة.'))}
function injectUI(){var box=$('voiceSelect');if(!box||$('audioModeSelect'))return;var p=box.parentNode&&box.parentNode.parentNode;if(!p)return;var wrap=document.createElement('div');wrap.style.margin='8px 0';wrap.innerHTML='<label style="display:block;margin:6px">طريقة الصوت <select id="audioModeSelect" style="min-width:260px"><option value="auto">تلقائي ذكي: الأنسب للجهاز</option><option value="files">الملفات المسجلة فقط</option><option value="tts">صوت الجهاز الآلي فقط</option></select></label><button id="testBundledAudioBtn" type="button">🎧 اختبار صوت الاسم المسجل</button><button id="testColorAudioBtn" type="button">🎨 اختبار صوت الألوان</button><button id="testLegacyAudioBtn" type="button">📻 اختبار توافق الجهاز القديم</button><div id="bundledAudioInfo" style="font-size:11px;line-height:1.8;margin:7px;padding:8px;border-radius:6px;background:#eef8ff"></div>';p.appendChild(wrap);var s=$('audioModeSelect');mode=storeGet('pk_audio_mode','auto');s.value=mode;if(s.selectedIndex<0){mode='auto';s.value='auto'}s.onchange=function(){mode=this.value;storeSet('pk_audio_mode',mode);refreshInfo();setStatus(mode==='files'?'تم اختيار الملفات المسجلة يدوياً':mode==='tts'?'تم اختيار صوت الجهاز الآلي يدوياً':'تم اختيار الوضع التلقائي الذكي')};$('testBundledAudioBtn').onclick=function(){loadRegistry(function(){if(!playFile('مرحبا يا '+username()+'، هذا اختبار للصوت المسجل',function(ok){if(!ok)setStatus('تعذر تشغيل ملف الاسم المسجل')}))setStatus('لا توجد ملفات صوت مسجلة لهذا الاسم')})};$('testColorAudioBtn').onclick=function(){loadRegistry(function(){if(!playFile('اللون أزرق',function(ok){if(!ok)setStatus('تعذر تشغيل ملف اللون')}))setStatus('لا توجد حزمة ألوان مسجلة')})};$('testLegacyAudioBtn').onclick=function(){loadRegistry(function(){var c=clipFor('اللون أحمر');if(!c){setStatus('تعذر العثور على ملف اختبار الجهاز القديم');return}if(playClip(c,function(ok){setStatus(ok?'✅ الصوت المسجل متوافق مع هذا الجهاز':'تعذر تشغيل صيغ الصوت المسجلة على هذا المتصفح')}))setStatus('📻 جارٍ اختبار MP3/OGG/WAV مباشرة بدون TTS')})};refreshInfo()}
function watchName(){var b=$('saveUserBtn');if(b)b.addEventListener('click',function(){setTimeout(function(){refreshInfo();unlock()},80)},false)}
function init(){mode=storeGet('pk_audio_mode','auto');ensurePlayer();injectUI();watchName();loadRegistry();document.addEventListener('mousedown',unlock,false);document.addEventListener('touchstart',unlock,false);document.addEventListener('keydown',unlock,false);setTimeout(injectUI,500);setTimeout(refreshInfo,900);setTimeout(function(){var db=$('desktopAudioTest');if(db)db.onclick=function(){loadRegistry(function(){speak('مرحبا يا '+username()+'، هذا اختبار للصوت المسجل',true)})}},650)}
window.Audio360={speak:function(text,allowFallback){loadRegistry();return speak(text,allowFallback)},playRecorded:function(text){loadRegistry(function(){playFile(text)});return true},stop:function(){stopFile();try{speechSynthesis.cancel()}catch(e){}},reload:function(){registry=null;loadRegistry()},mode:function(){return mode},isLegacy:isLegacy};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,false);else init();
})();
