(function(){
'use strict';
var BUILD='13',registry=null,mode='auto',currentAudio=null,unlocked=false,loading=false;
function $(id){return document.getElementById(id)}
function trim(s){return(''+(s||'')).replace(/^\s+|\s+$/g,'')}
function norm(s){return trim(s).toLowerCase().replace(/[ًٌٍَُِّْـ،,.!؟?؛;:\-–—]/g,'').replace(/\s+/g,' ')}
function storeGet(k,d){try{var v=localStorage.getItem(k);return v===null?d:v}catch(e){return d}}
function storeSet(k,v){try{localStorage.setItem(k,v)}catch(e){}}
function username(){try{if(window.PenKidsCore&&PenKidsCore.getUserName)return trim(PenKidsCore.getUserName())||'نور'}catch(e){}return'نور'}
function setStatus(s){try{if(window.PenKidsCore&&PenKidsCore.setStatus)PenKidsCore.setStatus(s);else if($('statusText'))$('statusText').innerHTML=s}catch(e){}}
function setInfo(s){var e=$('bundledAudioInfo');if(e)e.innerHTML=s}
function isMobile(){return /Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent||'')}
function xhrJson(url,ok,fail){try{var x=new XMLHttpRequest();x.open('GET',url+(url.indexOf('?')>=0?'&':'?')+'_='+(+new Date()),true);try{x.setRequestHeader('Cache-Control','no-cache')}catch(e){}x.onreadystatechange=function(){if(x.readyState===4){if(x.status>=200&&x.status<300){try{ok(JSON.parse(x.responseText))}catch(e){if(fail)fail(e)}}else if(fail)fail(new Error('HTTP '+x.status))}};x.send(null)}catch(e){if(fail)fail(e)}}
function loadRegistry(cb){if(registry){if(cb)cb(true);return}if(loading){setTimeout(function(){loadRegistry(cb)},150);return}loading=true;xhrJson('audio/registry.json?v='+BUILD,function(j){registry=j||{};loading=false;refreshInfo();if(cb)cb(true)},function(){registry=null;loading=false;refreshInfo();if(cb)cb(false)})}
function userEntry(){if(!registry||!registry.users)return null;var n=username(),k;if(registry.users[n])return registry.users[n];for(k in registry.users){if(registry.users.hasOwnProperty(k)){var u=registry.users[k],a=u.aliases||[],i;if(norm(k)===norm(n))return u;for(i=0;i<a.length;i++)if(norm(a[i])===norm(n))return u}}return null}
function fileUrl(f){if(!f)return'';return f+(f.indexOf('?')>=0?'&':'?')+'v='+BUILD}
function clipFor(text){var u=userEntry(),clips=u&&u.clips||[],n=norm(text),i,c,a,j;if(!clips.length)return null;for(i=0;i<clips.length;i++){c=clips[i];if(norm(c.text)===n)return c;a=c.aliases||[];for(j=0;j<a.length;j++)if(norm(a[j])===n)return c}if(n.indexOf('اختبار')>=0||n.indexOf('مرحبا')>=0){for(i=0;i<clips.length;i++)if(clips[i].id==='test')return clips[i]}if(n.indexOf('اللون ')===0){for(i=0;i<clips.length;i++)if(clips[i].id&&clips[i].id.indexOf('color-')===0&&norm(clips[i].text)===n)return clips[i]}var cheers=[];for(i=0;i<clips.length;i++)if(clips[i].kind==='cheer')cheers.push(clips[i]);return cheers.length?cheers[Math.floor(Math.random()*cheers.length)]:clips[0]}
function stopFile(){try{if(currentAudio){currentAudio.pause();currentAudio.currentTime=0}}catch(e){}currentAudio=null}
function playFile(text,onDone){var c=clipFor(text);if(!c||!c.file)return false;stopFile();try{var a=new Audio(fileUrl(c.file));currentAudio=a;a.preload='auto';a.volume=1;a.onended=function(){currentAudio=null;if(onDone)onDone(true)};a.onerror=function(){currentAudio=null;if(onDone)onDone(false)};var p=a.play();if(p&&p.then){p.then(function(){setStatus('🔊 الصوت المسجل يعمل')}).catch(function(){currentAudio=null;if(onDone)onDone(false)})}else setStatus('🔊 الصوت المسجل يعمل');return true}catch(e){if(onDone)onDone(false);return false}}
function customFallback(){try{var b=$('testCustomBtn');if(b){b.click();return true}}catch(e){}return false}
function voiceKey(v){return(v.voiceURI||v.name||'')+'|'+(v.lang||'')}
function isArabic(v){var l=((v&&v.lang)||'').toLowerCase(),n=((v&&v.name)||'').toLowerCase();return l.indexOf('ar')===0||n.indexOf('arab')>=0||n.indexOf('عرب')>=0}
function selectedVoice(){var vs=[],i,s=$('voiceSelect'),key=s?s.value:'auto';try{vs=speechSynthesis.getVoices()||[]}catch(e){}if(key&&key!=='auto')for(i=0;i<vs.length;i++)if(voiceKey(vs[i])===key)return vs[i];for(i=0;i<vs.length;i++)if(isArabic(vs[i]))return vs[i];return null}
function nativeSpeak(text,done){if(!(window.speechSynthesis&&window.SpeechSynthesisUtterance)){done(false,'no-api');return}var synth=window.speechSynthesis,v=selectedVoice();if(!isMobile()&&!v){done(false,'no-arabic-desktop-voice');return}var u,started=false,finished=false,timer;try{try{synth.cancel()}catch(e){}try{if(synth.paused&&synth.resume)synth.resume()}catch(e){}u=new SpeechSynthesisUtterance(text);u.lang=v?(v.lang||'ar-SA'):'ar-SA';if(v)u.voice=v;var r=$('rateSelect');u.rate=r?(parseFloat(r.value)||.86):.86;u.pitch=1;u.volume=1;u.onstart=function(){started=true;setStatus('🔊 الصوت التلقائي يعمل')};u.onend=function(){if(finished)return;finished=true;if(timer)clearTimeout(timer);done(true,'ended')};u.onerror=function(){if(finished)return;finished=true;if(timer)clearTimeout(timer);done(false,'error')};synth.speak(u);timer=setTimeout(function(){if(started||finished)return;finished=true;try{synth.cancel()}catch(e){}done(false,'timeout')},1200)}catch(e){done(false,'exception')}}
function fallback(text){if(playFile(text,function(ok){if(!ok)customFallback()}))return true;return customFallback()}
function speak(text,allowFallback){if(mode==='files'){if(playFile(text,function(ok){if(!ok)customFallback()}))return true;customFallback();return true}if(mode==='tts'){nativeSpeak(text,function(ok){if(!ok)setStatus('تعذر تشغيل صوت المتصفح. اختر «تلقائي» ليعمل الصوت المسجل تلقائياً.')});return true}var u=userEntry();nativeSpeak(text,function(ok){if(!ok&&allowFallback!==false){if(u)fallback(text);else customFallback()}});return true}
function unlock(){if(unlocked)return;unlocked=true;loadRegistry(function(){var c=clipFor('مرحبا يا '+username()+' هذا اختبار للصوت المسجل');if(!c)return;try{var a=new Audio(fileUrl(c.file));a.muted=true;a.volume=0;a.play().then(function(){try{a.pause();a.currentTime=0;a.muted=false}catch(e){}}).catch(function(){})}catch(e){}})}
function refreshInfo(){var u=userEntry();if(!u){setInfo('لا توجد حالياً حزمة صوت مسجلة باسم «'+username()+'». سيستخدم التطبيق صوت الجهاز أو الملفات التي يضيفها المستخدم.');return}setInfo('✅ توجد حزمة صوت مسجلة باسم «'+username()+'» وبها '+((u.clips||[]).length)+' ملفاً. في الوضع التلقائي يستخدم صوت الجهاز أولاً، وإذا فشل ينتقل تلقائياً لهذه الملفات.')}
function injectUI(){var box=$('voiceSelect');if(!box||$('audioModeSelect'))return;var p=box.parentNode&&box.parentNode.parentNode;if(!p)return;var wrap=document.createElement('span');wrap.innerHTML='<label>طريقة الصوت <select id="audioModeSelect"><option value="auto">تلقائي: الجهاز ثم الملفات المسجلة</option><option value="tts">صوت الجهاز فقط</option><option value="files">الملفات المسجلة فقط</option></select></label><button id="testBundledAudioBtn" type="button">🎧 اختبار الملفات المضافة</button><div id="bundledAudioInfo" style="font-size:11px;line-height:1.7;margin:7px;padding:7px;border-radius:6px;background:#eef8ff"></div>';p.appendChild(wrap);var s=$('audioModeSelect');mode=storeGet('pk_audio_mode','auto');s.value=mode;if(s.selectedIndex<0){mode='auto';s.value='auto'}s.onchange=function(){mode=this.value;storeSet('pk_audio_mode',mode);refreshInfo()};$('testBundledAudioBtn').onclick=function(){loadRegistry(function(){if(!playFile('مرحبا يا '+username()+' هذا اختبار للصوت المسجل',function(ok){if(!ok)setStatus('تعذر تشغيل الملف المسجل في هذا المتصفح')}))setStatus('لا توجد ملفات صوت مسجلة لهذا الاسم')})};refreshInfo()}
function watchName(){var b=$('saveUserBtn');if(b)b.addEventListener('click',function(){setTimeout(function(){refreshInfo();unlock()},80)},false)}
function init(){mode=storeGet('pk_audio_mode','auto');injectUI();watchName();loadRegistry();document.addEventListener('mousedown',unlock,false);document.addEventListener('touchstart',unlock,false);document.addEventListener('keydown',unlock,false);setTimeout(injectUI,500);setTimeout(refreshInfo,900)}
window.Audio360={speak:function(text,allowFallback){loadRegistry();return speak(text,allowFallback)},playRecorded:function(text){loadRegistry(function(){playFile(text)});return true},stop:function(){stopFile();try{speechSynthesis.cancel()}catch(e){}},reload:function(){registry=null;loadRegistry()},mode:function(){return mode}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,false);else init();
})();
