(function(){
'use strict';
function ready(fn){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',fn,false);else fn()}
ready(function(){
 if(document.getElementById('childUiV12Style'))return;
 var d=document,$=function(id){return d.getElementById(id)};
 var st=d.createElement('style');st.id='childUiV12Style';st.type='text/css';st.innerHTML='\
#header{padding:8px 8px 6px!important;text-align:center}#header #tabs{display:none!important}#subtitle{display:none!important}#title{font-size:20px!important;margin:2px!important}\
#childTopBar{position:relative;z-index:24;background:#ffffff;border-bottom:1px solid #d8e7e6;padding:7px 5px;text-align:center;box-shadow:0 2px 7px rgba(0,0,0,.07)}\
#childTopBar button{min-height:46px;border:1px solid #b9d4d1;border-radius:12px;background:#f7fbfb;color:#17343a;font:700 15px Tahoma,Arial,sans-serif;margin:3px;padding:4px 12px}#childTopBar .main{background:#ffd54f;border-color:#e2b92e;color:#473800}#childTopBar .wide{min-width:120px}\
#topOptionsPanel{display:none;position:fixed;left:2%;right:2%;top:2%;bottom:2%;z-index:300;background:#fff;border:2px solid #0f8f8a;border-radius:16px;overflow:auto;padding:12px;box-sizing:border-box;box-shadow:0 8px 35px rgba(0,0,0,.3)}#topOptionsPanel.open{display:block}#topOptionsPanel h2{margin:5px 50px 10px;text-align:center;color:#08716c;font-size:20px}#topOptionsClose{position:absolute;left:10px;top:10px;min-height:38px;border:0;border-radius:10px;background:#edf2f2;padding:0 13px;font:bold 13px Tahoma}#topOptionsBody #tools,#topOptionsBody #lessonBar{display:block!important;background:#f8fbfb;border:1px solid #dbe9e8;border-radius:12px;margin:8px auto;padding:9px;max-width:900px}#topOptionsBody #tools button,#topOptionsBody #tools select{min-height:38px}\
#picker{z-index:420!important}#settingsPanel{z-index:430!important}#syncPanel{z-index:440!important}\
#drawStage{background:#fff;position:relative}#drawStage #colorBar{padding:7px 4px!important}#drawStage #drawQuickBar{position:relative!important;top:auto!important;z-index:20!important}#drawQuickBar button,#drawQuickBar select{min-height:38px!important;border-radius:9px!important}#drawQuickBar .v11Expand{background:#fff4c4!important;color:#563f00!important;font-weight:bold!important}\
#boardShell{height:68vh!important;min-height:360px!important}.drawFocus{position:fixed!important;left:0!important;right:0!important;top:0!important;bottom:0!important;z-index:210!important;background:#fff!important;overflow:hidden!important}.drawFocus #colorBar{height:auto}.drawFocus #drawQuickBar{position:relative!important}.drawFocus #boardShell{height:calc(100vh - 105px)!important;min-height:0!important;border-bottom:0!important}.childDrawFocus{overflow:hidden!important}\
#desktopAudioTest{background:#e8f3ff!important;border-color:#78aee8!important;font-weight:bold}.v11Hint{max-width:850px;margin:6px auto;padding:8px;border-radius:10px;background:#eef8ff;color:#345;line-height:1.65;font-size:12px}.v12VoiceState{max-width:850px;margin:5px auto;padding:7px;border-radius:9px;background:#fff9df;border:1px solid #eedc8e;color:#665821;font-size:11px;line-height:1.6}\
@media(max-width:700px){#childTopBar button{font-size:13px;min-height:43px;padding:3px 9px}#childTopBar .wide{min-width:auto}#title{font-size:18px!important}#boardShell{height:64vh!important;min-height:320px!important}.drawFocus #boardShell{height:calc(100vh - 112px)!important}#drawQuickBar button,#drawQuickBar select{min-height:36px!important}}';d.getElementsByTagName('head')[0].appendChild(st);
 var header=$('header'),tools=$('tools'),lesson=$('lessonBar'),color=$('colorBar'),quick=$('drawQuickBar'),board=$('boardShell');
 if(!header||!quick||!board)return;
 var top=d.createElement('div');top.id='childTopBar';top.innerHTML='<button id="v11Options" class="main wide">⚙️ الخيارات</button><button id="v11Audio">🔊 الصوت</button><button id="v11Sync">👥 جماعي</button><button id="v11Expand" class="wide">⛶ تكبير الرسم</button>';
 header.parentNode.insertBefore(top,header.nextSibling);
 var panel=d.createElement('div');panel.id='topOptionsPanel';panel.innerHTML='<button id="topOptionsClose">إغلاق</button><h2>⚙️ خيارات الرسم والتعلم</h2><div class="v11Hint">كل أدوات القلم والصوت والتشخيص والمساعدة موجودة هنا. عند فتح شاشة أخرى تُغلق هذه الشاشة تلقائياً حتى تظهر الشاشة الجديدة في المقدمة.</div><div id="topOptionsBody"></div><div class="v11Hint"><button id="desktopAudioTest">💻 اختبار صوت الحاسوب</button> على الحاسوب يجرب التطبيق صوت المتصفح أولاً، وإذا لم يتوفر صوت عربي صالح يستخدم صوتاً عربياً عبر الإنترنت تلقائياً.</div><div id="v12VoiceState" class="v12VoiceState">الصوت: جاهز للاختبار</div>';
 d.body.appendChild(panel);var body=$('topOptionsBody');if(tools)body.appendChild(tools);if(lesson)body.appendChild(lesson);
 var stage=d.createElement('div');stage.id='drawStage';if(color)color.parentNode.insertBefore(stage,color);else quick.parentNode.insertBefore(stage,quick);if(color)stage.appendChild(color);stage.appendChild(quick);stage.appendChild(board);
 var qexp=d.createElement('button');qexp.id='v11QuickExpand';qexp.className='v11Expand';qexp.innerHTML='⛶ تكبير';quick.appendChild(qexp);
 function openOptions(){panel.className='open'}function closeOptions(){panel.className=''}
 function hideOptionsBeforeOther(){if(panel.className.indexOf('open')>=0)closeOptions()}
 $('v11Options').onclick=openOptions;$('topOptionsClose').onclick=closeOptions;
 $('v11Audio').onclick=function(){hideOptionsBeforeOther();var b=$('userAudioBtn');if(b)b.click()};
 $('v11Sync').onclick=function(){hideOptionsBeforeOther();var b=$('syncBtn');if(b)b.click()};
 panel.addEventListener('click',function(e){var t=e.target||e.srcElement,id=t&&t.id;while(t&&t!==panel&&!id){t=t.parentNode;id=t&&t.id}if(id==='userAudioBtn'||id==='quickAudioBtn'||id==='syncBtn'||id==='quickSyncBtn'||id==='showAllBtn'||id==='quickShowAllBtn')hideOptionsBeforeOther()},true);
 function promote(id,z){var el=$(id);if(el&&el.style.display!=='none')el.style.zIndex=''+z}
 function promoteDialogs(){promote('picker',420);promote('settingsPanel',430);promote('syncPanel',440)}
 try{var mo=new MutationObserver(function(){promoteDialogs()});['picker','settingsPanel','syncPanel'].forEach(function(id){var el=$(id);if(el)mo.observe(el,{attributes:true,attributeFilter:['style','class']})})}catch(e){}
 var focused=false;
 function sizeLater(){setTimeout(function(){try{window.dispatchEvent(new Event('resize'))}catch(e){try{var ev=d.createEvent('UIEvents');ev.initUIEvent('resize',true,false,window,0);window.dispatchEvent(ev)}catch(x){}}},80)}
 function toggleFocus(){focused=!focused;if(focused){stage.className='drawFocus';d.body.className+=(d.body.className?' ':'')+'childDrawFocus';$('v11Expand').innerHTML='↙ تصغير الرسم';qexp.innerHTML='↙ تصغير'}else{stage.className='';d.body.className=d.body.className.replace(/\bchildDrawFocus\b/g,'').replace(/^\s+|\s+$/g,'');$('v11Expand').innerHTML='⛶ تكبير الرسم';qexp.innerHTML='⛶ تكبير'}sizeLater()}
 $('v11Expand').onclick=toggleFocus;qexp.onclick=toggleFocus;d.addEventListener('keydown',function(e){if(focused&&(e.key==='Escape'||e.keyCode===27))toggleFocus()},false);
 function voiceState(s){var el=$('v12VoiceState');if(el)el.innerHTML=s;var ss=$('statusText');if(ss&&s.indexOf('✅')===0)ss.innerHTML=s}
 function resumeSynth(){try{if(window.speechSynthesis){if(speechSynthesis.paused&&speechSynthesis.resume)speechSynthesis.resume();speechSynthesis.getVoices&&speechSynthesis.getVoices()}}catch(e){}}
 d.addEventListener('mousedown',resumeSynth,false);d.addEventListener('touchstart',resumeSynth,false);d.addEventListener('keydown',resumeSynth,false);
 var ua=navigator.userAgent||'',isDesktop=!/Android|iPhone|iPad|iPod|Mobile/i.test(ua),mediaUnlocked=false,activeOnlineAudio=null,lastOnlineText='',lastOnlineAt=0;
 function primeMedia(){if(mediaUnlocked)return;mediaUnlocked=true;try{var a=new Audio();a.volume=0;a.src='data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQAAAAA=';var p=a.play();if(p&&p.catch)p.catch(function(){})}catch(e){}}
 d.addEventListener('mousedown',primeMedia,false);d.addEventListener('touchstart',primeMedia,false);d.addEventListener('keydown',primeMedia,false);
 function voices(){try{return window.speechSynthesis&&speechSynthesis.getVoices?speechSynthesis.getVoices()||[]:[]}catch(e){return[]}}
 function bestArabicVoice(){var v=voices(),i,l,n;for(i=0;i<v.length;i++){l=(v[i].lang||'').toLowerCase();n=(v[i].name||'').toLowerCase();if(l.indexOf('ar')===0||n.indexOf('arab')>=0||n.indexOf('عرب')>=0)return v[i]}return null}
 function cleanText(s){return(''+(s||'')).replace(/[🌟👏⭐🎨💪✨🌈🏅🔊]/g,'').replace(/\s+/g,' ').replace(/^\s+|\s+$/g,'')}
 function onlineUrls(text){var q=encodeURIComponent(cleanText(text));return['https://translate.googleapis.com/translate_tts?ie=UTF-8&client=gtx&tl=ar&q='+q,'https://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&tl=ar&q='+q]}
 function playOnlineArabic(text,cb){text=cleanText(text);if(!text){if(cb)cb(false);return false}var n=+new Date();if(text===lastOnlineText&&n-lastOnlineAt<1200){if(cb)cb(false);return false}lastOnlineText=text;lastOnlineAt=n;var urls=onlineUrls(text),i=0,a=null,done=false;function finish(ok){if(done)return;done=true;if(a){a.onplaying=a.onended=a.onerror=null}if(cb)cb(ok)}function next(){if(i>=urls.length){voiceState('⚠️ تعذر الصوت عبر الإنترنت؛ سيبقى صوت الجهاز كخيار احتياطي.');finish(false);return}try{if(activeOnlineAudio){try{activeOnlineAudio.pause()}catch(x){}}a=new Audio();activeOnlineAudio=a;a.preload='auto';a.volume=1;a.onplaying=function(){voiceState('✅ الصوت العربي يعمل عبر الإنترنت على الحاسوب');if(cb)cb('started')};a.onended=function(){finish(true)};a.onerror=function(){i++;next()};a.src=urls[i];var p=a.play();if(p&&p.catch)p.catch(function(){i++;next()})}catch(e){i++;next()}}next();return true}
 function tryNative(text,av){var synth=window.speechSynthesis;if(!synth||!window.SpeechSynthesisUtterance){playOnlineArabic(text);return}try{synth.cancel();synth.resume&&synth.resume()}catch(e){}var started=false,finished=false,u=new SpeechSynthesisUtterance(text);u.lang=av?(av.lang||'ar-SA'):'ar-SA';if(av)u.voice=av;u.rate=.86;u.volume=1;u.onstart=function(){started=true;voiceState('✅ صوت المتصفح يعمل على الحاسوب')};u.onend=function(){finished=true};u.onerror=function(){finished=true;if(isDesktop)playOnlineArabic(text)};try{synth.speak(u)}catch(e){finished=true;if(isDesktop)playOnlineArabic(text)}setTimeout(function(){if(!started&&!finished&&isDesktop){try{synth.cancel()}catch(e){}playOnlineArabic(text)}},1300)}
 function desktopSpeak(text){primeMedia();var av=bestArabicVoice(),synth=window.speechSynthesis;if(!synth||!window.SpeechSynthesisUtterance){playOnlineArabic(text);return}if(isDesktop&&!av){voiceState('جارٍ استخدام الصوت العربي عبر الإنترنت لأن المتصفح لا يعرض صوتاً عربياً محلياً...');playOnlineArabic(text,function(ok){if(!ok)tryNative(text,null)});return}tryNative(text,av)}
 function installDesktopSpeechBridge(){if(!isDesktop||!window.speechSynthesis||!window.SpeechSynthesisUtterance)return;var synth=window.speechSynthesis;if(synth.__app360Bridge)return;var nativeSpeak;try{nativeSpeak=synth.speak.bind(synth)}catch(e){return}var wrapped=function(u){var text=u&&u.text?u.text:'',lang=((u&&u.lang)||'').toLowerCase(),av=bestArabicVoice();if(!text)return nativeSpeak(u);if((lang.indexOf('ar')===0||/[\u0600-\u06FF]/.test(text))&&!av){var oldStart=u.onstart,oldEnd=u.onend,oldErr=u.onerror;voiceState('جارٍ تشغيل الصوت العربي عبر الإنترنت...');var ok=playOnlineArabic(text,function(state){if(state==='started'){try{if(oldStart)oldStart.call(u,{type:'start',online:true})}catch(e){}return}if(state===true){try{if(oldEnd)oldEnd.call(u,{type:'end',online:true})}catch(e){}return}try{nativeSpeak(u)}catch(e){try{if(oldErr)oldErr.call(u,{type:'error',error:'online-and-native-failed'})}catch(x){}}});if(ok)return}return nativeSpeak(u)};try{synth.speak=wrapped;if(synth.speak===wrapped)synth.__app360Bridge=true}catch(e){}
 }
 installDesktopSpeechBridge();setTimeout(installDesktopSpeechBridge,500);setTimeout(installDesktopSpeechBridge,1800);
 $('desktopAudioTest').onclick=function(){desktopSpeak('أحسنت يا نور، الصوت يعمل على الحاسوب')};
 var save=$('saveUserBtn');if(save)save.addEventListener('click',function(){setTimeout(function(){var t=$('title');if(t)top.setAttribute('data-user',t.textContent||t.innerText||'')},50)},false);
 promoteDialogs();
});
})();