'use strict';
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..'),repo=path.resolve(root,'../../..');function read(p){return fs.readFileSync(path.join(root,p),'utf8')}function json(p){return JSON.parse(read(p))}function fail(m){console.error('plan-runner-360 validation failed:',m);process.exit(1)}
const idx=read('index.html'),js=read('app.js'),css=read('styles.css'),p=json('data/presets.json'),app=json('app.json'),man=json('manifest.webmanifest'),sw=read('sw.js'),runtime=JSON.parse(fs.readFileSync(path.join(repo,'data/runtime-apps.json'),'utf8')),age=fs.readFileSync(path.join(repo,'ages/1-4/index.html'),'utf8'),portal=fs.readFileSync(path.join(repo,'assets/js/runtime-apps-v1.js'),'utf8'),registry=JSON.parse(fs.readFileSync(path.join(repo,'data/app-links-registry.json'),'utf8'));
try{new Function(js)}catch(e){fail('app.js syntax '+e.message)}try{new Function(portal)}catch(e){fail('runtime portal syntax '+e.message)}
if(app.id!=='a1-plan-runner'||app.slug!=='plan-runner-360'||app.status!=='live')fail('app contract identity/status');
if(idx.indexOf('plan-runner-360-v1-20260923')<0||idx.indexOf('خطط جاهزة')<0||idx.indexOf('ابنِ خطتك')<0||idx.indexOf('سجل التجارب')<0)fail('main UX sections missing');
if(/\bconst\b|\blet\b|=>|\bfetch\s*\(/.test(js))fail('runtime must remain ES5/XHR legacy-safe');if(css.indexOf('display:grid')>=0||css.indexOf('inset:')>=0)fail('CSS must avoid grid/inset legacy dependencies');
if(js.indexOf('data/app-links-registry.json')<0||js.indexOf('archive_path')<0)fail('dynamic app-link registry consumer missing');if(js.indexOf('route_id')<0||js.indexOf('category')<0||js.indexOf('completion')<0||js.indexOf('duration_seconds')<0)fail('deep-link step model incomplete');if(js.indexOf('https://yem1.com')<0)fail('Safe Reels 360 link missing');if(js.indexOf('templates')<0||js.indexOf('runs')<0||js.indexOf('run_id')<0)fail('templates/run history missing');
if(!Array.isArray(p.levels)||p.levels.length<3)fail('age levels missing');for(const id of ['1-2','2-3','3-4']){const rows=(p.presets||[]).filter(x=>x.level_id===id);if(rows.length<5)fail('need 5 presets for '+id);for(const r of rows){if(!r.steps||r.steps.length<2)fail('preset too short '+r.id);for(const s of r.steps)if(!s.label||!s.href||!s.duration_seconds)fail('bad preset step '+r.id)}}
if(!man.start_url||man.scope!=='./'||!man.icons||!man.icons.length)fail('manifest incomplete');if(sw.indexOf('app360-plan-runner-360-v1')<0||sw.indexOf('app-links-registry.json')<0)fail('service worker shell/registry cache missing');
const rr=(runtime.apps||[]).find(x=>x.id==='a1-plan-runner');if(!rr||rr.age_group!=='1-4'||rr.status!=='live'||rr.href.indexOf('plan-runner-360')<0)fail('runtime portal registration missing');if(age.indexOf('runtime-apps-v1.js?v=')<0)fail('age 1-4 page does not load runtime apps');if(portal.indexOf('runtime-app-card')<0)fail('runtime app card renderer missing');
if((registry.apps||[]).length<4||!(registry.future_app_contract_ar||[]).length)fail('future app deep-link contract missing from registry');
console.log('plan-runner-360 v1 validation OK: '+p.presets.length+' ready presets, runtime portal registered');
