(function(){'use strict';
var GAMES=window.A1ScreenMoveGames||[],root=document.getElementById('appRoot');
var storage=null,STORE_KEY='app360:a1-screen-move:schema2',state={level:1,game:null,mode:null,session:null,assist:'مع المرافق',reelTimer:null,reelFrame:0,reelPlaying:false,reelOverview:false};
try{storage=window.localStorage;var probe='__a1probe';storage.setItem(probe,'1');storage.removeItem(probe);}catch(e){storage=null;}
function el(id){return document.getElementById(id)}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function arr(a){return Array.prototype.slice.call(a||[])}
function nowId(){return'D'+new Date().getTime()+'-'+Math.floor(Math.random()*1000)}
function toast(t){var n=el('toast');n.textContent=t;n.style.display='block';clearTimeout(toast.t);toast.t=setTimeout(function(){n.style.display='none'},2600)}
function loadStore(){var base={sessions:[],prefs:{level:1}};if(!storage)return base;try{var x=JSON.parse(storage.getItem(STORE_KEY)||'null');if(x&&x.sessions&&x.prefs)return x;}catch(e){}return base}
var db=loadStore();
function saveStore(){if(!storage)return false;try{storage.setItem(STORE_KEY,JSON.stringify(db));return true}catch(e){storage=null;storageBanner();return false}}
function storageBanner(){var b=el('storageBanner');if(storage){b.hidden=true;return}b.hidden=false;b.innerHTML='<strong>الحفظ الدائم غير متاح.</strong> التطبيق سيستمر، ويمكنك تصدير السجل يدويًا من زر السجل.'}
function levelLabel(n){return['','المستوى الأول · أرى وأطابق','المستوى الثاني · أوصل وأكرر','المستوى الثالث · أرتب وأحل','المستوى الرابع · أفكر وأبتكر'][n]}
function levelHelp(n){return['','مطابقة وإشارة ومسارات قصيرة جدًا بمساعدة المرافق.','توصيل بسيط وأنماط وذاكرة بصور مألوفة.','تسلسل وفرز وبازل ونقاط أكثر مع مساعدة أقل.','قاعدتان أو قرائن بسيطة ثم ابتكار لغز جديد مع المرافق.'][n]}
function currentGames(){return GAMES.filter(function(g){return g.level===state.level})}
function svgText(x,y,t,size,fill){return'<text x="'+x+'" y="'+y+'" text-anchor="middle" dominant-baseline="middle" font-size="'+size+'" fill="'+(fill||'#17302f')+'" font-family="Arial, sans-serif">'+esc(t)+'</text>'}
function svgForFrame(g,i,wide){
 var w=wide?640:640,h=360,s=g.symbols||[g.icon],a=s[i%s.length]||g.icon,b=s[(i+1)%s.length]||g.icon,c=s[(i+2)%s.length]||g.icon;
 var bg=['#e8faf7','#fff4cb','#eef4ff','#f7edff','#eaf8e5'][i%5];
 var body='<rect width="'+w+'" height="'+h+'" rx="30" fill="'+bg+'"/><circle cx="95" cy="80" r="54" fill="#ffffffaa"/><circle cx="540" cy="270" r="72" fill="#ffffff88"/>';
 body+=svgText(155,165,a,76)+svgText(320,165,b,76)+svgText(485,165,c,76);
 if(i===1||i===3)body+='<path d="M210 165 H270 M370 165 H430" stroke="#0f8f8a" stroke-width="10" stroke-linecap="round"/><path d="M260 150 L280 165 L260 180 M420 150 L440 165 L420 180" fill="none" stroke="#0f8f8a" stroke-width="8"/>';
 if(g.type==='dots'&&g.points){for(var p=0;p<g.points.length;p++){var px=80+g.points[p][0]*4.8,py=310-g.points[p][1]*2.5;body+='<circle cx="'+px+'" cy="'+py+'" r="'+(p===0?15:11)+'" fill="'+(p===0?'#ef4444':'#0f8f8a')+'"/>';if(p<i&&p<g.points.length-1){var nx=80+g.points[p+1][0]*4.8,ny=310-g.points[p+1][1]*2.5;body+='<line x1="'+px+'" y1="'+py+'" x2="'+nx+'" y2="'+ny+'" stroke="#405b59" stroke-width="7" stroke-dasharray="10 8"/>';}}}
 body+=svgText(320,326,(g.frames&&g.frames[i])||g.title,22,'#24413f');
 return'<svg class="frame-visual" viewBox="0 0 '+w+' '+h+'" role="img" aria-label="'+esc((g.frames&&g.frames[i])||g.title)+'" xmlns="http://www.w3.org/2000/svg">'+body+'</svg>';
}
function renderLibrary(){
 stopReel();state.game=null;state.mode=null;var list=currentGames(),h='<section class="hero"><div class="hero-grid"><div><span class="hero-badge">20 تجربة · 4 مستويات · ورق أو شاشة</span><h2>شاهد الفكرة… ثم أغلق الشاشة والعب</h2><p>ألغاز صور وتوصيل نقاط وفرز ومسارات وبازل. كل لعبة لها ورقة عمل قابلة للطباعة، ونسخة على الشاشة فقط عندما لا تتوفر الورقة.</p></div><div class="hero-card"><strong>20</strong><span>تجربة أولية قابلة للتوسع</span><p>لا توجد جولة تلقائية بعد الانتهاء.</p></div></div></section>';
 h+='<div class="level-tabs">';
 for(var i=1;i<=4;i++)h+='<button class="chip '+(i===state.level?'active':'')+'" data-level="'+i+'">'+levelLabel(i)+'</button>';
 h+='</div><div class="library-head"><div><h2>'+levelLabel(state.level)+'</h2><p>'+levelHelp(state.level)+'</p></div><b>'+list.length+' ألعاب</b></div><div class="games-grid">';
 list.forEach(function(g){h+='<button class="game-card" data-game="'+g.id+'"><div class="game-art"><span class="big">'+esc(g.icon)+'</span><span class="mini">'+esc(g.id)+'</span></div><div class="game-body"><b>'+esc(g.title)+'</b><div class="meta"><span>'+esc(g.topic)+'</span><span>ورقة + شاشة</span></div></div></button>'});
 h+='</div>';root.innerHTML=h;
 arr(root.querySelectorAll('[data-level]')).forEach(function(b){b.onclick=function(){state.level=Number(this.getAttribute('data-level'));db.prefs.level=state.level;saveStore();renderLibrary()}});
 arr(root.querySelectorAll('[data-game]')).forEach(function(b){b.onclick=function(){openGame(this.getAttribute('data-game'))}});
}
function findGame(id){for(var i=0;i<GAMES.length;i++)if(GAMES[i].id===id)return GAMES[i];return null}
function openGame(id){
 var g=findGame(id);if(!g)return;stopReel();state.game=g;state.mode=null;state.session={session_id:nowId(),task_id:g.id,attempts:0,artifact:{game_id:g.id,title:g.title,selected_mode:null},reflection:'',assistance_level:'مع المرافق',created_at:new Date().toISOString()};
 var h='<section class="game-view"><div class="backline"><button id="backLibrary">← العودة للألعاب</button><span>'+levelLabel(g.level)+'</span></div><section class="game-title-card"><div class="game-title-row"><div class="game-title-icon">'+esc(g.icon)+'</div><div><h2>'+esc(g.title)+'</h2><p>'+esc(g.topic)+'</p></div></div><div class="materials">';
 g.materials.forEach(function(m){h+='<span>✓ '+esc(m)+'</span>'});h+='</div></section>'+renderReel(g);
 h+='<section class="mode-grid"><article class="mode-card"><h3>🧻 اللعب على الورق والواقع</h3><p>اطبع الورقة أو ارسمها سريعًا، شاهد اللقطات، ثم اترك الجهاز جانبًا. لا يحتاج التطبيق أن يبقى مفتوحًا.</p><div class="action-row"><button class="btn accent" id="printOne">طباعة الورقة</button><button class="btn" id="downloadOne">تنزيل SVG</button><button class="btn primary" id="offlineStart">ابدأ خارج الشاشة</button></div></article><article class="mode-card"><h3>📱 البديل على الشاشة</h3><p>إذا لم تطبع الورقة، نفّذ نفس فكرة اللعبة باللمس أو الرسم على الشاشة دون نقاط أو مكافآت تدفع لجلسة طويلة.</p><button class="btn primary" id="screenStart">افتح اللعبة التفاعلية</button></article></section></section>';
 root.innerHTML=h;el('backLibrary').onclick=renderLibrary;el('printOne').onclick=function(){printGames([g])};el('downloadOne').onclick=function(){downloadWorksheet(g)};el('offlineStart').onclick=function(){state.mode='offline';state.session.artifact.selected_mode='offline';renderOfflineCard(g)};el('screenStart').onclick=function(){state.mode='screen';state.session.artifact.selected_mode='screen';renderScreenGame(g)};setupReel();
}
function renderReel(g){var frames='';for(var i=0;i<5;i++)frames+='<div class="frame"><div>'+svgForFrame(g,i,false)+'<div class="frame-caption">'+esc(g.frames[i])+'</div></div></div>';var dots='';for(i=0;i<5;i++)dots+='<button aria-label="اللقطة '+(i+1)+'" data-dot="'+i+'" class="'+(i===0?'on':'')+'"></button>';return'<section class="reel" id="reel"><div class="reel-label" id="reelLabel">اللقطة 1 من 5</div><div class="reel-viewport"><div id="reelTrack" class="reel-track">'+frames+'</div></div><div class="reel-controls"><button id="reelPlay">⏸ إيقاف</button><div id="reelDots" class="dots">'+dots+'</div><span id="reelCount">1 / 5</span><button id="reelReplay">↺ إعادة</button></div></section>'}
function setupReel(){
 state.reelFrame=0;state.reelPlaying=true;state.reelOverview=false;var track=el('reelTrack');if(!track)return;
 function show(n){state.reelOverview=false;state.reelFrame=Math.max(0,Math.min(4,n));el('reel').className='reel';track.style.transform='translate3d('+(-state.reelFrame*20)+'%,0,0)';arr(el('reelDots').children).forEach(function(d,k){d.className=k===state.reelFrame?'on':''});el('reelCount').textContent=(state.reelFrame+1)+' / 5';el('reelLabel').textContent='اللقطة '+(state.reelFrame+1)+' من 5'}
 function overview(){state.reelOverview=true;state.reelPlaying=false;clearTimeout(state.reelTimer);el('reel').className='reel overview';track.style.transform='none';el('reelCount').textContent='كل اللقطات';el('reelLabel').textContent='كل خطوات الفكرة';el('reelPlay').textContent='▶ تشغيل من البداية'}
 function schedule(){clearTimeout(state.reelTimer);if(!state.reelPlaying)return;state.reelTimer=setTimeout(function(){if(state.reelFrame<4){show(state.reelFrame+1);schedule()}else overview()},2300)}
 function start(reset){if(reset||state.reelOverview)show(0);state.reelPlaying=true;el('reelPlay').textContent='⏸ إيقاف';schedule()}
 function stop(){state.reelPlaying=false;clearTimeout(state.reelTimer);el('reelPlay').textContent=state.reelOverview?'▶ تشغيل من البداية':'▶ متابعة'}
 el('reelPlay').onclick=function(){if(state.reelPlaying)stop();else start(state.reelOverview)};el('reelReplay').onclick=function(){start(true)};
 arr(el('reelDots').children).forEach(function(d){d.onclick=function(){stop();show(Number(this.getAttribute('data-dot')))}});
 show(0);schedule();
}
function stopReel(){clearTimeout(state.reelTimer);state.reelTimer=null;state.reelPlaying=false}
function renderOfflineCard(g){
 stopReel();root.innerHTML='<section class="game-view"><div class="backline"><button id="backGame">← تفاصيل اللعبة</button><span>وضع اللعب خارج الشاشة</span></div><section class="game-title-card"><h2>'+esc(g.icon+' '+g.title)+'</h2><p>جهّز المواد ثم اترك الجهاز جانبًا. هذه البطاقة لا تراقب ما يحدث بعد ذلك.</p><div class="materials">'+g.materials.map(function(m){return'<span>✓ '+esc(m)+'</span>'}).join('')+'</div></section><section class="hero"><h2>الخطوات المختصرة</h2><ol>'+g.frames.map(function(x){return'<li>'+esc(x)+'</li>'}).join('')+'</ol><div class="action-row"><button class="btn accent" id="printCard">🖨 اطبع قبل الإغلاق</button><button class="btn primary" id="finishOffline">✓ انتهينا من البطاقة</button></div><p><strong>مهم:</strong> لا يلزم الرجوع للتطبيق بعد اللعب ولا تقديم صورة أو إثبات.</p></section></section>';
 el('backGame').onclick=function(){openGame(g.id)};el('printCard').onclick=function(){printGames([g])};el('finishOffline').onclick=function(){renderEnd(g,'offline')};
}
function renderScreenGame(g){
 stopReel();state.session.attempts=0;var h='<section class="game-view"><div class="backline"><button id="backGame">← تفاصيل اللعبة</button><span>البديل التفاعلي</span></div><section class="screen-game"><h2>'+esc(g.icon+' '+g.title)+'</h2><p>نفس الفكرة على الشاشة. يمكن إنهاؤها في أي لحظة.</p><div id="challenge" class="challenge"></div><div class="action-row"><button class="btn primary" id="finishScreen">✓ إنهاء اللعبة</button><button class="btn" id="drawingFromGame">🎨 افتح الرسم المشترك</button></div></section></section>';root.innerHTML=h;
 el('backGame').onclick=function(){openGame(g.id)};el('finishScreen').onclick=function(){renderEnd(g,'screen')};el('drawingFromGame').onclick=openDrawing;
 buildChallenge(g);
}
function buildChallenge(g){
 var box=el('challenge');if(!box)return;
 if(g.type==='choice'||g.type==='pattern'){var prompt=g.prompt||'ما القطعة التي تكمل الفكرة؟';box.innerHTML='<div><h3>'+esc(prompt)+'</h3><div class="choice-grid">'+g.options.map(function(o,k){return'<button data-choice="'+k+'">'+esc(o)+'</button>'}).join('')+'</div><p id="challengeMsg"></p></div>';arr(box.querySelectorAll('[data-choice]')).forEach(function(b){b.onclick=function(){state.session.attempts++;var k=Number(this.getAttribute('data-choice'));this.className=k===g.answer?'correct':'wrong';el('challengeMsg').textContent=k===g.answer?'وجدتها! الآن جرّب الفكرة بأشياء حقيقية إن رغبت.':'جرّب صورة أخرى، أو اطلب من المرافق أن يشير إلى الفرق.'}});return}
 if(g.type==='match'){var left='',right='';for(var i=0;i<g.pairs.length;i++){left+='<button class="match-btn" data-side="a" data-pair="'+i+'">'+esc(g.pairs[i][0])+'</button>';right='<button class="match-btn" data-side="b" data-pair="'+i+'">'+esc(g.pairs[i][1])+'</button>'+right}box.innerHTML='<div class="match-board"><div class="match-col">'+left+'</div><div class="match-col">'+right+'</div></div><p id="challengeMsg"></p>';setupMatch(box);return}
 if(g.type==='sort'){box.innerHTML='<div class="sort-board"><div class="sort-bins">'+g.bins.map(function(x,k){return'<button class="sort-bin" data-bin="'+k+'">'+esc(x)+'</button>'}).join('')+'</div><div class="sort-items">'+g.items.map(function(x,k){return'<button class="sort-item" data-item="'+k+'" data-target="'+x[1]+'">'+esc(x[0])+'</button>'}).join('')+'</div><p>اختر قطعة ثم اختر المكان المناسب لها.</p><p id="challengeMsg"></p></div>';setupSort(box);return}
 if(g.type==='memory'){var cards=[];g.cards.forEach(function(x){cards.push(x);cards.push(x)});cards.sort(function(){return Math.random()-.5});box.innerHTML='<div class="memory-grid">'+cards.map(function(x,k){return'<button class="memory-card hidden-card" data-card="'+k+'" data-value="'+esc(x)+'">'+esc(x)+'</button>'}).join('')+'</div>';setupMemory(box);return}
 if(g.type==='order'){var o=g.order.slice().sort(function(){return Math.random()-.5});box.innerHTML='<div><p>المس الصور بالترتيب الذي تراه مناسبًا.</p><div class="order-grid">'+o.map(function(x,k){return'<button data-order="'+k+'" data-value="'+esc(x)+'">'+esc(x)+'</button>'}).join('')+'</div><p id="challengeMsg"></p></div>';setupOrder(box,g.order);return}
 if(g.type==='dots'||g.type==='path'||g.type==='draw'||g.type==='create'||g.type==='puzzle'){box.innerHTML='<canvas id="playCanvas" class="'+(g.type==='dots'?'dots-canvas':'path-canvas')+'"></canvas><p>ارسم بإصبعك أو القلم. لا توجد درجة؛ يكفي أن تجرب.</p>';setupPlayCanvas(el('playCanvas'),g);return}
 box.innerHTML='<div class="choice-grid">'+(g.symbols||[]).map(function(x){return'<button>'+esc(x)+'</button>'}).join('')+'</div>';
}
function setupMatch(box){var selected=null;arr(box.querySelectorAll('.match-btn')).forEach(function(b){b.onclick=function(){if(this.className.indexOf('done')>=0)return;if(!selected){selected=this;this.className+=' selected';return}state.session.attempts++;if(selected.getAttribute('data-side')!==this.getAttribute('data-side')&&selected.getAttribute('data-pair')===this.getAttribute('data-pair')){selected.className='match-btn done';this.className='match-btn done';el('challengeMsg').textContent='زوج متشابه ✓'}else{selected.className='match-btn';el('challengeMsg').textContent='ليسا زوجًا واحدًا، جرّب مجددًا.'}selected=null}})}
function setupSort(box){var selected=null;arr(box.querySelectorAll('.sort-item')).forEach(function(b){b.onclick=function(){if(this.className.indexOf('done')>=0)return;selected=this;arr(box.querySelectorAll('.sort-item')).forEach(function(x){x.style.outline='none'});this.style.outline='4px solid #ffd54f'}});arr(box.querySelectorAll('.sort-bin')).forEach(function(b){b.onclick=function(){if(!selected){el('challengeMsg').textContent='اختر قطعة أولًا.';return}state.session.attempts++;if(selected.getAttribute('data-target')===this.getAttribute('data-bin')){selected.className+=' done';el('challengeMsg').textContent='وضعتها في المكان المناسب ✓'}else el('challengeMsg').textContent='جرّب مكانًا آخر.';selected.style.outline='none';selected=null}})}
function setupMemory(box){var open=[];arr(box.querySelectorAll('.memory-card')).forEach(function(b){b.onclick=function(){if(this.className.indexOf('done')>=0||open.indexOf(this)>=0||open.length===2)return;this.className='memory-card';open.push(this);if(open.length===2){state.session.attempts++;var a=open[0],c=open[1];setTimeout(function(){if(a.getAttribute('data-value')===c.getAttribute('data-value')){a.className='memory-card done';c.className='memory-card done'}else{a.className='memory-card hidden-card';c.className='memory-card hidden-card'}open=[]},650)}}})}
function setupOrder(box,target){var picked=[];arr(box.querySelectorAll('[data-order]')).forEach(function(b){b.onclick=function(){if(this.className.indexOf('done')>=0)return;picked.push(this.getAttribute('data-value'));this.className='done';state.session.attempts++;if(picked.length===target.length){var ok=true;for(var i=0;i<target.length;i++)if(picked[i]!==target[i])ok=false;el('challengeMsg').textContent=ok?'ترتيب جميل ✓':'هذا ترتيب مختلف. يمكن إعادة اللعبة أو تمثيل القصة بطريقتكم.'}}})}
function fitCanvas(c){var r=c.getBoundingClientRect(),d=window.devicePixelRatio||1;c.width=Math.max(320,Math.floor(r.width*d));c.height=Math.max(220,Math.floor(r.height*d));var ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);return{ctx:ctx,w:r.width,h:r.height}}
function setupPlayCanvas(c,g){var z=fitCanvas(c),ctx=z.ctx,w=z.w,h=z.h,down=false,last=null;ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=8;ctx.strokeStyle='#0f8f8a';ctx.fillStyle='#17302f';
 if(g.type==='dots'&&g.points){for(var i=0;i<g.points.length;i++){var x=g.points[i][0]*w/100,y=(100-g.points[i][1])*h/100;ctx.beginPath();ctx.arc(x,y,i===0?11:8,0,Math.PI*2);ctx.fillStyle=i===0?'#ef4444':'#0f8f8a';ctx.fill();}}
 if(g.type==='path'&&g.path){ctx.font='42px Arial';ctx.fillText(g.symbols[0],15,h-28);ctx.fillText(g.symbols[1],w-65,55);for(i=2;i<g.symbols.length;i++)ctx.fillText(g.symbols[i],w*(.25+.18*i),h*(.35+.12*(i%2)));}
 if(g.type==='draw'){ctx.strokeStyle='#b4cbc8';ctx.lineWidth=5;ctx.setLineDash([10,8]);ctx.beginPath();ctx.arc(w/2,h/2,Math.min(w,h)*.28,-Math.PI/2,Math.PI/2);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#0f8f8a';ctx.lineWidth=8}
 if(g.type==='puzzle'){ctx.font='58px Arial';ctx.fillText('🧩',w/2-25,h/2+20);ctx.font='22px Arial';ctx.fillText('رتّب القطع بالرسم حول الصورة',w/2-125,h-30)}
 function pos(e){var r=c.getBoundingClientRect(),t=e.touches&&e.touches[0]?e.touches[0]:e;return{x:t.clientX-r.left,y:t.clientY-r.top}}
 function start(e){down=true;last=pos(e);state.session.attempts++;if(e.preventDefault)e.preventDefault()}
 function move(e){if(!down)return;var p=pos(e);ctx.strokeStyle='#0f8f8a';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p;if(e.preventDefault)e.preventDefault()}
 function end(){down=false;last=null}
 c.addEventListener('mousedown',start);c.addEventListener('mousemove',move);document.addEventListener('mouseup',end);c.addEventListener('touchstart',start,{passive:false});c.addEventListener('touchmove',move,{passive:false});c.addEventListener('touchend',end);
}
function renderEnd(g,mode){
 stopReel();state.session.artifact.selected_mode=mode;root.innerHTML='<section class="end-card"><div class="end-icon">🌟</div><h2>انتهت بطاقة اللعب</h2><p>أغلق النشاط هنا. لن يبدأ التطبيق لعبة أخرى تلقائيًا، ولا يلزم إثبات ما حدث خارج الشاشة.</p><div class="reflection"><p><strong>مراجعة اختيارية للمرافق فقط</strong> — اتركها فارغة إن أردت.</p><label>مقدار المساعدة</label><div class="assist-row"><button data-assist="مع المرافق" class="active">مع المرافق</button><button data-assist="مساعدة قليلة">مساعدة قليلة</button><button data-assist="محاولة ذاتية">محاولة ذاتية</button></div><label for="reflectionText">ملاحظة قصيرة اختيارية</label><textarea id="reflectionText" placeholder="مثال: أحب توصيل النقاط، فسنكررها بورقة أكبر."></textarea><div class="action-row"><button class="btn primary" id="saveReflection">حفظ المراجعة محليًا</button><button class="btn" id="closeEnd">العودة للمكتبة</button></div></div></section>';
 arr(root.querySelectorAll('[data-assist]')).forEach(function(b){b.onclick=function(){state.assist=this.getAttribute('data-assist');arr(root.querySelectorAll('[data-assist]')).forEach(function(x){x.className=''});this.className='active'}});
 el('saveReflection').onclick=function(){state.session.reflection=el('reflectionText').value||'';state.session.assistance_level=state.assist;state.session.finished_at=new Date().toISOString();db.sessions.unshift(state.session);if(db.sessions.length>100)db.sessions.length=100;saveStore();toast(storage?'حُفظت المراجعة على هذا الجهاز':'لم يتوفر حفظ دائم؛ يمكنك التصدير من السجل');el('saveReflection').disabled=true};
 el('closeEnd').onclick=renderLibrary;
}
function worksheetSVG(g){
 var body='<rect width="1120" height="1584" fill="white"/><rect x="45" y="45" width="1030" height="1494" rx="34" fill="#fbfefd" stroke="#0f8f8a" stroke-width="5"/>';
 body+=svgText(560,110,'لنلعب الآن · '+g.id,34,'#0f8f8a')+svgText(560,175,g.title,46,'#17302f')+svgText(560,225,'المستوى '+g.level+' · '+g.topic,26,'#45605e');
 body+='<g transform="translate(80 275) scale(1.5)">'+svgForFrame(g,2,true).replace('<svg class="frame-visual" viewBox="0 0 640 360" role="img" aria-label="'+esc(g.frames[2])+'" xmlns="http://www.w3.org/2000/svg">','<svg x="0" y="0" width="640" height="360" viewBox="0 0 640 360">').replace('</svg>','</svg>')+'</g>';
 body+=svgText(560,900,'نفّذ الفكرة على الورق أو بأشياء حقيقية',32,'#17302f');
 var y=970;g.frames.forEach(function(x,k){body+=svgText(560,y+k*70,(k+1)+' · '+x,28,'#24413f')});
 body+='<line x1="100" y1="1360" x2="1020" y2="1360" stroke="#8da9a6" stroke-width="3" stroke-dasharray="14 10"/>'+svgText(560,1415,'مساحة رسم أو إضافة لغز من الطفل والمرافق',26,'#45605e')+'<rect x="120" y="1450" width="880" height="55" rx="14" fill="none" stroke="#b7cbc9" stroke-width="3" stroke-dasharray="10 8"/>';
 return'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1120 1584">'+body+'</svg>';
}
function printGames(list){var p=el('printArea');p.innerHTML=list.map(function(g){return'<article class="print-sheet"><h1>'+esc(g.title)+'</h1>'+worksheetSVG(g)+'<p>اللعب الحقيقي أولًا · لا توجد مطالبة بإثبات الإنجاز.</p></article>'}).join('');setTimeout(function(){window.print()},100)}
function downloadBlob(name,type,text){try{var blob=new Blob([text],{type:type}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(u);a.parentNode.removeChild(a)},200)}catch(e){toast('تعذر التنزيل على هذا المتصفح؛ استخدم الطباعة بدلًا منه.')}}
function downloadWorksheet(g){downloadBlob('app360-'+g.id+'-worksheet.svg','image/svg+xml;charset=utf-8',worksheetSVG(g))}
function openWorksheets(){
 var h='<p>كل تجربة لها ورقة A4 مستقلة. يمكن طباعة ورقة واحدة أو الحزمة كلها، أو تنزيل SVG واضح للطباعة.</p><div class="action-row"><button class="btn accent" id="printAll">🖨 طباعة كل الأوراق</button><button class="btn" id="downloadPack">⬇ تنزيل حزمة HTML</button></div><div class="worksheet-list">';
 GAMES.forEach(function(g){h+='<div class="worksheet-row"><div class="wi">'+esc(g.icon)+'</div><div><b>'+esc(g.id+' · '+g.title)+'</b><small>المستوى '+g.level+' · '+esc(g.topic)+'</small></div><div class="wa"><button class="btn" data-print="'+g.id+'">طباعة</button><button class="btn" data-down="'+g.id+'">SVG</button></div></div>'});h+='</div>';openSheet('🖨 أوراق العمل',h);
 el('printAll').onclick=function(){printGames(GAMES)};el('downloadPack').onclick=downloadPack;arr(el('sheetBody').querySelectorAll('[data-print]')).forEach(function(b){b.onclick=function(){printGames([findGame(this.getAttribute('data-print'))])}});arr(el('sheetBody').querySelectorAll('[data-down]')).forEach(function(b){b.onclick=function(){downloadWorksheet(findGame(this.getAttribute('data-down')))}})
}
function downloadPack(){var sheets=GAMES.map(function(g){return'<article style="page-break-after:always;direction:rtl;font-family:Arial"><h1>'+esc(g.title)+'</h1>'+worksheetSVG(g)+'</article>'}).join('');downloadBlob('app360-screen-to-move-20-worksheets.html','text/html;charset=utf-8','<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><title>20 ورقة لعب</title><body>'+sheets+'</body></html>')}
function openHistory(){
 var list=db.sessions||[],h='<div class="action-row"><button class="btn" id="exportHistory">تصدير JSON</button><button class="btn danger" id="deleteHistory">حذف السجل المحلي</button></div><p>السجل يسجل فقط ما تختار حفظه داخل التطبيق؛ لا يثبت تنفيذ أي نشاط خارج الشاشة.</p>';
 if(!list.length)h+='<p>لا توجد مراجعات محفوظة.</p>';else list.forEach(function(s){h+='<div class="history-item"><b>'+esc((s.artifact&&s.artifact.title)||s.task_id)+'</b><div>'+esc(s.assistance_level||'')+' · '+esc(s.artifact&&s.artifact.selected_mode==='offline'?'خارج الشاشة':'على الشاشة')+'</div><small>'+esc(s.reflection||'بدون ملاحظة')+'</small></div>'});
 openSheet('📚 السجل المحلي',h);el('exportHistory').onclick=function(){downloadBlob('app360-a1-screen-move-history.json','application/json;charset=utf-8',JSON.stringify(db,null,2))};el('deleteHistory').onclick=function(){if(window.confirm('حذف كل المراجعات المحفوظة على هذا الجهاز؟')){db.sessions=[];saveStore();openHistory()}}
}
var overlayKind=null;
function openSheet(title,html){el('sheetTitle').textContent=title;el('sheetBody').innerHTML=html;el('sheet').hidden=false;el('sheet').setAttribute('aria-hidden','false');overlayKind='sheet';try{history.pushState({a1Overlay:'sheet'},'',location.href)}catch(e){}}
function hideSheet(){el('sheet').hidden=true;el('sheet').setAttribute('aria-hidden','true');if(overlayKind==='sheet')overlayKind=null}
function closeSheet(){if(overlayKind==='sheet'){try{history.back();return}catch(e){}}hideSheet()}
function openDrawing(){var o=el('drawingOverlay');o.hidden=false;o.setAttribute('aria-hidden','false');overlayKind='drawing';try{history.pushState({a1Overlay:'drawing'},'',location.href)}catch(e){};setTimeout(initDrawing,30)}
function hideDrawing(){el('drawingOverlay').hidden=true;el('drawingOverlay').setAttribute('aria-hidden','true');if(overlayKind==='drawing')overlayKind=null}
function closeDrawing(){if(overlayKind==='drawing'){try{history.back();return}catch(e){}}hideDrawing()}
window.addEventListener('popstate',function(){if(overlayKind==='drawing'){hideDrawing();return}if(overlayKind==='sheet'){hideSheet();return}});
arr(document.querySelectorAll('[data-close-sheet]')).forEach(function(b){b.onclick=closeSheet});arr(document.querySelectorAll('[data-close-drawing]')).forEach(function(b){b.onclick=closeDrawing});
var draw={ctx:null,color:'#1f2937',eraser:false,down:false,last:null,history:[]};
function initDrawing(){var c=el('sharedCanvas'),wrap=c.parentNode,r=wrap.getBoundingClientRect(),d=window.devicePixelRatio||1;c.width=Math.max(320,Math.floor(r.width*d));c.height=Math.max(260,Math.floor(r.height*d));c.style.width=r.width+'px';c.style.height=r.height+'px';draw.ctx=c.getContext('2d');draw.ctx.setTransform(d,0,0,d,0,0);draw.ctx.fillStyle='#fff';draw.ctx.fillRect(0,0,r.width,r.height);draw.history=[];bindDrawing(c)}
function bindDrawing(c){if(c._bound)return;c._bound=true;function p(e){var r=c.getBoundingClientRect(),t=e.touches&&e.touches[0]?e.touches[0]:e;return{x:t.clientX-r.left,y:t.clientY-r.top}}function start(e){draw.down=true;draw.last=p(e);snapshot();if(e.preventDefault)e.preventDefault()}function move(e){if(!draw.down||!draw.ctx)return;var q=p(e);draw.ctx.lineCap='round';draw.ctx.lineJoin='round';draw.ctx.lineWidth=draw.eraser?30:7;draw.ctx.strokeStyle=draw.eraser?'#fff':draw.color;draw.ctx.beginPath();draw.ctx.moveTo(draw.last.x,draw.last.y);draw.ctx.lineTo(q.x,q.y);draw.ctx.stroke();draw.last=q;if(e.preventDefault)e.preventDefault()}function end(){draw.down=false;draw.last=null}c.addEventListener('mousedown',start);c.addEventListener('mousemove',move);document.addEventListener('mouseup',end);c.addEventListener('touchstart',start,{passive:false});c.addEventListener('touchmove',move,{passive:false});c.addEventListener('touchend',end)}
function snapshot(){try{if(draw.history.length>10)draw.history.shift();draw.history.push(el('sharedCanvas').toDataURL('image/png'))}catch(e){}}
arr(document.querySelectorAll('[data-color]')).forEach(function(b){b.onclick=function(){draw.color=this.getAttribute('data-color');draw.eraser=false}});
el('eraserBtn').onclick=function(){draw.eraser=true};el('clearDrawingBtn').onclick=function(){if(!draw.ctx)return;snapshot();var c=el('sharedCanvas');draw.ctx.clearRect(0,0,c.width,c.height);draw.ctx.fillStyle='#fff';draw.ctx.fillRect(0,0,c.width,c.height)};
el('undoBtn').onclick=function(){if(!draw.history.length||!draw.ctx)return;var img=new Image(),src=draw.history.pop(),c=el('sharedCanvas');img.onload=function(){draw.ctx.clearRect(0,0,c.width,c.height);draw.ctx.drawImage(img,0,0,c.clientWidth,c.clientHeight)};img.src=src};
el('saveDrawingBtn').onclick=function(){try{var a=document.createElement('a');a.href=el('sharedCanvas').toDataURL('image/png');a.download='app360-shared-drawing.png';a.click()}catch(e){toast('تعذر حفظ الصورة على هذا المتصفح.')}};
function pwa(){
 var deferred=null;window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();deferred=e});
 el('installBtn').onclick=function(){if(deferred){deferred.prompt();deferred.userChoice.then(function(){deferred=null})}else toast('من قائمة المتصفح اختر: تثبيت التطبيق أو إضافة إلى الشاشة الرئيسية.')};
 if(!('serviceWorker'in navigator)){el('updateBtn').onclick=function(){location.reload()};return}
 navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(function(reg){el('updateBtn').onclick=function(){toast('جارٍ فحص التحديث…');reg.update().then(function(){toast(reg.waiting?'يوجد تحديث جاهز؛ اضغط تحديث مرة أخرى لتفعيله.':'تم فحص النسخة.')});if(reg.waiting)reg.waiting.postMessage({type:'SKIP_WAITING'})};reg.addEventListener('updatefound',function(){var nw=reg.installing;if(nw)nw.addEventListener('statechange',function(){if(nw.state==='installed'&&navigator.serviceWorker.controller)toast('نسخة أحدث جاهزة للتفعيل.')})})}).catch(function(){el('updateBtn').onclick=function(){location.reload()}});
 var reloaded=false;navigator.serviceWorker.addEventListener('controllerchange',function(){if(reloaded)return;reloaded=true;location.reload()});
}
el('libraryBtn').onclick=renderLibrary;el('worksheetsBtn').onclick=openWorksheets;el('drawingBtn').onclick=openDrawing;el('historyBtn').onclick=openHistory;
state.level=(db.prefs&&Number(db.prefs.level))||1;if(state.level<1||state.level>4)state.level=1;storageBanner();renderLibrary();pwa();
})();
