'use strict';
const fs=require('node:fs');
const test=require('node:test');
const assert=require('node:assert/strict');
const games=require('./games-data.js');
test('library has exactly 90 creative games',()=>{assert.equal(games.length,90);assert.equal(new Set(games.map(g=>g.id)).size,90);});
test('four readiness levels remain balanced after the 20 checkmark exercises',()=>{const expected={1:23,2:23,3:22,4:22};for(let level=1;level<=4;level++)assert.equal(games.filter(g=>g.level===level).length,expected[level]);});
test('G71 through G90 are multi-choice mark exercises',()=>{for(let n=71;n<=90;n++){const id='G'+n;const g=games.find(x=>x.id===id);assert.ok(g,id+' missing');assert.equal(g.type,'mark');assert.ok(Array.isArray(g.markOptions)&&g.markOptions.length>=12,id+' needs large option set');assert.ok(g.markOptions.filter(x=>x[1]).length>=3);assert.ok(g.markOptions.filter(x=>!x[1]).length>=3);assert.equal(g.frames.length,5);}});
test('all 90 games use supported direct play types and paper materials',()=>{const supported=new Set(['choice','match','sort','dots','path','pattern','memory','draw','order','puzzle','create','mark']);for(const g of games){assert.ok(supported.has(g.type),g.id+' unsupported');assert.ok(Array.isArray(g.materials)&&g.materials.length>=1);assert.equal(g.frames.length,5);}});
test('mark engine supports large selections, validation and printable checkboxes',()=>{const js=fs.readFileSync('./app.js','utf8');const css=fs.readFileSync('./styles.css','utf8');assert.match(js,/function buildMark\(box,g\)/);assert.match(js,/function markWorksheetSVG\(g\)/);assert.match(js,/g\.type==='mark'/);assert.match(js,/تحقق من العلامات/);assert.match(css,/large multi-choice checkmark exercises/);assert.match(css,/\.mark-option/);});
test('wide screen five-step overview and mobile autoplay remain enabled',()=>{const js=fs.readFileSync('./app.js','utf8');assert.match(js,/function compactReel\(\)/);assert.match(js,/if\(compactReel\(\)\)\{show\(0\);play\(\)\}else showOverview\(\)/);assert.match(js,/reelPrev/);assert.match(js,/reelNext/);});
test('shared name audio remains centralized',()=>{const js=fs.readFileSync('./app.js','utf8');const html=fs.readFileSync('./index.html','utf8');assert.match(js,/function speakCheer\(\)/);assert.match(html,/Audio360Base/);assert.match(html,/drawing-writing-foundations\/audio-v21\.js/);});
