(function(win){'use strict';
var store=win.App360DesignerStore,timer=null;
function el(id){return document.getElementById(id)}
function api(kind){return kind==='worksheet'?win.App360WorksheetDesigner:win.App360GameDesigner}
function panel(kind){return document.querySelector(kind==='worksheet'?'.wd9-panel':'.gd-panel')}
function settings(kind){return el(kind==='worksheet'?'wdSettingsDrawer':'gdSettings')}
function status(kind,t){var n=el(kind==='worksheet'?'wdStatus':'gdStatus');if(n)n.textContent=t||''}
function markDirty(){if(win.App360DesignerGuard)win.App360DesignerGuard.markDirty()}
function clearDirty(){if(win.App360DesignerGuard)win.App360DesignerGuard.clearDirty()}
function modeText(){return store&&store.mode?store.mode():'LocalStorage'}
function html(kind){return '<section class="wd-block gd-block v15-assist-block" data-v15-assist="'+kind+'"><strong>مساعد التصميم 360</strong><button type="button" class="v15-magic" data-v15-magic>✨ تحسين سحري للتصميم<small>يضبط الحدود، المحاذاة، المسافات ويقلل التداخل مع الحفاظ على الفكرة</small></button><div class="v15-tool-group"><button data-v15-align="right">محاذاة يمين</button><button data-v15-align="left">محاذاة يسار</button><button data-v15-align="top">إلى الأعلى</button><button data-v15-align="bottom">إلى الأسفل</button><button data-v15-align="centerX">توسيط أفقي</button><button data-v15-align="centerY">توسيط رأسي</button><button data-v15-distribute="x">توزيع أفقي</button><button data-v15-distribute="y">توزيع رأسي</button><button data-v15-snap>تثبيت على شبكة</button><button data-v15-normalize>توحيد الأحجام</button></div><div class="v15-storage"><b>الحفظ والاسترجاع</b><div class="v15-storage-row"><button type="button" class="v15-save-browser" data-v15-save>حفظ في المتصفح</button><select data-v15-saved><option value="">المحفوظات</option></select><button type="button" data-v15-load>فتح</button><button type="button" data-v15-delete>حذف</button><button type="button" data-v15-draft>استرجاع المسودة</button></div><small class="v15-storage-note">التخزين الحالي: <b data-v15-mode>'+modeText()+'</b>. الأجهزة الحديثة تستخدم IndexedDB، والأجهزة القديمة تعود تلقائيًا إلى LocalStorage. الاستيراد والتصدير JSON يبقيان متاحين.</small><span class="v15-draft-badge ok" data-v15-draft-status>الحفظ التلقائي للمسودة فعّال</span></div></section>'}
function refresh(kind){var p=panel(kind),sel=p&&p.querySelector('[data-v15-saved]');if(!sel||!store)return;store.list(kind,function(a){var h='<option value="">المحفوظات ('+a.length+')</option>';for(var i=0;i<a.length;i++)h+='<option value="'+a[i].id+'">'+String(a[i].title||'تصميم')+' · '+String(a[i].updated_at||'').slice(0,16).replace('T',' ')+'</option>';sel.innerHTML=h})}
function current(kind){var a=api(kind);return a&&a.getData?a.getData():null}
function save(kind,quiet){var p=panel(kind),a=api(kind),d=current(kind);if(!p||!a||!d||!store)return;d.id=p._v15RecordId||d.id||kind+'-'+new Date().getTime();p._v15RecordId=d.id;store.save(kind,d,function(r){p._v15RecordId=r.id;store.clearDraft(kind,function(){});clearDirty();refresh(kind);if(!quiet)status(kind,'تم الحفظ الآمن في '+modeText())})}
function openSaved(kind){var p=panel(kind),sel=p&&p.querySelector('[data-v15-saved]'),a=api(kind);if(!sel||!sel.value||!a||!store)return;store.get(kind,sel.value,function(r){if(!r)return;a.loadData(r.data);p._v15RecordId=r.id;clearDirty();status(kind,'تم فتح التصميم المحفوظ')})}
function deleteSaved(kind){var p=panel(kind),sel=p&&p.querySelector('[data-v15-saved]');if(!sel||!sel.value||!store)return;if(win.confirm&&!win.confirm('حذف هذا التصميم المحفوظ من المتصفح؟'))return;store.remove(kind,sel.value,function(){refresh(kind);status(kind,'تم حذف التصميم المحفوظ')})}
function draft(kind,quiet){if(!store||!win.App360DesignerGuard||!win.App360DesignerGuard.isDirty())return;var d=current(kind);if(!d)return;store.saveDraft(kind,d,function(){var p=panel(kind),b=p&&p.querySelector('[data-v15-draft-status]');if(b){b.className='v15-draft-badge ok';b.textContent='تم حفظ مسودة تلقائية الآن'}if(!quiet)status(kind,'حُفظت مسودة استرداد تلقائيًا')})}
function restoreDraft(kind,ask){if(!store)return;var a=api(kind),p=panel(kind);store.loadDraft(kind,function(r){if(!r||!r.data||!a)return;var items=r.data.items||[];if(!items.length)return;var ok=true;if(ask&&win.confirm)ok=win.confirm('وجدنا مسودة غير مكتملة محفوظة بتاريخ '+String(r.updated_at||'').slice(0,16).replace('T',' ')+'. هل تريد استرجاعها؟');if(ok){a.loadData(r.data);p._v15RecordId=r.data.id||null;markDirty();status(kind,'تم استرجاع المسودة غير المكتملة')}})}
function bind(kind){var p=panel(kind),s=settings(kind),a=api(kind);if(!p||!s||!a||p.getAttribute('data-v15-enhanced')==='1')return;p.setAttribute('data-v15-enhanced','1');var box=document.createElement('div');box.innerHTML=html(kind);s.insertBefore(box.firstChild,s.firstChild);var assist=s.querySelector('[data-v15-assist]');assist.querySelector('[data-v15-magic]').onclick=function(){a.smartFinish();markDirty();draft(kind,true)};var als=assist.querySelectorAll('[data-v15-align]');for(var i=0;i<als.length;i++)als[i].onclick=function(){a.align(this.getAttribute('data-v15-align'));markDirty()};var ds=assist.querySelectorAll('[data-v15-distribute]');for(i=0;i<ds.length;i++)ds[i].onclick=function(){a.distribute(this.getAttribute('data-v15-distribute'));markDirty()};assist.querySelector('[data-v15-snap]').onclick=function(){a.snap(10);markDirty()};assist.querySelector('[data-v15-normalize]').onclick=function(){a.normalize();markDirty()};assist.querySelector('[data-v15-save]').onclick=function(){save(kind,false)};assist.querySelector('[data-v15-load]').onclick=function(){openSaved(kind)};assist.querySelector('[data-v15-delete]').onclick=function(){deleteSaved(kind)};assist.querySelector('[data-v15-draft]').onclick=function(){restoreDraft(kind,false)};refresh(kind);
 var nativeSave=el(kind==='worksheet'?'wdSaveLocal':'gdSaveBtn');if(nativeSave)nativeSave.addEventListener('click',function(){setTimeout(function(){save(kind,true)},80)},false);
 if(kind==='worksheet'){var tools=s.querySelectorAll('[data-wdshape]');for(i=0;i<tools.length;i++){tools[i].setAttribute('draggable','true');tools[i].ondragstart=function(e){try{e.dataTransfer.setData('text/x-app360-tool','shape:'+this.getAttribute('data-wdshape'))}catch(err){}}}var line=el('wdAddLine'),check=el('wdAddCheckbox');if(line){line.setAttribute('draggable','true');line.ondragstart=function(e){try{e.dataTransfer.setData('text/x-app360-tool','line')}catch(err){}}}if(check){check.setAttribute('draggable','true');check.ondragstart=function(e){try{e.dataTransfer.setData('text/x-app360-tool','checkbox')}catch(err){}}}}
 setTimeout(function(){restoreDraft(kind,true)},180)}
function wrap(){var w=win.App360WorksheetDesigner,g=win.App360GameDesigner;if(w&&w.open&&!w._v15Wrapped){var ow=w.open;w.open=function(game){ow(game);setTimeout(function(){bind('worksheet')},20)};w._v15Wrapped=true}if(g&&g.open&&!g._v15Wrapped){var og=g.open;g.open=function(){og();setTimeout(function(){bind('game')},20)};g._v15Wrapped=true}}
function visibleKind(){var o=el('drawingOverlay');if(!o||o.hidden)return null;if(document.querySelector('.wd9-panel'))return'worksheet';if(document.querySelector('.gd-panel'))return'game';return null}
wrap();timer=setInterval(function(){var k=visibleKind();if(k)draft(k,true)},2500);
win.App360DesignerV15={enhance:bind,save:save,restoreDraft:restoreDraft};
})(window);