(function(win){'use strict';
var touchOpt=false,keyboardBound=false;
function noop(){}
try{var opt=Object.defineProperty({},'passive',{get:function(){touchOpt={passive:false}}});win.addEventListener('a360passive',noop,opt);win.removeEventListener('a360passive',noop,opt)}catch(e){touchOpt=false}
win.App360TouchOptions=touchOpt||false;
function el(id){return document.getElementById(id)}
function qa(sel,base){return Array.prototype.slice.call((base||document).querySelectorAll(sel)||[])}
function addClass(n,c){if(n&&(' '+n.className+' ').indexOf(' '+c+' ')<0)n.className=(n.className+' '+c).replace(/^\s+|\s+$/g,'')}
function removeClass(n,c){if(n)n.className=(' '+n.className+' ').replace(' '+c+' ',' ').replace(/^\s+|\s+$/g,'')}
function api(kind){return kind==='worksheet'?win.App360WorksheetDesigner:win.App360GameDesigner}
function panel(kind){return document.querySelector(kind==='worksheet'?'.wd9-panel':'.gd-panel')}
function settings(kind){return el(kind==='worksheet'?'wdSettingsDrawer':'gdSettings')}
function work(kind){var p=panel(kind);return p&&p.querySelector(kind==='worksheet'?'.wd-work':'.gd-work')}
function visibleKind(){var o=el('drawingOverlay');if(!o||o.hidden)return null;if(panel('worksheet'))return'worksheet';if(panel('game'))return'game';return null}
function feedbackNode(){var n=el('v16DesignerFeedback');if(n)return n;n=document.createElement('div');n.id='v16DesignerFeedback';n.className='v16-feedback';n.setAttribute('role','status');n.setAttribute('aria-live','polite');var o=el('drawingOverlay');(o||document.body).appendChild(n);return n}
function feedback(kind,text){var n=feedbackNode();n.textContent=text;n.style.display='block';removeClass(n,'show');setTimeout(function(){addClass(n,'show')},1);clearTimeout(feedback.t);feedback.t=setTimeout(function(){removeClass(n,'show');setTimeout(function(){n.style.display='none'},180)},1600);try{if(navigator.vibrate)navigator.vibrate(10)}catch(e){}setTimeout(function(){refresh(kind)},0)}
win.App360DesignerFeedback=feedback;
function injectSmartFit(){if(el('v16DesignerSmartFitStyle'))return;var s=document.createElement('style');s.id='v16DesignerSmartFitStyle';s.type='text/css';s.innerHTML='.wd-item>img,.gd-item>img{width:100%!important;height:100%!important;max-width:100%!important;max-height:100%!important;object-fit:contain!important;object-position:center center!important;display:block!important;box-sizing:border-box!important}.wd-item.wd-shape>svg,.wd-item.wd-checkbox>div,.wd-item.wd-line>svg{max-width:100%!important;max-height:100%!important}.v16-delete{border-color:#d88383!important;color:#8a2727!important;background:#fff5f4!important}.v16-smart-fit-note{display:block;margin-top:5px;color:#55706d;font-size:10px;line-height:1.5}';(document.head||document.getElementsByTagName('head')[0]||document.body).appendChild(s)}
function selectionHtml(kind){return'<div class="v16-selection-box" data-v16-selection="'+kind+'"><b>التحديد الجماعي</b><div class="v16-selection-actions"><button type="button" data-v16-multi>تحديد متعدد</button><button type="button" data-v16-all>تحديد الكل</button><button type="button" data-v16-clear>إلغاء التحديد</button><button type="button" class="v16-delete" data-v16-delete>حذف المحدد</button></div><small data-v16-count>اختر عنصرين أو أكثر ليتم ترتيبها معًا.</small><small class="v16-smart-fit-note">الصور تُلائم مساحاتها تلقائيًا بدون تمديد أو قص؛ ويمكن استخدام «التحسين السحري» للمحاذاة والمسافات.</small></div>'}
function mobileBarHtml(kind){return'<div class="v16-mobile-bar" data-v16-bar="'+kind+'"><span data-v16-mobile-count>لا يوجد عنصر محدد</span><button type="button" data-v16-smaller aria-label="تصغير العناصر">− تصغير</button><button type="button" data-v16-larger aria-label="تكبير العناصر">+ تكبير</button><button type="button" data-v16-mobile-multi>تحديد متعدد</button><button type="button" data-v16-mobile-clear>إلغاء</button><button type="button" class="v16-delete" data-v16-mobile-delete aria-label="حذف العناصر المحددة">حذف</button></div>'}
function setButtonState(b,on,label){if(!b)return;b.textContent=(on?'✓ ':'')+label;if(on)addClass(b,'active');else removeClass(b,'active')}
function refresh(kind){var p=panel(kind),a=api(kind);if(!p||!a||!a.getSelectionCount)return;var count=a.getSelectionCount(),multi=a.isMultiSelect&&a.isMultiSelect(),countText=count?('المحدد حاليًا: '+count+' عنصر'):'لا يوجد عنصر محدد';qa('[data-v16-count]',p).forEach(function(n){n.textContent=count>=2?countText+' — أدوات المحاذاة والترتيب ستعمل على هذه المجموعة فقط.':countText+' — فعّل «تحديد متعدد» ثم المس العناصر المطلوبة.'});qa('[data-v16-mobile-count]',p).forEach(function(n){n.textContent=countText});qa('[data-v16-multi]',p).forEach(function(b){setButtonState(b,multi,'تحديد متعدد')});qa('[data-v16-mobile-multi]',p).forEach(function(b){setButtonState(b,multi,'متعدد')});qa('[data-v16-delete],[data-v16-mobile-delete]',p).forEach(function(b){b.disabled=!count;b.setAttribute('aria-disabled',count?'false':'true')});var magic=p.querySelector('[data-v15-magic]');if(magic){var sm=magic.getElementsByTagName('small')[0];if(sm)sm.textContent=count>=2?('سيتم تحسين '+count+' عناصر محددة فقط: ملاءمة، محاذاة، مسافات وتوزيع واضح.'):'اختر عنصرين أو أكثر لمعالجة المجموعة فقط؛ بدون مجموعة سيتم تحسين التصميم كاملًا.'}}
function deleteSelection(kind){var a=api(kind),count=a&&a.getSelectionCount?a.getSelectionCount():0,b;if(!a||!count){feedback(kind,'حدد صورة أو شكلًا أو نصًا أولًا ثم اضغط حذف');return false}b=el(kind==='worksheet'?'wdDelete':'gdDelete');if(b&&typeof b.click==='function')b.click();else if(b&&b.onclick)b.onclick();else{feedback(kind,'تعذر تنفيذ الحذف في هذه اللحظة');return false}refresh(kind);return true}
function editableTarget(t){var tag=t&&t.tagName?String(t.tagName).toLowerCase():'';return tag==='input'||tag==='textarea'||tag==='select'||(t&&t.isContentEditable)}
function bindKeyboard(){if(keyboardBound||!document.addEventListener)return;keyboardBound=true;document.addEventListener('keydown',function(e){var code=e.key||e.keyCode||e.which,k=visibleKind();if(!k||editableTarget(e.target))return;if(code==='Delete'||code==='Backspace'||code===46||code===8){var a=api(k);if(a&&a.getSelectionCount&&a.getSelectionCount()>0){if(e.preventDefault)e.preventDefault();deleteSelection(k)}}},true)}
function bindSelectionControls(kind,scope){var a=api(kind);if(!a)return;qa('[data-v16-multi]',scope).forEach(function(b){b.onclick=function(){a.setMultiSelect(!a.isMultiSelect());refresh(kind)}});qa('[data-v16-all]',scope).forEach(function(b){b.onclick=function(){a.selectAll();refresh(kind)}});qa('[data-v16-clear]',scope).forEach(function(b){b.onclick=function(){a.clearSelection();refresh(kind)}});qa('[data-v16-delete]',scope).forEach(function(b){b.onclick=function(){deleteSelection(kind)}});qa('[data-v16-mobile-multi]',scope).forEach(function(b){b.onclick=function(){a.setMultiSelect(!a.isMultiSelect());refresh(kind)}});qa('[data-v16-mobile-clear]',scope).forEach(function(b){b.onclick=function(){a.clearSelection();refresh(kind)}});qa('[data-v16-mobile-delete]',scope).forEach(function(b){b.onclick=function(){deleteSelection(kind)}});qa('[data-v16-smaller]',scope).forEach(function(b){b.onclick=function(){a.scaleSelection(.9);refresh(kind)}});qa('[data-v16-larger]',scope).forEach(function(b){b.onclick=function(){a.scaleSelection(1.1);refresh(kind)}})}
function enhance(kind){var p=panel(kind),s=settings(kind),w=work(kind),a=api(kind);if(!p||!s||!w||!a||p.getAttribute('data-v16')==='1')return;injectSmartFit();bindKeyboard();p.setAttribute('data-v16','1');var assist=s.querySelector('[data-v15-assist]');if(assist){var box=document.createElement('div');box.innerHTML=selectionHtml(kind);assist.insertBefore(box.firstChild,assist.querySelector('[data-v15-magic]')||assist.firstChild)}var mb=document.createElement('div');mb.innerHTML=mobileBarHtml(kind);w.appendChild(mb.firstChild);var nativeDelete=el(kind==='worksheet'?'wdDelete':'gdDelete');if(nativeDelete){nativeDelete.className=(nativeDelete.className?nativeDelete.className+' ':'')+'v16-delete';nativeDelete.setAttribute('aria-label','حذف العنصر أو العناصر المحددة')}bindSelectionControls(kind,p);refresh(kind);p.addEventListener('click',function(){setTimeout(function(){refresh(kind)},30)},false);p.addEventListener('touchend',function(){setTimeout(function(){refresh(kind)},40)},win.App360TouchOptions||false)}
function wrap(){var w=win.App360WorksheetDesigner,g=win.App360GameDesigner;if(w&&w.open&&!w._v16Wrapped){var ow=w.open;w.open=function(game){ow(game);setTimeout(function(){enhance('worksheet')},90)};w._v16Wrapped=true}if(g&&g.open&&!g._v16Wrapped){var og=g.open;g.open=function(){og();setTimeout(function(){enhance('game')},90)};g._v16Wrapped=true}}
injectSmartFit();bindKeyboard();wrap();
win.App360DesignerV16={version:'16.1',enhance:enhance,refresh:refresh,feedback:feedback,deleteSelection:deleteSelection};
})(window);
