(function(){'use strict';
var doc=document,win=window,dirty=false,lastPanel=null,activeMouse=null,drag=null,suppressClickUntil=0,lastMoveAt=0;
var ua=navigator.userAgent||'',legacy=/Android\s(?:[0-4])(?:\.|;)/i.test(ua)||((' '+doc.documentElement.className+' ').indexOf(' legacy-android ')>=0);
function hasClass(n,c){return !!n&&(' '+(n.className||'')+' ').indexOf(' '+c+' ')>=0}
function parentClass(n,c){while(n&&n!==doc){if(hasClass(n,c))return n;n=n.parentNode}return null}
function parentAttr(n,a){while(n&&n!==doc){if(n.getAttribute&&n.getAttribute(a)!==null)return n;n=n.parentNode}return null}
function designerPanel(){return doc.querySelector('.wd9-panel')||doc.querySelector('.gd-panel')}
function designerVisible(){var o=doc.getElementById('drawingOverlay');return !!(o&&!o.hidden&&designerPanel())}
function kindNow(){return doc.querySelector('.wd9-panel')?'worksheet':(doc.querySelector('.gd-panel')?'game':null)}
function warnText(){return'يوجد عمل غير محفوظ في المصمم. هل تريد إغلاقه وفقد التعديلات الحالية؟'}
function stop(e){if(e.preventDefault)e.preventDefault();if(e.stopImmediatePropagation)e.stopImmediatePropagation();else if(e.stopPropagation)e.stopPropagation();e.cancelBubble=true;return false}
function note(t){var n=doc.createElement('div');n.className='v14-save-warning';n.innerHTML=t;doc.body.appendChild(n);setTimeout(function(){if(n.parentNode)n.parentNode.removeChild(n)},2500)}
function markDirty(){if(designerVisible())dirty=true}
function clearDirty(){dirty=false}
win.App360DesignerGuard={isDirty:function(){return dirty},markDirty:markDirty,clearDirty:clearDirty};
function point(e){var t=e.touches&&e.touches[0]?e.touches[0]:(e.changedTouches&&e.changedTouches[0]?e.changedTouches[0]:e),x=t.clientX,y=t.clientY;if(x==null&&t.pageX!=null)x=t.pageX-(win.pageXOffset||0);if(y==null&&t.pageY!=null)y=t.pageY-(win.pageYOffset||0);return{x:Number(x)||0,y:Number(y)||0}}
function mouseEvent(type,p){var ev;try{ev=doc.createEvent('MouseEvents');ev.initMouseEvent(type,true,true,win,1,p.x,p.y,p.x,p.y,false,false,false,false,0,null)}catch(e){try{ev=doc.createEvent('Event');ev.initEvent(type,true,true);ev.clientX=p.x;ev.clientY=p.y}catch(e2){return null}}return ev}
function dispatchMouse(target,type,p){var ev=mouseEvent(type,p);if(ev&&target&&target.dispatchEvent)target.dispatchEvent(ev)}
function ghost(label,img,p){var g=doc.createElement('div');g.className='v15-tool-ghost';if(img)g.innerHTML='<img src="'+img+'" alt=""><small>'+label+'</small>';else g.innerHTML=label;doc.body.appendChild(g);positionGhost(g,p);return g}
function positionGhost(g,p){if(!g)return;g.style.left=Math.max(0,p.x-42)+'px';g.style.top=Math.max(0,p.y-36)+'px'}
function removeGhost(){if(drag&&drag.ghost&&drag.ghost.parentNode)drag.ghost.parentNode.removeChild(drag.ghost)}
function toolInfo(t){var b=parentAttr(t,'data-wdshape');if(b)return{kind:'tool',tool:'shape:'+b.getAttribute('data-wdshape'),label:b.textContent||'شكل'};b=parentClass(t,'wd-tools');var n=t;while(n&&n!==b){if(n.id==='wdAddLine')return{kind:'tool',tool:'line',label:'خط'};if(n.id==='wdAddCheckbox')return{kind:'tool',tool:'checkbox',label:'مربع اختيار'};n=n.parentNode}return null}
function resetOnOpen(){var p=designerPanel();if(p!==lastPanel){lastPanel=p;dirty=false}}
setInterval(resetOnOpen,350);
doc.addEventListener('click',function(e){var t=e.target||e.srcElement,close=parentAttr(t,'data-close-wd')||parentAttr(t,'data-close-gd');if(close&&designerVisible()){if(hasClass(close,'drawing-backdrop')){note('لن تُغلق مساحة العمل بلمس الخلفية. استخدم زر × عند الانتهاء.');return stop(e)}if(dirty&&win.confirm&&!win.confirm(warnText()))return stop(e);if(win.App360DesignerStore){var k=kindNow();if(k)win.App360DesignerStore.clearDraft(k,function(){})}dirty=false;return}if(t&&t.id==='updateBtn'&&dirty){if(win.confirm&&!win.confirm('لديك عمل غير محفوظ. التحديث قد يعيد تحميل الصفحة. هل تريد المتابعة؟'))return stop(e);dirty=false}if(parentClass(t,'wd-item')||parentClass(t,'gd-item')||parentClass(t,'wd-asset')||parentClass(t,'gd-asset'))markDirty()},true);
doc.addEventListener('input',function(e){var t=e.target||e.srcElement;if(!designerVisible()||!t)return;if(t.id==='wdAssetSearch'||t.id==='wdWebSearch'||t.id==='gdSearch')return;markDirty()},true);
doc.addEventListener('change',function(e){var t=e.target||e.srcElement;if(!designerVisible()||!t)return;if(t.id==='wdSaved'||t.id==='gdSaved'||t.id==='v15BrowserSaved')return;markDirty()},true);
win.addEventListener('beforeunload',function(e){if(!dirty)return;var m='لديك عمل غير محفوظ.';e.returnValue=m;return m});
win.addEventListener('popstate',function(e){if(!designerVisible()||!dirty)return;if(win.confirm&&win.confirm(warnText())){var k=kindNow();if(win.App360DesignerStore&&k)win.App360DesignerStore.clearDraft(k,function(){});dirty=false;return}try{history.pushState({a1Overlay:'drawing-guard'},'',location.href)}catch(err){}stop(e)},false);
if(navigator.serviceWorker&&navigator.serviceWorker.addEventListener)navigator.serviceWorker.addEventListener('controllerchange',function(e){if(!dirty)return;note('التحديث جاهز، وسيُطبق بعد حفظ العمل.');stop(e)},false);
if(legacy){
 doc.addEventListener('touchstart',function(e){var t=e.target||e.srcElement,p=point(e),asset=parentClass(t,'wd-asset')||parentClass(t,'gd-asset'),ti=toolInfo(t);if(asset){var im=asset.getElementsByTagName('img')[0];drag={type:'asset',asset:asset,start:p,last:p,moved:false,ghost:null,kind:hasClass(asset,'wd-asset')?'wd':'gd',img:im?im.src:'',label:asset.getAttribute('data-label')||asset.textContent||'صورة'};return}if(ti){drag={type:'tool',tool:ti.tool,start:p,last:p,moved:false,ghost:null,kind:'wd',label:ti.label};return}var handle=parentClass(t,'wd-handle')||parentClass(t,'gd-resize'),item=parentClass(t,'wd-item')||parentClass(t,'gd-item'),target=handle||item;if(!target)return;if(item&&hasClass(item,'wd-item')){var sel=doc.querySelector('[data-wdtool="select"]');if(sel&&sel.onclick)sel.onclick()}activeMouse={target:target,last:p,item:item};if(item)item.className+=' v15-touch-active';stop(e);dispatchMouse(target,'mousedown',p);markDirty()},true);
 doc.addEventListener('touchmove',function(e){var p=point(e),now=new Date().getTime();if(activeMouse){activeMouse.last=p;stop(e);if(now-lastMoveAt>=20){lastMoveAt=now;dispatchMouse(doc,'mousemove',p)}return}if(drag){drag.last=p;var dx=p.x-drag.start.x,dy=p.y-drag.start.y;if(!drag.moved&&Math.sqrt(dx*dx+dy*dy)>8){drag.moved=true;drag.ghost=ghost(drag.label,drag.img,p)}if(drag.moved){stop(e);positionGhost(drag.ghost,p)}}},true);
 doc.addEventListener('touchend',function(e){var p=point(e);if(activeMouse){stop(e);dispatchMouse(doc,'mousemove',p);dispatchMouse(doc,'mouseup',p);if(activeMouse.item)activeMouse.item.className=(' '+activeMouse.item.className+' ').replace(' v15-touch-active ',' ').replace(/^\s+|\s+$/g,'');activeMouse=null;return}if(!drag)return;var d=drag;if(d.moved){stop(e);removeGhost();var under=doc.elementFromPoint?doc.elementFromPoint(p.x,p.y):null;if(d.type==='asset'){var target=d.kind==='wd'?parentClass(under,'wd-page'):parentClass(under,'gd-board');if(target){var src=d.asset.getAttribute('data-src')||d.img,label=d.asset.getAttribute('data-label')||d.label;if(d.kind==='wd'&&win.App360WorksheetDesigner&&win.App360WorksheetDesigner.placeAssetAtClient)win.App360WorksheetDesigner.placeAssetAtClient(src,label,p.x,p.y);else if(d.kind==='gd'&&win.App360GameDesigner&&win.App360GameDesigner.placeAssetAtClient)win.App360GameDesigner.placeAssetAtClient(src,label,p.x,p.y);markDirty();suppressClickUntil=new Date().getTime()+700}else note('أفلت الصورة داخل مساحة العمل.')}else if(d.type==='tool'){var pg=parentClass(under,'wd-page');if(pg&&win.App360WorksheetDesigner&&win.App360WorksheetDesigner.placeToolAtClient){win.App360WorksheetDesigner.placeToolAtClient(d.tool,p.x,p.y);markDirty();suppressClickUntil=new Date().getTime()+700}else note('أفلت الأداة داخل ورقة التصميم.')}}drag=null},true);
 doc.addEventListener('touchcancel',function(){if(activeMouse){dispatchMouse(doc,'mouseup',activeMouse.last);activeMouse=null}removeGhost();drag=null},true);
 doc.addEventListener('click',function(e){var t=e.target||e.srcElement;if(new Date().getTime()<suppressClickUntil&&(parentClass(t,'wd-asset')||parentClass(t,'gd-asset')||parentAttr(t,'data-wdshape')||(t&&t.id==='wdAddLine')||(t&&t.id==='wdAddCheckbox')))stop(e)},true);
}
})(window);