(function(){'use strict';
var doc=document,html=doc.documentElement;
function hasClass(n,c){return(' '+(n.className||'')+' ').indexOf(' '+c+' ')>=0}
function addClass(n,c){if(n&&!hasClass(n,c))n.className=(n.className? n.className+' ':'')+c}
var ua=navigator.userAgent||'';var st=doc.createElement('div').style;var old=/Android\s(?:[0-4])(?:\.|;)/i.test(ua)||!('inset' in st);if(old)addClass(html,'legacy-android');
var BASE='../say-and-name/assets/word-images/';
var real={
'حذاء':'w0028.jpg','جورب':'w0029.jpg','قبعة':'w0030.jpg','معطف':'w0392.jpg','قميص':'w0025.jpg','بنطال':'w0026.jpg','سرير':'w0032.jpg','كلب':'w0096.jpg','أرنب':'w0099.jpg','سمكة':'w0098.jpg','طائر':'w0097.jpg','سلحفاة':'corrected-turtle-v24.jpg','أسد':'corrected-lion-v24.jpg','فيل':'corrected-elephant-v24.jpg','قرش':'corrected-shark-v24.jpg','فظ':'corrected-walrus-v24.jpg','برتقال':'w0082.jpg','كمثرى':'w0235.jpg','عنب':'w0083.jpg','بطيخ':'w0085.jpg','جزر':'w0090.jpg','بروكلي':'w0249.jpg','خبز':'w0071.jpg','حليب':'w0075.jpg','جبن':'w0074.jpg','دراجة':'w0114.jpg','حافلة':'w0112.jpg','قطار':'w0115.jpg','طائرة':'w0116.jpg','مروحية':'w0297.jpg','قارب':'w0118.jpg','لعبة':'w0035.jpg','منزل':'w0045.jpg','شجرة':'w0125.jpg','نجمة':'w0139.jpg','قلب':'w0140.jpg','شمس':'w0119.jpg','قمر':'w0120.jpg','صابون':'w0066.jpg','منشفة':'w0067.jpg','نحلة':'w0109.jpg','زهرة':'w0126.jpg','وجه سعيد':'w0622.jpg','عينان':'w0014.jpg','أنف':'w0015.jpg','فم':'w0016.jpg','بذرة':'w0303.jpg','صخرة':'w0776.jpg','نهاية':'w0977.jpg','طبق':'w0057.jpg','حمام':'w0048.jpg','بيضة':'w0760.jpg','فرخ':'w0762.jpg','كتكوت':'w0259.jpg','أسنان':'w0018.jpg','قلم':'w0148.jpg','ورقة':'w0149.jpg','طباخ':'w0366.jpg','طبيب':'w0163.jpg','سماعة طبيب':'w0664.jpg','عامل':'w0371.jpg','مطرقة':'w0566.jpg','سحابة':'w0123.jpg','مطر':'w0124.jpg','مظلة':'w0151.jpg','مكنسة':'w0420.jpg','فراشة':'w0110.jpg','هدف':'w0577.jpg','إشارة مرور':'w0819.jpg','مبنى':'w0833.jpg','جسر':'w0821.jpg','مسطرة':'w0339.jpg','طوب':'w0889.jpg','قدم':'w0022.jpg','طريق':'w0316.jpg','كرسي':'w0039.jpg','كرة':'w0037.jpg','سيارة':'w0111.jpg','تفاحة':'w0080.jpg','موز':'w0081.jpg'};
var symbol={'👟':'حذاء','🧦':'جورب','🧢':'قبعة','🧥':'معطف','👕':'قميص','👖':'بنطال','🛏️':'سرير','🐶':'كلب','🐰':'أرنب','🐟':'سمكة','🐦':'طائر','🐢':'سلحفاة','🦁':'أسد','🐘':'فيل','🦈':'قرش','🦭':'فظ','🍊':'برتقال','🍐':'كمثرى','🍇':'عنب','🍉':'بطيخ','🥕':'جزر','🥦':'بروكلي','🍞':'خبز','🥛':'حليب','🧀':'جبن','🚲':'دراجة','🚌':'حافلة','🚂':'قطار','✈️':'طائرة','🚁':'مروحية','🚤':'قارب','⛵':'قارب','🧸':'لعبة','🏠':'منزل','🌳':'شجرة','⭐':'نجمة','❤️':'قلب','☀️':'شمس','🌞':'شمس','🌙':'قمر','🧼':'صابون','🧻':'منشفة','🐝':'نحلة','🌼':'زهرة','😊':'وجه سعيد','👃':'أنف','👄':'فم','🌰':'بذرة','🪨':'صخرة','🏁':'نهاية','🍽️':'طبق','🛁':'حمام','🥚':'بيضة','🐣':'فرخ','🐥':'كتكوت','😁':'أسنان','✏️':'قلم','📄':'ورقة','👨‍🍳':'طباخ','👨‍⚕️':'طبيب','🩺':'سماعة طبيب','👷':'عامل','🔨':'مطرقة','☁️':'سحابة','🌧️':'مطر','☂️':'مظلة','🧹':'مكنسة','🦋':'فراشة','🎯':'هدف','🚦':'إشارة مرور','🏢':'مبنى','🌉':'جسر','📏':'مسطرة','🧱':'طوب','🦶':'قدم','🛣️':'طريق','🪑':'كرسي','⚽':'كرة','🚗':'سيارة','🍎':'تفاحة','🍌':'موز'};
function trim(s){return String(s||'').replace(/^\s+|\s+$/g,'')}
function putImage(box,label){var file=real[label];if(!file||!box)return;var imgs=box.getElementsByTagName('img'),img=imgs.length?imgs[0]:null;if(!img){img=doc.createElement('img');var b=box.getElementsByTagName('b');if(b.length)box.insertBefore(img,b[0]);else box.insertBefore(img,box.firstChild)}img.src=BASE+file;img.alt=label;addClass(box,'legacy-real-visual');var bs=box.getElementsByTagName('b');for(var j=0;j<bs.length;j++)bs[j].style.display='none'}
function replaceStable(){var nodes=doc.querySelectorAll?doc.querySelectorAll('.stable-visual'):[];for(var i=0;i<nodes.length;i++){var sm=nodes[i].getElementsByTagName('small');if(!sm.length)continue;var label=trim(sm[0].textContent||sm[0].innerText);if(real[label])putImage(nodes[i],label)}var shoes=doc.getElementsByTagName('img');for(var k=0;k<shoes.length;k++){var src=shoes[k].getAttribute('src')||'';if(src.indexOf('/objects/shoe.svg')>=0||src.indexOf('objects/shoe.svg')>=0)shoes[k].src=BASE+'w0028.jpg'}}
function replaceSequence(){var rows=doc.querySelectorAll?doc.querySelectorAll('.sequence-row span'):[];for(var i=0;i<rows.length;i++){var n=rows[i];if(hasClass(n,'missing')||n.getAttribute('data-real-v13')==='1')continue;var raw=trim(n.textContent||n.innerText),label=symbol[raw],file=label&&real[label];if(!file)continue;n.innerHTML='';var img=doc.createElement('img');img.className='legacy-sequence-photo';img.src=BASE+file;img.alt=label;n.appendChild(img);n.setAttribute('data-real-v13','1')}}
function forceOverlay(o){if(!old||!o||o.hidden)return;o.style.display='block';o.style.position='fixed';o.style.top='0px';o.style.right='0px';o.style.bottom='0px';o.style.left='0px';o.style.zIndex='1000000';var de=doc.documentElement;o.style.width=(de.clientWidth||window.innerWidth||1024)+'px';o.style.height=(de.clientHeight||window.innerHeight||600)+'px';o.style.webkitTransform='translateZ(0)'}
function fixOverlays(){forceOverlay(doc.getElementById('sheet'));forceOverlay(doc.getElementById('drawingOverlay'))}
function scan(){replaceStable();replaceSequence();fixOverlays()}
if(doc.addEventListener){doc.addEventListener('click',function(){setTimeout(scan,0);setTimeout(scan,80)},false);window.addEventListener('resize',function(){setTimeout(fixOverlays,30)},false)}
if(window.MutationObserver){try{new MutationObserver(function(){scan()}).observe(doc.body,{childList:true,subtree:true})}catch(e){}}
setInterval(scan,700);scan();
})();
