(function(){
'use strict';
var core=window.ImitatePracticeCore,engine=window.ExperienceEngine,root=document.getElementById('practiceRoot');
var data=null,items=[],byId={},families={},levels={},storyboards={},rawStorage=null,store=null,timerInt=null,timerLeft=60;
var state={view:'library',experience:null,session:null,phase:0,reflection:'',filters:{text:'',levels:[],families:[],availability:[],energy:'all',place:'all'},visible:24,prefs:{largeText:false,hideDuringPlay:true},refocusSearch:false};
try{rawStorage=window.localStorage}catch(e){}store=core.storageAdapter(rawStorage);
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function el(id){return document.getElementById(id)}
function toast(msg){var n=el('appPwaNotice');n.textContent=msg;n.style.display='block';clearTimeout(toast.t);toast.t=setTimeout(function(){n.style.display='none'},3000)}
function toggle(arr,v){var a=arr.slice(),i=a.indexOf(v);if(i>=0)a.splice(i,1);else a.push(v);return a}
function chip(text,active,attr){return'<button class="chip '+(active?'active':'')+'" type="button" '+attr+'>'+text+'</button>'}
function savePrefs(){try{if(rawStorage)rawStorage.setItem('app360:a1-imitate:v2:prefs',JSON.stringify(state.prefs))}catch(e){}}
function loadPrefs(){try{var p=rawStorage&&rawStorage.getItem('app360:a1-imitate:v2:prefs');if(p)state.prefs=Object.assign(state.prefs,JSON.parse(p))}catch(e){}applyPrefs()}
function applyPrefs(){document.documentElement.classList.toggle('large-text',!!state.prefs.largeText)}
function storageStatus(){var b=el('storageBanner');if(store.isPersistent()){b.hidden=true;return}b.hidden=false;b.innerHTML='<strong>الحفظ الدائم غير متاح.</strong> ستعمل التجارب بذاكرة مؤقتة؛ صدّر السجل قبل الإغلاق إذا أردت الاحتفاظ به.'}
function saveCurrent(){if(state.session)store.saveCurrent({state:{view:state.view,experienceId:state.experience&&state.experience.id,phase:state.phase,reflection:state.reflection},session:state.session})}
function clearCurrent(){store.clearCurrent()}
function toolLabel(a){var x=(data.availability||[]).find(function(v){return v.id===a});return x?x.icon+' '+x.label:a}
function energyLabel(x){return x==='quiet'?'هادئة':x==='active'?'حركية':'متوسطة'}
function placeLabel(x){return x==='floor'?'على الأرض':x==='table'?'على الطاولة':'أي مكان'}
function progress(n,total){var s='<div class="progress">';for(var i=1;i<=total;i++)s+='<i class="'+(i<=n?'on':'')+'"></i>';return s+'</div>'}
function renderLoading(){root.innerHTML='<div class="loading"><div class="spinner"></div><b>جارٍ تجهيز 200 تجربة…</b></div>'}
function renderError(msg){root.innerHTML='<div class="empty-state"><div>⚠️</div><h2>تعذر تحميل المكتبة</h2><p>'+esc(msg)+'</p><button class="btn primary" id="retryBtn">إعادة المحاولة</button></div>';el('retryBtn').onclick=boot}
function getFiltered(){return engine.filter(items,state.filters)}
function renderLibrary(){
state.view='library';state.experience=null;state.phase=0;var filtered=getFiltered(),shown=filtered.slice(0,state.visible),active=state.filters.levels.length+state.filters.families.length+state.filters.availability.length+(state.filters.energy!=='all'?1:0)+(state.filters.place!=='all'?1:0)+(state.filters.text?1:0);
var current=store.loadCurrent(),resume=current&&current.session&&byId[current.session.task_id]?'<div class="resume-banner"><span>⏯ لديك تجربة غير مكتملة: <b>'+esc(byId[current.session.task_id].title)+'</b></span><button id="resumeBtn" class="btn secondary">متابعة</button><button id="discardResume" class="btn ghost">إلغاء</button></div>':'';
var h=resume+'<section class="hero-mini"><div><span class="count-pill">200 تجربة مشتركة</span><h2>اختر ما يناسب لحظتكم الآن</h2><p>حركات، أصابع، ورق، أدوات منزلية، لعب تمثيلي وصبورة. الشاشة تشرح ثم تترك مساحة للعب الحقيقي.</p></div><button id="surpriseBtn" class="surprise-btn"><span>🎲</span>فاجئني</button></section>';
h+='<div class="search-row"><label class="search-box"><span>⌕</span><input id="searchInput" value="'+esc(state.filters.text)+'" placeholder="ابحث: تركيز، ورق، رسم…" autocomplete="off"></label><button id="filtersBtn" class="filter-btn">☰ فلاتر'+(active?' <b>'+active+'</b>':'')+'</button></div><div class="level-strip">'+chip('كل المستويات',!state.filters.levels.length,'data-level="all"');
data.levels.forEach(function(l){h+=chip(l.id+' · '+l.title,state.filters.levels.indexOf(l.id)>=0,'data-level="'+l.id+'"')});h+='</div><div class="family-strip">'+chip('كل المجالات',!state.filters.families.length,'data-family="all"');
data.families.forEach(function(f){h+=chip(f.icon+' '+f.title,state.filters.families.indexOf(f.id)>=0,'data-family="'+f.id+'"')});h+='</div><div class="results-head"><b>'+filtered.length+' تجربة</b><span>يعرض '+shown.length+' الآن</span></div><div class="experience-grid">';
shown.forEach(function(x){var f=families[x.family],l=levels[x.level];h+='<button class="experience-card" data-exp="'+x.id+'"><div class="card-art"><span>'+esc(x.icon)+'</span><em>'+x.id+'</em></div><div class="card-body"><div class="card-kicker">'+esc(f.icon+' '+f.title)+' · '+esc(l.short)+'</div><b>'+esc(x.title)+'</b><div class="card-meta"><span>⏱ '+x.duration_minutes+' د</span><span>'+esc(toolLabel(x.availability))+'</span></div></div></button>'});
h+='</div>';if(shown.length<filtered.length)h+='<div class="load-more"><button id="moreBtn" class="btn secondary">عرض المزيد ('+(filtered.length-shown.length)+')</button></div>';if(!filtered.length)h+='<div class="empty-state"><div>🔎</div><h3>لا توجد نتيجة بهذه الفلاتر</h3><button class="btn secondary" id="resetFilters">مسح الفلاتر</button></div>';root.innerHTML=h;
var search=el('searchInput');search.oninput=function(){state.filters.text=this.value;state.visible=24;state.refocusSearch=true;clearTimeout(renderLibrary.t);renderLibrary.t=setTimeout(renderLibrary,140)};if(state.refocusSearch){state.refocusSearch=false;setTimeout(function(){search.focus();var n=search.value.length;try{search.setSelectionRange(n,n)}catch(e){}},0)}
root.querySelectorAll('[data-level]').forEach(function(b){b.onclick=function(){var v=this.getAttribute('data-level');state.filters.levels=v==='all'?[]:toggle(state.filters.levels,Number(v));state.visible=24;renderLibrary()}});
root.querySelectorAll('[data-family]').forEach(function(b){b.onclick=function(){var v=this.getAttribute('data-family');state.filters.families=v==='all'?[]:toggle(state.filters.families,v);state.visible=24;renderLibrary()}});
root.querySelectorAll('[data-exp]').forEach(function(b){b.onclick=function(){openExperience(this.getAttribute('data-exp'))}});
el('surpriseBtn').onclick=function(){var x=engine.pick(filtered.length?filtered:items);if(x)openExperience(x.id)};el('filtersBtn').onclick=openFilters;
if(el('moreBtn'))el('moreBtn').onclick=function(){state.visible+=24;renderLibrary()};if(el('resetFilters'))el('resetFilters').onclick=function(){state.filters={text:'',levels:[],families:[],availability:[],energy:'all',place:'all'};state.visible=24;renderLibrary()};
if(el('resumeBtn'))el('resumeBtn').onclick=resumeCurrent;if(el('discardResume'))el('discardResume').onclick=function(){clearCurrent();renderLibrary()};
}
function storyboardFallback(x){var h='<div class="storyboard-grid">';x.steps.forEach(function(s,i){h+='<div class="story-frame"><div class="frame-no">'+(i+1)+'</div><div class="frame-icon">'+esc(s.icon)+'</div><b>'+esc(s.label)+'</b><p>'+esc(s.text)+'</p></div>'});return h+'</div>'}
function renderStoryboard(x){var asset=storyboards[x.id];if(asset)return'<figure class="real-storyboard"><img src="'+esc(asset)+'" alt="مراحل تجربة '+esc(x.title)+'"><figcaption>صورة واحدة تجمع مراحل التجربة، والخطوات النصية متاحة أسفلها.</figcaption></figure>'+storyboardFallback(x);return'<div class="story-placeholder-note">🖼️ <b>موضع الصورة الحقيقية محفوظ.</b> حاليًا نعرض خمس لقطات رمزية ثابتة، ويمكن استبدالها بصورة واحدة لاحقًا دون تغيير البرمجة.</div>'+storyboardFallback(x)}
function openExperience(id){
var x=byId[id];if(!x)return;state.experience=x;state.view='detail';var f=families[x.family],l=levels[x.level],tools=x.tools.length?x.tools.map(function(t){return'<span class="tool-pill">'+esc(t.icon+' '+t.name)+'</span>'}).join(''):'<span class="tool-pill">🙌 بدون أدوات</span>',alts=x.alternatives.length?'<div class="alternatives"><b>بدائل:</b> '+x.alternatives.map(esc).join(' · ')+'</div>':'';
root.innerHTML='<button class="back-link" id="backLibrary">→ المكتبة</button><div class="experience-title"><div class="big-icon">'+esc(x.icon)+'</div><div><div class="card-kicker">'+esc(f.title)+' · '+esc(l.short)+'</div><h2>'+esc(x.title)+'</h2><div class="detail-meta"><span>⏱ '+x.duration_minutes+' دقائق</span><span>⚡ '+energyLabel(x.energy)+'</span><span>📍 '+placeLabel(x.place)+'</span></div></div></div><div class="tools-box"><div><b>ما الذي تحتاجه؟</b><div class="tool-list">'+tools+'</div>'+alts+'</div><span class="availability-badge">'+esc(toolLabel(x.availability))+'</span></div>'+renderStoryboard(x)+'<div class="coach-box"><b>للمرافق</b><p>'+esc(x.facilitator_tip)+'</p></div><details class="safe-details"><summary>السلامة والتدرج</summary><div class="safe-grid"><div><b>أسهل</b><p>'+esc(x.easier)+'</p></div><div><b>أصعب</b><p>'+esc(x.harder)+'</p></div><div><b>سلامة</b><ul>'+x.safety.map(function(s){return'<li>'+esc(s)+'</li>'}).join('')+'</ul></div></div></details><div class="sticky-actions"><button id="startExperience" class="btn primary grow">ابدأ التجربة</button>'+(x.helper?'<button id="openHelperForExp" class="btn secondary">أداة مساعدة</button>':'')+'</div>';
el('backLibrary').onclick=renderLibrary;el('startExperience').onclick=startExperience;if(el('openHelperForExp'))el('openHelperForExp').onclick=function(){openHelpers(x.helper)};window.scrollTo(0,0)
}
function startExperience(){if(!state.experience)return;state.session=core.createSession(state.experience.id);state.reflection='';state.phase=1;renderPractice()}
function practiceShell(title,text,inside){var x=state.experience,s=x.steps[Math.min(state.phase-1,4)],visual=state.prefs.hideDuringPlay&&state.phase>=2?'<div class="quiet-visual"><div>'+esc(s.icon)+'</div><b>'+esc(s.label)+'</b></div>':'<div class="practice-step-card"><span>'+esc(s.icon)+'</span><div><b>'+esc(s.label)+'</b><p>'+esc(s.text)+'</p></div></div>';return'<button class="back-link" data-exit>→ خروج</button>'+progress(state.phase,5)+'<div class="practice-focus">'+visual+'<h2>'+esc(title)+'</h2><p class="lead">'+esc(text)+'</p>'+inside+'<div class="practice-tools-row"><button class="btn ghost" data-remodel>↺ أعد الشرح</button>'+(x.helper?'<button class="btn ghost" data-helper>🧰 أداة مساعدة</button>':'')+'<button class="btn ghost" data-skip>تجاوز</button></div></div>'}
function renderPractice(){state.view='practice';saveCurrent();var x=state.experience,h='';if(state.phase===1)h=practiceShell('جهّز واعرض مرة واحدة',x.steps[0].text+' '+x.steps[1].text,'<button class="btn primary wide" data-next>تم الشرح — ابدأ اللعب</button>');if(state.phase===2)h=practiceShell('دوري',x.steps[1].text,'<button class="btn primary wide" data-next>تم دوري — الآن دور الطفل</button>');if(state.phase===3)h=practiceShell('دور الطفل',x.steps[2].text,'<div class="assist-grid"><button class="assist-btn" data-help="independent">محاولة ذاتية<small>دون مساعدة</small></button><button class="assist-btn" data-help="gesture">إشارة فقط<small>تلميح بسيط</small></button><button class="assist-btn" data-help="model">احتاج نموذجًا<small>إعادة العرض</small></button><button class="assist-btn" data-help="direct">مساعدة مباشرة<small>مساعدة قصيرة</small></button></div>');if(state.phase===4)h=practiceShell('بدّل القيادة',x.steps[3].text,'<button class="btn primary wide" data-next>تم تبديل الدور</button>');if(state.phase===5)h=practiceShell('الجولة المطوّرة',x.steps[4].text,'<button class="btn primary wide" data-finish>اكتملت التجربة</button>');root.innerHTML=h;bindPractice();window.scrollTo(0,0)}
function bindPractice(){root.querySelectorAll('[data-exit]').forEach(function(b){b.onclick=function(){renderLibrary()}});root.querySelectorAll('[data-remodel]').forEach(function(b){b.onclick=function(){state.session=core.replayModel(state.session);state.phase=1;renderPractice()}});root.querySelectorAll('[data-skip]').forEach(function(b){b.onclick=skipExperience});root.querySelectorAll('[data-helper]').forEach(function(b){b.onclick=function(){openHelpers(state.experience.helper)}});root.querySelectorAll('[data-next]').forEach(function(b){b.onclick=function(){state.phase++;renderPractice()}});root.querySelectorAll('[data-help]').forEach(function(b){b.onclick=function(){state.session=core.recordAttempt(state.session,this.getAttribute('data-help'));state.phase=4;renderPractice()}});var f=root.querySelector('[data-finish]');if(f)f.onclick=renderComplete}
function skipExperience(){if(state.session){state.session=core.skip(state.session);store.append(state.session)}clearCurrent();state.session=null;state.experience=null;renderLibrary()}
function renderComplete(){if(state.session.status!=='completed')state.session=core.complete(state.session,{roleExchangeCompleted:true,childLedTurnCompleted:true,reflection:state.reflection});state.phase=6;state.view='complete';saveCurrent();var x=state.experience,sum=core.summary(state.session);root.innerHTML='<div class="success"><div class="success-mark">✓</div><h2>اكتملت التجربة</h2><p class="lead">سجل بسيط للمرافق، لا درجة ولا تشخيص.</p><div class="summary-list"><div class="summary-item"><span>التجربة</span><b>'+esc(x.title)+'</b></div><div class="summary-item"><span>المساعدة</span><b>'+esc(sum.assistance_label)+'</b></div><div class="summary-item"><span>إعادة الشرح</span><b>'+sum.replay_count+'</b></div><div class="summary-item"><span>تبادل الدور</span><b>تم</b></div></div><label class="reflection-label">ملاحظة اختيارية<textarea id="reflection" maxlength="300" placeholder="ما الذي بادر به الطفل؟">'+esc(state.reflection)+'</textarea></label><div class="action-row"><button id="saveDone" class="btn primary">حفظ وإنهاء</button><button id="sameAgain" class="btn secondary">أعدها</button><button id="nextSimilar" class="btn ghost">تجربة مشابهة</button></div></div>';el('reflection').oninput=function(){state.reflection=this.value;state.session.reflection=state.reflection.slice(0,300);saveCurrent()};el('saveDone').onclick=finishSession;el('sameAgain').onclick=function(){persistCompleted();startExperience()};el('nextSimilar').onclick=function(){persistCompleted();var a=items.filter(function(v){return v.family===x.family&&v.level===x.level&&v.id!==x.id}),n=engine.pick(a);if(n)openExperience(n.id);else renderLibrary()}}
function persistCompleted(){state.reflection=el('reflection')?el('reflection').value:state.reflection;state.session=core.complete(state.session,{roleExchangeCompleted:true,childLedTurnCompleted:true,reflection:state.reflection});store.append(state.session);clearCurrent()}
function finishSession(){persistCompleted();state.session=null;state.experience=null;renderLibrary();toast('حُفظت المحاولة محليًا.')}
function resumeCurrent(){var c=store.loadCurrent();if(!c||!c.session)return;var x=byId[c.session.task_id];if(!x){clearCurrent();return renderLibrary()}state.experience=x;state.session=c.session;state.phase=(c.state&&c.state.phase)||1;state.reflection=(c.state&&c.state.reflection)||c.session.reflection||'';if(c.session.status==='completed'||state.phase>=6)renderComplete();else renderPractice()}
function openFilters(){var h='<div class="filter-groups"><div><b>الأدوات</b><div class="chip-wrap">';data.availability.forEach(function(a){h+=chip(a.icon+' '+a.label,state.filters.availability.indexOf(a.id)>=0,'data-tool="'+a.id+'"')});h+='</div></div><div><b>الطاقة</b><div class="chip-wrap">'+[['all','الكل'],['quiet','هادئة'],['medium','متوسطة'],['active','حركية']].map(function(v){return chip(v[1],state.filters.energy===v[0],'data-energy="'+v[0]+'"')}).join('')+'</div></div><div><b>المكان</b><div class="chip-wrap">'+[['all','أي مكان'],['floor','الأرض'],['table','الطاولة']].map(function(v){return chip(v[1],state.filters.place===v[0],'data-place="'+v[0]+'"')}).join('')+'</div></div><button class="btn ghost wide" id="clearAdvanced">مسح الفلاتر الإضافية</button></div>';openSheet('الفلاتر',h);document.querySelectorAll('[data-tool]').forEach(function(b){b.onclick=function(){state.filters.availability=toggle(state.filters.availability,this.getAttribute('data-tool'));openFilters()}});document.querySelectorAll('[data-energy]').forEach(function(b){b.onclick=function(){state.filters.energy=this.getAttribute('data-energy');openFilters()}});document.querySelectorAll('[data-place]').forEach(function(b){b.onclick=function(){state.filters.place=this.getAttribute('data-place');openFilters()}});el('clearAdvanced').onclick=function(){state.filters.availability=[];state.filters.energy='all';state.filters.place='all';closeSheet();renderLibrary()}}
function openSettings(){openSheet('الإعدادات','<div class="settings-list"><label><span><b>نص أكبر</b><small>يكبّر العناوين والنصوص</small></span><input id="largeTextToggle" type="checkbox" '+(state.prefs.largeText?'checked':'')+'></label><label><span><b>وضع هادئ أثناء اللعب</b><small>يقلل تفاصيل الشاشة بعد بدء التجربة</small></span><input id="hidePlayToggle" type="checkbox" '+(state.prefs.hideDuringPlay?'checked':'')+'></label></div>');el('largeTextToggle').onchange=function(){state.prefs.largeText=this.checked;savePrefs();applyPrefs()};el('hidePlayToggle').onchange=function(){state.prefs.hideDuringPlay=this.checked;savePrefs()}}
function openHistory(){var rows=store.list(),h=rows.length?'':'<div class="history-empty">لا توجد محاولات محفوظة بعد.</div>';rows.forEach(function(s){var x=byId[s.task_id],sum=core.summary(s);h+='<div class="history-row"><b>'+esc(x?x.title:s.task_id)+'</b><small>'+esc(sum.status==='completed'?'مكتملة':'متجاوزة')+' · '+esc(sum.assistance_label)+' · إعادة: '+sum.replay_count+'</small></div>'});h+='<div class="sheet-actions"><button class="btn secondary" id="exportAll">تصدير JSON</button><button class="btn danger" id="clearAll">حذف السجل</button></div><p class="micro">السجل محلي فقط.</p>';openSheet('السجل المحلي',h);el('exportAll').onclick=downloadExport;el('clearAll').onclick=function(){if(confirm('حذف السجل المحلي؟')){store.clear();closeSheet();toast('تم حذف السجل.')}}}
function downloadExport(){var p=store.exportPayload(state.session),blob=new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='a1-imitate-export-'+new Date().toISOString().slice(0,10)+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url)},400)}
function openHelpers(prefer){openSheet('أدوات مساعدة','<div class="helper-tabs"><button class="chip" data-helper-tab="timer">⏱ مؤقت</button><button class="chip" data-helper-tab="signal">🚦 إشارة</button><button class="chip" data-helper-tab="whiteboard">✏️ صبورة</button></div><div id="helperBody"></div>');var tab=prefer||'timer';document.querySelectorAll('[data-helper-tab]').forEach(function(b){if(b.getAttribute('data-helper-tab')===tab)b.classList.add('active');b.onclick=function(){document.querySelectorAll('[data-helper-tab]').forEach(function(x){x.classList.remove('active')});this.classList.add('active');renderHelperTab(this.getAttribute('data-helper-tab'))}});renderHelperTab(tab)}
function renderHelperTab(tab){var b=el('helperBody');if(timerInt){clearInterval(timerInt);timerInt=null}if(tab==='timer'){b.innerHTML='<div class="timer-tool"><div id="timerDisplay">01:00</div><div class="action-row"><button class="btn secondary" data-min="1">1 دقيقة</button><button class="btn secondary" data-min="3">3 دقائق</button><button class="btn secondary" data-min="5">5 دقائق</button></div><button id="timerStart" class="btn primary wide">ابدأ</button></div>';timerLeft=60;document.querySelectorAll('[data-min]').forEach(function(x){x.onclick=function(){timerLeft=Number(this.getAttribute('data-min'))*60;updateTimer()}});el('timerStart').onclick=function(){if(timerInt)clearInterval(timerInt);timerInt=setInterval(function(){timerLeft--;updateTimer();if(timerLeft<=0){clearInterval(timerInt);timerInt=null;toast('انتهى الوقت')}},1000)};return}if(tab==='signal'){b.innerHTML='<div class="signal-tool"><div id="signalFace" class="signal-face wait">انتظر</div><div class="signal-buttons"><button data-signal="go">ابدأ</button><button data-signal="wait">انتظر</button><button data-signal="stop">توقف</button></div></div>';document.querySelectorAll('[data-signal]').forEach(function(x){x.onclick=function(){var v=this.getAttribute('data-signal'),f=el('signalFace');f.className='signal-face '+v;f.textContent=v==='go'?'ابدأ':v==='stop'?'توقف':'انتظر'}});return}b.innerHTML='<div class="whiteboard-tool"><canvas id="board" width="900" height="520"></canvas><div class="action-row"><button id="clearBoard" class="btn ghost">مسح الصبورة</button></div></div>';setupBoard()}
function updateTimer(){var m=Math.floor(timerLeft/60),s=timerLeft%60;if(el('timerDisplay'))el('timerDisplay').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function setupBoard(){var c=el('board'),ctx=c.getContext('2d'),down=false,last=null;ctx.lineWidth=10;ctx.lineCap='round';ctx.strokeStyle='#17343a';function pos(e){var r=c.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*c.width/r.width,y:(p.clientY-r.top)*c.height/r.height}}function start(e){down=true;last=pos(e);if(e.cancelable)e.preventDefault()}function move(e){if(!down)return;var p=pos(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p;if(e.cancelable)e.preventDefault()}function end(){down=false;last=null}c.addEventListener('mousedown',start);c.addEventListener('mousemove',move);window.addEventListener('mouseup',end);c.addEventListener('touchstart',start,{passive:false});c.addEventListener('touchmove',move,{passive:false});c.addEventListener('touchend',end);el('clearBoard').onclick=function(){ctx.clearRect(0,0,c.width,c.height)}}
function openSheet(title,body){var sh=el('sheet');el('sheetTitle').textContent=title;el('sheetBody').innerHTML=body;sh.hidden=false;sh.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';sh.querySelectorAll('[data-close-sheet]').forEach(function(b){b.onclick=closeSheet})}
function closeSheet(){if(timerInt){clearInterval(timerInt);timerInt=null}var sh=el('sheet');sh.hidden=true;sh.setAttribute('aria-hidden','true');document.body.style.overflow=''}
function bindHeader(){el('libraryBtn').onclick=renderLibrary;el('historyBtn').onclick=openHistory;el('helpersBtn').onclick=function(){openHelpers(null)};el('settingsBtn').onclick=openSettings;document.addEventListener('keydown',function(e){if(e.key==='Escape'&&!el('sheet').hidden)closeSheet()})}
function boot(){renderLoading();Promise.all([fetch('experiences.json?v=1',{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('experiences '+r.status);return r.json()}),fetch('storyboards/manifest.json?v=1',{cache:'no-store'}).then(function(r){return r.ok?r.json():{assets:{}}}).catch(function(){return{assets:{}}})]).then(function(res){data=res[0];items=data.experiences||[];storyboards=res[1].assets||{};families=engine.familyMap(data);levels=engine.levelMap(data);byId={};items.forEach(function(x){byId[x.id]=x});if(items.length!==200)throw new Error('المكتبة غير مكتملة: '+items.length);loadPrefs();storageStatus();var c=store.loadCurrent();if(c&&c.session&&!byId[c.session.task_id])clearCurrent();renderLibrary()}).catch(function(e){renderError(e.message||'خطأ غير معروف')})}
bindHeader();boot();
}());