(function(){'use strict';
var engine=window.ExperienceEngine,activityApi=window.A1ActivityStore,communityEngine=window.A1CommunityEngine,drawingApi=window.A1DrawingLab,root=document.getElementById('practiceRoot');
var data=null,items=[],byId={},families={},levels={},storyboards={},community={enabled:false},rawStorage=null,activity=null,timerInt=null,timerLeft=60,reelTimer=null,drawingSession=null,communityCache={comments:null,loadedAt:0};
var state={experience:null,filters:{text:'',levels:[],families:[],availability:[],energy:'all',place:'all'},visible:24,prefs:{largeText:false},refocusSearch:false};
try{rawStorage=window.localStorage}catch(e){}activity=activityApi.create(rawStorage);
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function el(id){return document.getElementById(id)}
function toast(msg){var n=el('appPwaNotice');n.textContent=msg;n.style.display='block';clearTimeout(toast.t);toast.t=setTimeout(function(){n.style.display='none'},3000)}
function toggle(arr,v){var a=arr.slice(),i=a.indexOf(v);if(i>=0)a.splice(i,1);else a.push(v);return a}
function chip(text,active,attr){return'<button class="chip '+(active?'active':'')+'" type="button" '+attr+'>'+text+'</button>'}
function toolLabel(a){var x=(data.availability||[]).find(function(v){return v.id===a});return x?x.icon+' '+x.label:a}
function energyLabel(x){return x==='quiet'?'هادئة':x==='active'?'حركية':'متوسطة'}
function placeLabel(x){return x==='floor'?'على الأرض':x==='table'?'على الطاولة':'أي مكان'}
function loadPrefs(){try{var p=rawStorage&&rawStorage.getItem('app360:a1-imitate:v3:prefs');if(p)state.prefs=Object.assign(state.prefs,JSON.parse(p))}catch(e){}applyPrefs()}
function savePrefs(){try{if(rawStorage)rawStorage.setItem('app360:a1-imitate:v3:prefs',JSON.stringify(state.prefs))}catch(e){}}
function applyPrefs(){document.documentElement.classList.toggle('large-text',!!state.prefs.largeText)}
function storageStatus(){var b=el('storageBanner');if(activity.isPersistent()){b.hidden=true;return}b.hidden=false;b.innerHTML='<strong>الحفظ الدائم غير متاح.</strong> سيعمل العداد مؤقتًا حتى إغلاق الصفحة.'}
function getFiltered(){return engine.filter(items,state.filters)}
function cardVisual(x){var asset=storyboards[x.id];if(asset)return '<div class="card-thumb-frame"><img src="'+esc(asset)+'" alt="" loading="lazy"></div>';return '<div class="card-art"><span>'+esc(x.icon)+'</span><em>'+x.id+'</em></div>'}
function globalMethod(){return'<section class="global-method"><div class="method-title"><span>طريقة واحدة لكل التجارب</span><h3>شاهد الفكرة ثم العبها بطريقتكم</h3></div><div class="method-row"><div><b>1</b><span>شاهد اللقطات</span></div><div><b>2</b><span>نفّذ أنت مرة</span></div><div><b>3</b><span>دع الطفل يجرب</span></div><div><b>4</b><span>بدّلوا القيادة</span></div><div><b>5</b><span>سجّل التنفيذ والتحسين</span></div></div><p>لا يلزم الالتزام بحركات حرفية. الهدف هو المشاركة والانتظار والتبادل، ويمكن تبسيط أي فكرة أو تطويرها بحسب استعداد الطفل.</p></section>'}
function renderLoading(){root.innerHTML='<div class="loading"><div class="spinner"></div><b>جارٍ تجهيز 200 تجربة…</b></div>'}
function renderError(msg){root.innerHTML='<div class="empty-state"><div>⚠️</div><h2>تعذر تحميل المكتبة</h2><p>'+esc(msg)+'</p><button class="btn primary" id="retryBtn">إعادة المحاولة</button></div>';el('retryBtn').onclick=boot}
function renderLibrary(){
clearReel();state.experience=null;var filtered=getFiltered(),shown=filtered.slice(0,state.visible),active=state.filters.levels.length+state.filters.families.length+state.filters.availability.length+(state.filters.energy!=='all'?1:0)+(state.filters.place!=='all'?1:0)+(state.filters.text?1:0);
var h='<section class="hero-mini"><div><span class="count-pill">200 تجربة مشتركة</span><h2>الفكرة أمامك واللعب بينكم</h2><p>شاهد اللقطات، طبّق الفكرة في الواقع، ثم سجّل أنها تمت وأضف أي تحسين اكتشفته.</p></div><div class="hero-stats"><strong>'+activity.total()+'</strong><span>إجمالي تنفيذاتك</span><button id="surpriseBtn" class="surprise-btn"><span>🎲</span>فاجئني</button></div></section>';
h+='<div class="search-row"><label class="search-box"><span>⌕</span><input id="searchInput" value="'+esc(state.filters.text)+'" placeholder="ابحث: تركيز، ورق، رسم…" autocomplete="off"></label><button id="filtersBtn" class="filter-btn">☰ فلاتر'+(active?' <b>'+active+'</b>':'')+'</button></div><div class="level-strip">'+chip('كل المستويات',!state.filters.levels.length,'data-level="all"');
data.levels.forEach(function(l){h+=chip(l.id+' · '+l.title,state.filters.levels.indexOf(l.id)>=0,'data-level="'+l.id+'"')});h+='</div><div class="family-strip">'+chip('كل المجالات',!state.filters.families.length,'data-family="all"');data.families.forEach(function(f){h+=chip(f.icon+' '+f.title,state.filters.families.indexOf(f.id)>=0,'data-family="'+f.id+'"')});h+='</div><div class="results-head"><b>'+filtered.length+' تجربة</b><span>يعرض '+shown.length+' الآن</span></div><div class="experience-grid">';
shown.forEach(function(x){var f=families[x.family],l=levels[x.level],stat=activity.get(x.id);h+='<button class="experience-card" data-exp="'+x.id+'">'+cardVisual(x)+'<div class="card-body"><div class="card-kicker">'+esc(f.icon+' '+f.title)+' · '+esc(l.short)+'</div><b>'+esc(x.title)+'</b><div class="card-meta"><span>⏱ '+x.duration_minutes+' د</span><span>'+esc(toolLabel(x.availability))+'</span>'+(stat.count?'<span class="done-mini">✓ '+stat.count+'</span>':'')+'</div></div></button>'});h+='</div>';
if(shown.length<filtered.length)h+='<div class="load-more"><button id="moreBtn" class="btn secondary">عرض المزيد ('+(filtered.length-shown.length)+')</button></div>';if(!filtered.length)h+='<div class="empty-state"><div>🔎</div><h3>لا توجد نتيجة بهذه الفلاتر</h3><button class="btn secondary" id="resetFilters">مسح الفلاتر</button></div>';
h+=globalMethod();root.innerHTML=h;
var search=el('searchInput');search.oninput=function(){state.filters.text=this.value;state.visible=24;state.refocusSearch=true;clearTimeout(renderLibrary.t);renderLibrary.t=setTimeout(renderLibrary,140)};if(state.refocusSearch){state.refocusSearch=false;setTimeout(function(){search.focus();var n=search.value.length;try{search.setSelectionRange(n,n)}catch(e){}},0)}
root.querySelectorAll('[data-level]').forEach(function(b){b.onclick=function(){var v=this.getAttribute('data-level');state.filters.levels=v==='all'?[]:toggle(state.filters.levels,Number(v));state.visible=24;renderLibrary()}});
root.querySelectorAll('[data-family]').forEach(function(b){b.onclick=function(){var v=this.getAttribute('data-family');state.filters.families=v==='all'?[]:toggle(state.filters.families,v);state.visible=24;renderLibrary()}});
root.querySelectorAll('[data-exp]').forEach(function(b){b.onclick=function(){openExperience(this.getAttribute('data-exp'))}});
el('surpriseBtn').onclick=function(){var x=engine.pick(filtered.length?filtered:items);if(x)openExperience(x.id)};el('filtersBtn').onclick=openFilters;
if(el('moreBtn'))el('moreBtn').onclick=function(){state.visible+=24;renderLibrary()};if(el('resetFilters'))el('resetFilters').onclick=function(){state.filters={text:'',levels:[],families:[],availability:[],energy:'all',place:'all'};state.visible=24;renderLibrary()}
}
function renderReel(x){
var asset=storyboards[x.id];if(!asset)return'<div class="symbol-placeholder"><div>'+esc(x.icon)+'</div><b>الصورة المتحركة لهذه التجربة قيد الإضافة</b><span>رقم '+x.id+'</span></div>';
var dots='';for(var i=0;i<5;i++)dots+='<i class="'+(i===0?'on':'')+'" aria-label="اللقطة '+(i+1)+'"></i>';
return'<div class="reel" id="storyReel" data-frames="5"><div class="reel-stage-label" id="reelStageLabel">اللقطة 1 من 5</div><div class="reel-viewport frame-mode" id="reelViewport"><img id="reelStrip" class="reel-strip" src="'+esc(asset)+'" alt="لقطات متتابعة لتجربة '+esc(x.title)+'"></div><div class="reel-controls"><button id="reelPlay" class="reel-play" type="button">⏸ إيقاف</button><div id="reelDots" class="reel-dots">'+dots+'</div><span id="reelCounter">1 / 5</span><button id="reelReplay" class="reel-replay" type="button">↺ إعادة</button></div></div>'
}
function setupReel(){
clearReel();var strip=el('reelStrip'),viewport=el('reelViewport');if(!strip||!viewport)return;
var frame=0,playing=true,overview=false,total=5,play=el('reelPlay'),dots=el('reelDots'),counter=el('reelCounter'),label=el('reelStageLabel');
function setDots(current,all){Array.prototype.forEach.call(dots.children,function(d,i){d.classList.toggle('on',all||i===current)})}
function showFrame(n){
overview=false;frame=Math.max(0,Math.min(total-1,n));viewport.className='reel-viewport frame-mode';strip.style.transform='translate3d('+(-20*frame)+'%,0,0)';setDots(frame,false);counter.textContent=(frame+1)+' / '+total;label.textContent='اللقطة '+(frame+1)+' من '+total
}
function showOverview(){
overview=true;playing=false;clearTimeout(reelTimer);reelTimer=null;viewport.className='reel-viewport overview-mode';strip.style.transform='translate3d(0,0,0)';setDots(frame,true);counter.textContent='الصورة كاملة';label.textContent='كل لقطات التجربة';play.textContent='▶ تشغيل من البداية'
}
function stop(){playing=false;clearTimeout(reelTimer);reelTimer=null;play.textContent=overview?'▶ تشغيل من البداية':'▶ متابعة'}
function schedule(){
clearTimeout(reelTimer);if(!playing)return;
reelTimer=setTimeout(function(){
  if(frame<total-1){showFrame(frame+1);schedule();return}
  showOverview()
},2200)
}
function start(reset){
if(reset||overview)showFrame(0);playing=true;play.textContent='⏸ إيقاف';schedule()
}
play.onclick=function(){if(playing)stop();else start(overview)};
el('reelReplay').onclick=function(){start(true)};
Array.prototype.forEach.call(dots.children,function(d,i){d.onclick=function(){stop();showFrame(i)}});
showFrame(0);schedule()
}
function clearReel(){if(reelTimer){clearTimeout(reelTimer);reelTimer=null}}
function ideaText(x){return'جرّبوا «'+x.title+'» كتجربة مشتركة قصيرة. يعرض المرافق الفكرة مرة، ثم يجرب الطفل بطريقته، وبعدها يتبادل الطرفان القيادة ويضيفان تعديلًا صغيرًا إذا رغبا.'}
function previousExperienceId(id){var n=parseInt(id,10)||1;n--;if(n<1)n=200;return String(n).padStart(3,'0')}
function goPreviousExperience(){if(!state.experience)return;openExperience(previousExperienceId(state.experience.id))}
function nextExperienceId(id){var n=parseInt(id,10)||1;n++;if(n>200)n=1;return String(n).padStart(3,'0')}
function goNextExperience(){if(!state.experience)return;openExperience(nextExperienceId(state.experience.id))}
function openDrawingLab(){if(!drawingApi)return toast('أداة الرسم غير متاحة الآن.');openSheet('🎨 الرسم الجماعي','<div id="drawLabRoot"></div>');var sh=el('sheet');sh.classList.add('drawing-open');drawingSession=drawingApi.mount(el('drawLabRoot'),{experience:state.experience})}
function notesHtml(stat){if(!stat.notes.length)return'<div class="no-notes">لا توجد ملاحظات شخصية لهذه التجربة بعد.</div>';return'<div class="note-list">'+stat.notes.slice(0,5).map(function(n){return'<div class="note-item"><span>'+formatDate(n.at)+'</span><p>'+esc(n.text)+'</p></div>'}).join('')+'</div>'}
function formatDate(v){if(!v)return'';try{return new Date(v).toLocaleDateString('ar',{year:'numeric',month:'short',day:'numeric'})}catch(e){return''}}
function openExperience(id){
clearReel();var x=byId[id];if(!x)return;state.experience=x;var f=families[x.family],l=levels[x.level],stat=activity.get(x.id),tools=x.tools.length?x.tools.map(function(t){return'<span class="tool-pill">'+esc(t.icon+' '+t.name)+'</span>'}).join(''):'<span class="tool-pill">🙌 بدون أدوات</span>';
root.innerHTML='<div class="detail-nav"><button class="back-link" id="backLibrary">→ المكتبة</button><div class="detail-nav-pair"><button class="btn prev-exp-btn" id="previousExperience">→ التجربة السابقة</button><button class="btn next-exp-btn" id="nextExperience">التجربة التالية ←</button></div></div><div class="experience-title compact"><div class="big-icon">'+esc(x.icon)+'</div><div><div class="card-kicker">التجربة '+x.id+' · '+esc(f.title)+' · '+esc(l.short)+'</div><h2>'+esc(x.title)+'</h2><div class="detail-meta"><span>⏱ '+x.duration_minutes+' د</span><span>⚡ '+energyLabel(x.energy)+'</span><span>📍 '+placeLabel(x.place)+'</span></div></div></div>'+
renderReel(x)+
'<section class="idea-card"><span>الفكرة</span><p>'+esc(ideaText(x))+'</p><div class="tool-list">'+tools+'</div>'+(x.alternatives.length?'<small><b>بديل:</b> '+esc(x.alternatives.join(' · '))+'</small>':'')+'</section>'+
'<section class="done-card compact-done"><div class="done-count"><strong id="doneCount">'+stat.count+'</strong><span>مرات تنفيذك لهذه التجربة</span></div><div class="action-row"><button id="markDone" class="btn primary grow">✓ تم عمل التجربة</button><button id="openDrawLab" class="btn drawing-btn">🎨 رسم جماعي</button>'+(x.helper?'<button id="openHelperForExp" class="btn ghost">أداة مساعدة</button>':'')+'<button id="previousExperienceBottom" class="btn ghost">→ التجربة السابقة</button><button id="nextExperienceBottom" class="btn secondary">التجربة التالية ←</button></div></section>'+
'<details id="feedbackPanel" class="feedback-fold"><summary><span>💬 التعليقات والتحسينات</span><small>ملاحظاتي: '+stat.notes.length+' · اضغط للفتح</small></summary><div class="feedback-body"><section class="personal-feedback"><label class="improve-label">ملاحظة أو تحسين خاص بك<textarea id="improveNote" maxlength="500" placeholder="مثال: نجحت أكثر عندما جعلنا الطفل يختار الكوب التالي…"></textarea></label><button id="saveNoteOnly" class="btn secondary">حفظ الملاحظة على جهازي</button><div id="myNotes">'+notesHtml(stat)+'</div></section><section class="community-inline"><div class="community-head"><div><span>تعليقات المجتمع</span><h3>تحسينات وتجارب من مستخدمين آخرين</h3></div><button id="refreshCommunity" class="icon-round" title="تحديث">↻</button></div><div id="communityComments" class="community-comments"><div class="community-empty">افتح هذا القسم لتحميل التعليقات العامة.</div></div><label class="community-compose">شارك تحسينًا عامًا<textarea id="publicComment" maxlength="800" placeholder="اكتب ملاحظة مفيدة دون أسماء أو بيانات شخصية."></textarea></label><button id="publishCommunity" class="btn community-btn">نسخ التعليق وفتح صفحة النشر العام</button><small class="community-help">النشر العام يتم عبر GitHub ويحتاج تسجيل الدخول هناك.</small></section></div></details>'+
globalMethod();
el('backLibrary').onclick=renderLibrary;el('previousExperience').onclick=goPreviousExperience;el('nextExperience').onclick=goNextExperience;el('previousExperienceBottom').onclick=goPreviousExperience;el('nextExperienceBottom').onclick=goNextExperience;el('openDrawLab').onclick=openDrawingLab;
el('markDone').onclick=function(){var r=activity.markDone(x.id,'');refreshLocal(r);toast('تم تسجيل تنفيذ التجربة.')};
el('saveNoteOnly').onclick=function(){var t=el('improveNote').value.trim();if(!t)return toast('اكتب الملاحظة أولًا.');var r=activity.addNote(x.id,t);el('improveNote').value='';refreshLocal(r);toast('تم حفظ الملاحظة على جهازك.')};
if(el('openHelperForExp'))el('openHelperForExp').onclick=function(){openHelpers(x.helper)};
el('refreshCommunity').onclick=function(){loadCommunity(x.id,true)};el('publishCommunity').onclick=function(){preparePublicComment(x.id)};
var feedback=el('feedbackPanel');feedback.ontoggle=function(){if(feedback.open)loadCommunity(x.id,false)};
setupReel();window.scrollTo(0,0)
}
function refreshLocal(r){el('doneCount').textContent=r.count;el('myNotes').innerHTML=notesHtml(r)}
function loadCommunity(id,force){var box=el('communityComments');if(!box)return;if(!community.enabled){box.innerHTML='<div class="community-empty">التعليقات العامة غير مفعلة.</div>';return}var fresh=communityCache.comments&&Date.now()-communityCache.loadedAt<120000;if(fresh&&!force)return renderCommunity(id,communityCache.comments);box.innerHTML='<div class="community-loading">جارٍ تحميل التعليقات العامة…</div>';fetch(community.api_comments_url+'?per_page=100',{headers:{Accept:'application/vnd.github+json'}}).then(function(r){if(!r.ok)throw new Error(String(r.status));return r.json()}).then(function(rows){communityCache={comments:rows,loadedAt:Date.now()};renderCommunity(id,rows)}).catch(function(){box.innerHTML='<div class="community-empty">تعذر تحميل التعليقات الآن. يمكنك فتح صفحة المجتمع مباشرة.</div>'})}
function renderCommunity(id,rows){var box=el('communityComments');if(!box)return;var list=communityEngine.filter(rows,id);if(!list.length){box.innerHTML='<div class="community-empty">لا توجد تعليقات عامة لهذه التجربة بعد. كن أول من يشارك تحسينًا.</div>';return}box.innerHTML=list.slice().reverse().map(function(c){return'<article class="public-comment"><div class="comment-author">'+(c.avatar?'<img src="'+esc(c.avatar)+'" alt="">':'')+'<b>@'+esc(c.user)+'</b><span>'+formatDate(c.created_at)+'</span></div><p>'+esc(c.text)+'</p></article>'}).join('')}
function copyText(text){if(navigator.clipboard&&navigator.clipboard.writeText)return navigator.clipboard.writeText(text);return new Promise(function(resolve,reject){try{var ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();resolve()}catch(e){reject(e)}})}
function preparePublicComment(id){var ta=el('publicComment'),text=ta.value.trim();if(!text)return toast('اكتب التعليق العام أولًا.');var payload=communityEngine.compose(id,text),url=community.web_url+'#new_comment_field';copyText(payload).then(function(){toast('تم نسخ التعليق. الصقه في GitHub ثم انشره.');window.open(url,'_blank','noopener')}).catch(function(){window.prompt('انسخ هذا التعليق ثم انشره في صفحة المجتمع:',payload);window.open(url,'_blank','noopener')})}
function openFilters(){var h='<div class="filter-groups"><div><b>الأدوات</b><div class="chip-wrap">';data.availability.forEach(function(a){h+=chip(a.icon+' '+a.label,state.filters.availability.indexOf(a.id)>=0,'data-tool="'+a.id+'"')});h+='</div></div><div><b>الطاقة</b><div class="chip-wrap">'+[['all','الكل'],['quiet','هادئة'],['medium','متوسطة'],['active','حركية']].map(function(v){return chip(v[1],state.filters.energy===v[0],'data-energy="'+v[0]+'"')}).join('')+'</div></div><div><b>المكان</b><div class="chip-wrap">'+[['all','أي مكان'],['floor','الأرض'],['table','الطاولة']].map(function(v){return chip(v[1],state.filters.place===v[0],'data-place="'+v[0]+'"')}).join('')+'</div></div><button class="btn ghost wide" id="clearAdvanced">مسح الفلاتر الإضافية</button></div>';openSheet('الفلاتر',h);document.querySelectorAll('[data-tool]').forEach(function(b){b.onclick=function(){state.filters.availability=toggle(state.filters.availability,this.getAttribute('data-tool'));openFilters()}});document.querySelectorAll('[data-energy]').forEach(function(b){b.onclick=function(){state.filters.energy=this.getAttribute('data-energy');openFilters()}});document.querySelectorAll('[data-place]').forEach(function(b){b.onclick=function(){state.filters.place=this.getAttribute('data-place');openFilters()}});el('clearAdvanced').onclick=function(){state.filters.availability=[];state.filters.energy='all';state.filters.place='all';closeSheet();renderLibrary()}}
function openSettings(){openSheet('الإعدادات','<div class="settings-list"><label><span><b>نص أكبر</b><small>يكبّر العناوين والنصوص</small></span><input id="largeTextToggle" type="checkbox" '+(state.prefs.largeText?'checked':'')+'></label></div>');el('largeTextToggle').onchange=function(){state.prefs.largeText=this.checked;savePrefs();applyPrefs()}}
function openHistory(){var rows=activity.all(),ids=Object.keys(rows).filter(function(id){return rows[id]&&((rows[id].count||0)||(rows[id].notes||[]).length)}).sort(function(a,b){return String(rows[b].last_done||'').localeCompare(String(rows[a].last_done||''))}),h=ids.length?'':'<div class="history-empty">لم تسجل أي تجربة بعد.</div>';ids.forEach(function(id){var r=rows[id],x=byId[id];h+='<div class="history-row"><b>'+esc(x?x.title:id)+'</b><small>نفذت '+(r.count||0)+' مرات · '+(r.notes||[]).length+' ملاحظات</small></div>'});h+='<div class="sheet-actions"><button class="btn secondary" id="exportAll">تصدير سجلي</button><button class="btn danger" id="clearAll">حذف سجلي</button></div>';openSheet('سجلي',h);el('exportAll').onclick=downloadExport;el('clearAll').onclick=function(){if(confirm('حذف كل العدادات والملاحظات المحلية؟')){activity.clear();closeSheet();renderLibrary();toast('تم حذف السجل المحلي.')}}}
function downloadExport(){var blob=new Blob([JSON.stringify(activity.exportPayload(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='a1-activity-'+new Date().toISOString().slice(0,10)+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url)},400)}
function openHelpers(prefer){openSheet('أدوات مساعدة','<div class="helper-tabs"><button class="chip" data-helper-tab="timer">⏱ مؤقت</button><button class="chip" data-helper-tab="signal">🚦 إشارة</button><button class="chip" data-helper-tab="whiteboard">✏️ صبورة</button></div><div id="helperBody"></div>');var tab=prefer||'timer';document.querySelectorAll('[data-helper-tab]').forEach(function(b){if(b.getAttribute('data-helper-tab')===tab)b.classList.add('active');b.onclick=function(){document.querySelectorAll('[data-helper-tab]').forEach(function(x){x.classList.remove('active')});this.classList.add('active');renderHelperTab(this.getAttribute('data-helper-tab'))}});renderHelperTab(tab)}
function renderHelperTab(tab){var b=el('helperBody');if(timerInt){clearInterval(timerInt);timerInt=null}if(tab==='timer'){b.innerHTML='<div class="timer-tool"><div id="timerDisplay">01:00</div><div class="action-row"><button class="btn secondary" data-min="1">1 دقيقة</button><button class="btn secondary" data-min="3">3 دقائق</button><button class="btn secondary" data-min="5">5 دقائق</button></div><button id="timerStart" class="btn primary wide">ابدأ</button></div>';timerLeft=60;document.querySelectorAll('[data-min]').forEach(function(x){x.onclick=function(){timerLeft=Number(this.getAttribute('data-min'))*60;updateTimer()}});el('timerStart').onclick=function(){if(timerInt)clearInterval(timerInt);timerInt=setInterval(function(){timerLeft--;updateTimer();if(timerLeft<=0){clearInterval(timerInt);timerInt=null;toast('انتهى الوقت')}},1000)};return}if(tab==='signal'){b.innerHTML='<div class="signal-tool"><div id="signalFace" class="signal-face wait">انتظر</div><div class="signal-buttons"><button data-signal="go">ابدأ</button><button data-signal="wait">انتظر</button><button data-signal="stop">توقف</button></div></div>';document.querySelectorAll('[data-signal]').forEach(function(x){x.onclick=function(){var v=this.getAttribute('data-signal'),f=el('signalFace');f.className='signal-face '+v;f.textContent=v==='go'?'ابدأ':v==='stop'?'توقف':'انتظر'}});return}b.innerHTML='<div class="whiteboard-tool"><canvas id="board" width="900" height="520"></canvas><div class="action-row"><button id="clearBoard" class="btn ghost">مسح الصبورة</button></div></div>';setupBoard()}
function updateTimer(){var m=Math.floor(timerLeft/60),s=timerLeft%60;if(el('timerDisplay'))el('timerDisplay').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function setupBoard(){var c=el('board'),ctx=c.getContext('2d'),down=false,last=null;ctx.lineWidth=10;ctx.lineCap='round';ctx.strokeStyle='#17343a';function pos(e){var r=c.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*c.width/r.width,y:(p.clientY-r.top)*c.height/r.height}}function start(e){down=true;last=pos(e);if(e.cancelable)e.preventDefault()}function move(e){if(!down)return;var p=pos(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p;if(e.cancelable)e.preventDefault()}function end(){down=false;last=null}c.addEventListener('mousedown',start);c.addEventListener('mousemove',move);window.addEventListener('mouseup',end);c.addEventListener('touchstart',start,{passive:false});c.addEventListener('touchmove',move,{passive:false});c.addEventListener('touchend',end);el('clearBoard').onclick=function(){ctx.clearRect(0,0,c.width,c.height)}}
function openSheet(title,body){var sh=el('sheet');el('sheetTitle').textContent=title;el('sheetBody').innerHTML=body;sh.hidden=false;sh.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';sh.querySelectorAll('[data-close-sheet]').forEach(function(b){b.onclick=closeSheet})}
function closeSheet(){if(timerInt){clearInterval(timerInt);timerInt=null}if(drawingSession&&drawingSession.destroy){drawingSession.destroy();drawingSession=null}var sh=el('sheet');sh.classList.remove('drawing-open');sh.hidden=true;sh.setAttribute('aria-hidden','true');document.body.style.overflow=''}
function bindHeader(){var b=el('libraryBtn');if(b)b.onclick=renderLibrary;b=el('historyBtn');if(b)b.onclick=openHistory;b=el('helpersBtn');if(b)b.onclick=function(){openHelpers(null)};b=el('drawingBtn');if(b)b.onclick=openDrawingLab;b=el('settingsBtn');if(b)b.onclick=openSettings;document.addEventListener('keydown',function(e){var sh=el('sheet');if(e.key==='Escape'&&sh&&!sh.hidden)closeSheet()})}
function boot(){renderLoading();Promise.all([fetch('experiences.json?v=1',{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('experiences '+r.status);return r.json()}),fetch('storyboards/manifest.json?v=2',{cache:'no-store'}).then(function(r){return r.ok?r.json():{assets:{}}}).catch(function(){return{assets:{}}}),fetch('community.json?v=1',{cache:'no-store'}).then(function(r){return r.ok?r.json():{enabled:false}}).catch(function(){return{enabled:false}})]).then(function(res){data=res[0];items=data.experiences||[];storyboards=res[1].assets||{};community=res[2]||{enabled:false};families=engine.familyMap(data);levels=engine.levelMap(data);byId={};items.forEach(function(x){byId[x.id]=x});if(items.length!==200)throw new Error('المكتبة غير مكتملة: '+items.length);loadPrefs();storageStatus();renderLibrary()}).catch(function(e){renderError(e.message||'خطأ غير معروف')})}
bindHeader();boot();
}());