(function(){
'use strict';
var core=window.ImitatePracticeCore,tasks=window.ImitateTasks||[],root=document.getElementById('practiceRoot');
var taskById={};for(var i=0;i<tasks.length;i++)taskById[tasks[i].id]=tasks[i];
var store=core.storageAdapter(window.localStorage),state={view:'choose',task:null,session:null,phase:0,reflection:''};
function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function saveCurrent(){if(state.session)store.saveCurrent({state:{view:state.view,taskId:state.task&&state.task.id,phase:state.phase,reflection:state.reflection},session:state.session})}
function clearCurrent(){store.clearCurrent()}
function storageStatus(){var b=document.getElementById('storageBanner');if(store.isPersistent()){b.hidden=true;return}b.hidden=false;b.innerHTML='<strong>الحفظ الدائم غير متاح في هذا المتصفح.</strong> ستعمل الممارسة الآن، لكن قد تضيع البيانات بعد إغلاق الصفحة. استخدم «السجل ← تصدير» قبل الإغلاق إذا أردت الاحتفاظ بها.'}
function stage(n,title,lead){return '<div class="stage-title"><span class="stage-dot">'+n+'</span><h2>'+title+'</h2></div><p class="lead">'+lead+'</p>'}
function progress(n){var x='<div class="progress" aria-label="تقدم الممارسة">';for(var i=1;i<=4;i++)x+='<i class="'+(i<=n?'on':'')+'"></i>';return x+'</div>'}
function renderChoose(){state.view='choose';state.phase=0;var resumed=store.loadCurrent();var html=stage('1','اختر حركة واحدة','جهّز اللعبة الحقيقية أولًا. الطفل لا يحتاج إلى قراءة أو لمس الشاشة؛ المرافق هو من يستخدم التطبيق.');
if(resumed&&resumed.session&&resumed.session.status==='in_progress'){var rt=taskById[resumed.session.task_id];if(rt)html+='<div class="resume-card"><b>لديك محاولة غير مكتملة: '+esc(rt.short)+'</b><button class="btn secondary" type="button" data-resume>متابعة المحاولة</button> <button class="btn ghost" type="button" data-discard>بدء جديد</button></div>'}
html+='<div class="helper"><strong>قبل البدء</strong>استخدم أدوات كبيرة وآمنة. قل التعليمة مرة واحدة، اعرض الحركة مرة واحدة، ثم انتظر. لا تحول النشاط إلى سلسلة أوامر.</div><div class="task-grid">';
for(var i=0;i<tasks.length;i++){var t=tasks[i];html+='<button class="task-card" type="button" data-task="'+t.id+'">'+t.scene+'<b>'+esc(t.short)+'</b><span class="object-hint">'+esc(t.objectHint)+'</span></button>'}
html+='</div><p class="micro">ثماني بطاقات أصلية داخل التطبيق. يمكن تجاوز أي بطاقة فورًا واختيار غيرها.</p>';root.innerHTML=html;bindChoose()}
function bindChoose(){var cards=root.querySelectorAll('[data-task]');for(var i=0;i<cards.length;i++)cards[i].onclick=function(){startTask(this.getAttribute('data-task'))};var r=root.querySelector('[data-resume]');if(r)r.onclick=resumeCurrent;var d=root.querySelector('[data-discard]');if(d)d.onclick=function(){clearCurrent();renderChoose()}}
function startTask(id){var t=taskById[id];if(!t)return;state.task=t;state.session=core.createSession(id);state.reflection='';state.phase=1;renderModel()}
function resumeCurrent(){var c=store.loadCurrent();if(!c||!c.session)return renderChoose();var t=taskById[c.session.task_id];if(!t){clearCurrent();return renderChoose()}state.task=t;state.session=c.session;state.phase=(c.state&&c.state.phase)||1;state.reflection=(c.state&&c.state.reflection)||'';if(state.phase<=1)renderModel();else renderPlay()}
function renderModel(){state.view='model';state.phase=1;saveCurrent();root.innerHTML=progress(1)+stage('2','اعرض نموذجًا واحدًا','نفّذ الحركة أمام الطفل بهدوء. اجعل الجسم والحركة أوضح من الكلام.')+'<div class="model-card">'+state.task.scene+'<div><div class="instruction">'+esc(state.task.title)+'</div><p class="say-once">قل العبارة مرة واحدة فقط ثم انتظر.</p></div></div><div class="helper"><strong>مهمة المرافق</strong>صف ما تفعله بجملة قصيرة، اتبع انتباه الطفل، ثم اترك له وقتًا للمحاولة. إذا بادر بحركة مختلفة، لاحظها بدل مقاطعته.</div><div class="action-row"><button class="btn primary wide" id="hideBtn" type="button">عرضت النموذج — أخفِ الشاشة وابدأ</button><button class="btn ghost" id="skipBtn" type="button">تجاوز هذه المهمة</button></div>';document.getElementById('hideBtn').onclick=function(){state.phase=2;renderPlay()};document.getElementById('skipBtn').onclick=skipTask}
function hiddenShell(badge,title,text,inside){return progress(state.phase)+ '<div class="hidden-mode"><div class="turn-badge">'+badge+'</div><h2>'+title+'</h2><p>'+text+'</p>'+inside+'<div class="quiet-cue"><span class="wait-ring"></span><span><strong>قاعدة الدور:</strong> قلها مرة، ثم انتظر. الصمت جزء من الممارسة.</span></div><div class="hidden-actions"><button class="btn secondary" type="button" data-remodel>أعد النموذج</button><button class="btn ghost" type="button" data-skip>تجاوز المهمة</button></div></div>'}
function renderPlay(){state.view='play';saveCurrent();if(state.phase===2){root.innerHTML=hiddenShell('دوري','المرافق يبدأ','ضع الهاتف جانبًا ونفّذ الحركة مرة واحدة أمام الطفل.','<button class="btn primary wide" type="button" data-next>تم دوري — الآن دور الطفل</button>');bindPlay(function(){state.phase=3;renderPlay()});return}
if(state.phase===3){var buttons='<div class="assist-wrap"><p>دع الطفل يحاول، ثم اختر مقدار المساعدة التي احتاجها:</p><div class="assist-grid"><button class="assist-btn" data-help="independent">محاولة ذاتية<small>انتظر فحاول وحده</small></button><button class="assist-btn" data-help="gesture">إشارة فقط<small>نظرة أو إشارة بسيطة</small></button><button class="assist-btn" data-help="model">احتاج نموذجًا<small>أعدت الحركة أمامه</small></button><button class="assist-btn" data-help="direct">مساعدة مباشرة<small>مساعدة عملية قصيرة وآمنة</small></button></div></div>';
root.innerHTML=hiddenShell('دورك','الطفل يقلّد','لا تكرر الأمر. انتظر المحاولة، وسجّل أقل قدر من المساعدة احتاجه.',buttons);bindPlay();var hs=root.querySelectorAll('[data-help]');for(var j=0;j<hs.length;j++)hs[j].onclick=function(){state.session=core.recordAttempt(state.session,this.getAttribute('data-help'));state.phase=4;renderPlay()};return}
if(state.phase===4){root.innerHTML=hiddenShell('بدّل الدور','الطفل يبدأ الآن','اتبع مبادرة الطفل: دعه يحرك اللعبة أولًا، ثم قلّد أنت حركته. هكذا يصبح صاحب الدور لا مجرد منفذ.','<button class="btn primary wide" type="button" data-next>تم تبادل الدورين</button>');bindPlay(function(){renderComplete()});}}
function bindPlay(next){var r=root.querySelector('[data-remodel]');if(r)r.onclick=function(){state.session=core.replayModel(state.session);renderModel()};var s=root.querySelector('[data-skip]');if(s)s.onclick=skipTask;var n=root.querySelector('[data-next]');if(n&&next)n.onclick=next}
function skipTask(){if(state.session){state.session=core.skip(state.session);store.append(state.session)}clearCurrent();state.session=null;state.task=null;renderChoose()}
function renderComplete(){state.view='complete';state.session=core.complete(state.session,{roleExchangeCompleted:true,childLedTurnCompleted:true,reflection:state.reflection});saveCurrent();var sum=core.summary(state.session);root.innerHTML=progress(4)+'<div class="success"><div class="success-mark">✓</div><h2>اكتملت محاولة تبادل الدور</h2><p class="lead">النتيجة هنا ملاحظة للممارسة فقط، وليست درجة أو تشخيصًا.</p><div class="summary-card"><div class="summary-list"><div class="summary-item"><span>الحركة</span><b>'+esc(state.task.short)+'</b></div><div class="summary-item"><span>المساعدة</span><b>'+esc(sum.assistance_label)+'</b></div><div class="summary-item"><span>إعادة النموذج</span><b>'+sum.replay_count+'</b></div><div class="summary-item"><span>تبادل الدورين</span><b>تم</b></div></div></div><label for="reflection"><strong>ملاحظة اختيارية للمرافق</strong></label><textarea id="reflection" class="reflection" maxlength="300" placeholder="مثال: بادر بدحرجة الكرة وحده بعد الانتظار.">'+esc(state.reflection)+'</textarea><div class="action-row"><button class="btn primary" id="saveDone" type="button">حفظ وإنهاء</button><button class="btn secondary" id="againBtn" type="button">محاولة أخرى لنفس الحركة</button><button class="btn ghost" id="exportNow" type="button">تصدير نسخة</button></div></div>';document.getElementById('saveDone').onclick=finishSession;document.getElementById('againBtn').onclick=function(){var text=document.getElementById('reflection').value;state.reflection=text;state.session=core.complete(state.session,{roleExchangeCompleted:true,childLedTurnCompleted:true,reflection:text});store.append(state.session);clearCurrent();startTask(state.task.id)};document.getElementById('exportNow').onclick=function(){state.reflection=document.getElementById('reflection').value;downloadExport()};document.getElementById('reflection').oninput=function(){state.reflection=this.value}}
function finishSession(){state.reflection=document.getElementById('reflection').value;state.session=core.complete(state.session,{roleExchangeCompleted:true,childLedTurnCompleted:true,reflection:state.reflection});store.append(state.session);clearCurrent();state.session=null;state.task=null;renderChoose();toast('حُفظت المحاولة محليًا على هذا الجهاز.')}
function toast(msg){var n=document.getElementById('appPwaNotice');n.textContent=msg;n.style.display='block';clearTimeout(toast.t);toast.t=setTimeout(function(){n.style.display='none'},3200)}
function openSheet(){var sh=document.getElementById('sheet'),body=document.getElementById('sheetBody'),rows=store.list();var html='';if(!rows.length)html='<div class="history-empty">لا توجد محاولات محفوظة بعد.</div>';else{for(var i=0;i<rows.length;i++){var s=rows[i],t=taskById[s.task_id],sum=core.summary(s);html+='<div class="history-row"><b>'+esc(t?t.short:s.task_id)+'</b><small>'+esc(sum.status==='completed'?'مكتملة':'متجاوزة')+' · '+esc(sum.assistance_label)+' · إعادة النموذج: '+sum.replay_count+'</small></div>'}}html+='<div class="sheet-actions"><button class="btn secondary" id="exportAll" type="button">تصدير JSON</button><button class="btn danger" id="clearAll" type="button">حذف السجل</button></div><p class="micro">السجل يبقى على هذا الجهاز فقط ولا يرسل إلى أي خدمة.</p>';body.innerHTML=html;sh.hidden=false;sh.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';document.getElementById('exportAll').onclick=downloadExport;document.getElementById('clearAll').onclick=function(){if(window.confirm('حذف كل المحاولات المحفوظة على هذا الجهاز؟')){store.clear();closeSheet();renderChoose();toast('تم حذف السجل المحلي.')}};var cls=sh.querySelectorAll('[data-close-sheet]');for(var j=0;j<cls.length;j++)cls[j].onclick=closeSheet}
function closeSheet(){var sh=document.getElementById('sheet');sh.hidden=true;sh.setAttribute('aria-hidden','true');document.body.style.overflow=''}
function downloadExport(){var payload=store.exportPayload(state.session);var blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});var url=URL.createObjectURL(blob);var a=document.createElement('a');a.href=url;a.download='a1-imitate-export-'+new Date().toISOString().slice(0,10)+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url)},500);toast('تم تجهيز ملف التصدير.')}
document.getElementById('historyBtn').onclick=openSheet;document.addEventListener('keydown',function(e){if(e.key==='Escape'&&!document.getElementById('sheet').hidden)closeSheet()});
storageStatus();renderChoose();
}());
