(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.A1DrawingLab=api;}(typeof self!=='undefined'?self:this,function(){'use strict';
var templates=[
{id:'free',label:'حر'},{id:'line_h',label:'خط أفقي'},{id:'wave',label:'موجة'},{id:'circle',label:'دائرة'},{id:'square',label:'مربع'},{id:'triangle',label:'مثلث'},{id:'star',label:'نجمة'},{id:'house',label:'بيت'},{id:'sun',label:'شمس'},{id:'face',label:'وجه'},{id:'road',label:'طريق'},{id:'target',label:'هدف'}
];
var colors=['#111111','#e53935','#1e88e5','#43a047','#fb8c00','#8e24aa'];
function config(){return{repair:true,palm:true,power:3,width:7,color:'#111111',guide:.22}}
function distance(a,b){var dx=a.x-b.x,dy=a.y-b.y;return Math.sqrt(dx*dx+dy*dy)}
function limits(c){var p=parseInt(c.power,10)||3;return{maxGap:75+p*52,maxDist:18+p*17,jump:150+p*10}}
function shouldRepair(lastEnd,p,dt,c){var l=limits(c);return!!(c.repair&&lastEnd&&dt<=l.maxGap&&distance(lastEnd,p)<=l.maxDist)}
function shouldRejectJump(last,p,c){return!!(last&&distance(last,p)>limits(c).jump)}
function suggest(exp){var out=[];if(!exp)return['free','circle','line_h'];var t=(exp.title||'')+' '+(exp.family||'');if(/رسم|لوحة|فن|صلصال/.test(t))out=['free','circle','star','house','sun','face'];else if(/مسار|طريق|حركة|توازن|مشي|قفز/.test(t))out=['road','line_h','wave','target'];else if(/تركيز|هدف|إشارة/.test(t))out=['target','circle','line_h'];else if(/بيت|غرفة|منزل|روتين/.test(t))out=['house','square','line_h'];else out=['free','circle','line_h','star'];return out}
function path(ctx,id,w,h,alpha){
ctx.save();ctx.strokeStyle='rgba(15,143,138,'+alpha+')';ctx.lineWidth=Math.max(5,Math.min(w,h)*.018);ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();var cx=w/2,cy=h/2,r=Math.min(w,h)*.27,i,a;
if(id==='free'){ctx.restore();return}
if(id==='line_h'){ctx.moveTo(w*.18,cy);ctx.lineTo(w*.82,cy)}
else if(id==='wave'){ctx.moveTo(w*.12,cy);for(i=1;i<=70;i++){a=i/70;ctx.lineTo(w*.12+a*w*.76,cy+Math.sin(a*Math.PI*4)*r*.32)}}
else if(id==='circle'||id==='target'){ctx.arc(cx,cy,r,0,Math.PI*2);if(id==='target'){ctx.moveTo(cx+r*.55,cy);ctx.arc(cx,cy,r*.55,0,Math.PI*2);ctx.moveTo(cx+r*.12,cy);ctx.arc(cx,cy,r*.12,0,Math.PI*2)}}
else if(id==='square'){ctx.rect(cx-r,cy-r,r*2,r*2)}
else if(id==='triangle'){ctx.moveTo(cx,cy-r);ctx.lineTo(cx+r,cy+r);ctx.lineTo(cx-r,cy+r);ctx.closePath()}
else if(id==='star'){for(i=0;i<10;i++){a=-Math.PI/2+i*Math.PI/5;var rr=i%2===0?r:r*.43,x=cx+rr*Math.cos(a),y=cy+rr*Math.sin(a);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.closePath()}
else if(id==='house'){ctx.moveTo(cx-r,cy-r*.05);ctx.lineTo(cx,cy-r);ctx.lineTo(cx+r,cy-r*.05);ctx.moveTo(cx-r*.78,cy-r*.05);ctx.lineTo(cx-r*.78,cy+r);ctx.lineTo(cx+r*.78,cy+r);ctx.lineTo(cx+r*.78,cy-r*.05)}
else if(id==='sun'){ctx.arc(cx,cy,r*.55,0,Math.PI*2);for(i=0;i<8;i++){a=Math.PI*2*i/8;ctx.moveTo(cx+r*.72*Math.cos(a),cy+r*.72*Math.sin(a));ctx.lineTo(cx+r*1.03*Math.cos(a),cy+r*1.03*Math.sin(a))}}
else if(id==='face'){ctx.arc(cx,cy,r,0,Math.PI*2);ctx.moveTo(cx-r*.35,cy-r*.23);ctx.arc(cx-r*.35,cy-r*.23,5,0,Math.PI*2);ctx.moveTo(cx+r*.35,cy-r*.23);ctx.arc(cx+r*.35,cy-r*.23,5,0,Math.PI*2);ctx.moveTo(cx-r*.45,cy+r*.12);ctx.quadraticCurveTo(cx,cy+r*.62,cx+r*.45,cy+r*.12)}
else if(id==='road'){ctx.moveTo(w*.15,h*.72);ctx.bezierCurveTo(w*.3,h*.55,w*.36,h*.25,w*.52,h*.32);ctx.bezierCurveTo(w*.68,h*.39,w*.72,h*.65,w*.86,h*.5);ctx.moveTo(w*.15,h*.84);ctx.bezierCurveTo(w*.32,h*.67,w*.39,h*.38,w*.52,h*.44);ctx.bezierCurveTo(w*.66,h*.5,w*.72,h*.78,w*.88,h*.62)}
ctx.stroke();ctx.restore()
}
function Board(host,index,state){
this.host=host;this.index=index;this.state=state;this.strokes=[];this.current=null;this.drawing=false;this.last=null;this.prev=null;this.lastEnd=null;this.lastEndTime=0;this.activeTouchId=null;this.ignoreMouseUntil=0;
var card=document.createElement('section');card.className='draw-board-card';card.innerHTML='<div class="draw-board-head"><b>لوحة '+index+'</b><select class="draw-template"></select><button class="draw-clear" type="button">مسح</button><button class="draw-undo" type="button">تراجع</button></div><div class="draw-canvas-shell"><canvas class="draw-guide"></canvas><canvas class="draw-ink"></canvas></div>';host.appendChild(card);this.card=card;this.guide=card.querySelector('.draw-guide');this.canvas=card.querySelector('.draw-ink');this.g=this.guide.getContext('2d');this.ctx=this.canvas.getContext('2d');this.select=card.querySelector('.draw-template');
var suggested=state.suggested||[],ordered=[],seen={},i,t;for(i=0;i<suggested.length;i++){for(var j=0;j<templates.length;j++)if(templates[j].id===suggested[i]&&!seen[templates[j].id]){ordered.push(templates[j]);seen[templates[j].id]=1}}for(i=0;i<templates.length;i++)if(!seen[templates[i].id])ordered.push(templates[i]);
for(i=0;i<ordered.length;i++){t=document.createElement('option');t.value=ordered[i].id;t.text=ordered[i].label;this.select.appendChild(t)}this.select.value=ordered[0]?ordered[0].id:'free';
var self=this;this.select.onchange=function(){self.drawGuide()};card.querySelector('.draw-clear').onclick=function(){self.clear()};card.querySelector('.draw-undo').onclick=function(){self.strokes.pop();self.redraw()};
this.bind();this.resize()
}
function setScale(ctx,dpr){if(ctx.setTransform){ctx.setTransform(dpr,0,0,dpr,0,0);return}if(ctx.scale)ctx.scale(dpr,dpr)}
Board.prototype.resize=function(){var box=this.canvas.parentNode,r=box.getBoundingClientRect?box.getBoundingClientRect():{width:0,height:0},dpr=window.devicePixelRatio||1;if(dpr>2)dpr=2;var rw=r&&r.width?r.width:(box.offsetWidth||this.host.offsetWidth||600),rh=r&&r.height?r.height:(box.offsetHeight||360),w=Math.max(260,Math.round(rw||600)),h=Math.max(280,Math.round(rh||360));this.canvas.width=Math.round(w*dpr);this.canvas.height=Math.round(h*dpr);this.guide.width=this.canvas.width;this.guide.height=this.canvas.height;setScale(this.ctx,dpr);setScale(this.g,dpr);this.redraw();this.drawGuide()};
Board.prototype.drawGuide=function(){var r=this.canvas.parentNode.getBoundingClientRect();this.g.clearRect(0,0,r.width,r.height);path(this.g,this.select.value,r.width,r.height,this.state.cfg.guide)};
Board.prototype.setPen=function(){this.ctx.lineCap='round';this.ctx.lineJoin='round';this.ctx.strokeStyle=this.state.cfg.color;this.ctx.lineWidth=parseInt(this.state.cfg.width,10)||7};
Board.prototype.pos=function(p){var r=this.canvas.getBoundingClientRect();return{x:p.clientX-r.left,y:p.clientY-r.top,t:(new Date()).getTime()}};
Board.prototype.segment=function(a,b){this.setPen();this.ctx.beginPath();this.ctx.moveTo(a.x,a.y);this.ctx.lineTo(b.x,b.y);this.ctx.stroke()};
Board.prototype.begin=function(p){if(shouldRepair(this.lastEnd,p,p.t-this.lastEndTime,this.state.cfg)){this.segment(this.lastEnd,p);if(this.strokes.length)this.current=this.strokes[this.strokes.length-1];else{this.current=[];this.strokes.push(this.current)}}else{this.current=[];this.strokes.push(this.current)}this.current.push({x:p.x,y:p.y,c:this.state.cfg.color,w:this.state.cfg.width});this.drawing=true;this.last=p;this.prev=p};
Board.prototype.move=function(p){if(!this.drawing||shouldRejectJump(this.last,p,this.state.cfg))return;if(!this.last){this.last=p;this.prev=p;return}this.setPen();var mx=(this.last.x+p.x)/2,my=(this.last.y+p.y)/2;this.ctx.beginPath();this.ctx.moveTo(this.prev.x,this.prev.y);this.ctx.quadraticCurveTo(this.last.x,this.last.y,mx,my);this.ctx.stroke();this.prev={x:mx,y:my,t:p.t};this.last=p;if(this.current)this.current.push({x:p.x,y:p.y,c:this.state.cfg.color,w:this.state.cfg.width})};
Board.prototype.end=function(p){if(!this.drawing)return;if(p&&this.last&&!shouldRejectJump(this.last,p,this.state.cfg)&&distance(this.last,p)>1)this.move(p);if(this.last)this.segment(this.prev||this.last,this.last);this.drawing=false;this.lastEnd=this.last;this.lastEndTime=(new Date()).getTime();this.last=null;this.prev=null;this.activeTouchId=null};
Board.prototype.redraw=function(){var r=this.canvas.parentNode.getBoundingClientRect();this.ctx.clearRect(0,0,r.width,r.height);for(var s=0;s<this.strokes.length;s++){var st=this.strokes[s];if(!st||!st.length)continue;this.ctx.lineCap='round';this.ctx.lineJoin='round';this.ctx.lineWidth=parseInt(st[0].w,10)||7;this.ctx.strokeStyle=st[0].c||'#111';this.ctx.beginPath();this.ctx.moveTo(st[0].x,st[0].y);for(var i=1;i<st.length;i++)this.ctx.lineTo(st[i].x,st[i].y);this.ctx.stroke()}};
Board.prototype.clear=function(){this.strokes=[];this.current=null;this.drawing=false;this.last=null;this.prev=null;this.lastEnd=null;this.redraw()};
Board.prototype.findTouch=function(list,id){if(!list)return null;for(var i=0;i<list.length;i++)if(list[i].identifier===id)return list[i];return null};
Board.prototype.bind=function(){var self=this,c=this.canvas;c.addEventListener('touchstart',function(e){self.ignoreMouseUntil=(new Date()).getTime()+800;if(self.drawing&&self.state.cfg.palm){e.preventDefault();return}if(e.touches&&e.touches.length){self.activeTouchId=e.touches[0].identifier;self.begin(self.pos(e.touches[0]));e.preventDefault()}},false);c.addEventListener('touchmove',function(e){if(!self.drawing)return;var t=self.state.cfg.palm?self.findTouch(e.touches,self.activeTouchId):(e.touches&&e.touches[0]);if(t)self.move(self.pos(t));e.preventDefault()},false);c.addEventListener('touchend',function(e){var t=self.state.cfg.palm?self.findTouch(e.changedTouches,self.activeTouchId):(e.changedTouches&&e.changedTouches[0]);if(t)self.end(self.pos(t));else if(!e.touches||!e.touches.length)self.end(null);e.preventDefault()},false);c.addEventListener('touchcancel',function(e){self.end(null);e.preventDefault()},false);c.addEventListener('mousedown',function(e){if((new Date()).getTime()<self.ignoreMouseUntil)return;self.begin(self.pos(e));e.preventDefault()},false);window.addEventListener('mousemove',function(e){if(self.drawing&&self.activeTouchId===null&&((new Date()).getTime()>=self.ignoreMouseUntil))self.move(self.pos(e))},false);window.addEventListener('mouseup',function(e){if(self.drawing&&self.activeTouchId===null)self.end(self.pos(e))},false)};
function mount(host,opts){opts=opts||{};var state={cfg:config(),boards:[],suggested:suggest(opts.experience),max:6,legacy:!!opts.legacy};host.innerHTML='<div class="draw-lab-toolbar"><div class="draw-lab-main"><button id="drawAddPerson" type="button">+ مشارك</button><button id="drawSameTemplate" type="button">نفس النموذج للجميع</button><label><input id="drawRepair" type="checkbox" checked> إصلاح تقطيع القلم</label><label><input id="drawPalm" type="checkbox" checked> حماية اليد</label></div><div class="draw-lab-settings"><label>قوة الإصلاح <input id="drawPower" type="range" min="1" max="5" value="3"></label><label>سماكة <input id="drawWidth" type="range" min="2" max="18" value="7"></label><label>وضوح النموذج <input id="drawGuideOpacity" type="range" min="5" max="55" value="22"></label><span id="drawColors" class="draw-colors"></span></div><div class="draw-lab-hint">ابدأ بلوحتين. أضف لوحة لكل طفل إضافي. اللمسات الإضافية أثناء الرسم تُعامل كراحة يد، وإصلاح التقطيع يصل الانقطاعات القصيرة الناتجة عن القلم القديم.</div></div><div id="drawBoards" class="draw-boards"></div>';
var boardsHost=host.querySelector('#drawBoards'),destroyed=false;
function add(){if(state.boards.length>=state.max)return;var b=new Board(boardsHost,state.boards.length+1,state);state.boards.push(b);setTimeout(function(){b.resize()},20)}
add();add();
host.querySelector('#drawAddPerson').onclick=add;host.querySelector('#drawSameTemplate').onclick=function(){if(!state.boards.length)return;var v=state.boards[0].select.value;for(var i=1;i<state.boards.length;i++){state.boards[i].select.value=v;state.boards[i].drawGuide()}};
host.querySelector('#drawRepair').onchange=function(){state.cfg.repair=this.checked};host.querySelector('#drawPalm').onchange=function(){state.cfg.palm=this.checked};host.querySelector('#drawPower').oninput=function(){state.cfg.power=parseInt(this.value,10)||3};host.querySelector('#drawWidth').oninput=function(){state.cfg.width=parseInt(this.value,10)||7};host.querySelector('#drawGuideOpacity').oninput=function(){state.cfg.guide=(parseInt(this.value,10)||22)/100;for(var i=0;i<state.boards.length;i++)state.boards[i].drawGuide()};
var colorsHost=host.querySelector('#drawColors');for(var i=0;i<colors.length;i++){var b=document.createElement('button');b.type='button';b.className='draw-color'+(i===0?' on':'');b.style.background=colors[i];b.setAttribute('data-color',colors[i]);b.onclick=function(){state.cfg.color=this.getAttribute('data-color');var all=colorsHost.getElementsByTagName('button');for(var j=0;j<all.length;j++)all[j].className='draw-color';this.className='draw-color on'};colorsHost.appendChild(b)}
function resize(){if(destroyed)return;for(var i=0;i<state.boards.length;i++)state.boards[i].resize()}window.addEventListener('resize',resize,false);
return{destroy:function(){destroyed=true;window.removeEventListener('resize',resize,false)},resize:resize,state:state}
}
return{templates:templates,config:config,limits:limits,shouldRepair:shouldRepair,shouldRejectJump:shouldRejectJump,suggest:suggest,mount:mount};
}));