'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const core=require('./practice-core.js');
function fakeStorage(){const data={};return {setItem(k,v){data[k]=String(v)},getItem(k){return Object.prototype.hasOwnProperty.call(data,k)?data[k]:null},removeItem(k){delete data[k]}}}
test('creates a minimal in-progress session',()=>{const s=core.createSession('cube-basket');assert.equal(s.task_id,'cube-basket');assert.equal(s.status,'in_progress');assert.equal(s.attempts.length,0);assert.equal(s.artifact.replay_count,0)});
test('records assistance and preserves prior session immutably',()=>{const s=core.createSession('cube-basket');const next=core.recordAttempt(s,'model');assert.equal(s.attempts.length,0);assert.equal(next.attempts.length,1);assert.equal(next.assistance_level,'model');assert.match(core.summary(next).assistance_label,/نموذج/)});
test('tracks model replay and role exchange completion',()=>{let s=core.createSession('ball-roll');s=core.replayModel(s);s=core.recordAttempt(s,'independent');s=core.complete(s,{roleExchangeCompleted:true,childLedTurnCompleted:true,reflection:'انتظر المرافق'});const x=core.summary(s);assert.equal(x.replay_count,1);assert.equal(x.role_exchange_completed,true);assert.equal(x.child_led_turn_completed,true);assert.equal(x.status,'completed')});
test('persistent adapter saves, reloads, exports and clears',()=>{const st=core.storageAdapter(fakeStorage());const s=core.complete(core.recordAttempt(core.createSession('car-push'),'gesture'),{roleExchangeCompleted:true,childLedTurnCompleted:true});st.append(s);st.saveCurrent(s);assert.equal(st.isPersistent(),true);assert.equal(st.list().length,1);assert.equal(st.loadCurrent().task_id,'car-push');assert.equal(st.exportPayload(null).sessions.length,1);st.clear();assert.equal(st.list().length,0);assert.equal(st.loadCurrent(),null)});
test('storage refusal falls back without blocking practice',()=>{const broken={setItem(){throw new Error('denied')},getItem(){throw new Error('denied')},removeItem(){throw new Error('denied')}};const st=core.storageAdapter(broken);const s=core.skip(core.createSession('stack'));st.append(s);assert.equal(st.isPersistent(),false);assert.equal(st.list().length,1);assert.equal(st.list()[0].status,'skipped')});
