const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const M=require('../src/model.js');const sandbox={window:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../src/content.js'),'utf8'),sandbox);const content=JSON.parse(JSON.stringify(sandbox.window.MAKER_CONTENT));
function begin(id='book',mode='screen',track='entry',profile='child:A'){const p=content.projects.find(p=>p.id===id),d=M.create(id,profile,track,mode);d.user_need=p.need.ar;d.other_user_note='طلب المستخدم وضوح الصفحة.';d.materials=[p.materials[0]];M.start(d,p);return d;}
function first(d){M.freeze(d);M.test(d,1,'لاحظت موضع النموذج.',true);}
for(const id of M.ids)test(id+' keeps first prototype and fixed test across two models',()=>{const d=begin(id,'screen','extend');first(d);const baseline=JSON.stringify(d.prototype_versions[0]);const field=M.keys[id][0];d.design[field]=2;d.change_reason='أجرب تغيير هذا الجزء.';M.freeze(d);M.test(d,1,'لاحظت أثر التغيير.',true);d.reflection='سأجرب مع شخص آخر.';const saved=M.finish(d);assert.equal(JSON.stringify(saved.prototype_versions[0]),baseline);assert.deepEqual(saved.test_notes[0].protocol,saved.test_notes[1].protocol);assert.equal(M.validate(saved,'child:A').state,'saved');});
test('zero or multiple part changes rejected and failed tests can be saved',()=>{const d=begin();first(d);d.change_reason='سبب';assert.throws(()=>M.freeze(d),/one-change/);d.design.base=0;d.design.back=0;assert.throws(()=>M.freeze(d),/one-change/);d.design.back=1;M.freeze(d);M.test(d,0,'مال النموذج.',true);assert.equal(d.test_notes[1].result.passed,false);d.reflection='أحاول قاعدة أوسع.';assert.equal(M.finish(d).state,'saved');});
test('physical build needs a real observation, note and explicit confirmation',()=>{const d=begin('bridge','real');M.freeze(d);assert.throws(()=>M.test(d,null,'',false),/real-observation/);assert.throws(()=>M.test(d,1,'',true),/observation/);M.test(d,3,'هبط منتصف الورقة.',true);assert.equal(d.test_notes[0].result.passed,null);assert.equal(d.test_notes[0].result.source,'physical-observation');});
test('profile isolation including children with duplicate names',()=>{const d=begin('book','screen','entry','user:parent:child:A');assert.throws(()=>M.validate(d,'user:parent:child:B'),/profile/);});
test('incomplete imports and forged model results rejected',()=>{const d=begin();first(d);d.test_notes[0].result.passed=false;assert.throws(()=>M.validate(d,'child:A'),/simulation/);const x=begin();x.step='review';assert.throws(()=>M.validate(x,'child:A'),/incomplete/);});
test('unsafe drawing commands rejected; exports omit private coach note',()=>{const d=begin();d.drawing=[{type:'stamp',kind:'<script>',x:0,y:0,size:.2,color:'#26777c'}];assert.throws(()=>M.validate(d,'child:A'),/stamp/);d.drawing=[];d.coach_note='خاص';assert.equal(M.exported({gallery:[],draft:d}).draft.coach_note,'');});
test('every project and stage has complete Arabic and English recording and genuine cues',()=>{const root=require('node:path').resolve(__dirname,'..'),manifest=JSON.parse(fs.readFileSync(root+'/data/audio-manifest.json')),cues=JSON.parse(fs.readFileSync(root+'/data/read-along.json'));assert.equal(manifest.items.length,204);for(const item of manifest.items){assert.ok(fs.statSync(root+'/'+item.path).size>500);const cue=cues.items[item.path];assert.equal(cue.text,item.text);assert.equal(cue.language,item.language);assert.ok(cue.duration>0);let last=-1;for(const [index,start,end]of cue.cues){assert.ok(index>last&&start>=0&&end>start&&end<=cue.duration);last=index;}assert.equal(cue.cues.length,item.text.split(/\s+/).filter(x=>/[\p{L}\p{N}]/u.test(x)).length);}});
