const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const P=require('../src/story-player.js');
const vm=require('node:vm');
function harness(count=4){let id=0,timers=new Map(),voices=[],seen=[],finished=0;const p=P.create({count,onScene:i=>seen.push(i),onFinish:()=>finished++,narrate:(i,done)=>voices.push(done),setTimeout:(fn,ms)=>{timers.set(++id,{fn,ms});return id;},clearTimeout:i=>timers.delete(i)});return {p,timers,voices,seen,finished:()=>finished,tick:()=>{const [i,t]=timers.entries().next().value;timers.delete(i);t.fn();}};}
test('automatic scenes wait for narration and finish without looping',()=>{const h=harness(2);h.p.play();assert.equal(h.timers.size,1);assert.equal(h.timers.values().next().value.ms,45000);h.voices[0](true);assert.equal(h.p.state().index,0);assert.equal(h.timers.values().next().value.ms,1400);h.tick();assert.equal(h.p.state().index,1);h.voices[1](true);h.tick();assert.equal(h.finished(),1);assert.equal(h.p.state().ended,true);assert.equal(h.timers.size,0);});
test('rapid manual changes and stale narration cannot advance the selected scene',()=>{const h=harness();h.p.play();const old=h.voices[0];h.p.select(3,true);old(true);assert.equal(h.p.state().index,3);assert.equal(h.timers.size,0);h.p.play();assert.equal(h.timers.size,1);h.p.pause();h.voices.at(-1)(true);assert.equal(h.timers.size,0);assert.equal(h.p.state().playing,false);});
test('stalled and rejected audio pause instead of skipping explanations',()=>{const h=harness();h.p.play();h.tick();assert.equal(h.p.state().index,0);assert.equal(h.p.state().playing,false);h.p.play();h.voices.at(-1)(false);assert.equal(h.timers.size,0);assert.equal(h.p.state().index,0);});
test('destroy cancels resources and silent replay starts at the first scene',()=>{let timers=new Map(),id=0,scenes=[];const p=P.create({count:2,onScene:i=>scenes.push(i),setTimeout:fn=>{timers.set(++id,fn);return id;},clearTimeout:i=>timers.delete(i)});p.select(1,false);p.play();let fn=timers.values().next().value;timers.clear();fn();assert.equal(p.state().ended,true);p.play();assert.equal(p.state().index,0);p.destroy();assert.equal(timers.size,0);p.play();assert.equal(timers.size,0);});
test('every level exposes ten experiments in both languages and a same-text Arabic voice comparison',()=>{const root=path.resolve(__dirname,'..'),context={window:{}};vm.createContext(context);for(const file of ['story-content.js','story-view.js'])vm.runInContext(fs.readFileSync(path.join(root,'src',file),'utf8'),context);const C=context.window.MAKER_STORIES,V=context.window.MAKER_STORY_VIEW;for(const lang of ['ar','en'])for(const level of [1,2,3]){const html=V.library({lang,level,progress:()=>({seen:[]})});assert.equal((html.match(/data-action="story-open"/g)||[]).length,10);assert.equal((html.match(/data-action="voice-compare"/g)||[]).length,lang==='ar'?2:0);for(const p of C.projects){const scene=V.workspace({lang,level,project:p,progress:{note:''}});assert.equal((scene.match(/data-action="story-step"/g)||[]).length,p.routes[level].length);assert.equal((scene.match(/data-action="story-voice"/g)||[]).length,lang==='ar'&&p.voice_group==='new'?2:0);}}assert.equal(C.voice_comparison.text,C.projects.find(p=>p.id==='tower').scenes[0].text.ar);assert.equal(C.projects.filter(p=>p.voice_group==='original').length,2);assert.equal(C.projects.filter(p=>p.voice_group==='new').length,8);});
test('each age route references real atlas cells and synchronized bilingual recordings',()=>{const root=path.resolve(__dirname,'..'),data=JSON.parse(fs.readFileSync(path.join(root,'data/story-content.json'))),cues=JSON.parse(fs.readFileSync(path.join(root,'data/read-along.json'))).items;assert.equal(data.levels.length,3);assert.equal(data.projects.length,10);assert.equal(new Set(data.projects.map(p=>p.id)).size,10);for(const p of data.projects){assert.equal(p.scenes.length,p.voice_group==='new'?6:12);for(const level of data.levels){const route=p.routes[level.id];assert.ok(route.length>=4);assert.equal(new Set(route).size,route.length);for(const n of route)assert.ok(p.scenes[n]);}for(const scene of p.scenes){assert.ok(scene.cell>=0&&scene.cell<6);assert.ok(fs.statSync(path.join(root,scene.atlas)).size<150000);for(const language of ['ar','en',...(scene.old_audio?['old']:[])]){const clip=language==='old'?scene.old_audio:scene.audio[language],record=cues[clip];assert.equal(record.text,scene.text[language==='old'?'ar':language]);assert.ok(record.cues.length>0);assert.ok(record.cues.every(c=>c[1]>=0&&c[2]<=record.duration));assert.ok(fs.statSync(path.join(root,clip)).size>1000);}}}});
