(function(w,d){'use strict';
var APP_ID='a1-plan-runner',STORE='app360:'+APP_ID+':schema-1',EVENT_KEY='app360:interop:v1:events',db=null,storageOk=true,registry=null,manifests={},presets=null,activeLevel='1-2',draft={plan_id:'',title:'',level_id:'1-2',steps:[]},routeCtx={},cache={},run=null,timer=null,eventTimer=null,paused=false,remaining=0,externalWin=null;
function $(id){return d.getElementById(id)}function text(v){return String(v==null?'':v)}function trim(v){return text(v).replace(/^\s+|\s+$/g,'')}function esc(v){return text(v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}function uid(p){return(p||'id')+'-'+(+new Date()).toString(36)+'-'+Math.floor(Math.random()*999999).toString(36)}function iso(){return new Date().toISOString()}function clone(x){try{return JSON.parse(JSON.stringify(x))}catch(e){return x}}function each(nodes,fn){var i;for(i=0;i<(nodes||[]).length;i++)fn(nodes[i],i)}
function toast(m){var n=$('toast');if(!n)return;n.innerHTML=esc(m);n.className='pr-toast show';clearTimeout(toast.t);toast.t=setTimeout(function(){n.className='pr-toast'},2600)}
function repoPrefix(){var p=w.location.pathname||'/',i=p.indexOf('/apps/');return i>=0?p.substring(0,i+1):p.substring(0,p.lastIndexOf('/')+1)}function origin(){return w.location.origin||(w.location.protocol+'//'+w.location.host)}function rootUrl(path){path=text(path).replace(/^\/+/, '');return origin()+repoPrefix()+path}function isExternal(u){return /^https?:\/\//i.test(text(u))}function safeInternal(u){u=text(u);return !!u&&!isExternal(u)&&u.indexOf('..')<0&&!/^\//.test(u)}function addParam(u,k,v){var h=u.indexOf('#'),hash='';if(h>=0){hash=u.substring(h);u=u.substring(0,h)}return u+(u.indexOf('?')>=0?'&':'?')+encodeURIComponent(k)+'='+encodeURIComponent(v)+hash}
function xhr(url,asJson,cb){var x;try{x=new XMLHttpRequest();x.open('GET',url,true);x.onreadystatechange=function(){if(x.readyState!==4)return;if((x.status>=200&&x.status<300)||x.status===0){if(asJson){try{cb(null,JSON.parse(x.responseText))}catch(e){cb(e)}}else cb(null,x.responseText)}else cb(new Error('HTTP '+x.status))};x.onerror=function(){cb(new Error('network'))};x.send(null)}catch(e){cb(e)}}function json(path,cb){xhr(rootUrl(path),true,cb)}function raw(path,cb){xhr(rootUrl(path),false,cb)}
function storage(){try{var k='__pr360__';w.localStorage.setItem(k,'1');w.localStorage.removeItem(k);return w.localStorage}catch(e){return null}}function defaults(){return{schema_version:'1.0',plans:[],templates:[],runs:[]}}function loadDb(){var s=storage(),x=null;storageOk=!!s;if(s){try{x=JSON.parse(s.getItem(STORE)||'null')}catch(e){}}db=x&&x.plans?x:defaults();var b=$('storageBanner');if(b){b.hidden=storageOk;if(!storageOk)b.innerHTML='<b>الحفظ المحلي غير متاح.</b> يمكن استخدام المخطط الآن، لكن صدّر البيانات قبل إغلاق الصفحة.'}}function saveDb(){var s=storage();if(!s){storageOk=false;return false}try{s.setItem(STORE,JSON.stringify(db));return true}catch(e){storageOk=false;return false}}
function typeAr(k){return k==='category'?'تصنيف':k==='item'?'بطاقة/نشاط':k==='service-item'?'خدمة + عنصر':k==='service'?'خدمة':'التطبيق'}function levelLabel(id){return id==='1-2'?'1–2 سنة':id==='2-3'?'2–3 سنوات':id==='3-4'?'3–4 سنوات':'مخصص'}
function switchTab(id){var views=d.getElementsByClassName('pr-view'),buttons=$('mainTabs').getElementsByTagName('button'),i;for(i=0;i<views.length;i++)views[i].hidden=views[i].id!=='tab-'+id;for(i=0;i<buttons.length;i++)buttons[i].className=buttons[i].getAttribute('data-tab')===id?'on':'';if(id==='saved')renderSaved();if(id==='history')renderHistory();if(id==='builder')renderDraft();try{w.scrollTo(0,0)}catch(e){}}
function loadCatalog(cb){json('data/app-links-registry.json',function(e,r){if(e){$('catalogStatus').innerHTML='تعذر تحميل سجل التطبيقات.';cb&&cb();return}registry=r;var apps=r.apps||[],left=apps.length;if(!left){finish();return}function finish(){addSafeReels();renderAppSelect();cb&&cb()}for(var i=0;i<apps.length;i++)(function(a){json(a.archive_path,function(err,m){if(!err&&m){m._registry=a;manifests[m.app_id]=m}left--;if(left===0)finish()})})(apps[i])})}
function addSafeReels(){manifests['safe-reels-360']={schema_version:'1.0',app_id:'safe-reels-360',title_ar:'الريلز الآمن 360',external:true,app_href:'https://yem1.com',routes:[{id:'home',kind:'app',label_ar:'فتح الريلز الآمن 360',href:'https://yem1.com'}]}}
function renderAppSelect(){var s=$('appSelect'),ids=[],k,h='';for(k in manifests)if(Object.prototype.hasOwnProperty.call(manifests,k))ids.push(k);ids.sort();for(var i=0;i<ids.length;i++){var m=manifests[ids[i]];h+='<option value="'+esc(m.app_id)+'">'+esc(m.title_ar)+'</option>'}s.innerHTML=h;s.onchange=renderRouteSelect;renderRouteSelect()}
function routesFor(m){var r=[{id:'__app__',kind:'app',label_ar:'فتح التطبيق كاملًا',href:m.app_href}],a=m.routes||[],i;for(i=0;i<a.length;i++)r.push(a[i]);return r}
function renderRouteSelect(){var app=$('appSelect').value,m=manifests[app],s=$('routeSelect'),routes=m?routesFor(m):[],h='',i;routeCtx={app_id:app,manifest:m,route:null,values:{}};for(i=0;i<routes.length;i++)h+='<option value="'+esc(routes[i].id)+'">'+esc(typeAr(routes[i].kind))+' · '+esc(routes[i].label_ar)+'</option>';s.innerHTML=h;s.onchange=renderRouteFields;renderRouteFields()}
function currentRoute(){var m=routeCtx.manifest,rs=m?routesFor(m):[],id=$('routeSelect').value,i;for(i=0;i<rs.length;i++)if(rs[i].id===id)return rs[i];return null}
function setFields(html){$('routeFields').innerHTML=html||'<div class="pr-status">لا يحتاج هذا الخيار إلى تفاصيل إضافية.</div>'}
function selectHtml(id,label,rows,valueKey,labelKey){var h='<label>'+esc(label)+'<select id="'+id+'">',i,x,v,l;for(i=0;i<rows.length;i++){x=rows[i];if(typeof x==='object'){v=x[valueKey||'id'];l=x[labelKey||'title']||x.label_ar||v}else{v=x;l=x}h+='<option value="'+esc(v)+'">'+esc(l)+'</option>'}return h+'</select></label>'}
function numberLevels(id,label){return'<label>'+label+'<select id="'+id+'"><option value="1">المستوى 1</option><option value="2">المستوى 2</option><option value="3">المستوى 3</option><option value="4">المستوى 4</option></select></label>'}
function loadWords(cb){if(cache.words){cb(cache.words);return}raw('apps/1-4/say-and-name/data/levels-inline-v8.js',function(e,t){if(e){cb(null);return}try{var mark='window.APP360_LEVELS=',p=t.indexOf(mark),end=t.lastIndexOf(';'),obj=JSON.parse(t.substring(p+mark.length,end>p?end:t.length));cache.words=obj;cb(obj)}catch(x){cb(null)}})}
function loadExperiences(cb){if(cache.experiences){cb(cache.experiences);return}json('apps/1-4/imitate-one-step/experiences.json',function(e,x){cache.experiences=!e?x:null;cb(cache.experiences)})}
function loadGames(cb){if(cache.games){cb(cache.games);return}var files=['apps/1-4/screen-to-move/games-data.js','apps/1-4/screen-to-move/games-data-v12.js'],out=[],left=files.length;for(var i=0;i<files.length;i++)(function(path){raw(path,function(e,t){if(!e){try{var box={},fn=new Function(t);fn.call(box);var a=box.A1ScreenMoveGames||box.A1ScreenMoveGamesV12||[],j;for(j=0;j<a.length;j++)out.push(a[j])}catch(x){}}left--;if(!left){cache.games=out;cb(out)}})})(files[i])}
function wordCategories(data,level){var out=[],seen={},l,i,j,row;for(l=1;l<=Number(level);l++){var a=data&&data[String(l)]||[];for(i=0;i<a.length;i++){row=a[i];if(!seen[row[0]]){seen[row[0]]=1;out.push({id:row[0],title:row[0]})}}}return out}
function wordsFor(data,level){var out=[],seen={},l,i,j,a,ws,v;for(l=1;l<=Number(level);l++){a=data&&data[String(l)]||[];for(i=0;i<a.length;i++){ws=text(a[i][2]).split('|');for(j=0;j<ws.length;j++){v=trim(ws[j]);if(v&&!seen[v]){seen[v]=1;out.push({id:v,title:v+' · '+a[i][0]})}}}}return out}
function renderRouteFields(){var r=currentRoute(),m=routeCtx.manifest;if(!r||!m){setFields('');return}routeCtx.route=r;if(r.id==='__app__'||r.href){setFields('');return}if(m.app_id==='a1-first-words'&&(r.id==='category'||r.id==='word')){setFields('<div class="pr-status">جارٍ قراءة مفردات التطبيق…</div>');loadWords(function(data){if(!data){setFields('<div class="pr-status">تعذر قراءة المفردات.</div>');return}setFields(numberLevels('rfLevel','المستوى')+'<label>'+(r.id==='category'?'التصنيف':'الكلمة')+'<select id="rfItem"></select></label>');function refresh(){var lv=$('rfLevel').value,rows=r.id==='category'?wordCategories(data,lv):wordsFor(data,lv);$('rfItem').innerHTML=optionRows(rows)}$('rfLevel').onchange=refresh;refresh()});return}if(m.app_id==='a1-imitate'&&(r.id==='family'||r.id==='experience')){setFields('<div class="pr-status">جارٍ قراءة مكتبة التجارب…</div>');loadExperiences(function(data){if(!data){setFields('<div class="pr-status">تعذر قراءة التجارب.</div>');return}var rows=r.id==='family'?(data.families||[]):data.experiences||[];setFields(selectHtml('rfItem',r.id==='family'?'المجال':'التجربة',rows,'id','title'))});return}if(m.app_id==='a1-screen-move'&&(r.id==='game'||r.id==='worksheet-designer')){setFields('<div class="pr-status">جارٍ قراءة الألعاب…</div>');loadGames(function(rows){setFields(selectHtml('rfItem',r.id==='game'?'اللعبة':'قالب اللعبة',rows,'id','title'))});return}if(r.items&&r.items.length){setFields(selectHtml('rfItem','الاختيار',r.items));return}if(r.item_type==='arabic-character'){setFields(selectHtml('rfItem','الحرف',['ا','ب','ت','ث','ج','ح','خ','د','ذ','ر','ز','س','ش','ص','ض','ط','ظ','ع','غ','ف','ق','ك','ل','م','ن','ه','و','ي']));return}if(r.item_type==='arabic-number'){setFields(selectHtml('rfItem','الرقم',['٠','١','٢','٣','٤','٥','٦','٧','٨','٩','١٠']));return}var params=r.params||[],h='';for(var i=0;i<params.length;i++)h+='<label>'+esc(params[i])+'<input class="rf-param" data-param="'+esc(params[i])+'" type="text"></label>';if(!params.length&&r.href_template)h='<label>معرف العنصر — إن لزم<input id="rfItem" type="text"></label>';setFields(h)}
function optionRows(rows){var h='',i,x;for(i=0;i<rows.length;i++){x=rows[i];h+='<option value="'+esc(x.id)+'">'+esc(x.title||x.label_ar||x.id)+'</option>'}return h}
function fillTemplate(t,vals){return text(t).replace(/\{([^}]+)\}/g,function(all,k){return encodeURIComponent(vals[k]==null?'':vals[k])})}
function stepFromForm(){var m=routeCtx.manifest,r=currentRoute(),vals={},el,item,lv,label,href,params,i;if(!m||!r)return null;if(r.id==='__app__'){href=m.app_href;label=m.title_ar+' · التطبيق كاملًا'}else if(r.href){href=r.href;label=m.title_ar+' · '+r.label_ar}else{if(m.app_id==='a1-first-words'&&(r.id==='category'||r.id==='word')){lv=$('rfLevel')&&$('rfLevel').value||'1';item=$('rfItem')&&$('rfItem').value||'';vals.level=lv;if(r.id==='category')vals.category=item;else vals.word=item;vals.display='ar'}else if($('rfItem')){item=$('rfItem').value;vals.id=item;vals.value=item}else{each($('routeFields').getElementsByClassName('rf-param'),function(x){vals[x.getAttribute('data-param')]=x.value})}params=r.params||[];for(i=0;i<params.length;i++)if(vals[params[i]]==null){if(params[i]==='id'&&vals.id!=null)continue;if(params[i]==='value'&&vals.value!=null)continue;vals[params[i]]=''}href=fillTemplate(r.href_template,vals);label=m.title_ar+' · '+r.label_ar+(item?' · '+item:'')}if(!href)return null;return{step_id:uid('step'),app_id:m.app_id,route_id:r.id,label:label,href:href,external:isExternal(href),duration_seconds:Math.max(5,Number($('stepSeconds').value)||60),advance_mode:$('advanceMode').value||'time'}}
function addStep(){var s=stepFromForm();if(!s){toast('اختر تفاصيل الخطوة أولًا.');return}draft.steps.push(s);syncDraftInputs();renderDraft();toast('أضيفت الخطوة.')}
function addManual(){var title=trim($('manualTitle').value),url=trim($('manualUrl').value),sec=Number($('manualSeconds').value)||60;if(!title||(!isExternal(url)&&!safeInternal(url))){toast('اكتب اسمًا ورابطًا صحيحًا.');return}draft.steps.push({step_id:uid('step'),app_id:isExternal(url)?'external':'manual',route_id:'manual',label:title,href:url,external:isExternal(url),duration_seconds:Math.max(5,sec),advance_mode:'time'});renderDraft();$('manualTitle').value='';$('manualUrl').value=''}
function syncDraftInputs(){draft.title=trim($('planTitle').value);draft.level_id=$('planLevel').value||'custom'}function renderDraft(){if(!$('draftSteps'))return;$('planTitle').value=draft.title||'';$('planLevel').value=draft.level_id||'custom';var h='',i,s;if(!draft.steps.length)h='<div class="pr-empty">لا توجد خطوات بعد. اختر من التطبيقات أدناه أو استخدم خطة جاهزة.</div>';for(i=0;i<draft.steps.length;i++){s=draft.steps[i];h+='<article class="pr-step"><span class="pr-step-index">'+(i+1)+'</span><div class="pr-step-main"><b>'+esc(s.label)+'</b><small>'+esc(s.duration_seconds)+'ث · '+esc(s.advance_mode==='time'?'انتقال بالوقت':s.advance_mode==='completion'?'عند الإكمال':'يدوي')+'</small></div><div class="pr-step-actions"><button data-step-action="up" data-i="'+i+'">↑</button><button data-step-action="down" data-i="'+i+'">↓</button><button data-step-action="remove" data-i="'+i+'" class="danger">حذف</button></div></article>'}$('draftSteps').innerHTML=h;each($('draftSteps').getElementsByTagName('button'),function(b){b.onclick=function(){var i=Number(this.getAttribute('data-i')),a=this.getAttribute('data-step-action'),x;if(a==='remove')draft.steps.splice(i,1);else if(a==='up'&&i>0){x=draft.steps[i-1];draft.steps[i-1]=draft.steps[i];draft.steps[i]=x}else if(a==='down'&&i<draft.steps.length-1){x=draft.steps[i+1];draft.steps[i+1]=draft.steps[i];draft.steps[i]=x}renderDraft()}})}
function newDraft(){draft={plan_id:'',title:'',level_id:activeLevel||'1-2',steps:[]};renderDraft();switchTab('builder')}
function savePlan(asTemplate){syncDraftInputs();if(!draft.steps.length){toast('أضف خطوة واحدة على الأقل.');return}var x=clone(draft),arr=asTemplate?db.templates:db.plans,idKey=asTemplate?'template_id':'plan_id';x[idKey]=x[idKey]||uid(asTemplate?'template':'plan');x.created_at=x.created_at||iso();x.updated_at=iso();if(asTemplate)delete x.plan_id;else delete x.template_id;arr.unshift(x);saveDb();toast(asTemplate?'تم حفظ النمط.':'تم حفظ الخطة.');renderSaved()}
function renderSaved(){var h='',i,p;for(i=0;i<db.plans.length;i++){p=db.plans[i];h+=savedHtml(p,'plan',i)}$('savedPlans').innerHTML=h||'<div class="pr-empty">لا توجد خطط محفوظة.</div>';h='';for(i=0;i<db.templates.length;i++){p=db.templates[i];h+=savedHtml(p,'template',i)}$('savedTemplates').innerHTML=h||'<div class="pr-empty">لا توجد أنماط محفوظة.</div>';bindSaved()}
function savedHtml(p,type,i){return'<article class="pr-saved"><h3>'+esc(p.title||'خطة بلا اسم')+'</h3><div class="pr-saved-meta">'+esc(levelLabel(p.level_id))+' · '+(p.steps||[]).length+' خطوات</div><div class="pr-saved-actions"><button data-saved="run" data-type="'+type+'" data-i="'+i+'" class="primary">تشغيل</button><button data-saved="edit" data-type="'+type+'" data-i="'+i+'">نسخ وتعديل</button><button data-saved="delete" data-type="'+type+'" data-i="'+i+'" class="danger">حذف</button></div></article>'}
function bindSaved(){var root=$('tab-saved');each(root.querySelectorAll('[data-saved]'),function(b){b.onclick=function(){var type=this.getAttribute('data-type'),i=Number(this.getAttribute('data-i')),a=this.getAttribute('data-saved'),arr=type==='template'?db.templates:db.plans,p=arr[i];if(!p)return;if(a==='run')startRun(p);else if(a==='edit'){draft=clone(p);delete draft.plan_id;delete draft.template_id;draft.title=(p.title||'خطة')+' — نسخة';switchTab('builder')}else if(a==='delete'){arr.splice(i,1);saveDb();renderSaved()}}})}
function loadPresets(){json('apps/1-4/plan-runner-360/data/presets.json',function(e,p){if(e){$('presetList').innerHTML='<div class="pr-empty">تعذر تحميل الخطط الجاهزة.</div>';return}presets=p;renderLevels();renderPresets()})}
function renderLevels(){var levels=presets&&presets.levels||[],h='',i;for(i=0;i<levels.length;i++)h+='<button type="button" data-level="'+esc(levels[i].id)+'" class="'+(levels[i].id===activeLevel?'on':'')+'">'+esc(levels[i].label_ar)+'</button>';$('levelTabs').innerHTML=h;each($('levelTabs').getElementsByTagName('button'),function(b){b.onclick=function(){activeLevel=this.getAttribute('data-level');renderLevels();renderPresets()}})}
function renderPresets(){var list=presets&&presets.presets||[],h='',i,j,p;for(i=0;i<list.length;i++){p=list[i];if(p.level_id!==activeLevel)continue;h+='<article class="pr-preset"><small>'+esc(levelLabel(p.level_id))+'</small><h3>'+esc(p.title_ar)+'</h3><p>'+esc(p.note_ar||'')+'</p><ul class="pr-preset-steps">';for(j=0;j<p.steps.length;j++)h+='<li><b>'+(j+1)+'.</b> '+esc(p.steps[j].label)+' · '+esc(p.steps[j].duration_seconds)+'ث</li>';h+='</ul><div class="pr-preset-actions"><button class="primary" data-preset="run" data-id="'+esc(p.id)+'">▶ تشغيل الآن</button><button data-preset="edit" data-id="'+esc(p.id)+'">استخدم وعدّل</button></div></article>'}$('presetList').innerHTML=h||'<div class="pr-empty">لا توجد نماذج لهذا المستوى.</div>';each($('presetList').querySelectorAll('[data-preset]'),function(b){b.onclick=function(){var p=findPreset(this.getAttribute('data-id'));if(!p)return;if(this.getAttribute('data-preset')==='run')startRun(p);else{draft=clone(p);delete draft.id;draft.plan_id='';switchTab('builder')}}})}
function findPreset(id){var a=presets&&presets.presets||[],i;for(i=0;i<a.length;i++)if(a[i].id===id)return a[i];return null}
function fmt(sec){sec=Math.max(0,Math.floor(sec));var m=Math.floor(sec/60),s=sec%60;return(m<10?'0':'')+m+':'+(s<10?'0':'')+s}function eventList(){try{var a=JSON.parse(w.localStorage.getItem(EVENT_KEY)||'[]');return a&&a.push?a:[]}catch(e){return[]}}
function startRun(plan){if(!plan||!plan.steps||!plan.steps.length){toast('الخطة لا تحتوي خطوات.');return}syncDraftInputs();run={run_id:uid('run'),plan_id:plan.plan_id||plan.id||'',title:plan.title||plan.title_ar||'خطة تشغيل',level_id:plan.level_id||'custom',started_at:iso(),finished_at:null,index:0,steps:clone(plan.steps),results:[]};$('runner').hidden=false;$('runner').setAttribute('aria-hidden','false');openRunStep(0)}
function stopTimers(){if(timer){clearInterval(timer);timer=null}if(eventTimer){clearInterval(eventTimer);eventTimer=null}}function closeExternal(){try{if(externalWin&&!externalWin.closed)externalWin.close()}catch(e){}externalWin=null}
function recordCurrent(status){if(!run)return;var s=run.steps[run.index],last=run.results.length?run.results[run.results.length-1]:null;if(last&&last.step_id===s.step_id&&!last.ended_at){last.ended_at=iso();last.status=status||last.status||'left'}else if(!last||last.step_id!==s.step_id){run.results.push({step_id:s.step_id,label:s.label,status:status||'left',started_at:iso(),ended_at:iso()})}}
function openRunStep(i){if(!run)return;if(i<0)i=0;if(i>=run.steps.length){finishRun('completed');return}stopTimers();closeExternal();run.index=i;paused=false;var s=run.steps[i],launch=uid('launch'),url=s.href,finalUrl;if(s.external||isExternal(url)){finalUrl=url;$('runNotice').innerHTML='رابط خارجي: إذا لم يظهر داخل الصفحة استخدم «فتح بتبويب جديد». '}else{finalUrl=rootUrl(url);finalUrl=addParam(finalUrl,'embedded','1');finalUrl=addParam(finalUrl,'caller',APP_ID);finalUrl=addParam(finalUrl,'launch_id',launch)}s._launch_id=launch;s._opened_at=iso();run.results.push({step_id:s.step_id,label:s.label,status:'opened',launch_id:launch,started_at:iso(),ended_at:null});$('runPlanTitle').innerHTML=esc(run.title);$('runStepTitle').innerHTML=esc(s.label);$('runProgress').innerHTML=(i+1)+' / '+run.steps.length;$('runNotice').innerHTML=(s.external?'رابط خارجي · ':'')+esc(s.advance_mode==='time'?'سينتقل تلقائيًا عند انتهاء الوقت.':s.advance_mode==='completion'?'سينتقل عند تسجيل إكمال النشاط.':'الانتقال يدوي.');$('runFrame').src=finalUrl;remaining=Math.max(5,Number(s.duration_seconds)||60);$('runClock').innerHTML=fmt(remaining);startClock(s);watchEvents(s)}
function startClock(s){var deadline=+new Date()+remaining*1000;timer=setInterval(function(){if(paused)return;remaining=Math.max(0,Math.ceil((deadline-(+new Date()))/1000));$('runClock').innerHTML=fmt(remaining);if(remaining<=0){clearInterval(timer);timer=null;if(s.advance_mode==='time')moveRun(1,'time-finished');else $('runNotice').innerHTML='انتهى الوقت المقترح؛ يمكنك المتابعة أو الانتقال يدويًا.'}},250)}
function watchEvents(s){if(s.external)return;eventTimer=setInterval(function(){var ev=eventList(),i,e;for(i=ev.length-1;i>=0;i--){e=ev[i];if(e.launch_id===s._launch_id&&e.type==='completed'){clearInterval(eventTimer);eventTimer=null;$('runNotice').innerHTML='✓ تم تسجيل إكمال النشاط.';if(s.advance_mode==='completion')moveRun(1,'completed');return}}},500)}
function moveRun(delta,status){if(!run)return;recordCurrent(status||'manual-next');openRunStep(run.index+delta)}function finishRun(status){if(!run)return;stopTimers();closeExternal();recordCurrent(status==='stopped'?'stopped':'completed');run.finished_at=iso();run.status=status||'completed';db.runs.unshift(clone(run));if(db.runs.length>100)db.runs=db.runs.slice(0,100);saveDb();$('runFrame').src='about:blank';$('runner').hidden=true;$('runner').setAttribute('aria-hidden','true');toast(status==='stopped'?'تم إيقاف الخطة وحفظ التجربة.':'اكتملت الخطة وسُجلت التجربة.');run=null;renderHistory()}
function togglePause(){if(!run)return;paused=!paused;$('pauseBtn').innerHTML=paused?'استئناف المؤقت':'إيقاف المؤقت';if(!paused){stopTimers();var s=run.steps[run.index];startClock(s);watchEvents(s)}}function openExternal(){if(!run)return;var s=run.steps[run.index],u=s.external?s.href:rootUrl(s.href);try{externalWin=w.open(u,'_blank')}catch(e){w.location.href=u}}
function renderHistory(){var h='',i,r;for(i=0;i<db.runs.length;i++){r=db.runs[i];h+='<article class="pr-history-row"><b>'+esc(r.title||'خطة')+'</b><small>'+esc(r.started_at||'')+' · '+esc(levelLabel(r.level_id))+' · '+(r.results||[]).length+' خطوات · '+esc(r.status||'')+'</small></article>'}$('runHistory').innerHTML=h||'<div class="pr-empty">لا توجد تجارب تشغيل محفوظة بعد.</div>'}
function exportData(){var t=$('transferText');t.value=JSON.stringify({schema_version:'1.0',app_id:APP_ID,exported_at:iso(),plans:db.plans,templates:db.templates,runs:db.runs},null,2);$('transferBox').hidden=false;switchTab('saved');try{t.focus();t.select()}catch(e){}}
function copyTransfer(){var t=$('transferText');try{t.focus();t.select();if(d.execCommand('copy'))toast('تم النسخ.');else toast('حدد النص وانسخه يدويًا.')}catch(e){toast('حدد النص وانسخه يدويًا.')}}function importTransfer(){var x;try{x=JSON.parse($('transferText').value)}catch(e){toast('JSON غير صالح.');return}if(x.plans&&x.plans.push)db.plans=x.plans.concat(db.plans);if(x.templates&&x.templates.push)db.templates=x.templates.concat(db.templates);if(x.runs&&x.runs.push)db.runs=x.runs.concat(db.runs);saveDb();renderSaved();renderHistory();toast('تم الاستيراد.')}
function bind(){each($('mainTabs').getElementsByTagName('button'),function(b){b.onclick=function(){switchTab(this.getAttribute('data-tab'))}});$('planTitle').onchange=syncDraftInputs;$('planLevel').onchange=syncDraftInputs;$('newPlanBtn').onclick=newDraft;$('addStepBtn').onclick=addStep;$('addManualBtn').onclick=addManual;$('savePlanBtn').onclick=function(){savePlan(false)};$('saveTemplateBtn').onclick=function(){savePlan(true)};$('runDraftBtn').onclick=function(){syncDraftInputs();startRun(draft)};$('exportBtn').onclick=exportData;$('copyTransferBtn').onclick=copyTransfer;$('importTransferBtn').onclick=importTransfer;$('clearHistoryBtn').onclick=function(){if(w.confirm('حذف سجل التجارب فقط؟')){db.runs=[];saveDb();renderHistory()}};$('pauseBtn').onclick=togglePause;$('prevBtn').onclick=function(){if(run&&run.index>0)moveRun(-1,'manual-prev')};$('nextBtn').onclick=function(){moveRun(1,'manual-next')};$('stopBtn').onclick=function(){finishRun('stopped')};$('externalBtn').onclick=openExternal}
function boot(){loadDb();bind();renderDraft();renderSaved();renderHistory();loadPresets();loadCatalog(function(){$('catalogStatus').innerHTML='تم تحميل '+Object.keys?Object.keys(manifests).length:'مكتبة التطبيقات'+' تطبيق/خدمة قابلة للربط.'})}
if(d.readyState==='loading'){if(d.addEventListener)d.addEventListener('DOMContentLoaded',boot,false);else w.attachEvent&&w.attachEvent('onload',boot)}else boot();
})(window,document);
