var CACHE='app360-plan-runner-360-v6-family-inline-family-school-v99';
var SHELL=['../../../assets/js/app360-app-audience-v1.js?v=98','../../../assets/brand/family-school-360-icon-192.png?v=98','../../../assets/brand/family-school-360-logo.png?v=98',
  './','./index.html?v=98','./styles.css?v=3','./responsive-session-v2.css?v=3','./presets-merge-v3.js?v=98','./app.js?v=98&brand=98','./responsive-session-v3.js?v=3','./real-play.html?v=2','./data/presets.json','./manifest.webmanifest?v=3','./icon.svg?v=3','./app.json',
  '../../../assets/css/legacy-compat.css?v=24','../../../assets/js/legacy-compat.js?v=24','../../../assets/js/app-pwa.js?v=3','../../../assets/js/app360-ai-shell.js?v=2&brand=98','../../../assets/js/app360-session-v1.js?v=98&brand=98','../../../assets/js/app360-family-sync-v1.js?v=99','../../../assets/js/app360-family-catalog-v1.js?v=99&brand=98','../../../assets/js/app360-family-ui-v2.js?v=98',
  '../../../data/app-links-registry.json','../../../data/catalog.json',
  '../say-and-name/links.json','../imitate-one-step/links.json','../screen-to-move/links.json','../drawing-writing-foundations/links.json','../calm-with-me/links.json','../sensory-motion-missions/links.json','../my-little-routine/links.json','../tangram-builder/links.json','../picture-puzzles/links.json'
];
self.addEventListener('install',function(e){e.waitUntil(caches.open(CACHE).then(function(c){return Promise.all(SHELL.map(function(u){return c.add(u).catch(function(){return null})}))}));if(self.skipWaiting)self.skipWaiting()});
self.addEventListener('activate',function(e){e.waitUntil(caches.keys().then(function(keys){return Promise.all(keys.map(function(k){if(k.indexOf('app360-plan-runner-360-')===0&&k!==CACHE)return caches.delete(k)}))}).then(function(){return self.clients&&self.clients.claim?self.clients.claim():null}))});
function same(req){try{return new URL(req.url).origin===self.location.origin}catch(e){return false}}
function fresh(req){return fetch(req,{cache:'no-store'}).then(function(r){if(r&&r.ok&&same(req)){var x=r.clone();caches.open(CACHE).then(function(c){c.put(req,x)})}return r}).catch(function(){return caches.match(req).then(function(x){return x||caches.match('./index.html?v=98')||caches.match('./')})})}
function cached(req){return caches.match(req).then(function(x){return x||fetch(req,{cache:'no-store'}).then(function(r){if(r&&r.ok&&same(req)){var y=r.clone();caches.open(CACHE).then(function(c){c.put(req,y)})}return r})})}
self.addEventListener('fetch',function(e){if(!e.request||e.request.method!=='GET'||!same(e.request))return;var u=e.request.url||'';if(e.request.mode==='navigate'||u.indexOf('presets-merge-v3.js')>=0||u.indexOf('app360-family-sync')>=0||u.indexOf('app360-family-catalog')>=0||u.indexOf('app360-family-ui')>=0){e.respondWith(fresh(e.request));return}e.respondWith(cached(e.request))});
