'use strict';
var http=require('http');var url=require('url');var core=require('./index');var sessions=require('./session-repository');var safe=require('./safe-reels-adapter');
var PORT=Number(process.env.APP360_PORT||3036),MAX_BODY=1024*1024;
function send(res,status,obj,origin){var body=JSON.stringify(obj||{});res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');if(origin)res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.end(body)}
function allowedOrigin(req){var origin=req.headers.origin||'';if(!origin)return'';try{var u=new URL(origin);if(u.host===req.headers.host)return origin}catch(e){}var list=String(process.env.APP360_ALLOWED_ORIGINS||'').split(',');for(var i=0;i<list.length;i++)if(list[i].trim()===origin)return origin;return null}
function body(req){return new Promise(function(resolve,reject){var parts=[],size=0;req.on('data',function(c){size+=c.length;if(size>MAX_BODY){reject(new Error('body too large'));req.destroy();return}parts.push(c)});req.on('end',function(){if(!parts.length){resolve({});return}try{resolve(JSON.parse(Buffer.concat(parts).toString('utf8')))}catch(e){reject(new Error('invalid JSON'))}});req.on('error',reject)})}
function bearer(req){var h=String(req.headers.authorization||''),m=/^Bearer\s+(.+)$/i.exec(h);return m?m[1]:''}
async function auth(db,req){return await sessions.findIdentitySession(db,bearer(req))}
async function handler(req,res){var origin=allowedOrigin(req);if(origin===null){send(res,403,{error:'origin_not_allowed'});return}if(req.method==='OPTIONS'){res.statusCode=204;if(origin)res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');res.setHeader('Access-Control-Allow-Methods','GET, POST, OPTIONS');res.setHeader('Vary','Origin');res.end();return}var p=url.parse(req.url,true),path=p.pathname||'',db=await core.db.createDb();try{
  if(req.method==='GET'&&path==='/api/app360/health'){var m=await db('knex_migrations').count({n:'id'}).first().catch(function(){return{n:0}});send(res,200,{ok:true,service:'app360-data-core',safe_reels_auth_configured:safe.configured(),applied_migrations:Number(m.n)||0},origin);return}
  if(req.method==='POST'&&path==='/api/app360/auth/child-login'){var input=await body(req),identity;try{identity=await safe.loginChild(input)}catch(e){if(e.code==='SAFE_REELS_NOT_CONFIGURED'){send(res,503,{error:e.code,message:'Safe Reels login adapter is not configured on this server.'},origin);return}if(e.code==='AUTH_REJECTED'){send(res,401,{error:e.code,message:'بيانات الدخول غير صحيحة.'},origin);return}throw e}var linked=await sessions.ensureExternalUser(db,identity),created=await sessions.createIdentitySession(db,{user_id:linked.user.id,account_id:linked.account_id,source:'safe-reels-360',external_session_ref:identity.external_session_ref});send(res,200,{token:created.token,expires_at:created.session.expires_at,profile:{user_id:linked.user.id,display_name:linked.user.display_name,role:linked.user.role,age_band:linked.user.age_band,account_id:linked.account_id}},origin);return}
  if(req.method==='POST'&&path==='/api/app360/auth/logout'){await sessions.revokeIdentitySession(db,bearer(req));send(res,200,{ok:true},origin);return}
  var me=await auth(db,req);if(!me){send(res,401,{error:'authentication_required',message:'سجل دخول الطفل أو المتدرب أولًا.'},origin);return}
  if(req.method==='POST'&&path==='/api/app360/usage/batch'){var usage=await body(req),ur=await sessions.importUsageBatch(db,me.user.id,usage);send(res,200,ur,origin);return}
  if(req.method==='GET'&&path==='/api/app360/me/dashboard'){var dash=await sessions.usageDashboard(db,me.user.id);dash.profile={user_id:me.user.id,display_name:me.user.display_name,role:me.user.role,age_band:me.user.age_band};send(res,200,dash,origin);return}
  if(req.method==='POST'&&path==='/api/app360/content/batch'){var content=await body(req),cr=await sessions.upsertUserContentBatch(db,me.user.id,content);send(res,200,cr,origin);return}
  if(req.method==='GET'&&path==='/api/app360/content'){var rows=await sessions.listUserContent(db,me.user.id,p.query.app_id||null);send(res,200,{items:rows},origin);return}
  send(res,404,{error:'not_found'},origin)
 }catch(e){console.error(e&&e.stack||e);send(res,500,{error:'server_error',message:'حدث خطأ في خدمة بيانات App360.'},origin)}finally{await db.destroy()}}
var server=http.createServer(function(req,res){handler(req,res).catch(function(e){console.error(e&&e.stack||e);if(!res.headersSent)send(res,500,{error:'server_error'})})});
if(require.main===module)server.listen(PORT,function(){console.log('App360 Data Core API listening on '+PORT);console.log('Safe Reels auth configured:',safe.configured()?'yes':'no')});
module.exports={handler:handler,server:server};
