(function(){
'use strict';
var items=[],categories=[],categoryById={},state={mode:'category',category:'home',scope:'current',currentIndex:0,speech:true,autoplay:false,timer:null,touchX:0};
var SETTINGS='app360:a1-first-words:viewer-v5';
var $=function(id){return document.getElementById(id)};
function toast(msg){var n=$('toast');if(!n)return; n.textContent=msg;n.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(function(){n.classList.remove('show')},2300)}
function loadSettings(){try{var x=JSON.parse(localStorage.getItem(SETTINGS)||'{}');if(x.category)state.category=x.category;if(x.mode)state.mode=x.mode;if(x.scope)state.scope=x.scope;if(typeof x.speech==='boolean')state.speech=x.speech}catch(e){}}
function saveSettings(){try{localStorage.setItem(SETTINGS,JSON.stringify({category:state.category,mode:state.mode,scope:state.scope,speech:state.speech}))}catch(e){}}
function getCollection(){if(state.mode==='all'||state.scope==='all')return items;return items.filter(function(x){return x.category===state.category})}
function current(){var c=getCollection();if(!c.length)return null;if(state.currentIndex>=c.length)state.currentIndex=0;if(state.currentIndex<0)state.currentIndex=c.length-1;return c[state.currentIndex]}
function safe(s){return String(s==null?'':s).replace(/[&<>\"]/g,function(ch){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[ch]})}
function renderCategories(){var box=$('categoryChips');box.innerHTML=categories.map(function(c){return '<button class="chip '+(state.category===c.id?'is-active':'')+'" data-category="'+safe(c.id)+'">'+safe(c.emoji)+' '+safe(c.label_ar)+'</button>'}).join('');var bs=box.querySelectorAll('[data-category]');for(var i=0;i<bs.length;i++)bs[i].onclick=function(){state.category=this.getAttribute('data-category');state.mode='category';state.currentIndex=0;saveSettings();restartAutoplay();render();if(state.speech)speakCurrent()}}
function renderThumbs(c,it){var g=$('thumbGrid');g.innerHTML=c.map(function(x,ix){var cat=categoryById[x.category]||{};return '<div class="thumb"><button class="'+(it&&it.id===x.id?'is-current':'')+'" data-thumb-index="'+ix+'"><svg viewBox="0 0 800 800" aria-hidden="true"><use href="'+safe(x.sprite)+'#'+safe(x.symbol)+'" xlink:href="'+safe(x.sprite)+'#'+safe(x.symbol)+'"></use></svg><strong>'+safe(x.ar)+'</strong><small>'+safe(cat.label_ar||'')+'</small></button></div>'}).join('');var bs=g.querySelectorAll('[data-thumb-index]');for(var i=0;i<bs.length;i++)bs[i].onclick=function(){state.currentIndex=parseInt(this.getAttribute('data-thumb-index'),10)||0;render();if(state.speech)speakCurrent()}}
function render(){renderCategories();var c=getCollection(),it=current();if(!it)return;var cat=categoryById[it.category]||{};var ref=it.sprite+'#'+it.symbol;$('itemUse').setAttribute('href',ref);$('itemUse').setAttributeNS('http://www.w3.org/1999/xlink','xlink:href',ref);$('itemName').textContent=it.ar;$('itemHint').textContent=it.hint||'';$('categoryTag').textContent=(cat.emoji||'')+' '+(cat.label_ar||'');$('modeTag').textContent=state.mode==='all'?'عرض عام':'حسب التصنيف';$('playTag').textContent=state.autoplay?'تلقائي':'يدوي';$('positionMeta').textContent=(state.currentIndex+1)+' من '+c.length;$('scopeMeta').textContent=(state.mode==='all'||state.scope==='all')?'التنقل في كل التصنيفات':'التنقل داخل التصنيف';$('speechMeta').textContent=state.speech?'النطق مفعّل':'النطق متوقف';$('rangeLabel').textContent=(state.currentIndex+1)+' / '+c.length;$('itemRange').max=Math.max(c.length-1,0);$('itemRange').value=state.currentIndex;$('speechToggle').textContent=state.speech?'النطق مفعّل':'النطق متوقف';$('speechToggle').classList.toggle('is-active',state.speech);$('autoplayToggle').textContent=state.autoplay?'إيقاف التنقل التلقائي':'تشغيل التنقل التلقائي';$('autoplayToggle').classList.toggle('is-active',state.autoplay);var v=$('displayModeSegment').querySelectorAll('[data-mode]');for(var i=0;i<v.length;i++)v[i].classList.toggle('is-active',v[i].getAttribute('data-mode')===state.mode);var s=$('scopeSegment').querySelectorAll('[data-scope]');for(var j=0;j<s.length;j++)s[j].classList.toggle('is-active',s[j].getAttribute('data-scope')===state.scope);renderThumbs(c,it)}
function speakCurrent(force){var it=current();if(!it||(!state.speech&&!force))return;if(!('speechSynthesis'in window)||typeof SpeechSynthesisUtterance==='undefined'){toast('لا يتوفر نطق عربي على هذا الجهاز.');return}try{speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(it.ar);u.lang='ar-SA';u.rate=.76;u.pitch=1.02;var vs=speechSynthesis.getVoices?speechSynthesis.getVoices():[],voice=null;for(var i=0;i<vs.length;i++){if(/^ar(-|_)/i.test(vs[i].lang)){voice=vs[i];break}}if(voice)u.voice=voice;speechSynthesis.speak(u)}catch(e){toast('تعذر تشغيل النطق الآن.')}}
function move(n){var c=getCollection();if(!c.length)return;state.currentIndex=(state.currentIndex+n+c.length)%c.length;render();if(state.speech)speakCurrent()}function next(){move(1)}function prev(){move(-1)}
function restartAutoplay(){clearInterval(state.timer);state.timer=null;if(state.autoplay)state.timer=setInterval(next,parseInt($('autoplaySpeed').value,10)||4000)}
function bind(){$('prevBtn').onclick=prev;$('nextBtn').onclick=next;$('speakBtn').onclick=function(){speakCurrent(true)};$('speakCurrentThumb').onclick=function(){speakCurrent(true)};$('speechToggle').onclick=function(){state.speech=!state.speech;saveSettings();render();if(state.speech)speakCurrent()};$('autoplayToggle').onclick=function(){state.autoplay=!state.autoplay;restartAutoplay();render()};$('autoplaySpeed').onchange=restartAutoplay;$('itemRange').oninput=function(){state.currentIndex=parseInt(this.value,10)||0;render();if(state.speech)speakCurrent()};$('shuffleBtn').onclick=function(){state.mode='all';state.scope='all';state.currentIndex=Math.floor(Math.random()*Math.max(items.length,1));saveSettings();restartAutoplay();render();if(state.speech)speakCurrent()};$('fullscreenBtn').onclick=function(){if(!document.fullscreenElement){if(document.documentElement.requestFullscreen)document.documentElement.requestFullscreen();else toast('ملء الشاشة غير مدعوم.')}else if(document.exitFullscreen)document.exitFullscreen()};var v=$('displayModeSegment').querySelectorAll('[data-mode]');for(var i=0;i<v.length;i++)v[i].onclick=function(){state.mode=this.getAttribute('data-mode');state.currentIndex=0;saveSettings();restartAutoplay();render();if(state.speech)speakCurrent()};var s=$('scopeSegment').querySelectorAll('[data-scope]');for(var j=0;j<s.length;j++)s[j].onclick=function(){state.scope=this.getAttribute('data-scope');state.currentIndex=0;saveSettings();restartAutoplay();render();if(state.speech)speakCurrent()};var st=$('stage');st.addEventListener('touchstart',function(e){state.touchX=e.changedTouches[0].clientX},{passive:true});st.addEventListener('touchend',function(e){var dx=e.changedTouches[0].clientX-state.touchX;if(Math.abs(dx)<45)return;if(dx>0)prev();else next()},{passive:true});st.addEventListener('click',function(e){if(e.target.closest('button'))return;speakCurrent(true)});document.addEventListener('keydown',function(e){if(e.target&&/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='ArrowRight')prev();else if(e.key==='ArrowLeft')next()})}
function init(){loadSettings();bind();fetch('data/words.json',{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('data');return r.json()}).then(function(d){categories=d.categories||[];items=d.items||[];categoryById={};for(var i=0;i<categories.length;i++)categoryById[categories[i].id]=categories[i];if(!categoryById[state.category]&&categories[0])state.category=categories[0].id;render()}).catch(function(){toast('تعذر تحميل مكتبة الأشياء.');$('thumbGrid').innerHTML='<div class="side-note">تعذر تحميل البيانات. استخدم زر التحديث.</div>'})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
