(function(){
'use strict';
var items=[],categories=[],categoryById={},spriteReady={};
var state={mode:'category',category:'home',scope:'current',currentIndex:0,speech:true,autoplay:false,timer:null,touchX:0,speed:4000};
var SETTINGS='app360:a1-first-words:viewer-v6';
var $=function(id){return document.getElementById(id)};
var FALLBACK={
  categories:[
    {id:'home',label_ar:'أشياء في المنزل',emoji:'🏠'},
    {id:'nature',label_ar:'مخلوقات في الطبيعة',emoji:'🦋'},
    {id:'animals',label_ar:'الحيوانات',emoji:'🐾'},
    {id:'fruits',label_ar:'الفواكه والطعام',emoji:'🍎'},
    {id:'professions',label_ar:'أدوات ومهن',emoji:'🩺'}
  ],
  items:[
    {id:'cup',category:'home',ar:'كوب',hint:'يمكن الإشارة إلى كوب حقيقي أو استخدام الصورة فقط.',sprite:'assets/sprites/home.svg',symbol:'cup'},
    {id:'book',category:'home',ar:'كتاب',hint:'افتحوا كتابًا بسيطًا وسمّوه معًا.',sprite:'assets/sprites/home.svg',symbol:'book'},
    {id:'chair',category:'home',ar:'كرسي',hint:'أشيروا إلى كرسي قريب بدل إحضاره.',sprite:'assets/sprites/home.svg',symbol:'chair'},
    {id:'lamp',category:'home',ar:'مصباح',hint:'لاحظوا أن المصباح يضيء من دون لمس الأسلاك.',sprite:'assets/sprites/home.svg',symbol:'lamp'},
    {id:'door',category:'home',ar:'باب',hint:'يمكن فتح الباب وإغلاقه مع التسمية.',sprite:'assets/sprites/home.svg',symbol:'door'},
    {id:'spoon',category:'home',ar:'ملعقة',hint:'استخدموا ملعقة آمنة ومألوفة للطفل.',sprite:'assets/sprites/home.svg',symbol:'spoon'},
    {id:'butterfly',category:'nature',ar:'فراشة',hint:'مخلوق صغير جميل في الطبيعة. شاهدوا الصورة أو فراشة حقيقية من بعيد.',sprite:'assets/sprites/nature.svg',symbol:'butterfly'},
    {id:'bee',category:'nature',ar:'نحلة',hint:'نتعرّف إلى النحلة بصريًا من دون الاقتراب منها أو لمسها.',sprite:'assets/sprites/nature.svg',symbol:'bee'},
    {id:'ant',category:'nature',ar:'نملة',hint:'يمكن مراقبة النملة من مكان آمن وتسميتها بكلمة واحدة.',sprite:'assets/sprites/nature.svg',symbol:'ant'},
    {id:'snail',category:'nature',ar:'حلزون',hint:'مخلوق بطيء الحركة يمكن التعرف إلى شكله بسهولة.',sprite:'assets/sprites/nature.svg',symbol:'snail'},
    {id:'ladybug',category:'nature',ar:'دعسوقة',hint:'حشرة صغيرة ذات ألوان واضحة، مناسبة للتعرف البصري.',sprite:'assets/sprites/nature.svg',symbol:'ladybug'},
    {id:'frog',category:'nature',ar:'ضفدع',hint:'مخلوق يعيش قرب الماء، ويمكن تقليد صوته أثناء التسمية.',sprite:'assets/sprites/nature.svg',symbol:'frog'},
    {id:'cat',category:'animals',ar:'قطة',hint:'يمكن تقليد صوت القطة أيضًا.',sprite:'assets/sprites/animals.svg',symbol:'cat'},
    {id:'dog',category:'animals',ar:'كلب',hint:'استخدموا الصورة إذا لم يكن الحيوان قريبًا.',sprite:'assets/sprites/animals.svg',symbol:'dog'},
    {id:'bird',category:'animals',ar:'طائر',hint:'ابحثوا عن طائر في الخارج أو شاهدوا الصورة.',sprite:'assets/sprites/animals.svg',symbol:'bird'},
    {id:'fish',category:'animals',ar:'سمكة',hint:'يمكن وصف حركة السمكة في الماء.',sprite:'assets/sprites/animals.svg',symbol:'fish'},
    {id:'rabbit',category:'animals',ar:'أرنب',hint:'الصورة كافية لهذا النشاط اللغوي.',sprite:'assets/sprites/animals.svg',symbol:'rabbit'},
    {id:'horse',category:'animals',ar:'حصان',hint:'استخدموا الصورة أو لعبة حصان صغيرة.',sprite:'assets/sprites/animals.svg',symbol:'horse'},
    {id:'apple',category:'fruits',ar:'تفاحة',hint:'يمكن لمس التفاحة أو شمها إن وجدت.',sprite:'assets/sprites/fruits.svg',symbol:'apple'},
    {id:'banana',category:'fruits',ar:'موزة',hint:'ثمرة حقيقية تساعد على ربط الكلمة بالواقع.',sprite:'assets/sprites/fruits.svg',symbol:'banana'},
    {id:'orange',category:'fruits',ar:'برتقالة',hint:'اللون والرائحة يساعدان على التعلّم.',sprite:'assets/sprites/fruits.svg',symbol:'orange'},
    {id:'grapes',category:'fruits',ar:'عنب',hint:'يمكن مشاهدة العنقود وتسميته.',sprite:'assets/sprites/fruits.svg',symbol:'grapes'},
    {id:'watermelon',category:'fruits',ar:'بطيخ',hint:'تحدثوا عن اللون والحجم.',sprite:'assets/sprites/fruits.svg',symbol:'watermelon'},
    {id:'bread',category:'fruits',ar:'خبز',hint:'الخبز من الأشياء المألوفة جدًا للطفل.',sprite:'assets/sprites/fruits.svg',symbol:'bread'},
    {id:'stethoscope',category:'professions',ar:'سماعة الطبيب',hint:'قسم ثانوي مهم وجميل للتعرّف على أدوات المهن.',sprite:'assets/sprites/professions.svg',symbol:'stethoscope'},
    {id:'thermometer',category:'professions',ar:'ميزان حرارة',hint:'نتعرف على اسمه ووظيفته بشكل بسيط.',sprite:'assets/sprites/professions.svg',symbol:'thermometer'},
    {id:'medicine-box',category:'professions',ar:'صندوق إسعاف',hint:'نوضح أنه من أدوات المساعدة والعناية.',sprite:'assets/sprites/professions.svg',symbol:'medicine-box'},
    {id:'syringe',category:'professions',ar:'حقنة',hint:'معرفة شكلها فقط دون تخويف الطفل.',sprite:'assets/sprites/professions.svg',symbol:'syringe'},
    {id:'helmet',category:'professions',ar:'خوذة عامل',hint:'أداة أمان مهمة في بعض المهن.',sprite:'assets/sprites/professions.svg',symbol:'helmet'},
    {id:'brush',category:'professions',ar:'فرشاة رسم',hint:'أداة جميلة في مهنة الفنان والرسم.',sprite:'assets/sprites/professions.svg',symbol:'brush'}
  ]
};
function toast(msg){var n=$('toast');if(!n)return;n.textContent=msg;n.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(function(){n.classList.remove('show')},2300)}
function safe(s){return String(s==null?'':s).replace(/[&<>\"]/g,function(ch){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[ch]||ch})}
function loadSettings(){try{var x=JSON.parse(localStorage.getItem(SETTINGS)||'{}');if(x.category)state.category=x.category;if(x.mode)state.mode=x.mode;if(x.scope)state.scope=x.scope;if(typeof x.speech==='boolean')state.speech=x.speech;if(x.speed)state.speed=parseInt(x.speed,10)||4000}catch(e){}}
function saveSettings(){try{localStorage.setItem(SETTINGS,JSON.stringify({category:state.category,mode:state.mode,scope:state.scope,speech:state.speech,speed:state.speed}))}catch(e){}}
function xhrText(url,done){try{var x=new XMLHttpRequest();x.open('GET',url,true);x.onreadystatechange=function(){if(x.readyState!==4)return;if((x.status>=200&&x.status<300)||x.status===0)done(null,x.responseText);else done(new Error('http '+x.status))};x.onerror=function(){done(new Error('network'))};x.send()}catch(e){done(e)}}
function loadData(done){xhrText('data/words.json?v=6',function(err,text){if(!err){try{var d=JSON.parse(text);if(d&&d.items&&d.items.length){done(d,false);return}}catch(e){}}done(FALLBACK,true)})}
function ensureSpriteBank(){var b=$('spriteBank');if(b)return b;b=document.createElementNS('http://www.w3.org/2000/svg','svg');b.setAttribute('id','spriteBank');b.setAttribute('aria-hidden','true');b.style.display='none';document.body.appendChild(b);return b}
function loadSprite(url,done){xhrText(url+'?v=6',function(err,text){if(err){spriteReady[url]=false;done();return}try{var p=new DOMParser().parseFromString(text,'image/svg+xml');var syms=p.getElementsByTagName('symbol'),bank=ensureSpriteBank();for(var i=0;i<syms.length;i++){var n=document.importNode?document.importNode(syms[i],true):syms[i].cloneNode(true);bank.appendChild(n)}spriteReady[url]=true}catch(e){spriteReady[url]=false}done()})}
function loadSprites(done){var urls=[],seen={};for(var i=0;i<items.length;i++){var u=items[i].sprite;if(u&&!seen[u]){seen[u]=1;urls.push(u)}}if(!urls.length){done();return}var left=urls.length;for(var j=0;j<urls.length;j++)loadSprite(urls[j],function(){left--;if(left===0)done()})}
function getCollection(){if(state.mode==='all'||state.scope==='all')return items;var out=[];for(var i=0;i<items.length;i++)if(items[i].category===state.category)out.push(items[i]);return out}
function current(){var c=getCollection();if(!c.length)return null;if(state.currentIndex>=c.length)state.currentIndex=0;if(state.currentIndex<0)state.currentIndex=c.length-1;return c[state.currentIndex]}
function useRef(item){return spriteReady[item.sprite]?'#'+item.symbol:item.sprite+'#'+item.symbol}
function renderCategories(){var box=$('categoryChips');if(!box)return;var h='';for(var i=0;i<categories.length;i++){var c=categories[i];h+='<button class="chip '+(state.category===c.id?'is-active':'')+'" type="button" data-category="'+safe(c.id)+'">'+safe(c.emoji)+' '+safe(c.label_ar)+'</button>'}box.innerHTML=h;var bs=box.querySelectorAll('[data-category]');for(var j=0;j<bs.length;j++)bs[j].onclick=function(){state.category=this.getAttribute('data-category');state.mode='category';state.currentIndex=0;saveSettings();restartAutoplay();render();if(state.speech)speakCurrent()}}
function thumbSvg(item){var r=useRef(item);return '<svg viewBox="0 0 800 800" aria-hidden="true"><use href="'+safe(r)+'" xlink:href="'+safe(r)+'"></use></svg>'}
function renderThumbs(c,it){var g=$('thumbGrid');if(!g)return;var h='';for(var i=0;i<c.length;i++){var x=c[i],cat=categoryById[x.category]||{};h+='<div class="thumb"><button type="button" class="'+(it&&it.id===x.id?'is-current':'')+'" data-thumb-index="'+i+'">'+thumbSvg(x)+'<strong>'+safe(x.ar)+'</strong><small>'+safe(cat.label_ar||'')+'</small></button></div>'}g.innerHTML=h;var bs=g.querySelectorAll('[data-thumb-index]');for(var j=0;j<bs.length;j++)bs[j].onclick=function(){state.currentIndex=parseInt(this.getAttribute('data-thumb-index'),10)||0;render();if(state.speech)speakCurrent()}}
function render(){renderCategories();var c=getCollection(),it=current();if(!it)return;var cat=categoryById[it.category]||{},ref=useRef(it),use=$('itemUse');use.setAttribute('href',ref);try{use.setAttributeNS('http://www.w3.org/1999/xlink','xlink:href',ref)}catch(e){}$('itemName').textContent=it.ar;$('itemHint').textContent=it.hint||'';$('categoryTag').textContent=(cat.emoji||'')+' '+(cat.label_ar||'');$('modeTag').textContent=state.mode==='all'?'عرض عام':'حسب التصنيف';$('playTag').textContent=state.autoplay?'تلقائي':'يدوي';$('positionMeta').textContent=(state.currentIndex+1)+' من '+c.length;$('scopeMeta').textContent=(state.mode==='all'||state.scope==='all')?'التنقل في كل التصنيفات':'التنقل داخل التصنيف';$('speechMeta').textContent=state.speech?'النطق مفعّل':'النطق متوقف';$('rangeLabel').textContent=(state.currentIndex+1)+' / '+c.length;$('itemRange').max=Math.max(c.length-1,0);$('itemRange').value=state.currentIndex;$('speechToggle').textContent=state.speech?'النطق مفعّل':'النطق متوقف';$('speechToggle').classList.toggle('is-active',state.speech);$('autoplayToggle').textContent=state.autoplay?'إيقاف التنقل التلقائي':'تشغيل التنقل التلقائي';$('autoplayToggle').classList.toggle('is-active',state.autoplay);$('autoplaySpeed').value=String(state.speed);var v=$('displayModeSegment').querySelectorAll('[data-mode]');for(var i=0;i<v.length;i++)v[i].classList.toggle('is-active',v[i].getAttribute('data-mode')===state.mode);var s=$('scopeSegment').querySelectorAll('[data-scope]');for(var j=0;j<s.length;j++)s[j].classList.toggle('is-active',s[j].getAttribute('data-scope')===state.scope);renderThumbs(c,it)}
function speakCurrent(force){var it=current();if(!it||(!state.speech&&!force))return;if(!('speechSynthesis'in window)||typeof SpeechSynthesisUtterance==='undefined'){toast('لا يتوفر نطق عربي على هذا الجهاز.');return}try{speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(it.ar);u.lang='ar-SA';u.rate=.76;u.pitch=1.02;var vs=speechSynthesis.getVoices?speechSynthesis.getVoices():[],voice=null;for(var i=0;i<vs.length;i++){if(/^ar(-|_)/i.test(vs[i].lang)){voice=vs[i];break}}if(voice)u.voice=voice;speechSynthesis.speak(u)}catch(e){toast('تعذر تشغيل النطق الآن.')}}
function move(n){var c=getCollection();if(!c.length)return;state.currentIndex=(state.currentIndex+n+c.length)%c.length;render();if(state.speech)speakCurrent()}function next(){move(1)}function prev(){move(-1)}
function restartAutoplay(){clearInterval(state.timer);state.timer=null;if(state.autoplay)state.timer=setInterval(next,state.speed)}
function bind(){$('prevBtn').onclick=prev;$('nextBtn').onclick=next;$('speakBtn').onclick=function(){speakCurrent(true)};$('speakCurrentThumb').onclick=function(){speakCurrent(true)};$('speechToggle').onclick=function(){state.speech=!state.speech;saveSettings();render();if(state.speech)speakCurrent()};$('autoplayToggle').onclick=function(){state.autoplay=!state.autoplay;restartAutoplay();render()};$('autoplaySpeed').onchange=function(){state.speed=parseInt(this.value,10)||4000;saveSettings();restartAutoplay()};$('itemRange').oninput=function(){state.currentIndex=parseInt(this.value,10)||0;render();if(state.speech)speakCurrent()};$('shuffleBtn').onclick=function(){state.mode='all';state.scope='all';state.currentIndex=Math.floor(Math.random()*Math.max(items.length,1));saveSettings();restartAutoplay();render();if(state.speech)speakCurrent()};$('fullscreenBtn').onclick=function(){if(!document.fullscreenElement){if(document.documentElement.requestFullscreen)document.documentElement.requestFullscreen();else toast('ملء الشاشة غير مدعوم.')}else if(document.exitFullscreen)document.exitFullscreen()};var v=$('displayModeSegment').querySelectorAll('[data-mode]');for(var i=0;i<v.length;i++)v[i].onclick=function(){state.mode=this.getAttribute('data-mode');state.currentIndex=0;saveSettings();restartAutoplay();render();if(state.speech)speakCurrent()};var s=$('scopeSegment').querySelectorAll('[data-scope]');for(var j=0;j<s.length;j++)s[j].onclick=function(){state.scope=this.getAttribute('data-scope');state.currentIndex=0;saveSettings();restartAutoplay();render();if(state.speech)speakCurrent()};var st=$('stage');st.addEventListener('touchstart',function(e){state.touchX=e.changedTouches[0].clientX},{passive:true});st.addEventListener('touchend',function(e){var dx=e.changedTouches[0].clientX-state.touchX;if(Math.abs(dx)<45)return;if(dx>0)prev();else next()},{passive:true});st.onclick=function(e){var t=e.target;while(t&&t!==st){if(t.tagName&&t.tagName.toLowerCase()==='button')return;t=t.parentNode}speakCurrent(true)};document.addEventListener('keydown',function(e){if(e.target&&/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='ArrowRight')prev();else if(e.key==='ArrowLeft')next()})}
function applyData(d,fallbackUsed){categories=d.categories||[];items=d.items||[];categoryById={};for(var i=0;i<categories.length;i++)categoryById[categories[i].id]=categories[i];if(!categoryById[state.category]&&categories[0])state.category=categories[0].id;render();loadSprites(function(){render();if(fallbackUsed)toast('تم تشغيل المكتبة بالبيانات الاحتياطية بنجاح.')})}
function init(){loadSettings();bind();loadData(function(d,fallbackUsed){applyData(d,fallbackUsed)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
