(function(){
'use strict';
var LEVELS=window.APP360_LEVELS||{};
var WORD_EMOJI=window.APP360_WORD_EMOJI||{};
var COLOR_WORDS=window.APP360_COLOR_WORDS||{};
var NUMBER_WORDS=window.APP360_NUMBER_WORDS||{};

var state={level:1,view:'category',category:'',scope:'current',index:0,speech:true,autoplay:false,speed:4000,timer:null,touchX:0};
var SETTINGS_KEY='app360:a1-first-words:viewer-v7';
var MAX_THUMBS=24;
var LEVEL_TITLES={1:'المستوى 1 — عمر 2',2:'المستوى 2 — عمر 3',3:'المستوى 3 — عمر 4',4:'المستوى 4 — عمر 5'};
var COLOR_THEMES=['#ddf5f1','#fff2cf','#e4f8d8','#e8eeff','#ffe5da','#eef3ff','#ffe9f1','#ebf9ff'];
var themeCache={};
var catalogCache={};
var audioEl=null;
var $=function(id){return document.getElementById(id)};
function toast(msg){var n=$('toast');if(!n)return;n.textContent=msg;n.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(function(){n.classList.remove('show')},2500)}
function loadSettings(){try{var x=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}');if(x&&typeof x==='object'){if(x.level)state.level=Math.max(1,Math.min(4,parseInt(x.level,10)||1));if(x.category)state.category=x.category;if(x.view)state.view=x.view;if(x.scope)state.scope=x.scope;if(typeof x.speech==='boolean')state.speech=x.speech;if(x.speed)state.speed=x.speed}}catch(e){}}
function saveSettings(){try{localStorage.setItem(SETTINGS_KEY,JSON.stringify({level:state.level,category:state.category,view:state.view,scope:state.scope,speech:state.speech,speed:state.speed}))}catch(e){}}
function slugify(s){return String(s||'').toLowerCase().replace(/[ً-ٟ]/g,'').replace(/\s+/g,'-').replace(/[^؀-ۿa-z0-9-]/g,'').replace(/-+/g,'-').replace(/^-|-$/g,'')}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(ch){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]})}
function getTheme(key){key=key||'default';if(themeCache[key])return themeCache[key];var idx=Math.abs(key.split('').reduce(function(a,c){return a+c.charCodeAt(0)},0))%COLOR_THEMES.length;var pairs=[['#ddf5f1','#fff2cf'],['#e4f8d8','#fff3d8'],['#e8eeff','#f5e9ff'],['#ffe5da','#fff5cc'],['#e0f1ff','#eef9ff'],['#edf7ff','#f3eeff'],['#eafcf5','#fef3db'],['#fff0f4','#eef8ff']][idx];return themeCache[key]={a:pairs[0],b:pairs[1]}}
function buildCatalog(level){if(catalogCache[level])return catalogCache[level];var merged=[],byKey={};for(var lv=1;lv<=level;lv++){var rows=LEVELS[String(lv)]||LEVELS[lv]||[];for(var r=0;r<rows.length;r++){var row=rows[r],key=row[0],emoji=row[1]||'🧠',words=String(row[2]||'').split('|'),bucket=byKey[key];if(!bucket){bucket=byKey[key]={id:slugify(key)||('cat-'+(merged.length+1)),name_ar:key,emoji:emoji,items:[],_seen:{}};merged.push(bucket)}for(var w=0;w<words.length;w++){var text=String(words[w]||'').trim();if(!text||bucket._seen[text])continue;bucket._seen[text]=true;bucket.items.push({id:slugify(key+'-'+text)||('item-'+bucket.items.length+1),ar:text,category:bucket.id,category_ar:key,emoji:emoji,introduced_level:lv,audio:''})}}}for(var i=0;i<merged.length;i++)delete merged[i]._seen;return catalogCache[level]={categories:merged}}
function currentCatalog(){return buildCatalog(state.level)}
function ensureCategory(){var cats=currentCatalog().categories||[];if(!cats.length){state.category='';return}var exists=false;for(var i=0;i<cats.length;i++){if(cats[i].id===state.category){exists=true;break}}if(!exists)state.category=cats[0].id}
function getCategories(){ensureCategory();return currentCatalog().categories}
function findCategory(){var cats=getCategories();for(var i=0;i<cats.length;i++)if(cats[i].id===state.category)return cats[i];return cats[0]||null}
function getCollection(){if(state.view==='all'||state.scope==='all'){var all=[];getCategories().forEach(function(cat){cat.items.forEach(function(item){all.push(item)})});return all}var cat=findCategory();return cat?cat.items:[]}
function currentItem(){var c=getCollection();if(!c.length)return null;if(state.index>=c.length)state.index=0;if(state.index<0)state.index=c.length-1;return c[state.index]}
function getHint(item){if(!item)return '';return 'التصنيف: '+item.category_ar+' · ظهر أولاً في '+LEVEL_TITLES[item.introduced_level].replace('المستوى ','المستوى ')}
function renderLevelTabs(){var box=$('levelTabs');var html='';for(var i=1;i<=4;i++){html+='<button type="button" class="level-tab '+(state.level===i?'is-active':'')+'" data-level="'+i+'">'+esc(String(i))+'</button>'}box.innerHTML=html;var btns=box.querySelectorAll('[data-level]');for(var j=0;j<btns.length;j++)btns[j].onclick=function(){state.level=parseInt(this.getAttribute('data-level'),10)||1;state.index=0;catalogCache={};ensureCategory();restartAutoplay();saveSettings();render();if(state.speech)speakCurrent()}}
function renderCategories(){var cats=getCategories();var html=cats.map(function(c){return '<button class="category-chip '+(state.category===c.id?'is-active':'')+'" type="button" data-category="'+esc(c.id)+'">'+esc(c.emoji)+' '+esc(c.name_ar)+'</button>'}).join('');$('categoryChips').innerHTML=html;var btns=$('categoryChips').querySelectorAll('[data-category]');for(var i=0;i<btns.length;i++)btns[i].onclick=function(){state.category=this.getAttribute('data-category');state.view='category';state.index=0;restartAutoplay();saveSettings();render();if(state.speech)speakCurrent()}}
function renderSwitches(){var v=$('viewSwitch').querySelectorAll('[data-view]');for(var i=0;i<v.length;i++)v[i].classList.toggle('is-active',v[i].getAttribute('data-view')===state.view);var s=$('scopeSwitch').querySelectorAll('[data-scope]');for(var j=0;j<s.length;j++)s[j].classList.toggle('is-active',s[j].getAttribute('data-scope')===state.scope)}
function visualMarkup(item){var w=item.ar||'';if(COLOR_WORDS[w]){var stroke=w==='أبيض'?'#9ca3af':'#ffffff';return '<circle cx="400" cy="350" r="155" fill="'+COLOR_WORDS[w]+'" stroke="'+stroke+'" stroke-width="16"/><circle cx="400" cy="350" r="110" fill="none" stroke="rgba(255,255,255,.55)" stroke-width="10"/>'}if(NUMBER_WORDS[w])return '<text x="400" y="430" text-anchor="middle" font-family="Arial,sans-serif" font-size="280" font-weight="800" fill="#0f8f8a">'+NUMBER_WORDS[w]+'</text>';if(w==='دائرة')return '<circle cx="400" cy="350" r="150" fill="#67c9be" stroke="#17343a" stroke-width="18"/>';if(w==='مربع')return '<rect x="250" y="200" width="300" height="300" rx="22" fill="#f2c84b" stroke="#17343a" stroke-width="18"/>';if(w==='مثلث')return '<path d="M400 170L580 500H220Z" fill="#f59e0b" stroke="#17343a" stroke-width="18"/>';if(w==='مستطيل')return '<rect x="190" y="250" width="420" height="220" rx="22" fill="#60a5fa" stroke="#17343a" stroke-width="18"/>';if(w==='بيضاوي')return '<ellipse cx="400" cy="350" rx="190" ry="125" fill="#a78bfa" stroke="#17343a" stroke-width="18"/>';if(w==='هلال')return '<path d="M470 180c-95 20-145 108-116 195 30 88 130 126 210 78-70 10-128-40-138-105-10-68 28-132 94-156-16-8-32-13-50-12z" fill="#facc15" stroke="#17343a" stroke-width="12"/>';if(w==='نجمة')return '<path d="M400 160l50 120 130 10-100 84 32 126-112-70-112 70 32-126-100-84 130-10z" fill="#facc15" stroke="#17343a" stroke-width="14"/>';if(w==='قلب')return '<path d="M400 515C250 420 210 350 238 274c28-76 126-88 162-22 36-66 134-54 162 22 28 76-12 146-162 241z" fill="#ef4444" stroke="#17343a" stroke-width="14"/>';var em=WORD_EMOJI[w]||item.emoji||'🧠';return '<text x="400" y="430" text-anchor="middle" font-size="230">'+esc(em)+'</text>'}
function svgForItem(item){if(item._img)return item._img;var theme=getTheme(item.category_ar);var title=esc(item.ar);var cat=esc(item.category_ar);var lv='المستوى '+item.introduced_level;var svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 800"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="'+theme.a+'"/><stop offset="100%" stop-color="'+theme.b+'"/></linearGradient></defs><rect width="800" height="800" rx="56" fill="url(#g)"/><rect x="40" y="40" width="720" height="720" rx="48" fill="#fff" opacity="0.94"/><rect x="104" y="90" width="592" height="510" rx="40" fill="#f7fbfb"/><rect x="125" y="116" width="190" height="56" rx="28" fill="#0f8f8a" opacity="0.13"/><text x="220" y="154" text-anchor="middle" font-family="Tahoma,Arial,sans-serif" font-size="28" fill="#0a6966">'+lv+'</text>'+visualMarkup(item)+'<text x="400" y="620" text-anchor="middle" font-family="Tahoma,Arial,sans-serif" font-size="54" fill="#17343a">'+title+'</text><rect x="180" y="660" width="440" height="58" rx="29" fill="#0f8f8a" opacity="0.10"/><text x="400" y="699" text-anchor="middle" font-family="Tahoma,Arial,sans-serif" font-size="28" fill="#38555b">'+cat+'</text></svg>';item._img='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);return item._img}
function thumbWindow(collection){var len=collection.length;if(len<=MAX_THUMBS)return {start:0,end:len};var start=Math.max(0,state.index-10);var end=start+MAX_THUMBS;if(end>len){end=len;start=Math.max(0,end-MAX_THUMBS)}return {start:start,end:end}}
function renderThumbs(collection,item){var meta=thumbWindow(collection);var slice=collection.slice(meta.start,meta.end);$('gridMeta').textContent='يعرض '+(meta.start+1)+'–'+meta.end+' من أصل '+collection.length+' كلمة في المسار الحالي.';$('thumbGrid').innerHTML=slice.map(function(x,offset){var ix=meta.start+offset;return '<button class="thumb-card '+(item&&item.id===x.id?'is-current':'')+'" type="button" data-index="'+ix+'"><img src="'+svgForItem(x)+'" alt="'+esc(x.ar)+'"><strong>'+esc(x.ar)+'</strong><small>'+esc(x.category_ar)+'</small></button>'}).join('');var btns=$('thumbGrid').querySelectorAll('[data-index]');for(var i=0;i<btns.length;i++)btns[i].onclick=function(){state.index=parseInt(this.getAttribute('data-index'),10)||0;render();if(state.speech)speakCurrent()}}
function render(){renderLevelTabs();renderCategories();renderSwitches();var categories=getCategories();var totalWords=categories.reduce(function(sum,c){return sum+c.items.length},0);$('levelTitle').textContent=LEVEL_TITLES[state.level];$('levelSummary').textContent=categories.length+' تصنيف · '+totalWords+' كلمة';var c=getCollection(),it=currentItem();if(!it){$('itemName').textContent='لا توجد كلمات';$('itemHint').textContent='';$('thumbGrid').innerHTML='';return}var cat=findCategory();$('itemImage').src=svgForItem(it);$('itemImage').alt=it.ar;$('itemName').textContent=it.ar;$('itemHint').textContent=getHint(it);$('levelTag').textContent=LEVEL_TITLES[state.level];$('categoryTag').textContent=(it.emoji||'🧠')+' '+it.category_ar;$('scopeTag').textContent=(state.view==='all'||state.scope==='all')?'كل كلمات المستوى':'داخل التصنيف';$('autoplayTag').textContent=state.autoplay?'تلقائي':'يدوي';$('itemRange').max=Math.max(c.length-1,0);$('itemRange').value=state.index;$('rangeLabel').textContent=(state.index+1)+' / '+c.length;$('visibleCount').textContent=c.length+' كلمة';$('speechToggle').textContent=state.speech?'الصوت مفعّل':'الصوت متوقف';$('speechToggle').classList.toggle('is-active',state.speech);$('autoplayToggle').textContent=state.autoplay?'إيقاف التنقل التلقائي':'تشغيل التنقل التلقائي';$('autoplayToggle').classList.toggle('is-active',state.autoplay);$('autoplaySpeed').value=String(state.speed);renderThumbs(c,it)}
function stopAudio(){try{if(audioEl){audioEl.pause();audioEl.currentTime=0}}catch(e){}try{if('speechSynthesis'in window)speechSynthesis.cancel()}catch(e){}}
function playBundledAudio(src){if(!src)return false;try{if(!audioEl)audioEl=new Audio();audioEl.src=src;audioEl.play().catch(function(){})}catch(e){return false}return true}
function speakWord(text){if(!('speechSynthesis'in window)||typeof SpeechSynthesisUtterance==='undefined')return false;try{speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(text);u.lang='ar-SA';u.rate=.78;u.pitch=1.02;var vs=speechSynthesis.getVoices?speechSynthesis.getVoices():[],voice=null;for(var i=0;i<vs.length;i++){if(/^ar(-|_)/i.test(vs[i].lang)){voice=vs[i];break}}if(voice)u.voice=voice;speechSynthesis.speak(u);return true}catch(e){return false}}
function speakCurrent(force){var it=currentItem();if(!it||(!state.speech&&!force))return;stopAudio();if(it.audio&&playBundledAudio(it.audio))return;if(speakWord(it.ar))return;toast('الصوت غير متاح على هذا الجهاز في هذه النسخة.')}
function move(step){var c=getCollection();if(!c.length)return;state.index=(state.index+step+c.length)%c.length;render();if(state.speech)speakCurrent()}
function next(){move(1)}function prev(){move(-1)}
function restartAutoplay(){clearInterval(state.timer);state.timer=null;if(state.autoplay)state.timer=setInterval(next,state.speed)}
function setView(v){state.view=v;state.index=0;restartAutoplay();saveSettings();render();if(state.speech)speakCurrent()}
function setScope(v){state.scope=v;state.index=0;restartAutoplay();saveSettings();render();if(state.speech)speakCurrent()}
function mixed(){state.view='all';state.scope='all';state.index=Math.floor(Math.random()*Math.max(getCollection().length,1));restartAutoplay();saveSettings();render();if(state.speech)speakCurrent()}
function fullscreen(){var d=document.documentElement;if(!document.fullscreenElement){if(d.requestFullscreen)d.requestFullscreen();else toast('ملء الشاشة غير مدعوم في هذا المتصفح.')}else if(document.exitFullscreen)document.exitFullscreen()}
function bind(){ $('prevBtn').onclick=prev; $('nextBtn').onclick=next; $('pictureButton').onclick=function(){speakCurrent(true)}; $('stageSpeakBtn').onclick=function(){speakCurrent(true)}; $('speakNowBtn').onclick=function(){speakCurrent(true)}; $('speechToggle').onclick=function(){state.speech=!state.speech;saveSettings();render();if(state.speech)speakCurrent()}; $('autoplayToggle').onclick=function(){state.autoplay=!state.autoplay;restartAutoplay();render()}; $('autoplaySpeed').onchange=function(){state.speed=parseInt(this.value,10)||4000;saveSettings();restartAutoplay()}; $('mixedBtn').onclick=mixed; $('fullscreenBtn').onclick=fullscreen; $('itemRange').oninput=function(){state.index=parseInt(this.value,10)||0;render();if(state.speech)speakCurrent()}; var v=$('viewSwitch').querySelectorAll('[data-view]');for(var i=0;i<v.length;i++)v[i].onclick=function(){setView(this.getAttribute('data-view'))}; var s=$('scopeSwitch').querySelectorAll('[data-scope]');for(var j=0;j<s.length;j++)s[j].onclick=function(){setScope(this.getAttribute('data-scope'))}; var stage=$('stage'); stage.addEventListener('touchstart',function(e){state.touchX=e.changedTouches[0].clientX},{passive:true}); stage.addEventListener('touchend',function(e){var dx=e.changedTouches[0].clientX-state.touchX;if(Math.abs(dx)<45)return;if(dx>0)prev();else next()},{passive:true}); stage.addEventListener('keydown',function(e){if(e.key==='ArrowRight'){e.preventDefault();prev()}else if(e.key==='ArrowLeft'){e.preventDefault();next()}else if((e.key==='Enter'||e.key===' ')&&state.speech){e.preventDefault();speakCurrent(true)}}); document.addEventListener('keydown',function(e){if(e.target&&/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='ArrowRight')prev();else if(e.key==='ArrowLeft')next()}) }
function init(){loadSettings();ensureCategory();bind();render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();