(function(){
'use strict';
var LEVELS=window.APP360_LEVELS||{};
var WORD_EMOJI=window.APP360_WORD_EMOJI||{};
var AUDIO_AR=window.APP360_AUDIO_MAP||{};
var AUDIO_AR_SENSE=window.APP360_AUDIO_SENSE_MAP||{};
var EN=window.APP360_EN||{categories:{},words:{}};
var AUDIO_EN=window.APP360_AUDIO_MAP_EN||{};
var WORD_IMAGES=window.APP360_WORD_IMAGE_MAP||{};
var WORD_IMAGE_CONTEXTS=window.APP360_WORD_IMAGE_CONTEXT_MAP||{};
var WORD_IMAGE_BASE='assets/word-images/';
var SEP='\u0001';
var UI={
 ar:{title:'كلماتي مع أشيائي',eyebrow:'مختبر التطبيق 360 · تعلم بالصورة والصوت',heroDesc:'اختر المستوى والتصنيف، شاهد الصورة، ثم استمع وسمِّ. ويمكن عرض العربية والإنجليزية معًا.',clearImage:'صورة واضحة',listenName:'استمع وسمِّ',displayLanguage:'لغة العرض',help:'تعليمات',settings:'الإعدادات',install:'تثبيت',update:'تحديث',chooseLevel:'اختر المستوى',categories:'التصنيفات',categoriesHint:'تصنيفات المستوى المختار تظهر أولًا. التصنيفات السابقة مجمعة أسفلها لتبقى الصفحة واضحة.',categoryView:'حسب التصنيف',randomView:'متنوع عشوائي 10',speakWord:'انطق الكلمة',cardsTitle:'بطاقات سريعة',previous:'السابق',next:'التالي',shuffle:'اختيار عشوائي',guide:'إرشاد مختصر للمرافق — اختياري',currentCats:'تصنيفات هذا المستوى',previousCats:'تصنيفات من المستويات السابقة',randomMode:'عشوائي',categoryMode:'تصنيف',audioAr:'العربية',audioEn:'English',audioBoth:'العربية ثم English'},
 en:{title:'My Words & Things',eyebrow:'App 360 Lab · Learn with pictures and sound',heroDesc:'Choose a level and category, see the picture, then listen and name it. Arabic and English can also be shown together.',clearImage:'Clear picture',listenName:'Listen & name',displayLanguage:'Display language',help:'Help',settings:'Settings',install:'Install',update:'Update',chooseLevel:'Choose level',categories:'Categories',categoriesHint:'Categories from the selected level appear first. Earlier levels are grouped below to keep the page clear.',categoryView:'By category',randomView:'10 random picks',speakWord:'Speak word',cardsTitle:'Quick cards',previous:'Previous',next:'Next',shuffle:'Random pick',guide:'Short guide for the adult — optional',currentCats:'This level',previousCats:'Earlier levels',randomMode:'Random',categoryMode:'Category',audioAr:'Arabic',audioEn:'English',audioBoth:'Arabic then English'}
};
var state={level:1,display:'ar',voice:'ar',view:'category',category:'',scope:'current',index:0,speech:true,autoplay:false,speed:4000,timer:null,touchX:0,randomPool:[]};
var SETTINGS='app360:say-name:v19';
var LEGACY18='app360:say-name:v18';
var LEGACY='app360:a1-first-words:viewer-v10';
var cache={},audioEl=null,speechSeq=0;
var $=function(id){return document.getElementById(id)};
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function slug(s){return String(s||'').replace(/\s+/g,'-').replace(/[^؀-ۿa-zA-Z0-9-]/g,'').replace(/-+/g,'-')}
function shuffle(a){for(var i=a.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),t=a[i];a[i]=a[j];a[j]=t}return a}
function toast(s){var n=$('toast');if(!n)return;n.textContent=s;n.className='toast show';clearTimeout(toast.t);toast.t=setTimeout(function(){n.className='toast'},2500)}
function englishReady(){return EN&&EN.words&&Object.keys(EN.words).length>10}
function uiLang(){return state.display==='en'?'en':'ar'}
function tr(){return UI[uiLang()]||UI.ar}
function enWord(it){return EN.words&&EN.words[it.category_ar+SEP+it.ar]?EN.words[it.category_ar+SEP+it.ar]:it.ar}
function enCat(ar){return EN.categories&&EN.categories[ar]?EN.categories[ar]:ar}
function labelWord(it){if(state.display==='en')return enWord(it);if(state.display==='both')return it.ar+' / '+enWord(it);return it.ar}
function wordHtml(it){if(state.display==='both')return '<span class="word-ar" lang="ar" dir="rtl">'+esc(it.ar)+'</span><span class="word-en" lang="en" dir="ltr">'+esc(enWord(it))+'</span>';if(state.display==='en')return '<span class="word-en" lang="en" dir="ltr">'+esc(enWord(it))+'</span>';return '<span class="word-ar" lang="ar" dir="rtl">'+esc(it.ar)+'</span>'}
function catHtml(ar){if(state.display==='both')return '<span lang="ar" dir="rtl">'+esc(ar)+'</span><span class="bilingual-sep"> / </span><span lang="en" dir="ltr">'+esc(enCat(ar))+'</span>';if(state.display==='en')return '<span lang="en" dir="ltr">'+esc(enCat(ar))+'</span>';return '<span lang="ar" dir="rtl">'+esc(ar)+'</span>'}
function loadSettings(){try{var raw=localStorage.getItem(SETTINGS)||localStorage.getItem(LEGACY18)||localStorage.getItem(LEGACY)||'{}',x=JSON.parse(raw);if(x.display)state.display=x.display;else if(x.lang)state.display=x.lang;if(x.voice)state.voice=x.voice;else state.voice=state.display;if(x.level)state.level=parseInt(x.level,10)||1;if(x.view==='category'||x.view==='random')state.view=x.view;if(x.scope)state.scope=x.scope;if(x.category)state.category=x.category;if(typeof x.speech==='boolean')state.speech=x.speech;if(typeof x.autoplay==='boolean')state.autoplay=x.autoplay;if(x.speed)state.speed=parseInt(x.speed,10)||4000}catch(e){}if((state.display==='en'||state.display==='both')&&!englishReady()){state.display='ar';state.voice='ar'}if((state.voice==='en'||state.voice==='both')&&!englishReady())state.voice='ar';if(state.view==='category'&&state.scope==='all')state.scope='current'}
function saveSettings(){try{localStorage.setItem(SETTINGS,JSON.stringify({display:state.display,voice:state.voice,level:state.level,view:state.view,scope:state.scope,category:state.category,speech:state.speech,autoplay:state.autoplay,speed:state.speed}))}catch(e){}}
function build(level){if(cache[level])return cache[level];var cats=[],by={};for(var lv=1;lv<=level;lv++){var rows=LEVELS[String(lv)]||[];for(var i=0;i<rows.length;i++){var r=rows[i],name=r[0],em=r[1]||'🧠',words=String(r[2]||'').split('|'),c=by[name];if(!c){c={id:slug(name)||('cat-'+cats.length),name:name,emoji:em,items:[],seen:{},levels:{}};by[name]=c;cats.push(c)}c.levels[lv]=true;for(var j=0;j<words.length;j++){var w=String(words[j]||'').replace(/^\s+|\s+$/g,'');if(!w||c.seen[w])continue;c.seen[w]=1;c.items.push({ar:w,category:c.id,category_ar:name,emoji:em,level:lv})}}}for(var k=0;k<cats.length;k++)delete cats[k].seen;cache[level]=cats;return cats}
function currentLevelNames(){var rows=LEVELS[String(state.level)]||[],o={},a=[];for(var i=0;i<rows.length;i++){var n=rows[i][0];if(!o[n]){o[n]=1;a.push(n)}}return a}
function preferredCategoryId(level){var rows=LEVELS[String(level)]||[];return rows.length?slug(rows[0][0]):''}
function cats(){var a=build(state.level);if(!state.category)state.category=preferredCategoryId(state.level)||(a[0]&&a[0].id)||'';var ok=false;for(var i=0;i<a.length;i++)if(a[i].id===state.category)ok=true;if(!ok)state.category=preferredCategoryId(state.level)||(a[0]&&a[0].id)||'';return a}
function currentCat(){var a=cats();for(var i=0;i<a.length;i++)if(a[i].id===state.category)return a[i];return a[0]||null}
function allItems(){var a=cats(),out=[];for(var i=0;i<a.length;i++)for(var j=0;j<a[i].items.length;j++)out.push(a[i].items[j]);return out}
function makeRandomPool(exclude){var groups=cats().slice(),picked=[],seen={};shuffle(groups);for(var i=0;i<groups.length&&picked.length<10;i++){var options=groups[i].items.filter(function(it){return it.ar!==exclude&&!seen[it.ar]});if(!options.length)continue;var it=options[Math.floor(Math.random()*options.length)];picked.push(it);seen[it.ar]=1}if(picked.length<10){var rest=shuffle(allItems().slice());for(i=0;i<rest.length&&picked.length<10;i++){if(rest[i].ar===exclude||seen[rest[i].ar])continue;picked.push(rest[i]);seen[rest[i].ar]=1}}state.randomPool=picked;state.index=0;return picked}
function collection(){if(state.view==='random'){if(!state.randomPool.length)makeRandomPool('');return state.randomPool}if(state.scope==='all')return allItems();var c=currentCat();return c?c.items:[]}
function item(){var a=collection();if(!a.length)return null;if(state.index>=a.length)state.index=0;if(state.index<0)state.index=a.length-1;return a[state.index]}
function contextKey(it){return it.category_ar+SEP+it.ar}
function fallbackImage(it){var em=WORD_EMOJI[it.ar]||it.emoji||'🧠',svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 800"><rect width="800" height="800" rx="54" fill="#eaf7f5"/><rect x="42" y="42" width="716" height="716" rx="46" fill="#fff"/><text x="400" y="475" text-anchor="middle" font-size="250">'+esc(em)+'</text></svg>';return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg)}
function image(it){var map=window.APP360_WORD_IMAGE_MAP||WORD_IMAGES,ctx=window.APP360_WORD_IMAGE_CONTEXT_MAP||WORD_IMAGE_CONTEXTS,key=contextKey(it),file=(ctx&&ctx[key])||(map&&map[it.ar]);return file?WORD_IMAGE_BASE+file:fallbackImage(it)}
function applyLanguage(){var t=tr(),isEn=state.display==='en';document.documentElement.lang=isEn?'en':'ar';document.documentElement.dir=isEn?'ltr':'rtl';document.body.setAttribute('data-display-language',state.display);var stage=$('stage');if(stage)stage.setAttribute('data-dir',isEn?'ltr':'rtl');document.title=t.title+' | App 360';var nodes=document.querySelectorAll('[data-i18n]');for(var i=0;i<nodes.length;i++){var key=nodes[i].getAttribute('data-i18n');if(t[key]!=null)nodes[i].textContent=t[key]}var btns=$('languageSwitch').querySelectorAll('[data-lang]');for(i=0;i<btns.length;i++)btns[i].className=btns[i].getAttribute('data-lang')===state.display?'is-active':''}
function scrollToStage(){var el=$('stage');if(!el)return;setTimeout(function(){try{el.scrollIntoView({behavior:'smooth',block:'start'})}catch(e){el.scrollIntoView(true)}},100)}
function renderLevels(){var h='';for(var i=1;i<=4;i++)h+='<button type="button" class="level-tab '+(state.level===i?'is-active':'')+'" data-level="'+i+'">'+i+'</button>';$('levelTabs').innerHTML=h;var b=$('levelTabs').querySelectorAll('[data-level]');for(var j=0;j<b.length;j++)b[j].onclick=function(){state.level=parseInt(this.getAttribute('data-level'),10)||1;state.category=preferredCategoryId(state.level);state.view='category';state.randomPool=[];state.index=0;saveSettings();render();if(state.speech)speak()}}
function catButton(c,current){return '<button type="button" class="category-chip '+(c.id===state.category&&state.view==='category'?'is-active':'')+'" data-cat="'+esc(c.id)+'"><span>'+esc(c.emoji)+'</span> '+catHtml(c.name)+'</button>'}
function renderCats(){var a=cats(),currentNames=currentLevelNames(),isCurrent={},current=[],previous=[];for(var i=0;i<currentNames.length;i++)isCurrent[currentNames[i]]=1;for(i=0;i<a.length;i++){if(isCurrent[a[i].name])current.push(a[i]);else previous.push(a[i])}var t=tr(),h='<div class="category-group current"><div class="category-group-title"><span class="dot"></span>'+esc(t.currentCats)+' '+state.level+'</div><div class="category-row">';for(i=0;i<current.length;i++)h+=catButton(current[i],true);h+='</div></div>';if(previous.length){h+='<details class="previous-categories"><summary>'+esc(t.previousCats)+' <small>('+previous.length+')</small></summary><div class="category-row">';for(i=0;i<previous.length;i++)h+=catButton(previous[i],false);h+='</div></details>'}$('categoryChips').innerHTML=h;var b=$('categoryChips').querySelectorAll('[data-cat]');for(var j=0;j<b.length;j++)b[j].onclick=function(){state.category=this.getAttribute('data-cat');state.view='category';state.scope='current';state.randomPool=[];state.index=0;saveSettings();render();if(state.speech)speak();scrollToStage()}}
function renderViewSwitch(){var b=$('viewSwitch').querySelectorAll('[data-view]');for(var i=0;i<b.length;i++)b[i].className=b[i].getAttribute('data-view')===state.view?'is-active':''}
function renderThumbs(a){var start=0,end=a.length;if(state.view!=='random'){start=Math.max(0,state.index-4);end=Math.min(a.length,start+10);if(end-start<10)start=Math.max(0,end-10)}var h='';for(var i=start;i<end;i++)h+='<button type="button" class="thumb-card '+(i===state.index?'is-current':'')+'" data-i="'+i+'"><img loading="lazy" src="'+image(a[i])+'" alt="'+esc(labelWord(a[i]))+'"><strong>'+wordHtml(a[i])+'</strong><small>'+catHtml(a[i].category_ar)+'</small></button>';$('thumbGrid').innerHTML=h;var b=$('thumbGrid').querySelectorAll('[data-i]');for(var j=0;j<b.length;j++)b[j].onclick=function(){state.index=parseInt(this.getAttribute('data-i'),10)||0;render();if(state.speech)speak();scrollToStage()};if(state.view==='random')$('gridMeta').textContent=state.display==='en'?'10 random picks from different categories.':'10 اختيارات عشوائية من تصنيفات متنوعة.';else $('gridMeta').textContent=state.display==='en'?'Choose any card to jump directly to it.':'اختر أي بطاقة للانتقال إليها مباشرة.'}
function voiceLabel(){var t=tr();return state.voice==='both'?t.audioBoth:(state.voice==='en'?t.audioEn:t.audioAr)}
function render(){applyLanguage();renderLevels();renderCats();renderViewSwitch();var ca=cats(),total=0;for(var i=0;i<ca.length;i++)total+=ca[i].items.length;if(state.display==='en'){$('levelTitle').textContent='Level '+state.level;$('levelSummary').textContent=ca.length+' categories · '+total+' words'}else if(state.display==='both'){$('levelTitle').textContent='المستوى '+state.level+' / Level '+state.level;$('levelSummary').textContent=ca.length+' تصنيف · '+total+' كلمة / '+ca.length+' categories · '+total+' words'}else{$('levelTitle').textContent='المستوى '+state.level;$('levelSummary').textContent=ca.length+' تصنيف · '+total+' كلمة'}var a=collection(),it=item();if(!it)return;$('itemImage').src=image(it);$('itemImage').alt=labelWord(it);$('itemName').innerHTML=wordHtml(it);if(state.display==='both')$('itemHint').innerHTML='<span class="hint-line" lang="ar" dir="rtl">'+esc(it.category_ar)+' · ظهر أولًا في المستوى '+it.level+'</span><span class="hint-line hint-en" lang="en" dir="ltr">'+esc(enCat(it.category_ar))+' · First introduced in Level '+it.level+'</span>';else $('itemHint').textContent=(state.display==='en'?enCat(it.category_ar):it.category_ar)+' · '+(state.display==='en'?'Level ':'المستوى ')+it.level;$('levelTag').textContent=(state.display==='en'?'Level ':'المستوى ')+state.level;$('categoryTag').innerHTML='<span>'+esc(it.emoji)+'</span> '+catHtml(it.category_ar);$('modeTag').textContent=state.view==='random'?tr().randomMode:tr().categoryMode;$('voiceTag').textContent='🔊 '+voiceLabel();$('itemRange').max=Math.max(0,a.length-1);$('itemRange').value=state.index;$('rangeLabel').textContent=(state.index+1)+' / '+a.length;if(state.display==='en')$('visibleCount').textContent=a.length+' '+(a.length===1?'word':'words');else if(state.display==='both')$('visibleCount').textContent=a.length+' كلمة / '+a.length+' words';else $('visibleCount').textContent=a.length+' كلمة';renderThumbs(a);saveSettings()}
function stopAudio(){speechSeq++;try{if(audioEl){audioEl.pause();audioEl.currentTime=0;audioEl.onerror=null;audioEl.onended=null}}catch(e){}try{if(window.speechSynthesis)window.speechSynthesis.cancel()}catch(e){}}
function spokenText(it,lang){if(lang==='en')return enWord(it);var k=contextKey(it);if(k==='الجسم'+SEP+'ظهر')return 'ظَهْر';if(k==='الوقت'+SEP+'ظهر')return 'ظُهْر';return it.ar}
function audioPath(it,lang){if(lang==='en'){var e=enWord(it);return AUDIO_EN[e]||''}return AUDIO_AR_SENSE[contextKey(it)]||AUDIO_AR[it.ar]||''}
function ttsOne(it,lang,token,done){if(token!==speechSeq)return;if(!window.speechSynthesis||typeof window.SpeechSynthesisUtterance==='undefined'){done();return}try{var u=new SpeechSynthesisUtterance(spokenText(it,lang));u.lang=lang==='en'?'en-US':'ar-SA';u.rate=.78;var finished=false,next=function(){if(finished)return;finished=true;if(token===speechSeq)done()};u.onend=next;u.onerror=next;window.speechSynthesis.speak(u)}catch(e){done()}}
function playOne(it,lang,token,done){if(token!==speechSeq)return;var src=audioPath(it,lang);if(!src){ttsOne(it,lang,token,done);return}try{if(!audioEl)audioEl=new Audio();var finished=false,next=function(){if(finished)return;finished=true;if(token===speechSeq)done()};audioEl.onerror=function(){if(finished)return;finished=true;ttsOne(it,lang,token,done)};audioEl.onended=next;audioEl.src=src;if(audioEl.load)audioEl.load();var p=audioEl.play();if(p&&p.catch)p.catch(function(){if(finished)return;finished=true;ttsOne(it,lang,token,done)})}catch(e){ttsOne(it,lang,token,done)}}
function speak(){var it=item();if(!it||!state.speech)return;stopAudio();var token=speechSeq,langs=state.voice==='both'?['ar','en']:[state.voice==='en'?'en':'ar'],pos=0;function next(){if(token!==speechSeq||pos>=langs.length)return;playOne(it,langs[pos++],token,next)}next()}
function randomJump(){var cur=item();makeRandomPool(cur&&cur.ar||'');render();if(state.speech)speak()}function shuffleCurrent(){if(state.view==='random'){randomJump();return}var a=collection();if(!a.length)return;if(a.length===1){render();if(state.speech)speak();return}var old=state.index,next=old;while(next===old)next=Math.floor(Math.random()*a.length);state.index=next;render();if(state.speech)speak()}
function move(n){if(state.view==='random'){randomJump();return}var a=collection();if(!a.length)return;state.index=(state.index+n+a.length)%a.length;render();if(state.speech)speak()}
function restart(){clearInterval(state.timer);state.timer=null;if(state.autoplay)state.timer=setInterval(function(){move(1)},state.speed)}
function setDisplay(mode){if((mode==='en'||mode==='both')&&!englishReady()){toast('ملفات الإنجليزية لم تكتمل بعد.');return}state.display=mode;state.voice=mode;state.index=0;saveSettings();render();if(state.speech)speak()}
function activateRandom(){state.view='random';makeRandomPool(item()&&item().ar||'');saveSettings();render();if(state.speech)speak()}
function setView(mode){if(mode==='random'){activateRandom();return}state.view='category';state.scope='current';state.randomPool=[];state.index=0;saveSettings();render();if(state.speech)speak()}
function openStageFullscreen(){var el=$('stage');try{if(document.fullscreenElement){document.exitFullscreen();return}if(el.requestFullscreen)el.requestFullscreen();else if(el.webkitRequestFullscreen)el.webkitRequestFullscreen();else if(document.documentElement.requestFullscreen)document.documentElement.requestFullscreen()}catch(e){}}
function modalHtml(){return '<div class="settings-sheet">'+
'<div class="setting-block"><span class="setting-title">🔊 لغة النطق</span><p>يمكن أن تختلف لغة النطق عن لغة النص المعروض.</p><div class="modal-choice" id="modalVoice"><button data-voice="ar">العربية</button><button data-voice="en">English</button><button data-voice="both">العربية + English</button></div></div>'+
'<div class="setting-block"><div class="setting-line"><label class="setting-check"><input id="modalSpeech" type="checkbox"> تشغيل الصوت</label><label class="setting-check"><input id="modalAutoplay" type="checkbox"> تنقل تلقائي</label></div></div>'+
'<div class="setting-block"><div class="setting-line"><span class="setting-title">سرعة التنقل</span><select id="modalSpeed"><option value="2500">سريع</option><option value="4000">متوسط</option><option value="6000">هادئ</option></select></div></div>'+
'<div class="setting-block"><span class="setting-title">نطاق التنقل العادي</span><div class="modal-choice" id="modalScope"><button data-scope="current">التصنيف الحالي</button><button data-scope="all">كل كلمات المستوى</button></div></div>'+
'</div>'}
function syncModal(){var root=document.querySelector('.swal2-popup');if(!root)return;var vb=root.querySelectorAll('[data-voice]');for(var i=0;i<vb.length;i++)vb[i].className=vb[i].getAttribute('data-voice')===state.voice?'is-active':'';var sb=root.querySelectorAll('[data-scope]');for(i=0;i<sb.length;i++)sb[i].className=sb[i].getAttribute('data-scope')===state.scope?'is-active':'';var sp=root.querySelector('#modalSpeech'),ap=root.querySelector('#modalAutoplay'),speed=root.querySelector('#modalSpeed');if(sp)sp.checked=state.speech;if(ap)ap.checked=state.autoplay;if(speed)speed.value=String(state.speed)}
function openSettings(){if(!window.Swal){toast('تعذر فتح الإعدادات المتقدمة الآن.');return}Swal.fire({title:'⚙ الإعدادات المتقدمة',html:modalHtml(),showCloseButton:true,confirmButtonText:'تم',customClass:{popup:'app360-settings'},didOpen:function(){syncModal();var root=document.querySelector('.swal2-popup');var vb=root.querySelectorAll('[data-voice]');for(var i=0;i<vb.length;i++)vb[i].onclick=function(){var m=this.getAttribute('data-voice');if((m==='en'||m==='both')&&!englishReady()){toast('ملفات الإنجليزية لم تكتمل بعد.');return}state.voice=m;saveSettings();syncModal();render();if(state.speech)speak()};var sb=root.querySelectorAll('[data-scope]');for(i=0;i<sb.length;i++)sb[i].onclick=function(){state.scope=this.getAttribute('data-scope');if(state.view!=='random')state.index=0;saveSettings();syncModal();render()};var sp=root.querySelector('#modalSpeech');sp.onchange=function(){state.speech=this.checked;if(!state.speech)stopAudio();saveSettings();syncModal();render();if(state.speech)speak()};var ap=root.querySelector('#modalAutoplay');ap.onchange=function(){state.autoplay=this.checked;saveSettings();restart();syncModal();render()};var speed=root.querySelector('#modalSpeed');speed.onchange=function(){state.speed=parseInt(this.value,10)||4000;saveSettings();restart();syncModal()}}})}

function helpContent(kind){if(kind==='child')return '<div class="help-card"><b>👧 للطفل الذي يقرأ ويفهم التعليمات</b><ol><li>اختر المستوى.</li><li>اختر مجموعة تحبها مثل الحيوانات أو الطعام.</li><li>انظر إلى الصورة وحاول أن تقول اسمها قبل سماع الصوت.</li><li>اضغط 🔊 لتسمع الاسم، ثم كرره بصوتك.</li><li>استخدم التالي والسابق، أو جرّب 🎲 المتنوع العشوائي.</li></ol><p>الفكرة: انظر ← فكّر ← سمِّ ← استمع ← كرّر.</p></div>';return '<div class="help-card"><b>👨‍👩‍👧 للمربي أو المعلم</b><ol><li>اختر المستوى المناسب، وسيفتح أول تصنيف خاص به مباشرة.</li><li>دع الطفل ينظر للصورة ويشير أو يسمي قبل تشغيل الصوت.</li><li>شغّل النطق عند الحاجة، ويمكن اختيار العربية أو English أو كليهما من الإعدادات.</li><li>اربط البطاقة بشيء حقيقي كلما أمكن.</li><li>استخدم المتنوع العشوائي للمراجعة، وليس كبداية للتعلم.</li></ol><p>جلسات قصيرة ومتكررة أفضل من جلسة طويلة أو تحويل النشاط إلى اختبار.</p></div>'}
function openHelp(){if(!window.Swal){toast('التعليمات غير متاحة الآن.');return}var selected='adult';Swal.fire({title:'❓ كيف نستخدم التطبيق؟',html:'<div class="help-sheet"><div class="help-tabs"><button class="is-active" data-help="adult">للمربي والمعلم</button><button data-help="child">للطفل الواعي</button></div><div id="helpBody" class="help-body">'+helpContent('adult')+'</div></div>',showCloseButton:true,showCancelButton:true,confirmButtonText:'ابدأ جولة داخل التطبيق',cancelButtonText:'إغلاق',customClass:{popup:'app360-help'},didOpen:function(){var root=document.querySelector('.swal2-popup'),btns=root.querySelectorAll('[data-help]'),body=root.querySelector('#helpBody');for(var i=0;i<btns.length;i++)btns[i].onclick=function(){selected=this.getAttribute('data-help');for(var j=0;j<btns.length;j++)btns[j].className=btns[j]===this?'is-active':'';body.innerHTML=helpContent(selected)}}}).then(function(r){if(r.isConfirmed)runTour(0,selected)})}
function clearTourTarget(){var n=document.querySelector('.tour-target');if(n)n.classList.remove('tour-target')}
function runTour(index,kind){if(!window.Swal)return;var steps=kind==='child'?[{s:'#levelTabs',t:'1. اختر المستوى',d:'اضغط على رقم المستوى الذي تريد أن تتعلم منه.'},{s:'#categoryChips',t:'2. اختر التصنيف',d:'اختر الحيوانات أو الطعام أو أي مجموعة أخرى تحبها.'},{s:'#stage',t:'3. انظر وسمِّ',d:'انظر للصورة أولًا وحاول قول الاسم بنفسك.'},{s:'#stageSpeakBtn',t:'4. استمع',d:'اضغط زر الصوت واسمع الكلمة ثم كررها.'},{s:'.bottom-nav',t:'5. تنقّل والعب',d:'استخدم السابق والتالي، أو زر الاختيار العشوائي للمراجعة.'}]:[{s:'#levelTabs',t:'1. اختر المستوى',d:'ابدأ بالمستوى الذي تريد تدريبه. عند تغييره يفتح أول تصنيف خاص به مباشرة.'},{s:'#categoryChips',t:'2. اختر التصنيف',d:'ابدأ بتصنيف واحد. بعد اختياره سينتقل التطبيق تلقائيًا إلى بطاقة التعلم.'},{s:'#stage',t:'3. الممارسة',d:'دع المتعلم ينظر ويشير أو يسمي قبل تشغيل النطق.'},{s:'#stageSpeakBtn',t:'4. استخدم الصوت بوعي',d:'شغّل النطق بعد محاولة المتعلم. يمكن تخصيص لغة النطق من الإعدادات.'},{s:'#viewSwitch',t:'5. المراجعة العشوائية',d:'بعد التعلم استخدم متنوع عشوائي 10 للمراجعة بين تصنيفات مختلفة.'},{s:'#advancedSettingsBtn',t:'6. الإعدادات المتقدمة',d:'اضبط لغة النطق والتشغيل التلقائي والسرعة ونطاق التنقل عند الحاجة.'}];if(index<0||index>=steps.length){clearTourTarget();return}clearTourTarget();var step=steps[index],target=document.querySelector(step.s);if(target){try{target.scrollIntoView({behavior:'smooth',block:'center'})}catch(e){}target.classList.add('tour-target')}setTimeout(function(){Swal.fire({title:step.t,text:step.d,showCloseButton:true,showDenyButton:index>0,confirmButtonText:index===steps.length-1?'إنهاء':'التالي',denyButtonText:'السابق',allowOutsideClick:false,customClass:{popup:'app360-help'}}).then(function(r){clearTourTarget();if(r.isConfirmed){if(index===steps.length-1)return;runTour(index+1,kind)}else if(r.isDenied)runTour(index-1,kind)})},220)}
function checkForUpdate(manual){if(!('serviceWorker' in navigator))return;navigator.serviceWorker.getRegistration('./').then(function(reg){if(!reg)return;reg.update().then(function(){if(reg.waiting)try{reg.waiting.postMessage({type:'SKIP_WAITING'})}catch(e){}if(manual){toast('جارٍ تحديث التطبيق إلى أحدث نسخة…');setTimeout(function(){location.reload()},900)}}).catch(function(){if(manual)toast('تعذر التحقق من التحديث الآن.')})})}
function initUpdateSystem(){if(!('serviceWorker' in navigator))return;var reloading=false;navigator.serviceWorker.addEventListener('controllerchange',function(){if(reloading)return;reloading=true;setTimeout(function(){location.reload()},160)});setTimeout(function(){checkForUpdate(false)},700);window.addEventListener('focus',function(){checkForUpdate(false)});document.addEventListener('visibilitychange',function(){if(!document.hidden)checkForUpdate(false)});var u=$('updateAppBtn');if(u)u.addEventListener('click',function(){checkForUpdate(true)},true)}

function bind(){var lb=$('languageSwitch').querySelectorAll('[data-lang]');for(var q=0;q<lb.length;q++)lb[q].onclick=function(){setDisplay(this.getAttribute('data-lang'))};var vw=$('viewSwitch').querySelectorAll('[data-view]');for(q=0;q<vw.length;q++)vw[q].onclick=function(){setView(this.getAttribute('data-view'))};$('helpBtn').onclick=openHelp;$('advancedSettingsBtn').onclick=openSettings;$('prevBtn').onclick=function(){move(-1)};$('nextBtn').onclick=function(){move(1)};$('bottomPrevBtn').onclick=function(){move(-1)};$('bottomNextBtn').onclick=function(){move(1)};$('bottomShuffleBtn').onclick=shuffleCurrent;$('pictureButton').onclick=speak;$('stageSpeakBtn').onclick=speak;$('stageFullscreenBtn').onclick=openStageFullscreen;$('itemRange').oninput=function(){state.index=parseInt(this.value,10)||0;render();if(state.speech)speak()};var st=$('stage');st.addEventListener('touchstart',function(e){state.touchX=e.changedTouches[0].clientX},{passive:true});st.addEventListener('touchend',function(e){var dx=e.changedTouches[0].clientX-state.touchX;if(Math.abs(dx)<45)return;if(dx>0)move(-1);else move(1)},{passive:true});document.addEventListener('keydown',function(e){if(e.target&&/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='ArrowLeft')move(-1);else if(e.key==='ArrowRight')move(1)})}
function init(){loadSettings();state.category=state.category||preferredCategoryId(state.level);bind();render();restart();initUpdateSystem()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
