(function(){
'use strict';
var FALLBACK={"1":[["الأسرة","👪","أم|أب|طفل|ولد|بنت|أخ|أخت|جد|جدة|عائلة"],["الجسم","🙂","رأس|شعر|وجه|عين|أنف|فم|أذن|أسنان|لسان|يد|إصبع|قدم|بطن|ظهر"],["الملابس","👕","قميص|بنطال|فستان|حذاء|جورب|قبعة|جاكيت"],["غرفة الطفل","🧸","سرير|وسادة|بطانية|لعبة|دمية|كرة|كتاب|كرسي|طاولة|صندوق|باب|نافذة|مصباح"],["المنزل","🏠","بيت|غرفة|مطبخ|حمام|صالة|درج|مفتاح|جدار|أرض|سقف"],["المطبخ","🍽️","كوب|كأس|طبق|ملعقة|شوكة|سكين|قدر|إبريق|زجاجة|ثلاجة"],["الحمام","🛁","ماء|صابون|منشفة|فرشاة|معجون|مرآة"],["الطعام","🍲","خبز|أرز|بيض|جبن|حليب|ماء|عصير|كعك|بسكويت|شوربة"],["الفواكه","🍎","تفاح|موز|برتقال|عنب|فراولة|بطيخ|مانجو|تمر"],["الخضروات","🥕","طماطم|بطاطس|جزر|خيار|بصل|خس|فلفل"],["الحيوانات","🐾","قطة|كلب|طائر|سمكة|أرنب|دجاجة|بقرة|حصان|خروف|ماعز|أسد|فيل|قرد"],["الحشرات","🦋","نملة|نحلة|فراشة"],["وسائل النقل","🚗","سيارة|حافلة|شاحنة|دراجة|قطار|طائرة|سفينة|قارب"],["الطبيعة","🌞","شمس|قمر|نجم|سماء|سحابة|مطر|شجرة|زهرة|عشب|حجر|بحر"],["الألوان","🎨","أحمر|أزرق|أصفر|أخضر|أبيض|أسود"],["الأشكال","🔷","دائرة|مربع|مثلث|نجمة|قلب"],["الألعاب","🧩","كرة|مكعب|دمية|سيارة|بالون|أحجية|طبلة"],["أشياء يومية","👜","هاتف|ساعة|حقيبة|قلم|ورقة|كتاب|صورة|مفتاح|مظلة|نظارة"]]};
var LEVELS=window.APP360_LEVELS||FALLBACK;
var WORD_EMOJI=window.APP360_WORD_EMOJI||{};
var COLORS={'أحمر':'#ef4444','أزرق':'#3b82f6','أصفر':'#facc15','أخضر':'#22c55e','أبيض':'#ffffff','أسود':'#111827','برتقالي':'#f97316','بنفسجي':'#8b5cf6','وردي':'#ec4899','بني':'#92400e','رمادي':'#6b7280'};
var NUMBERS={'صفر':'0','واحد':'1','اثنان':'2','ثلاثة':'3','أربعة':'4','خمسة':'5','ستة':'6','سبعة':'7','ثمانية':'8','تسعة':'9','عشرة':'10'};
var state={level:1,view:'category',category:'',scope:'current',index:0,speech:true,autoplay:false,speed:4000,timer:null,touchX:0};
var cache={};
var $=function(id){return document.getElementById(id)};
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function slug(s){return String(s||'').replace(/\s+/g,'-').replace(/[^؀-ۿa-zA-Z0-9-]/g,'').replace(/-+/g,'-')}
function toast(s){var n=$('toast');if(!n)return;n.innerHTML=esc(s);n.className='toast show';clearTimeout(toast.t);toast.t=setTimeout(function(){n.className='toast'},2200)}
function tryLoadFullData(){if(window.APP360_LEVELS&&window.APP360_LEVELS['2']){LEVELS=window.APP360_LEVELS;return}try{var x=new XMLHttpRequest();x.open('GET','data/levels-inline-v8.js?v=8',false);x.send(null);if((x.status>=200&&x.status<300)||x.status===0){(0,eval)(x.responseText);if(window.APP360_LEVELS)LEVELS=window.APP360_LEVELS}}catch(e){}}
function build(level){if(cache[level])return cache[level];var cats=[],by={};for(var lv=1;lv<=level;lv++){var rows=LEVELS[String(lv)]||[];for(var i=0;i<rows.length;i++){var r=rows[i],name=r[0],em=r[1]||'🧠',words=String(r[2]||'').split('|'),c=by[name];if(!c){c={id:slug(name)||('cat-'+cats.length),name:name,emoji:em,items:[],seen:{}};by[name]=c;cats.push(c)}for(var j=0;j<words.length;j++){var w=String(words[j]||'').replace(/^\s+|\s+$/g,'');if(!w||c.seen[w])continue;c.seen[w]=1;c.items.push({ar:w,category:c.id,category_ar:name,emoji:em,level:lv})}}}for(var k=0;k<cats.length;k++)delete cats[k].seen;cache[level]=cats;return cats}
function cats(){var a=build(state.level);if(!state.category&&a[0])state.category=a[0].id;var ok=false;for(var i=0;i<a.length;i++)if(a[i].id===state.category)ok=true;if(!ok&&a[0])state.category=a[0].id;return a}
function currentCat(){var a=cats();for(var i=0;i<a.length;i++)if(a[i].id===state.category)return a[i];return a[0]||null}
function collection(){var a=cats(),out=[],i,j;if(state.view==='all'||state.scope==='all'){for(i=0;i<a.length;i++)for(j=0;j<a[i].items.length;j++)out.push(a[i].items[j]);return out}var c=currentCat();return c?c.items:[]}
function item(){var a=collection();if(!a.length)return null;if(state.index>=a.length)state.index=0;if(state.index<0)state.index=a.length-1;return a[state.index]}
function visual(it){var w=it.ar,em=WORD_EMOJI[w]||it.emoji||'🧠';if(COLORS[w])return '<circle cx="400" cy="350" r="155" fill="'+COLORS[w]+'" stroke="#9ca3af" stroke-width="14"/>';if(NUMBERS[w])return '<text x="400" y="435" text-anchor="middle" font-family="Arial" font-size="280" font-weight="700" fill="#0f8f8a">'+NUMBERS[w]+'</text>';if(w==='دائرة')return '<circle cx="400" cy="350" r="150" fill="#67c9be"/>';if(w==='مربع')return '<rect x="250" y="200" width="300" height="300" fill="#f2c84b"/>';if(w==='مثلث')return '<path d="M400 170L580 500H220Z" fill="#f59e0b"/>';if(w==='نجمة')return '<text x="400" y="430" text-anchor="middle" font-size="250">⭐</text>';if(w==='قلب')return '<text x="400" y="430" text-anchor="middle" font-size="250">❤️</text>';return '<text x="400" y="430" text-anchor="middle" font-size="220">'+esc(em)+'</text>'}
function image(it){var svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 800"><rect width="800" height="800" rx="54" fill="#eaf7f5"/><rect x="42" y="42" width="716" height="716" rx="46" fill="#fff"/><rect x="105" y="105" width="590" height="500" rx="38" fill="#f7fbfb"/>'+visual(it)+'<text x="400" y="630" text-anchor="middle" font-family="Tahoma,Arial" font-size="58" fill="#17343a">'+esc(it.ar)+'</text><text x="400" y="700" text-anchor="middle" font-family="Tahoma,Arial" font-size="28" fill="#527076">'+esc(it.category_ar)+'</text></svg>';return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg)}
function renderLevels(){var h='';for(var i=1;i<=4;i++)h+='<button type="button" class="level-tab '+(state.level===i?'is-active':'')+'" data-level="'+i+'">'+i+'</button>';$('levelTabs').innerHTML=h;var b=$('levelTabs').querySelectorAll('[data-level]');for(var j=0;j<b.length;j++)b[j].onclick=function(){state.level=parseInt(this.getAttribute('data-level'),10)||1;state.index=0;state.category='';render();if(state.speech)speak()}}
function renderCats(){var a=cats(),h='';for(var i=0;i<a.length;i++)h+='<button type="button" class="category-chip '+(a[i].id===state.category?'is-active':'')+'" data-cat="'+esc(a[i].id)+'">'+esc(a[i].emoji)+' '+esc(a[i].name)+'</button>';$('categoryChips').innerHTML=h;var b=$('categoryChips').querySelectorAll('[data-cat]');for(var j=0;j<b.length;j++)b[j].onclick=function(){state.category=this.getAttribute('data-cat');state.view='category';state.index=0;render();if(state.speech)speak()}}
function renderThumbs(a,it){var start=Math.max(0,state.index-8),end=Math.min(a.length,start+20);if(end-start<20)start=Math.max(0,end-20);var h='';for(var i=start;i<end;i++)h+='<button type="button" class="thumb-card '+(i===state.index?'is-current':'')+'" data-i="'+i+'"><img src="'+image(a[i])+'" alt="'+esc(a[i].ar)+'"><strong>'+esc(a[i].ar)+'</strong><small>'+esc(a[i].category_ar)+'</small></button>';$('thumbGrid').innerHTML=h;var b=$('thumbGrid').querySelectorAll('[data-i]');for(var j=0;j<b.length;j++)b[j].onclick=function(){state.index=parseInt(this.getAttribute('data-i'),10)||0;render();if(state.speech)speak()};$('gridMeta').innerHTML='يعرض '+(start+1)+'–'+end+' من أصل '+a.length+' كلمة.'}
function render(){renderLevels();renderCats();var ca=cats(),total=0;for(var i=0;i<ca.length;i++)total+=ca[i].items.length;$('levelTitle').innerHTML='المستوى '+state.level+' — عمر '+(state.level+1);$('levelSummary').innerHTML=ca.length+' تصنيف · '+total+' كلمة';var a=collection(),it=item();if(!it)return;$('itemImage').src=image(it);$('itemImage').alt=it.ar;$('itemName').innerHTML=esc(it.ar);$('itemHint').innerHTML='التصنيف: '+esc(it.category_ar)+' · ظهر أولًا في المستوى '+it.level;$('levelTag').innerHTML='المستوى '+state.level;$('categoryTag').innerHTML=esc(it.emoji)+' '+esc(it.category_ar);$('scopeTag').innerHTML=(state.view==='all'||state.scope==='all')?'كل كلمات المستوى':'داخل التصنيف';$('autoplayTag').innerHTML=state.autoplay?'تلقائي':'يدوي';$('itemRange').max=Math.max(0,a.length-1);$('itemRange').value=state.index;$('rangeLabel').innerHTML=(state.index+1)+' / '+a.length;$('visibleCount').innerHTML=a.length+' كلمة';$('speechToggle').innerHTML=state.speech?'الصوت مفعّل':'الصوت متوقف';$('speechToggle').className='toggle'+(state.speech?' is-active':'');$('autoplayToggle').innerHTML=state.autoplay?'إيقاف التنقل التلقائي':'تشغيل التنقل التلقائي';$('autoplayToggle').className='toggle'+(state.autoplay?' is-active':'');var vb=$('viewSwitch').querySelectorAll('[data-view]');for(i=0;i<vb.length;i++)vb[i].className=(vb[i].getAttribute('data-view')===state.view?'is-active':'');var sb=$('scopeSwitch').querySelectorAll('[data-scope]');for(i=0;i<sb.length;i++)sb[i].className='toggle'+(sb[i].getAttribute('data-scope')===state.scope?' is-active':'');renderThumbs(a,it)}
function speak(){var it=item();if(!it||!state.speech)return;if(!window.speechSynthesis||typeof window.SpeechSynthesisUtterance==='undefined'){toast('الصوت غير متاح على هذا الجهاز حاليًا.');return}try{window.speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(it.ar);u.lang='ar-SA';u.rate=.78;window.speechSynthesis.speak(u)}catch(e){toast('تعذر تشغيل الصوت.')}}
function move(n){var a=collection();if(!a.length)return;state.index=(state.index+n+a.length)%a.length;render();if(state.speech)speak()}
function restart(){clearInterval(state.timer);state.timer=null;if(state.autoplay)state.timer=setInterval(function(){move(1)},state.speed)}
function bind(){$('prevBtn').onclick=function(){move(-1)};$('nextBtn').onclick=function(){move(1)};$('pictureButton').onclick=speak;$('stageSpeakBtn').onclick=speak;$('speakNowBtn').onclick=speak;$('speechToggle').onclick=function(){state.speech=!state.speech;render();if(state.speech)speak()};$('autoplayToggle').onclick=function(){state.autoplay=!state.autoplay;restart();render()};$('autoplaySpeed').onchange=function(){state.speed=parseInt(this.value,10)||4000;restart()};$('itemRange').oninput=function(){state.index=parseInt(this.value,10)||0;render();if(state.speech)speak()};$('mixedBtn').onclick=function(){state.view='all';state.scope='all';state.index=Math.floor(Math.random()*Math.max(collection().length,1));render();if(state.speech)speak()};$('fullscreenBtn').onclick=function(){var d=document.documentElement;if(d.requestFullscreen)d.requestFullscreen();else if(d.webkitRequestFullscreen)d.webkitRequestFullscreen()};var v=$('viewSwitch').querySelectorAll('[data-view]');for(var i=0;i<v.length;i++)v[i].onclick=function(){state.view=this.getAttribute('data-view');state.index=0;render()};var s=$('scopeSwitch').querySelectorAll('[data-scope]');for(i=0;i<s.length;i++)s[i].onclick=function(){state.scope=this.getAttribute('data-scope');state.index=0;render()};var st=$('stage');st.addEventListener('touchstart',function(e){state.touchX=e.changedTouches[0].clientX},false);st.addEventListener('touchend',function(e){var dx=e.changedTouches[0].clientX-state.touchX;if(Math.abs(dx)>45)move(dx>0?-1:1)},false)}
function init(){tryLoadFullData();bind();render();if((LEVELS['2']||[]).length===0)toast('تم تشغيل المستوى الأول بالوضع الاحتياطي. اضغط تحديث لتحميل بقية المستويات.')} 
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();