(function(){
'use strict';
var FALLBACK={"1":[["الأسرة","👪","أم|أب|طفل|ولد|بنت|أخ|أخت|جد|جدة|عائلة"],["الجسم","🙂","رأس|شعر|وجه|عين|أنف|فم|أذن|أسنان|لسان|يد|إصبع|قدم|بطن|ظهر"],["الملابس","👕","قميص|بنطال|فستان|حذاء|جورب|قبعة|جاكيت"],["غرفة الطفل","🧸","سرير|وسادة|بطانية|لعبة|دمية|كرة|كتاب|كرسي|طاولة|صندوق|باب|نافذة|مصباح"],["المنزل","🏠","بيت|غرفة|مطبخ|حمام|صالة|درج|مفتاح|جدار|أرض|سقف"],["المطبخ","🍽️","كوب|كأس|طبق|ملعقة|شوكة|سكين|قدر|إبريق|زجاجة|ثلاجة"],["الحمام","🛁","ماء|صابون|منشفة|فرشاة|معجون|مرآة"],["الطعام","🍲","خبز|أرز|بيض|جبن|حليب|ماء|عصير|كعك|بسكويت|شوربة"],["الفواكه","🍎","تفاح|موز|برتقال|عنب|فراولة|بطيخ|مانجو|تمر"],["الخضروات","🥕","طماطم|بطاطس|جزر|خيار|بصل|خس|فلفل"],["الحيوانات","🐾","قطة|كلب|طائر|سمكة|أرنب|دجاجة|بقرة|حصان|خروف|ماعز|أسد|فيل|قرد"],["الحشرات","🦋","نملة|نحلة|فراشة"],["وسائل النقل","🚗","سيارة|حافلة|شاحنة|دراجة|قطار|طائرة|سفينة|قارب"],["الطبيعة","🌞","شمس|قمر|نجم|سماء|سحابة|مطر|شجرة|زهرة|عشب|حجر|بحر"],["الألوان","🎨","أحمر|أزرق|أصفر|أخضر|أبيض|أسود"],["الأشكال","🔷","دائرة|مربع|مثلث|نجمة|قلب"],["الألعاب","🧩","كرة|مكعب|دمية|سيارة|بالون|أحجية|طبلة"],["أشياء يومية","👜","هاتف|ساعة|حقيبة|قلم|ورقة|كتاب|صورة|مفتاح|مظلة|نظارة"]]};
var LEVELS=window.APP360_LEVELS||FALLBACK;
var WORD_EMOJI=window.APP360_WORD_EMOJI||{};
var AUDIO_AR=window.APP360_AUDIO_MAP||{};
var AUDIO_AR_SENSE=window.APP360_AUDIO_SENSE_MAP||{};
var EN=window.APP360_EN||{categories:{},words:{}};
var AUDIO_EN=window.APP360_AUDIO_MAP_EN||{};
var WORD_IMAGES=window.APP360_WORD_IMAGE_MAP||{};
var WORD_IMAGE_BASE='assets/word-images/';
var SEP='\u0001';
var COLORS={'أحمر':'#ef4444','أزرق':'#3b82f6','أصفر':'#facc15','أخضر':'#22c55e','أبيض':'#ffffff','أسود':'#111827','برتقالي':'#f97316','بنفسجي':'#8b5cf6','وردي':'#ec4899','بني':'#92400e','رمادي':'#6b7280'};
var NUMBERS={'صفر':'0','واحد':'1','اثنان':'2','ثلاثة':'3','أربعة':'4','خمسة':'5','ستة':'6','سبعة':'7','ثمانية':'8','تسعة':'9','عشرة':'10'};
var UI={
 ar:{title:'كلماتي مع أشيائي',eyebrow:'مختبر التطبيق 360 · من عمر 2 إلى 5 سنوات',heroDesc:'مكتبة تعلم مصنفة عبر أربعة مستويات. اختر لغة العرض والصوت، ثم المستوى والتصنيف.',badgeLevels:'4 مستويات',badgeCategories:'تصنيفات كثيرة',badgeTouch:'تنقل بالسحب والأسهم',badgeAudio:'عرض ونطق عربي وإنجليزي',install:'⬇ تثبيت',update:'↻ تحديث',pill:'مستويات الكلمات',sectionTitle:'تعلّم الأشياء والأسماء بالتدرج',sectionDesc:'يمكن عرض العربية أو الإنجليزية أو اللغتين معًا، مع تحكم مستقل في لغة النطق.',byCategory:'حسب التصنيف',allView:'عرض عام',level:'المستوى',autoTitle:'الحركة التلقائية',autoDesc:'شغّل التنقل التلقائي داخل التصنيف الحالي أو في العرض العام.',autoOn:'تشغيل التنقل التلقائي',autoOff:'إيقاف التنقل التلقائي',fast:'سريع',medium:'متوسط',slow:'هادئ',audioTitle:'الصوت والنطق',audioDesc:'اختر العربية أو الإنجليزية أو اللغتين على التوالي. الإعداد الافتراضي يتبع لغة العرض.',audioOn:'الصوت مفعّل',audioOff:'الصوت متوقف',speakNow:'🔊 انطق الآن',scopeTitle:'نطاق الحركة',scopeDesc:'حدد هل الحركة داخل التصنيف الحالي أو بين جميع كلمات المستوى المختار.',scopeCurrent:'التصنيف الحالي',scopeAll:'كل كلمات المستوى',extraTitle:'خيارات إضافية',extraDesc:'منوّع يعرض كلمات من جميع التصنيفات، وملء الشاشة مناسب للتابلت.',fullscreen:'⛶ ملء الشاشة',mixed:'🎲 منوّع',speakWord:'🔊 انطق الكلمة',cardsTitle:'بطاقات سريعة من المسار الحالي',cardsDesc:'يعرض التطبيق نافذة من البطاقات القريبة لتخفيف الحمل على الأجهزة الضعيفة.',facSummary:'إرشاد مختصر للمرافق — اختياري',fac1t:'ابدأ بالأسهل',fac1:'في كل مستوى ابدأ بما هو مألوف جدًا للطفل ثم وسّع الكلمات لاحقًا.',fac2t:'استخدم الواقع',fac2:'إن وجد الشيء الحقيقي فأشِر إليه مع البطاقة بدل الاكتفاء بالشاشة.',fac3t:'لا تجعلها اختبارًا',fac3:'الهدف هو الفهم والإشارة والتسمية بلطف، لا الضغط على الطفل.',fac4t:'كرّر بهدوء',fac4:'التكرار القصير المنتظم أفضل من الجلسة الطويلة.',inside:'داخل التصنيف',allWords:'كل كلمات المستوى',manual:'يدوي',automatic:'تلقائي',category:'التصنيف',firstLevel:'ظهر أولًا في المستوى',audioUnavailable:'الصوت غير متاح على هذا الجهاز حاليًا.',englishLoading:'ملفات اللغة الإنجليزية لم تكتمل بعد. جرّب التحديث بعد قليل.'},
 en:{title:'My Words & Things',eyebrow:'App 360 Lab · Ages 2 to 5',heroDesc:'A four-level visual vocabulary library. Choose display and speech languages, then a level and category.',badgeLevels:'4 levels',badgeCategories:'Many categories',badgeTouch:'Swipe and arrow navigation',badgeAudio:'Arabic & English display and speech',install:'⬇ Install',update:'↻ Update',pill:'Vocabulary Levels',sectionTitle:'Learn things and names step by step',sectionDesc:'Show Arabic, English, or both together, with independent speech-language control.',byCategory:'By Category',allView:'All Words',level:'Level',autoTitle:'Automatic Navigation',autoDesc:'Move automatically inside the current category or across the full level.',autoOn:'Start Auto Play',autoOff:'Stop Auto Play',fast:'Fast',medium:'Medium',slow:'Slow',audioTitle:'Speech & Audio',audioDesc:'Choose Arabic, English, or both in sequence. By default speech follows the display language.',audioOn:'Audio On',audioOff:'Audio Off',speakNow:'🔊 Speak Now',scopeTitle:'Navigation Scope',scopeDesc:'Choose whether navigation stays in the current category or moves across the whole level.',scopeCurrent:'Current Category',scopeAll:'Whole Level',extraTitle:'More Options',extraDesc:'Mixed mode samples all categories, and full screen is useful on tablets.',fullscreen:'⛶ Full Screen',mixed:'🎲 Mixed',speakWord:'🔊 Speak Word',cardsTitle:'Quick Cards in This Path',cardsDesc:'A nearby window of cards is shown to keep older devices fast.',facSummary:'Short guide for the adult — optional',fac1t:'Start easy',fac1:'Begin with very familiar words, then expand gradually.',fac2t:'Use real objects',fac2:'When possible, point to the real object while showing the card.',fac3t:'Do not turn it into a test',fac3:'The goal is gentle understanding, pointing, and naming.',fac4t:'Repeat calmly',fac4:'Short regular repetition is better than a long session.',inside:'Inside Category',allWords:'Whole Level',manual:'Manual',automatic:'Auto',category:'Category',firstLevel:'First introduced in Level',audioUnavailable:'Audio is not available on this device right now.',englishLoading:'English vocabulary files are still loading. Please refresh shortly.'}
};
var state={level:1,display:'ar',voice:'ar',view:'category',category:'',scope:'current',index:0,speech:true,autoplay:false,speed:4000,timer:null,touchX:0};
var SETTINGS='app360:a1-first-words:viewer-v17';
var LEGACY_SETTINGS='app360:a1-first-words:viewer-v10';
var cache={},audioEl=null,speechSeq=0;
var $=function(id){return document.getElementById(id)};
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]})}
function slug(s){return String(s||'').replace(/\s+/g,'-').replace(/[^؀-ۿa-zA-Z0-9-]/g,'').replace(/-+/g,'-')}
function toast(s){var n=$('toast');if(!n)return;n.textContent=s;n.className='toast show';clearTimeout(toast.t);toast.t=setTimeout(function(){n.className='toast'},2600)}
function englishReady(){return EN&&EN.words&&Object.keys(EN.words).length>10}
function loadSettings(){try{var raw=localStorage.getItem(SETTINGS)||localStorage.getItem(LEGACY_SETTINGS)||'{}';var x=JSON.parse(raw);if(x.display)state.display=x.display;else if(x.lang)state.display=x.lang;if(x.voice)state.voice=x.voice;else state.voice=state.display;if(x.level)state.level=parseInt(x.level,10)||1;if(x.view)state.view=x.view;if(x.scope)state.scope=x.scope;if(x.category)state.category=x.category;if(typeof x.speech==='boolean')state.speech=x.speech;if(x.speed)state.speed=parseInt(x.speed,10)||4000}catch(e){}if((state.display==='en'||state.display==='both')&&!englishReady()){state.display='ar';state.voice='ar'}if((state.voice==='en'||state.voice==='both')&&!englishReady())state.voice='ar'}
function saveSettings(){try{localStorage.setItem(SETTINGS,JSON.stringify({display:state.display,voice:state.voice,level:state.level,view:state.view,scope:state.scope,category:state.category,speech:state.speech,speed:state.speed}))}catch(e){}}
function uiLang(){return state.display==='en'?'en':'ar'}
function tr(){return UI[uiLang()]||UI.ar}
function enWord(it){return EN.words&&EN.words[it.category_ar+SEP+it.ar]?EN.words[it.category_ar+SEP+it.ar]:it.ar}
function enCat(ar){return EN.categories&&EN.categories[ar]?EN.categories[ar]:ar}
function labelWord(it){if(state.display==='en')return enWord(it);if(state.display==='both')return it.ar+' / '+enWord(it);return it.ar}
function labelCat(ar){if(state.display==='en')return enCat(ar);if(state.display==='both')return ar+' / '+enCat(ar);return ar}
function wordHtml(it){if(state.display==='both')return '<span class="word-ar" lang="ar" dir="rtl">'+esc(it.ar)+'</span><span class="word-en" lang="en" dir="ltr">'+esc(enWord(it))+'</span>';if(state.display==='en')return '<span class="word-en" lang="en" dir="ltr">'+esc(enWord(it))+'</span>';return '<span class="word-ar" lang="ar" dir="rtl">'+esc(it.ar)+'</span>'}
function catHtml(ar){if(state.display==='both')return '<span lang="ar" dir="rtl">'+esc(ar)+'</span><span class="bilingual-sep"> / </span><span lang="en" dir="ltr">'+esc(enCat(ar))+'</span>';if(state.display==='en')return '<span lang="en" dir="ltr">'+esc(enCat(ar))+'</span>';return '<span lang="ar" dir="rtl">'+esc(ar)+'</span>'}
function build(level){if(cache[level])return cache[level];var cats=[],by={};for(var lv=1;lv<=level;lv++){var rows=LEVELS[String(lv)]||[];for(var i=0;i<rows.length;i++){var r=rows[i],name=r[0],em=r[1]||'🧠',words=String(r[2]||'').split('|'),c=by[name];if(!c){c={id:slug(name)||('cat-'+cats.length),name:name,emoji:em,items:[],seen:{}};by[name]=c;cats.push(c)}for(var j=0;j<words.length;j++){var w=String(words[j]||'').replace(/^\s+|\s+$/g,'');if(!w||c.seen[w])continue;c.seen[w]=1;c.items.push({ar:w,category:c.id,category_ar:name,emoji:em,level:lv})}}}for(var k=0;k<cats.length;k++)delete cats[k].seen;cache[level]=cats;return cats}
function cats(){var a=build(state.level);if(!state.category&&a[0])state.category=a[0].id;var ok=false;for(var i=0;i<a.length;i++)if(a[i].id===state.category)ok=true;if(!ok&&a[0])state.category=a[0].id;return a}
function currentCat(){var a=cats();for(var i=0;i<a.length;i++)if(a[i].id===state.category)return a[i];return a[0]||null}
function collection(){var a=cats(),out=[],i,j;if(state.view==='all'||state.scope==='all'){for(i=0;i<a.length;i++)for(j=0;j<a[i].items.length;j++)out.push(a[i].items[j]);return out}var c=currentCat();return c?c.items:[]}
function item(){var a=collection();if(!a.length)return null;if(state.index>=a.length)state.index=0;if(state.index<0)state.index=a.length-1;return a[state.index]}
function contextKey(it){return it.category_ar+SEP+it.ar}
function contextVisual(it){var k=contextKey(it);if(k==='الجسم'+SEP+'ظهر')return '<g><circle cx="400" cy="220" r="65" fill="#f4c6a5"/><path d="M285 310Q400 250 515 310L548 520H252Z" fill="#65b5d8" stroke="#17343a" stroke-width="14"/><path d="M400 300v195" stroke="#17343a" stroke-width="12" stroke-linecap="round"/><path d="M310 340Q400 385 490 340" fill="none" stroke="#ffffff" stroke-width="10" opacity=".8"/><path d="M285 320L210 455M515 320L590 455" stroke="#f4c6a5" stroke-width="34" stroke-linecap="round"/></g>';if(k==='الوقت'+SEP+'ظهر')return '<g><circle cx="400" cy="350" r="125" fill="#facc15"/><g stroke="#f59e0b" stroke-width="18" stroke-linecap="round"><path d="M400 145v70M400 485v70M195 350h70M535 350h70M255 205l48 48M497 447l48 48M545 205l-48 48M303 447l-48 48"/></g></g>';if((it.category_ar==='النباتات'||it.category_ar==='أجزاء النبات')&&it.ar==='ساق')return '<g><path d="M400 500V240" stroke="#3a9b50" stroke-width="34" stroke-linecap="round"/><path d="M395 330c-90-75-150-18-122 35 28 52 88 48 122 10z" fill="#65c96f"/><path d="M405 400c90-75 150-18 122 35-28 52-88 48-122 10z" fill="#7bd982"/></g>';if(it.category_ar==='الجسم'&&it.ar==='ساق')return '<g><path d="M340 190h120v200c0 50-10 92-28 145h-70c-18-53-22-95-22-145z" fill="#f4c6a5" stroke="#17343a" stroke-width="14"/><path d="M360 535h95" stroke="#17343a" stroke-width="25" stroke-linecap="round"/></g>';if((it.category_ar==='الحديقة'||it.category_ar==='النباتات'||it.category_ar==='أجزاء النبات')&&it.ar==='ورقة')return '<path d="M230 430C210 245 365 150 570 190c-24 202-160 330-340 240z" fill="#59bd65" stroke="#287a3b" stroke-width="14"/><path d="M270 420L525 220" stroke="#287a3b" stroke-width="14"/>';if((it.category_ar==='أشياء يومية'||it.category_ar==='أدوات الرسم')&&it.ar==='ورقة')return '<g><rect x="260" y="165" width="280" height="370" rx="16" fill="#fff" stroke="#17343a" stroke-width="14"/><path d="M315 255h170M315 315h170M315 375h130" stroke="#8bb8c0" stroke-width="12" stroke-linecap="round"/></g>';if(it.category_ar==='المنزل'&&it.ar==='أرض')return '<g><path d="M190 445h420v95H190z" fill="#c69b6d" stroke="#17343a" stroke-width="14"/><path d="M230 445v95M310 445v95M390 445v95M470 445v95M550 445v95" stroke="#9a734e" stroke-width="9"/></g>';if((it.category_ar==='السماء والفضاء'&&it.ar==='أرض')||(it.category_ar==='الفضاء'&&it.ar==='الأرض'))return '<g><circle cx="400" cy="350" r="170" fill="#4ea6e8" stroke="#17343a" stroke-width="14"/><path d="M275 270c40-80 120-72 145-24 28 55-35 70-8 115 25 40 80 22 110 62-45 62-120 92-190 70-70-22-115-82-110-145 4-42 20-60 53-78z" fill="#67c86b"/></g>';if(it.category_ar==='الرياضيات والأشكال'&&it.ar==='كرة')return '<g><defs><radialGradient id="sphere" cx="35%" cy="30%"><stop offset="0%" stop-color="#d7f4ff"/><stop offset="45%" stop-color="#67bde8"/><stop offset="100%" stop-color="#1c6fa4"/></radialGradient></defs><circle cx="400" cy="350" r="170" fill="url(#sphere)" stroke="#17343a" stroke-width="14"/></g>';return ''}
function visual(it){var special=contextVisual(it);if(special)return special;var w=it.ar,em=WORD_EMOJI[w]||it.emoji||'🧠';if(COLORS[w])return '<circle cx="400" cy="350" r="155" fill="'+COLORS[w]+'" stroke="#9ca3af" stroke-width="14"/>';if(NUMBERS[w])return '<text x="400" y="435" text-anchor="middle" font-family="Arial" font-size="280" font-weight="700" fill="#0f8f8a">'+NUMBERS[w]+'</text>';if(w==='دائرة')return '<circle cx="400" cy="350" r="150" fill="#67c9be"/>';if(w==='مربع')return '<rect x="250" y="200" width="300" height="300" fill="#f2c84b"/>';if(w==='مثلث')return '<path d="M400 170L580 500H220Z" fill="#f59e0b"/>';if(w==='نجمة')return '<text x="400" y="430" text-anchor="middle" font-size="250">⭐</text>';if(w==='قلب')return '<text x="400" y="430" text-anchor="middle" font-size="250">❤️</text>';return '<text x="400" y="430" text-anchor="middle" font-size="220">'+esc(em)+'</text>'}
function fallbackImage(it){var svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 800"><rect width="800" height="800" rx="54" fill="#eaf7f5"/><rect x="42" y="42" width="716" height="716" rx="46" fill="#fff"/><rect x="105" y="105" width="590" height="500" rx="38" fill="#f7fbfb"/>'+visual(it)+'</svg>';return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg)}
function image(it){var map=window.APP360_WORD_IMAGE_MAP||WORD_IMAGES;var file=map&&map[it.ar];if(file)return WORD_IMAGE_BASE+file;return fallbackImage(it)}
function applyLanguage(){var t=tr(),isEn=state.display==='en';document.documentElement.lang=isEn?'en':'ar';document.documentElement.dir=isEn?'ltr':'rtl';document.body.setAttribute('data-display-language',state.display);document.title=t.title+' | App 360';var nodes=document.querySelectorAll('[data-i18n]');for(var i=0;i<nodes.length;i++){var key=nodes[i].getAttribute('data-i18n');if(t[key]!=null)nodes[i].textContent=t[key]}var btns=$('languageSwitch').querySelectorAll('[data-lang]');for(i=0;i<btns.length;i++)btns[i].className=btns[i].getAttribute('data-lang')===state.display?'is-active':'';$('prevBtn').textContent=isEn?'‹':'›';$('nextBtn').textContent=isEn?'›':'‹'}
function renderLevels(){var h='';for(var i=1;i<=4;i++)h+='<button type="button" class="level-tab '+(state.level===i?'is-active':'')+'" data-level="'+i+'">'+i+'</button>';$('levelTabs').innerHTML=h;var b=$('levelTabs').querySelectorAll('[data-level]');for(var j=0;j<b.length;j++)b[j].onclick=function(){state.level=parseInt(this.getAttribute('data-level'),10)||1;state.index=0;state.category='';saveSettings();render();if(state.speech)speak()}}
function renderCats(){var a=cats(),h='';for(var i=0;i<a.length;i++)h+='<button type="button" class="category-chip '+(a[i].id===state.category?'is-active':'')+'" data-cat="'+esc(a[i].id)+'"><span class="chip-emoji">'+esc(a[i].emoji)+'</span> '+catHtml(a[i].name)+'</button>';$('categoryChips').innerHTML=h;var b=$('categoryChips').querySelectorAll('[data-cat]');for(var j=0;j<b.length;j++)b[j].onclick=function(){state.category=this.getAttribute('data-cat');state.view='category';state.index=0;saveSettings();render();if(state.speech)speak()}}
function renderThumbs(a){var start=Math.max(0,state.index-8),end=Math.min(a.length,start+20);if(end-start<20)start=Math.max(0,end-20);var h='';for(var i=start;i<end;i++)h+='<button type="button" class="thumb-card '+(i===state.index?'is-current':'')+'" data-i="'+i+'"><img src="'+image(a[i])+'" alt="'+esc(labelWord(a[i]))+'"><strong>'+wordHtml(a[i])+'</strong><small>'+catHtml(a[i].category_ar)+'</small></button>';$('thumbGrid').innerHTML=h;var b=$('thumbGrid').querySelectorAll('[data-i]');for(var j=0;j<b.length;j++)b[j].onclick=function(){state.index=parseInt(this.getAttribute('data-i'),10)||0;render();if(state.speech)speak()};if(state.display==='en')$('gridMeta').textContent='Showing '+(start+1)+'–'+end+' of '+a.length+' words.';else if(state.display==='both')$('gridMeta').textContent='يعرض '+(start+1)+'–'+end+' من أصل '+a.length+' كلمة / Showing '+(start+1)+'–'+end+' of '+a.length+' words.';else $('gridMeta').textContent='يعرض '+(start+1)+'–'+end+' من أصل '+a.length+' كلمة.'}
function renderVoice(){var vb=$('voiceSwitch').querySelectorAll('[data-voice]');for(var i=0;i<vb.length;i++)vb[i].className='voice-option'+(vb[i].getAttribute('data-voice')===state.voice?' is-active':'');$('voiceModeText').textContent=state.voice==='both'?'العربية ثم English':(state.voice==='en'?'English':'العربية')}
function render(){applyLanguage();renderLevels();renderCats();renderVoice();var t=tr(),ca=cats(),total=0;for(var i=0;i<ca.length;i++)total+=ca[i].items.length;if(state.display==='en'){$('levelTitle').textContent='Level '+state.level+' — Age '+(state.level+1);$('levelSummary').textContent=ca.length+' categories · '+total+' words'}else if(state.display==='both'){$('levelTitle').textContent='المستوى '+state.level+' — عمر '+(state.level+1)+' / Level '+state.level+' — Age '+(state.level+1);$('levelSummary').textContent=ca.length+' تصنيف · '+total+' كلمة / '+ca.length+' categories · '+total+' words'}else{$('levelTitle').textContent='المستوى '+state.level+' — عمر '+(state.level+1);$('levelSummary').textContent=ca.length+' تصنيف · '+total+' كلمة'}var a=collection(),it=item();if(!it)return;$('itemImage').src=image(it);$('itemImage').alt=labelWord(it);$('itemName').innerHTML=wordHtml(it);if(state.display==='both')$('itemHint').innerHTML='<span lang="ar" dir="rtl">التصنيف: '+esc(it.category_ar)+' · ظهر أولًا في المستوى '+it.level+'</span><span class="hint-divider"> / </span><span lang="en" dir="ltr">Category: '+esc(enCat(it.category_ar))+' · First introduced in Level '+it.level+'</span>';else $('itemHint').textContent=t.category+': '+labelCat(it.category_ar)+' · '+t.firstLevel+' '+it.level;$('levelTag').textContent=(state.display==='en'?'Level ':'المستوى ')+state.level;$('categoryTag').innerHTML='<span>'+esc(it.emoji)+'</span> '+catHtml(it.category_ar);$('scopeTag').textContent=(state.view==='all'||state.scope==='all')?t.allWords:t.inside;$('autoplayTag').textContent=state.autoplay?t.automatic:t.manual;$('itemRange').max=Math.max(0,a.length-1);$('itemRange').value=state.index;$('rangeLabel').textContent=(state.index+1)+' / '+a.length;if(state.display==='en')$('visibleCount').textContent=a.length+' '+(a.length===1?'word':'words');else if(state.display==='both')$('visibleCount').textContent=a.length+' كلمة / '+a.length+' words';else $('visibleCount').textContent=a.length+' كلمة';$('speechToggle').textContent=state.speech?t.audioOn:t.audioOff;$('speechToggle').className='toggle'+(state.speech?' is-active':'');$('autoplayToggle').textContent=state.autoplay?t.autoOff:t.autoOn;$('autoplayToggle').className='toggle'+(state.autoplay?' is-active':'');var sw=$('viewSwitch').querySelectorAll('[data-view]');for(i=0;i<sw.length;i++)sw[i].className=(sw[i].getAttribute('data-view')===state.view?'is-active':'');var sb=$('scopeSwitch').querySelectorAll('[data-scope]');for(i=0;i<sb.length;i++)sb[i].className='toggle'+(sb[i].getAttribute('data-scope')===state.scope?' is-active':'');renderThumbs(a)}
function stopAudio(){speechSeq++;try{if(audioEl){audioEl.pause();audioEl.currentTime=0;audioEl.onerror=null;audioEl.onended=null}}catch(e){}try{if(window.speechSynthesis)window.speechSynthesis.cancel()}catch(e){}}
function spokenText(it,lang){if(lang==='en')return enWord(it);var k=contextKey(it);if(k==='الجسم'+SEP+'ظهر')return 'ظَهْر';if(k==='الوقت'+SEP+'ظهر')return 'ظُهْر';return it.ar}
function audioPath(it,lang){if(lang==='en'){var e=enWord(it);return AUDIO_EN[e]||''}return AUDIO_AR_SENSE[contextKey(it)]||AUDIO_AR[it.ar]||''}
function ttsOne(it,lang,token,done){if(token!==speechSeq)return;if(!window.speechSynthesis||typeof window.SpeechSynthesisUtterance==='undefined'){done();return}try{var u=new SpeechSynthesisUtterance(spokenText(it,lang));u.lang=lang==='en'?'en-US':'ar-SA';u.rate=.78;var finished=false;var next=function(){if(finished)return;finished=true;if(token===speechSeq)done()};u.onend=next;u.onerror=next;window.speechSynthesis.speak(u)}catch(e){done()}}
function playOne(it,lang,token,done){if(token!==speechSeq)return;var src=audioPath(it,lang);if(!src){ttsOne(it,lang,token,done);return}try{if(!audioEl)audioEl=new Audio();var finished=false;var next=function(){if(finished)return;finished=true;if(token===speechSeq)done()};audioEl.onerror=function(){if(finished)return;finished=true;ttsOne(it,lang,token,done)};audioEl.onended=next;audioEl.src=src;if(audioEl.load)audioEl.load();var p=audioEl.play();if(p&&p.catch)p.catch(function(){if(finished)return;finished=true;ttsOne(it,lang,token,done)})}catch(e){ttsOne(it,lang,token,done)}}
function speak(){var it=item();if(!it||!state.speech)return;stopAudio();var token=speechSeq,langs=state.voice==='both'?['ar','en']:[state.voice==='en'?'en':'ar'],pos=0;function next(){if(token!==speechSeq)return;if(pos>=langs.length)return;playOne(it,langs[pos++],token,next)}next()}
function move(n){var a=collection();if(!a.length)return;state.index=(state.index+n+a.length)%a.length;render();if(state.speech)speak()}
function restart(){clearInterval(state.timer);state.timer=null;if(state.autoplay)state.timer=setInterval(function(){move(1)},state.speed)}
function setDisplay(mode){if((mode==='en'||mode==='both')&&!englishReady()){toast(UI.ar.englishLoading);return}state.display=mode;state.voice=mode;state.index=0;saveSettings();render();if(state.speech)speak()}
function setVoice(mode){if((mode==='en'||mode==='both')&&!englishReady()){toast(UI.ar.englishLoading);return}state.voice=mode;saveSettings();renderVoice();if(state.speech)speak()}
function bind(){var lb=$('languageSwitch').querySelectorAll('[data-lang]');for(var q=0;q<lb.length;q++)lb[q].onclick=function(){setDisplay(this.getAttribute('data-lang'))};var vs=$('voiceSwitch').querySelectorAll('[data-voice]');for(q=0;q<vs.length;q++)vs[q].onclick=function(){setVoice(this.getAttribute('data-voice'))};$('prevBtn').onclick=function(){move(-1)};$('nextBtn').onclick=function(){move(1)};$('pictureButton').onclick=speak;$('stageSpeakBtn').onclick=speak;$('speakNowBtn').onclick=speak;$('speechToggle').onclick=function(){state.speech=!state.speech;if(!state.speech)stopAudio();saveSettings();render();if(state.speech)speak()};$('autoplayToggle').onclick=function(){state.autoplay=!state.autoplay;restart();render()};$('autoplaySpeed').onchange=function(){state.speed=parseInt(this.value,10)||4000;saveSettings();restart()};$('itemRange').oninput=function(){state.index=parseInt(this.value,10)||0;render();if(state.speech)speak()};$('mixedBtn').onclick=function(){state.view='all';state.scope='all';state.index=Math.floor(Math.random()*Math.max(collection().length,1));saveSettings();render();if(state.speech)speak()};$('fullscreenBtn').onclick=function(){var d=document.documentElement;if(d.requestFullscreen)d.requestFullscreen();else if(d.webkitRequestFullscreen)d.webkitRequestFullscreen()};var v=$('viewSwitch').querySelectorAll('[data-view]');for(var i=0;i<v.length;i++)v[i].onclick=function(){state.view=this.getAttribute('data-view');state.index=0;saveSettings();render();if(state.speech)speak()};var s=$('scopeSwitch').querySelectorAll('[data-scope]');for(i=0;i<s.length;i++)s[i].onclick=function(){state.scope=this.getAttribute('data-scope');state.index=0;saveSettings();render();if(state.speech)speak()};var st=$('stage');st.addEventListener('touchstart',function(e){state.touchX=e.changedTouches[0].clientX},{passive:true});st.addEventListener('touchend',function(e){var dx=e.changedTouches[0].clientX-state.touchX;if(Math.abs(dx)<45)return;if(dx>0)move(-1);else move(1)},{passive:true});document.addEventListener('keydown',function(e){if(e.target&&/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;var en=state.display==='en';if(e.key==='ArrowLeft')move(en?-1:1);else if(e.key==='ArrowRight')move(en?1:-1)})}
function init(){loadSettings();bind();$('autoplaySpeed').value=String(state.speed);render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
