var CACHE='app360-app-say-and-name-v18';
var SHELL=["./","./index.html","./styles-v18.css?v=18","./runtime-v18.js?v=18","./data/levels-inline-v8.js?v=18","./data/visuals.js?v=18","./data/audio-map.js?v=18","./data/audio-sense-map.js?v=18","./data/translations-en.js?v=18","./data/audio-map-en.js?v=18","./data/word-images-map.js?v=18","./manifest.webmanifest?v=18","./icon.svg?v=18","./app.json","../../../assets/js/app-pwa.js?v=1"];
self.addEventListener('install',function(e){e.waitUntil(caches.open(CACHE).then(function(c){return Promise.all(SHELL.map(function(u){return c.add(u).catch(function(){return null})}))}));if(self.skipWaiting)self.skipWaiting()});
self.addEventListener('activate',function(e){e.waitUntil(caches.keys().then(function(keys){return Promise.all(keys.map(function(k){if(k.indexOf('app360-app-say-and-name-')===0&&k!==CACHE)return caches.delete(k)}))}).then(function(){return self.clients&&self.clients.claim?self.clients.claim():null}))});
self.addEventListener('message',function(e){if(e.data&&e.data.type==='SKIP_WAITING'&&self.skipWaiting)self.skipWaiting()});
function same(req){try{return new URL(req.url).origin===self.location.origin}catch(e){return false}}
function fresh(req){return fetch(req,{cache:'no-store'}).then(function(r){if(r&&r.ok&&same(req)){var x=r.clone();caches.open(CACHE).then(function(c){c.put(req,x)})}return r}).catch(function(){return caches.match(req).then(function(x){return x||caches.match('./index.html')})})}
function cached(req){return caches.match(req).then(function(x){return x||fetch(req).then(function(r){if(r&&r.ok&&same(req)){var y=r.clone();caches.open(CACHE).then(function(c){c.put(req,y)})}return r})})}
self.addEventListener('fetch',function(e){if(!e.request||e.request.method!=='GET'||!same(e.request))return;var u='';try{u=new URL(e.request.url).pathname}catch(x){}if(e.request.mode==='navigate'||/\.(?:html|json|js|css)$/.test(u)){e.respondWith(fresh(e.request));return}e.respondWith(cached(e.request))});
