(function(w){'use strict';var stages=['intro','needA','needB','solutions','agree','trial','review'];
function copy(x){return JSON.parse(JSON.stringify(x));}function fail(s){throw Error(s);}function text(x,n){return typeof x==='string'&&x.length<=n;}
var situationTracks={"same-truck": "entry", "red-pencil": "entry", "ball-pass": "entry", "book-choice": "entry", "tidy-toys": "entry", "block-bridge": "practice", "shop-roles": "practice", "picture-space": "practice", "quiet-loud": "practice", "puppet-story": "practice", "group-game": "extend", "team-map": "extend", "fair-materials": "extend", "change-rule": "extend", "team-cleanup": "extend"};function fresh(profile,track,situation){if(['entry','practice','extend'].indexOf(track)<0)fail('track');situation=situation||'same-truck';if(!situationTracks[situation]||situation!=='same-truck'&&situationTracks[situation]!==track)fail('situation');return {schema_version:1,profile_ref:profile,session_id:'coop-'+Date.now()+'-'+Math.random().toString(36).slice(2,8),situation_id:situation,readiness_track:track,step:'intro',state:'in_progress',reached:0,heard:{needA:false,needB:false},explored:{turns:false,together:false},selected_plan:'',agreed_rule:'',consent:[false,false,false],participants:2,trial_done:false,reflection:'',trial_note:'',coach_note:'',assistance_level:'with-adult',revisions:0,attempt_history:[]};}
function record(d,type){d.attempt_history.push({type:type,step:d.step,at:Date.now()});if(d.attempt_history.length>40)d.attempt_history.shift();}
function go(d,step){var index=stages.indexOf(step);if(index<0||index>d.reached)fail('stage');if(index>=5){if(!d.agreed_rule.trim()||!d.selected_plan)fail('rule');for(var n=0;n<d.participants;n++)if(!d.consent[n])fail('consent');}if(index>=6&&!d.trial_done)fail('trial');d.step=step;d.state='in_progress';return d;}
function next(d){var i=stages.indexOf(d.step);if(d.step==='needA'&&!d.heard.needA||d.step==='needB'&&!d.heard.needB)fail('listen');if(d.step==='solutions'){if(!d.selected_plan)fail('plan');if(d.readiness_track!=='entry'&&(!d.explored.turns||!d.explored.together))fail('both');}if(d.step==='agree'){if(!d.agreed_rule.trim())fail('rule');for(var n=0;n<d.participants;n++)if(!d.consent[n])fail('consent');}if(d.step==='trial'&&!d.trial_done)fail('trial');if(i>=stages.length-1)fail('end');d.step=stages[i+1];d.reached=Math.max(d.reached,i+1);d.state=d.step==='review'?'review':'in_progress';record(d,'next');return d;}
function select(d,plan){if(['turns','together'].indexOf(plan)<0)fail('plan');if(d.selected_plan!==plan){d.selected_plan=plan;d.reached=Math.min(d.reached,3);d.agreed_rule='';d.consent=[false,false,false];d.trial_done=false;d.reflection='';}record(d,'select-'+plan);}
function revise(d){if(d.step!=='review')fail('stage');record(d,'revise');d.revisions++;d.step='solutions';d.reached=3;d.consent=[false,false,false];d.trial_done=false;d.reflection='';d.state='in_progress';}
function finish(d){if(d.step!=='review'||!d.trial_done||!d.selected_plan||!d.agreed_rule.trim()||!d.heard.needA||!d.heard.needB||['worked','adjust','stopped'].indexOf(d.reflection)<0)fail('reflection');for(var n=0;n<d.participants;n++)if(!d.consent[n])fail('consent');d.state='saved';record(d,'saved');return copy(d);}
function validate(d,profile){if(!d||d.schema_version!==1||d.profile_ref!==profile||!text(d.session_id,120)||(!situationTracks[d.situation_id]||d.situation_id!=='same-truck'&&situationTracks[d.situation_id]!==d.readiness_track)||['entry','practice','extend'].indexOf(d.readiness_track)<0||stages.indexOf(d.step)<0||['in_progress','review','paused','needs_help','saved'].indexOf(d.state)<0||typeof d.reached!=='number'||d.reached%1||d.reached<stages.indexOf(d.step)||d.reached>6)fail('draft');if(!d.heard||!d.explored||typeof d.heard.needA!=='boolean'||typeof d.heard.needB!=='boolean'||typeof d.explored.turns!=='boolean'||typeof d.explored.together!=='boolean')fail('choices');if(['','turns','together'].indexOf(d.selected_plan)<0||!text(d.agreed_rule,400)||!text(d.trial_note,600)||!text(d.coach_note,600)||['','worked','adjust','stopped'].indexOf(d.reflection)<0||typeof d.trial_done!=='boolean'||[2,3].indexOf(d.participants)<0||d.participants===3&&d.readiness_track!=='extend'||!Array.isArray(d.consent)||d.consent.length!==3||d.consent.some(function(x){return typeof x!=='boolean';})||!Array.isArray(d.attempt_history)||d.attempt_history.length>40||['with-adult','pointing','independent'].indexOf(d.assistance_level)<0||typeof d.revisions!=='number'||d.revisions<0||d.revisions>100)fail('fields');if(d.state==='saved'){var c=copy(d);c.step='review';finish(c);}return copy(d);}
function exported(db){var items=db.gallery.map(function(d){var c=copy(d);delete c.profile_ref;delete c.coach_note;delete c.attempt_history;return c;});return {schema_version:1,app_id:'a4-cooperate',agreements:items};}
w.COOP_MODEL={fresh:fresh,copy:copy,go:go,next:next,select:select,revise:revise,finish:finish,validate:validate,record:record,exported:exported,stages:stages};if(typeof module!=='undefined')module.exports=w.COOP_MODEL;
})(typeof window!=='undefined'?window:globalThis);
